### ISSUE TITLE
Window resizing causes event processing to block

### ISSUE THREAD

**Issue by tmpvar** [glfw/glfw#1]
This can be seen on the demos as well. 

![Boing.app screenshot](https://f.cloud.github.com/assets/46673/404450/ad0cd11c-a948-11e2-9272-0df26256ec16.png)

**Comment by TuomLarsen** [comment]
I'm having this problem, too. I tried to asked in the forum ("Resize callback stall") first but I then found this issue. You mentioned here, and in #185, that one can try to "use the window size or refresh callbacks to update the contents of a window during resize". Could you please show how exactly do this, in an example perhaps?

BTW, I tried to subclass NSOpenGLView and it redraws even during resizing. This is how the it looks like:

    - reshape(void) {
        NSSize size = [self.window.contentView frame].size;
        glViewport(0, 0, size.width, size.height);
    }

Apple also provides "GLEssentials" example which works in this regard, too.

**Comment by shurcooL** [comment]
Also a duplicate of #408.
