### ISSUE TITLE
Initialization fails on Xdummy

### ISSUE THREAD

**Issue by philbinj** [glfw/glfw#1004]
We are using GLFW to render some graphics to an off-stream buffer for a server process (ec2 GPU-less instance). The graphics are very simple (basically 2-D geometry overlays), so GPU-acceleration is not really needed.

I followed the guidelines for installing Xdummy here: https://xpra.org/trac/wiki/Xdummy

I do end up getting an xserver which produces something reasonable when I run:
$ DISPLAY=:100 glxinfo

However, my server code fails when trying to call `glfwInit`:
65544 : 'X11: RandR gamma ramp support seems broken'
65542 : 'EGL: Failed to load EGL'

Is headless rendering expected to be possible, and if so, how can I get it to work?

**Comment by elmindreda** [comment]
Headless should work just fine as long as there's an X server running.

What version of GLFW are you using?

**Comment by qiukeren** [comment]
+1 but i am using it on ssh x11 forwarding so you can ignore me.

People seldom want to use it on x11 forwarding.

**Comment by qianyizh** [comment]
Just want to chip in. I have the same problem.
I think the main issue is that Ubuntu 16.04 apt-get installs a old version of glfw3 (3.1.2).
I have checked the code. I am pretty sure it has been fixed in the current release.
But Ubuntu apt-get is really out dated.

My glfw version is (installed via apt-get):
```
libglfw3 is already the newest version (3.1.2-3).
libglfw3-dev is already the newest version (3.1.2-3).
```
With python binding (installed via pip):
```
glfw                               1.4.0    
```

My environment is:
Headless rendering on a server with NVidia graphcis cards. I used this to config Xorg.
```
sudo nvidia-xconfig -a --use-display-device=none
```
This gives reasonable output:
```
DISPLAY=:0 glxinfo | grep OpenGL
```
But glfw breaks with:
```
glfw.GLFWError: (65544) b'X11: RandR gamma ramp support seems broken'
```

**Comment by qianyizh** [comment]
There is a very complicated and painful workaround. The idea is to use VirtualGL and TurboVNC to mock a display.

First, install VirtualGL and TurboVNC, something like:
```
sudo dpkg -i virtualgl_xxx.deb
sudo dpkg -i turbovnc_xxx.deb
```

Then launch vnc server to run glfw.
```
sudo service lightdm stop
sudo nohup Xorg :0 &
/opt/TurboVNC/bin/vncserver :1
export DISPLAY=:1
vglrun -d :0.0 glxinfo
vglrun -d :0.0 <a script that calls glfw>
```

But this workaround is so painful. I am trying to install a newer version of glfw on Ubuntu. This is probably also related to #808

**Comment by xCuri0** [comment]
@qianyizh why not just build it from source

**Comment by qianyizh** [comment]
Have tried to compile GLFW from source.
The stable release version 3.2.1 has the same problem.
But the current dev version (cloned from github) works well.

**Comment by xCuri0** [comment]
@qianyizh Then this issue can be closed

**Comment by qianyizh** [comment]
@xCuri0 I have no problem. If PO @philbinj sees fine too then this issue can be closed.

**Comment by VGAstudent** [comment]
Does this mean that GLFW3.2+ compiles from source with no problem? I would like to know how to compile GLFW3.2+ in Linux Mint 18.3. I have downloaded the files as a package, but I'm currently trying to put the install files in a place where all the users on my computer can get to them? (I'm new to compiling my kernel, but I would like to know how to keep this process as straight-forward as possible, lacking any desire to be totally internet dependent on a compiling process that may need to be isolated) I'd like to know where to look for this information for my own documentation. I'd like to make a company manual on the subject.

Thank you for your consideration and assistance.

**Comment by tombsar** [comment]
@VGAstudent GLFW This issue is a specific case where glfw compiles, but fails to run on headless systems (without screens attached).

For generic information on how to compile, see the website: http://www.glfw.org/docs/latest/compile_guide.html

If you have any specific questions, please direct them to the forums: http://discourse.glfw.org/

**Comment by VGAstudent** [comment]
Thank you, and yes, I do plan on trying to start graphics in headless processes, using a codeblocks environment to code in. I just finished compiling the glfw3 without error...   ...so I will assume this is working good so far. If I do have this error where it breaks when displaying, I will consult this article in depth. Thank you for mentioning the workaround!
