### ISSUE TITLE
Memory leak in XkbGetMap

### ISSUE THREAD

**Issue by R-Kapp** [glfw/glfw#1007]
I have seen #693 and #662, but I still see the same memory leak when using OpenGL 4.5. I'm unsure if I'm doing something wrong...

**Comment by elmindreda** [comment]
What version of GLFW are you using?

**Comment by R-Kapp** [comment]
I was using 3.2.0 - in between posting this bug and now, I tried using 3.2.1 (hadn't realized it was out yet) and the error went away. My mistake in reading which version the fix went in apparently - apologies.

**Comment by elmindreda** [comment]
No worries. Thank you for the follow-up.
