### ISSUE TITLE
Analog joystick buttons

### ISSUE THREAD

**Issue by satoshinm** [glfw/glfw#1008]
I'd like to request support for reading the analog value of buttons on joysticks, if the hardware supports it (couldn't find any existing issue for this feature request). [`glfwGetJoystickButtons`](http://www.glfw.org/docs/latest/input_guide.html#joystick_button) only returns an `unsigned char *` of `GLFW_PRESS` or `GLFW_RELEASE`, i.e., the digital value, but some joysticks support analog as well: a floating-point value from 0.0 to 1.0. Also a `touched` boolean if the value is >0, in addition to the usual `pressed` boolean if the value is 1.

For comparison, the HTML5 Gamepad API: https://w3c.github.io/gamepad/#gamepadbutton-interface

> **value**
> For buttons that have an analog sensor, this property must represent the amount which the button has been pressed. All button values must be linearly normalized to the range [0.0 .. 1.0]. 0.0 must mean fully unpressed, and 1.0 must mean fully pressed. For buttons without an analog sensor, only the values 0.0 and 1.0 for fully unpressed and fully pressed must be provided.

(This could be useful in the web-based emscripten port of glfw, too, after https://github.com/kripken/emscripten/pull/5175 Implement glfw joystick API)

**Comment by elmindreda** [comment]
As far as I know, none of the APIs GLFW uses provides analog buttons. Such elements, for example gamepad triggers, are exposed as axes.

**Comment by elmindreda** [comment]
This isn't what you asked for, but it's somewhat related.

The new [gamepad functions](http://www.glfw.org/docs/3.3/input_guide.html#gamepad) should map fairly closely to the W3 gamepad API. The buttons that are digital in the GLFW interface should mapped to digital hardware buttons in the W3 one as well on most devices.

**Comment by elmindreda** [comment]
I don't think GLFW is going to get closer to the W3 gamepad API than this. Is it okay to close this issue?
