### ISSUE TITLE
Resizing "splitview" example causes application to become unresponsive

### ISSUE THREAD

**Issue by TheMrMilchmann** [glfw/glfw#1014]
OS and version: Windows 10 x64
GPU and driver: NVIDIA GeForce GTX 1070/PCIe/SSE2 (382.05, also occured on 376.53)
Commit: current master (2f5e2303380d084ab9b097765d34f98504324d65)
NVIDIA Thread Optimization is turned off

While resizing the window (in both directions) the application suddenly becomes unresponsive. This is 100% reproducable on my PC. A few notes on the behaviour:
- The issue does occur while the mouse button is still being hold down.
- The issue does only seem to occur whenever the window is first made bigger and then smaller, or smaller and then bigger, during one resize operation (= the mouse button is not released).
- The issue does occur no matter which core of the window I grab.
- The issue does not always occur when I move the window to another position. (However, I did not recognize a pattern.)

I also made a small screencap which can be found [here](https://youtu.be/QF6uKxVEaEU).

The issue does seem to be related to the refresh callback. More specifically it does not occur when `glfwSwapBuffers` is commented out.

**Comment by elmindreda** [comment]
Cannot reproduce on Windows 10 x64, NVIDIA GeForce G 105M (342.01) with Threaded Optimization turned off.

What is the call stack of the crash?

**Comment by TheMrMilchmann** [comment]
I have uploaded the call stack to [Gist](https://gist.github.com/TheMrMilchmann/ff4b440f42149ee8d6873e854a101dcf) because of its length.

I rarely work with C and originally noticed this behaviour in a LWJGL demo. However, the crash is reproducable using the splitview example (at least on my system). I hope that this stack provides you with sufficient information but in case it does not I probably need more detailed guidance on how to continue.

**Comment by elmindreda** [comment]
Thank you!

That looks like a possible driver bug.

**Comment by TheMrMilchmann** [comment]
Recently my PC crashed on me multiple times due to a Windows error and just to be safe I did a full new install. I'm still using excactly the same software (and versions) and hardware but I cannot reproduce the issue anymore.

I assume that the issue was caused by a faulty driver install that I never noticed.
