### ISSUE TITLE
GLFW interferes with stdin before (and after) glfwInit() is called

### ISSUE THREAD

**Issue by mohawkjohn** [glfw/glfw#1017]
I'm trying to read a bunch of different commands from stdin, then run `glfwInit()` and render according to the commands. Unfortunately, it seems like GLFW is converting my `\n` keypresses into `\r` (in Linux), and then requiring me to hit `^D`. As a result, code like this doesn't work:

```
std::cin >> w;
std::cin >> x;
std::cin >> y;
std::cin >> z;
std::cerr << "Read in a quaternion!" << std::endl;
```

It doesn't matter where I put it in the program. If I instead put it in a function which takes an `std::istream`, I get the same behavior — until I pass it an `ifstream` I've opened instead, then it works as expected.

I'm on Ubuntu, using libglfw3-dev 3.1.2-3. I have not checked to see if this issue still exists in the current build, but I've Googled extensively, and don't think anyone else has reported this behavior.

[Here is a more complete description.](http://stackoverflow.com/questions/44006810/in-glfw-app-stdcin-behaves-oddly?noredirect=1#comment75042757_44006810)

**Comment by tombsar** [comment]
That is certainly strange behaviour, and I can't think of anything that would cause it.

Are you able to verify that your program works as expected when glfw is removed? If that is problematic, does the following snippet show the same problem?

```C++
#include <iostream>
#include <GLFW/glfw3.h>

int main (void) {
    double x;
    std::cin >> x;
    std::cout << x << std::endl;
#if 0
    glfwInit();
    glfwTerminate();
#endif
}
```

**Comment by jcowgill** [comment]
Do you have your terminal setup correctly?
What is the output of `stty -a`?
Does it work if you run `stty sane` in your terminal just before running your GLFW program?

**Comment by mohawkjohn** [comment]
```
$ stty -a
speed 38400 baud; rows 44; columns 149; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = M-^?; eol2 = M-^?; swtch = M-^?; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
werase = ^W; lnext = <undef>; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 hupcl -cstopb cread -clocal -crtscts
-ignbrk brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr -icrnl ixon -ixoff -iuclc ixany imaxbel iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc
```

And it *does* work when I run `stty sane`. Wow! What is this and how have I never heard of it? How did it get like this?

**Comment by jcowgill** [comment]
> `-icrnl`

This is the bad option here. The `icrnl` option tells the tty driver to convert carriage returns from your keyboard into line feeds, but it seems to be disable. You could check your `.bashrc` or it might have been set by your terminal emulator (or anything else which ran in that terminal session).

**Comment by mohawkjohn** [comment]
Thank you all so much for the help! I really appreciate it.
