### ISSUE TITLE
glfwDestroyWindow crash related to autorelease pool

### ISSUE THREAD

**Issue by datait1407** [glfw/glfw#1018]
I  create hidden windows for offscreen rendering in separate threads and call glfwDestroyWindow when the threads exit. It works well with glfw 3.1.2 but crash occurs if I use glfw 3.2.1. I found function _glfwPlatformDestroyWindow  added [_glfw.ns.autoreleasePool drain] for fixing issue #721.  If I comment two lines: [_glfw.ns.autoreleasePool drain];_glfw.ns.autoreleasePool = [[NSAutoreleasePool alloc] init]; and rebuild glfw, it works well but I have memory leaks.  
My code is something like that: 
```c
my_thread() {
glfwWindowHint(GLFW_VISIBLE, GL_FALSE);
GLFWwindow *window = glfwCreateWindow(1, 1, "", NULL, NULL);
if (!window) return;
glfwMakeContextCurrent(window);
GLenum err = glewInit();
 if (GLEW_OK != err) return;
fprintf(stdout, "Status: Using GLEW %s\n", glewGetString(GLEW_VERSION));
fprintf(stdout, "Status: Using GLFW %s\n", glfwGetVersionString());

//Do something here but i comment all
//....

//call destroy window 
glfwMakeContextCurrent(NULL);
glfwDestroyWindow(window);
}
```
Output: 
```
Status: Using GLEW 1.12.0
Status: Using GLFW 3.2.1 Cocoa NSGL chdir retina dynamic
```
Crash log:
```
C  [CoreFoundation+0x38102]  _CFAutoreleasePoolPop+0x32
C  [Foundation+0x1fcb6]  -[NSAutoreleasePool drain]+0x99
C  [libglfw3.3.dylib+0xc077]  _glfwPlatformDestroyWindow+0xde
C  [libglfw3.3.dylib+0x758e]  glfwDestroyWindow+0xe0
```
My OSX versions is 10.11

**Comment by elmindreda** [comment]
You [may not](http://www.glfw.org/docs/latest/intro_guide.html#thread_safety) create or destroy windows in threads other than the main thread.

**Comment by datait1407** [comment]
What is the diffecrence between the main thread and others? 

For some reasons, i can't create windows in main thread. As I described above, I create a window and use only within the thread created it and I don't share its context between threads.

**Comment by elmindreda** [comment]
> What is the diffecrence between the main thread and others?

Most of AppKit isn't thread safe and the main thread's event queue is special as well. There are somewhat poorly documented exceptions, but full window creation isn't among them.

These limitations in macOS is a major reason for the corresponding limitations in GLFW, to keep code from other platforms portable to macOS.
