### ISSUE TITLE
Calling GLFW window by system keys.

### ISSUE THREAD

**Issue by openGLnoob** [glfw/glfw#1022]
Interesting, is there a way calling GLFW window from tray or unfolded and make it active by pressing system keys, Home or End for example? I want to implement it for my small screenshot app. App starts by autoload and waiting his own keys.

**Comment by Playermet** [comment]
You need to use global hotkeys, GLFW currently don't support this. Example how to make it on windows - [RegisterHotKey](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646309(v=vs.85).aspx).

**Comment by openGLnoob** [comment]
Sad to hear that. But thanks for advice!
