### ISSUE TITLE
GLFWimage under-documented

### ISSUE THREAD

**Issue by genpfault** [glfw/glfw#1027]
http://www.glfw.org/docs/latest/structGLFWimage.html

GLFWimage::pixels is documented as:

"The pixel data of this image, arranged left-to-right, top-to-bottom."

This gives no indication of the number of color channel components or their layout (RGB or BGR?  Alpha?)

**Comment by elmindreda** [comment]
Seems it's missing from the documentation of both GLFWimage and glfwSetWindowIcon.

Thanks!

**Comment by shurcooL** [comment]
For posterity, this was also related to #426.
