### ISSUE TITLE
new idea for a key/scancode descriptor function - glfwGetKeyDescriptor(int key, int scancode)

### ISSUE THREAD

**Issue by donington** [glfw/glfw#1029]
I've been playing with the latest GLFW in my spare time, even moving to the master here on github to get fixes post 3.2.1.  I love how far this project has come since the 2.x days and am having a good time with it.  That being said, I ran into something that I feel I should bring up.

I was preparing to make a key binding UI of some sort, and completely misunderstood the concept of glfwGetKeyName - thinking it was going to give me a description of the key and not a human readable symbol representing the key in the current locale or nothing at all.  For key binding feedback to the user this works fine for any printable key, but becomes useless for keys like Escape, Enter, etc since they all return NULL.  I can see why glfwGetKeyName is a useful idea but it wasn't what I was looking for.

I'm developing on Ubuntu currently, and I was able to come up with this nifty little function for the X11 side of things:

```c
const char* _glfwPlatformGetKeyDescriptor(int key, int scancode)
{
    if (!_glfw.x11.xkb.available)
        return NULL;

    if (key != GLFW_KEY_UNKNOWN)
        scancode = _glfw.x11.scancodes[key];

    const KeySym keysym = XkbKeycodeToKeysym(_glfw.x11.display, scancode, 0, 0);
    if (keysym == NoSymbol)
        return NULL;

    char* keyname = XKeysymToString(keysym);
    if ( keyname == NULL )
      return NULL;

    return keyname;
}
```

This returns a static char* to a human readable name for a given keysym (eg: 's', 'H', 'space', 'Return', 'Alt_L').  This would be very useful for reporting the active key bindings back to the user in a human readable format.

I'm not sure if Windows or OSX provide a function similar to XKeysymToString, but if they do I think this would be a great quality of life improvement for developers and end users.  If they don't, then this probably wouldn't be worth implementing.

Any thoughts?  Thanks for taking the time to read this.

*edit*

I don't have access to a Windows build environment to test right now, but GetKeyNameTextA appears to be able to provide names for scancodes.  For reference later if I get around to (or somebody beats me to) implementing it:

https://msdn.microsoft.com/en-us/library/windows/desktop/ms646300(v=vs.85).aspx
https://cboard.cprogramming.com/windows-programming/56115-getkeynametext-api-buggy-me.html

Not sure where to start with something like this for OSX sadly.

**Comment by elmindreda** [comment]
Since support for non-printable keys is so varied across platforms (human-readable uppercase strings localized to the keyboard language on Win32, not-terribly-human-readable mixed case strings on X11, nothing at all on macOS as far as I know) it would have to be a string table built into GLFW to be consistent.

Perhaps this's something worth adding, for the benefit of applications that are hard-coded to English. It's can be done [outside of GLFW](https://github.com/glfw/glfw/blob/master/tests/events.c#L64), though.

**Comment by donington** [comment]
I agree the platform inconsistencies kind of make it not worthwhile relying on them for the information.  I was hoping there was a sane way to convert the codes based off the locale, but of course the concept of a locale differs from system to system.

It really isn't very hard to build a table of strings, you're right.  And then people can tune for localization if it's available in their code base.  This is pretty insignificant since it's so easy to work around.  Thanks for the feedback.
