### ISSUE TITLE
Packaging glfw with conan

### ISSUE THREAD

**Issue by dimi309** [glfw/glfw#1034]
Hello,

I've been using glfw for a while. Recently, I have packaged it with conan, an open source C/C++ package manager and placed the package on bintray:

https://bintray.com/dimi309/conan-packages/glfw%3Adimi309

I hope you don't mind :)

The package is in the process of being evaluated for inclusion into a curated repository on bintray, which is to only contain good quality conan packages. I am writing to ask you if you would be interested in maintaining this package directly. I can provide you with the packaging code (actually, you can just copy it, since it's open source) or even introduce a pull request with some non-intrusive changes that would allow you to package it directly from the main glfw repository.

**Comment by elmindreda** [comment]
> I hope you don't mind :)

Not at all; it's great!

I personally don't have time to maintain an external package, but suggest you leave this open and hopefully someone will volunteer.

**Comment by dimi309** [comment]
Thank you very much for your reply! Yes, I'll just leave this here and see if there is any interest. I don't mind maintaining the package myself. I was just wondering if someone involved with its development may be better at it that I am 😄

**Comment by p-groarke** [comment]
Any chance you create an org on conan-center to get an official package? Great work!

**Comment by dimi309** [comment]
Thank you @p-groarke 
As a matter of fact, I have just joined bincrafters (https://github.com/bincrafters) and will put the package into their collection. It is almost ready with all the necessary improvements. So that should be done in a couple of days. I don't know how long it will take but the conan team has said that it is faster to get packages on conan center when going through bincrafters, so I hope that it will be accepted there also, soon. I had already applied directly for admission of glfw to conan center but I suppose the team hasn't had time to review the package yet.

**Comment by p-groarke** [comment]
@dimi309 That is awesome news! I'll keep an eye out :) Your work is really appreciated.

**Comment by dimi309** [comment]
Thanks again!

**Comment by dimi309** [comment]
As discussed, the conan GLFW package is now available on the [Bincrafters ](https://bincrafters.github.io/) bintray repository: https://bintray.com/bincrafters/public-conan/glfw%3Abincrafters
We'll be maintaining the code under Bincrafters on GitHub from now on: https://github.com/bincrafters/conan-glfw

**Comment by dimi309** [comment]
Closing issue, since it has been a while that the glfw package is managed well by the bincrafters team.
