### ISSUE TITLE
cygwin build with dll fails to put cygglfw-3.dll in the appropriate bin directory

### ISSUE THREAD

**Issue by devel-chm** [glfw/glfw#1035]
I don't know if this is a problem with the GLFW use of cmake or with cmake itself but the cygglfw-3.dll file should be installed into  CMAKE_INSTALL_PREFIX/bin and not CMAKE_INSTALL_PREFIX/lib.

This is for a cygwin/win7 system with uname -a:
CYGWIN_NT-6.1 glfwtest 2.6.0(0.304/5/3) 2016-08-31 14:32 x86_64 Cygwin

and cmake --version 3.6.2 and here is the cmake configure process output:
>  cmake -DCMAKE_INSTALL_PREFIX=/usr/local64/glfw_so/ -DBUILD_SHARED_LIBS=ON ../glfw/
-- The C compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Could NOT find Vulkan (missing:  VULKAN_LIBRARY VULKAN_INCLUDE_DIR) 
-- Found Doxygen: /usr/bin/doxygen.exe (found version "1.8.12") 
-- Using X11 for window creation
-- Looking for XOpenDisplay in /usr/lib/libX11.dll.a;/usr/lib/libXext.dll.a
-- Looking for XOpenDisplay in /usr/lib/libX11.dll.a;/usr/lib/libXext.dll.a - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/libX11.dll.a
-- Configuring done
-- Generating done
-- Build files have been written to: /home/work/git/glfw-build-dir

**Comment by elmindreda** [comment]
This has been fixed with 58c05ba8ee93272a806cb3c0d3153ef228567ba2. Thank you!
