### ISSUE TITLE
Memory leak in glfw.

### ISSUE THREAD

**Issue by snowfoxer** [glfw/glfw#1037]
First, thanks to giving such a useful lib.
When I use glfw to create window, I got this error(under valgrind).
==758==    at 0x4C2F975: calloc (vg_replace_malloc.c:711)
==758==    by 0x6D898A0: XkbGetMap (in /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0)
==758==    by 0x564B2FA: ??? (in /usr/lib/x86_64-linux-gnu/libglfw.so.3.1)
==758==    by 0x56479BC: glfwInit (in /usr/lib/x86_64-linux-gnu/libglfw.so.3.1)

I think maybe it's my fault. So I use the code in the document and got it as before.

My OS is ubuntu 16.04.2 LTS, and the compiler is clang.

**Comment by elmindreda** [comment]
This seems to be the issue fixed by #662.

**Comment by snowfoxer** [comment]
Thanks for saving obsessive compulsive disorder！I will update the system lib.
