### ISSUE TITLE
Inaccurate joystick axes

### ISSUE THREAD

**Issue by Klotzi111** [glfw/glfw#1045]
I found out that the axes of my joystick/gamepad are only recognized that they moved if the value is much higher than the default value. For example the right trigger returns -1. If the value is higher than -0.75 its working fine.
And this is not the hardware because Steam can receive smaller values.
Why is this?

**Comment by elmindreda** [comment]
Please see [Reporting a window, input or event bug](https://github.com/glfw/glfw/blob/master/.github/CONTRIBUTING.md#reporting-a-window-input-or-event-bug).

**Comment by Klotzi111** [comment]
How should I write this? There is no callback of the returns. I can make a video showing this. Sorry for for asking such stupid questions, but I dont know how to do this correctly.

**Comment by intrigus** [comment]
Read the guide again. Do exactly what it tells you to do.
If you have problems following the guide, please ask specific questions.

**Comment by Klotzi111** [comment]
OS and version: Windows 10 64-Bit
Release or commit: 67c9155f3bce1da59a0eb66b7c18d1b2a48fa1ab
No Error
No event output with "tests/events.exe" (because there is no callback for joysticks)

I tested with "tests/joysticks.exe". On the axis there is a deadzone, a range of values which will not be returned. But other applications like Steam dont have this deadzone. So I think this is a bug.

**Comment by Klotzi111** [comment]
An other thing to mention is that the axes are cutted of (by the red square). See in following video:

[https://www.youtube.com/watch?v=etIdk_iodZ8](url)

Is there any possibility to get "cutted of" values in the blue circle? Or could you add one?
Or have I to calculate the values out of the green circle down to a lenght of 1. But that would lose accuracy (thats not nice).

**Comment by elmindreda** [comment]
Since only one system API (XInput) provides proper deadzone data, it may be better to leave the joystick function data raw and move all deadzone calculations to the gamepad functions where it can be done safely across all platforms.

**Comment by Klotzi111** [comment]
That would be nice.
And what about the "cutted off"(by the red square) values?

**Comment by Klotzi111** [comment]
There is also a misstake in [win32_joystick.c](https://github.com/glfw/glfw/blob/master/src/win32_joystick.c#L720) at line 720 (and the other same doing lines above).

```C
            axes[3] = (xis.Gamepad.sThumbRY + 0.5f) / 32767.f;
```
should be
```C
            axes[3] = (xis.Gamepad.sThumbRY + 0.5f) / 32767.5f;
```
to the axact 1 and not 1.000015.

**Comment by Klotzi111** [comment]
Is there any possibility to get the values not cutted off? Or is it not possible to get the raw values from the API?

**Comment by elmindreda** [comment]
@Klotzi111 That change is already staged in the `ci` branch (see 9716ea511e2de763c7b3b99b767d3be9f48b6a4c above) along with a fix for the bug you found, but for some reason AppVeyor refuses to build that branch right now. I'll be offline until Sunday but if you check out the current `ci` branch you should get the data without any deadzone applied.

**Comment by Klotzi111** [comment]
I saw that and I have to thank you. But with the comment above I meant all values that go over 32767 are not registered but its not the limit of my controller.
Look at the video I posted:
https://www.youtube.com/watch?v=etIdk_iodZ8
You fixed the "deadzone" but not the red square that cuts the of the blue circle (which is the actual limit of my controller). So the question is can this also be fixed or not?

**Comment by elmindreda** [comment]
There is no way to get values outside of the red square of [-32768,32767] via XInput. The [XINPUT_GAMEPAD](https://msdn.microsoft.com/en-us/library/windows/desktop/microsoft.directx_sdk.reference.xinput_gamepad.aspx) struct provides axis values as int16.

This almost roundrect that is the intersection of the red square and the blue circle is what you want in most cases and would have to emulate if the API didn't do it for you. It gives the user nice wide edges for hitting the max and min values without needing perfect precision during hectic gameplay.

**Comment by elmindreda** [comment]
Sorry, forgot to update the commit message command.

**Comment by elmindreda** [comment]
This appears to be fixed to the extent that it's possible. If I overlooked anything, please re-open it.

**Comment by DesertCookie** [comment]
> 
> 
> Please see [Reporting a window, input or event bug](https://github.com/glfw/glfw/blob/master/.github/CONTRIBUTING.md#reporting-a-window-input-or-event-bug) in the contribution guide.

The link is broken. Please update. Thanks!
