### ISSUE TITLE
Call to glfwGetKey fires "Invalid Key" errors to the GLFW Error Callback

### ISSUE THREAD

**Issue by DodgeeSoftware** [glfw/glfw#1046]
The method in input.c "GLFWAPI int glfwGetKey(GLFWwindow* handle, int key)" has a bug in it (as of version 3.2.1)

The lines reads
if (key < GLFW_KEY_SPACE || key > GLFW_KEY_LAST)

And it should be
if (key < 0 || key > GLFW_KEY_LAST)

**Comment by DodgeeSoftware** [comment]
The Error can be reproduced with the following code
```

// C++ Includes
#include <iostream>

// GLFW Includes
#include <glfw/glfw3.h>

// A pointer to the game window
GLFWwindow* pWindow;
bool isRunning = true;
// Array of keyboard keys
bool keyDownArray[GLFW_KEY_LAST];

void GLFWErrorCallback(int errorCode, const char* description)
{
    // Send a message to the console
    std::cout << "ERROR: GLFW Error Code: " << errorCode << std::endl;
    std::cout << description << std::endl;
}

int main()
{
    if (glfwInit() == GL_TRUE)
    {
        // Set the GLFW error handling callback
        glfwSetErrorCallback(GLFWErrorCallback);
        // Send a message to the console
        std::cout << "glfwInit Success." << std::endl;
    }
    else
    {
        // Send a message to the console
        std::cout << "glfwInit failure." << std::endl;
        // Failure
        return -1;
    }

    pWindow = glfwCreateWindow(640, 480, "", 0, 0);

    while (isRunning == true)
    {

        for(unsigned int i = 0; i < GLFW_KEY_LAST; i++)
            keyDownArray[i] = ((glfwGetKey(pWindow, i) == GLFW_PRESS) ? true : false);

        if (keyDownArray[GLFW_KEY_ESCAPE] == true)
            isRunning = false;

        // Swap the back buffer to the front (double buffered OpenGL Context)
        glfwSwapBuffers(pWindow);
    }

    // shutdown glfw
    glfwTerminate();

    return 0;
}

```

**Comment by elmindreda** [comment]
There are no [valid keys](http://www.glfw.org/docs/latest/group__keys.html) in the interval 0-31, and there are other holes as well although the function doesn't yet check for those.

**Comment by DodgeeSoftware** [comment]
At present to detect when keys are toggled I take a snap shot of the all keys from one frame and then compare that snap shot with all the keys the present frame to work out when keys have been toggled or not.  I don't think I can use call backs for this sort of thing because I think they are event driven and that means they wouldn't represent they keyboard in a present or previous frame. Sure I can use a for loop from GLFW_KEY_SPACE for now but if there are other keys that are invalid I am going to end up with a huge error log full of "Invalid Keys". Is there going to be an isValidKey function so I can skip over those keys? Do you know if there is a better approach for tracking toggle keys? If not should I just modify glfw to function the old way?

**Comment by elmindreda** [comment]
> At present to detect when keys are toggled I take a snap shot of the all keys from one frame and then compare that snap shot with all the keys the present frame to work out when keys have been toggled or not. I don't think I can use call backs for this sort of thing because I think they are event driven and that means they wouldn't represent the keyboard in a present or previous frame.

If you mean you're using `glfwGetKey` then note that only returns [the last state reported to the callback](http://www.glfw.org/docs/latest/group__input.html#gadd341da06bc8d418b4dc3a3518af9ad2). That function cannot give you newer state than the key callback.

> Do you know if there is a better approach for tracking toggle keys? If not should I just modify glfw to function the old way?

The most straightforward way is probably a key array.

```c
const int keys[] = {
    GLFW_KEY_SPACE,
    GLFW_KEY_APOSTROPHE,
    GLFW_KEY_COMMA,
    ...
    GLFW_KEY_RIGHT_SUPER,
    GLFW_KEY_MENU,
};

for (int i = 0;  i < sizeof(keys) / sizeof(keys[0]);  i++)
{
    const int state = glfwGetKey(window, keys[i]);
    ...
}
```

> Could we have a glfwGetKeyboardArray() function or something similar?

It's possible that will happen. It's a little trickier for GLFW due to the sticky keys feature, but not impossible.
