### ISSUE TITLE
glfwInit() take 10s to complete

### ISSUE THREAD

**Issue by malobre** [glfw/glfw#1049]
I cloned the repository, compiled everything and ran the examples, they all take around 10 seconds to launch.

I originally discovered this bug when using lwjgl bindings, I made some measurements with those bindings as I am more familiar with java than C:
```java
import org.lwjgl.glfw.GLFW;

public class Main {
    public static void main(String[] args) {
        long start = System.currentTimeMillis();
        if (!GLFW.glfwInit()) throw new IllegalStateException("Unable to initialize GLFW");
        long stop = System.currentTimeMillis();
        System.out.println("GLFW.glfwInit() took " + (stop - start) + "ms");
    }
}
```

Output:
```
GLFW.glfwInit() took 10071ms
GLFW.glfwInit() took 10073ms
GLFW.glfwInit() took 10060ms
GLFW.glfwInit() took 10070ms
GLFW.glfwInit() took 10058ms
GLFW.glfwInit() took 10068ms
GLFW.glfwInit() took 10075ms
GLFW.glfwInit() took 10077ms
GLFW.glfwInit() took 10070ms
GLFW.glfwInit() took 10076ms
```

I'm running **Windows 10 Pro N 1703** on a **64bit CPU**

**Comment by malobre** [comment]
I compiled this:
```c
#include <glad/glad.h>
#include <GLFW/glfw3.h>

#include <stdlib.h>
#include <stdio.h>

static void error_callback(int error, const char* description)
{
    fprintf(stderr, "Error: %s\n", description);
}

int main(void)
{
    glfwSetErrorCallback(error_callback);

    if (!glfwInit()) exit(1);

    exit(0);
}
```

and I use the time command to measure how long it takes and I get the same result as before (through lwjgl).

**Comment by Klotzi111** [comment]
Its maybe because your antivirus is checking the .dll. I had a similar problem, but it only took so long very time i compiled the glfw3.dll new und then started my application.

**Comment by elmindreda** [comment]
@malobre I need to know what part of the code is taking that long to have any chance of diagnosing it. That functions does a lot of things.

**Comment by malobre** [comment]
@Klotzi111 I don't have an Antivirus.
@elmindreda I'll try to get you more info asap.

**Comment by malobre** [comment]
@elmindreda I investigated a little bit and [win32_joystick.c#L561](https://github.com/glfw/glfw/blob/617c42b20ab48715934f4fa27af5cae738837eb0/src/win32_joystick.c#L561) is the line taking 10s.

Path I followed:
 [glfwInit()](https://github.com/glfw/glfw/blob/953106e74ddaf925eb2d100ea67bb36bf89167d4/src/init.c#L191) -> [_glfwPlatformInit()](https://github.com/glfw/glfw/blob/731ff91acd7c52abe74bcde0f333f1c11c16f3db/src/win32_init.c#L437) -> [_glfwInitJoysticksWin32()](https://github.com/glfw/glfw/blob/617c42b20ab48715934f4fa27af5cae738837eb0/src/win32_joystick.c#L483) -> [_glfwDetectJoystickConnectionWin32()](https://github.com/glfw/glfw/blob/617c42b20ab48715934f4fa27af5cae738837eb0/src/win32_joystick.c#L516)

**Comment by elmindreda** [comment]
@malobre Thanks! Do you have any controllers connected?

**Comment by malobre** [comment]
@elmindreda Nope, I do use a Xbox controller sometimes but it is not connected now.

**Comment by elmindreda** [comment]
Cannot reproduce on Windows 7 or Windows 10.

**Comment by yzsolt** [comment]
According to [this StackOverflow page](https://stackoverflow.com/questions/10967795/directinput8-enumdevices-sometimes-painfully-slow), this is a driver/kernel bug, not GLFW's fault.

@malobre there's a workaround mentioned on the linked page. I think you should check if it helps.

**Comment by malobre** [comment]
@yzsolt Thank you, the workaround totally worked and GLFW.glfwInit() take around 50ms now.
I'm closing this issue since this is not caused by GLFW.
