### ISSUE TITLE
GLFWContentView::setMarkedText leaks

### ISSUE THREAD

**Issue by Kangz** [glfw/glfw#1050]
Found when running the XCode static analyzer on our project: [setMarkedText](https://github.com/glfw/glfw/blob/82284b86ebde945951f35bbb20bfe582f2d7322b/src/cocoa_window.m#L697) leaks because ```initWithString``` ([doc](https://developer.apple.com/documentation/foundation/nsattributedstring/1407481-initwithstring?language=objc)) and ```initWithAttributedString``` ([doc](https://developer.apple.com/documentation/foundation/nsattributedstring/1415342-initwithattributedstring?language=objc)) return a value but do not modify the string in place.

```
    if ([string isKindOfClass:[NSAttributedString class]])
        [markedText initWithAttributedString:string];
    else
        [markedText initWithString:string];
```

Should probably become
```
    [markedText release];
    if ([string isKindOfClass:[NSAttributedString class]])
        markedText = [NSMutableAttributedString initWithAttributedString:string];
    else
        markedText = [NSMutableAttributedString initWithString:string];
```

Might be related to #892 ?

**Comment by elmindreda** [comment]
This has been fixed with ab2247f8f38198b97c43b0d9a51cbe1e8ce4ea99. Thank you!
