### ISSUE TITLE
glfwTerminate causes ERROR_INVALID_HANDLE

### ISSUE THREAD

**Issue by liavt** [glfw/glfw#1053]
OS and version: Windows 10 x32
Release or commit: 3.2.1
Error messages: Running GetLastError() returns non-zero value after `glfwTerminate()`

I was able to trace the offending function call to this call to `FreeLibrary` in `freeLibraries()` in `win32_init.c`:
```c++
    if (_glfw.win32.dinput8.instance)
        FreeLibrary(_glfw.win32.dinput8.instance);
```

Commenting these 2 lines out fixed the problem.

The following code reproduces issue:
```c++
#include <GLFW/glfw3.h>

#include <Windows.h>

int main() {
	if (!glfwInit()) {
		return -1;
	}

	SetLastError(0);

	glfwTerminate();

	return GetLastError(); // returns 6 (ERROR_INVALID_HANDLE)
}
```

The program returns 0 if `glfwTerminate()` is commented out, 6 (ERROR_INVALID_HANDLE) otherwise.

**Comment by elmindreda** [comment]
I can't reproduce this specific error, but GLFW makes no guarantees about the state of the OS error code, whether this one or `errno`. Why are you checking this after termination?

**Comment by liavt** [comment]
My app checks the os error code after termination because it uses some system specific functions elsewhere, not specifically because of glfw. This problem could just be a problem on my local machine

**Comment by elmindreda** [comment]
The error code returned by `GetLastError` is really only meaningful directly after a Win32 function has indicated failure, and only for functions that reports errors this way. Some only report via a return value or out parameter and some Win32 errors are unavoidable and benign.

I see in `System.cpp` that you are attempting to clear the error with `GetLastError`, but this doesn't work like in OpenGL. You need to call `SetLastError` to clear it.

**Comment by elmindreda** [comment]
I'm a little worried that the call to `FreeLibrary` fails though. This may still indicate a bug in GLFW and I will look into it further.

**Comment by liavt** [comment]
FreeLibrary also returns a boolean value whether it succeeded or not. If it returns false, you check GetLastError. Currently, glfw ignores all win32 system errors which could cause hidden issues

**Comment by liavt** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/ms683152(v=vs.85).aspx

"If the function succeeds, the return value is nonzero.
If the function fails, the return value is zero. To get extended error information, call the GetLastError function."

**Comment by elmindreda** [comment]
True, but I don't know what GLFW could do differently if `FreeLibrary` fails.

**Comment by liavt** [comment]
If `FreeLibrary` creates `ERROR_INVLAID_HANDLE`, it could be that `LoadLibrary` is failing to properly load dinput8.dll. `glfwInit()` could possibly do error checking when it loads libraries.

**Comment by elmindreda** [comment]
If `LoadLibrary` fails then it returns `NULL`, which is stored in `_glfw.win32.dinput8.instance`. If `_glfw.win32.dinput8.instance` is `NULL` then `FreeLibrary` is not called.

**Comment by elmindreda** [comment]
This makes me suspect GLFW is corrupting memory somewhere for it to cause an invalid handle error.

**Comment by liavt** [comment]
I found the issue in the following code in `glfwInit()`:
```c
_glfw.win32.dinput8.instance = LoadLibraryA("dinput8.dll");
    if (_glfw.win32.dinput8.instance)
    {
        _glfw.win32.dinput8.DirectInput8Create = (DIRECTINPUT8CREATE_T)
            GetProcAddress(_glfw.win32.dinput8.instance, "DirectInput8Create");
    }
```

On my system, `GetProcAddress` here sets LastError to `ERROR_INVALID_FUNCTION`. This explains the `ERROR_INVALID_HANDLE` later on. It can't find `DirectInput8Create` in `dinput8.dll`. This could be a problem on my system only with an outdated version of `dinput8.dll`

**Comment by liavt** [comment]
Closing the issue as it's probably only on my system. It's strange because GLFW works perfectly fine other than this one error, but it's not major so it's fine.
