### ISSUE TITLE
_glfwFreeMonitor segfaults

### ISSUE THREAD

**Issue by cenomla** [glfw/glfw#1055]
When I call `glfwTerminate` the function `_glfwFreeMonitor` in `monitor.c` segfaults when trying to free `monitor->name`.  I think this is caused by `strdup` returning an invalid address in `_glfwAllocMonitor`. Replacing `strdup` with `calloc` and `strcpy` fixes the issue. There is a warning when compiling this file with gcc saying that `strdup` in implicitly declared. I am using gcc 7.1.1 and Arch Linux.

**Comment by elmindreda** [comment]
Please post the full gcc error.

**Comment by cenomla** [comment]
`warning: implicit declaration of function 'strdup'; did you mean 'strcmp'? [-Wimplicit-function-declaration]`
`warning: assignment makes pointer from integer without a cast [-Wint-conversion]`

I get these two warnings everywhere there is a `strdup` in the code.

**Comment by elmindreda** [comment]
It has a point. GLFW shouldn't be using `strdup` without requsting one of the standards that provide it. Thanks!
