### ISSUE TITLE
Use official FindVulkan.cmake for Vulkan

### ISSUE THREAD

**Issue by undisputed-seraphim** [glfw/glfw#1058]
Because the custom ones included don't work on Windows (doesn't find headers for LunarG Vulkan).

I already have a working edit of CMakeLists for this, if you'd like.

Pros: It just works.
Cons: Probably doesn't work well with versions of CMake earlier than 3.0. I'm on 3.9.

**Comment by elmindreda** [comment]
What version of GLFW are you using?

**Comment by elmindreda** [comment]
Cannot reproduce. Windows 7, CMake 3.8.1, GLFW `master`, LunarG SDK 1.0.54.0.

**Comment by elmindreda** [comment]
Seems the upstream Vulkan find module was [added in CMake 3.7](https://cmake.org/cmake/help/v3.7/release/3.7.html). That's too recent to require. Hopefully the bug in our version can be fixed.

**Comment by elmindreda** [comment]
Cannot reproduce with CMake 3.9.

**Comment by undisputed-seraphim** [comment]
I'm on Windows 8.1 using Visual Studio 2015 Community.

My CMake command is `cmake .. -G "Visual Studio 2015 Win64"`.

My LunarG Vulkan is installed with all default options and the directory is registered in the `PATH`environment variable in Windows.

**Comment by elmindreda** [comment]
Verified with GLFW 3.2.1. I really need to get 3.3 out. Thank you for the follow-up!
