### ISSUE TITLE
Window surface creation

### ISSUE THREAD

**Issue by WowVeryLogin** [glfw/glfw#1061]
When using glfw for creating window for Vulkan application glfwGetRequiredInstanceExtensions returns "VK_KHR_surface" and "VK_KHR_xcb_surface". But in glfw3native.h there is no function to retrieve xcb_connection_t and other stuff to fill VkXcbSurfaceCreateInfoKHR. Probably you should add this functions.
Using VkXlibSurfaceCreateInfoKHR and vkCreateXlibSurfaceKHR for created window work fine though. So does glfw to create window use Xlib or Xcb?

**Comment by elmindreda** [comment]
You don't need to call `vkCreateXlibSurfaceKHR` or `vkCreateXcbSurfaceKHR` yourself. The [glfwCreateWindowSurface](http://www.glfw.org/docs/latest/group__vulkan.html#ga1a24536bec3f80b08ead18e28e6ae965) function calls the appropriate `vkCreate*SurfaceKHR` function on each platform.

**Comment by pknowles** [comment]
For people using their own vulkan loader it would be nice to allow the app to manage its own vulkan interaction entirely. This means exposing the native window handles. It sounds like that's what `glfw3native.h` is intended for. There is `glfwGetX11Display()`, but no equivalent `glfwGetXCBConnection()` to get the connection that one might pass to `vkCreateXcbSurfaceKHR()`, that they loaded themselves.

**Comment by YaaZ** [comment]
Related PR: #2398

**Comment by pknowles** [comment]
@elmindreda can this issue be reopened? The fix is small. Just needs some little extras like:

```
xcb_visualid_t    glfwGetXCBVisualID();
xcb_connection_t* glfwGetXCBConnection();
xcb_window_t      glfwGetXCBWindow(GLFWwindow* window);
```

Example implementations in my [vulkan_objects](https://github.com/pknowles/vulkan_objects/blob/main/src/glfw_xcb_hack.cpp) library. XCB is really nice to avoid X11 macro pollution: https://stackoverflow.com/questions/79583727/how-to-avoid-macros-from-x11-polluting-other-third-party-code
