### ISSUE TITLE
Rendering fails using multiple windows on Ubuntu 16.04

### ISSUE THREAD

**Issue by claudiofantacci** [glfw/glfw#1065]
**System version**: Ubuntu 16.04
`glfw` version: compiled from source on `master` branch
**GPU**: NVIDIA K40

I have an application that define and initialize multiple windows to render different objects *with the same code*. Say for example that I need 3 contexts and windows, the last one always fails to render objects. The only workaround I found so far is to define and initialize *one window more than needed* to have all the needed rendering process to succeed (that is, the last one is a fake window doing nothing).

I use this [class and its init method](https://github.com/robotology/superimpose-mesh-lib/blob/02f4b7521241966907dd8e4dcabd4555a8d5e59f/src/SuperimposeMesh/src/SICAD.cpp#L262-L367) to render objects in a given context and window.

The same code running on macOS, which is were the application is actually developed, *does not present this issue*. Because of this, I don't understand whether I'm doing something conceptually wrong (wrong code, missing code, wrong code execution) or if it is actually an issue.
Thanks in advance for the help :-) !

**Comment by elmindreda** [comment]
That is a very strange bug. Are you running Nouveau or the closed source driver on Ubuntu?

**Comment by elmindreda** [comment]
Does the `sharing` test program (located in the `tests` directory of the GLFW source tree) work on the Ubuntu machine?

**Comment by claudiofantacci** [comment]
Hi @elmindreda, thanks for your reply.

It is indeed a really strange behaviour. I'm performing tests on my software side and so fare they reported no errors.

I don't have the PC with me, it's in my lab. Tomorrow morning I will check what NVIDIA drivers are installed, but as far as I remember they should be the official drivers from NVIDIA repositories.

Let me also report here another strange behaviour I'm experiencing and that may be connected or may provide you a hint (meanwhile, I have updated GLFW and have to test this issue again, don't take it as 100% accurate).
My program is pretty simple: render an object and then read the output with [`glReadPixels`](http://docs.gl/gl3/glReadPixels), then use it for some image processing. I usually do this [off-screen](http://www.glfw.org/docs/latest/context_guide.html#context_offscreen), but on Ubuntu I can't set `glfwWindowHint(GLFW_VISIBLE, GLFW_FALSE);` because otherwise `glReadPixels` returns the on-screen pixels that would be occupied by the rendering window. *Basically it is like taking a screenshot of what the monitor is currently displaying on the portion of screen occupied by the rendering window*. As a result I can't do off-screen rendering and I have to set `glfwWindowHint(GLFW_VISIBLE, GLFW_TRUE);`.

**Comment by claudiofantacci** [comment]
As far as test are concerned, I will run them as soon as I get back to the lab.

**Comment by claudiofantacci** [comment]
Sorry for the third post in a row.

One more detail: when I render I use 'glScissor' to have multiple renders in a single window.

**Comment by claudiofantacci** [comment]
I run the `sharing` test and seems to be working fine. Two windows appear with granular purple and yellow texture.

This is the output of `glfwinfo`:
```bash
GLFW header version: 3.2.1
GLFW library version: 3.2.1
GLFW library version string: "3.2.1 X11 GLX EGL clock_gettime /dev/js Xf86vm shared"
OpenGL context version string: "4.5.0 NVIDIA 375.66"
OpenGL context version parsed by GLFW: 4.5.0
OpenGL context flags (0x00000000):
OpenGL context flags parsed by GLFW:
OpenGL profile mask (0x00000000): unknown
OpenGL profile mask parsed by GLFW: compat
OpenGL robustness strategy (0x00008261): none
OpenGL robustness strategy parsed by GLFW: none
OpenGL context renderer string: "Quadro K2000/PCIe/SSE2"
OpenGL context vendor string: "NVIDIA Corporation"
OpenGL context shading language version: "4.50 NVIDIA"
OpenGL framebuffer:
 red: 8 green: 8 blue: 8 alpha: 8 depth: 24 stencil: 8
 samples: 0 sample buffers: 0
 accum red: 16 accum green: 16 accum blue: 16 accum alpha: 16 aux buffers: 4
Vulkan loader: missing
```

The only test seems to be failing is `gamma` that reports the following:
```bash
Gamma: 1.000000
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  140 (RANDR)
  Minor opcode of failed request:  24 (RRSetCrtcGamma)
  Serial number of failed request:  184
  Current serial number in output stream:  186
```

**Comment by claudiofantacci** [comment]
As far as the video card is concerned, this is my current setting:
```bash
  *-display               
       description: VGA compatible controller
       product: GK107GL [Quadro K2000]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:05:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:45 memory:ec000000-ecffffff memory:b0000000-bfffffff memory:c0000000-c1ffffff ioport:c000(size=128) memory:ed000000-ed07ffff
  *-display
       description: 3D controller
       product: GK110BGL [Tesla K40c]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:04:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress bus_master cap_list
       configuration: driver=nvidia latency=0
       resources: irq:46 memory:ee000000-eeffffff memory:d0000000-dfffffff memory:e0000000-e1ffffff
```
So we actually have 2 video cards, the K40 is the second. I was unaware of this double video card configuration and now I wonder which one I'm actually targeting for rendering. May be this the source of my problem?

The NVIDIA dirver is:
```bash
Mon Aug 28 09:01:00 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.66                 Driver Version: 375.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K40c          Off  | 0000:04:00.0     Off |                    0 |
| 33%   73C    P0    86W / 235W |    602MiB / 11439MiB |     32%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Quadro K2000        Off  | 0000:05:00.0      On |                  N/A |
| 32%   49C    P5    N/A /  N/A |    230MiB /  1997MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
```

**Comment by claudiofantacci** [comment]
I have an update about this issue. Sorry for the long delay, but I have been super-busy here 🙃 !

The setting is still the same, but **for the GPUs that have been replaced in favour of a single NVIDIA 1080Ti**. The issue is still present but, after some tests, I found out what **may be** the cause of error.

I still use this [class, `SICAD`, constructor](https://github.com/robotology/superimpose-mesh-lib/blob/32682e8f8855672bda62a0cc2a7dc51a7763648d/src/SuperimposeMesh/src/SICAD.cpp#L66-L181) and its [`SICAD::initOpenGL()` method](https://github.com/robotology/superimpose-mesh-lib/blob/32682e8f8855672bda62a0cc2a7dc51a7763648d/src/SuperimposeMesh/src/SICAD.cpp#L277-L382) to render objects in a given context and window.

I have an application that uses different classes, each of which has a **pointer to `SICAD`**. When these class constructors are called, the `SICAD` classes are allocated on the heap using `new`. At this point, the **last** `SICAD` object that is allocated **always fails to render properly**.
If instead I allow the `SICAD` classes to be **allocated on the stack*, hence without using any pointer and `new` calls to `SICAD`, everything seems to work perfectly 😲 .

(Please be aware that I'm still doing tests and eventually I'll provide further updates).

At this point I wonder whether there is a bug somewhere between my code or `glfw` or if it is just wrong/bad practice allocating graphic-related stuff on the heap, which to be honest seems odd to me.

**Comment by claudiofantacci** [comment]
Hi @elmindreda, I finally find the problem behind this issue.

To make the long story short, I was using `glfwMakeContextCurrent(window_);` in my functions to make the context current, but I was never calling `glfwMakeContextCurrent(nullptr);` to make it back non-current and, for example, be available to other thread.
On macOS **this is not a problem** (or at least it seems not to be) since the code was running smoothly. On Ubuntu, however, you are required to invoke `glfwMakeContextCurrent(nullptr);`. Note also that on my setup, by default, `glfwMakeContextCurrent(nullptr);` causes a pipeline flush. Trying to hint not to flush brings back the issue (but this is related to some peculiarities of my implementation).

**Comment by elmindreda** [comment]
Ah, that makes sense. Thank you for the detailed follow-up! I see the documentation isn't very explicit about this. I'll try to improve that bit.

**Comment by claudiofantacci** [comment]
Hey @elmindreda it's a pleasure contributing to this project, even with some follow-ups 😄 .
I think that by improving the documentation just a little bit can avoid this platform-dependent pitfalls.

**Comment by claudiofantacci** [comment]
Hi @elmindreda, thanks for the documentation update made in https://github.com/glfw/glfw/commit/f2756d0b3f357c7ea160445d91bc9e6169932124.

I think we can close this issue now 😄
