### ISSUE TITLE
No window decorations or close callback on Wayland

### ISSUE THREAD

**Issue by Scoopta** [glfw/glfw#1068]
I'm aware Wayland is currently experimental but I figured I'd bring up the issues I'm having with it since I haven't seen many posts regarding it. When using the wayland backend I have no window decorations regardless of what the GLFW_DECORATIONS hint is set to and my close callback never seems to get called and as far as I've found the only way for me to close the program is by ending the process directly, using Ctrl+C if I'm running from shell, or by adding a listener to escape or some other key that performs a close. The mouse also seems to be larger when hovering over my glfw window when compared with what it should be. I'm using gnome 3.24 on Debian sid as my wayland server.

**Comment by ferreiradaselva** [comment]
On Wayland, window decorations are made on client-side, and GLFW doesn't do that. It's hard to tell if GLFW will ever do that by default (imo, it shouldn't).

One thing you can do is create a drag operation on the mouse button-press/move callbacks. But, some work for dragging borderless windows is already on the way (https://github.com/glfw/glfw/pull/987).

**Comment by Scoopta** [comment]
Dragging the Window isn't a problem. Under gnome you can hold the super key down to drag any window no matter where you click. Also you said in your opinion it shouldn't create them but why not? I would expect it to seeing as that's part of the window and GLFW is what manages the window.

**Comment by ferreiradaselva** [comment]
The problem is that to make a "default decoration" would require to make on each rendering backend of GLFW:

- OpenGL. It would require a texture and framebuffer to be generated in the backend. Also the rendering pipeline (shaders of fixed pipeline, depending on the OpenGL version);
- Vulkan;
- No backend. GLFW allows to create windows with no OpenGL backend, so that is also a target.

Maybe in the future there will be a extension for that, maybe not that, but a standard. With an unclear route, we would be focusing effort on implementing something that might be discarded after a standardization or extension.

**Comment by Scoopta** [comment]
Ahhh yeah that makes sense. I didn't think about that. Well it's good to know that isn't a bug because it means I might add decorations as an engine level feature. At least for the time being.

**Comment by Scoopta** [comment]
Also what's with the close call back not working? Neither clicking the x in the activities menu nor clicking quit in the application drop down at the top calls my call back.

**Comment by ferreiradaselva** [comment]
Yeah, it's definitely not. Take in consideration that, at this point, any other application not using a widget framework (GTK+ or Qt) will have the same problem of non decorated window at this point. And if they make their own decorations, it's definitely something that won't fit (aesthetically) the rest of the desktop.

**Comment by Scoopta** [comment]
Yeah I didn't realize that about Wayland and most other Wayland native applications I run are GTK+ which obviously use the traditional gnome 3 decorations.

**Comment by gracicot** [comment]
Please make note of this: https://lists.freedesktop.org/archives/wayland-devel/2017-October/035564.html

There might be a protocol to ask the compositor for decorations.
