### ISSUE TITLE
Incorrect canvas offset/scaling behavior.

### ISSUE THREAD

**Issue by voxelv** [glfw/glfw#1069]
I'm trying to develop an application on my new laptop, however, I seem to be encountering this bug at every turn. 

Most relevant to GLFW would be this image (also attached)
<img width="1078" alt="red_triangle_compare" src="https://user-images.githubusercontent.com/6580714/30005904-8daacb18-90a1-11e7-9910-4297de8349c1.png">

However the entire album of troubleshooting screenshots may be useful: http://imgur.com/a/ZmSnV

I began developing in libGDX and encountered this canvas issue. I had asked on the libGDX forums and have not gotten a solution, so I gave up.
Next I thought I'd try some 3D modelling with blender. Turns out blender has the same canvas issue. Life got busy around that time so I gave up again without too much digging.
Now I'm trying a C++ OpenGL tutorial at opengl-tutorial.org but I'm still getting this canvas issue.

It could be my specific laptop (it's new-ish: ThinkPad X1 Yoga (2nd Gen)), or some pre-loaded software settings I can't find to turn off or change.
I've done every conceivable Windows 10 Display Scaling / Resolution configuration, and none have fixed this. I've ensured I have the latest graphics drivers. I've tried changing the Intel Graphics Settings configurations. Nothing has worked.

I need this resolved soon!

(also, does anyone know if blender is a consumer of GLFW? this information would help)

**Comment by ferreiradaselva** [comment]
Some code would be useful.

> also, does anyone know if blender is a consumer of GLFW? this information would help

Blender uses a mix of its own API and SDL.

**Comment by voxelv** [comment]
The code I used was stock from the tutorial site: https://github.com/opengl-tutorials/ogl/blob/master/tutorial02_red_triangle/tutorial02.cpp

I've done some more research and it looks like an Intel Graphics Driver issue, discovered previously by the Blender community: https://developer.blender.org/T51521

It seems to be fixed in a recent driver update (8/13/2017 22.20.16.4771), however Lenovo hasn't packaged and made it available for my computer yet.

**Comment by ferreiradaselva** [comment]
Yeah, the driver seems to be the issue. I don't see anything in the code that would cause the problem, either.

Check if the driver is available at https://downloadcenter.intel.com.

**Comment by voxelv** [comment]
The solution was a bit more of a hassle since directly installing the driver from Intel gave an error. Something along the lines of "This driver is not approved for your computer by its manufacturer".
 
I eventually got it to install by doing the following:
1. Open Device Manager
2. Right Click Display Adapters -> Intel HD Graphics
3. Properties -> Driver tab -> Update Driver button
4. Use the "List of drivers on my computer" option
5. Set to Microsoft Basic Driver. Note, your graphics may now be quite wonky because they aren't using the GPU...
6. Install the new driver from Intel.
7. Reboot.
Done!
