### ISSUE TITLE
GLFW + Qt. QEventLoop with QGuiApplication leads to crash

### ISSUE THREAD

**Issue by akustovbanuba** [glfw/glfw#1070]
There is a macOS application with glfw visible window and QApplication eventloop at the same time. The problem is that when QEventLoop is active and there is a loop with "glfwPollEvents()" periodic calls is active (both in main application thread), application crashes when any input event (mouse or keyboard) occurs. "glfwPollEvents()" function calls to "_glfwPlatformPollEvents()" where "[_glfw.ns.autoreleasePool drain];" call causes crash with one of the next messages:
	- objc[2111]: autorelease pool page 0x101894000 corrupted
	- objc[2255]: Invalid or prematurely-freed autorelease pool 0x1018c7948
Is it possible to isolate one from another or any other way to let the application to correctly handle input events for each system's window?
Example code uses Qt 5.9.1 and glfw is from actual master branch.

```cpp
#include <glad/glad.h>
#define GLFW_INCLUDE_NONE
#include <GLFW/glfw3.h>

#include <QApplication>
#include <QTimer>

#include <iostream>

using namespace std;

void glfw_error_callback(int error, const char* description)
{
    cout << "GLFW Error (" << error << "): " << description << endl;
}

int main(int argc, char *argv[])
{

    glfwSetErrorCallback(glfw_error_callback);

    int return_code = 0;
    {
        QApplication a(argc, argv);

        // ************* GLFW initialization *************
        if (GLFW_TRUE != glfwInit())
        {
            cout << "glfwInit error" << endl;
            throw std::exception();
        }

        glfwWindowHint(GLFW_CLIENT_API, GLFW_OPENGL_API);
        glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
        glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GLFW_TRUE);
        glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
        glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 1);
        glfwWindowHint(GLFW_RESIZABLE, GL_FALSE);

        GLFWwindow* window = glfwCreateWindow(480, 640, "gl window", nullptr, nullptr);
        if (nullptr == window)
        {
            cout << "glfwCreateWindow error" << endl;
            glfwTerminate();
            throw std::exception();
        }

        glfwMakeContextCurrent(window);

        if (0 == gladLoadGLES2Loader((GLADloadproc) glfwGetProcAddress))
        {
            cout << "gladLoadGLES2Loader error" << endl;
            glfwTerminate();
            throw std::exception();
        }

        glfwMakeContextCurrent(nullptr);

        // ***********************************************

        QTimer timer;
        timer.setInterval(50);
        timer.setSingleShot(true);

        QObject::connect(&timer, &QTimer::timeout, [&] () {
            glfwPollEvents();
            if(glfwWindowShouldClose(window) == 0) {
                timer.start();
            } else {
                a.quit();
            }
        });

        timer.start();
        return_code = a.exec();

        glfwDestroyWindow(window);
        glfwTerminate();
    }

    return return_code;
}
```

**Comment by elmindreda** [comment]
> Is it possible to isolate one from another or any other way to let the application to correctly handle input events for each system's window?

They can't really be isolated as they both work with the write-only autoreleasepool stack. However, if you're processing events with Qt then specifically on macOS there shouldn't be a need to do so with GLFW. That may prevent the libraries from stepping on each other's feet.

There may still be issues at termination time and it's still going to be some amount of trial and error, so perhaps the Qt OpenGL widget would be a better choice than GLFW if you're already using Qt?

**Comment by akustovbanuba** [comment]
Without "glfwPollEvents()" calls there weren't any issues at termination. We'll try to use one of the proposed options (only Qt events handling or Qt OpenGL widget).
Thank you for response.

**Comment by sphinxdeneme** [comment]
How can I add the project create with glfw as a widget to my qt project?
