### ISSUE TITLE
Can't close window from title bar in GLFW_CURSOR_DISABLED mode

### ISSUE THREAD

**Issue by IanLilleyT** [glfw/glfw#1071]
OS and version: Windows 10 64-bit (10.0.15063 Build 15063)
Release or commit: master (d80d4be0307d52d7add69f9a995a34325a9dfe1c)
Test: "boing" project in examples (64-bit)

Steps:
- Before init() type glfwSetInputMode(window, GLFW_CURSOR, GLFW_CURSOR_DISABLED);
- Defocus the window (i press the windows key) 
- Try to click the X button on the top bar
Result: mouse gets recaptured and the window stays open

I also tried calling glfwSetWindowFocusCallback and inside that function setting to GLFW_CURSOR_DISABLED when focused and GLFW_CURSOR_NORMAL when unfocused, but it made no difference besides the cursor being visible when hovering over the window while defocused.

This is unexpected behavior to me because the X button lights up making you think it can be clicked. Also, other games that capture the mouse let you close this way (none of the ones I tested use GLFW as far as I know).

**Comment by elmindreda** [comment]
This was one of the left-over bits of #650. It should be fixed now with a368d89c947db11afb97bc4788022929fcd71493. Thank you!
