### ISSUE TITLE
glfwVulkanSupported returning 0 on OSX (With MoltenVK)

### ISSUE THREAD

**Issue by mtesseracttech** [glfw/glfw#1073]
I am not 100% sure if this belongs here, if not, my apologies. Because I am not sure where else to take this.

A little context:
I am trying to develop a rendering engine using Vulkan and GLFW. At the same time I am learning how to use CMake (so possibly the error may lie there) and multiplatform development.
I am trying to make the engine buildable on both OSX and Windows, and thus far that seemed to work out (libraries are detected, both on windows and OSX, and it compiled).
Now to the problem: When I try to run glfwVulkanSupported on OSX, it returns 0. I am not sure what causes this, because there are available vulkan extensions when I call vkEnumerateInstanceExtensionProperties
I get the following output:

VK_MVK_moltenvk
VK_KHR_swapchain
VK_KHR_surface
VK_MVK_macos_surface

but when I call glfwGetRequiredInstanceExtensions(&glfwExtensionCount)
I get 0x0 back.

So would this be some kind of linking problem or something else? I have used a strategy to get things running that I describe in this file:
https://github.com/mtesseracttech/VulkanEngine/blob/master/Setup%20Readme.txt

The biggest thing I can think of is that the includes are not linked in the proper way, I am not sure how to get around this though, because with the way the FindVulkan.cmake file was on your repo, it would not detect the headers. (it tried to look inside of the .framework file, but never seemed to actually find the headers, so I hardcoded a path as stated in the Setup Readme)

**Comment by mtesseracttech** [comment]
I was thinking about it and my best guess is at that the FindVulkan.cmake in GLFW is not detecting MoltenVK just like it wouldn't find MoltenVK in my application itself. Maybe that is why it is not seeing Vulkan at all.

**Comment by Shimmen** [comment]
From looking at your [CMakeLists.txt](https://github.com/mtesseracttech/VulkanEngine/blob/master/CMakeLists.txt#L28) I can see that the following message should be printed when configuring CMake if Vulkan was successfully found: `"Found Vulkan, Including and Linking now"`. Does that message show up? In CLion you can open up the CMake tab in the bottom and press the reload button to force a reload of the CMake list files. From that tab you can also look at the CMake variable cache: there you should be able to see some values for your variables like `VULKAN_INCLUDE_DIR` etc.

**Comment by mtesseracttech** [comment]
Yes, they do show up. The reason I manually define VULKAN_INCLUDE_DIR in the FindVulkan.cmake for OSX is because it was not picking up the /headers folder located inside of MoltenVK.framework, even though it was finding the .framework file.

**Comment by elmindreda** [comment]
@mtesseracttech What commit of GLFW are you using?

**Comment by mtesseracttech** [comment]
@elmindreda what exactly do you mean? On OSX I use the version that is downloaded with by default with Homebrew, which is 3.2.1 as far as I know.

**Comment by elmindreda** [comment]
@mtesseracttech Ah, that explains it then. GLFW added support for MoltenVK after 3.2.1. Uninstall the Homebrew version and build and install from this repo instead.

**Comment by mtesseracttech** [comment]
@elmindreda Thanks! It seems to be fine now. The best technique to do that right now if you work with homebrew would be to do the following (for people that might run into this in the near future):

brew install cmake //If this hasn't been done yet
brew uninstall glfw
brew install glfw --HEAD

That will build and install the most recent version.

**Comment by elmindreda** [comment]
From what I understand this issue has been resolved so I'm closing it. If not, please re-open it at any time.

**Comment by mrdev023** [comment]
I have same problem

Source Code : https://github.com/mrdev023/TUTO_VULKAN

Log: 

[mvk-info] MoltenVK version 0.19.0. Vulkan version 1.0.64.
[mvk-info] GPU device Intel(R) Iris(TM) Plus Graphics 640 supports the following Metal Feature Sets:
        OSX GPU Family 1 v3
        OSX GPU Family 1 v2
        OSX GPU Family 1 v1
Available extensions:
        VK_MVK_moltenvk
        VK_KHR_swapchain
        VK_KHR_surface
        VK_AMD_negative_viewport_height
        VK_MVK_macos_surface
Required Extensions :
VkResult : -3
failed to create window surface!

**Comment by xgalaxy** [comment]
Sorry to resurrect an old thread.

I'm using CLion.
I'm using GLFW head and I have VulkanSDK installed on MacOs.
I can run `vulkaninfo` from the command line fine.

When CLion/Cmake run I see the following output:
```
-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- GLM: Build with C++17 features
-- GLM: SSE3 instruction set
GLM: Clang - AppleClang compiler
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Found Vulkan: /Users/xxx/Code/vendor/vulkansdk/macOS/lib/libvulkan.dylib  
-- Using Cocoa for window creation
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/xxx/Code/projects/gate/cmake-build-debug

[Finished]
```

I have this in my main.cpp
```
#define GLFW_INCLUDE_VULKAN
#include <GLFW/glfw3.h>
```

But when I compile I see the following
```
[ 95%] Building CXX object game/CMakeFiles/gate.dir/main.cpp.o
In file included from /Users/robert/Code/projects/gate/game/main.cpp:2:
/Users/xxx/Code/projects/gate/vendor/glfw/include/GLFW/glfw3.h:215:12: fatal error: 'vulkan/vulkan.h' file not found
  #include <vulkan/vulkan.h>
           ^~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by xgalaxy** [comment]
Sorry to bother you.

I figured out my problem. I'm not linking against Vulkan statically. Therefore I had to `find_package` Vulkan myself and link it against the appropriate target.
