### ISSUE TITLE
GLFW window crashes when "Mute speakers" or "Increasing/Decreasing a volume" keys pressed once. 

### ISSUE THREAD

**Issue by openGLnoob** [glfw/glfw#1076]
Hi there!
I noticed one strange thing - when I press my volume keys on my keyboard ("Defender", made in China) my GLFW (3.2) window freeze and Win7 trying to close this program urgently. May be GLFW can't handle codes of this keys, I don't know. How can I solve this problem?

**Comment by elmindreda** [comment]
Does the GLFW `events` test program have the same problem?

**Comment by openGLnoob** [comment]
Events, cursor, gamma and other works fine. Events program gives: 
Key 0xfffffffff Scancode 0x012e <UNKNOWN> - when "Increase volume"
Key 0xfffffffff Scancode 0x0130 <UNKNOWN> - when "IDecrease volume"

**Comment by elmindreda** [comment]
Are you using the key passed to your key callback as an array index without checking if it's -1?

**Comment by openGLnoob** [comment]
Yes, I use array of states and only two state of key callback -"press" and "release". How is the proper way to handle "unknown key"? Something like that is calls exception and I can't just skip this error:

static void keyCallback(GLFWwindow* window, int key, int scancode, int action, int mode)
	{
		if (action == GLFW_PRESS)
			keys[key] = true;
		if (action == GLFW_RELEASE)
			keys[key] = false;
		if (action == GLFW_KEY_UNKNOWN)
			return;
       }

**Comment by tombsar** [comment]
@openGLnoob The simple fix is to add `if (key == GLFW_KEY_UNKNOWN) { return; }` to the top of your `keyCallback` function. In the snippet you posted you are 1) checking too late, after you have already used `key` to index into your array, and 2) checking `action` rather than `key`.

**Comment by openGLnoob** [comment]
@tombsar Thank you! It works as expect!
