### ISSUE TITLE
Get content scale drop FPS

### ISSUE THREAD

**Issue by ghost** [glfw/glfw#1077]
Here is profiler screenshots. Here you can see why drops my FPS. Problem with **get content scale** function. 

<details>

![time0](https://user-images.githubusercontent.com/28119043/30506577-a4539d96-9aaf-11e7-8be7-988eeecdf7da.PNG)
![time1](https://user-images.githubusercontent.com/28119043/30506575-a4147756-9aaf-11e7-934c-5622b046e672.PNG)
![time2](https://user-images.githubusercontent.com/28119043/30506576-a43f7708-9aaf-11e7-99b0-e1fb6e7b0de0.PNG)

</details>

Used commit from 10 September as I remembered.

**Comment by elmindreda** [comment]
How frequently are you calling the function and how long does it take to execute?

**Comment by capitalknew** [comment]
I getting every frame. It depends on the version of GLFW. The last commit I not seen this leak. I previous commits (I don't know what number) this performance drop not so visible.

**Comment by elmindreda** [comment]
So the performance is acceptable now?

**Comment by capitalknew** [comment]
For OpenGL yeah. For Vulkan API I don't know, I work on Vulkan API version.

**Comment by elmindreda** [comment]
All right, no hurry and thank you for the follow-up! The performance of `glfGetWindowContentScale` should be identical between rendering APIs as it doesn't interface with them at all.

That said, the current implementation is far from optimal and I will try to improve it before 3.3 release.

**Comment by elmindreda** [comment]
There is now also a callback for the window content scale in case polling. See `glfwSetWindowContentScaleCallback`.
