### ISSUE TITLE
User pointer in GLFWjoystickfun

### ISSUE THREAD

**Issue by albinodervall** [glfw/glfw#1080]
All other callback functions has a `GLFWwindow*` which is really useful in conjunction with `glfwGetWindowUserPointer`. This is not the case for `GLFWjoystickfun` though. I understand that this is related to *Joystick state is updated as needed when a joystick function is called and does not require a window to be created or glfwPollEvents or glfwWaitEvents to be called.* in the documentation but this renders the function mostly useless without using a global variable.

Would it be possible to add `GLFWwindow*` as a parameter to `GLFWjoystickfun`, perhaps just passing `NULL` if no window exists?

**Comment by gracicot** [comment]
This affects me also. I almost never rely on mutable global state. However, a simple function without a state pointer sent to it is pretty much useless without some global state.

**Comment by gracicot** [comment]
It seems it adds the requested functionality. Thank you very much!

**Comment by elmindreda** [comment]
@Dav1dde Thank you!
