### ISSUE TITLE
Doxyfile generation does not handle paths with spaces

### ISSUE THREAD

**Issue by poanchen** [glfw/glfw#1081]
OS and version: Ubuntu 16.04 LTS 
Compiler version: g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Release or commit: f4fb25b63df16c8a6d87077d176e7fe1c80c04d3
Steps to reproduce:
1. mkdir folder\ with\ spaces
2. cd folder\ with\ spaces
3. git clone https://github.com/glfw/glfw.git
4. cd glfw
5. cmake CMakeLists.txt
6. make

Build log:
> Scanning dependencies of target docs
[100%] Generating HTML documentation
error: tag HTML_HEADER: header file `/home/poanchen/Downloads/folderwithspaces/glfw/docs/header.html' does not exist
docs/CMakeFiles/docs.dir/build.make:57: recipe for target 'docs/CMakeFiles/docs' failed
make[2]: *** [docs/CMakeFiles/docs] Error 1
CMakeFiles/Makefile2:1257: recipe for target 'docs/CMakeFiles/docs.dir/all' failed
make[1]: *** [docs/CMakeFiles/docs.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

What I observed:
This only happens when the folder name includes spaces. (I tried making a directory without the spaces and it works fine)

Notes:
As you may cleverly figure out, if the path were
`/home/poanchen/Downloads/folder with spaces/glfw/docs/header.html`
instead of
`/home/poanchen/Downloads/folderwithspaces/glfw/docs/header.html`
then it would have been fine

Disclaimer: I am not 100% sure if it was a bug for glfw or cmake. My intention was just wanted to let you guys know this issue and see how we can fix this problem.

Cheers,
Baron

**Comment by elmindreda** [comment]
This should be fixed now with 176ab9a5d273e117bd2b9301430c67fd2125e942. Thank you!

**Comment by poanchen** [comment]
Hi @elmindreda,

I just tried with the latest commit 176ab9a5d273e117bd2b9301430c67fd2125e942 in my machine and it works fine now. Thank you for your speedy response and fix.

Cheers,
Baron
