### ISSUE TITLE
Unnecessary resize callback calls

### ISSUE THREAD

**Issue by mokafolio** [glfw/glfw#1085]
Hi,

In the following minimal example, the resize callback get's called three times, I'd not expect it to be called at all since no resolution change is actually happen:

```
#include <GLFW/glfw3.h>

static void windowSizeCallback(GLFWwindow * _window, int _width, int _height)
{
    printf("GLFW RESIZE %i %i\n", _width, _height);
}

int main(int _argc, const char * _args[])
{
    // initialize glfw
    if (!glfwInit())
        return EXIT_FAILURE;

    // and set some hints to get the correct opengl versions/profiles
    glfwWindowHint(GLFW_SAMPLES, 4);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);

    //create the window
    GLFWwindow * window = glfwCreateWindow(800, 600, "GLAnnotateExample", NULL, NULL);
    if (window)
    {
        glfwSetWindowSizeCallback(window, &windowSizeCallback);
        glfwSetWindowMonitor(window, glfwGetPrimaryMonitor(), 0, 0, 800, 600, GLFW_DONT_CARE);
        glfwMakeContextCurrent(window);

        // main loop
        while (!glfwWindowShouldClose(window))
        {
            //...

            glfwSwapBuffers(window);
            glfwPollEvents();
        }
    }
    else
    {
        glfwTerminate();
        printf("Could not open GLFW window :(\n");
        return EXIT_FAILURE;
    }

    // clean up glfw
    glfwDestroyWindow(window);
    glfwTerminate();

    return EXIT_SUCCESS;
}
```
I get the output where 1440 x 900 is the fullscreen resolution and 800x600 the one of the actual video mode that is finally picked:
```
GLFW RESIZE 800 600
GLFW RESIZE 1440 900
GLFW RESIZE 800 600
```

I am aware that this example is a little bit nonsense as of course I could initialize the window as fullscreen, but the same is happening if I go fullscreen to any other resolution, i.e. I get resize callbacks of the following logic when going fullscreen with a vidmode change:

1. resize callback for original window size
2. resize callback for current video mode
3. resize callback for new video mode

In that scenario the expected behavior is only step 3 in my opinion. If you do heavy lifting whenever the window is resized, i.e. loading /resizing a bunch of assets, this is actually kind of annoying.

Let me know what you think!

Thanks!

**EDIT:** 
This does not appear to be exclusively related to vidmode change, as if you go fullscreen without a vidmode change, you still get two instead of one resize callbacks a la:

1. resize callback for original window size
2. resize callback for fullscreen size

I'd only expect step two in that scenario.

**Comment by raysan5** [comment]
I'm experimenting the same issue on Windows 10 64bit.

I create a windowed program with:
```c
int screenWidth = 800;    // Global
int screenHeight = 450;   // Global
```
then I toggle to fullscreen using:
```c
glfwSetWindowMonitor(window, glfwGetPrimaryMonitor(), 0, 0, screenWidth, screenHeight, GLFW_DONT_CARE);
```
I see that `WindowsSizeCallback()` is launched and new `width` and `height` values are passed, they seem to be set to the closest monitor supported standard resolution: **720x480**

This is my print values from `WindowsSizeCallback()` on this process (go and return to fullscreen):
```
**GLFW RESIZED to 1920 1080**     // Is this expected?
GLFW RESIZED to 720 480
GLFW RESIZED to 800 450
```
