### ISSUE TITLE
Make the compiling step more explicit

### ISSUE THREAD

**Issue by philippefutureboy** [glfw/glfw#1088]
Hi! 

I rarely use cmake/make on my UNIX distributions, and as such I have limited knowledge to how to use said programs. I am a web dev trying to learn WebGL through OpenGL, and the formulation of the step "Compiling the library" on the page [Compiling GLFW](http://www.glfw.org/docs/latest/compile_guide.html#compile_deps_x11) is a bit obscure. 

I suggest that rather than the current:

```md
## Compiling the library
You should now have all required dependencies and the project files or makefiles necessary to compile GLFW. Go ahead and compile the actual GLFW library with these files, as you would with any other project.

...
```

The following be used:

```md
## Compiling the library
You should now have all required dependencies and the project files or makefiles necessary to compile GLFW. You can now compile the GLFW library with these files. You can generally do so with 

\```
cd <glfw-root-dir>
make install
\```
```

Cheers! 👍

**Comment by ferreiradaselva** [comment]
Hi, @philippefutureboy, the actual process is explained in the section before, using `cmake`: http://www.glfw.org/docs/latest/compile_guide.html#compile_generate

```
mkdir glfw-build
cd glfw-build
cmake <glfw-root-dir>
`

So, if you downloaded the library to `/home/username/glfw`, you can make something like:
```
cd /home/username/glfw
mkdir build
cd ./build
cmake ..
make
```
`cmake` will generate the Makefile based on the `CMakeLists.txt` that is on the "up" directory (that is specified by the `..`). Then, after the Makefile is generated, you can build using `make`. The built library will be in the current directory `build/`.

**Comment by philippefutureboy** [comment]
Fair point! I suggest then that the use of make be made explicit in the http://www.glfw.org/docs/latest/compile_guide.html#compile_generate section with:

```
mkdir glfw-build
cd glfw-build
cmake <glfw-root-dir>
```

being supplemented with `make` at the end of the code snippet.

Let me know,
Cheers ✨

**Comment by davidvmckay** [comment]
I rebuilt this project 3 times before **guessing** that I just needed to run `make` ... and even then, didn't know to `make install` so my other lib (wgpu-native) could find glfw for includes.

Trying to build [wgpu-native](https://github.com/gfx-rs/wgpu-native/wiki/Getting-Started) in wsl2 on Windows 11, requires glfw dependency to be built manually -- but I only know enough about building binaries on linux to confuse myself when I actually try to do it.

Coming from 20 years of coding on M$FT and / or nodeJS tech stacks, to me it just wasn't [obvious like the glfw docs expected](https://www.google.com/search?q=Go+ahead+and+compile+the+actual+GLFW+library+with+these+files%2C+as+you+would+with+any+other+project).
