### ISSUE TITLE
Full window transparency

### ISSUE THREAD

**Issue by elmindreda** [glfw/glfw#1089]
Support for specifying a single alpha value for the whole window. Suggested hint and attribute name is `GLFW_OPACITY`. Implemented on Windows as `LWA_ALPHA`, on macOS as `NSWindow alphaValue` and on X11 as `_NET_WM_WINDOW_OPACITY`. Unlike framebuffer transparency this can be updated at any time after window creation.

This will require renaming `GLFW_TRANSPARENCY` to avoid confusion. Some possible new names are `GLFW_TRANSPARENT_FRAMEBUFFER` and `GLFW_OPACITY_FROM_FRAMEBUFFER`.

**Comment by ckaran** [comment]
How about `GLFW_OPACITY_FOR_WINDOW` and `GLFW_OPACITY_FOR_FRAMEBUFFER`?  Keeps the names related, so once you learn the idea for one, the idea for the other should be fairly obvious.

**Comment by linkmauve** [comment]
Wayland doesn’t support this feature, and it’s unlikely for it to ever support it.  The user is expected to provide a buffer containing the correct alpha values, instead of having a second multiplier applied to it.

Weston does provide this as a user control, same as resize or rotate, but it’s fully a user thing, and not part of the protocol.

**Comment by elmindreda** [comment]
@ckaran I like `GLFW_OPACITY_FOR_WINDOW`. It expresses exactly what the specified value does. `GLFW_OPACITY_FOR_FRAMEBUFFER` doesn't, though. That value is a boolean and not the opacity of the framebuffer.

@linkmauve Noted. This could be expressed by always returning full opacity via the window attribute whatever it's set to. Would that be acceptable or would you recommend leaving this feature out entirely?

**Comment by linkmauve** [comment]
That would be totally acceptable, I can perfectly imagine a future compositor exposing a protocol for that feature.

**Comment by ckaran** [comment]
@elmindreda OK, how about `GLFW_FRAMEBUFFER_IS_OPAQUE` instead of `GLFW_OPACITY_FOR_FRAMEBUFFER`?

**Comment by tombsar** [comment]
Naming is hard. I vote for `GLFW_TRANSPARENT_FRAMEBUFFER` and `GLFW_OPACITY` (or `GLFW_WINDOW_OPACITY` for maximum differentiation).

**Comment by raysan5** [comment]
Why not make it more consistent like `{lib}_{object]_{property}`?
```
GLFW_FRAMEBUFFER_TRANSPARENT
GLFW_WINDOW_OPACITY
```

**Comment by tombsar** [comment]
@raysan5 I completely agree in principle, but that would not be consistent with the existing hints and attributes exposed by GLFW (http://www.glfw.org/docs/3.3/window_guide.html#window_hints_wnd).

**Comment by elmindreda** [comment]
My thinking was that _window_ is both the top level object in GLFW and is implied by the function name, i.e. `glfwWindowHint`, `glfwGetWindowAttrib`, etc, so it's `{lib}_[subobject_]{property}`.

**Comment by elmindreda** [comment]
Been thinking about this Far Too Long.

`GLFW_OPACITY_FROM_FRAMEBUFFER` says exactly what the feature does and uses the same keyword as this feature (whole window opacity) but sounds esoteric and weird.
`GLFW_FRAMEBUFFER_IS_OPAQUE`, `GLFW_OPAQUE_FRAMEBUFFER` are clear and clearly booleans but suffer from double negation, i.e. the "set disabled = false" problem.

So `GLFW_TRANSPARENT_FRAMEBUFFER` won. It sounds like a boolean and contains the words people are most likely to search for.

**Comment by bpunsky** [comment]
```
glfwWindowHint(GLFW_TRANSPARENT_FRAMEBUFFER, GLFW_TRUE);
```
seems to be making the contents of my window completely transparent, including a semi-opaque clear color and/or stuff that's being drawn by opengl

windows 10, nvidia

**Comment by pedroosorio** [comment]
@elmindreda i can confirm what @bpunsky is saying, running the gears example or setting the hint to True will make everything go transparent. Is there something regarding BlendFuncs that i'm missing ?

**Comment by elmindreda** [comment]
Please open a separate issue for this bug. This issue is about adding the feature.

**Comment by pedroosorio** [comment]
@elmindreda just did, #1237 ;)
