### ISSUE TITLE
Send control characters to charModsCallback.

### ISSUE THREAD

**Issue by ccxvii** [glfw/glfw#1091]
At the moment, at least on X11, regular control characters don't make it to the charModsCallback. It would be very useful for me if I could catch things like Ctl+S in the character callback. Using the keyCallback doesn't work for me, since it does not translate the key using the current keyboard layout (so dvorak or azerty users will not have the correct key mapping).

I have created an accompanying pull request that implements this on X11.

**Comment by elmindreda** [comment]
This is related to #1090.

**Comment by elmindreda** [comment]
The charmods callback has been deprecated and no further fixes will be made to it.
