### ISSUE TITLE
Please allow software rendering contexts.

### ISSUE THREAD

**Issue by ccxvii** [glfw/glfw#1092]
The context creation hardcodes checks for accelerated contexts. My application doesn't mind having a non-accelerated software rendering context, and it would be very helpful if I could tell glfw that HW acceleration is not required so that I can test my software in virtualbox and other systems that don't have HW accelerated drivers installed.

**Comment by RicoP** [comment]
Alternative sugestion, it would be sweet if we could have a null_context.c which we can link to, in case when we dont need an rendering backend at all.

**Comment by elmindreda** [comment]
@RicoP If you don't want a window to have a context then set the `GLFW_CLIENT_API` hint to `GLFW_NO_API`.

**Comment by elmindreda** [comment]
@ccxvii This seems to be a duplicate of #589.

**Comment by chipweinberger** [comment]
Could you share your code on how to make GLFW work with windows remote desktop?

**Comment by RicoP** [comment]
GLFW should work fine on a remote desktop, the only problem you might could encounter is, when you try to create a graphics context, because remote desktops often lack hardware acceleration.
