### ISSUE TITLE
Restoring window (after iconification(minimization)) causes the context to not be current.

### ISSUE THREAD

**Issue by c4ooo** [glfw/glfw#1093]
I am on windows 7 64 bit with an Intel iGPU. If I iconify (minimize) a window by clicking the "-" in the top right corner, and then un-iconify(open) the window again, the window become blank even though my main loop is still running. Note that the window doesn't become blank when I _iconify_ it, but when I _un-iconify_ it. Even when iconified, the window is still working correctly (I can see with the windows aero theme), however as soon as I un-iconify it, it stops working. (This doesn't happen when i simply switch to a different window and then back to my glfw window)

I can fix this by adding a window_iconify_callback, and calling "glfwMakeContextCurrent(window);" inside the callback, which i guess means that the context is dropped when the window is un-iconified.

**Comment by elmindreda** [comment]
What is the output of `glfwinfo` on your machine?

**Comment by c4ooo** [comment]
How do i use glfwinfo? It the i cant find the call in the API, unless maybe i have an outdated version or something.

**Comment by elmindreda** [comment]
`glfwinfo` is a test program, found in the `tests` directory. It is built along with the library when you compile GLFW from source.

If you're using a binary release, instead post the GLFW version number and the version of your GPU driver.

**Comment by c4ooo** [comment]
I am using the 3.2.1 GLFW binaries. My have the GM45 iGPU ("Mobile Intel 4 series express chipset family") in my laptop, the driver version being 8.15.10.1883. 

(I need to upgrade my PC V: )

**Comment by elmindreda** [comment]
I cannot reproduce this and haven't ever encountered this before. Try updating the GPU driver.

**Comment by c4ooo** [comment]
All drivers are up to date, but becouse support for that chipset was dropped a long time ago, i would not be surprised if there were still bugs like this.

**Comment by elmindreda** [comment]
Does this happen even with a very basic program, say [this one](http://www.glfw.org/documentation.html)?

**Comment by c4ooo** [comment]
Well, i couldn't actually test the issue with the basic program becouse it doesn't actually contain any drawing, so i added a simple fixed pipeline triangle. (https://pastebin.com/eEEAEt1m)  After doing so, i observed that this issue did not occur.

Another thing i noticed was that glfwGetWindowSize always returned 0 for both width and height when the window was iconified. (But not when simply a different window was opened instead.)

I though that perhaps having two glfw windows in two separate threads (main, plus a ImGui interface) was causing the issue, but in my main menu, (when second window isn't opened yet), this issue was still occurring.

**Comment by elmindreda** [comment]
> Well, i couldn't actually test the issue with the basic program becouse it doesn't actually contain any drawing, so i added a simple fixed pipeline triangle. After doing so, i observed that this issue did NOT occur.

Are you updating the OpenGL viewport in your application when the framebuffer size changes?

> Another thing i noticed was that glfwGetWindowSize always returned 0 for both width and height when the window was iconified, but returning to normal values once the window was open again.

This is normal behavior on Windows.

**Comment by c4ooo** [comment]
Yes i set glViewport() every frame.

**Comment by elmindreda** [comment]
I don't know what is causing this, then.

**Comment by c4ooo** [comment]
Well, i am having the exact same issue with SDL, so ¯\\\_(ツ)_/¯
(Unfortunately the fix i use with GLFW does not work with SDL though)
