### ISSUE TITLE
/usr/bin/ld: /usr/local/lib/libglfw3.a(x11_window.c.o): undefined reference to symbol 'XConvertSelection' //usr/lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line

### ISSUE THREAD

**Issue by csuwp** [glfw/glfw#1095]
I compile my project using this GLFW.But the comes the error like this .
/usr/bin/ld: /usr/local/lib/libglfw3.a(x11_window.c.o): undefined reference to symbol 'XConvertSelection'
//usr/lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line

I am using cmake to build my project ,and I find all the dependencies . But still goes the error ,is there anyone can help me to solve this problem ?

**Comment by xCuri0** [comment]
Your X libraries seem to not contain the function.Can you try updating them ?

**Comment by csuwp** [comment]
Problem solved,because we should reorder the linking lib process

**Comment by xCuri0** [comment]
@csuwp close this then

**Comment by DavidTorresOcana** [comment]
Hello

I am having this exact same error when trying to compile wit glfw.
Here a snapshot of my CMakeLists.txt : 
`set(glfw_INCLUDE_DIR /usr/local/include/)
set(glfw_LIBRARY /usr/local/lib/libglfw3.a)
include_directories(
  ${glfw_INCLUDE_DIRS}   .....)
target_link_libraries(MyApp
  ${glfw_LIBRARY}
....)
`
What is wrong here? Please help

Regards

**Comment by elmindreda** [comment]
@DavidTorresOcana Have a look at the [Linking with CMake and installed GLFW binaries](http://www.glfw.org/docs/3.3/build_guide.html#build_link_cmake_package) section of the documentation.
