### ISSUE TITLE
Documentation: minor typo in the Window guide

### ISSUE THREAD

**Issue by anton-kl** [glfw/glfw#1099]
The last paragraph in the ["Full screen windows"](http://www.glfw.org/docs/latest/window_guide.html) section states as follows:

> By default, the original video mode of the monitor will be restored and the window iconified if it loses input focus, to allow the user to switch back to the desktop. This behavior can be disabled with the GLFW_AUTO_ICONIFY window hint, for example if you wish to simultaneously cover multiple windows with full screen windows.

I believe last words were meant to be written as

> cover multiple _monitors_ with full screen windows.

instead of 

> cover multiple _windows_ with full screen windows.

Cheers, and thanks for all your work! You are doing great things here.

**Comment by elmindreda** [comment]
Well spotted, thank you! This should be fixed now with 66c0394ae19c24483a5228eeaa179945206768ab.
