### ISSUE TITLE
Inconsistency in position and size documentation

### ISSUE THREAD

**Issue by ghuser404** [glfw/glfw#1104]
The latter section doesn't mention that the callback will be triggered by your own code, when in reality it is, at least on Windows.
> If you wish to be notified when a window is moved, whether by the user, system or your own code, set a position callback.
> `glfwSetWindowPosCallback(window, window_pos_callback);`

> If you wish to be notified when a window is resized, whether by the user or the system, set a size callback.
> `glfwSetWindowSizeCallback(window, window_size_callback);`

**Comment by elmindreda** [comment]
Thank you!
