### ISSUE TITLE
GLFW_CENTER_CURSOR is not GLFW_TRUE by default

### ISSUE THREAD

**Issue by ghuser404** [glfw/glfw#1105]
> GLFW now supports controlling whether the cursor is centered over newly created
> full screen windows with the [GLFW_CENTER_CURSOR](ref GLFW_CENTER_CURSOR_hint)
> window hint.  It is enabled by default.

> GLFW_CENTER_CURSOR            | `GLFW_TRUE`                 | `GLFW_TRUE` or `GLFW_FALSE`

It's not set to `GLFW_TRUE` in `glfwDefaultWindowHints()`, so by default it's `GLFW_FALSE`.

**Comment by elmindreda** [comment]
Well spotted, thank you!
