### ISSUE TITLE
GLFW crash NSAutoReleasePool in a Cocoa app

### ISSUE THREAD

**Issue by AndySomogyi** [glfw/glfw#1107]
Hi, 

I'm using GLFW in a Cocoa app, I can create and interact with a GLFW window just fine, however, void ```_glfwPlatformDestroyWindow``` crashes in the call to ```[_glfw.ns.autoreleasePool drain];```

This happens whenever I try to call ```glfwDestroyWindow(window);```, either from inside the window close callback, or from another message. 

In fact, ANY glfw call that invokes ``` [_glfw.ns.autoreleasePool drain];```, such as ```void _glfwPlatformPollEvents(void)``` results in a segfault. 

I've got a git repo that demonstrates this issue:

https://github.com/AndySomogyi/CocoaGLFW

I basically took the GLFW example, and hooked up to a Cocoa app, the exact file that interacts with GLFW is 

https://github.com/AndySomogyi/CocoaGLFW/blob/master/GLFWTest.cpp

It's actually *REALLY* important that I can use GLFW with the native UI, as our app will use WPF on Windows, and Cocoa on Mac.

**Comment by elmindreda** [comment]
> This happens whenever I try to call ```glfwDestroyWindow(window);```, either from inside the window close callback, or from another message. 

[You may not destroy windows in callbacks](http://www.glfw.org/docs/latest/intro.html#reentrancy).

> In fact, ANY glfw call that invokes ``` [_glfw.ns.autoreleasePool drain];```, such as ```void _glfwPlatformPollEvents(void)``` results in a segfault. 

Cocoa pushes its own autorelase pool on the stack each run loop iteration, just like GLFW does when polling events. You could rewrite the GLFW bit to have this mostly work, but this isn't how GLFW is intended to be used. It expects to initialize AppKit, not the other way around.

> It's actually REALLY important that I can use GLFW with the native UI, as our app will use WPF on Windows, and Cocoa on Mac.

Why not use an `NSOpenGLView` if you're writing native Cocoa code?

**Comment by AndySomogyi** [comment]
I'm using GLFW because I would like to have as much of the core of our app cross-platform, and only the UI be platform-specific, and GLFW is a nice layer that gives a cross-platform way of making OpenGL windows. 

I could wrap an NSOpenGLView in my own cross-platform layer, but GLFW already does that. Also, I want all of the cross-platform code in a shared library, and I'm not entirely sure how to create an NSOpenGLView based window without a xib, and I'm not sure how to embed a xib/nib into a shared library.

**Comment by AndySomogyi** [comment]
Regarding Reentrancy as per the link, is it possible to call these non-reentrant functions from a non-GLFW callback, i.e. from the main application delegate, or a message handler in a non-GLFW window? 

I've tried that and the ```glfwDestroyWindow``` function crashes there also when it sends the ```drain``` message to the autorelease pool.

**Comment by ghuser404** [comment]
@AndySomogyi, you should also watch for the following notes in the docs: **This function must only be called from the main thread.** This note basically means that the function must only be called from main thread, because it probably deals with windowing functionality.

**Comment by AndySomogyi** [comment]
The test app does not create any threads, everything is in response to messages on the main UI thread. 

I have a possible fix through. 

The 

```
struct _GLFWlibraryNS
{
   ...
   id                  autoreleasePool;
   ...
}```

appears to be there to serve as the main NSAutoReleasePool when GLFW is running the main application loop. However, in a Cocoa app, you always use the main NSApplication loop, which already has an autorelease pool. 

I've performed a little experiment, and added a 

```
glfwUseNSApplicationEventLoop(bool)
``` 

function to glfw3native.h, and this set a bool that I added to ```GLFWlibraryNS``` that tells glfw that the native event loop is used, and not use the ```GLFWlibraryNS::autoreleasePool``` pool. Basically, I surround the calls to ```[_glfw.ns.autoreleasePool drain] / alloc/init``` with an ```if (_glfw.ns.useNativeReleasePool)```. 

This approach seems to work, and according to the XCode leak checker, all the objects do get freed correctly.

**Comment by AndySomogyi** [comment]
I've come up with I think a much more elegant solution than my previous one. 

I think I've figured out how to get GLFW to automatically detect if it's running with an existing NSApplication event loop provided NSAutoreleasePool, or if it's running in the GLFW provided event loop, and automatically perform the right action with the ``` [_glfw.ns.autoreleasePool drain] / alloc/init ```. 

This change requires zero API changes, and only fixes the bug under Cocoa. 

I'm going to test this solution out a bit this weekend, and I'll add a Cocoa test application under glfw examples. 

Any comments on this solution before I go ahead and implement it, and submit an pull request?

**Comment by AndySomogyi** [comment]
I've come up with I think a much more elegant solution than my previous one.

I think I've figured out how to get GLFW to automatically detect if it's running with an existing NSApplication event loop provided NSAutoreleasePool, or if it's running in the GLFW provided event loop, and automatically perform the right action with the [_glfw.ns.autoreleasePool drain] / alloc/init.

This change requires zero API changes and fixes the bug under Cocoa.

I'm going to test this solution probably tomorrow, and I'll add a Cocoa-based test app under examples. 

@elmindreda, any comments on this solution before I go ahead and implement it. If this approach works and tests out using both the new Cocoa test app, and verifies that the existing apps work correctly, should I submit it as a pull request for the master branch, or should I make a new branch and submit that as a PR? Note, this approach will end up adding a couple static functions to the cocoa_window.m file, and a few changes there, and will add a new example app.

**Comment by elmindreda** [comment]
GLFW now wraps platform functions in `@autoreleasepool` blocks, which should resolve this and similar issues.
