### ISSUE TITLE
Window appears white upon creation

### ISSUE THREAD

**Issue by ghuser404** [glfw/glfw#1116]
On my machine, on Windows, this code doesn't seem to do anything, as it is run before `ShowWindow`:
```
// Clearing the front buffer to black to avoid garbage pixels left over from
// previous uses of our bit of VRAM
{
    PFNGLCLEARPROC glClear = (PFNGLCLEARPROC)
        window->context.getProcAddress("glClear");
    glClear(GL_COLOR_BUFFER_BIT);
    window->context.swapBuffers(window);
}
```
This comes as a slight issue when resizing:
I clear colour buffer to black, then try to resize (increase size), and see a ~5px white border just outside the initial framebuffer.

**Comment by elmindreda** [comment]
Use the window refresh callback or rendering from a non-main thread to keep the window contents sane during window resize on Windows. The window refresh callback is effectively `WM_PAINT`.

Will look into whether that initial clear still makes sense.

**Comment by ghuser404** [comment]
@elmindreda, I'm actually rendering from a separate thread. But I'm having an issue, which I didn't mention originally: when I resize the window, there is a mysterious white box appearing at the sides, when the window is enlarged. My guess is that it's because buffer swapping happens from a different thread.

Anyway, the resize still looks a bit jittery. I'm currently looking if I could make it act like this:
when resize is in progress, do not draw new content but stretch the current picture, while still processing the game logic (game logic and rendering happens on a separate thread).

Do you have any pointers on how this could be achievable?

**Comment by ghuser404** [comment]
I think I should try to switch rendering from a separate thread to refresh callback, when resize is in progress.

**Comment by ghuser404** [comment]
I've come up with a solution, maybe someone will find it interesting or will comment if it's good or bad. I'm not sure how practical it is (with a lot of stuff to draw), but it's definitely less/not jittery.

In `FramebufferSize` callback save new width and height, then set atomic bools `a` and `b` to **true**, and wait (busy wait with yield) until `b` is set to **false**. `b` is set to **false** after a secondary thread swaps buffers, but it can only set `b` to **false** if `a` is **false** too - that said, `a` is set to **false** when new width and height are read [from the secondary thread].

This approach is lock-free, so should not be a hit on performance - of course, it blocks the main thread for a while, but my guess is that it shouldn't be a huge problem.

**Comment by ghuser404** [comment]
> Will look into whether that initial clear still makes sense.

It seems to be happening because I'm creating a window with `GLFW_VISIBLE` hint.
Closing this ticket.
