### ISSUE TITLE
Initial stick position is not at (0;0)

### ISSUE THREAD

**Issue by NukeBird** [glfw/glfw#1117]
I tested it on dualshock 4 and gamepad by logitech

Dualshock: 
```
Left stick (-0.0312352, -0.00779736)
Right stick (-0.00779736, -1)
```

Logitech:
```
Left stick (-0.00779736, -0.00778736)
Right stick (1.5258e-05, -0.00779736)
```

My code:
```cpp
#include <iostream>
#include <GLFW/glfw3.h>

void joystick_callback(int joy, int event)
{
	if (event == GLFW_CONNECTED)
	{
		std::cout << "Gamepad #" << joy << " connected (" <<
			glfwGetJoystickName(joy) << ")" << std::endl;
	}
	else if (event == GLFW_DISCONNECTED)
	{
		std::cout << "Gamepad #" << joy << " disconnected" << std::endl;
	}
}

int main()
{
	glfwInit();
	glfwSetJoystickCallback(joystick_callback);

	auto w = glfwCreateWindow(100, 100, "", 0, 0);

	while (glfwGetKey(w, GLFW_KEY_ESCAPE) == GLFW_RELEASE)
	{
		glfwPollEvents();

		int axes_count = 0;
		const float* axes = glfwGetJoystickAxes(GLFW_JOYSTICK_1, &axes_count);

		if (axes_count >= 4)
		{
			std::cout << "Left stick (" << axes[0] << ", "
				<< axes[1] << ")" << std::endl;

			std::cout << "Right stick (" << axes[2] << ", "
				<< axes[3] << ")" << std::endl;
		}

		glfwSwapBuffers(w);
	}

	glfwTerminate();
}
```

**Comment by NukeBird** [comment]
I must somehow normalize it? 

Anyway, why right stick of dualshock returns -1?

**Comment by fractilegames** [comment]
Are you sure axis 3 is the right stick Y? DualShock triggers report values in range -1 .. 1, so when released, the axis would show -1.

You should not assume that released axis position is exactly zero. Apply some sort of dead-zone in your code.

**Comment by NukeBird** [comment]
@fractilegames something like this?:
```
#include <iostream>
#include <GLFW/glfw3.h>
#include <glm/glm.hpp>
#include <glm/gtx/string_cast.hpp>

glm::vec2 dead_zone_stick1;
glm::vec2 dead_zone_stick2;

void config_dead_zone()
{
	int axes_count = 0;
	const float* axes = glfwGetJoystickAxes(GLFW_JOYSTICK_1, &axes_count);
	
	if (axes)
	{
		dead_zone_stick1 = { axes[0], axes[1] };
		dead_zone_stick2 = { axes[2], axes[3] };
	}
}

void joystick_callback(int joy, int event)
{
	if (event == GLFW_CONNECTED)
	{
		config_dead_zone();
		std::cout << "Gamepad #" << joy << " connected (" <<
			glfwGetJoystickName(joy) << ")" << std::endl;
	}
	else if (event == GLFW_DISCONNECTED)
	{
		std::cout << "Gamepad #" << joy << " disconnected" << std::endl;
	}
}

glm::vec2 get_stick(unsigned id)
{
	int axes_count = 0;
	const float* axes = glfwGetJoystickAxes(GLFW_JOYSTICK_1, &axes_count);

	glm::vec2 stick;

	if (axes)
	{
		stick = { axes[id*2], axes[id*2 + 1] };

		if (glm::distance(stick, dead_zone_stick1) < 0.05)
			return { 0.0, 0.0 };
	}

	return stick;
}

int main()
{
	glfwInit();
	glfwSetJoystickCallback(joystick_callback);

	auto w = glfwCreateWindow(100, 100, "", 0, 0);

	config_dead_zone();

	while (glfwGetKey(w, GLFW_KEY_ESCAPE) == GLFW_RELEASE)
	{
		glfwPollEvents();

		std::cout << "Left stick: " << glm::to_string(get_stick(0)) << std::endl;
		std::cout << "Right stick: " << glm::to_string(get_stick(1)) << std::endl;

		glfwSwapBuffers(w);
	}

	glfwTerminate();
}
```

**Comment by fractilegames** [comment]
That's one way to do it. You should read this: http://www.third-helix.com/2013/04/12/doing-thumbstick-dead-zones-right.html

**Comment by shurcooL** [comment]
Issue #1001 appears to be related. Also see https://github.com/glfw/glfw/issues/1001#issuecomment-299205380 by @elmindreda:

> GLFW does apply a very basic dead zone with XInput devices, where the dead zone data is specified, but not for DirectInput or on other platforms, where it isn't. Applying one in your application is therefore a very good idea.

@NukeBird, what OS are you testing this on?

**Comment by NukeBird** [comment]
@shurcooL I test it on Windows 10

**Comment by shurcooL** [comment]
Do you know if XInput or DirectInput is being used for those 2 joysticks?

**Comment by NukeBird** [comment]
@fractilegames "Scaled Radial Dead Zone" looks cool:
```
float deadzone = 0.25f;
    Vector2 stickInput = new Vector2(Input.GetAxis(“Horizontal”), Input.GetAxis(“Vertical”));
    if(stickInput.magnitude < deadzone)
        stickInput = Vector2.zero;
    else
        stickInput = stickInput.normalized * ((stickInput.magnitude - deadzone) / (1 - deadzone));
```
But I don't think that it will work ok with dualshock (here is '-1' number! =( )
Btw I implemented this function a little bit different:
```
glm::vec2 get_stick(unsigned id)
{
	int axes_count = 0;
	const float* axes = glfwGetJoystickAxes(GLFW_JOYSTICK_1, &axes_count);

	glm::vec2 stick;
	const float dead_zone = 0.14f;

	if (axes)
	{
		stick = { axes[id*2], axes[id*2 + 1] };

		if (glm::length(stick) <= dead_zone)
			return { 0, 0 };
	}

	//map dead_zone..1 range to 0..1
	stick = (stick - glm::sign(stick) * dead_zone) / (1.0f - dead_zone);

	return stick;
}
```
Now logitech gamepad works OK, but not dualshock one

>>Do you know if XInput or DirectInput is being used for those 2 joysticks?
@shurcooL I don't know =(

**Comment by NukeBird** [comment]
>Are you sure axis 3 is the right stick Y? DualShock triggers report values in range -1 .. 1, so when released, the axis would show -1.

but why only axis[3] == -1 when everything released? 
IDK how to handle it properly :(

**Comment by elmindreda** [comment]
Perhaps the gamepad functions can help?

**Comment by fractilegames** [comment]
Unless you have installed some external driver for the DS4, you're probably using it through DirectInput. I dug up this axis configuration for DualShock4 (Windows, DirectInput) from my old "gamepad database":
```
		<axes>
			<leftx>0</leftx>
			<lefty>1</lefty>
			<lefttrigger>3</lefttrigger>
			<rightx>2</rightx>
			<righty>5</righty>
			<righttrigger>4</righttrigger>
		</axes>
```
According to that the right stick Y-axis should be the sixth axis.

Anyways, if you wan't support multiple gamepads, you should look into SDL game controller database support recently added to GLFW and coming in the next release.

**Comment by NukeBird** [comment]
>Anyways, if you want to support multiple gamepads, you should look into SDL game controller database support recently added to GLFW.

Wow, amazing! Why such functionality still not documented?

**Comment by NukeBird** [comment]
@fractilegames THANK YOU VERY MUCH

It is really useful

**Comment by cblc** [comment]
FWIW, SDL has SDL_JoystickGetAxisInitialState() which provides the value of an axis at rest (so the true "zero" for an axis). I'm not sure if implementing a dead zone is always a good idea, because if the purpose is to cancel jittery values, then what you need is not a dead zone, but an anti-jitter code (which is a must both for analog sticks and for paddles/wheels). If you know the true zero for an axis, and you have anti-jitter code, I tend to believe you don't want a dead zone at all.

**Comment by cblc** [comment]
Personally, I'd suggest reopening this issue and implementing something similar to SDL_JoystickGetAxisInitialState()
