### ISSUE TITLE
Add compilation option to control _GLFW_WNDCLASSNAME

### ISSUE THREAD

**Issue by ghuser404** [glfw/glfw#1120]
It may be worth adding a compilation option to control `_GLFW_WNDCLASSNAME`.
This string is observable via programs such as `inspect.exe`.

**Comment by ghuser404** [comment]
Or even, make it a Windows-specific window hint - if someone wants to specify a different string for multiple windows.

**Comment by elmindreda** [comment]
Why would you want to change the window class name?

**Comment by ghuser404** [comment]
Just for customizability, I guess. But I'm not sure how valid this request is. I guess if someone really wanted to change it, they could just change it in code and compile the library.

**Comment by elmindreda** [comment]
Yeah, I'm hoping that's enough. Usually its only job is to be unique.

**Comment by irov** [comment]
Hi, please open this problem.
I create the plugins for the After Effect, and chose this library to create the OpenGL context. But as soon as I have two different effects in my scene, I get

_glfwInputError (GLFW_PLATFORM_ERROR,
                         "Win32: Failed to register window class");

Thank you

**Comment by elmindreda** [comment]
@irov It sounds like you have more than one copy of the GLFW library in your process. One in each plugin binary, I'm guessing. GLFW does not support this and it would be very difficult to do so.

Try having the plugins share a single GLFW DLL.

**Comment by irov** [comment]
this is all the code for fixing this problem

> #ifndef _GLFW_WNDCLASSNAME
> #define _GLFW_WNDCLASSNAME L"GLFW30"
> #endif

**Comment by ghuser404** [comment]
@elmindreda What if someone happens to use 2 different GLFW applications from different developers? Think those After Effect plugins. One of the developers gets bad review on their app.
There seems to be no proper way for developer to make their app [more or less] unique in that regard.

**Comment by ghuser404** [comment]
@irov Your solution will not work, because _GLFW_WNDCLASSNAME is used by GLFW during library compilation, so you can't change it in runtime.

However, I'm not sure that it would be `very difficult to do` like @elmindreda said. How I see this could be approached is instead of using `#define`, this string could be kept in a variable. GLFW could provide a Windows-specific API for setting this string, like an initialisation hint or similar.

**Comment by irov** [comment]
@ghuser404 Of course my solution is not as good as @elmindreda, but it solves my problems at this stage and is quickly implemented. And with it, I can wait until the implementation of @elmindreda

**Comment by ghuser404** [comment]
That will work if you're building GLFW as part of your build plan.

**Comment by irov** [comment]
@ghuser404 yes, i have build plan

    ExternalProject_Add(glfw_download PREFIX glfw
        GIT_REPOSITORY https://github.com/glfw/glfw.git
        GIT_TAG 3.2
            
        UPDATE_COMMAND ""
      
        CMAKE_ARGS 
            "-DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>"
            "-DGLFW_BUILD_EXAMPLES=OFF"
            "-DGLFW_BUILD_TESTS=OFF"
            "-DGLFW_BUILD_DOCS=OFF"
            "-DUSE_MSVC_RUNTIME_LIBRARY_DLL=OFF"    
    )
here I would add this, define

**Comment by 54hahaya** [comment]
First drag glfw3.lib to any hexadecimal viewer (I used HxD.exe),
 then search for the string GLFW30, the character encoding is set to UTF-16,
Save it after modification, (! !  Note: The format and length of the modified class name should be the same as the original class name)
![1](https://github.com/user-attachments/assets/b0d6d4eb-3745-436a-a711-fe54c0fc0f7f)
