### ISSUE TITLE
Request header guard in internal.h

### ISSUE THREAD

**Issue by raysan5** [glfw/glfw#1127]
I decided to include GLFW sources in my project [raylib](https://github.com/raysan5/raylib) to avoid dependencies issues that I found in some platforms (https://github.com/glfw/glfw/issues/1051).

I created [rglfw.c](https://github.com/raysan5/raylib/blob/develop/src/rglfw.c) including all GLFW library sources to be compiled as a single module... but I got an error due to the multiple `internal.h` inclusions.

To solve that, just added a `#pragma once` at the beginning [of the file](https://github.com/raysan5/raylib/blob/develop/src/external/glfw/src/internal.h#L28). Could it be added in the official repo version?

**Comment by elmindreda** [comment]
Thank you!

This is a regression introduced by 372e908682f1b467b7aa31090b0abb2e25e921b8. I forgot to keep the outermost ones for unity builds. Have to get round to adding a unity build to the CI.

**Comment by raysan5** [comment]
Many thanks @elmindreda for the quick fix! :)
