### ISSUE TITLE
glfwGetVideoMode crashes on Windows due to bad monitor pointer when a mirror device driver is active (RealVNCServer)

### ISSUE THREAD

**Issue by georgevanvenrooij** [glfw/glfw#1135]
While testing with GLFW 3.2.1 on Windows 7, I noticed a crash (access violation) in glfwGetVideoMode() in win32_monitor.c at line 339 whenever a VNC client is connected to the machine. This crash does NOT happen if no clients are connected to the VNC server.

The cause of the crash is that the call to EnumDisplaySettingsW() is given a bad monitor pointer.
Backtracking this to its cause lead me to a possible bug in _glfwPlatformGetMonitor() around the areas at line 194:

In my test, the following if-statement is TRUE first for the actual physical display adapter AND the mirror device driver:

`        if (adapter.StateFlags & DISPLAY_DEVICE_PRIMARY_DEVICE)
            primaryIndex = found;
`

the next loop, guarded by `if (hasDisplays)` then looks for a display, but only finds one for the first (physical) device, but none for the mirror device.

Then when we reach line 220, primaryIndex == 1 (because of the mirror device) but found == 1 and then this statement:

`_GLFW_SWAP_POINTERS(monitors[0], monitors[primaryIndex]);`

... swaps the uninitialized memory at monitors[1] with the entry at index monitors[0], leading to a badly initialized monitors array, which then causes the crash in glfwGetVideoMode().

Possible solutions are to either skip mirror devices completely, similar as non-active devices, OR only set the value of primaryIndex for valid monitors.

**Comment by elmindreda** [comment]
That part of the code has been completely rewritten in 3.3. Is this still an issue with `master`?

**Comment by georgevanvenrooij** [comment]
Using `master` I could not reproduce the issue, so it seems the rewrite has fixed it. When does GLFW 3.3 come out?

**Comment by elmindreda** [comment]
As soon as possible.
