### ISSUE TITLE
Unable to create windows on macOS High Sierra

### ISSUE THREAD

**Issue by jameslinden** [glfw/glfw#1137]
When calling glfwCreateWindow() I get the following trace at runtime:

```2017-11-19 07:54:13.165413-0800 renderer[14025:228846] [General] ERROR: Setting <GLFWContentView: 0x1006c6430> as the first responder for window <GLFWWindow: 0x10052f1c0>, but it is in a different window ((null))! This would eventually crash when the view is freed. The first responder will be set to nil.```

I've tried using the following code before I create my window with no success:
``` 
glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 2);
glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
```

**Comment by ghuser404** [comment]
Are you also setting `GLFW_CONTEXT_VERSION_MAJOR`?

**Comment by jameslinden** [comment]
@ghuser404 Yeah.  Github's formatting clipped the first line for some reason.

**Comment by intrigus** [comment]
Duplicate of:
https://github.com/glfw/glfw/issues/1057
https://github.com/glfw/glfw/issues/1002
https://github.com/glfw/glfw/issues/909
https://github.com/glfw/glfw/issues/908
https://github.com/glfw/glfw/issues/876

**Comment by jameslinden** [comment]
Got it to run without crashing but it's just a black window regardless of what I choose to draw to the screen.  Just using a simple hello triangle example for testing: http://forum.devmaster.net/t/simple-triangle-using-opengl-and-glfw/24546

**Comment by jameslinden** [comment]
![screen shot 2017-11-19 at 8 50 07 am](https://user-images.githubusercontent.com/7868826/32992997-b0e34d20-cd06-11e7-850e-fd13a8634070.png)

**Comment by jameslinden** [comment]
@intrigus Awesome, found a fix in one those tickets.  You can close this.

**Comment by jameslinden** [comment]
Actually, getting the following output when I try to use a vertex or fragment shader at glsl version 3.3:

```
GL version: 2.1 INTEL-10.28.29
Error compiling shader type 35633: 'ERROR: 0:1: '' :  version '330' is not supported
ERROR: 0:3: 'layout' : syntax error: syntax error
'
Program ended with exit code: 1
```

**Comment by ghuser404** [comment]
Isn't it because you're setting OpenGL version 3.2? Try 3.3.

**Comment by jameslinden** [comment]
@ghuser404 Actually I got it up and working.  It had to do with me not having a VAO bound for newer Mac oses and nothing to do with GLFW.  Thanks for the help.
