### ISSUE TITLE
fatal error C1091: compiler limit: string exceeds 65535 bytes in length

### ISSUE THREAD

**Issue by chaoticbob** [glfw/glfw#1145]
Not sure if this was present before, but I just ran into this error:
````
C:\code\glfw\src\mappings.h(302): fatal error C1091: compiler limit: string exceeds 65535 bytes in length
````

Haven't found a good workaround yet. 

Using Visual Studio 2015 and target platform is x64. 

**Update:** just looked at the history of the file and the changes appear to be recent?

**Comment by elmindreda** [comment]
Fix up shortly.

**Comment by chaoticbob** [comment]
Thanks for the super quick fix!

**Comment by rayvling** [comment]
@elmindreda 
could you share how to fix up? thanks
