### ISSUE TITLE
glfw returns zero as the width or height of primary monitor

### ISSUE THREAD

**Issue by boojum** [glfw/glfw#1149]
Bug happens when trying to start `kitty` terminal, which depends on `glfw`. I thought that it might be issue with `kitty` but it would appear that it is indeed `glfw` bug, see original bug report [here](https://github.com/kovidgoyal/kitty/issues/204). Relevant part of `kitty` error is:
```
  File "/usr/bin/../lib/kitty/kitty/utils.py", line 134, in get_dpi
    pdpi = glfw_get_physical_dpi()
ValueError: Failed to get primary monitor size
```
`xrandr` is reporting my primary monitor correctly:
```
Screen 0: minimum 320 x 200, current 1600 x 900, maximum 8192 x 8192
VGA-1 disconnected (normal left inverted right x axis y axis)
LVDS-1 connected primary 1600x900+0+0 (normal left inverted right x axis y axis) 0mm x 0mm
   1600x900      59.95*+
   1440x900      59.99
   1280x854      59.95
   1280x800      59.96
   1280x720      59.97
   1152x768      59.95
   1024x768      60.04    60.00    59.95
   960x720       60.00
   928x696       60.05
   896x672       60.01
   800x600       60.00    60.32    59.96    56.25
   848x480       59.94
   700x525       59.98
   720x480       59.94
   640x512       60.02
   640x480       60.00    59.94    59.94
   512x384       60.00
   400x300       60.32    56.34
   320x240       60.05
HDMI-1 disconnected (normal left inverted right x axis y axis)
```
`glfw` version is `3.2.1`. How can I further debug this issue?

**Comment by tombsar** [comment]
Are you able to compile glfw from source on that machine? The `monitors` test program distributed with the source might give useful clues.

I'd suggest trying both 3.2.1 and current master, as there have been a lot of fixes since the last release.

**Comment by tombsar** [comment]
At least glfw is consistent with xrandr, but if xdpyinfo is getting reasonable values it should be possible for us to do better. Perhaps someone who knows X11 can suggest something?

**Comment by elmindreda** [comment]
Both RandR and GLFW ignore the display size since it's for the bounding rect of all monitors and doesn't really make sense for multi-monitor.

We _could_ add a hack where if there's only one monitor and RandR returns zero then we grab the display size. Not sure what to do with monitors connected after that, though. We could assume a DPI and derive the physical size from the resolution like Windows used to do, but... every option is terrible.

**Comment by boojum** [comment]
`xdpyinfo` takes it info from `DisplaySize` section of `xorg.conf` (which i had to set manually), without it it reports incorrect dimensions. I just tested it by changing values in `xorg.conf` to something slightly different.

I tried changing the size with `xrandr --output LVDS --fbmm 363x204` but that did absolutely nothing.

The issue might only exist with my crappy hardware, and have nothing to do with `glfw` or `X11`... Thou I would appreciate any advice on how I could test it further.

**Comment by boojum** [comment]
Furthermore, playing with `get-edid` (part of `read-edid`) produces only more errors and confusion:
```
$ sudo get-edid
This is read-edid version 3.0.2. Prepare for some fun.
Attempting to use i2c interface
Looks like no busses have an EDID. Sorry!
Attempting to use the classical VBE interface

	Performing real mode VBE call
	Interrupt 0x10 ax=0x4f00 bx=0x0 cx=0x0
	Function supported
	Call successful

	VBE version 300
	VBE string at 0xc01d0 "ATI ATOMBIOS"

VBE/DDC service about to be called
	Report DDC capabilities

	Performing real mode VBE call
	Interrupt 0x10 ax=0x4f15 bx=0x0 cx=0x0
	Function supported
	Call successful

	Monitor and video card combination does not support DDC1 transfers
	Monitor and video card combination supports DDC2 transfers
	0 seconds per 128 byte EDID block transfer
	Screen is not blanked during DDC transfer

Reading next EDID block

VBE/DDC service about to be called
	Read EDID

	Performing real mode VBE call
	Interrupt 0x10 ax=0x4f15 bx=0x1 cx=0x0
	Function supported
	Call failed

The EDID data should not be trusted as the VBE call failed
Error: output block unchanged
I'm sorry nothing was successful. Maybe try some other arguments
if you played with them, or send an email to Matthew Kern <pyrophobicman@gmail.com>.
```
I'm convinced now that the problem *is* with my laptop's screen. If no one has any further suggestions / ideas perhaps this issue should be closed as irrelevant to `glfw`?
