### ISSUE TITLE
Retrieve key modifiers

### ISSUE THREAD

**Issue by elect86** [glfw/glfw#1160]
Hi,

I'd like to ask if it could be possible implementing some sort of `glfwGetKey` for key modifiers

some sort of  `glfwGetMod` or something similar?

**Comment by FlandreScarlet** [comment]
`glfwGetKey` already supports this though. Are you unaware of this?
If not, what do you imagine `glfwGetMod` would do different from `glfwGetKey`?

[See here for the documentation](http://www.glfw.org/docs/latest/group__keys.html), near the bottom of the macros list.

I have quoted the relevant portion down below as well.
```
#define 	GLFW_KEY_LEFT_SHIFT   340
#define 	GLFW_KEY_LEFT_CONTROL   341
#define 	GLFW_KEY_LEFT_ALT   342
#define 	GLFW_KEY_LEFT_SUPER   343
#define 	GLFW_KEY_RIGHT_SHIFT   344
#define 	GLFW_KEY_RIGHT_CONTROL   345
#define 	GLFW_KEY_RIGHT_ALT   346
#define 	GLFW_KEY_RIGHT_SUPER   347
#define 	GLFW_KEY_MENU   348
```
