### ISSUE TITLE
Window doesn't move or recieve mouse input

### ISSUE THREAD

**Issue by nick-prat** [glfw/glfw#1162]
On Ubuntu 17.10 with Gnome and Wayland, windows aren't able to be moved, or receive any mouse input. Clicking on the window results in the window behind it being brought up, or nothing if there is no window beneath it. 

I have tested this with a clean build from the master branch, and it has the same results for all examples. At the time of testing, my computer is running Mesa 17.2.2 with Intel graphics on Gnome 3.26.1 and Mutter 3.26.2.

If there's any information I'm missing that would help, I'd be happy to provide it.

**Comment by linkmauve** [comment]
According to @jadahl, this is a bug in Mutter, see https://bugzilla.gnome.org/show_bug.cgi?id=791865

**Comment by lumonix** [comment]
I assume you have enough repro cases. In case you need another: the nuklear / glfw3 examples show this problem also.

**Comment by linkmauve** [comment]
This has been fixed on the 9th of January, see https://bugzilla.gnome.org/show_bug.cgi?id=790309#c8
