### ISSUE TITLE
Query if a window is being hovered by the mouse? (e.g. Add GLFW_HOVERED window attrib)

### ISSUE THREAD

**Issue by ocornut** [glfw/glfw#1166]
Hello,

I am working on better multi-windows support for dear imgui backends. To make cross-window drag and drop patterns easy to implement in a portable manner (bypassing the full OS machinery which is incredibly complicated for the end-user) I found it necessary to be able to query whether a window is being hovered by the mouse, regardless of it being focused or not. As far as I know this is not currently possible with GLFW. It's also not something we can track/compute without the window manager assistance.

(Context, this is my use case: https://twitter.com/ocornut/status/946470996529336321 )

In the Win32 code, this information is currently provided by the function:
`static GLFWbool cursorInClientArea(_GLFWwindow* window)`

I don't know about other supported platforms, but may I suggest exposing it in GLFW?
A suggestion would be to add an additional GLFW_HOVERED attribute that could be queried with:
`glfwGetWindowAttrib(window, GLFW_HOVERED)`

I could work on a PR for Win32 if useful but I don't have easy access nor knowledge of other platforms.

Thank you,
Omar

**Comment by elmindreda** [comment]
This has been added with ee9dffcd6673b891a0ca7bb0533094b9f5a9b07e. Thank you!
