### ISSUE TITLE
GLFWContentView error in High Sierra

### ISSUE THREAD

**Issue by dr3amnightmare** [glfw/glfw#1167]
Like previous issues that have been noted in the past, I have received the error
`2018-01-01 13:56:37.782734-0500 Application[31521:484286] [General] ERROR: Setting
<GLFWContentView: 0x100417f00> as the first responder for window <GLFWWindow:
0x100538140>, but it is in a different window ((null))! This would eventually crash when the view
is freed. The first responder will be set to nil.`
(
       
       0   AppKit                              0x00007fff4904152e -[NSWindow _validateFirstResponder:] + 578
       
        1   AppKit                              0x00007fff48788a58 -[NSWindow _setFirstResponder:] + 31

        2   AppKit                              0x00007fff4882717d -[NSWindow _realMakeFirstResponder:] + 448

	3   libglfw.3.dylib                  0x0000000100317975 _glfwPlatformCreateWindow + 657

	4   libglfw.3.dylib                  0x0000000100313592 glfwCreateWindow + 443

	5   Application                      0x0000000100001804 RWGame_initWithTitle + 260

	6   Application                      0x00000001000010e7 main + 55

	7   libdyld.dylib                     0x00007fff729e8115 start + 1

	8   ???                                   0x0000000000000001 0x0 + 1
)
The difference I seem to be having from others is that my windows does in fact create and work as intended. It is just alarming to see that knowing that at some point and/or time the application could just crash or screw up royally. I have the master from Github as of the date of this post and it is present.

Hope to see a fix soon. Cheers!
Tyler McLean

**Comment by elmindreda** [comment]
What does `glfwGetVersionString` return?

**Comment by dr3amnightmare** [comment]
It returns `3.2.1 Cocoa NSGL chdir menubar retina dynamic`

**Comment by elmindreda** [comment]
Then you're not using current master as that would say 3.3.

**Comment by elmindreda** [comment]
That whole string is stored statically in the library so you can check it with `grep` or `strings`.

**Comment by dr3amnightmare** [comment]
Well isn't that embarrassing. Looks like I had one from Homebrew kicking around. Works flawlessly on 3.3. Thanks for the help elmindreda. Cheers!

**Comment by Cstzhang** [comment]
how to get  3.3 ?

**Comment by Cstzhang** [comment]
i have the same problem
