### ISSUE TITLE
Failing to use ANGLE EGL

### ISSUE THREAD

**Issue by mumin16** [glfw/glfw#1169]
for osx, i compiled google angle.
	glfwWindowHint(GLFW_CONTEXT_CREATION_API, GLFW_EGL_CONTEXT_API);
	glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 2);
	glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 0);
	glfwWindowHint(GLFW_CLIENT_API, GLFW_OPENGL_ES_API); 

i have this error: GLFW Error: Cocoa: EGL not available

**Comment by elmindreda** [comment]
Seems your GLFW binary is too old to include EGL support on macOS. Try building a newer one from master.

**Comment by mumin16** [comment]
GLFW Error: EGL: Failed to create window surface: A NativeWindowType argument does not refer to a valid native window

**Comment by elmindreda** [comment]
Yay, that's definitely progress! Try changing the definition of `_GLFW_EGL_NATIVE_WINDOW` in `cocoa_platform.h` to
```c
#define _GLFW_EGL_NATIVE_WINDOW  ((EGLNativeWindowType) window->ns.object)
```
and see if that helps.

**Comment by mumin16** [comment]
it is not work!

**Comment by mumin16** [comment]
https://github.com/mumin16/veriaktar/releases/download/1alfa/sil.zip

**Comment by Kangz** [comment]
@mumin16 ANGLE's support for rendering to windows directly on OSX is extremely bad at the moment. It expects EGLNativeWindowType to be CALayer* and even then introduces extra blits, isn't vsynced etc.

Source: I'm the author of this crappy code and should fix it some day :)

**Comment by elmindreda** [comment]
@Kangz Thanks! Do you know if it will expect a CALayer in the future as well?

**Comment by Kangz** [comment]
I think it will end up accepting both a CALayer or an NSView like [Swiftshader](https://github.com/google/swiftshader/blob/master/src/Main/FrameBufferOSX.mm#L90). If you think an NSView is better I can make a patch to allow that.

**Comment by elmindreda** [comment]
@Kangz I'm fine with whatever variant lets us talk to most (all?) macOS EGL implementations.

**Comment by dougbinks** [comment]
FYI this came up in the following forum question along with a potential fix:

http://discourse.glfw.org/t/egl-and-opengl-es-on-mac/1281

**Comment by Kangz** [comment]
Coming back to this (it's been two years >_>) I put up https://github.com/glfw/glfw/pull/1680 and checked locally with a modified `triangle-opengl` that it works correctly with ANGLE. I also fixed retina support for ANGLE's OpenGL backend on Mac [here](https://chromium-review.googlesource.com/c/angle/angle/+/2154670).

Note that the window surface implementation of ANGLE OpenGL on Mac sucks and shouldn't be relied upon, but in the future the Vulkan (on swiftshader) or Metal backends on Mac should have good window surface implementation.

**Comment by elmindreda** [comment]
Sorry, I lost track of this one. Will merge #1680 asap.

**Comment by Kangz** [comment]
No worries, I lost track too. The ANGLE fix has landed.
