### ISSUE TITLE
Load libwayland-client at runtime

### ISSUE THREAD

**Issue by linkmauve** [glfw/glfw#1174]
Once #1173 is merged, libwayland-client will be the last Wayland-specific shared object GLFW links against.

The main issue with this library is that protocol headers, generated by `wayland-scanner` and provided either alongside libwayland for `wayland-client-protocol.h`, or built by GLFW (see e.g. `build/src/wayland-idle-inhibit-unstable-v1-client-protocol.h`), have `static inline` functions calling into it.

I haven’t been able to figure out how to make those functions defined in the protocol header call our own function aliases, the ones defined in `_glfw.wl` and loaded during `glfwInit()`.

To make it worse, these protocol headers also depend on `wl_interface` symbols which aren’t functions, exported by libwayland-client.so or internal to GLFW for other protocols, and I haven’t been able to change them using our usual `#define` dance either.

**Comment by jadahl** [comment]
You can do what I made SDL do here: http://hg.libsdl.org/SDL/rev/b326f93e1bc5

In short, you don't use the protocol symbols from libwayland-client, but generate your own that can be bundled. The only libwayland-client symbols you load on demand are the non-generated one.
