### ISSUE TITLE
key press ALT+A+D blocks the D press event until A is released

### ISSUE THREAD

**Issue by malytomas** [glfw/glfw#1176]
Hi

keys A and D does not work:

I press ALT (and hold it)
0000031b to 1 at 787,041: Key 0x0156 Scancode 0x0038 (LEFT ALT) (with alt) was pressed
I press A (and hold it)
0000031c to 1 at 788,368: Key 0x0041 Scancode 0x001e (A) (a) (with alt) was pressed
I press D (and hold it) ... no event
I release A
0000031d to 1 at 791,098: Key 0x0041 Scancode 0x001e (A) (a) (with alt) was released
0000031e to 1 at 791,103: Key 0x0044 Scancode 0x0020 (D) (d) (with alt) was pressed
I release D
0000031f to 1 at 792,280: Key 0x0044 Scancode 0x0020 (D) (d) (with alt) was released
I release ALT
00000320 to 1 at 793,536: Key 0x0156 Scancode 0x0038 (LEFT ALT) (with no mods) was released

the 0000031e is the delayed event

keys H, J, and K works as expected:

000002d6 to 1 at 743,001: Key 0x0156 Scancode 0x0038 (LEFT ALT) (with alt) was pressed
000002d7 to 1 at 745,168: Key 0x0048 Scancode 0x0023 (H) (h) (with alt) was pressed
000002d8 to 1 at 745,824: Key 0x004a Scancode 0x0024 (J) (j) (with alt) was pressed
000002d9 to 1 at 746,400: Key 0x004b Scancode 0x0025 (K) (k) (with alt) was pressed
000002da to 1 at 749,640: Key 0x0048 Scancode 0x0023 (H) (h) (with alt) was released
000002db to 1 at 750,169: Key 0x004a Scancode 0x0024 (J) (j) (with alt) was released
000002dc to 1 at 751,080: Key 0x004b Scancode 0x0025 (K) (k) (with alt) was released
000002dd to 1 at 751,592: Key 0x0156 Scancode 0x0038 (LEFT ALT) (with no mods) was released

also note that this issue only happens with ALT, it works as expected with eg. CTRL.
key S has similar issues. i thought it could be related to WSAD being often used as arrow keys in games, but W key works ok.

checked on events test with minor changes:
char_callback and char_mods_callback immediately returns
key_callback immediately returns if the action is repeat
these changes were made to suppress unrelated events in the output

commit: ac94014ef85853059eed65f1fa5344e2688b6f40
windows 10, 64 bit, visual studio 2017 (win32 build)

thanks for looking into this :D

**Comment by tombsar** [comment]
Any chance you can test this with a different keyboard (preferably a different brand)? It could be a hardware limitation that those three keys cannot be held together. Alternatively, does the combination work in other, non-glfw programs?

**Comment by malytomas** [comment]
@tombsar good point. I tried it on some javascript website and it behaves the same. That pretty much rules glfw out.
Now I am curious if it is actually hardware limitation or windows.

**Comment by malytomas** [comment]
So it is actually the keyboard. I am having hard time believing this :D
