### ISSUE TITLE
GLFW_MOD_CONTROL not recognised in 'charmods_callback'

### ISSUE THREAD

**Issue by rebirth123** [glfw/glfw#1178]
switch (mods)
{
	case GLFW_MOD_SHIFT: printf("SHIFT\n"); break;
	case GLFW_MOD_CONTROL: printf("CONTROL\n"); break;
	case GLFW_MOD_ALT: printf("ALT\n"); break;
	default: break;
}
printf("%c\n", codepoint);

The other modifiers appear to work.  I'm using a UK layout.  GLFW 3.2.1

Also, whilst holding Ctrl no other input is handled.  For example, if I hold Shift and press a character key the 'codepoint' follows.  If I don't hold any modifier keys only the 'codepoint' is printing.  Something within GLFW appears to halt all input to this function when Ctrl is held, but the expected behaviour should be the same as Shift+character.

I have written my own windows specific code before which does most of what GLFW does, but I didn't want to maintain it.  Plus, I wanted something that isn't platform specific.  However, this is how I got certain modifiers in windows:

WPARAM mapKey(WPARAM wp, LPARAM lp)
{
	switch (wp)
	{
	case VK_SHIFT: return MapVirtualKey(((lp & 0x00ff0000) >> 16), MAPVK_VSC_TO_VK_EX);
	case VK_CONTROL: return ((lp & 0x01000000) != 0) ? VK_RCONTROL : VK_LCONTROL;
	case VK_MENU: return ((lp & 0x01000000) != 0) ? VK_RMENU : VK_LMENU;
	default: return wp;
	}
}

{
        case WM_KEYDOWN:
               const int key = (int)mapKey(wParam, lParam);
}
  
It works, and fixed some issues I had when dealing with modifier keys in a old app of mine.

**Comment by tombsar** [comment]
Are you able to compile and test with the latest master of glfw? There have been quite a lot of changes and fixes since that last release.

Also, does the `events` test show the same results as your code (to help with reproducing the issue)?

**Comment by rebirth123** [comment]
Hi, thanks for the quick response.  I just downloaded and compiled the master, but the problem still exists.  In the normal key_callback it does recognise GLFW_MOD_CONTROL, so the problem only appears to be in the charmods_callback.  I'll probably have to hack the two together to mimic copy/pasting for now.

**Comment by tombsar** [comment]
Ah, I missed that this was the character callback rather than the key callback.

This actually looks like intended ("correct") behaviour. In all programs I can think of, CTRL+key combinations perform functions within a program, and do not input any text. I believe it was a deliberate design decision to exclude CTRL+key events from the character callbacks, as they are intended to be used only in situations where the user is inputting text. Comment from the maintainers?

Related to #1140

**Comment by rebirth123** [comment]
The documentation doesn't mention Ctrl being omitted by design for this function call, and does link to the modifier bits it uses: http://www.glfw.org/docs/latest/input_guide.html#input_char 

However, looking over your link somebody did mention that the charmods callback was deprecated (kovidgoyal).

I was hoping to mimic Ctrl+x/c/v for copy/pasting.  I'll try and use the normal key_callback to capture mods.  It's the only key callback function that gets called when ctrl is held.  

Thanks for pointing me to that discussion.

**Comment by tombsar** [comment]
It's definitely a confusing part of the API right now; I recommend using the character callbacks just for text input, and the key callback for keyboard shortcuts, as you say.

**Comment by elmindreda** [comment]
The charmods callback has been deprecated and no further work will be done on it.
