### ISSUE TITLE
glfwCreateWindow always "Activate" windows regardless of GLFW_FOCUSED

### ISSUE THREAD

**Issue by ocornut** [glfw/glfw#1179]
Hello,

A)
This code in win32_window.c:
```
void _glfwPlatformShowWindow(_GLFWwindow* window)
{
    ShowWindow(window->win32.handle, SW_SHOW);
}
```

I believe should be:
```
void _glfwPlatformShowWindow(_GLFWwindow* window)
{
    ShowWindow(window->win32.handle, SW_SHOWNA);
}
```

Right now if you call `glfwCreateWindow()` with the `GLFW_FOCUSED` hint set to FALSE, the code in glfwCreateWindow does:
```
_glfwPlatformShowWindow(window);
if (wndconfig.focused)
    _glfwPlatformFocusWindow(window);
```
And _glfwPlatformShowWindow() alone with SW_SHOW "activates" the Windows. Now honestly, I am confused about the exact meaning of "activation" in the Win32 api but essentially it looks like we are losing the focus, and this defeat the purpose of GLFW_FOCUSED as documented:  `GLFW_FOCUSED specifies whether the windowed mode window will be given input focus when created. This hint is ignored for full screen and initially hidden windows. `

I will post a PR shortly to make it easy to test that change. I think it should probably be checked/confirmed by people who are more expert of the Win32 api that I am. 

(PS/1: My usage context is I am trying to get this feature working in my GLFW backends: https://twitter.com/ocornut/status/950430111710482433 / the code create undecorated window dynamically and it is a problem and overly noticeable by the end-user if the parent window lose its focus.)

(PS/2: Out of curiosity I traced the history for `_glfwPlatformShowWindow()`: 
May 2014: b91116e2bc8e1abe83b2f486b9cb9b1f0fc1109b Changed `SW_SHOWNORMAL` to `SW_SHOW` for #264
Jan 2013: b72a97d5318ca497224739411d806bc4b217cc0d Refactor, didn't affect functionalities
Aug 2012, 596132c3a1becceb0ba6d10991d52a85ba8f201c Initial version)

---

B)
Note that my proposed PR only fixes glfwCreateWindow().
`glfwShowWindow()` always calls `_glfwPlatformShowWindow` + `_glfwPlatformFocusWindow`, which seems redundant with the the fact that `glfwFocusWindow()` exists. 
My intuition it that it would it be more correct and consistent to remove that call to `_glfwPlatformFocusWindow()` in `glfwShowWindow()`, however: that extra call was added in 89f438de5a862802717a5d6e32ebfe462775cccf "Fix window focus regression" (March 2016) so I imagine there is more to it.

---

Thank you very much.
O.

**Comment by ocornut** [comment]
*EDIT* 
Based on 
https://msdn.microsoft.com/en-us/library/windows/desktop/ms633548(v=vs.85).aspx

We should use `SW_SHOWNA` which is the "no activation" variant of `SW_SHOW`
`SW_SHOWNOACTIVATE` is the "no activation" variant of `SW_SHOWNORMAL`.
I have edited my text above + pushed a new branch that the incoming PR will use.

**Comment by ghuser404** [comment]
Yeah, I find it weird that baf5744 first fixes the `glfwShowWindow` saying

> This removes the (undocumented) behavior where glfwShowWindow would
> bring the window to front and set input focus.  That function now
> does what it says.

And then 89f438d reverts that fix saying

> Regression caused by baf5744.

**Comment by ocornut** [comment]
My suspicion is that the casual user would expect glfwShowWindow() to set make the window "ready" and therefore the focus, so it is partly a documentation problem + partly a backward compatibility problem.

Luckily it would only affect a subset of users (those who set GLFW_VISIBLE to fals?), and the behavioral change would be fairly easy to spot and change as well.

**Comment by ghuser404** [comment]
> Luckily it would only affect a subset of users (those who set GLFW_VISIBLE to fals?), and the behavioral change would be fairly easy to spot and change as well

Correct me if I'm wrong, the hint only affects how `glfwCreateWindow` behaves - `glfwShowWindow` is unrelated to `GLFW_VISIBLE` hint.

**Comment by elmindreda** [comment]
> We should use `SW_SHOWNA` which is the "no activation" variant of `SW_SHOW`

Yup. That was an oversight in baf574494da1f1b6a07ff426c62670090e67b445. Thank you!

> Now honestly, I am confused about the exact meaning of "activation" in the Win32 api but essentially it looks like we are losing the focus

Correct. They're essentially the same for us as we don't have child windows. Here is [the official explanation of active window](https://msdn.microsoft.com/en-us/library/windows/desktop/ms632599(v=vs.85).aspx#active).

> My suspicion is that the casual user would expect glfwShowWindow() to set make the window "ready" and therefore the focus, so it is partly a documentation problem + partly a backward compatibility problem.

Yep, that's it exactly and I was quite sensibly asked to revert, so we're somewhat stuck with the current behavior until 4.0.

**Comment by ocornut** [comment]
Thanks @elmindreda!

**Comment by elmindreda** [comment]
This has been fixed with 20b12204af481d863e9a256f973e2bf7dc480c53 by @ocornut.

**Comment by ghuser404** [comment]
@elmindreda Should I create a ticket for the `glfwShowWindow` issue for GLFW 4.0?

**Comment by elmindreda** [comment]
@ghuser404 It might be good to have an issue people can find for it. I added it to [the list](https://github.com/glfw/glfw/wiki/GLFW-4.0-sketchbook) for now.

**Comment by ocornut** [comment]
Just for the records, for the (B) part of this I _think_ I can find a workaround for my specific use case.

**Comment by ghuser404** [comment]
Inclusion into GLFW 4.0 sketchbook sounds good enough to me.

**Comment by elmindreda** [comment]
@ocornut If it turns out you can't, we can add a function that only calls `_glfwPlatformShowWindow`.

**Comment by ocornut** [comment]
@elmindreda I am tempted to say yes, I'd appreciate another entry point is that's not too polluting.

(
I was about to create an issue for another feature: a flag to disable appearing in taskbar, which correspond to `~WS_EX_APPWINDOW | WS_EX_TOOLWINDOW` in Win32, but I don't know how to formalize that in a portable way. 

I can get around by querying the HWND via `glfwGetWin32Window()` but doing that after a ShowWindow create a flicker in the task bar, and I can't use GLFW_VISIBLE=FALSE + later glfwShowWindow() because it steals focus... If I have a call that does the Show without the Focus then manipulating window styles in a non-portable manner will be doable without the flicker. 
)

**Comment by ocornut** [comment]
> If it turns out you can't, we can add a function that only calls _glfwPlatformShowWindow.

If your offer still stand, would you like me to create a separate issue for this? (since this one is closed). Thank you!

(I also made minor edits to my post above to clarify the relationship with this)

**Comment by elmindreda** [comment]
@ocornut I would like a function like that but it needs a good name; one that avoids making the API even more confusing. Please do open a new issue if you don't mind this still being a "it depends".
