### ISSUE TITLE
problem with window GLFW_DECORATED = true

### ISSUE THREAD

**Issue by NkD** [glfw/glfw#1184]
Window with decoration has wrong dimensions of frame buffer (probably).

Very simple example:

```java
System.out.println("LWJGL version : " + org.lwjgl.Version.getVersion());
System.out.println(" GLFW version : " + glfwGetVersionString());
glfwInit();
glfwDefaultWindowHints();

glfwWindowHint(GLFW_DECORATED, GLFW_TRUE);  <-- PROBLEM IS HERE

long window = glfwCreateWindow(500, 500, "", 0, 0);
glfwMakeContextCurrent(window);
GL.createCapabilities();
glfwShowWindow(window);
glfwSetWindowPos(window, 1200, 200);
glClearColor(0, 0, 0, 1);

int[] width = new int[1];
int[] height = new int[1];
glfwGetFramebufferSize(window, width, height);
System.out.println("FrameBuffer size : width = " + width[0] + ", height = " + height[0]);
glfwGetWindowSize(window, width, height);
System.out.println("     Window size : width = " + width[0] + ", height = " + height[0]);
while (true) {
	glClear(GL_COLOR_BUFFER_BIT);
	glfwGetFramebufferSize(window, width, height);
	glViewport(0, 0, width[0], height[0]);
	GL11.glColor4f(1, 1, 0, 1);
	GL11.glBegin(GL11.GL_QUADS);
	GL11.glVertex2f(-0.9f, -0.9f);
	GL11.glVertex2f(-0.9f, 0.9f);
	GL11.glVertex2f(0.9f, 0.9f);
	GL11.glVertex2f(0.9f, -0.9f);
	GL11.glEnd();
	glfwSwapBuffers(window);
	glfwPollEvents();
}
```

PROBLEM:
![decorated](https://user-images.githubusercontent.com/917951/34945335-48bf47c4-fa03-11e7-92e3-42f3da7a2957.png)

WITHOUT DECORATION FOR REFERENCE:
![undecorated](https://user-images.githubusercontent.com/917951/34945342-4be049ee-fa03-11e7-95a0-39f7b9dfa74f.png)

Tested on:
WINDOWS 10 Pro 64bit, GF 960M, 

Possible same issue: #1148

**Comment by ghuser404** [comment]
I quickly converted your code into C, and I cannot reproduce this issue.

I tried this with the latest trunk, though. I assume LWJGL is not using the latest trunk.
There might also be bugs in the LWJGL binding.

Did you try asking LWJGL community?

**Comment by Spasi** [comment]
Cannot reproduce with latest LWJGL snapshot (which is also on latest GLFW commit, 6c421f131da0bdd79326b8c16fdb9df8fd8be03a). Output:

> LWJGL version : 3.1.6 SNAPSHOT
> GLFW version : 3.3.0 Win32 WGL EGL VisualC DLL
> FrameBuffer size : width = 500, height = 500
> Window size : width = 500, height = 500

**Comment by NkD** [comment]
My output (problem version):
> LWJGL version : 3.1.4 build 8
>  GLFW version : 3.3.0 Win32 WGL EGL VisualC DLL
> FrameBuffer size : width = 500, height = 500
>     Window size : width = 500, height = 500

**Comment by ghuser404** [comment]
Can you try it with the latest version?

**Comment by NkD** [comment]
Latest version:

![problem](https://user-images.githubusercontent.com/917951/34964133-5d9552c6-fa4c-11e7-999b-7e04b3df474e.png)

but, maybe it is problem in LWJGL and not in GLFW, maybe in driver (nvidia 390.65) or maybe conjuction between Mercur and Venus. I don't know.

**Comment by ghuser404** [comment]
@NkD What is `GL.createCapabilities();`?

**Comment by trashuj** [comment]
Hi guys,
I gave this a try again this week(re-enabling decoration), and apparently it's fixed.
I didnt change anything code wise, but i updated my nvidia driver.. so maybe a driver issue after all.

**Comment by NkD** [comment]
I confirm that the issue has disappeared after updating the NVIDIA drivers. In version 390.77 everything works as it should. Problem solved. Heh.
