### ISSUE TITLE
Setting GLFW_OPENGL_DEBUG_CONTEXT to true gives "no current context" error

### ISSUE THREAD

**Issue by sir-pinecone** [glfw/glfw#1193]
I'm using OpenGL 3.3 (seeing this in 4.x as well) on Windows 7. Here's some extra info:

```
GPU: Vendor:         NVIDIA Corporation
GPU: Renderer:       GeForce GTX 1070/PCIe/SSE2
GPU: OpenGL version: 3.3.0 NVIDIA 390.65
GPU: GLSL version:   3.30 NVIDIA via Cg compiler
GPU: Loaded 374 extensions
```

I'm setting the window hint like so:

```
if (glfwExtensionSupported("GL_ARB_debug_output") == GLFW_TRUE) {
    glfwWindowHint(GLFW_OPENGL_DEBUG_CONTEXT, GL_TRUE);
}
```

After calling `glfwMakeContextCurrent()` I get the error. 

I'm not sure how to debug this as I'm fairly new to OpenGL. Any ideas? I can provide more info if needed.

**Comment by elmindreda** [comment]
The error is probably caused by calling `glfwExtensionSupported` without a current context.

To create a debug context, set `GLFW_OPENGL_DEBUG_CONTEXT` before context creation and then check after having made the context current if the `GL_ARB_debug_output` is supported by that context.

You should probably also support the newer `GL_KHR_debug`.

**Comment by sir-pinecone** [comment]
> The error is probably caused by calling glfwExtensionSupported without a current context.

Thank you, that was the cause. 
I just looked at the docs again and it's very clear that a context is required, but perhaps a more detailed error message would help in this case. I can submit a PR if you like.

I'll take a look at `GL_KHR_debug`, cheers.

**Comment by elmindreda** [comment]
Those error messages could definitely do with some improvement. Will fix.

**Comment by sir-pinecone** [comment]
Great. I'm going to close this. Thanks again.

**Comment by elmindreda** [comment]
Related error messages have hopefully been improved somewhat with ae53cd29ef46372fbc928a251f8de6e64fa4e7c4.
