### ISSUE TITLE
Make it an error to create a glfwCreateWindowSurface without GLFW_NO_API

### ISSUE THREAD

**Issue by Kangz** [glfw/glfw#1194]
Long story short: I spent 3 days debugging a crash in the NVIDIA driver on `vkQueuePresentKHR` because I forgot to add `glfwWindowHint(GLFW_CLIENT_API, GLFW_NO_API);`.

Using Vulkan and OpenGL / OpenGL ES on the same window isn't defined AFAIK. Would it make sense to produce an error if `glfwCreateWindowSurface` is called on a window that doesn't have the `GLFW_CLIENT_API` hint set to `GLFW_NO_API`? I'm sure this would help preserve some other developer's sanity.

**Comment by elmindreda** [comment]
Huh, interesting, because [Nvidia is why](https://youtu.be/NqensKmmRfE?t=43m20s) I didn't add this check to begin with, since it seemed they wanted to let you mix them.

What OS are you on?

**Comment by Kangz** [comment]
This is on Linux X11 with a recent driver. I can provide more detailed info next week if needed. From the presentation you linked it looks like NVIDIA's Vulkan and OpenGL implementations can share resources, but I'm not sure there is a useful case for sharing swapchains/backbuffer. So erroring on `glfwCreateWindowSurface` might make sense (?).

@pdaniell-nv since you gave the presentation linked above, do you know if there's any case where a Vulkan swapchain and an OpenGL backbuffer could coexist on the same window?

**Comment by elmindreda** [comment]
[Here](https://github.com/nvpro-samples/gl_vk_threaded_cadscene) is the (possibly updated) code for what he showed.

Seems it's not creating a surface. I'll add the error.

**Comment by pdaniell-nv** [comment]
I didn't get the chance to go into great detail in that presentation. It is possible with our driver for an application to use both OpenGL and Vulkan. However, it's not possible for a single window to be a presentation target for both OpenGL SwapBuffers() and Vulkan swap chains simultaneously. I window can only be used for one or the other. If an application wants to use both OpenGL and Vulkan and present both to the same window then it must use something like [GL_NV_draw_vulkan_image](https://www.khronos.org/registry/OpenGL/extensions/NV/NV_draw_vulkan_image.txt) to draw the Vulkan render targets onto the OpenGL framebuffer.

**Comment by Kangz** [comment]
Thanks a lot for the confirmation. @elmindreda I have PR up at #1205 PTAL
