### ISSUE TITLE
glfwCreateWindow() should support wchar_t as input window title

### ISSUE THREAD

**Issue by 3x3y3z3t** [glfw/glfw#1199]
The current `glfwCreateWindow()` current takes `const char*` as parameter for window title. This works fine most of the time. However when I try to input non-ASCII (e.g Japanese character symbol), the output window title display them as ? for each byte of those non-ASCII symbol. Note that I use 
`wchar_t* text = L"あ";`
to hard-code the unicode string for testing.

I've read the FAQ and see that GLFW supports Unicode. I have browse the source code and found this function:
`WCHAR* _glfwCreateWideStringFromUTF8Win32(const char* source);`
in which it calls `MultiByteToWideChar()` to convert multi-byte string from the title parameter said above to `wchar_t*`.

So I have reversed the process by call `WideCharToMultiByte()` to convert my `wchar_t*` unicode string to `const char*` and then pass the result in CreateWindow function or SetWindowTitle function. And I find that pretty annoying even I can warp the process in one function, plus convert an unicode string to multi-byte char string then convert it back to unicode string is a waste of time and resource.

So I think there should be a version of `glfwCreateWindow()` that takes in `wchar_t*` as window title parameter. Do this may require the change of `_GLFWwndconfig` structure, or just simple warp the conversion of `wchar_t*` to `const char*` then call the former function. The change is not much, but it lift the weight for user.

```
GLFWAPI GLFWwindow* glfwCreateWindow(int width, int height, const char* title,
                                     GLFWmonitor* monitor, GLFWwindow* share)
{
    char* newtitle;
    int count;
    GLFWwindow* retWindow;

    // first get the size of the buffer, if you know exactly the size then this is not necessary;
    count = WideCharToMultiByte(CP_UTF8, 0, cl, -1, nullptr, 0, NULL, NULL);
    if (!count)
    {
        _glfwInputErrorWin32(GLFW_PLATFORM_ERROR, "Win32: Failed to convert string from UTF-8");
        return NULL;
    }

    newtitle = (char*)calloc(count, sizeof(char));
    WideCharToMultiByte(CP_UTF8, 0, cl, -1, newtitlet, count, NULL, NULL);

    // call the exactly former function;
    retWindow = glfwCreateWindow(width, height, newtitle, monitor, share);

    // need to free the calloc()-ed pointer;
    free(newtitle);
    
    return retWindow;
}
```

**Comment by ghuser404** [comment]
> And I find that pretty annoying even I can warp the process in one function

Then do it :)

> plus convert an unicode string to multi-byte char string then convert it back to unicode string is a waste of time and resource

That's because Windows implementation requires it to be converted to wide string, have a look at other platforms. Your program will [usually] run this function once, I'm sure no one will call it slow because it converted wide string to UTF-8 and back.

Also, how would you call the function? `glfwCreateWindowW`? Mind you, there are no function overloads in C. What if someone came along and asked this function to accept UTF-32? What if someone asked it to accept 64-bit ints for width/height, because their compiler was giving them warnings? Oh, we have another problem here...

**Comment by 3x3y3z3t** [comment]
> Then do it :)

I did it :)

> Also, how would you call the function? `glfwCreateWindowW`? Mind you, there are no function overloads in C. What if someone came along and asked this function to accept UTF-32? What if someone asked it to accept 64-bit ints for width/height, because their compiler was giving them warnings? Oh, we have another problem here...

Thanks for remind, I have just completely forgotten that there is no function overload in C (in which glfw is written), so there really are problems. However, I think UTF-8 string window title should be common enough to make a separate function..

**Comment by ghuser404** [comment]
> However, I think UTF-8 string window title should be common enough to make a separate function..

This function already accepts UTF-8 string. Or are you taking about UTF-16? Then I can't agree nor disagree.

**Comment by ghuser404** [comment]
I don't know if you are confusing UTF-8 and UTF-16, but FYI, you can do like this (just make sure your files are saved in UTF-8 format):
```
const char* title= "あ";
GLFWwindow* window = glfwCreateWindow(width, height, title, NULL, NULL);
```

**Comment by elmindreda** [comment]
@3x3y3z3t Have you had a look at the [title](https://github.com/glfw/glfw/blob/master/tests/title.c) test program?

**Comment by 3x3y3z3t** [comment]
I have tried my own title as well as the title taken from the title test program. On my end, the window appeared with one or two '?' symbol for each non-ASCII character. Only if I use WideCharToMultiByte() to convert them to multi-byte char array and pass in window create function, it displays correctly.

Here is the window title when I use exact the same parameter in the test program:
![title1](https://user-images.githubusercontent.com/16525687/35577295-8248d96a-0624-11e8-9168-37bada833143.PNG)
And here is the window title using the same title string but converted from wchar to multi-byte char before pass in function:
![title2](https://user-images.githubusercontent.com/16525687/35577357-b1042bce-0624-11e8-8ff5-00e984235f72.PNG)

(The title string in both case is  `"English 日本語 русский язык 官話"`)

**Comment by elmindreda** [comment]
What encoding is your source file in?

**Comment by ghuser404** [comment]
@3x3y3z3t Is this still an issue for you?

**Comment by 3x3y3z3t** [comment]
Sorry for late reply, everyone.
@elmindreda My source file is encoded in ANSI, and my locale is set to Japan (VS save the file as JIS - codepage 50220, I think this is what cause the problem on my end. When I save the file as UTF-8 w/o signature - codpage 65001, the title string passed in display correctly for almost all character (include Japanese symbol), except some Vietnamese symbol like `ầ ở ẵ`.

Workaround using `wchar*` to store the string, convert using `WideCharToMultiByte()` then passed in create window function result in all character (symbol) displayed correctly.

**Comment by ghuser404** [comment]
Thanks for coming back.
If you're satisfied with the solution, please close the ticket.

**Comment by elmindreda** [comment]
@3x3y3z3t No worries and thank you for the follow-up!
