### ISSUE TITLE
Key name pointer lifetime

### ISSUE THREAD

**Issue by ghuser404** [glfw/glfw#1200]
> The returned string is allocated and freed by GLFW. You should not free it yourself. **It is valid until the next call to glfwGetKeyName**, or until the library is terminated.

With the recent changes that fix #943, on Windows GLFW now caches key names. However, the fix appears to break the promise in the doc above - the key names are invalidated when `WM_INPUTLANGCHANGE` is processed.

**Comment by ocornut** [comment]
I think it would be reasonable to just update the promise in the doc. I guess it could now (in theory) breaks when calling `glfwPollEvents()`, people are unlikely to be relying on that.

**Comment by ghuser404** [comment]
> people are unlikely to be relying on that

You never know :)

**Comment by elmindreda** [comment]
The contents of the string might change, but the string is a static array in a global struct so it won't move, even through re-initialization.

This seems like a useful event to have, though.

**Comment by ghuser404** [comment]
@elmindreda Regarding you changing the title of this issue. Maybe this happened by mistake, but this issue describes the problem with the lifetime of `glfwGetKeyName`. You changed the title to "Add keyboard layout change event" - but I've already created such issue #1201.

**Comment by ghuser404** [comment]
@elmindreda As I understand, `valid` here refers to pointer lifetime and is not related to the string contents, for that user would have to use a potential keyboard-layout-changed callback or even not rely on the contents to stay the same. With that said, I believe we need to update the documentation, as pointer no longer becomes invalid on the subsequent call to `glfwGetKeyName`.

>The returned string is allocated and freed by GLFW. You should not free it yourself. **It is valid until the next call to glfwGetKeyName**, or until the library is terminated.

**Comment by ghuser404** [comment]
P.S. Although it never used to be invalidated after the call to `glfwGetKeyName`. I'm confused right now.

**Comment by elmindreda** [comment]
@ghuser404 You're right; this should have kept its name and #1201 should be the issue for the feature. Thanks!

I think the lifetime thing comes from early implementations of `glfwGetKeyName` using a heap-allocated string because some of the corresponding platform APIs look like they can return strings of arbitrary length. Will update the documentation. Thanks again!
