### ISSUE TITLE
glfwJoystickIsGamepad's return value is too vague and leads to redundant calls

### ISSUE THREAD

**Issue by jesta88** [glfw/glfw#1212]
If glfwJoystickIsGamepad returns false, we still have to call glfwJoystickPresent if we want to know that the joystick is connected. Having the function return one of 3 states instead of just GLFW_TRUE or GLFW_FALSE would allow us to prevent the redundant calls to _glfwPlatformPollJoystick.

Something like GLFW_GAMEPAD, GLFW_NOT_GAMEPAD, GLFW_NOT_PRESENT (not great names but I put it there to explain the idea).

**Comment by elmindreda** [comment]
You only need to poll with both functions at initialization. After that you have connection/disconnection events delivered via the joystick callback. Is the need for two calls at initialization a problem in practice on any system?
