### ISSUE TITLE
glfwGetKey returns arrow keys when left analog stick is moved on controller.

### ISSUE THREAD

**Issue by Whirvis** [glfw/glfw#1213]
When using the `glfwGetKey` function, if one of the left analog sticks are moved up, down, left, or right, GLFW will return `GLFW_KEY_UP`, `GLFW_KEY_DOWN`, `GLFW_KEY_LEFT`, or `GLFW_KEY_RIGHT` as a response. Is this intended? At first I thought it was as it would be a useful way to see if an analog stick was pressed but it seems more like it is a glitch as there is no way to check which controller is pressing the analog stick in the returned direction.

Operating system: Windows 10 64-bit
GLFW version: v3.2.1

**Comment by elmindreda** [comment]
It is not intended. Are you running from inside Steam?

**Comment by Whirvis** [comment]
No, I am running from Eclipse Neon 3.

**Comment by elmindreda** [comment]
It sounds like something caused by an OEM utility program trying to be "helpful".

**Comment by Whirvis** [comment]
Could you explain what an OEM is?

**Comment by ghuser404** [comment]
@Whirvis I would guess @elmindreda meant software that came pre-installed on your machine, that you may be unaware of.

**Comment by Whirvis** [comment]
That's odd. I'll look around on my computer and test on some other machines to see if I get different results.
