### ISSUE TITLE
i want stb style（header only）API library

### ISSUE THREAD

**Issue by sdragonx** [glfw/glfw#1221]
suppert c++，using template。suppert android and ios。

**Comment by sdragonx** [comment]
use like this：

#include <glfw.hpp>
//for windows os
glfw::window<GLFW_WINDOWS> window = glfw::create_window<GLFW_WINDOWS>(...);

//for android os
glfw::window<GLFW_ANDROID> window = glfw::create_window<GLFW_ANDROID>(...);

//create opengl context
glfw::opengl_context glc = glfw::create_opengl_context(window);

//audio for windows
glfw::audio_device<GLFW_WINDOWS> audio = glfw::create_audio_device<GLFW_WINDOWS>(...);

//audio for android
glfw::audio_device<GLFW_ANDROID> audio = glfw::create_audio_device<GLFW_WINDOWS>(...);

//play
audio.playsound("a.wav");
audio.playmp3("a.mp3");

**Comment by intrigus** [comment]
Well it's open source, so go ahead :)
But I don't think that it is ever possible to provide glfw as a header only library.

**Comment by elmindreda** [comment]
@sdragonx GLFW is written in C, uses tons of platform-specific headers and does not provide audio support. You seem to want an entirely different project. Perhaps [SFML](https://github.com/SFML/sfml) would be a better fit?
