### ISSUE TITLE
Update Source Code Download in website

### ISSUE THREAD

**Issue by Spacebody** [glfw/glfw#1224]
It seems that the source code downloaded from your website is different from the source code now on your current Github repo, please update it. Thanks.

**Comment by Shimmen** [comment]
The website links to the latest stable release, i.e. version 3.2.1. I think that is resonable. If you want the latest code you can clone the repository.

**Comment by Spacebody** [comment]
It seems that the cloned repo code has fixed some bugs in the stable
version. Thank you.
Simon Moos <notifications@github.com>于2018年3月1日 周四17:11写道：

**Comment by tombsar** [comment]
The maintainers are currently working on getting a new stable release out (see #1098) with multiple bug fixes and enhancements. The source code on the website will be updated when that release is finalized, but until then you are welcome (and encouraged) to clone the github repository.

**Comment by Spacebody** [comment]
@tombsar Thank you.
