### ISSUE TITLE
Unavailable axis value reported by glfwGetGamepadState

### ISSUE THREAD

**Issue by ChengCat** [glfw/glfw#1226]
Thanks for adding the gamepad feature.

Documentation of `glfwGetGamepadState` states:
> Unavailable buttons and axes will always report `GLFW_RELEASE` and 1.0 respectively.

However, by looking at the source code, it seems that `glfwGetGamepadState` will actually report 0.0 for unavailable axes.

I am not sure which is the intended behavior, but in my opinion reporting 0.0 is better.

**Comment by elmindreda** [comment]
Thank you for spotting and reporting this! It has been fixed with 34d20b0f03df5926882611041354d558c0b364dd.
