### ISSUE TITLE
backingScaleFactor not propagated to CAMetalLayer

### ISSUE THREAD

**Issue by gemorin** [glfw/glfw#1229]
I am using the current master branch with MoltenVK and I noticed that the extent advertised by molten vk for a surface created with glfwCreateWindowSurface() was not the size of the backing store but the scaled size (i.e it reports what glfw calls the window size instead of the framebuffer size).  This is because the backingScaleFactor is not propagated to the metal layer and therefore it's unaware it's running in hidpi.

This fixes the problem for me:
```
--- a/src/cocoa_window.m
+++ b/src/cocoa_window.m
@@ -583,6 +583,10 @@ - (void)viewDidChangeBackingProperties
         window->ns.yscale = yscale;
         _glfwInputWindowContentScale(window, xscale, yscale);
     }
+    if (window->ns.layer) {
+        CGFloat scale = [window->ns.view backingScaleFactor];
+        [window->ns.layer setValue:@(scale) forKey:@"contentsScale"];
+    }
 }
 
 - (void)drawRect:(NSRect)rect
@@ -1872,6 +1876,8 @@ VkResult _glfwPlatformCreateWindowSurface(VkInstance instance,
     }
 
     [window->ns.view setWantsLayer:YES];
+    CGFloat scale = [window->ns.view backingScaleFactor];
+    [window->ns.layer setValue:@(scale) forKey:@"contentsScale"];
 
     memset(&sci, 0, sizeof(sci));
     sci.sType = VK_STRUCTURE_TYPE_MACOS_SURFACE_CREATE_INFO_MVK;
```

I am a Obj-C and glfw newbie.  My apologies if it's not very idiomatic.

**Comment by elmindreda** [comment]
This should be fixed now with 2884915000b9fee580713864254dc4fd1b377b45.
