### ISSUE TITLE
glfwGetKey() always return 0, the version is 3.2.1

### ISSUE THREAD

**Issue by Tbwas** [glfw/glfw#1230]

**Comment by tombsar** [comment]
Can you give us any more information about the problem? e.g. your OS, and what code you are trying to run.

It would also be helpful if you could try running against the latest master (effectively pre-release 3.3) to see if the issue has been fixed already.

**Comment by Tbwas** [comment]
OK. The macOS version is 10.12.6, I want to close window when release the escape key. However, the glfwGetKey(window, GL_KEY_ESCAPE) is always return 0 even if I release other keys. The code is 
![image](https://user-images.githubusercontent.com/10513969/37198648-f6e1abc8-23b9-11e8-87ac-24dd0b630a24.png)

**Comment by ghuser404** [comment]
`glfwGetKey` returns current state of the given key, at the moment of the call.

Basically, what you are doing is on any key press/release you are asking GLFW if ESC is not pressed currently.

You should be using the key/scanCode arguments to determine what key got pressed/released.

**Comment by Tbwas** [comment]
@ghuser404 oh~ i got it, thanks very much.
