### ISSUE TITLE
error for MAC_OS_X_VERSION_MAX_ALLOWED

### ISSUE THREAD

**Issue by rf-studios** [glfw/glfw#1232]
When I compiled glfw on MacOS 10.9, I found an error:
MAC_OS_X_VERSION_MAX_ALLOWED >= 100800
The value 100800 may be defined in the > 10.9 version (I guess), but in MacOS 10.9 it is defined in AvailabilityMacros.h, which should be 1080:
/*
  * Set up standard Mac OS X versions
  */
#define MAC_OS_X_VERSION_10_0 1000
#define MAC_OS_X_VERSION_10_1 1010
#define MAC_OS_X_VERSION_10_2 1020
#define MAC_OS_X_VERSION_10_3 1030
#define MAC_OS_X_VERSION_10_4 1040
#define MAC_OS_X_VERSION_10_5 1050
#define MAC_OS_X_VERSION_10_6 1060
#define MAC_OS_X_VERSION_10_7 1070
#define MAC_OS_X_VERSION_10_8 1080
#define MAC_OS_X_VERSION_10_9 1090
...
#define MAC_OS_X_VERSION_MAX_ALLOWED MAC_OS_X_VERSION_10_9
...

I'm sorry! I use google translate, I hope you can understand.

**Comment by elmindreda** [comment]
> I'm sorry! I use google translate, I hope you can understand.

You're perfectly understandable! Thank you for reporting this!

**Comment by elmindreda** [comment]
This should be fixed now with 5f8108e8a9ee4a5747474adb059156824094e610.
