### ISSUE TITLE
Linux C GLFW minimal code, function named "shutdown" is called twice

### ISSUE THREAD

**Issue by francholi** [glfw/glfw#1234]
Hi,

I am working with C (gcc), on Linux, and have an issue that I cannot find the reason for it, something to do with GLFW, Linux and C... (cannot reproduce in with C++ compiler)

```
#include <stdio.h>
#include <GLFW/glfw3.h>

void init() {
  glfwInit();
  return;
};

void shutdown() {
  printf("print twice\n");
};

int main() {
  init();
  shutdown();
  glfwTerminate();
  return 0;
}
```

Code is compiled with: 
cc -Wall -g -O0 minimal_crash.c -lglfw -o main

If I compile with C++, or if I remove glfwInit() it calls shutdown() only once.
If I rename the function shutdown to anything else (eg. shutdownn), is called only once (took a me a while to figure this out)

I believe it has to do with xcb_disconnect, it calls another shutdown function, but I have tried different prototypes for my shutdown function without luck, it is still called twice.
Have not tested on Windows.

Why is this happening?

thanks!

**Comment by tombsar** [comment]
`shutdown` is a standard POSIX function (https://linux.die.net/man/3/shutdown), so creating another function of the same name is probably confusing the linker. C doesn't have as many tools to prevent name clashes as C++ (e.g. namespaces), so it is best to simply avoid duplicate function and variable names.

You can also try declaring your function as `static`, which should prevent anything external from linking to it.

**Comment by francholi** [comment]
Thanks @tombsar,
I have just tested passing an "int" as first argument, the first time gets my argument, the second time I get consistently a number 3 (some socket descriptor?).

What in more general terms you are saying here, is that a posix function can be overriden regardless of the signature I use, just by name.

**Comment by thedmd** [comment]
In C name is the signature, so you're correct.

**Comment by francholi** [comment]
Changing the visibility with static did the job.
And I also got a full backtrace to see who was calling my shutdown.

Breakpoint 1, shutdown (x=3) at minimal_crash.c:10
10	  printf("print twice: %d\n", x);
(gdb) bt full
#0  shutdown (x=3) at minimal_crash.c:10
No locals.
#1  0x00007ffff5f4485b in xcb_disconnect () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
No symbol table info available.
#2  0x00007ffff6fc6677 in XCloseDisplay () from /usr/lib/x86_64-linux-gnu/libX11.so.6
No symbol table info available.
#3  0x00007ffff7bcb2f2 in ?? () from /usr/lib/x86_64-linux-gnu/libglfw.so.3
No symbol table info available.
#4  0x00007ffff7bc6ae0 in glfwTerminate () from /usr/lib/x86_64-linux-gnu/libglfw.so.3
No symbol table info available.
#5  0x0000000000400791 in main () at minimal_crash.c:16


Thanks for the help.
