### ISSUE TITLE
GLFW 3.2 and 3.2.1 prevent the use of CRT memory leak detection (Windows, VS2015).

### ISSUE THREAD

**Issue by kundelstein** [glfw/glfw#1240]
Somehow after calling glfwInit () automatic memory leak detection using CRT library doesn't get called on exit. This is regardless of the use of:
_CrtSetDbgFlag (_CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF);

Manual call at the end to: _CrtDumpMemoryLeaks() works fine, but as we all know, we are getting lots of false positives then due to static objects not being released yet.

It works fine in GLFW 3.1.2
EDIT: It works in GLFW 3.1.2 until glfwCreateWindow gets called.

**Comment by ghuser404** [comment]
Did you try it on the latest trunk?

**Comment by kundelstein** [comment]
Yes, it doesn't work.
I remember long time ago (years) I used to check for memory leaks in project based on GLFW. Today I tried a few versions of 3.* lineup and couldn't get any of them to work along with CRT mem leak detection.

**Comment by Fincodr** [comment]
I am reporting the same issue with 3.3 (latest master branch). Any progress or known workaround on this?

**Comment by kundelstein** [comment]
Not really. I dropped the subject. I noticed that some of my project doesn't have this issue so it is probably some build settings but never actually had a time to look into it.

**Comment by Fincodr** [comment]
Oops.. You're right! It was simple problem with my build settings.. I was using Multi-threaded DLL (/MD) runtime library.. instead it is required to use Debug (/MDd or /MTd) runtime libraries for the CRT mem leak detection to work. Thanks for your help :)

**Comment by paintdream** [comment]
> Yes, it doesn't work. I remember long time ago (years) I used to check for memory leaks in project based on GLFW. Today I tried a few versions of 3.* lineup and couldn't get any of them to work along with CRT mem leak detection.
> 
> EDIT: Checked the insides of the GLFW. It looks like the call to BringWindowToTop is the point where things get weird. It is even stranger that it is a call to WinUser function, which is M$ itself.
> 
> EDIT2: Same goes to Visual Leak Detector - it doesn't work after using GLFW method.

The same issue to me. A simple workaround is to remove the call to 'wglDeleteContext' in function 'destroyContextWGL'.

**Comment by elmindreda** [comment]
I'm closing this as it doesn't seem to be an issue in GLFW.
