### ISSUE TITLE
Unable to create OpenGL 3.3 context over RDP

### ISSUE THREAD

**Issue by grebenyukaa** [glfw/glfw#1245]
Steps to reproduce:
  1. Run glfw-based application over RDP session, for example this one https://github.com/wjakob/instant-meshes
  1. Observe error: 
> Caught fatal error: Unable to create an OpenGL 3.3 context

When starting the same app from a physical session, the error is not observed and the app starts normally.
Other OpenGL 3.3 apps are starting normally in RDP session, like Solidworks.

Also, it can be workarounded with an old trick, described here:
https://social.technet.microsoft.com/Forums/windowsserver/en-US/c8295ef8-3711-4576-9293-2c4965280165/opengl-and-remote-desktop?forum=winserverTS

**Comment by elmindreda** [comment]
> Also, it can be workarounded with an old trick, described here:
https://social.technet.microsoft.com/Forums/windowsserver/en-US/c8295ef8-3711-4576-9293-2c4965280165/opengl-and-remote-desktop?forum=winserverTS

That's a long thread. What is the trick?

**Comment by grebenyukaa** [comment]
Nothing useful from developer's point of view, but you can create a batch-script like:
>tscon 1 /dest:console
start glfw-app.exe

The first line forces an RDP session to become a physical one and disconnects the current RDP session. The second line starts the app.

After that you can reconnect via RDP to the newly created physical session and work with the app normally.  This obviously is utterly inconvenient, but can help to start the app remotely and work with it.

**Comment by elmindreda** [comment]
This is outside the scope of GLFW then.

**Comment by SairesArt** [comment]
I'm killing myself over this. I love GLFW, but am in need of making it work with Windows RDP, since in corporate enviroments this is used all the time.
With SDL I found [this tip for enabling Rendering into system memory](https://stackoverflow.com/questions/4050110/sdl-remote-desktop#4051035).
No idea wheter this allows for INIT to even function correctly which is the crux of the problem... Is there any equivalent in GLFW?

**Comment by elmindreda** [comment]
@SairesArt I don't think that's relevant to OpenGL but rather to directly blitting pixels into a window.

**Comment by SairesArt** [comment]
@elmindreda Thanks for the tip. Could you point me to a resource on how to do that? So far I always fail at making a windows even appear over Windows RDP

**Comment by elmindreda** [comment]
@SairesArt I have little experience with RDP, sorry.

**Comment by SairesArt** [comment]
@elmindreda ahh,OK. I have yet to find a resource myself.
Gonna try the Mesa route. If.I understand it correctly,  mesa not only functions as a software renderer when no alternative is found, it uses hardware acceleration if it is possible.

Will report back if I get it working

**Comment by SairesArt** [comment]
@elmindreda I have compiled GLFW with OSMesa, but can't get a window created with it. Could you point me to resources on how to get the Offscreen Buffer into a window? I can't get any sense out of GLFW Context documentation for this problem.

**Comment by malamanteau** [comment]
Mixing RDP and OpenGL is difficult/impossible to make reliable. There are situations and configurations that work, but it's patchy. I've had good luck building GL apps using GLFW (latest git) plus ANGLE. This lets you write GLES3.0 (virtually identical to desktop GL 3+) code, but use the Direct3D 11 driver, which works well with RDP, particularly on Windows 10. My $0.02, anyway. Good luck!

https://github.com/Microsoft/angle

**Comment by elmindreda** [comment]
This does not appear to be something GLFW can fix.
