### ISSUE TITLE
glfwVulkanSupported returning 0 on OSX (With MoltenVK) [#1073]

### ISSUE THREAD

**Issue by mrdev023** [glfw/glfw#1248]
I have the same problem

- Source Code : https://github.com/mrdev023/TUTO_VULKAN/tree/0b1e4c0728fb7d645cecbb6b570082516573cd5d
- Install include folder in /usr/include/
- Install libMoltenVK.dylib and MoltenVK.framework in /usr/lib
- It Work in Linux
- glfw installed with ```$ brew install glfw --HEAD```

Result of ```$ brew list glfw```
```
/usr/local/Cellar/glfw/HEAD-23dfeee/include/GLFW/ (2 files)
/usr/local/Cellar/glfw/HEAD-23dfeee/lib/libglfw.3.3.dylib
/usr/local/Cellar/glfw/HEAD-23dfeee/lib/cmake/ (4 files)
/usr/local/Cellar/glfw/HEAD-23dfeee/lib/pkgconfig/glfw3.pc
/usr/local/Cellar/glfw/HEAD-23dfeee/lib/ (2 other files)
```
Log: 

```
[mvk-info] MoltenVK version 0.19.0. Vulkan version 1.0.64.
[mvk-info] GPU device Intel(R) Iris(TM) Plus Graphics 640 supports the following Metal Feature Sets:
        OSX GPU Family 1 v3
        OSX GPU Family 1 v2
        OSX GPU Family 1 v1
Available extensions:
        VK_MVK_moltenvk
        VK_KHR_swapchain
        VK_KHR_surface
        VK_AMD_negative_viewport_height
        VK_MVK_macos_surface
Required Extensions :
VkResult : -3
failed to create window surface!
```

**Comment by elmindreda** [comment]
If brew used the latest GLFW pre-3.3 code then it's no longer checking for `libMoltenVK.dylib`. Instead it looks for `libvulkan.1.dylib`, the new name used by the [macOS LunarG Vulkan SDK](https://vulkan.lunarg.com/).

**Comment by elmindreda** [comment]
You can customize the name used by defining the `_GLFW_VULKAN_LIBRARY` macro to the desired string when building GLFW.

**Comment by mrdev023** [comment]
It works Thanks.

For those who have the same problem
- [Download SDK](https://vulkan.lunarg.com/sdk/home)
- Add Env Variables in .bashrc or in .zshrc
- with cmake add linker and include path [optional]

My Env Variables:
```
export VULKAN_SDK=/Users/$USER/vulkansdk-macos-1.0.69.0/macOS
export PATH=$VULKAN_SDK/bin:$PATH
export VK_ICD_FILENAMES=$VULKAN_SDK/etc/vulkan/icd.d/MoltenVK_icd.json
export VK_LAYER_PATH=$VULKAN_SDK/etc/vulkan/explicit_layers.d
export DYLD_LIBRARY_PATH=$VULKAN_SDK/lib:$DYLD_LIBRARY_PATH
export VULKAN_FRAMEWORK_PATH=$VULKAN_SDK/Frameworks
export DYLD_FRAMEWORK_PATH=$VULKAN_FRAMEWORK_PATH:$DYLD_FRAMEWORK_PATH
```

CMakeLists.txt
```
...
IF (APPLE)
    link_directories($ENV{VULKAN_SDK}/lib)
    include_directories($ENV{VULKAN_SDK}/include)
ENDIF()
...
target_link_libraries(
    ...
    vulkan
)
```

**Comment by maddanio** [comment]
no dice here :(

**Comment by Znapi** [comment]
I am also having issues getting GLFW to work with MoltenVK on macOS. It seems that CMake requires the variables VULKAN_LIBRARY and VULKAN_INCLUDE_DIR to be set. Using `cmake . -DVULKAN_LIBRARY=... -DVULKAN_INCLUDE_DIR=...` worked for me, and cmake says it found vulkan.

Calling `glfwVulkanSupported` still returns false though. What is GLFW looking for during runtime that might be making this false?

**Comment by elmindreda** [comment]
> Calling `glfwVulkanSupported` still returns false though. What is GLFW looking for during runtime that might be making this false?

It loads the Vulkan loader library, loads a few function pointers from it and checks if any of the surface creation extensions we support are present.

> Adding that VULKAN_LIBRARY and VULKAN_INCLUDE_DIR need to be set for cmake to the docs is probably a good idea though.

GLFW itself doesn't need those or any part of the Vulkan SDK, they're only used to build the test program. Is application re-using those CMake variables from the GLFW subdirectory?

**Comment by csantosbh** [comment]
Make sure you build your application according to the build guide (https://www.glfw.org/docs/latest/build_guide.html). I personally like to build with cmake and glfw source.

Also make sure you call `glfwInit()` prior to the check `glfwVulkanSupported()`.

**Comment by KaoCC** [comment]
it seems like `glfwVulkanSupported` cannot recognise MoltenVK installed from Conan.

For example in conanfile.txt I have:

```
[requires]
moltenvk/1.1.9

[generators]
cmake
```

but `glfwVulkanSupported` still returns 0 despite that I can call other VK APIs directly and can include the Vulkan header .
