### ISSUE TITLE
GLFWinit is putting GLFW in invalid state with no error being output

### ISSUE THREAD

**Issue by jacobmcleman** [glfw/glfw#1249]
Compiling  from source on .

OS and version: Windows 10 64 bit
GPU and driver: GTX 1080 Nvidia driver version 391.35
Release or commit: GLFW static 3.2.1
Version string: 3.2.1 Win32 WGL EGL VisualC

Code I have to reproduce the error:
```
GLFWmonitor * primaryMonitor = glfwGetPrimaryMonitor();
const GLFWvidmode* mode = glfwGetVideoMode(primaryMonitor);
```

Began looking into a bug where `glfwGetPrimaryMonitor();`  was returning an invalid pointer (contained windows heap FD guard bytes in debug mode). This function seems to just return the monitors array from the internal glfw state.

I don't think the problem is in my code or glfw, but glfw is not catching that it is in an invalid state.

So I went digging, traced the code into win32_monitor.c (_glfwPlatformGetMonitors) and found that
 ```
if (adapter.StateFlags & DISPLAY_DEVICE_PRIMARY_DEVICE)
            primaryIndex = found;
``` 
was finding a new primary monitor that was then rejected by the statement below 
```
if (!EnumDisplayDevicesW(adapter.DeviceName, displayIndex, &display, 0))
                    break;
```
primaryIndex is being set to 1 by the first case, and then because the second check fails there is only a single monitor in the array, and so when the pointers are swapped before returning, the monitors array now contains only a single invalid monitor. 

The root cause of the problem is probably in my system somewhere, but there is no check to make sure that the primary monitor index is actually within the bounds of the monitors array before copying and using that memory.

**Comment by elmindreda** [comment]
Thank you for reporting this! However, that logic has already been removed and replaced in the current version.
