### ISSUE TITLE
GLFW Win32 build, wrong linker directory for vulkan

### ISSUE THREAD

**Issue by vchizhov** [glfw/glfw#1259]
Hi,

After generating a solution with cmake for VS2017 win32, the vulkan project in tests can't be built. More precisely the vulkan project seems to include the 64bit vulkan-1.lib that resides in the Lib directory rather than the 32bit version that resides in the Lib32 directory. Changing the project to link to the correct folder makes it compile without issues.

**Comment by elmindreda** [comment]
Cannot reproduce this with `master`. What version of GLFW are you using?

**Comment by vchizhov** [comment]
The version I have is 3.2.1. I made the visual studio solutions with cmake from the cmakelists.txt. I am assuming that for some strange reason  ${VULKAN_STATIC_LIBRARY} was substitued with the 64bit library path rather than the 32 bit one.

**Comment by elmindreda** [comment]
GLFW 3.2.1 is older than the new Vulkan SDK directory layout so it'll likely fail. Try building from `master`, which has been updated for the current layout.

**Comment by vchizhov** [comment]
Thank you. As I said, this was easy to fix so I had no issue. I just mentioned it just so that you are aware since 3.2.1 is the latest stable release version.

**Comment by elmindreda** [comment]
Thank you!
