### ISSUE TITLE
Retrieve window refresh rate

### ISSUE THREAD

**Issue by SephiRok** [glfw/glfw#1262]
Would it be reasonable and possible get a way to retrieve a window's refresh rate?

Perhaps by
`glfwGetWindowAttrib(window, GLFW_REFRESH_RATE)`

Currently struggling to determine what refresh rate was set when letting GLFW choose the most appropriate one. This is, for example, helpful so one can match frame and other update rate limits when vertical synchronization is on.

Sorry if there's already a way and I missed it -- I could not find it in the documentation.

**Comment by ghuser404** [comment]
How about `glfwGetVideoMode`?

**Comment by SephiRok** [comment]
That works, thanks!

**Comment by Emill** [comment]
`glfwGetVideoMode` doesn't work if you don't run in full screen and you have multiple monitors. When you have multiple monitors, the refresh rate that is chosen for the window seems to follow the monitor where (most of) the window is placed. Any way to retrieve the current monitor for a window?
