### ISSUE TITLE
glfwSetCharModsCallback doesn't work when Super is pressed

### ISSUE THREAD

**Issue by medvednikov** [glfw/glfw#1272]
Hi,

According to http://www.glfw.org/docs/latest/group__input.html:

> The character callback behaves as system text input normally does and will not be called if modifier keys are held down that would prevent normal text input on that platform, for example a Super (Command) key on OS X or Alt key on Windows. There is a character with modifiers callback that receives these events.

I need to receive characters with the Super key pressed, but unfortunately I get nothing in my `void(* GLFWcharmodsfun) (GLFWwindow *, unsigned int, int)` when ⌘ is pressed.

I'm using the latest GLFW build on macOS High Sierra.

**Comment by elmindreda** [comment]
The charmods callback has been deprecated.
