### ISSUE TITLE
website glfw.org seems to be down

### ISSUE THREAD

**Issue by admunro** [glfw/glfw#1274]
Is glfw.org down?

I have no access, and testing from https://www.uptrends.com/tools/uptime shows failures from all global test points.

**Comment by tombsar** [comment]
It's loading fine for me right now. It was probably just a blip.

**Comment by elmindreda** [comment]
Sorry. My ISP has been acting up. I'm currently moving web hosting to GH Pages.

**Comment by admunro** [comment]
Me too - all good :-)
