### ISSUE TITLE
 CMake Error at CMakeLists.txt:96 (set_target_properties):           set_target_properties called with incorrect number of arguments.

### ISSUE THREAD

**Issue by Guang1234567** [glfw/glfw#1277]
Hello dev:

when i use  win7x64 cmake3.7.2  vs2015  to  compile  glfw-master-branch. i get below error. 

Help me, please.

```ruby
You have called ADD_LIBRARY for library glfw without any source files. This typically indicates a problem with your CMakeLists.txt file

 CMake Error at CMakeLists.txt:96 (set_target_properties):
          set_target_properties called with incorrect number of arguments.
```

**console output :** 

        You have called ADD_LIBRARY for library glfw without any source files. This typically indicates a problem with your CMakeLists.txt file
        CMake Error at CMakeLists.txt:96 (set_target_properties):
          set_target_properties called with incorrect number of arguments.

        CMake Warning (dev) in CMakeLists.txt:
          No cmake_minimum_required command is present.  A line of code such as

            cmake_minimum_required(VERSION 3.7)

          should be added at the top of the file.  The version specified may be lower
          if you wish to support older CMake versions for this project.  For more
          information run "cmake --help-policy CMP0000".
        This warning is for project developers.  Use -Wno-dev to suppress it.

        Configuring incomplete, errors occurred!
        See also "F:/lean_opengl/glfw/build/CMakeFiles/CMakeOutput.log".

**Comment by Guang1234567** [comment]
Is my variables **${GLFW_LIB_NAME}** and  **${GLFW_VERSION}** are undefine?  

set_target_properties(glfw PROPERTIES
                      OUTPUT_NAME ${GLFW_LIB_NAME}
                      VERSION ${GLFW_VERSION}
                      SOVERSION ${GLFW_VERSION_MAJOR}
                      POSITION_INDEPENDENT_CODE ON
                      FOLDER "GLFW3")

**Comment by Guang1234567** [comment]
My solution：


！[](https://images2015.cnblogs.com/blog/1129428/201706/1129428-20170603173728977-1253843137.jpg)


If  your system is  **Win7 X64** ，  still select **“visual studio 14 2015” **   not **“visual studio 14 2015 X64” ** !!!

！[](https://images2015.cnblogs.com/blog/1129428/201706/1129428-20170603173448211-119787000.jpg)

**Comment by DanielChabrowski** [comment]
My guess is you took wrong CMakeLists. I get the same result when I run cmake from src directory. In your "solution" you run it correctly from root glfw directory. I would say there's no issue. If that's not the case, could you provide full log, please?

**Comment by Guang1234567** [comment]
@DanielChabrowski 

There's no issue!  Thanks for your reply.  

 **Run it (CMake) correctly from root glfw directory, not src directory!**
