### ISSUE TITLE
FindVulkan.cmake not aligned with version delivered by cmake 3.10 installs

### ISSUE THREAD

**Issue by ThomasL81** [glfw/glfw#1278]
Hi, I'm working on a multi-lib cross-platform app, using the Vulkan API and cmake.
I'm using a recent version of CMake, which delivers a FindVulkan module. 
GLFW is included as a git submodule and is built as part of my CMake project structure.
Certain libraries in my project structures also depend on the FindVulkan module (which ones don't reference the GLFW library). Only there I refer to the CMake delivery.

On Mac, i'm finding the glfw version conflicts with the standard version as the find_library and find_path calls explicitly refer to macOS subdirectory:

```
    find_library(VULKAN_LIBRARY vulkan.1 HINTS
        "$ENV{VULKAN_SDK}/macOS/lib")
    find_path(VULKAN_INCLUDE_DIR NAMES vulkan/vulkan.h HINTS
        "$ENV{VULKAN_SDK}/macOS/include")
```

If you compare it to the Cmake delivery, it doesn't have this exception code.
The [LunarG documentation](https://vulkan.lunarg.com/doc/sdk/1.1.73.0/mac/getting_started.html) for the Mac API (see section Command Line) also includes the macOS folder in the VULKAN_SDK environment variable. 
This way the FindVulkan (GLFW version or CMake version) is still matching the documentation.

An example of how the environment variables are then set:
> export VULKAN_SDK="/Users/<username>/Development/libs/vulkansdk-macos-1.1.73.0/macOS"
> export DYLD_LIBRARY_PATH="$VULKAN_SDK/lib"
> export VK_LAYER_PATH="$VULKAN_SDK/etc/vulkan/explicit_layers.d"
> export VK_ICD_FILENAMES="$VULKAN_SDK/etc/vulkan/icd.d/MoltenVK_icd.json"
> export PATH="$VULKAN_SDK/bin:/opt/local/bin:/opt/local/sbin:$PATH"

The CMake version of the module can be found on their [official git repo](https://github.com/Kitware/CMake/blob/master/Modules/FindVulkan.cmake)

I'm running:
MacOS: 10.13.2 (High Sierra)
Visual Studio Code
CMake version 3.10.1

Thanks!
Rgds,
Thomas

**Comment by elmindreda** [comment]
Thank you! This should be fixed now with bf6551a3cab44d3bb2dae0d782dfa1fcef1c699c.
