### ISSUE TITLE
[X11] glfwSetWindowAspectRatio doesn't work

### ISSUE THREAD

**Issue by ghuser404** [glfw/glfw#1286]
I tried the `boing` example, the window didn't keep aspect ratio when resized. Tried on 2 different machines, both master and 3.2.1. No success.

Am I missing something?

**Comment by elmindreda** [comment]
Probably not, it's supposed to be very straightforward. What window manager did you use?

**Comment by ghuser404** [comment]
Compiz.

Those 2 machines are very old, Ubuntu 12.04 LTS and 14.04 LTS, and probably use some old version of that window manager, that most likely doesn't have support for how aspect ratio is done in GLFW.

I've now installed latest Ubuntu 18.04 LTS on virtual machine, and it works perfectly fine.
I'm not too bothered about old version of Compiz, so I'll just close this issue.

Thanks!
