### ISSUE TITLE
GLFW_TRANSPARENT_FRAMEBUFFER, laptop, incompatible with the real GPU (only the integrated graphic works)

### ISSUE THREAD

**Issue by c-sonntag** [glfw/glfw#1288]
Hello, I could try your new option "GLFW_TRANSPARENT_FRAMEBUFFER" and I find it very interesting.
```cpp
glfwWindowHint (GLFW_DEPTH_BITS, 16);
glfwWindowHint (GLFW_TRANSPARENT_FRAMEBUFFER, GLFW_TRUE);
```
However I use a laptop, and this option is only valid with my "integrated" graphics processor, not my Nvidia Geforce GPU ...
Do you think you can, in the future, make this transparency option compatible with the real GPU?
Yours truly.

**Comment by ghuser404** [comment]
Are your drivers up-to-date for your Nvidia card?

**Comment by orange451** [comment]
My first guess would be with the drivers, not with GLFW.

**Comment by elmindreda** [comment]
Unable to reproduce on Nvidia Optimus laptop (710M + HD 4000) running Windows 7. Drivers 391.35 and 10.18.10.4653.

**Comment by c-sonntag** [comment]
I have a NVidia Geforce GTX 860M with graphics drivers that are up to date (version 398.11).
Everything works in "integrated graphics" mode, that is, with my Intel HD Graphics 4600 GPU.
However no transparency in "NVidia high performance processor" GPU mode ...
@elmindreda did you launch in GPU mode "high performance"?

**Comment by c-sonntag** [comment]
![choosing-gpu](https://user-images.githubusercontent.com/15939808/41475260-934445ce-70be-11e8-972e-aa054d3305ba.png)
---
![gear-transparency](https://user-images.githubusercontent.com/15939808/41475265-9672f8c6-70be-11e8-9d35-62988ab7fe1c.png)

**Comment by ghuser404** [comment]
I've tried this on my myachine and I can confirm the bug, the window is fully transparent.

It appears to happen because of this code
```
// Decorated windows don't repaint the transparent background
// leaving a trail behind animations
// HACK: Making the window layered with a transparency color key
//       seems to fix this.  Normally, when specifying
//       a transparency color key to be used when composing the
//       layered window, all pixels painted by the window in this
//       color will be transparent.  That doesn't seem to be the
//       case anymore, at least when used with blur behind window
//       plus negative region.
LONG exStyle = GetWindowLongW(window->win32.handle, GWL_EXSTYLE);
exStyle |= WS_EX_LAYERED;
SetWindowLongW(window->win32.handle, GWL_EXSTYLE, exStyle);
```
I've looked deeper into this issue and people seem to say that `DwmEnableBlurBehindWindow` no longer works on Windows 10, and suggest using an undocumented call to `SetWindowCompositionAttribute`. I've been successful in making the window blurry following the code here https://gist.github.com/ethanhs/0e157e4003812e99bf5bc7cb6f73459f

This may help someone to look into this further to achieve the desired behaviour.

**Comment by c-sonntag** [comment]
After an recent update of NVidia driver, the transparency works !
Thinks anyway.

**Comment by Grantim** [comment]
Hello!
Looks like this is happening again. 
```c++
glfwWindowHint (GLFW_TRANSPARENT_FRAMEBUFFER, GLFW_TRUE);
```
does not work (window thinks that it has transparent framebuffer, but it is not) with NVIDIA drivers >= 526 on my laptop, but it works fine with older drivers or with integrated GPU. (I have `NVIDIA GeForce RTX 3070 Laptop GPU/PCIe/SSE2` discrete GPU).

Is there any workaround, or I should just wait for NVIDIA to fix that?
Thanks!

**Comment by philipguin** [comment]
I've gotten this issue today as well. Integrated graphics works perfectly, NVIDIA version totally opaque, no transparency.

GLFW version (shipped with LWJGL): 3.4.0
Intel renderer: "Intel(R) UHD Graphics"
NVIDIA renderer: "NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2"
NVIDIA driver: 528.24 (latest Game Ready driver as of now)

**Comment by alexjchn** [comment]
the same problem here, windows 11, 
[image](https://user-images.githubusercontent.com/20543726/231787721-dac64e84-ed8b-4e5d-8690-9b9c2dc5eb7d.png)
NVIDIA geforce gtx 1650

**Comment by Grantim** [comment]
I have noticed that when the integrated GPU on my laptop is disabled (which can be done in the BIOS), transparency works fine. Therefore, it may be related to the system's decision on how to separate computation between the integrated and discrete GPUs.

**Comment by Renardjojo** [comment]
Same problems here too on Windows 11. My driver is updated and transparency no longer works

**Comment by 4skl** [comment]
I found that I had the same problem and it was caused by thoses two lines 
```c
//force use dedicated graphic card //https://stackoverflow.com/questions/16823372/forcing-machine-to-use-dedicated-graphics-card
__declspec(dllexport) unsigned long NvOptimusEnablement = 1;
__declspec(dllexport) int AmdPowerXpressRequestHighPerformance = 1;
```
Removing them solve the issue in my case (glfw 3.3)
