### ISSUE TITLE
Range of gamepad axes mapped from digital source incorrect?

### ISSUE THREAD

**Issue by sammko** [glfw/glfw#1293]
Some gamepads do not have analogue triggers. In such cases, the mapping simply assigns a digital source to the axis -- usually a button (apparently always, in the current SDL_GameControllerDB). Let's call this type of mapping a digital axis. This case is handled [here](https://github.com/glfw/glfw/blob/0be4f3f75aebd9d24583ee86590a38e741db0904/src/input.c#L1255) in glfw. The resulting range of the axis is from 0 to 1.0 instead of the expected(?) -1.0 to 1.0. Other gamepads with analogue triggers produce values in the full range. I propose changing the behaviour to something like this:
```state->axes[i] = js->buttons[e->index] ? 1.0f : -1.0f;```
Similarly with the hat case [just above](https://github.com/glfw/glfw/blob/0be4f3f75aebd9d24583ee86590a38e741db0904/src/input.c#L1252).

Of course, one has to consider the behaviour with regard to standard "stick" axes, which in the default state are expected to return 0.0f. The current SDL_GameControllerDB contains only two cases of this

1. the `030000000d0f00000d00000000010000,hori` with `leftx:b4,lefty:b5` and
2. the `03000000100000008200000000000000,PS360+ v1.66` with `leftx:h0.4`.

The negative range is however never reached in these two mappings, which, to me, makes no sense either. On the other hand, cases of digital triggers in the database are countless.

Another option is to mimic SDL, which always uses the [positive-only range with triggers](https://github.com/SDL-mirror/SDL/blob/master/include/SDL_gamecontroller.h#L297). The current glfw implementation follows [that of SDL](https://github.com/SDL-mirror/SDL/blob/a2a09abf66a72abead51ee95ff9120000d5c9c9b/src/joystick/SDL_gamecontroller.c#L1602), which also only returns positive values for digital axes. This makes sense in SDL, due to the different trigger range.

I appreciate any thoughts.

**Comment by tombsar** [comment]
Personally, I think 0 to 1 range makes the most sense for both analogue and digital triggers. Is there a good reason we went with -1 to 1 in the first place?

**Comment by elmindreda** [comment]
> Personally, I think 0 to 1 range makes the most sense for both analogue and digital triggers. Is there a good reason we went with -1 to 1 in the first place?

There is no good reason for it. It's my mistake, sorry. At this point I'm afraid enough people are running `master` that we'll have to wait until the next API revision to fix it. I'll make them all map to [-1,1] for now.

@sammko Thank you for spotting this!
