### ISSUE TITLE
IsWindows8Point1OrGreater fails on Windows 10

### ISSUE THREAD

**Issue by ghuser404** [glfw/glfw#1294]
Both `IsWindows8Point1OrGreater` and `IsWindows10OrGreater` fail on Windows 10. This is because Windows 10 deprecates `VerifyVersionInfo`.
> While you can still call the deprecated functions, if your application does not specifically target Windows 8.1 or Windows 10, you will get Windows 8 version (6.2.0.0).

https://msdn.microsoft.com/en-gb/library/windows/desktop/dn481241(v=vs.85).aspx

Among other things, this leads to per-monitor DPI not behaving correctly on Windows 10.
```
if (IsWindows8Point1OrGreater())
    SetProcessDpiAwareness(PROCESS_PER_MONITOR_DPI_AWARE);
else if (IsWindowsVistaOrGreater())
    SetProcessDPIAware();
```
This requires application to provide app manifest.
Internet suggests 2 solutions to this problem, if you want to avoid including app manifest:
1. Use `RtlGetVersion`
https://stackoverflow.com/questions/36543301/detecting-windows-10-version
2. Query version of `kernel32.dll` (this will not work well with compatibility options).

Now, while I could mess around with app manifest myself, GLFW tests and examples will still behave incorrectly.

**Comment by elmindreda** [comment]
Yup, thank you! I'm looking into this right now as I'm working on Windows 10 DPI support. So far I'm leaning towards judging a system by what functions and messages are available and abandoning the versionhelpers route altogether.

We should probably also try to teach how to embed a suitable manifest on toolchains where this isn't done by default.

**Comment by elmindreda** [comment]
I hadn't until now. `RtlVerifyVersionInfo` looks useful too.

**Comment by ghuser404** [comment]
Presumably it does the same what `VerifyVersionInfo` does, but works? We should check that.

**Comment by ghuser404** [comment]
I think the most recommended way is to do a feature check instead of a system check anyway. The system check may be a bit more convenient though.

**Comment by ghuser404** [comment]
I tried `RtlVerifyVersionInfo`, works like a charm.

**Comment by ghuser404** [comment]
Can this possibly be flagged `3.4`?

**Comment by elmindreda** [comment]
I was leaning more towards 3.3. Implemented it in my Windows 10 DPI branch today and it indeed works like a charm.

**Comment by ghuser404** [comment]
This is even better, thanks!

**Comment by amerkoleci** [comment]
Did you submitted PR?

**Comment by elmindreda** [comment]
@amerkoleci Not yet. Non-FOSS things are keeping me busy at the moment.

**Comment by amerkoleci** [comment]
I submitted PR, dunno if the coding style is ok tho.
