### ISSUE TITLE
Stop initializing GLFW second time

### ISSUE THREAD

**Issue by wrymn** [glfw/glfw#1296]
Hi,

I am using java [imgui ](https://github.com/ice1000/jimgui) library to draw game editor on top of our existing java game framework that uses GLFW.

The problem as you can see that both, our framework (which I cannot modify) and the graphics library (not ours) does initialize GLFW instance. When one of these frameworks does initialize GLFW second time, application does crash on:

`Win32: Failed to register window class`
(which is expected)

Is there any possible way how to solve this issue? Or how to re-use some GLFW instance or pointer?

Thank you

**Comment by elmindreda** [comment]
`glfwInit` can be called any number of times and will succeed immediately if GLFW is already initialized. Instead it sounds like there's more than one copy of GLFW in your process. GLFW doesn't yet support multiple copies of itself in a single process, though I will look into supporting this after 3.3.

In the meantime, if possible try to have all parts of your application call the same copy of GLFW.

**Comment by tombsar** [comment]
@wrymn Is this still an issue for you, or did you find a way to resolve it at your end?

**Comment by elmindreda** [comment]
This error should be fixed now with 07a5518c3e42f4412a5d9fa8620950d8f5041e28. Thank you!
