### ISSUE TITLE
cross compiling GLFW

### ISSUE THREAD

**Issue by SimonDanisch** [glfw/glfw#1297]
Hi,
[Julia](https://julialang.org/) offers an awesome cross compilation platform: https://github.com/JuliaPackaging/BinaryBuilder.jl/

I set up a builder for [GLFW](https://github.com/SimonDanisch/GLFWBuilder/releases), which already works for OSX. 
Now I want to know if it's possible to crosscompile for linux as well. 
Do I understand it correctly, that we just need to install the X11 headers correctly, but won't actually need to have the binaries installed in the sandbox?
Would be nice if someone who knows more about cmake + GLFW could help me with that!

The resulting binaries should work for any project, so I hope this offers some value to everyone here ;)

Best,
Simon

CC: @keno, @staticfloat, @jayschwa

**Comment by jayschwa** [comment]
We should try to support Wayland in addition to X11. I'm not sure if support for both backends can be compiled into the same libglfw. If not, then I suppose two libraries can be built and GLFW.jl can select one at runtime.

**Comment by elmindreda** [comment]
The main branch of GLFW, which will become 3.4, now supports both building without linking against any X11 or Wayland libraries, and building a single GLFW binary that contains support for both X11 and Wayland.
