### ISSUE TITLE
GLFW Callbacks can't update custom objects!

### ISSUE THREAD

**Issue by babaliaris** [glfw/glfw#1302]
Because callbacks are c functions you can't actually update anything inside them except Global variables.
Is it too difficult to change callbacks in a next release  of GLFW and make the work like this?

```c
glfwSetFramebufferSizeCallback(window, (void *)MyWindowObject, OnWindowResize)

void OnWindowResize(GLFWwindow *window, void *object, int width, int height)
{
    WindowClass *w = (WindowClass *)object;

    w->SetWindowWidth(width);
    w->SetWindowHeight(height);
}

We really need a functionality like this in GLFW!!!
Whoever agrees, please support this issue so we can see some changes in the next release!!

**Comment by TheMrMilchmann** [comment]
The functionality you are asking for already exists. See http://www.glfw.org/docs/latest/window_guide.html#window_userptr.

**Comment by babaliaris** [comment]
Oh ok I understand know. Probably I missed that when I was reading the documentation. Thanks anyway!!!!
