### ISSUE TITLE
Cursor stuck in the center of window in OpenGL

### ISSUE THREAD

**Issue by ltqsoft** [glfw/glfw#1306]
When switching between GLFW_CURSOR_DISABLED and GLFW_CURSOR_NORMAL input mode, the cursor shows but it always get back to center of the window. The cursor alway stay at the center event if I switched modes several times. #

**Comment by tombsar** [comment]
Which Operating System and (if applicable) window manager are you experiencing the problem on?

**Comment by elmindreda** [comment]
Also is it running inside a virtual machine?

**Comment by ltqsoft** [comment]
'm using Windows 10 with Insider Program turned on, and I'm not running any virtual machines.

**Comment by elmindreda** [comment]
Just to clarify, the issue is that the cursor is visible in the middle of the window when in disabled mode?

**Comment by elmindreda** [comment]
Disabled cursor mode and switching between it and normal mode appear to work as expected on my machine running Windows 10 version 1709.

**Comment by ltqsoft** [comment]
The issue is that when exiting disabled mode and come to normal mode, the cursor is visible again as I expected, but somehow it always get back to the center no matter how I move the mouse. When in disabled mode it's gone of course.
Maybe I should call another function to solve this issue but I don't know which one to call.
And BTW, the version of OpenGL I used was 4.5.

**Comment by elmindreda** [comment]
Can you reproduce this with the `cursor` test program in the `tests` directory? Use the <kbd>D</kbd> and <kbd>N</kbd> keys to switch between modes.

**Comment by ltqsoft** [comment]
Here is s sample code:
https://github.com/ltqsoft/glTest
Hope I didn't miss something.

**Comment by elmindreda** [comment]
It looks like you're [calling `glfwSetInputMode` from a secondary thread](https://github.com/ltqsoft/glTest/blob/master/TestLab/TestLabGL/evilGlobals.h#L126). This is [not supported](http://www.glfw.org/docs/latest/group__input.html#gaa92336e173da9c8834558b54ee80563b) and will probably break in interesting ways. It may be what's causing your problem. There doesn't seem to be any reason to run these code sections in their own threads, so it may be easy to fix.

**Comment by ltqsoft** [comment]
Looks like I should use key callback instead of call the glfwGetKey() directly in my thread, thank you for the tip.
