### ISSUE TITLE
glfwInit() causes device disconnect and reconnect sounds on Windows 10.

### ISSUE THREAD

**Issue by Millerni456** [glfw/glfw#1313]
First of all, I'm not entirely sure if this is a problem with GLFW or with Windows 10. I run the technical preview, so I tend to believe this is behavior caused by changes with Windows.

Nonetheless, I've encountered a strange situation where the operating system's device disconnect/connect sounds are played (as if plugging in a USB device) when calling `glfwInit()`.

My testing shows that this is occurring for Windows 10 Pro 64-bit version 1803 and for GLFW pre-release 3.3.0 (as bundled through LWJGL 3.1.4).
As a sanity check, I also ran a test using Jogamp's NEWT APIs for window creation and this behavior was _NOT_ observed.
I determined that the behavior was connected to `glfwInit()` by using breakpoints before and after the call.

[For more information I've made a post on MSFT Windows Forum.](https://answers.microsoft.com/en-us/windows/forum/windows_tp-hardware/in-windows-10-device-connectdisconnect-sound-plays/cc79fbe9-1932-4916-8094-dfe75f5e5738?page=7&rtAction=1533783327939)

**Comment by elmindreda** [comment]
Cannot reproduce on Windows 10 version 1803 (non-preview).

GLFW registers for listening to device notifications on init and it's possible this is somehow triggering this effect on that preview version.

**Comment by Millerni456** [comment]
I updated the preview again to the latest version. It is now version 1803 build 17713.1002 (17713.rs5_release.180706-1551).
Problem is gone. Hopefully this issue helps someone else.

Thanks @elmindreda for testing on the non-preview.

**Comment by elmindreda** [comment]
@Millerni456 Thank you for the follow-up!
