### ISSUE TITLE
GLFW_INCLUDE_VULKAN ignored on OS X

### ISSUE THREAD

**Issue by decitrig** [glfw/glfw#1314]
I've been following https://vulkan-tutorial.com/ on OS X, and ran into an issue where `glfwCreateWindowSurface` was undeclared. I was able to confirm that GLFW wasn't including vulkan, even though I had defined `GLFW_INCLUDE_VULKAN`. I discovered that in the header for glfw 3.2.1, `GLFW_INCLUDE_VULKAN` is only checked if `__APPLE__` is not defined.

```
#if defined(__APPLE__)
#if defined(GLFW_INCLUDE_GLCOREARB)
#include <OpenGL/gl3.h>
#if defined(GLFW_INCLUDE_GLEXT)
#include <OpenGL/gl3ext.h>
#endif
#elif !defined(GLFW_INCLUDE_NONE)
#if !defined(GLFW_INCLUDE_GLEXT)
#define GL_GLEXT_LEGACY
#endif
#include <OpenGL/gl.h>
#endif
#if defined(GLFW_INCLUDE_GLU)
#include <OpenGL/glu.h>
#endif
#else  // __APPLE__ is not defined
#if defined(GLFW_INCLUDE_GLCOREARB)
#include <GL/glcorearb.h>
#elif defined(GLFW_INCLUDE_ES1)
#include <GLES/gl.h>
#if defined(GLFW_INCLUDE_GLEXT)
#include <GLES/glext.h>
#endif
#elif defined(GLFW_INCLUDE_ES2)
#include <GLES2/gl2.h>
#if defined(GLFW_INCLUDE_GLEXT)
#include <GLES2/gl2ext.h>
#endif
#elif defined(GLFW_INCLUDE_ES3)
#include <GLES3/gl3.h>
#if defined(GLFW_INCLUDE_GLEXT)
#include <GLES2/gl2ext.h>
#endif
#elif defined(GLFW_INCLUDE_ES31)
#include <GLES3/gl31.h>
#if defined(GLFW_INCLUDE_GLEXT)
#include <GLES2/gl2ext.h>
#endif
#elif defined(GLFW_INCLUDE_VULKAN)
#include <vulkan/vulkanblah.h>
#elif !defined(GLFW_INCLUDE_NONE)
#include <GL/gl.h>
#if defined(GLFW_INCLUDE_GLEXT)
#include <GL/glext.h>
#endif
#endif
#if defined(GLFW_INCLUDE_GLU)
#include <GL/glu.h>
#endif
#endif
```
Including `vulkan.h` before including GLFW fixes the issue, and it seems to work just fine. Is Vulkan unsupported on OS X with GLFW intentionally?

**Comment by intrigus** [comment]
Did you follow the tutorial by word?
If so, running `brew install glfw3 --HEAD` as described should give you the latest glfw version which should support vulkan on OS X :)

**Comment by decitrig** [comment]
ARGH. I had, but I did a bit of reorganizing of the project dependencies and that got lost. Building against HEAD fixed the issue, of course. Sorry for the noise!
