### ISSUE TITLE
Numpad equals key is unknown

### ISSUE THREAD

**Issue by Robertk92** [glfw/glfw#1315]
My numpad equals key reports "Unknown" when pressed (or released)
The scancode  89 (0x059) is not present in the windows init source code (according to dougbinks). 

Original issue post: [http://discourse.glfw.org/t/numpad-equals-not-working/1157/2](url)

**Comment by dougbinks** [comment]
As per the discourse issue, this should be a one line fix in win32_init.c, between lines 311-312.

_glfw.win32.keycodes[0x059] = GLFW_KEY_KP_EQUAL;

**Comment by dougbinks** [comment]
I am preparing a PR for this, though I don't have a keyboard with this key so can't test that it works.

**Comment by elmindreda** [comment]
This should be fixed now with ed12a54afd79d3f52ee633b8323fa129b6c59cfc.

Thank you @Robertk92 for reporting it and @dougbinks for the PR.

**Comment by Robertk92** [comment]
Hi thanks for the fix, I can confirm it is working (I do have this key)
