### ISSUE TITLE
glfwSwapBuffers with vsync=on takes more time than expected on El Capitan

### ISSUE THREAD

**Issue by ysmolsky** [glfw/glfw#1321]
GLFW version: 3.3.0 Cocoa NSGL

My monitor is 60Hz. When I set vsync to on via glfwSwapInterval(1) I expect that glfwSwapBuffers does not take more than 1/60 ~ .0166 (s). But it does consistently:
```
swap: 0.0175044
swap: 0.0150701
swap: 0.0158472
swap: 0.0176584
swap: 0.0159936
swap: 0.0159472
swap: 0.0171444
swap: 0.0168068
swap: 0.0164158
swap: 0.0162674
swap: 0.0171232
swap: 0.0155130
swap: 0.0159395
swap: 0.0171639
swap: 0.0154896
swap: 0.0163791
swap: 0.0178637
swap: 0.0144472
swap: 0.0163385
swap: 0.0162658
swap: 0.0160792
```

Reproduce:
```c
~/tmp % cat swapbuf.c
/* Ask for an OpenGL Core Context */
#define GLFW_INCLUDE_GLCOREARB
#include <stdio.h>
#include <GLFW/glfw3.h>

#define BUFFER_OFFSET(i) ((char *)NULL + (i))

int main(int argc, char** argv)
{
  GLFWwindow* window;

  /* Initialize the library */
  if ( !glfwInit() )
  {
     return -1;
  }

#ifdef __APPLE__
  /* We need to explicitly ask for a 3.2 context on OS X */
  glfwWindowHint (GLFW_CONTEXT_VERSION_MAJOR, 3);
  glfwWindowHint (GLFW_CONTEXT_VERSION_MINOR, 3);
  glfwWindowHint (GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
  glfwWindowHint (GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
#endif

  /* Create a windowed mode window and its OpenGL context */
  window = glfwCreateWindow( 1280, 720, "Hello World", NULL, NULL );
  if (!window)
  {
     glfwTerminate();
     return -1;
  }

  /* Make the window's context current */
  glfwMakeContextCurrent(window);

  /* Loop until the user closes the window */
  while (!glfwWindowShouldClose(window))
  {
    /* Render here */
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT); // Clear the buffers

    /* Swap front and back buffers */
    glfwSwapInterval(1);
    double seconds = glfwGetTime();
    glfwSwapBuffers(window);
    seconds = glfwGetTime() - seconds;
    printf("swap: %.7f\n", seconds);

    /* Poll for and process events */
    glfwPollEvents();

  }
  printf("%s\n", glfwGetVersionString());

  glfwTerminate();
  return 0;
}
~/tmp % cat swapbuf.c
~/tmp % clang++ -std=c++11 -stdlib=libc++ -lglfw3 -framework CoreVideo -framework OpenGL -framework IOKit -framework Cocoa -framework Carbon swapbuf.c
```

Not sure, maybe it's a problem of Apple drivers, who are know for their negligence regarding OpenGL.
 
I have never worked with profiling C++ code in Mac. Can someone suggest something so I can try to find out the reason myself. Thanks.

**Comment by tombsar** [comment]
NB you only need to call glfwSwapInterval once in setup code, not every loop. I don't think it has much cost, but you never know.

FWIW that amount of variation looks fairly normal to me; I remember seeing a similar spread on my Windows and Linux computers (albeit measuring a slightly different quantity). Note that the calls taking longer than 1/60 are matched by ones that take less, so on average you are still keeping up with the refresh rate. I've always put the difference down to the driver taking more or less time to return control to your program after the swap, so unless you can see missed frames, probably don't worry about it.

**Comment by ysmolsky** [comment]
Yes, you might be right here. I might be blaming the wrong library here. I will poke at it for next 24 hours and if I cannot reproduce this with pure GLFW, I will close the ticket.

 Actually I have been using Golang GLFW bindings via Pixel library and when I set Vsync to on I get constant overshooting by small fraction of a time. I cannot reproduce the scale of the problem on pure GLFW. But again it's Macbook pro with a fake GPU on two cored CPU. So external stuff might load the system and that produces long return times because Go has GC.

Anyway, I am sorry for the noise.

**Comment by tombsar** [comment]
No problem. Accurate frame scheduling is a real pain on general-purpose computers; even AAA titles get it wrong a lot of the time.
