### ISSUE TITLE
When setting up GLFW with Qt Creator,There is a problem

### ISSUE THREAD

**Issue by wrzfeijianshen** [glfw/glfw#1330]
When setting up GLFW with windows Qt Creator, set up the pure MinGW C++ console project, lib library lib-mingw (32-bit), there will be the following error, request support and solution, thank you all.
![image](https://user-images.githubusercontent.com/23181790/45794005-1f090a00-bcc7-11e8-97f2-033e29afe89b.png)
![image](https://user-images.githubusercontent.com/23181790/45791775-ae112480-bcbd-11e8-8515-59078b1d1e27.png)

**Comment by ghuser404** [comment]
Can you try this on master?

**Comment by wrzfeijianshen** [comment]
> Can you try this on master?

I will not compile GLFW with MinGW under Windows, please compile a MinGW library for me, or teach me how to compile, it is too stupid, vs is easy, MinGW is more difficult, thank you
![image](https://user-images.githubusercontent.com/23181790/45855738-1fb3a600-bd84-11e8-9f04-c0c033f4d7b7.png)

**Comment by ghuser404** [comment]
Use this guide to compile GLFW http://www.glfw.org/docs/3.3/compile_guide.html

**Comment by wrzfeijianshen** [comment]
> Use this guide to compile GLFW http://www.glfw.org/docs/3.3/compile_guide.html
> 
> Edit: you should be able to compile it without Vulkan. Also, I'm pretty sure you should be able to do what you're doing with 3.2.1 - you're probably doing something wrong.

thank you，I have compiled this master. I have studied how cmake is compiled, and found that it is possible to compile lib library by simply typing the command make in the figure above, without installing VulkanSDK and doxygen. Thank you very much

![18 09 22 1150_1](https://user-images.githubusercontent.com/23181790/45913026-c750d700-be5d-11e8-8b51-57cdc9d0b446.png)

**Comment by ghuser404** [comment]
Glad to help. If your problem is solved, please close this issue.
