### ISSUE TITLE
CMake 3.12.2: Cannot find glfw3Targets.cmake

### ISSUE THREAD

**Issue by Postski** [glfw/glfw#1331]
_Note_: ellipsis '...' were added by me manually to shorten the messages.

GLFW version 3.2.1 succeeds in building, but attempts to link to the built libraries using the `find_package(... CONFIG ...)` mechanism from my test project fails with the following message:

```
CMake Error at C:/.../bin/glfw-3.2.1/src/glfw3Config.cmake:1 (include):
  include could not find load file:

    C:/.../bin/glfw-3.2.1/src/glfw3Targets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:24 (find_package)
```

Contents of `C:/.../bin/glfw-3.2.1/src/glfw3Config.cmake`:
```
include("${CMAKE_CURRENT_LIST_DIR}/glfw3Targets.cmake")
```

My CMakeLists.txt file:
```
# Include GLFW
find_package(glfw3
	3.2.1 EXACT
	REQUIRED
	CONFIG
	HINTS "C:/.../bin/glfw-3.2.1/src"
)

...

target_link_libraries(glfwtest
	PUBLIC
		glfw3
)
```

I have tested this exact CMakeLists.txt project format with SDL2-2.0.8 and SFML-2.5.0, and both work. The file(s) being looked for are infact present in the GLFW build directory, specifically in `C:/.../bin/glfw-3.2.1/CMakeFiles/Export/lib/cmake/glfw3`.

I've tried manually copying this file, in which case CMake successfully configures and generates, but complains about not being able to find "GLFW/glfw3.h".

**Comment by Postski** [comment]
Nevermind, I was mis-using CMake.

**Comment by sunkingac** [comment]
> Nevermind, I was mis-using CMake.

I am also facing the same issue. What is the problem u had in using the CMake?

**Comment by timhutton** [comment]
For the record, you need to build the ```install``` target too (the ```INSTALL``` project in Visual Studio) and then use the installed location (for me, ```C:/Program Files (x86)/GLFW/lib/cmake/glfw3```) as the ```glfw3_DIR``` in other projects.
