### ISSUE TITLE
GLFW 3.2 crashed on macOS 10.14

### ISSUE THREAD

**Issue by woc2006** [glfw/glfw#1333]
![image](https://user-images.githubusercontent.com/1716430/46027451-71f81c80-c120-11e8-97b9-261fc7fc3bc4.png)

*** Assertion failure in -[GLFWContentView _createLayerAndInitialize], /BuildRoot/Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1671/AppKit.subproj/NSView.m:17221

Please tell me if you need any more information.

**Comment by elmindreda** [comment]
It would be useful to see the whole warning that's cut off on the right side.

The full call stack of the error would also be very useful, and whether it occurred on the main thread or another thread.

**Comment by elmindreda** [comment]
Please see if the `mjoave-fixes` branch resolves this for you.

**Comment by Kangz** [comment]
We had a [similar issue](https://bugs.chromium.org/p/dawn/issues/detail?id=35) in Dawn and it was fixed by rolling to the latest GLFW version.

**Comment by FelikZ** [comment]
@Kangz do you mean `master`? Since last release was a while ago.

**Comment by Kangz** [comment]
Yes I meant `master` and more precisely 2de2589f910b1a85905f425be4d32f33cec092df which was the top of tree a couple days ago.

**Comment by Alzathar** [comment]
Works perfectly using 53c8c72c676ca97c10aedfe3d0eb4271c5b23dba. The dev machine uses Xcode 9.2 (under macOS 10.12.6). The test machine is under macOS 10.14.1.

**Comment by FelikZ** [comment]
@Kangz I confirm that current master branch fixes an issue for me. Thank you!
