### ISSUE TITLE
Vsync doesn't work on macOS 10.14 (Mojave)

### ISSUE THREAD

**Issue by hajimehoshi** [glfw/glfw#1337]
I checked example `boing` (built as `boing.app`) and it didn't sync with display refresh rate even with `glfwSwapInterval(1)` and `glfwSwapBuffer`. I'm not sure whether it worked on 10.13, but I think so.

**Comment by ghuser404** [comment]
It may depend on whether your GPU driver is forcing this.

**Comment by hajimehoshi** [comment]
Hi, I'm using MacBook Pro 2018, and I think vsync is enforced.

**Comment by hajimehoshi** [comment]
My graphics card info

```
Intel Iris Plus Graphics 655:

  Chipset Model:	Intel Iris Plus Graphics 655
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel
  Device ID:	0x3ea5
  Revision ID:	0x0001
  Metal:	Supported, feature set macOS GPUFamily2 v1
  Displays:
Color LCD:
  Display Type:	Built-In Retina LCD
  Resolution:	2560 x 1600 Retina
  Framebuffer Depth:	24-Bit Color (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
  Automatically Adjust Brightness:	No
```

**Comment by ghuser404** [comment]
I don't know much about macOS, but in Windows you can enforce vsync on/off, so that the GLFW setting won't do anything.

**Comment by kivutar** [comment]
I can confirm this is a regression due to 10.14. On the previous version of OSX, vsync used to work.

**Comment by mokafolio** [comment]
Can confirm. This is new on mojave and does only happen when using my dedicated GPU, not the integrated one.

**Comment by gimblll** [comment]
Still broken with the 10.14.2 update. Anyone have any workarounds?

**Comment by gimblll** [comment]
Answering myself: the workaround I got working now was compiling with XCode 9 instead of 10. Seems SDL has come to the same conclusion https://discourse.libsdl.org/t/sdl2-no-renderer-vsync-on-macos-mojave/25169/21

**Comment by rcgordon** [comment]
Heads up, I just got a solution into SDL for this problem, if you want to adapt it for GLFW:

https://hg.libsdl.org/SDL/rev/73f3ca85ac0e

**Comment by gerryhernandez** [comment]
Great work, and you saved my bacon. Thank you!

**Comment by amarcu5** [comment]
Good news, I adapted @rcgordon's fix for GLFW

See pull request #1417

**Comment by Bilalmirza** [comment]
will this be included in 3.3? and when will 3.3 release?

**Comment by elmindreda** [comment]
@rcgordon Thank you again! Perhaps 8d7e5cdb49a1a5247df612157ecffdd8e68923d2 can be useful in return, for updating the display link as the window moves between monitors with different refresh rates. Couldn't find any reference to this in your HEAD or Bugzilla.

**Comment by rcgordon** [comment]
> Perhaps 8d7e5cd can be useful in return

Thanks, @elmindreda, I'll take a look!

Also: I haven't confirmed personally, but someone on Twitter told me that the broken vsync support is _fixed_ in the 10.14.2 beta releases, against expectations. If this is true, we'll all have to decide if we want the CVDisplayLink code at all, as it adds a little complexity to the codebase and is only necessary for people on 10.14.0 and .1, all of whom will be able to do a free update to .2.

**Comment by dmitshur** [comment]
> someone on Twitter told me that the broken vsync support is *fixed* in the 10.14.2 beta releases, against expectations

I'm on 10.14.3 (18D109), the latest public release, and the vsync issue is not resolved in it when using the latest stable GLFW. Is there any chance they were referring to 10.14.4 betas, since 10.14.4 is likely to be released publicly in a week or so?

**Comment by rcgordon** [comment]
Yes, sorry, I had the wrong number; it’s whatever the current beta is.

**Comment by elmindreda** [comment]
> If this is true, we'll all have to decide if we want the CVDisplayLink code at all, as it adds a little complexity to the codebase and is only necessary for people on [10.14.0 to 10.14.3]

@rcgordon Yeah, I'm hoping the update will drop before our next release so this can be verified. It's nice that CVDisplayLink also solves the issue of vsync being silently disabled for miniaturized windows, but as you say it adds complexity and it also behaves poorly (very obvious tearing) on an older system (2008 MacBook, 10.10.5).

**Comment by dmitshur** [comment]
macOS 10.14.4 has been released today, and I can confirm that vsync has started working with GLFW v3.2.1, as @rcgordon suggested in https://github.com/glfw/glfw/issues/1337#issuecomment-474954781.

**Comment by elmindreda** [comment]
Is everyone fine with shipping 3.3 with CVDisplayLink and re-evaluating this for a patch release?

**Comment by kivutar** [comment]
This issue might be back with Monterey

**Comment by dmitshur** [comment]
@kivutar I think so too. Since this issue was about Mojave specifically and has been fixed, could you please file a new issue to track the new problem with Monterey? Thanks.
