### ISSUE TITLE
CAMetalLayer not set despite call to glfwCreateWindowSurface

### ISSUE THREAD

**Issue by hecaex** [glfw/glfw#1340]
On macOS Mojave the surface creation failes with this error:
`[***MoltenVK ERROR***] VK_ERROR_INITIALIZATION_FAILED: On-screen rendering requires a view that is backed by a layer of type CAMetalLayer.`

The error happens when I call `glfwCreateWindowSurface()`

However my code works on macOS High Sierra, but not on Mojave.

Some information:
macOS 10.14 Mojave
MacBook 12" early 2016
GLFW: latest (master branch)
LunarG SDK: 1.1.82.1

**Comment by ByunghoonKim** [comment]
Is this a verified bug? I am currently postponing installing macOS 10.14 because of this thread.

If this is still an unresolved problem, could this be any relevant?
https://github.com/KhronosGroup/MoltenVK/issues/78

**Comment by elmindreda** [comment]
Cannot reproduce on macOS 10.14.1 with Vulkan SDK 1.1.92.1.

GLFW creates a CAMetalLayer for the view when `glfwCreateWindowSurface` is called and has done so since support for MoltenVK was added. It is possible we are clobbering this layer by accident for some call sequence. Do you have a test program that triggers this?

**Comment by hecaex** [comment]
I haven't tested this with the macOS 10.14.1 update and the current Vulkan SDK. I'll check it and report back.

**Comment by TheMasterMaind** [comment]
Hmm....the error about CAMetalLayer seems to be gone with the most recent master branch build of GLFW and the latest version of the VulkanSDK and Mojave.

Still `glfwCreateWindowSurface` returns error: `Vulkan: Loader not found`

Seems the way GLFW loads the Vulkan lib is different than we do it in our engine:

GLFW:

`#if defined(_GLFW_VULKAN_LIBRARY)
    _glfw.vk.handle = _glfw_dlopen(_GLFW_VULKAN_LIBRARY);
#elif defined(_GLFW_WIN32)
    _glfw.vk.handle = _glfw_dlopen("vulkan-1.dll");
#elif defined(_GLFW_COCOA)
    _glfw.vk.handle = _glfw_dlopen("libvulkan.1.dylib");
#else
    _glfw.vk.handle = _glfw_dlopen("libvulkan.so.1");
#endif`

VOLK Vulkan loader:

`void* module = dlopen("libvulkan.dylib", RTLD_NOW | RTLD_LOCAL);
	if (!module)
		module = dlopen("libvulkan.dylib.1", RTLD_NOW | RTLD_LOCAL);
	if (!module)
		module = dlopen("libMoltenVK.dylib", RTLD_NOW | RTLD_LOCAL);
	if (!module)
		return VK_ERROR_INITIALIZATION_FAILED;`

**Comment by hecaex** [comment]
I tested it today, the issue with the CAMetalLayer seems to be gone with 10.14.2. However we run into another issue:
`VK_ERROR_EXTENSION_NOT_PRESENT`
when calling `glfwCreateWindowSurface`.

I created a small test application for you to test, download link below.
[GLFWTest.zip](https://oc.cyphis.com/s/UoBRcY64k818a97)

**Comment by hecaex** [comment]
A call to `glfwGetError` returns nothing. But a call to `glfwCreateWindowSurface` returns `VK_ERROR_EXTENSION_NOT_PRESENT`.

**Comment by elmindreda** [comment]
That is very odd. Are you compiling GLFW with `MAC_OS_X_VERSION_MAX_ALLOWED` set to less than macOS 10.11?

**Comment by hecaex** [comment]
No I compile GLFW statically with macOS 10.14. The weird thing is, that on macOS 10.13 (High Sierra) everything worked (I updated some time ago to Mojave, recompiled alot of times and also used the 'old' binaries I compiled). Maybe I'm doing something totally wrong in my configuration and Mojave needs special configuration. The issue I opened before seem to be gone since 10.14.2. But now the next weird error happens. I could send you some Xcode project I created for testing (without any binaries, so you have to add GLFW, libvulkan.1.dylib and libMoltenVK.dylib from the VulkanSDK into the project root directory.) According to MoltenVK one have to add both libvulkan.dylib and libMoltenVK.dylib + the icd json file to the ressources directory of the app. I did this, but it seem to fail ONLY with Mojave and GLFW.

**Comment by ToxiCore** [comment]
I ran into the same using the newest VulkanSDK [1.1.92.1](
https://vulkan.lunarg.com/sdk/home#sdk/downloadConfirm/1.1.92.1/mac/vulkansdk-macos-1.1.92.1.tar.gz) and GLFW [master](
https://github.com/glfw/glfw/commit/cf0857f79aed5688d764d33dda11d3cee031a182).
However I apparently fixed it by adding the following line
`[window->ns.view setLayer:window->ns.layer];`
right before [`cocoa_window.m` : `[window->ns.view setWantsLayer:YES];`](https://github.com/glfw/glfw/blob/c90c7b97109db909577e3bf540b5f884422b7e14/src/cocoa_window.m#L1824).

Without this simple assignment, the layer was of type `_NSViewBackingLayer` as I figured out using
`NSLog(@"yourObject is a: %@", NSStringFromClass([window->ns.layer class]));`.

However I know almost nothing about Apple's API and therefore this may be just another hack..
Hope this helps anyways.

**Comment by hecaex** [comment]
> I ran into the same problems using VulkanSDK [1.1.92.1](https://vulkan.lunarg.com/sdk/home#sdk/downloadConfirm/1.1.92.1/mac/vulkansdk-macos-1.1.92.1.tar.gz) and GLFW [master](https://github.com/glfw/glfw/commit/cf0857f79aed5688d764d33dda11d3cee031a182).
> However I apparently fixed it by adding the following line
> `[window->ns.view setLayer:window->ns.layer];`
> right before [`cocoa_window.m` : `[window->ns.view setWantsLayer:YES];`](https://github.com/glfw/glfw/blob/c90c7b97109db909577e3bf540b5f884422b7e14/src/cocoa_window.m#L1824).
> 
> Without this simple assignment, the layer was of type `_NSViewBackingLayer` as I figured out using
> `NSLog(@"yourObject is a: %@", NSStringFromClass([window->ns.layer class]));`.
> 
> It seems that the surface ends up with the wrong dimensions this way :(
> I was able to fix that by removing (commenting out)
> `[window->ns.layer setContentsScale:[window->ns.object backingScaleFactor]];`
> which was added for #1229.
> 
> Furthermore I have to use VulkanSDK [1.1.73.0](https://vulkan.lunarg.com/sdk/home#sdk/downloadConfirm/1.1.73.0/mac/vulkansdk-macos-1.1.73.0.tar.gz) beacause `vkCreateSwapchainKHR` stopped working. (I did not test any releases between those two mentioned.) Probably doing something terribly wrong, but I have no Idea what…
> 
> Anyway this works for me and as I know almost nothing about Apple's API I'm happy about that..
> 
> PS: The MoltenVK code to check for `CAMetalLayer` can be found [here](https://github.com/KhronosGroup/MoltenVK/blob/5f661ea6d8fa055f0c1d7b8dd0e0ba3c4d73e543/MoltenVK/MoltenVK/GPUObjects/MVKSurface.mm#L42).

Indeed, this fix worked like a charm!
I was able to run my application with the mentioned code change in GLFW.

**Comment by TheMasterMaind** [comment]
Also note for loading GLFW dynamically. There is need to load the MoltenVK libs directly if there is no ICD json file. So GLFW should try to load the following files:

`libvulkan.dylib`
`libvulkan.dylib.1`
`libMoltenVK.dylib`

So dynamic applications can be shipped with and without the ICD json file.

Also interesting: https://github.com/zeux/volk/commit/08b64f38ac5a71cf7c53a17fe66ee4746c4859da

**Comment by ThomasL81** [comment]
> I ran into the same problems using VulkanSDK [1.1.92.1](https://vulkan.lunarg.com/sdk/home#sdk/downloadConfirm/1.1.92.1/mac/vulkansdk-macos-1.1.92.1.tar.gz) and GLFW [master](https://github.com/glfw/glfw/commit/cf0857f79aed5688d764d33dda11d3cee031a182).
> However I apparently fixed it by adding the following line
> `[window->ns.view setLayer:window->ns.layer];`
> right before [`cocoa_window.m` : `[window->ns.view setWantsLayer:YES];`](https://github.com/glfw/glfw/blob/c90c7b97109db909577e3bf540b5f884422b7e14/src/cocoa_window.m#L1824).
> 
> Without this simple assignment, the layer was of type `_NSViewBackingLayer` as I figured out using
> `NSLog(@"yourObject is a: %@", NSStringFromClass([window->ns.layer class]));`.
> 
> It seems that the surface ends up with the wrong dimensions this way :(
> I was able to fix that by removing (commenting out)
> `[window->ns.layer setContentsScale:[window->ns.object backingScaleFactor]];`
> which was added for #1229.
> 
> Furthermore I have to use VulkanSDK [1.1.73.0](https://vulkan.lunarg.com/sdk/home#sdk/downloadConfirm/1.1.73.0/mac/vulkansdk-macos-1.1.73.0.tar.gz) beacause `vkCreateSwapchainKHR` stopped working. (I did not test any releases between those two mentioned.) Probably doing something terribly wrong, but I have no Idea what…
> 
> Anyway this works for me and as I know almost nothing about Apple's API I'm happy about that..
> 
> PS: The MoltenVK code to check for `CAMetalLayer` can be found [here](https://github.com/KhronosGroup/MoltenVK/blob/5f661ea6d8fa055f0c1d7b8dd0e0ba3c4d73e543/MoltenVK/MoltenVK/GPUObjects/MVKSurface.mm#L42).

I can confirm this is also working for me.

Currently running:
- Vulkan 1.1.92.1 dynamically loaded
- GLFW latest master branch pull as submodule using CMake
- MacOS Mojave 10.14.2 on a Macbook Pro 15" 2017

**Comment by n8vm** [comment]
> I ran into the same problems using VulkanSDK [1.1.92.1](https://vulkan.lunarg.com/sdk/home#sdk/downloadConfirm/1.1.92.1/mac/vulkansdk-macos-1.1.92.1.tar.gz) and GLFW [master](https://github.com/glfw/glfw/commit/cf0857f79aed5688d764d33dda11d3cee031a182).
> However I apparently fixed it by adding the following line
> `[window->ns.view setLayer:window->ns.layer];`
> right before [`cocoa_window.m` : `[window->ns.view setWantsLayer:YES];`](https://github.com/glfw/glfw/blob/c90c7b97109db909577e3bf540b5f884422b7e14/src/cocoa_window.m#L1824).
> 
> Without this simple assignment, the layer was of type `_NSViewBackingLayer` as I figured out using
> `NSLog(@"yourObject is a: %@", NSStringFromClass([window->ns.layer class]));`.
> 
> It seems that the surface ends up with the wrong dimensions this way :(
> I was able to fix that by removing (commenting out)
> `[window->ns.layer setContentsScale:[window->ns.object backingScaleFactor]];`
> which was added for #1229.
> 
> Furthermore I have to use VulkanSDK [1.1.73.0](https://vulkan.lunarg.com/sdk/home#sdk/downloadConfirm/1.1.73.0/mac/vulkansdk-macos-1.1.73.0.tar.gz) beacause `vkCreateSwapchainKHR` stopped working. (I did not test any releases between those two mentioned.) Probably doing something terribly wrong, but I have no Idea what…
> 
> Anyway this works for me and as I know almost nothing about Apple's API I'm happy about that..
> 
> PS: The MoltenVK code to check for `CAMetalLayer` can be found [here](https://github.com/KhronosGroup/MoltenVK/blob/5f661ea6d8fa055f0c1d7b8dd0e0ba3c4d73e543/MoltenVK/MoltenVK/GPUObjects/MVKSurface.mm#L42).

This works for me too!

**Comment by elmindreda** [comment]
I believe this issue should be fixed now with e108c0de0d531123b560931c07c5a226e7d7a3da and so closed this issue for the 3.3 release, but please re-open or comment if that's not the case. I never managed to reproduce it but it is clearly a bug judging by the discussion above and I want it to be fixed.
