### ISSUE TITLE
SIGSEGV cursor.exe

### ISSUE THREAD

**Issue by sonoro1234** [glfw/glfw#1351]
Windows / with mingw-w64 for 32 bits. (Also tried MSVC 2017 Win64)
Debuging cursor.exe, empty.exe and some others (but no windows.exe) shows
with last master
```
Thread 1 (Thread 5476.0x1444):
#0  0x00000000 in ?? ()
#1  0x76a062fa in gapfnScSendMessage () from C:\Windows\syswow64\user32.dll
#2  0x001603aa in ?? ()
#3  0x76a06d3a in USER32!GetThreadDesktop () from C:\Windows\syswow64\user32.dll
#4  0x6beddb00 in disableCursor () at C:\luaGL\gitsources\LuaJIT-GLFW\GLFW\src\win32_window.c:295
#5  0x76a06de8 in USER32!GetThreadDesktop () from C:\Windows\syswow64\user32.dll
#6  0x00000000 in ?? ()
(gdb)
```

It seems to appear for the first time running events.exe (or cursor.exe trying to move the window) in
https://github.com/glfw/glfw/commit/5294439595e5b95c238a121c8a63c076a0aa2c8a

with cursor.exe and empty.exe

>Thread 1 (Thread 3384.0x102c):
#0  0x00000000 in ?? ()
#1  0x75ed62fa in gapfnScSendMessage () from C:\Windows\syswow64\user32.dll
#2  0x000304a6 in ?? ()
#3  0x75ed6d3a in USER32!GetThreadDesktop () from C:\Windows\syswow64\user32.dll
#4  0x723ee8f1 in releaseMonitor (window=0x24)
    at C:\luaGL\gitsources\LuaJIT-GLFW\GLFW\src\win32_window.c:565
#5  0x000304a6 in ?? ()
#6  0x75ee0d3f in USER32!GetClientRect () from C:\Windows\syswow64\user32.dll
#7  0x00000000 in ?? ()

In the first dump we see  disableCursor in the second releaseMonitor so may be that there is a second bug in commits afterwards

**Comment by sonoro1234** [comment]
compiling with https://github.com/glfw/glfw/commit/2de2589f910b1a85905f425be4d32f33cec092df
error seems gone!!

**Comment by elmindreda** [comment]
Glad it was resolved! Is it okay to close this issue?

**Comment by sonoro1234** [comment]
Yes thanks
