### ISSUE TITLE
glfwSetWindowMonitor fails to change EWMH state for hidden windows

### ISSUE THREAD

**Issue by JudicaelCLAIR** [glfw/glfw#1358]
glfwSetWindowMonitor when window is hidden will cause it to be shown, resizable and with previous window settings. The window is not set fullscreen.

**Comment by elmindreda** [comment]
Which version of GLFW are you using?

**Comment by JudicaelCLAIR** [comment]
Sorry for the late reply, only just saw. I'm using version 3.2.1 (latest one I believe)

**Comment by JudicaelCLAIR** [comment]
I only get this bug when the window is by default set to hidden `glfwWindowHint(GLFW_VISIBLE, GLFW_FALSE);`. Note also that the bug is persistent, i.e. not just for the period between initialisation and first show, it continues occurring whenever I hide it again and attempt to set it fullscreen.

**Comment by elmindreda** [comment]
Which window manager are you using?

**Comment by elmindreda** [comment]
Reproduced successfully on MATE 1.20.

**Comment by JudicaelCLAIR** [comment]
I'm currently running on GNOME Shell but I've seen the bug persist on various other managers

**Comment by elmindreda** [comment]
The problem is the code that switches to EWMH full screen wasn't updated to take into account that the window may not be mapped. Will fix. Thank you!

**Comment by elmindreda** [comment]
This should be fixed now with 78e6a0063d27ed44c2c4805606309744f6fb29fc. Thank you!
