### ISSUE TITLE
Cocoa event processing is tied to the main thread

### ISSUE THREAD

**Issue by qimmer** [glfw/glfw#136]
I have an application running on Windows, Linux and Mac OS X 10.8. All GLFW commands are issued on a separate thread. On WIndows and Linux, everything runs fine. But on Mac OS X, GLFW doesn't process Cocoa events properly. It only works when GLFW commands are issued on the main app thread.

Everything renders as it should, but no events are received in the NSEvent/NSApp code and the window title is pure white (no close buttons, title text etc.).

**Comment by naphipps** [comment]
My repo [NP-Engine](https://github.com/naphipps/NP-Engine) tackles this by having my events dispatched in my [Application object](https://github.com/naphipps/NP-Engine/blob/master/include/NP-Engine/Application/Application.hpp). (Which stays on the main thread.) And when my [AppleWindow objects](https://github.com/naphipps/NP-Engine/blob/master/include/NP-Engine/Platform/Apple/Application/AppleWindow.hpp)(this link is liable to change) need a native window, they submit a WindowSpawnNativeWindowEvent. So, when that event gets dispatched by the Application, it is on the main thread, and creates the native window. Then my Window object can continue doing whatever. (Note the ShowProcedure method.)

Warning: The repo is a work in progress, and will be constantly under construction. But it's at a somewhat stable point as for right now. At the very least, I think it's good enough for just a code example. (Please note that I'm using [cameron314' concurrentqueue](https://github.com/naphipps/concurrentqueue/tree/8b468a2b14ad89cd8ab766037c325af085a312b9) to arrange my events, so I recommend something similar if not it.)
