### ISSUE TITLE
multiple monitor application, unplug will cause disorder

### ISSUE THREAD

**Issue by ngwd** [glfw/glfw#1365]
we have an application on linux, using glfw3.+ to display a window, the window sitting across 3 monitors, 0  1 and 2. in the box, monitor 0 always the primary monitors 
so we use glfwGetMonitors when application starts, 3 instances initialized, each will bind with the glfwMonitor structure. The window is rendering by looping through the 3 instances, the application works fine. but there are 2 issues beyond our understanding
1, but when you unplug monitor 1, the part of window showing on monitor 1 will creep on monitor 0. 
unplug monitor 2 will see the same scenario.  
2. plugging in the monitor back, the monitor 1 or 2 will not recover. 

but for monitor 0, unplug it will cause no video disorder, and it will restore after unplug back.
is there any one can help to give some hint on how to cure issue 1, and 2.

**Comment by elmindreda** [comment]
This may be due to window position adjustments by the window manager. Try recalculating and reapplying the window placement whenever you detect a monitor being connected or disconnected. Set a monitor callback to be notified of this.

**Comment by ngwd** [comment]
@elmindreda,
By using the glfwSetWindowPos in Monitor Callback, problem solved, Thanks a lot of

**Comment by elmindreda** [comment]
That's great to hear and thank you for the follow-up!
