### ISSUE TITLE
GLFW source build issue with Visual Studio 2017 fails

### ISSUE THREAD

**Issue by sajusathyan** [glfw/glfw#1370]
When trying to build the GLFW source using cmake in Visual Studio 2017, I ran into the following error:

`glfw\src\internal.h(49): fatal error C1083: Cannot open include file: '../include/GLFW/glfw3.h': No such file or directory `

I renamed the folder GLFW to glfw and modified internal.h 
from
`#include "../include/GLFW/glfw3.h"`
to
`#include "../include/glfw/glfw3.h"`
and this resolved the issue.

This is related to 
https://developercommunity.visualstudio.com/content/problem/287514/clexe-cant-find-files-in-casesensitive-folders.html

Adding following to src/CMakeLists.txt also solved the problem.
`target_compile_options(glfw PRIVATE
                       "$<$<C_COMPILER_ID:MSVC>:/d1scalableinclude->")`

**Comment by tombsar** [comment]
Do you recall how you obtained the glfw source code when you ran into this? I just tried using Github's repository .zip download and it compiles with no problems on my PC (Windows 10, CMake + Visual Studio Community 2017). The issue you linked suggests this is a bug in MSVC triggered by the way a certain git client creates directories, but it would be good to get some confirmation.

**Comment by sajusathyan** [comment]
I have been using the git client on the ubuntu 18.04 shell for windows 10! I too couldn't reproduce the issue when I downloaded the .zip file and compiled. It does look to be a problem with the MSVC when using git on linux shell on windows.

**Comment by tombsar** [comment]
Thanks for the quick followup. I don't know enough about CMake, but is the `d1scalableinclude-` addition something we should consider to make people's lives easier?

**Comment by sajusathyan** [comment]
It seems this issue is seen by developers who use the Linux shell on Windows 10, and the workaround proposed by Microsoft is to use the d1scalableinclude- switch, see here: https://developercommunity.visualstudio.com/content/problem/276297/clexe-breaks-with-case-sensitive-paths.html
