### ISSUE TITLE
glfwInit hangs

### ISSUE THREAD

**Issue by osozero** [glfw/glfw#1392]
When i try to call glfwInit function with glfw x86 version 3.2.1 library on Windows 10 intel graphics, it hangs on _glfwInitJoysticksWin32 call. When i replace glfw version from 3.2.1 to 3.1.2 it solves.

**Comment by tombsar** [comment]
Are you able to test with latest master? There have been lots of changes in the upcoming 3.3 release, and this issue might have already been fixed.

**Comment by osozero** [comment]
I have just tested with latest master and it works. it seems resolved 👍
