### ISSUE TITLE
GLFWContentView as the first responder for window error in macOS Mojave

### ISSUE THREAD

**Issue by dhhyuk** [glfw/glfw#1393]
OS and version: OSX 10.14 mojave
Compiler version: Apple Clang (Xcode)
Release or commit: 3.2.1
Build log: 

> 2018-11-29 17:03:05.684892+0900 Hello OpenGL Study[46633:1176448] [General] ERROR: Setting <GLFWContentView: 0x10283a620> as the first responder for window <GLFWWindow: 0x1007396e0>, but it is in a different window ((null))! This would eventually crash when the view is freed. The first responder will be set to nil.
(
	0   AppKit                              0x00007fff34690547 -[NSWindow _validateFirstResponder:] + 530
	1   AppKit                              0x00007fff346902f1 -[NSWindow _setFirstResponder:] + 31
	2   AppKit                              0x00007fff34762b40 -[NSWindow _realMakeFirstResponder:] + 448
	3   libglfw.3.dylib                     0x00000001003d2895 _glfwPlatformCreateWindow + 631
	4   libglfw.3.dylib                     0x00000001003ce430 glfwCreateWindow + 487
	5   Hello OpenGL Study                  0x0000000100000e9b main + 75
	6   libdyld.dylib                       0x00007fff64154085 start + 1
	7   ???                                 0x0000000000000001 0x0 + 1
)
2018-11-29 17:03:05.905921+0900 Hello OpenGL Study[46633:1176629] MessageTracer: load_domain_whitelist_search_tree:73: Search tree file's format version number (0) is not supported
2018-11-29 17:03:05.906275+0900 Hello OpenGL Study[46633:1176629] MessageTracer: Falling back to default whitelist
Program ended with exit code: 0

And my code is 
`
#include <iostream>

// GLEW
#define GLEW_STATIC
#include <GL/glew.h>

// GLFW
#include <GLFW/glfw3.h>

// Window dimensions
const GLint WIDTH = 800, HEIGHT = 600;

// The MAIN function, from here we start the application and run the game loop
int main( )
{
    // Init GLFW
    glfwInit( );
 
    // Set all the required options for GLFW
    glfwWindowHint( GLFW_CONTEXT_VERSION_MAJOR, 3 );
    glfwWindowHint( GLFW_CONTEXT_VERSION_MINOR, 3 );
    glfwWindowHint( GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE );
    glfwWindowHint( GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE );
    glfwWindowHint( GLFW_RESIZABLE, GL_FALSE );
    
    std::cout << glfwGetVersionString() << std::endl;
    
    // Create a GLFWwindow object that we can use for GLFW's functions
    GLFWwindow *window = glfwCreateWindow( WIDTH, HEIGHT, "LearnOpenGL", nullptr, nullptr );
    
    int screenWidth, screenHeight;
    glfwGetFramebufferSize( window, &screenWidth, &screenHeight );
    
    if ( nullptr == window )
    {
        std::cout << "Failed to create GLFW window" << std::endl;
        glfwTerminate( );
        
        return EXIT_FAILURE;
    }
    
    glfwMakeContextCurrent( window );
    
    // Set this to true so GLEW knows to use a modern approach to retrieving function pointers and extensions
    glewExperimental = GL_TRUE;
    // Initialize GLEW to setup the OpenGL Function pointers
    if ( GLEW_OK != glewInit( ) )
    {
        std::cout << "Failed to initialize GLEW" << std::endl;
        return EXIT_FAILURE;
    }
    
    // Define the viewport dimensions
    glViewport( 0, 0, screenWidth, screenHeight );
    
    // Game loop
    while ( !glfwWindowShouldClose( window ) )
    {
        // Check if any events have been activiated (key pressed, mouse moved etc.) and call corresponding response functions
        glfwPollEvents( );
        
        // Render
        // Clear the colorbuffer
        glClearColor( 0.2f, 0.3f, 0.3f, 1.0f );
        glClear( GL_COLOR_BUFFER_BIT );
        
        // Swap the screen buffers
        glfwSwapBuffers( window );
    }
    
    // Terminate GLFW, clearing any resources allocated by GLFW.
    glfwTerminate( );
    
    return EXIT_SUCCESS;
}

`

this sample code show blank color( 0.2f, 0.3f, 0.3f, 1.0f ) window.

but first display is black window and,
color( 0.2f, 0.3f, 0.3f, 1.0f ) is displayed after change window position.

and if change window position, this program use cpu 60~70%

**Comment by tombsar** [comment]
Could you try again with the latest master from GitHub? There have been several Mojave-specific fixes merged recently.

**Comment by dhhyuk** [comment]
@tombsar 

Is code from 'brew install' and 'github' different?

**Comment by tombsar** [comment]
brew will give you the latest stable release (3.2.1), but the current development version here on GitHub is 3.3. You will need to update glfw if you want to work on Mojave right now, as it might be some time until the new version is released.

I'm afraid I can't help with instructions for compiling/installing on macOS, but I'm sure someone else here will be happy to answer any questions you have.

**Comment by dhhyuk** [comment]
@tombsar Thank you for helping me. i will try it

**Comment by elmindreda** [comment]
This was reported and fixed in #876.

**Comment by MacintoshPlusPlus** [comment]
i have the same problem i think...
it says this:

2019-11-06 11:18:20.291451+0100 GLSL_test[1612:81962] MessageTracer: load_domain_whitelist_search_tree:73: Search tree file's format version number (0) is not supported
2019-11-06 11:18:20.291491+0100 GLSL_test[1612:81962] MessageTracer: Falling back to default whitelist

so how do i fix that??

**Comment by elmindreda** [comment]
@MacintoshPlusPlus What version of GLFW are you using?

**Comment by MacintoshPlusPlus** [comment]
hey!
3.3 is installed, said brew

**Comment by elmindreda** [comment]
@MacintoshPlusPlus In that case, please open a new issue for this problem.
