### ISSUE TITLE
How does glfw include/use vulkan?

### ISSUE THREAD

**Issue by gabrielevierti** [glfw/glfw#1399]
Hi everyone! I am currently working on a glfw-type library called [VKFW](https://github.com/gabrielevierti/VKFW), that is supposed to work very much like glfw, but only with support for Vulkan.   
It is a mistery how glfw handles the whole Vulkan thing:
- How does it include the required header file "vulkan.h" in "C:\VulkanSDK\VERSION\Include\vulkan\vulkan.h"? 
- How does it find and link the "vulkan-1.lib" static library?
- How do you define Vulkan-specific types like "VkResult"?

I am sorry if my question is out of scope, but I really cannot understand how you did these things in glfw..

**Comment by TheMasterMaind** [comment]
First of all GLFW uses the CMAKE function `find_package(vulkan)` (https://cmake.org/cmake/help/v3.7/module/FindVulkan.html) to properly find the installed Vulkan SDK. If this function is able to properly find the Vulkan SDK installed, the include path is updated to include the exact location of the header files.
So GLFW can include `vulkan/vulkan.h` to have all function prototypes and types declared.

The exact same way is done for the static Vulkan library

You can check the `CMakeLists.txt` on how GLFW do this all.

I hope I could answer your question to your satisfaction.

**Comment by gabrielevierti** [comment]
Thank you very much!
