### ISSUE TITLE
WM_CLASS window property not set

### ISSUE THREAD

**Issue by raedwulf** [glfw/glfw#140]
I'm using a window manager (bspwm) that makes use of WM_CLASS property to match windows and execute rules.  It isn't crucial for operation but it would nice if glfw sets the WM_CLASS and I believe it should?  I'm not entirely sure what it should be set to, but I suspect the window title should be fine.

http://tronche.com/gui/x/icccm/sec-4.html#WM_CLASS

**Comment by kovidgoyal** [comment]
I'd like a small enhancement to this hack. Currently both parts of the WM_CLASS are set to the title. Instead, could the title be split on the \x31 character (ASCII record separator) so that the name and class parts of WM_CLASS can be set separately? Thanks.

**Comment by elmindreda** [comment]
@kovidgoyal Please open a new issue. Posts to already closed issues are very likely to get lost.
