### ISSUE TITLE
Why STATUS_ACCESS_VIOLATION ?

### ISSUE THREAD

**Issue by dution89630** [glfw/glfw#1405]
I compiled glfw in win7, compiler is mysys2, but I get many STATUS_ACCESS_VIOLATION  error when executing all test and example. Do I have something wrong in compiling this library?

Exception: STATUS_ACCESS_VIOLATION at eip=69576C67
eax=69576C67 ebx=0028CC5C ecx=00000045 edx=00417E1E esi=80051A24 edi=0028CC70
ebp=0028CAD4 esp=0028CAC0 program=D:\glfw\build\tests\joysticks.exe, pid 5220, thread main
cs=0023 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame     Function  Args
0028CAD4  69576C67 (00417E1E, 80051DEC, 80051DF0, FFFDDB68)
0028CB38  00405620 (0028CB7C, 0028CB54, 0028CB7C, 0028CBA8)
0028CBF8  004091E6 (00000280, 000001E0, 00415095, 00000000)
0028CC38  0040172F (00000001, 0028CC5C, 800280F0, 61009E40)
0028CD28  61009EA2 (00000000, 0028CD84, 61008DC0, 00000000)
End of stack trace

**Comment by TheMasterMaind** [comment]
Do you use the latest code from the website or the latest master branch?

I am using `gcc version 8.2.1 20181214 (Rev1, Built by MSYS2 project)` via `MSYS2` and with Windows 10 (10.0.17763.195) I have no trouble executing the test or example programs.

Are you using any special CMAKE options? Which CMAKE version? Do you compile GLFW as static lib or DLL? Could you provide a test binary? 

Thanks in advance!

**Comment by TheMasterMaind** [comment]
I currently have no Windows 7 at hand but will try to find one!

In the meantime could you try to use gdb to find the exact spot where your binary crashes?

Like:
In cmd: `gdb .\binary.exe`
In gdb: `run`
And after the crash: `bt`

Thanks!

**Comment by tombsar** [comment]
Hi @dution89630, is this still a problem for you? If so, I can try to reproduce on a Windows 7 PC in the coming days.
