### ISSUE TITLE
Access violation when creating new window after GLFW re-initialization

### ISSUE THREAD

**Issue by nealkruis** [glfw/glfw#1410]
I am hitting up against an access violation on [this line](https://github.com/glfw/glfw/blob/3.2.1/src/wgl_context.c#L621) after updating my virtual machine software and drivers (I don't know if this is a GLFW, VMWare, or Mesa issue). I'm getting an access violation:

> Exception thrown at 0x687D2500 in test.exe: 0xC0000005: Access violation executing location 0x687D2500.

The actual violation is happening in a DLL called "vm3dgl.dll", which I assume is a VMWare implementation.

Below is the minimal code I need to reproduce the issue.

```
int main(void)
{
	{
		glfwInit();
		GLFWwindow* window;
		window = glfwCreateWindow(1, 1, "Test", NULL, NULL);
		glfwTerminate();
	}
	{
		glfwInit();
		GLFWwindow* window;
		window = glfwCreateWindow(1, 1, "Test", NULL, NULL);  // Fails in here!
		glfwTerminate();
	}
	return 0;
}
```

My understanding was that you could terminate GLFW as long as you re-initialize before using it again. However, moving to a single `glfwInit()` and `glfwTerminate()` seems to make the problem go away. Is it possible `glfwTerminate()` isn't cleaning up everything it needs to?

OS: Windows 10 Pro N (VMWare Fusion 11 virtual machine)

![screen shot 2018-12-28 at 10 07 47 am](https://user-images.githubusercontent.com/1964570/50522518-8e418780-0a88-11e9-8a21-469c914086f4.png)

Host OS: Mac OSX 10.4 (Mojave)

**Comment by nealkruis** [comment]
As mentioned in the report, the access violation happens somewhere within "vm3dgl.dll". The debugger does not have access to symbols in this library. The last location the debugger has information for is [this line](https://github.com/glfw/glfw/blob/3.2.1/src/wgl_context.c#L621).

It is entirely possible that:

- this is a VMWare issue (I'll make them aware of this issue), or
- this has been fixed since 3.2.1 (I'll test with a build from master)

**Comment by nealkruis** [comment]
Confirmed that the problem still exists on the master branch.

**Comment by nealkruis** [comment]
Thread on VMWare forums for context: https://communities.vmware.com/message/2826741#2826741

**Comment by elmindreda** [comment]
Is this still an issue with current GLFW on current VMWare?

**Comment by nealkruis** [comment]
@elmindreda, I'll check again and get back to you!

**Comment by elmindreda** [comment]
Thank you so much!

**Comment by nealkruis** [comment]
This does not appear to be an issue anymore with GLFW 3.3.6 on VMWare Fusion 12.2.3.

**Comment by elmindreda** [comment]
Yay! Thank you again!
