### ISSUE TITLE
glfwDestroyWindow leaves stuck window behind unless glfwPollEvents is called

### ISSUE THREAD

**Issue by fjl** [glfw/glfw#1412]
This might be a misunderstanding about the API on my side. Running the following program on macOS 10.14.2 Mojave leaves the window behind after clicking the red X button (but "window closed" is printed to stdout). The stuck window can be dragged around but not otherwise interacted with.

```c
#include <stdio.h>
#include <unistd.h>
#include <GLFW/glfw3.h>

int main() {
        glfwInit();
        GLFWwindow* win = glfwCreateWindow(400, 400, "Window", NULL, NULL);
        while (!glfwWindowShouldClose(win)) {
                glfwPollEvents();
        }
        glfwDestroyWindow(win);
        printf("window closed\n");
        
        // glfwPollEvents();
        
        sleep(100);
        glfwTerminate();
}
```

Removing the window works when uncommenting the call to `glfwPollEvents`.
This is similar to #1300.

**Comment by TheMasterMaind** [comment]
Normally any well defined GLFW application needs to call `glfwTerminate()` upon exit. But as someone might to close and reopen a window - i guess - this behaviour is not desired.

Can any other macOS user confirm this?

**Comment by fjl** [comment]
@TheMasterMaind I've added `glfwTerminate` call to the example, but note the issue isn't about that. I think the window should be gone after calling `glfwDestroyWindow`, but it's not.

**Comment by timtelcik** [comment]
Yes, I am observing the same hanging window issue with Mac OS 10.14.5 and GLFW 3.3.

**Comment by rsrock** [comment]
I can also confirm, at least using the Julia bindings referenced above. Adding an explicit `glfwTerminate` call had no effect, but adding an extra `glfwPollEvents` call after the `glfwDestroyWindow` closed the window as expected.

**Comment by elmindreda** [comment]
This should be fixed now with the hack introduced by c819f27ce3e6639b4d4b432c0e5191e5c26a9d31. Thank you for the bug report!

**Comment by dcabecinhas** [comment]
This issue is only partially fixed. A window artefact remains in the macOS dock and a [hung process shows in the Activity Monitor.app](https://github.com/JuliaPlots/Makie.jl/issues/393#issuecomment-643614690) until the main program exists.

The call to `GLFW.Terminate()` should finalize all GLFW code and windows but that is not happening. The Makie linked issues are precisely because people close the GLFW window, the window disappears from the screen but remain in the dock and as a hung process until the `julia` process exits. 

Having to exit `julia` to completely finish GLFW is especially troublesome as it clears JIT compiled code and is generally avoided.

System version information:
```
GLFW version: 3.3.2 Cocoa NSGL EGL OSMesa dynamic
macOS 10.15.6
```

To reproduce:
```C
#include <stdio.h>
#include <unistd.h>
#include <GLFW/glfw3.h>

int main() {
        glfwInit();
        GLFWwindow* win = glfwCreateWindow(400, 400, "Window", NULL, NULL);
        while (!glfwWindowShouldClose(win)) {
                glfwPollEvents();
        }
        glfwDestroyWindow(win);
        printf("window closed\n");

        glfwTerminate();

        printf("After glfwTerminate()\n");
        sleep(20);
}
```
Notice that a dock icon and a hung process still remain even after `After glfwTerminate()` is printed to the screen. Further calls to `glfwPollEvents()` after `glfwTerminate()` have no effect.

**Comment by elmindreda** [comment]
@dcabecinhas Noted. I will see what can be done about this. The process doing this is unbundled?

**Comment by dcabecinhas** [comment]
@elmindreda Thanks for looking into it.

I'm not sure what you mean by "unbundled process". I can notice the behavior by running the simple C program I posted from the command line.

What happens: Running the above C code from the command line spawns a window with an associated icon on the dock. However, when the window is closed, the icon remains active on the dock (and visible as "not responding" on the Activity Manager.app) until the `sleep(20)` is over.

What I expected: When `glfwTerminate()` is executed all GLFW window related artifacts and processes should be gone, even if the C program has not terminated yet.

In the context of a long running process that spawns a GLFW window from time to time, having window artifacts remain after `glfwTerminate()` is confusing for users.

**Comment by jkrumbiegel** [comment]
thanks @dcabecinhas for showing that this issue persists with a simple C example. That means I can stop looking for problems in Makie I assume

**Comment by jkrumbiegel** [comment]
Have you found anything that could cause this, yet? Maybe we can also reopen the issue so it doesn't get lost

**Comment by elmindreda** [comment]
The issue @dcabecinhas describes is related but not the same. Please open a new issue in that case instead of reopening this one.

**Comment by doug-moen** [comment]
Even though this bug is closed and marked as fixed in release 3.3.1, I am reproducing the bug in release 3.3.2 and in HEAD. (I am running macOS 10.14.6.) In other words, the bug is not fixed. Adding glfwPollEvents() after the call to glfwDestroyWindow(w) resolves the issue for me.

**Comment by finchco** [comment]
I'm having this same issue and the workaround of adding an extra call to glfwPollEvents() is not working for me. Version 3.3.3 installed via homebrew.

**Comment by cafaxo** [comment]
Same issue here with Version 3.3.3 on macOS 12.3.
The issue does not occur if I put a `sleep` before `glfwDestroyWindow`.
