### ISSUE TITLE
Gamepad documentation missing in docs/latest/input_guide

### ISSUE THREAD

**Issue by DesertCookie** [glfw/glfw#1421]
The page for input that is linked to in the code documentation (LWJGL javadocs - I guess it's taken from your C docs?...) is missing the gamepad section linked to with `https://.../input_guide.html#gamepad`.
While `https://www.glfw.org/docs/latest/input_guide.html` doesn't have it, `https://www.glfw.org/docs/3.3/input_guide.html` has it.
Not game breaking but annoying, since the page for the _latest_ documentation is the one coming up first in Google searches and thus most visited.

**Comment by tombsar** [comment]
This should be fixed implicitly when 3.3 is released.
