### ISSUE TITLE
glfwTerminate  crash issue

### ISSUE THREAD

**Issue by heitaoflower** [glfw/glfw#1430]
Hi my friend,

I always encounter such  issue as below.

when I set should close glfw as true, the function of glfwTerminate crash randomly, 

could you help me figure out what is the reason？

**Comment by GreenLightning** [comment]
Can you post a minimal working example that demonstrates the crash?

**Comment by heitaoflower** [comment]
I resolve this issue right now, because of the NULL pointer on some situation, still thank you very much.
