### ISSUE TITLE
Change X11 cursor from Hand1 to Hand2

### ISSUE THREAD

**Issue by andydotxyz** [glfw/glfw#1432]
Looking at cursors for other platforms the "Hand" cursor is for pointing, such as with a hyperlink. In X11 cursor themes the Hand2 cursor is typically a pointer whereas Hand1 is more often an open hand.

Can we change to the pointer hand?

**Comment by elmindreda** [comment]
This has been fixed with 2a27eb95e42ddc880fa1fdb18872d2c892bd36c1. Thank you!
