### ISSUE TITLE
Window not opaque on some wayland compositor

### ISSUE THREAD

**Issue by xdavidwu** [glfw/glfw#1434]
GLFW windows on swaywm and rootston are always transparent.
Current method to make sure window is opaque, set_opaque_region, according to wayland protocol description, is just an optimization hint. I don't think it would necessarily make window opaque.
According to [wayland mailing list](https://lists.freedesktop.org/archives/wayland-devel/2014-March/013651.html), the proper way to make it opaque is to use a buffer without alpha channel.
To reproduce, comment out the transparent framebuffer hint line in the gears example and run it on swaywm or rootston.
Although it can be fixed by manually calling glfwWindowHint(GLFW_ALPHA_BITS, 0), I think this should be default on wayland.

**Comment by linkmauve** [comment]
The issue with that is how the Wayland code and the EGL code are completely isolated inside of GLFW. This is useful for Vulkan for instance, which doesn’t use EGL at all, or when you ask for no context during window creation.

Another issue with changing the framebuffer configuration before EGL initialisation is that some programs may expect to have an alpha channel if they require one and store things into it, even if it isn’t used for composition.

I’m not sure how to solve this issue, which also happens for Vulkan I guess, so I’ll leave this issue open for other people to chime in.

**Comment by physkets** [comment]
I just began using GLFW, so correct me if what I'm saying is non-sense, but I don't understand what is wrong with the current behaviour. When I initialise a window, it is by default, completely transparent. I can then use OpenGL to add colours with alpha set to unity if I want opacity. Is that not so?

**Comment by xdavidwu** [comment]
This issue is about windows created with GLFW_TRANSPARENT_FRAMEBUFFER set to false is still rendered as transparent on some wayland compositor, which is not the intended behavior. The current implementation marks the region opaque by wl_surface_set_opaque_region, which, by definition, is just a optimization hint (so compositors may ignore it). Filling alpha to make it opaque is indeed a workaround, but people may assume their things will be rendered like there is a black background with GLFW_TRANSPARENT_FRAMEBUFFER set to false.

**Comment by physkets** [comment]
Okay, thanks for the explanation! I'm using this via pyGLFW, and when I test this as follows:

```
glfw.window_hint(glfw.TRANSPARENT_FRAMEBUFFER, False)
if not glfw.get_window_attrib(pane, glfw.TRANSPARENT_FRAMEBUFFER):
    raise RuntimeError("Opacitisation failed")
```

I do indeed get the error (and without the check, it renders a transparent window).

I'm using KDE's plasma wayland session, which uses the KWin compositor. So I suppose it ignores that optimisation suggestion.

**Comment by linkmauve** [comment]
What you should do is use an RGBX config instead of a RGBA one, that way the alpha bits will correctly get ignored on all platforms.

**Comment by linkmauve** [comment]
This is now fixed, when using drivers which expose the `EGL_EXT_present_opaque` extension, such as Mesa.
