### ISSUE TITLE
Strange high CPU usage / staggering framerates in fullscreen in macOS Mojave.

### ISSUE THREAD

**Issue by inDigiNeous** [glfw/glfw#1435]
Hello.
This is something I noticed while I built my 3D engine using glfw in macOS Mojave.
The framerates were off. It was like the vsync was not happening, and the engine would be blasting frames to the screen too fast. I tried both with vsync enabled and disabled, no difference.

I also noticed my program was using unusually high CPU times, like around 50-60% for just a very simple scene, like one simple dodecahedron rendered, which previously hadn't taken anything above 10% ever IIRC. 

I was wondering what the heck was happening, because I hadn't change anything, only thing I had done I had not built my engine on Mojave, last time I tried it was in High Sierra (10.13).

Now, trying to pinpoint the problem I started to look at how the examples shipped with glfw were behaving. Running even the basic examples that are bundled with glfw I'm seeing strange things. Running the bounce app in windowed mode is taking nearly 85% in CPU usage, as seen here reported by top:

<img width="1221" alt="screenshot 2019-02-17 at 0 05 44" src="https://user-images.githubusercontent.com/1212726/52905782-cfb01100-3247-11e9-83df-50c9db879362.png">

This is strange I thought, this very simple app is making my MacBook Pro 2014 mid blowing it's fans. Something is not right here, I don't remember this happening before.

Trying to run the examples in fullscreen also result in jaggy performance, it's like the video output is not somehow even vsynced or it is trying to vsync multiple times per frame or something like this, the output is not smooth at all.

Here you can see a video recording of how it looks:

https://drive.google.com/open?id=1lBlc9F9jAzv-ZbrRgbzeJByb4NLLwZsl

Any idea why this is happening ? Incompatibility with Mojave ? Is this expected behaviour with the example apps ? It's making using my 3D engine at the time unusable, and I'm suspecting it has to do with glfw or the screen updates, as in High Sierra these used to work much more smoothly.

I'm testing with the current master branch, MacBook Pro 2014 mid (integrated graphics disabled, using the NVidia GeForce GT750M 2GB gpu).

**Comment by inDigiNeous** [comment]
Even testing with the most simple default example app, rotating a single triangle, results in 60-85% CPU usage, fans blowing and not even completely smooth framerate as far as I can see with my eyes:

<img width="1216" alt="screenshot 2019-02-17 at 0 15 35" src="https://user-images.githubusercontent.com/1212726/52905872-400b6200-3249-11e9-95fb-cc5c36f9ec2f.png">

This can't be correct behaviour for such a simple operation.

**Comment by inDigiNeous** [comment]
Allright digging into the issues I see that this is related to vsync broken in Mojave, as explained in https://github.com/glfw/glfw/pull/1417.

Tried the branch from https://github.com/amarcu5/glfw with the fix and with this the framerate issue is gone. Please merge and fix.

**Comment by elmindreda** [comment]
Thank you for testing the fix! It's held up by one final implementation issue but should be merged Any Day Now™.

**Comment by inDigiNeous** [comment]
Thanks for the reply and info! I'm gonna leave this issue open for now, if somebody else comes across the same thing, not entirely trivial to connect this to vsync and mojave.

**Comment by AndrewBelt** [comment]
I'm not sure if @amarcu5's fix solves this entirely.

I wrote a simple loop
```cpp
while(!glfwWindowShouldClose(win)) {
	double startTime = glfwGetTime();
	glfwPollEvents();
	glfwSwapBuffers(win);
	double endTime = glfwGetTime();
	printf("%g fps\n", 1 / (endTime - startTime));
}

```
and out of a 30s profile, 16s were spent in the `[NSOpenGLContext flushBuffer]` method, which is directly called by `glfwSwapBuffers`, indicating that over 50% of a thread was used. This isn't the case on MacOS 10.13 or less, just 10.14 (Mojave).

<img width="569" alt="screen shot 2019-02-27 at 3 28 38 pm" src="https://user-images.githubusercontent.com/338179/53521108-4c8f8600-3aa5-11e9-9281-7dcd4860545d.png">

Using @amarcu5's fork consistently gives better results.

<img width="552" alt="screen shot 2019-02-27 at 3 31 09 pm" src="https://user-images.githubusercontent.com/338179/53521110-4d281c80-3aa5-11e9-827f-d48c066f6621.png">

But the expected result is that swapping buffers should only take 1-4% of CPU time per thread. Not sure what's going on with Apple's `flushBuffer` method.

**Comment by elmindreda** [comment]
The display link solution for this has been merged. It's not ideal but it does work.
