### ISSUE TITLE
GLFWvidmode refreshRate contains a truncated integer (on Linux)

### ISSUE THREAD

**Issue by mulle-kybernetik-tv** [glfw/glfw#1441]
I used `const GLFWvidmode* mode = glfwGetVideoMode(monitor);` to get at the [refreshRate](https://www.glfw.org/docs/latest/structGLFWvidmode.html#a791bdd6c7697b09f7e9c97054bf05649). This is an integer value in Hz. I observed a value of 59 on my linux machine. The actual refresh rate though is 59.97 as determined by `xrandr`. 

* The integer should be rounded to 60 I think.
* IMO It would be more useful to make the refreshRate value frames/ms no frames/s.

**Comment by elmindreda** [comment]
Good point, rounding is a better approach than truncation here.

I agree that the refresh rate shouldn't be integer Hz. It will be addressed in the next API revision, see #230.

**Comment by elmindreda** [comment]
By a stroke of luck this affected only platforms where we can use C99. Fixed with `round` in 621ece63c8d31ae0dcf2196a3abde19ce8569984.
