### ISSUE TITLE
The hint GLFW_COCOA_RETINA_FRAMEBUFFER is no longer working.

### ISSUE THREAD

**Issue by mtyberg** [glfw/glfw#1442]
I am trying to force the window to not use retina(for the sake of some tests) but this does not work anymore. I am on the latest version of Mac OS mojave.

**Comment by elmindreda** [comment]
This is likely related to our current, poor handling of layers for our content view. I will look into it while fixing #1340.

**Comment by elmindreda** [comment]
Cannot reproduce on 10.14.4.

**Comment by Milerius** [comment]
GLFW_COCOA_RETINA_BUFFER do nothing on Mac OS Catalina @elmindreda

**Comment by Milerius** [comment]
I got smth like:

```
[INFO] GLAD initialized
[INFO] OpenGL renderer: AMD Radeon Pro 455 OpenGL Engine
[INFO] OpenGL from glad 4.1
[INFO] Window size: 960x540
```

**Comment by elmindreda** [comment]
Successfully reproduced on 10.15.1 Catalina.
