### ISSUE TITLE
Invalid axis in gamepad mapping using an Xbox Wireless Controller

### ISSUE THREAD

**Issue by rafaskb** [glfw/glfw#1447]
Hi! I'm having a problem where I can't use my Xbox One S Controller in wireless mode on macOS properly because some of the buttons and axes are not being detected. I use LibGDX though, which uses LWJGL3, so I'm not sure where the problem lies exactly, so I apologize if I'm reporting the bug in the wrong place.

Here's some information:
- OS: MacOS 1.12.6 (Sierra)
- LibGDX version 1.9.9
- LWJGL version 3.2.0
- GLFW "Updated to pre-release 3.3.0 version (up from 3.3.0 pre-release)" (According to LWJGL's changelog)
- Issue also happens on LWJGL version 3.2.2-SNAPSHOT

Running a LibGDX application, or a LWJGL one that uses GLFW (I tested with [LWJGL's GLFW Demo application](https://github.com/LWJGL/lwjgl3-demos/blob/master/src/org/lwjgl/demo/opengl/glfw/Multithreaded.java) causes a lot of errors (precisely 199 times) in the console like this one:

```
~/lwjgl3-demos(master) » java -XstartOnFirstThread -cp target/lwjgl3-demos.jar org.lwjgl.demo.opengl.glfw.Multithreaded
[LWJGL] GLFW_INVALID_VALUE error
	Description : Invalid axis in gamepad mapping 030000005e040000fd02000003090000 (Xbox Wireless Controller)
	Stacktrace  :
		org.lwjgl.glfw.GLFW.glfwInit(GLFW.java:829)
		org.lwjgl.demo.opengl.glfw.Multithreaded.init(Multithreaded.java:55)
		org.lwjgl.demo.opengl.glfw.Multithreaded.run(Multithreaded.java:36)
		org.lwjgl.demo.opengl.glfw.Multithreaded.main(Multithreaded.java:146)
```

And this is the line where the exception is pointing at:
https://github.com/LWJGL/lwjgl3/blob/master/modules/lwjgl/glfw/src/generated/java/org/lwjgl/glfw/GLFW.java#L829

I also made a simple LibGDX app to detect all events received from gamepads, and I get no signals at all from Left Trigger, Right Trigger and Back buttons.
The funny thing is if I connect the controller with a USB cable, everything works, but the mappings change as well (that might be because of macOS drivers though).

Are there any steps I can take to help narrow down the issue? Maybe a GLFW specific test to detect the controller or something?

Thanks in advance!

**Comment by elmindreda** [comment]
I don't have that controller but I have an idea what could be causing this issue. Would you be willing to test a possible fix?

**Comment by rafaskb** [comment]
Absolutely! I don't have much knowledge on glfw though, but I will do everything I can to help

**Comment by elmindreda** [comment]
@rafaskb Thanks! Please see if the [cocoa-iohid-child-elements](https://github.com/glfw/glfw/tree/cocoa-iohid-child-elements) branch works better for you.

**Comment by rafaskb** [comment]
I just compiled glfw from the master branch first and ran the `joysticks` test, everything works perfectly except for the Right Trigger and Left Trigger axes, as the original report says. They are not detected at all.

The only difference from my report is that the Back button and "Xbox" button are being reported now, with button values of 17 and 16, respectively. They weren't being detected before.

After that I did the same test under the `cocoa-iohid-child-elements` branch, but the result was identical.

I also ran the `cursor` test and the output contains a lot of "Invalid axis in gamepad" errors: https://gist.github.com/rafaskb/afcc16154e21d984202b4702dc80fb65

This `cursor` test was also under the `cocoa-iohid-child-elements` branch.

Please let me know if I do any other tests to help. :)

**Comment by elmindreda** [comment]
Thanks, that's very useful! I've added a few fixes to master, one of which may affect this issue.

**Comment by rafaskb** [comment]
Yes! That fixed the issue! The controller works perfectly now, and the recently added labels for all controller buttons are reported the way they should.

Thank you for fixing this so quickly. 😁

**Comment by elmindreda** [comment]
Awesome, thank you for the quick testing!
