### ISSUE TITLE
Ability to get title of GLFWwindow

### ISSUE THREAD

**Issue by Xydez** [glfw/glfw#1448]
I have a project where I need to get the title of a GLFWwindow, and I think this would be an easily implemented feature. I am unfortunately not very familiar with the inner workings of GLFW, so I can't implement it myself.

**Comment by LucasGithub123** [comment]
For now, I would just use the window user pointer as a workaround. You can store a pointer to any data you want with [glfwSetWindowUserPointer](https://www.glfw.org/docs/latest/group__window.html#ga3d2fc6026e690ab31a13f78bc9fd3651) and retrieve it anytime later with [glfwGetWindowUserPointer](https://www.glfw.org/docs/latest/group__window.html#ga17807ce0f45ac3f8bb50d6dcc59a4e06).

It's probably best to put your data in a struct, so you can add more data to it later on, such as a version number or something.
Here's  an example program that stores the title and an int in the window user pointer, then when the user presses T, it retrieves the pointer and uses it to print the title to the terminal.

```C
#include <stdio.h>
#include <GLFW/glfw3.h>

typedef struct {
    char* title;
    int myVersion;
} MyWindowData;

void key_callback(GLFWwindow* window, int key, int scancode, int action, int mods) {
    if(action == GLFW_PRESS ) {
        if(key == GLFW_KEY_T) { // READ DATA HERE
            MyWindowData* data = (MyWindowData*)glfwGetWindowUserPointer(window);
            printf("%s version %d\n", data->title, data->myVersion);
        }else if(key == GLFW_KEY_Q) {
            glfwSetWindowShouldClose(window, 1); // type Q to quit
        }
    }
}

int main() {
    if (!glfwInit()) return 1;
    char title[] = "My Cool Game";
    GLFWwindow* window = glfwCreateWindow(1280, 720, title, NULL, NULL);
    glfwSetKeyCallback(window, key_callback);
    MyWindowData data = { title, 42 };
    glfwSetWindowUserPointer(window, &data); // STORE DATA HERE
    while( !glfwWindowShouldClose(window) ) {
        // render() or whatever...
        glfwSwapBuffers(window);
        glfwPollEvents();
    }
    glfwDestroyWindow(window);
    glfwTerminate();
}
```

**Comment by elmindreda** [comment]
@Xydez It would not be difficult to add. May I ask why you need this?

**Comment by Xydez** [comment]
To dynamically append things onto the title (such as adding a dot every time an action is performed for example.). It isn't really *required* but it's useful since the user of the API doesn't have to keep track of the title themselves.

**Comment by elmindreda** [comment]
Thanks. Will consider this for 3.4. Thought there was an earlier issue for this but can't find it now.

**Comment by AbitTheGray** [comment]
I must second this feature request because I know my OS (Debian with KDE) adds `<2>`, `<3>`... to end of the title to have unique window titles.

Tested on [`kate`](https://kate-editor.org/) for screenshot.
Works same on other applications.

![image](https://user-images.githubusercontent.com/24275405/65242586-ae1d4d80-dae6-11e9-8813-05ea818c5bc7.png)

**Comment by dougbinks** [comment]
I have started work on this based on PR #1909 as per https://github.com/glfw/glfw/pull/1909#issuecomment-1930576696
