### ISSUE TITLE
how can I make it support OpenGL 4.6

### ISSUE THREAD

**Issue by ncuhome-huyue** [glfw/glfw#1449]

**Comment by ncuhome-huyue** [comment]
I find if I write code like this, I will get a nullptr.
`glfwInit();
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 5);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
    GLFWwindow* window = glfwCreateWindow(SCR_WIDTH, SCR_HEIGHT, "LearnOpenGL", NULL, NULL);`

**Comment by ncuhome-huyue** [comment]
> I find if I write code like this, I will get a nullptr.
> 
> ```
> glfwInit();
> glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
> glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 5);
> glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
> GLFWwindow* window = glfwCreateWindow(SCR_WIDTH, SCR_HEIGHT, "LearnOpenGL", NULL, NULL);
> ```

**Comment by elmindreda** [comment]
Does your GPU and its driver support OpenGL 4.6?

**Comment by ncuhome-huyue** [comment]
yes，I use gtx 1050，and its driver support OpenGL 4.6.

**Comment by elmindreda** [comment]
What error description does GLFW report when window creation fails?

**Comment by ncuhome-huyue** [comment]
65543
WGL: Driver does not support OpenGL version 4.6.

But, my driver is NVIDIA 419.35 for GTX 1050 and 22.20.16.4836 for Intel(R) HD Graphics 630. They all support OpenGL version 4.6.

**Comment by ncuhome-huyue** [comment]
Oh, thanks . I find it. I find my app use Intel(R) HD Graphics 630, and it don't support version 4.6, now I use GTX 1050. It can run without bug.
