### ISSUE TITLE
Context creation API selection at runtime

### ISSUE THREAD

**Issue by canatan** [glfw/glfw#145]
i just think that it will be better that moving GLFW_USE_EGL and relevant GLFW_CLIENT_LIBRARY switches 

somethink like app compile macro or glfwinit()  parameter.

Do you think?

REGARDS

**Comment by elmindreda** [comment]
The compile-time client library options have been removed, as that is now handled at runtime. Selection between EGL and native APIs is up next.

**Comment by elmindreda** [comment]
Moving this to 3.3 as I will be putting out a 3.2 shortly to have a release out with Vulkan support. I'm still working towards this, as well as the larger goal of run-time window system selection.

**Comment by elmindreda** [comment]
This is being worked on in the [context-api](https://github.com/glfw/glfw/tree/context-api) branch.
