### ISSUE TITLE
Mouse y coordinate is off-by-one in callback and disagrees with (correct) value returned by glfwGetCursorPos.

### ISSUE THREAD

**Issue by martinbundgaard** [glfw/glfw#1461]
In cocoa_window.m:mouseMoved, glfw's mouse cursor position is updated incorrectly by the line:

`_glfwInputCursorPos(window, pos.x, contentRect.size.height - pos.y);`

whereas cocoa_window.m:_glfwPlatformGetCursorPos does it correctly:

`*ypos = contentRect.size.height - pos.y - 1;`

**Comment by elmindreda** [comment]
@martinbundgaard Thank you for reporting this!
