### ISSUE TITLE
Scroll offsets inverted

### ISSUE THREAD

**Issue by onox** [glfw/glfw#1463]
The scroll offsets (both the X and Y axis) received in the scroll callback are inverted (positive instead of negative) compared to the GLFW's X11 backend and to Wayland and X11 drivers of SDL.

OS and version: Ubuntu 18.04
Desktop environment: GNOME Shell on Wayland
Release or commit: latest commit in `master` branch (3461d1c)
Error messages: none
events output: positive xoffset and yoffset when scrolling down or to the right

**Comment by warisb** [comment]
I am also able to reproduce this issue.

**Comment by elmindreda** [comment]
Successfully reproduced on Weston, relative to GLFW on X11 and Win32.

**Comment by elmindreda** [comment]
Successfully reproduced on Ubuntu GNOME on Wayland, as you said.

**Comment by elmindreda** [comment]
Thank you for reporting this. It should be fixed now with f760b124ca849d99effbedb91fb8d10a828aea00, which will be included in 3.3.3.
