### ISSUE TITLE
Running a Vulkan program without GLFW_NO_API works, but leaks memory

### ISSUE THREAD

**Issue by LightAndLight** [glfw/glfw#1464]
GLFW version: 3.2.1

I've been following [vulkan-tutorial.com](https://vulkan-tutorial.com/), but forgot to set the `GLFW_NO_API` hint. I rendered a triangle, but noticed my program leaked memory at around 1MB/s. Further investigation revealed the leaks came from `glfwPollEvents` and `vkQueuePresentKHR`. The leaks stopped after I set the appropriate hint.

Here's the tutorial's example code: https://github.com/Overv/VulkanTutorial/blob/master/code/15_hello_triangle.cpp. Comment out line 108 to reproduce.

**Comment by ghuser404** [comment]
@LightAndLight Can you try this on the latest master?

**Comment by elmindreda** [comment]
Having both OpenGL and Vulkan on the same window is not supported and any resulting leaks will be in the window system interface or the driver.
