### ISSUE TITLE
Add macOS pre-compiled binaries to 3.3 release 

### ISSUE THREAD

**Issue by RustyMoyher** [glfw/glfw#1466]
Adding pre-compiled binaries for macOS (and Linux if possible) would make it easier for new users to test and adopt GLFW. I think it's important to allow users to compile from the source, but it shouldn't be the only way. A lot of work goes into creating GLFW working properly on macOS and Linux. This extra bit would help the framework reach more users.

(Sorry for all the changes. I accidentally submitted before I finished the issue.)

**Comment by elmindreda** [comment]
Agreed, this makes much more sense now that nearly all macOS specific options have been moved to run-time.

**Comment by Perksey** [comment]
+1 would defo love official Linux and Mac binaries

**Comment by elmindreda** [comment]
Static and dynamic macOS binaries have been added to the 3.3 release and may even work! Future releases will include macOS binaries. Thank you for getting this started!

> Sorry for all the changes. I accidentally submitted before I finished the issue

@RustyMoyher No worries!

> +1 would defo love official Linux and Mac binaries

Linux binaries would require a lot more work, but package systems are upgrading to 3.3.

**Comment by Perksey** [comment]
Out of curiosity, what's stopping you from providing Linux binaries? We built them ourselves and it's wasn't too much work, so what's stopping you setting up a nice CI/CD for GLFW and just using that to build binaries on all platforms?

**Comment by elmindreda** [comment]
@Perksey It would be significantly more work than Windows or macOS because of the many combinations of options, architectures and distributions involved, while compiling it for one's own system isn't a lot of work.
