### ISSUE TITLE
glfwForEachWindow?

### ISSUE THREAD

**Issue by tomeksowi** [glfw/glfw#1478]
With `glfw(S|G)etWindowUserPointer` there's no need for the app to keep `GLFWwindow` -> per-app structure binding. But it's still necessary to do bookkeeping of all the `GLFWwindow`s that are in the app's posession.

Since GLFW stores windows in a linked list, adding a useful API like `glfwForEachWindow(GLFWwindowfun);` seems quite easy. Would that be a welcome addition? If so, I can prepare a pull request.

**Comment by alexeilukin404** [comment]
GLFW is intended to provide abstraction for a window API. Honestly, what you're suggesting is not something the library should provide. This only pollutes API and can be easily done on your side.

**Comment by ghuser404** [comment]
GLFW is intended to provide abstraction for a window API. Honestly, what you're suggesting is not something the library should provide. This only pollutes API and can be easily done on your side.

**Comment by tomeksowi** [comment]
Alright.
