### ISSUE TITLE
glfwSwapInterval disabled on systems using DWM

### ISSUE THREAD

**Issue by elvencode** [glfw/glfw#148]
Using the function doesn't work in any way, even going fullscreen and/or setting the fullscreen refresh rate hint. So i tried to swap its call, for example, in the simple.c test, with (after the call to ):

```
//glfwSwapInterval(1);

GLenum err = glewInit();
if (GLEW_OK != err) {
    exit( 1 ); // error
};

wglSwapIntervalEXT(1);
```

and now it works, in windowed and fullscreen mode without having to set any hint or else. My settings:

GLFW 3.0.3 
Windows 7 64bit
Radeon 7850 with Catalyst 13.9
32 bit compilation

**Comment by elmindreda** [comment]
This has received what may be a more appropriate fix with 8309e0ecb09fe5cf670dff5df1e7ca71821c27bd.
