### ISSUE TITLE
glfw fails on debian docker with xvfb

### ISSUE THREAD

**Issue by yakirsudry** [glfw/glfw#1481]
When trying to create a window in python running inside xvfb on debian I get:

`GLX: Failed to find a suitable GLXFBConfig`

To reproduce the problem fully:

`docker run --name headless_test -ti python:3.6-jessie /bin/bash`

Inside the docker execute:

`apt update && apt install -y git xvfb xorg-dev cmake

pip3 install glfw

mkdir /projects

git clone https://github.com/glfw/glfw.git /projects/glfw

cd /projects/glfw

cmake -DBUILD_SHARED_LIBS=ON .

make

export PYGLFW_LIBRARY=/projects/glfw/src/libglfw.so

xvfb-run python -c "import glfw; glfw.init(); glfw.window_hint(glfw.VISIBLE, False); glfw.create_window(100, 100, 'hidden window', None, None)"`

executing `xvfb-run glxinfo` (after installing `mesa-utils`) returns the following:

`libGL error: No matching fbConfigs or visuals found

libGL error: failed to load driver: swrast

Error: couldn't find RGB GLX visual or fbconfig`

**Comment by elmindreda** [comment]
This seems like an issue with the X server not supporting GLX, not with GLFW, especially since non-GLFW programs have the same problem. I don't know what GLFW could do about this.
