### ISSUE TITLE
glfwSetCursorPosCallback Doesn't Detect Mouse Movement Outside GLFW Window

### ISSUE THREAD

**Issue by calioranged** [glfw/glfw#1485]
glfwSetCursorPosCallback() only runs when the mouse is inside the window. Mouse movement is not detected if outside the GLFW window. 

`static void cursorPositionCallback(GLFWwindow* window, double xPos, double yPos)`
`{`
`	std::cout << xPos << "   :   " << yPos << std::endl;`
`}`

`while (!glfw.WindowShouldClose())`
`{`
`	shader.ClearBuffers(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);`
`	glfw.ResizeWindow(MVP); `
`	Cube_IBO.DrawElementsInstanced(CubeIndices.size(), 2);`
`	glfwSetCursorPosCallback(glfw.GetWindowID(), cursorPositionCallback);`
`	glfw.SwapBuffers(); `
`}`

Just earlier I had this function working without any problems. But now mouse movement isn't detected outside the GLFW window. 

System details:

Using Windows 10
Visual Studio 16.0.4
GLFW Version 3.3

**Comment by elmindreda** [comment]
> Mouse movement is not detected if outside the GLFW window.

This is how mouse input normally works. It may have worked outside the content area earlier because you pressed a mouse button on the content area and activated mouse capture.

Do you need mouse position events outside the window even when not dragging?

**Comment by tombsar** [comment]
@calioranged Can this issue be closed?

**Comment by jensfredgaard** [comment]
@elmindreda Did you end up making a callback function or was this task ignored?

**Comment by jensfredgaard** [comment]
I might have mixed a few issues together, my bad. I will try again, my intention was to ask about the status for a callback function that throws an event when the mouse cursor leaves the window on Windows.

**Comment by jensfredgaard** [comment]
Wow, I totally missed that one, exactly what I was looking for, amazing response time! I was almost done writing my own WndProc func :D
