### ISSUE TITLE
Keypress not detected when other keys are pressed

### ISSUE THREAD

**Issue by mexxexx** [glfw/glfw#1488]
I have the following issue on X11 Ubuntu 18.04 and GLFW compiled from source:

Sometimes, when multiple keys are already pressed, GLFW does not detect when another one is pressed later on. In particular I noticed it a the following combination: If the W and S keys are already pressed, no "KEY_PRESS" event for key A is detected. On the other hand, if A was pressed, then W and S are pressed and then A is released, "KEY_RELEASE" is detected. 

I am using a loop and glfwPollEvents() if this makes any difference, and the issue occurs using glfwKeyCallback or glfwGetKey.

**Comment by tombsar** [comment]
Can you please test whether those same key combinations work in any non-glfw software on the same machine? It's common for consumer keyboards (particularly at the cheaper end) not to be able to resolve all possible three-or-more key combinations, and there's really not anything we can do about it in software if that is indeed the case.

**Comment by mexxexx** [comment]
Indeed, after having a look with showkey, it appears that in some cases no events are triggered by the system environment.

**Comment by tombsar** [comment]
For more information, see here: https://en.wikipedia.org/wiki/Rollover_(key)#n-key_rollover

I personally have a keyboard with n-key rollover; worth the extra cost imo!
