### ISSUE TITLE
window has no title bar on wayland

### ISSUE THREAD

**Issue by aleck099** [glfw/glfw#1489]
![Screenshot from 2019-05-26 09-21-12](https://user-images.githubusercontent.com/33549441/58376201-9678f280-7f54-11e9-9945-c2f4d5c5629d.png)
![Screenshot from 2019-05-26 09-20-18](https://user-images.githubusercontent.com/33549441/58376202-9b3da680-7f54-11e9-891e-a2ee95a5e6b9.png)
![Screenshot from 2019-05-26 09-31-03](https://user-images.githubusercontent.com/33549441/58376250-f45a0a00-7f55-11e9-8019-ccc1be438e57.png)

It's working well on Xorg
I don't know whether this is a bug or a feature.
But this would make trouble to users.
(I'm sorry can't record a video on wayland)

**Comment by aleck099** [comment]
This also happens on Ubuntu 18.04

**Comment by linkmauve** [comment]
Hi,

GNOME [has rejected implementing the xdg-decoration protocol](https://gitlab.gnome.org/GNOME/mutter/issues/217), which we [use to get server-side decoration](https://github.com/glfw/glfw/pull/1341).

What you get is not an absence of decoration, but [our simple fallback](https://github.com/glfw/glfw/pull/1161) which allows moving and resizing the window but not much more, as things such as text rendering or button drawing are very complex.

You may want to use another compositor, such as KDE or Sway, both of which do implement server-side decoration, or build GLFW using its X11 backend. Sorry about that.

**Comment by aleck099** [comment]
Thanks!
I got it
