### ISSUE TITLE
Why no plus key?

### ISSUE THREAD

**Issue by spth** [glfw/glfw#1494]
GLFW supports the minus key, but not the plus key on the main keyboard. On the keypad, both are supported.
This is confusing. Is it because there is no separate plus key on US keyboards (as I only just now found out about that US keyboard layout thing, after wondering for quite a while why GLFW does not support the plus key)?
If yes, this should be clearly stated in the documentation. While there is an "The US keyboard layout is used" in there, it would be nice to have something like "There is no GLFW_KEY_PLUS due to …"

**Comment by elmindreda** [comment]
If you run the `events` test program and press the plus key, what does it print out?

**Comment by Pokechu22** [comment]
`GLFW_KEY_MINUS` refers to the hyphen-minus key that also has underscore on it.  `GLFW_KEY_EQUAL` has the + key (but you get that with shift).

The keys you are looking for are the numpad ones, which have a `KP` suffix: `GLFW_KEY_KP_SUBTRACT` and `GLFW_KEY_KP_ADD`.
