### ISSUE TITLE
GLFW cannot use C++ lambdas as it is written in C

### ISSUE THREAD

**Issue by jenseh** [glfw/glfw#15]
I would like to see the glfwSet...Callback functions to accept lambda-expressions with captures (from c++11).
Example:

``` c++
glfwSetWindowSizeCallback(window,
    [&](int w, int h){
        width = w; height = h;
    });
```

**Comment by alecjacobson** [comment]
Is there a best practice (or existing solution) for such a C++11 wrapper?

**Comment by bcrist** [comment]
Something like this would work:
```
std::unordered_map<GLFWwindow*, std::function<void(int, int)>> callbacks;
void glfwSetWindowSizeCallback(GLFWwindow* window, std::function<void(int, int)> callback) {
    callbacks[window] = std::move(callback);
    glfwSetWindowSizeCallback(window, [](GLFWwindow* wnd, int w, int h) { callbacks[wnd](w,h); });
}
```
But in my opinion you're better off creating a class specific to your application that wraps everything related to GLFWwindow that you need and use glfwSet/GetWindowUserPointer to store and retrieve a pointer to an instance of your class.
