### ISSUE TITLE
Scroll Callback: On Scroll Stop?

### ISSUE THREAD

**Issue by mattparks** [glfw/glfw#1505]
I'm using `glfwSetScrollCallback` to record the scroll states on a mouse. On Windows 10 when a scroll is stopped the associated offset will not have a zero value passed. It also appears when this callback is called only one of the offsets will have a value.
For the application I'm using the callback in knowing when a scroll has stopped is very useful.

**Comment by ghuser404** [comment]
What do you mean "scroll is stopped"? Do you expect the callback fire twice every second if I scroll the wheel one step a second? What interval would you expect GLFW to wait before it notifies you about scroll stopped?

I don't think there is such thing on OS level as "scroll stopped", but perhaps you could implement such thing yourself? Create a thread that checks last time scroll was reported, and then, depending on your chosen interval, notify you about scroll stopped.

**Comment by mattparks** [comment]
![Example](https://user-images.githubusercontent.com/4019937/59558391-d3199600-8fb6-11e9-8c61-3c06f18d211b.png)
If I'm scrolling down and stop scrolling I would expect a zero reported to the callback. In this image I show when I change direction, or stop scrolling.
GLFW reports when the magnitude of the scroll has changed, so maybe when it drops to zero it would fire the event?

**Comment by ghuser404** [comment]
I believe, GLFW reports how much you have scrolled since the last time the scroll was discovered. So if you make a small or big scroll within a time frame where OS sees the scroll, this will be reflected in the value. So I'm afraid value 0 would be meaningless here.

This is something you should solve on your side.

**Comment by mattparks** [comment]
Ah ok, I misunderstood the functionality of the callback then. Thanks for the help.
