### ISSUE TITLE
Borderless fullscreen issues (low fps, black second monitor)

### ISSUE THREAD

**Issue by p-groarke** [glfw/glfw#1507]
I am using a maximize callback to override the window maximize behavior. When a user maximizes the window, it will enter fullscreen borderless. This needs to happen on the current monitor the window is drawn on.

Is there an API that returns the monitor of the current window?

`GLFWmonitor* monitor = glfwGetWindowMonitor(window);` 
This only works if the window is already fullscreen.

```
const GLFWvidmode* mode = glfwGetVideoMode(monitor);
glfwSetWindowMonitor(window, monitor, 0, 0, mode->width, mode->height, mode->refreshRate);
```
To enable the fullscreen mode, you need a monitor, or it will assert
`Assertion failed: monitor != NULL, file src\monitor.c, line 441`

Yet the docs say 
> You can move windows between monitors or between full screen and windowed mode with glfwSetWindowMonitor

But how can you go fullscreen if you don't have a monitor pointer (since you are in windowed mode)?

Thx

**Comment by p-groarke** [comment]
OK for now, I just iterate all monitors and find the correct one using the window position and mode width/height. @elmindreda Would you like a pr with something like this? Seems useful. Something like  `GLFWmonitor* glfwGetWindowMonitor(int xpos, int ypos)`.

In any case, setting "fullscreen borderless" doesn't give expected results. My second monitor becomes black and the FPS goes down to something ridiculous (maybe 1 fps, maybe less).

It's funny I get these issues, as I had the same problems with a game I bought yesterday. I guess they use GLFW :) I'm running Win10 64bits, glfw 3.3 and nvidia 430.39.

Setting `GLFW_DECORATED` to false works as I would expect in terms of fullscreen borderless, but the window doesn't cover the whole screen. If I maximize the non-decorated window, then fullscreen kicks in, the fps drops like mad and my second monitor turns black.

Is this a known issue? I'm happy to setup a unit test to repro and investigate some more.

**Comment by p-groarke** [comment]
My issues seem to be the same as this : https://github.com/glfw/glfw/issues/649
With the extra black second monitor.

**Comment by ghuser404** [comment]
Are you doing all that from the Maximize callback (don't do that)?
Can you try doing that from outside of the GLFW callbacks?

**Comment by p-groarke** [comment]
Sure, issues persist.

**Comment by p-groarke** [comment]
OK so I've been debugging this using boing. In `win32_window.c line 1735` adding `WS_POPUPWINDOW` to the style fixes all my issues.

```
        if (window->decorated)
        {
            DWORD style = GetWindowLongW(window->win32.handle, GWL_STYLE);
            style &= ~WS_OVERLAPPEDWINDOW;
            style |= getWindowStyle(window);
            SetWindowLongW(window->win32.handle, GWL_STYLE, style | WS_POPUPWINDOW);
            flags |= SWP_FRAMECHANGED;
        }
```

However, at that point the window will minimize when you change focus (click something on a second monitor). This isn't expected behavior for borderless windows. I'm investigating various things, `HWND_TOPMOST` doesn't fix this, neither does `WS_EX_TOPMOST`. I'll keep digging.

I've read on other issues `WS_POPUP` was removed due to tearing on nvidia card in windowed mode. Has `WS_POPUPWINDOW` been tested similarly?

**Comment by p-groarke** [comment]
OK, and that can be fixed be disabling `GLFW_AUTO_ICONIFY`. However, you need to change `HWND_TOPMOST` to `HWND_TOP` to get expected borderless fullscreen behavior.

Do you want a PR?

**Comment by aloucks** [comment]
> Setting `GLFW_DECORATED` to false works as I would expect in terms of fullscreen borderless, but the window doesn't cover the whole screen. If I maximize the non-decorated window, then fullscreen kicks in, the fps drops like mad and my second monitor turns black.

You need to **also** set the window size to the dimensions of the monitor after you disable decorations. 

I can't remember if I've done this in the maximize callback or not, but I'm 100% certain that you can set full screen windowed mode.

**Comment by p-groarke** [comment]
Just an update on this. It seems to be a driver bug (or windows issue, or both). Rebooting fixes the issue for a limited time. I'm trying to get through nvidia support to get them to open a ticket on their end, which seems impossible, lol.
