### ISSUE TITLE
green gear is transparent

### ISSUE THREAD

**Issue by bradder555** [glfw/glfw#1512]
The green gear on the gears example is partially fully transparent

Graphics card GTX980M
Windows 10, version 1803

First image is with no code changes
![1560949698](https://user-images.githubusercontent.com/17851543/59769791-69acc680-92d9-11e9-9064-974f9d420778.png)

Second image with transparent framebuffer off
![1560949735](https://user-images.githubusercontent.com/17851543/59769793-69acc680-92d9-11e9-9cab-84ca4a528768.png)

Third image is after changing from
```
            SetLayeredWindowAttributes(window->win32.handle,
                                       RGB(0, 193, 48), 255, LWA_COLORKEY);
```

to
```
            SetLayeredWindowAttributes(window->win32.handle,
                                       RGB(0, 0, 1), 255, LWA_COLORKEY);
```

on line:
https://github.com/glfw/glfw/blob/d834f01ca43c0f5ddd31b00a7fc2f48abbafa3da/src/win32_window.c#L414

![1560951152](https://user-images.githubusercontent.com/17851543/59769998-c8724000-92d9-11e9-9f0c-1848ef21d156.png)

There is a comment saying this bit of code is a bit hacky

Its just a massive coincidence that the green cog in its initial position happens to be the same color as rgb(0,193,48)
![image](https://user-images.githubusercontent.com/17851543/59770827-3bc88180-92db-11e9-9c29-24b7f452cfa2.png)

obviously my change is still vulnerable to this issue, i wonder what other's thoughts about fixing this would be.

Furthermore, the comment mentions leaving it at rgb(0,0,0) causes trailing backgrounds. This doesn't happen on my machine, however a neat side-effect is i can click through the transparency

**Comment by elmindreda** [comment]
Yup, that's a bug, thank you! Not sure if there's a _good_ solution, but the least we could do is pick a more suitable color.

**Comment by tombsar** [comment]
Would 0xFF00FF be appropriate? I typically use that as a to-become-transparent colour.

**Comment by elmindreda** [comment]
@tombsar Yeah, that or something like 0x010101.

**Comment by elmindreda** [comment]
I cannot reproduce the trailing issue that the color key code is supposed to work around on either Windows 7 (Intel and Nvidia) or Windows 10 (Intel and Nvidia). I'm inclined to say it was a bug in earlier versions of Windows 10 and remove the workaround altogether.

**Comment by BFavier** [comment]
Is this workaround still needed ? I had a hole in my window because i was rendering a pink image (testing some opengl shader), I thought it was a bug in my shader.
Maybe this should be mentioned in the GLFW window guide.

**Comment by elmindreda** [comment]
@BFavier Good point. It really needs to be.

**Comment by elmindreda** [comment]
It is mentioned [here](https://www.glfw.org/docs/latest/window#GLFW_TRANSPARENT_FRAMEBUFFER_hint).

**Comment by ErikMcClure** [comment]
So, after coming to GLFW after using Direct2D, I feel obligated to point out that WS_EX_LAYERED hasn't been required for transparency for a while. If you simply don't set WS_EX_LAYERED (or remove it after creating the window), everything works fine, because now windows ignores the color key and correctly composites. I'm pretty sure whatever bug this was working around only applied before Windows 7.

**Comment by elmindreda** [comment]
@ErikMcClure Ooh, I will look into this. Thank you! We do still support Windows XP but hopefully not for much longer.

**Comment by ErikMcClure** [comment]
Even if you are supporting XP, surely you could at least put in a compile switch to disable this behavior? Or even [dynamically detect whether or not the system is XP](https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getversion) and only enable the flag if it is XP.

**Comment by elmindreda** [comment]
@ErikMcClure I cannot reproduce the issue that led to the color key hack on either Windows 7 or 10 on any GPU, so I'd be fine with removing it and seeing if any issues pop up.

**Comment by elmindreda** [comment]
No, never mind, the bug is still there.

I tried to figure out why this bug happens but failed.  I did however figure out more about when it happens, which is on Windows 7 when DWM is enabled but transparency effects are disabled. The `win32-colorization-opacity` branch is the result and my proposal for resolving this issue.

**Comment by ErikMcClure** [comment]
That fix seems reasonable and should keep weird behavior from happening in windows 10

**Comment by hajimehoshi** [comment]
Isn't this change already in v3.3? https://github.com/glfw/glfw/blob/3.3-stable/src/win32_window.c#L367-L400

**Comment by elmindreda** [comment]
@hajimehoshi So it is! I've moved this to 3.3.3. Thank you!
