### ISSUE TITLE
glfwPostEmptyEvent does not unblock glfwWaitEvents on Wayland

### ISSUE THREAD

**Issue by eXeC64** [glfw/glfw#1520]
I played with [this test case](https://github.com/glfw/glfw/blob/master/tests/empty.c) to check if I was doing something wrong in my own code, but it also reproduces the issue.

On X11, glfw behaves correctly. On Wayland, `glfwPostEmptyEvent` from a second thread fails to wake up `glfwWaitEvents` and `glfwWaitEventsTimeout`.

**Comment by OlivierSohn** [comment]
I think I fixed that in #1285 which is not merged yet

**Comment by elmindreda** [comment]
This should be finally fixed now with a32cbf6d4febde6343167f19529b8bde8966670d, which was partly based on #1285 though the specific fix for Wayland was different. Thank you for the bug report and your patience!
