### ISSUE TITLE
3.3.0 release as package on ubuntu

### ISSUE THREAD

**Issue by marsp0** [glfw/glfw#1522]
When do you plan on releasing version 3.3.0 as a package that can be installed via `apt-get` ? I have installed 3.2.1 via the package manager and I believe I am encountering the same issues described here : https://github.com/glfw/glfw/issues/747. Those issues are resolved in 3.3 but it is not available through the package manager and i am not very comfortable building from scratch as i do not want to fuck something up.

**Comment by tombsar** [comment]
I'm afraid it's up to the package maintainers over at Debian and/or Ubuntu to pull the release from here and package it for their distributions.

I recommend trying to compile it yourself, if for nothing more than the learning opportunity; it's really quite easy compared to many other open-source projects I've come across!

**Comment by marsp0** [comment]
makes sense, ill try and compile it then!
