### ISSUE TITLE
GLFW_INCLUDE_VULKAN macro definition causes warnings on MSVC 2017

### ISSUE THREAD

**Issue by gordeevso** [glfw/glfw#1524]
example code:
#define GLFW_INCLUDE_VULKAN
#include <GLFW/glfw3.h>

causes such warnings:

1>c:\program files (x86)\windows kits\10\include\10.0.17763.0\shared\minwindef.h(130): warning C4005: 'APIENTRY': macro redefinition
1>c:\projects\blastengine\external\glfw\include\glfw\glfw3.h(98): note: see previous definition of 'APIENTRY'
1>c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\wingdi.h(36): warning C4005: 'WINGDIAPI': macro redefinition
1>c:\projects\blastengine\external\glfw\include\glfw\glfw3.h(107): note: see previous definition of 'WINGDIAPI'

(I used msvc 2017 community)

#include <vulkan/vulkan.h>
#include <GLFW/glfw3.h>

causes no warnings

**Comment by elmindreda** [comment]
Did you define `VK_USE_PLATFORM_WIN32_KHR` in or for that source file?

**Comment by gordeevso** [comment]
@elmindreda, yep, it comes from preprocessor definitions (visual studio projects settings)

**Comment by elmindreda** [comment]
This should be fixed now with 773f4495f005004ea17fbc4a96b6b1ce758e79d6. Thank you for reporting this.

**Comment by gordeevso** [comment]
No problem :) GLFW is a great software and I'm glad to help, even if it's about reporting bugs
