### ISSUE TITLE
Provide window pointer to joystick connected callback.

### ISSUE THREAD

**Issue by p-groarke** [glfw/glfw#1526]
Without a mechanism to get user window pointers, the joystick connected callback breaks the GLFW idioms set in place. As you can imagine, my whole window architecture is based on it.

I understand the joystick connected callback should broadcast to all windows, but not all windows want to receive the event. Could you add an overload where the user provides a GLFWwindow*, like all other callbacks?

Potentially, a function to get all set user window pointers would also fix this issue (I haven't found such a thing).

**Comment by tombsar** [comment]
Can the feature added in #1080 achieve what you need?

**Comment by p-groarke** [comment]
Thx for the quick reply @tombsar. The problem with joystick user pointers is there is only 1 pointer per joystick (if I understand the doc correctly). This means for a setup with a single window, it will work fine.

For my setup however, I support multiple windows. They must all receive the callback event, to decide whether or not to discard it. I guess I could hack something together, but this callback is in stark contrast to the rest of the GLFW architecture and should be updated to support passing `GLFWwindow*`.

Are there technical reasons why this isn't possible? Or at least, difficult to achieve?
