### ISSUE TITLE
Different callback calling behavior when calling glfwSetWindowPos

### ISSUE THREAD

**Issue by H1MSK** [glfw/glfw#1534]
On windows, when you call glfwSetWindowPos, this function will post a SetWindowPos(or so on) event, and call the glfwWindowPosCallback, but on X11, the glfwWindowPosCallback will not be called.

It isn't so important, but I still wish a standard to be set and followed

**Comment by aloucks** [comment]
This behavior is described in the documentation for `glfwPollEvents` and `glfwWaitEvents`.

https://www.glfw.org/docs/latest/input_guide.html#events

> Do not assume that callbacks will only be called in response to the above functions. While it is necessary to process events in one or more of the ways above, window systems that require GLFW to register callbacks of its own can pass events to GLFW in response to many window system function calls. GLFW will pass those events on to the application callbacks before returning.
>
> For example, on Windows the system function that glfwSetWindowSize is implemented with will send window size events directly to the event callback that every window has and that GLFW implements for its windows. If you have set a window size callback GLFW will call it in turn with the new size before everything returns back out of the glfwSetWindowSize call.
