### ISSUE TITLE
Cmake issue 

### ISSUE THREAD

**Issue by Digus12** [glfw/glfw#1536]
When generating build files, I am getting "error in Configuration process". I have searched everywhere for this issue. It seems like older versions work from previous tutorials. But not the stable? Can anyone help me out?

**Comment by Digus12** [comment]
![program](https://user-images.githubusercontent.com/30579236/61257798-8e615600-a740-11e9-9571-14a2212fc2c6.JPG)

**Comment by elmindreda** [comment]
What does the log file mentioned in the main window say?

**Comment by tombsar** [comment]
@Digus12 Can this issue be closed?
