### ISSUE TITLE
Error when building using cmake through Bazel on OSX

### ISSUE THREAD

**Issue by grant-rez** [glfw/glfw#1537]
Hi there,

I'm getting an error when building the library from source with Bazel using an external dependency rule. I believe that this problem is related to bazel defining DEBUG to be 1, which they claim is the [correct behavior ](https://github.com/bazelbuild/bazel/issues/3513) on MacOSX. The word DEBUG is used in at least one place in the code base and this creates problems. Here is the error:

```
/var/tmp/_bazel_grantreszczyk/0c7662858b5d6ee977c0c3f6d357e89a/sandbox/darwin-sandbox/12/execroot/__main__/external/glfw_src/tests/glfwinfo.c:361:39: error: expected identifier
    enum { CLIENT, CONTEXT, BEHAVIOR, DEBUG, FORWARD, HELP, EXTENSIONS, LAYERS,
                                      ^
<command line>:2:15: note: expanded from here
#define DEBUG 1
              ^
/var/tmp/_bazel_grantreszczyk/0c7662858b5d6ee977c0c3f6d357e89a/sandbox/darwin-sandbox/12/execroot/__main__/external/glfw_src/tests/glfwinfo.c:463:18: error: duplicate case value: 'CONTEXT' and '1' both equal '1'
            case DEBUG:
                 ^
<command line>:2:15: note: expanded from here
#define DEBUG 1
              ^
/var/tmp/_bazel_grantreszczyk/0c7662858b5d6ee977c0c3f6d357e89a/sandbox/darwin-sandbox/12/execroot/__main__/external/glfw_src/tests/glfwinfo.c:449:18: note: previous case defined here
            case CONTEXT:
                 ^
2 errors generated.
make[2]: *** [tests/CMakeFiles/glfwinfo.dir/glfwinfo.c.o] Error 1
make[1]: *** [tests/CMakeFiles/glfwinfo.dir/all] Error 2
make: *** [all] Error 2
```

When I compile with optimization flags, the library builds as expected.

**Comment by tombsar** [comment]
I find it strange that the development environment would rely on a non-reserved identifier this way, but it's easy enough to work around on our end.

Note that it's only the "glfwinfo" test program that triggers the issue, not the library itself. It should be possible to configure your dependency (sorry, I don't know anything about Bazel) to skip building the test and example programs if all you want is the library itself.
