### ISSUE TITLE
[BUG] glClearColor clears with wrong transparency

### ISSUE THREAD

**Issue by AregevDev** [glfw/glfw#1538]
To reproduce:
- enable framebuffer transparency
- clear the color to 0.0, 0.0, 0.0, 0.0 = works as expected, completely invisible window
- clear the color to 1.0, 1.0, 1.0, 0.0 = window is white but completely visible

GLFW 3.3 Ubuntu 19.04 Nvidia Drivers 418

Screenshots:
![image](https://user-images.githubusercontent.com/40574704/61404252-c18e1b80-a8df-11e9-90fa-38cd9562c03b.png)
![image](https://user-images.githubusercontent.com/40574704/61404325-e5e9f800-a8df-11e9-9b33-6302a76b7bcf.png)
![image](https://user-images.githubusercontent.com/40574704/61404365-f8fcc800-a8df-11e9-96f3-9955a9ce071f.png)

**Comment by tombsar** [comment]
Your window manager is probably expecting the framebuffer to be in "premultiplied alpha" format, in which case RGBA(255,255,255,0) is not a valid colour. This is something we have discussed before (in the context of mouse cursors, I believe), but there didn't seem to be a good way to detect what format the underlying system is expecting.

**Comment by AregevDev** [comment]
So is this platform-specific issue?

**Comment by AregevDev** [comment]
```c
#include <glad/glad.h>
#include <GLFW/glfw3.h>
#include <stdio.h>

void resizeCallback(GLFWwindow *window, int width, int height) {
    glViewport(0, 0, width, height);
}

void errorCallback(int error, const char* description) {
    printf("Error: %s\n", description);
}

int main() {
    GLFWwindow *window;

    if (!glfwInit()) {
        puts("Could not initialize GLFW");
        return 1;
    }

    glfwWindowHint(GLFW_TRANSPARENT_FRAMEBUFFER, 1);

    window = glfwCreateWindow(500, 500, "opengl", NULL, NULL);
    if (!window) {
        puts("Could not create GLFW window");
        return 1;
    }
    glfwSetFramebufferSizeCallback(window, resizeCallback);
    glfwSetErrorCallback(errorCallback);

    glfwMakeContextCurrent(window);
    glfwSwapInterval(1);

    if (!gladLoadGLLoader((GLADloadproc) glfwGetProcAddress)) {
        puts("Could not initialize Glad");
        return 1;
    }

    while (!glfwWindowShouldClose(window)) {
        glClearColor(0.0, 0.0, 0.0, 0.0);
        glClear(GL_COLOR_BUFFER_BIT);

        glfwSwapBuffers(window);
        glfwPollEvents();
    }
    glfwDestroyWindow(window);
    glfwTerminate();
    return 0;
}
```
My full code

**Comment by AregevDev** [comment]
This issue does not occur on raylib for example, a library that uses GLFW as it's windowing backend.

**Comment by tombsar** [comment]
Can you share the code that you tested raylib with? I tried running your example on Windows 10, and it gave the same result as you are reporting (i.e. colours should be in premul format).

**Comment by AregevDev** [comment]
There:
```c
#include <stdio.h>
#include <raylib.h>

int main() {
    SetConfigFlags(FLAG_WINDOW_TRANSPARENT | FLAG_WINDOW_RESIZABLE);
    InitWindow(500, 500, "Hello");

    while (!WindowShouldClose()) {
        BeginDrawing();
        ClearBackground(GetColor(0x11111100));
        DrawRectangle(40, 40, 100, 100, RED);
        EndDrawing();
    }

    CloseWindow();
    return 0;
}
```

**Comment by raysan5** [comment]
@AregevDev try with: 
```c
ClearBackground(GetColor(0xffffff00));
```
Behaviour should be the same than GLFW.

**Comment by AregevDev** [comment]
What's the difference?

**Comment by raysan5** [comment]
@AregevDev 

 - `0xffffff00` = RGBA(ff, ff, ff, 00) = RGBA(255, 255, 255, 0) = RGBA(1.0, 1.0, 1.0, 0.0)

 - `0x11111100` = RGBA(11, 11, 11, 00) = RGBA(17, 17, 17, 0) ~= RGBA(0.0667, 0.0667, 0.0667, 0.0)

Second case, the one you use with raylib, is close to `glClearColor(0.0, 0.0, 0.0, 0.0)` that works ok:

 > clear the color to 0.0, 0.0, 0.0, 0.0 = works as expected, completely invisible window

**Comment by tombsar** [comment]
IMO there isn't really a bug here per se, it's just a misunderstanding about the meaning of the alpha channel and how it is interpreted by the underlying system. Premultiplied alpha seems to be the dominant format (Windows 10 and popular Linux DEs expect it; I don't know about MacOS), so I recommend just using it as default.

Ideally glfw would provide a method to check if premul is expected (so you as the programmer can react accordingly), but as I said above there doesn't seem to be a standard mechanism to detect this.

Same issue as #1211 .

**Comment by tombsar** [comment]
Can this issue be closed?

**Comment by AregevDev** [comment]
Sure, I guess...

**Comment by raysan5** [comment]
I think it can be closed.
