### ISSUE TITLE
What should I do to enable my application to automatically select a high performance graphics card?

### ISSUE THREAD

**Issue by ncuhome-huyue** [glfw/glfw#1545]
What should I do to enable my application to automatically select the higher performance graphics card?
In windows 10 with OpenGL.

**Comment by dkorpel** [comment]
[Compile glfw with GLFW_USE_HYBRID_HPG enabled](https://github.com/glfw/glfw/blob/0ccb690853e29ae38317d762f9deaa37ba101f4b/docs/compile.dox#L239), or manually add this to one of your .cpp files:
```
extern "C"
{
   __declspec(dllexport) int AmdPowerXpressRequestHighPerformance = 1;
   __declspec(dllexport) DWORD NvOptimusEnablement = 0x00000001;
}
```

**Comment by smilexin** [comment]
@dkorpel  Thanks for you guide, I have one more question: the above method is only used in dynamically linked case, how can i use this optimization in static linked case? Looking forward for your reply, thanks :)

**Comment by dkorpel** [comment]
> the above method is only used in dynamically linked case, how can i use this optimization in static linked case?

What static linked case? As far as I know, your graphics card drivers are always dynamically loaded, and as long as these symbols are exported somewhere in your executable, they will find it.

**Comment by smilexin** [comment]
@dkorpel  How quickly reply : ) thanks.  I staticly link glfw3.lib static lib in our windows OpenGL project, which finally packaged into a dll sdk ,  we should only provide my custom a single dll, so i should include static glfw3.lib. When I enable the glfw with GLFW_USE_HYBRID_HPG macro and build a static glfw3.dll, there is no effect. Thanks for your kindly help.

**Comment by dkorpel** [comment]
I don't know what you mean with a "static glfw3.dll" but as the documentation of GLFW_USE_HYBRID_HPG says:
> These symbols need to be exported by the EXE to be detected by the driver, so the override
will not work if GLFW is built as a DLL.

You can always just put the two symbols in the code of your project and you should be good.

**Comment by dkorpel** [comment]
I don't think your .dll can influence how your customer's executable loads the graphics drivers, so your customer needs to add the symbols in his project. If you provide an import library for your dll, maybe that .lib can contain the exported symbols, and maybe if you load OpenGL within your dll it will recognize the symbols exported in the dll, but I'm not sure. Maybe you can ask on StackOverfow and/or Nvidia/Amd forums.
