### ISSUE TITLE
On Linux Mint 19.02, when attempting to create a class for dynamic key reading for a game engine causes crash.

### ISSUE THREAD

**Issue by coderguy1777** [glfw/glfw#1550]
Basically, when using glfwGetKey() in a seperate bool method from a class meant to be a keyboard to read keys, what happens is that it causes the entire system to crash when the program is run for the window.

**Comment by intrigus** [comment]
Please have a look at https://github.com/glfw/glfw/blob/master/docs/CONTRIBUTING.md#reporting-a-bug and fill in the appropriate info.
