### ISSUE TITLE
Resizing window repositions it on MacOS

### ISSUE THREAD

**Issue by rokups** [glfw/glfw#1553]
If we resize a window on MacOS using `glfwSetWindowSize()` - window visually move down. Bottom of the window remains stationary. This is because MacOS positions windows from the bottom-left corner while glfw positions windows from the top-left corner. A workaround to this issue is to move window upwards by the difference of current and new window size. glfw does not do that when window is resized.

Here is workaround code:
```cpp
static void ImGui_ImplGlfw_SetWindowSize(ImGuiViewport* viewport, ImVec2 size)
{
    ImGuiViewportDataGlfw* data = (ImGuiViewportDataGlfw*)viewport->PlatformUserData;
#if __APPLE__
    // Windows are positioned by bottom-left corner on MacOS. ImGui windows are positioned by top-left corner. When we
    // change size of a window we must move it as well in order to create illusion of positioning by top-left corner.
    int x, y, width, height;
    glfwGetWindowPos(data->Window, &x, &y);
    glfwGetWindowSize(data->Window, &width, &height);
    glfwSetWindowPos(data->Window, x, y - height + size.y);
#endif
    glfwSetWindowSize(data->Window, (int)size.x, (int)size.y);
}
```

**Comment by elmindreda** [comment]
This should be fixed now with 7f02898264d6077738f0e8032f027eb7e252c90e. Thank you for reporting this! Please re-open the issue if the fix is incomplete.
