### ISSUE TITLE
Centos error: ‘for’ loop initial declarations are only allowed in C99 mode 

### ISSUE THREAD

**Issue by byungheon-jeong** [glfw/glfw#1560]
When building, I get the following error:

`/home/b1jeong/glfw/src/x11_init.c: In function ‘hasUsableInputMethodStyle’:
/home/b1jeong/glfw/src/x11_init.c:340:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (unsigned int i = 0;  i < styles->count_styles;  i++)
     ^
/home/b1jeong/glfw/src/x11_init.c:340:5: note: use option -std=c99 or -std=gnu99 to compile your code
/home/b1jeong/glfw/src/x11_init.c: In function ‘getSupportedAtom’:
/home/b1jeong/glfw/src/x11_init.c:361:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (unsigned int i = 0;  i < atomCount;  i++)
     ^
make[2]: *** [src/CMakeFiles/glfw.dir/x11_init.c.o] Error 1
make[1]: *** [src/CMakeFiles/glfw.dir/all] Error 2
make: *** [all] Error 2
`

My gcc version:
`(base) [b1jeong@k8s-u200-01 build]$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
`
My g++ version:
` g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR 
`

**Comment by tombsar** [comment]
Could you run `make VERBOSE=1` to see what flags are being passed to the compiler? Or `make -n` if that doesn't work.

**Comment by byungheon-jeong** [comment]
`(base) [b1jeong@k8s-u200-01 build]$ make VERBOSE=1
/usr/local/bin/cmake -S/home/b1jeong/glfw -B/home/b1jeong/glfw/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/bin/cmake -E cmake_progress_start /home/b1jeong/glfw/build/CMakeFiles /home/b1jeong/glfw/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory `/home/b1jeong/glfw/build'
make -f src/CMakeFiles/glfw.dir/build.make src/CMakeFiles/glfw.dir/depend
make[2]: Entering directory `/home/b1jeong/glfw/build'
cd /home/b1jeong/glfw/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/b1jeong/glfw /home/b1jeong/glfw/src /home/b1jeong/glfw/build /home/b1jeong/glfw/build/src /home/b1jeong/glfw/build/src/CMakeFiles/glfw.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/home/b1jeong/glfw/build'
make -f src/CMakeFiles/glfw.dir/build.make src/CMakeFiles/glfw.dir/build
make[2]: Entering directory `/home/b1jeong/glfw/build'
[  1%] Building C object src/CMakeFiles/glfw.dir/x11_init.c.o
cd /home/b1jeong/glfw/build/src && /bin/cc -D_GLFW_USE_CONFIG_H -I/home/b1jeong/glfw/include -I/home/b1jeong/glfw/src -I/home/b1jeong/glfw/build/src  -fPIC   -Wall -o CMakeFiles/glfw.dir/x11_init.c.o   -c /home/b1jeong/glfw/src/x11_init.c
`

**Comment by tombsar** [comment]
Thanks.

`/bin/cc -D_GLFW_USE_CONFIG_H -I/home/b1jeong/glfw/include -I/home/b1jeong/glfw/src -I/home/b1jeong/glfw/build/src -fPIC -Wall -o CMakeFiles/glfw.dir/x11_init.c.o -c /home/b1jeong/glfw/src/x11_init.c`

It looks as though CMake isn't specifying a C standard (e.g. `-std=c99`), so the compiler's default is being used (probably `gnu90` for your compiler, whereas it would be `gnu11` on more recent releases).

IMO we should definitely add a C standard to the build line to avoid this kind of issue. Can someone who speaks CMake look into that?

**Comment by gracicot** [comment]
@byungheon-jeong @tombsar I created a pull request to fix that, but I don't currently have the setup to test it. Can someone try my patch to see if everything works as it should? Thanks.
