### ISSUE TITLE
Do you want to change the name to VKFW?

### ISSUE THREAD

**Issue by cers000** [glfw/glfw#1565]
Vulkan Fromwork

**Comment by linkmauve** [comment]
No, thanks.

**Comment by RsPlayer** [comment]
LOL

**Comment by cers000** [comment]
why or why not

**Comment by Playermet** [comment]
Why we should consider to change the name? There is literally no reason to do so. Even worse, it would just broke library name recognition and mentions.

**Comment by cers000** [comment]
@Playermet Are we consider the new project VKFW?

**Comment by Playermet** [comment]
Erm, nope.

**Comment by elmindreda** [comment]
GLFW isn't really an OpenGL framework anymore but changing the name of an established project is a big undertaking, so perhaps at some point but definitely not now.

**Comment by elmindreda** [comment]
There is nothing wrong with @cers000's question and no reason to be rude to them. Please keep a civil tone here.
