### ISSUE TITLE
Typo in wiki: "Buffer swapping"

### ISSUE THREAD

**Issue by DesertCookie** [glfw/glfw#1571]
In the section [Buffer swapping](https://www.glfw.org/docs/latest/window_guide.html#buffer_swap) of the window guide, it is stated:

> With the function glfwSwapInterval it is possible to select the minimum number of monitor refreshes the driver wait should from the time glfwSwapBuffers was called before swapping the buffers

I suggest switching `wait` and `should`, to satisfy our inner OCD. Cheers.

**Comment by elmindreda** [comment]
Thank you!
