### ISSUE TITLE
glfwGetWindowAttrib( g_Window, GLFW_FOCUSED ) always return 0

### ISSUE THREAD

**Issue by fishingGrapes** [glfw/glfw#1573]
The method `glfwGetWindowAttrib( g_Window, GLFW_FOCUSED )` always return 0, even if the window is focused. this happens regardless of whether the Window is Fullscreen or not.

**Comment by tombsar** [comment]
To help us investigate the issue, could you please give your operating system (and window manager, if appropriate) and glfw version?

**Comment by fishingGrapes** [comment]
@tombsar I am on Windows 10 and the GLFW version is 3.4.

**Comment by elmindreda** [comment]
@fishingGrapes I cannot reproduce this on Windows 10 with current `master` and it shouldn't be affected by how you render. Not sure what would be causing this behavior.

If possible, please try a small program that only uses GLFW and see if that has the same issue. It shouldn't need to render anything, just print the window attribute.

**Comment by essial** [comment]
This is an issue. Windows 10 as well. I have a GYX1060 and a 144hz monitor with GSync enabled.

**Comment by fishingGrapes** [comment]
> This is an issue. Windows 10 as well. I have a GTX1060 and a 144hz monitor with GSync enabled.

I have a similar setup as well. GTX 1080 and a 144hz monitor with Gysnc enabled.

**Comment by essial** [comment]
Another guy who had the same issue had an ATI card, no GSync (maybe freesync?), but a 144hz monitor as well.

**Comment by ghuser404** [comment]
@fishingGrapes @essial This is probably because you're calling `glfwGetWindowAttrib` from the rendering thread. I just tried that and it behaves like you described. You must only call it from the main thread.

Quote from documentation:
>Thread safety
This function must only be called from the main thread.

**Comment by fishingGrapes** [comment]
@ghuser404  Thanks for the update!

**Comment by ghuser404** [comment]
@fishingGrapes Please see if it helps you and close the ticket if appropriate.
