### ISSUE TITLE
Make libGLESv2 library reference more generic

### ISSUE THREAD

**Issue by j-omega** [glfw/glfw#1577]
https://github.com/glfw/glfw/blob/d25248343e248337284dfbe5ecd1eddbd37ae66d/src/egl_context.c#L649

It would be good to changes this to `libGLESv2.so` to maintain compatibility with systems using libGLESv2.so.1.

**Comment by elmindreda** [comment]
That would fail on a lot of systems where it is the optional developer package for a library that provides the plain `.so` symlink.

Do you have a system where the library is named `libGLESv2.so.1`?

**Comment by j-omega** [comment]
We are developing for a TI AM3359 which uses a PowerVR SGX GPU. The OpenGL ES library provided by TI is `libGLESv2.so.1`.

https://git.ti.com/graphics/omap5-sgx-ddk-um-linux/trees/ti-img-sgx/thud/1.17.4948957/targetfs/ti335x/lib

This may be a more appropriate case for the use of `_GLFW_GLESV2_LIBRARY`.

**Comment by j-omega** [comment]
It appears that at one point, this was considered the standard ABI:
https://lists.freedesktop.org/archives/mesa-dev/2012-September/027295.html

**Comment by elmindreda** [comment]
TI seem to have updated the name to match the official ABI.
