### ISSUE TITLE
Current CMake build documentation leads to undefined references

### ISSUE THREAD

**Issue by lukect** [glfw/glfw#1580]
OS: **Ubuntu 19.04**
CMake: **3.15**

Page: https://www.glfw.org/docs/latest/build_guide.html

Documentation states to use the `OPENGL_gl_LIBRARY` cache variable. However, this appears to be `null` (leads to undefined references during compilation) when using **CMake 3.15** on **Ubuntu 19.04**. Using the `OPENGL_LIBRARIES` result variable stated [here in the cmake.org documentation](https://cmake.org/cmake/help/latest/module/FindOpenGL.html) instead does work.

**Doesn't work (current documentation)** `target_link_libraries(myapp ${OPENGL_gl_LIBRARY})`
**Works** `target_link_libraries(myapp ${OPENGL_LIBRARIES})`

I believe this will likely be an issue on other distributions aswell.

**Comment by elmindreda** [comment]
Thank you, will fix!

**Comment by elmindreda** [comment]
This is somewhat better now with d973acc123826666ecc9e6fd475682e3d84c54a6. Thank you!
