### ISSUE TITLE
VERSION_GREATER_EQUAL not available in cmake < v3.7

### ISSUE THREAD

**Issue by papr** [glfw/glfw#1584]
The following line causes cmake to fail when using cmake < v3.7 since [`VERSION_GREATER_EQUAL` was introduced in came v3.7](https://cmake.org/cmake/help/v3.7/release/3.7.html#commands).

https://github.com/glfw/glfw/blob/master/src/CMakeLists.txt#L103

> `if (${CMAKE_VERSION} VERSION_GREATER_EQUAL "3.1.0")`

**Comment by infobeisel** [comment]
for me, it succeeded when i replaced it with VERSION_GREATER  (instead of VERSION_GREATER_EQUAL) , using cmake 3.5.1

**Comment by tombsar** [comment]
+1 Sorry for not testing this sooner. Does not build with cmake 3.6.2.

With @infobeisel 's change the main library builds ok, but the tests still do not (glfwinfo.c at least contains C99-isms).

**Comment by elmindreda** [comment]
Thank you for the fix!
