### ISSUE TITLE
window size exceeding monitor maximum resolution with GLFW_SCALE_TO_MONITOR 

### ISSUE THREAD

**Issue by Carandiru0** [glfw/glfw#1586]
I have my windows DPI set to 125%
using the window hint GLFW_SCALE_TO_MONITOR 
and using an initial resolution of my monitor's max (1920x1080) as parameters to glfwCreateWindow
the resulting window size & frame buffer size is scaled beyond the displayable maximum resolution of my monitor. This is while creating a "borderless" window.

workaround I'm using atm:
`point2D_t window_size;
	glfwGetFramebufferSize(glfwwindow, &window_size.x, &window_size.y);

	// bugfix, if window created is larger than maximum monitor resolution, disable hint GLFW_SCALE_TO_MONITOR and recreate window!
	if (window_size.x > max_resolution.x || window_size.y > max_resolution.y) {
		glfwDestroyWindow(glfwwindow); glfwwindow = nullptr;
		glfwWindowHint(GLFW_SCALE_TO_MONITOR, GLFW_FALSE);

		glfwwindow = glfwCreateWindow(resolution.x, resolution.y, Globals::TITLE, monitor, nullptr);
		// refresh window size
		glfwGetFramebufferSize(glfwwindow, &window_size.x, &window_size.y);
	}`

**Comment by elmindreda** [comment]
Are you trying to create a window that covers a whole monitor? In that case GLFW_SCALE_TO_MONITOR isn't appropriate. Perhaps a [windowed fullscreen window](https://www.glfw.org/docs/latest/window.html#window_windowed_full_screen) would be better.

**Comment by Carandiru0** [comment]
I've put in support for fullscreen borderless windows and native fullscreen with a toggle in an ini file. So both are working. I just noticed this happening while working on that implementation for my application.

**Comment by elmindreda** [comment]
If I understand this correctly then it is working as intended. You are creating a window intended to cover the whole monitor but are not (the first time) passing in a monitor, so GLFW treats it as a non-fullscreen window and resizes it.

**Comment by ghuser404** [comment]
A better way to do it is to create a hidden window, then resize and show it. AFAIK, while `glfwCreateWindow` is affected by `GLFW_SCALE_TO_MONITOR` - `glfwSetWindowSize` is not.

**Comment by elmindreda** [comment]
@ghuser404 Yes, that should work.
