### ISSUE TITLE
Can't input Chinese

### ISSUE THREAD

**Issue by ruanwenfeng** [glfw/glfw#1587]
after call Xutf8LookupString, status value is  1
glfw-version: 3.3
file: x11_window.c 
line: 1277

**Comment by orange451** [comment]
Chinese input is working for me. Make sure you're using a font that supports writing Chinese glyphs:
![image](https://user-images.githubusercontent.com/5247778/68727653-0b87c500-0593-11ea-8518-708d4ec58430.png)

**Comment by ruanwenfeng** [comment]
@orange451 i am sure. it work on win10.
![image](https://user-images.githubusercontent.com/27943586/68728190-93a4b380-0601-11ea-9795-ec74f6576a8e.png)

**Comment by elmindreda** [comment]
Thank you for reporting this. It happens on X11 when the character encoding part of the application locale is left at the default value, which is incredibly unintuitive. 4381b86b6ba63598de82c3f05824dc00a2b3ec59 enables the workaround for this for all cases.
