### ISSUE TITLE
Same GLFWwindow value returned by glfwCreateWindow()

### ISSUE THREAD

**Issue by thewoz** [glfw/glfw#1594]
Hi I create a window with glfwCreateWindow() and I get the GLFWwindow * as return value of the function. Then I destroy the window and I create a new window. Some time the second window have the save GLFWwindow * value of the first one. There is a way to check if a windows is different form a previous one?

thanks

**Comment by thewoz** [comment]
here the code to reproduce:

```
  glfwInit();
  
  glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
  glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 1);
  glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
  glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE); 
  
  for(size_t i=0; i<100; ++i) {
  
    GLFWwindow * window = glfwCreateWindow(800, 900, "title", NULL, NULL);
  
    printf("%p\n", window);
    
    glfwDestroyWindow(window);
    
  }

```

here  a sample of the output

0x10fa447d0
0x10d7cc6a0
**0x10d6190c0
0x10d6190c0**
0x10f920ea0
0x10d22c2a0
0x10fd257d0
0x10d61ad00
0x10d7d0090
**0x10d22c2a0
0x10d22c2a0**

**Comment by intrigus** [comment]
What problem do you actually want to solve?
It seems to be an XY-problem.

**Comment by thewoz** [comment]
sorry ,I may have expressed myself badly.

I have differente objects that need to set on the GPU (after the creation of a context) the shader vertex array etc.

My problem is that I create (open and close) different context i.e. different widows but I use the same objects. Thus for renizatinazte the objects in the context I check the pointer of the GLFWwindow.
If the pointer is changed I reinitialize all in GPU. 
Since some time the GLFWwindow value is the same for differente context I get an error.

here just an example

```
  glCube cube;

  GLFWwindow * oldWindow = NULL;

  for(size_t i=0; i<100; ++i) {
  
    GLFWwindow * window = glfwCreateWindow(800, 900, "title", NULL, NULL);
  
     if(window != oldWindow) {
        cube.loadShader();
       cube.createVertexArray();
       window = oldWindow;
    }

    cube.setUniform();

    cube.render();
    
    glfwDestroyWindow(window);
    
  }
```

when the new window will have the same address on the previous destroyed one the setUniform() will throw an error since the command inside the if has not performed.

So my question is how I can check is the windows (context) is a new one since the address of the GLFWwindow can be the same for the same run for different windows?

**Comment by ghuser404** [comment]
You should use some kind of messaging/notification system in your program, where code that creates windows will notify other code that relies on it. This is not a GLFW problem.

**Comment by CobbsLab** [comment]
Ok fair enough.
I ask just to know if there is some function or some propriety in GLFW that give me a unique id for each windows.
