### ISSUE TITLE
Xbox controllers on Windows 10 buttons are incorrectly mapped

### ISSUE THREAD

**Issue by Perksey** [glfw/glfw#1599]
Hi! I'm the maintainer of Silk.NET. We're currently experiencing a bug with Xbox controllers, where the buttons are returned incorrectly by GLFW. This could be because Windows 10 hijacks the home button, but:
- the home/guide button is never reported as pressed
- any buttons that are after GUIDE in the button array are offset by -1 (i.e. LEFT_STICK (index 9) is reported as GUIDE (index 8), RIGHT_STICK as LEFT_STICK etc)

To reproduce:
- Use GLFW 3.3
- Extract & run this sample: https://filebin.net/9w738tei2i54dqau
- Connect a Xbox Controller
- Press Left Stick, you will notice in the logs that this will appear as Home (which is our name for the Guide button).
- Press Right Stick, you will notice in the logs that this will appear as Left Stick

Sample source: https://github.com/Ultz/Silk.NET/tree/master/examples/InputTest

We have investigated thoroughly and have deduced that this is a problem with GLFW, not Silk.NET.

**Comment by Perksey** [comment]
cc @mikart143

**Comment by Perksey** [comment]
Any news on this?

**Comment by elmindreda** [comment]
Thank you for your patience. Which model Xbox controller are you using?

**Comment by Perksey** [comment]
I’m using a Day One 2013 controller with all the latest updates installed on it. I’m also using the latest version of Windows 10 and have the Xbox (Beta) app installed.

**Comment by Perksey** [comment]
Also did you still need that sample program as I noticed that the download link expired?

**Comment by elmindreda** [comment]
Thank you for the quick reply! No need to update the download link, though if you have access to the controller it would be useful to know what GUID that GLFW says it has on Windows.

**Comment by elmindreda** [comment]
Cannot reproduce this with an Xbox One controller on Windows 10 and the Xbox beta app.

**Comment by Perksey** [comment]
Are you using the sample I provided? Also I'll get the GUID now...

**Comment by Perksey** [comment]
The GUID is `78696e70757401000000000000000000`

**Comment by elmindreda** [comment]
Thank you! No, I'm using the `joysticks` test from GLFW.

**Comment by Perksey** [comment]
Ah okay. I've had a deeper look and it looks like glfwGetJoystickButtons is returning a button count of `14` instead of `15` as expected, implying that the Home/Guide button isn't included in the button array.

Here's the repackaged & reuploaded test application I'm using: https://filebin.net/3tj6d9omkriatfi5

**Comment by aloucks** [comment]
Are you using [glfwGetGamepadState](https://www.glfw.org/docs/latest/group__input.html#gadccddea8bce6113fa459de379ddaf051) and reading the buttons from [GLFWgamepadstate](https://www.glfw.org/docs/latest/structGLFWgamepadstate.html)?

I'm also on Windows 10 with the same controller and `glfwGetGamepadState` reports the button states as expected. The buttons returned by `glfwGetJoystickButtons` may not be mapped with the same indexes.

**Comment by Perksey** [comment]
Ah no we were using the joystick APIs alone as we need to support generic
joysticks - not just gamepads.

**Comment by Perksey** [comment]
Ah just seen your edit, will implement the suggested changes shortly. Will leave this open for the time being.

**Comment by Perksey** [comment]
Closing as this has been solved.
