### ISSUE TITLE
Maximizing a window to specific monitor

### ISSUE THREAD

**Issue by PokeMMO** [glfw/glfw#1600]
Calls to glfwSetWindowPos on Windows do not position the window to include the offset required for the title bar. This is not limited to maximized windows and also occurs to windowed windows.

This seems like it is correct according to glfw documentation.
https://github.com/glfw/glfw/blob/2c519709be0dacc7af2908982a7ab80b889a8126/docs/window.dox#L800-L805

Trying to work around by glfwGetWindowPosition to obtain the current x/y position and offsetting the position before calling glfwSetWindowPos results in slightly incorrect results.

If this is intended behavior, is there a proper way to request a window be maximized to a specific monitor?

This behavior was observed using latest Lwjgl3's glfw release, glfwGetVersionString: 3.4.0

**Comment by elmindreda** [comment]
Do you want to make a window full screen on a specific monitor but without a video mode switch?

If so I recommend setting it with `glfwSetWindowMonitor` as in the second example [here](https://www.glfw.org/docs/latest/window_guide.html#window_windowed_full_screen).

**Comment by PokeMMO** [comment]
> Do you want to make a window full screen on a specific monitor but without a video mode switch?

No, I'm trying to make a new maximized window with title bar/decorations on a specific monitor.

**Comment by elmindreda** [comment]
Oh, that makes sense. There's no single function for creating a window that's maximized on a specific monitor, but it can be done. Here is one example of how, by centering the window in the monitor's workarea.

```c
glfwWindowHint(GLFW_VISIBLE, 0);
GLFWwindow* window = glfwCreateWindow(window_width, window_height, "Title", NULL, NULL);
glfwGetMonitorWorkarea(monitor, &area_x, &area_y, &area_width, &area_height);
glfwSetWindowPos(window,
    area_x + area_width / 2 - window_width / 2,
    area_y + area_height / 2 - window_height / 2);
glfwMaximizeWindow(window);
glfwShowWindow(window);
```

**Comment by PokeMMO** [comment]
Thanks!
