### ISSUE TITLE
Setting GLFW_LOCK_KEY_MODS Does not work

### ISSUE THREAD

**Issue by jmher019** [glfw/glfw#1606]
I am trying to detect the state of caps lock and num lock for each key callback event.

I tried calling:

```
glfwSetInputMode(window, GLFW_LOCK_KEY_MODS, GLFW_TRUE);
```

Then in my callback for glfwSetKeyCallback I have the following code to check the state of caps lock and num lock:

```
bool capsLock = static_cast<bool>(mods & GLFW_MOD_CAPS_LOCK);
bool numLock = static_cast<bool>(mods & GLFW_MOD_NUM_LOCK);
```

I tried inspecting the value of mods in the callback function in the debugger with either caps or num lock on, but it is always set to 0.

Is there any other settings I need to turn on in order to start querying the caps or num lock states?

I am testing on an Alienware AW15R3 laptop running Windows and using OpenGL. (In case either of those matter)

**Comment by elmindreda** [comment]
That's odd. Cannot reproduce this. Does GLFW report any error? What is your GLFW version string?

**Comment by jmher019** [comment]
> That's odd. Cannot reproduce this. Does GLFW report any error? What is your GLFW version string?

My GLFW version string is:

```
3.2.1 Win32 WGL EGL VisualC DLL
```

**Comment by elmindreda** [comment]
Ah, that's why. You seem to have a 3.3 header but a 3.2.1 library. While `glfwSetInputMode` is from 3.0, the `GLFW_LOCK_KEY_MODS` mode was only added in GLFW 3.3.

**Comment by jmher019** [comment]
So I tried grabbing the binaries from the release tagged 3.3 and am still getting the same version string. Is there a mistake somehow?

**Comment by jmher019** [comment]
I think I should mention that I am trying to use the dll and lib for Visual Studio 2019. I tried downloading them directly from the website and I still get the same version string.

**Comment by jmher019** [comment]
I ended up building the binaries myself from the project but I would check the lib files you have on your downloads for Visual Studio 2019.

**Comment by elmindreda** [comment]
All 32- and 64-bit Windows library binaries for 3.3 contain the string `3.3.0 Win32 WGL`. None of them contain `3.2.1 Win32 WGL`. Checked just now with fresh downloads. Your project file is likely using a different library binary than the one from the 3.3 archive.

**Comment by jmher019** [comment]
Sorry it took so long to get back to this. I was able to test and verify the binaries are in fact working for me. Thank you so much for your assistance.

**Comment by elmindreda** [comment]
Thank you for the follow-up!
