### ISSUE TITLE
Keys can get stuck in pressed state

### ISSUE THREAD

**Issue by rokups** [glfw/glfw#1622]
## Steps
1. Open GLFW application and have it's window focused.
2. Press GLFW_KEY_LEFT_SUPER+v

## Result
Builtin windows clipboard utility pops up and GLFW_KEY_LEFT_SUPER is not reported as released even though GetKeyState(VK_LWIN) does report key as released.

## Expected result
GLFW should report GLFW_KEY_LEFT_SUPER as released.

## Cause
Win32 does not send WM_KEYUP message if window is not focused.

---

Originally reported at: https://github.com/ocornut/imgui/issues/2976

**Comment by elmindreda** [comment]
Thank you for reporting this! If possible, please test if the `win32-key-scancode-fixes` branch resolves this.

**Comment by rokups** [comment]
Fix confirmed. Thank you very much!
