### ISSUE TITLE
Key presses with unset scancode get lost

### ISSUE THREAD

**Issue by rokups** [glfw/glfw#1623]
Windows clipboard (Win+v) sends windows messages for CTRL+v with no scancode set. GLFW still catches CTRL press, but only because it has special case handling based on keycode. V press is lost because scancode is used to translate key press to gflw key.

**Comment by elmindreda** [comment]
Thank you for reporting this! If possible, please test if the `win32-key-scancode-fixes` branch resolves this.

**Comment by rokups** [comment]
This issue is also fixed. Thank you very much!
