### ISSUE TITLE
Support custom memory allocators

### ISSUE THREAD

**Issue by raysan5** [glfw/glfw#1628]
I checked for this feature and I saw it was already [discussed in the past](https://discourse.glfw.org/t/custom-memory-allocator/1352) and there is also an open PR about it: https://github.com/glfw/glfw/pull/544

There is also one related issue: https://github.com/glfw/glfw/issues/478

All proposals are intended for custom allocators defined at runtime but it could be nice to be able to just define custom allocators on compilation, similar to what other libraries like stb do:

```c
#ifndef GLFW_CALLOC
    #define GLFW_CALLOC(sz)  calloc(sz)
#endif
#ifndef GLFW_FREE
    #define GLFW_FREE(p)     free(p)
#endif
```

This way custom allocators could be defined by user on library compilation. 

Probably out-of-scope of GLFW, but this approximation is also useful if `stblib` (containing `malloc()`/`free()`) is replaced by a custom implementation, for example on embedded devices.

This request is related to raylib issue https://github.com/raysan5/raylib/issues/1074, it's a low priority feature.

**Comment by elmindreda** [comment]
Thank you for your feedback and you patience. A pull request for proper pluggable heap allocator support has finally been added over at #1947.

**Comment by raysan5** [comment]
@elmindreda Nice! Thank you very much for implementing this feature! :D
