### ISSUE TITLE
bad Emoji input on macOS

### ISSUE THREAD

**Issue by zhuah** [glfw/glfw#1635]
I'm using IME to input some emoji characters, but the screen shows two squares.
after dig into glfw source code, i just found that there may be a bug at https://github.com/glfw/glfw/blob/master/src/cocoa_window.m#L726-L734, since NSString is stored as UTF-16 encoding.

And i found a solution at https://stackoverflow.com/questions/20537706/how-to-handle-32bit-unicode-characters-in-a-nsstring, it may helps, thanks.

**Comment by zhuah** [comment]
I haven't tested on Linux and Windows yet,  so i don't know if there are same problem.

**Comment by elmindreda** [comment]
Thank you for reporting this! It should be fixed now with ad9eb768c9518dbe94232e5201d318d512ad9beb, and on Windows with 6ce207039240a63120a91ee4ba4d39bd0a3ef8c8.
