### ISSUE TITLE
IME(fcitx) doesn't works on Linux(both Mint and Ubuntu)

### ISSUE THREAD

**Issue by zhuah** [glfw/glfw#1636]
I typed some Chinese characters with fcitx, then i press Space to commit them to textbox, nothing happens except IME bar disappears.  
It works well if i switch to English mode.

**Comment by zhuah** [comment]
https://github.com/glfw/glfw/blob/master/src/x11_init.c#L941-L949

I added a `#else` code block,
```C
#else
    setlocale(LC_CTYPE, "");
```
then i can get right input characters from IME(fcitx).

i decide not to open a PR since i'm not familiar with X11 and i don't know if it's right or not.
i'm glad if it get to be fixed, thanks.

**Comment by elmindreda** [comment]
Thank you for verifying this is also the case on fcitx! This should be fixed now with 4381b86b6ba63598de82c3f05824dc00a2b3ec59.

**Comment by wujilingfeng** [comment]
> https://github.com/glfw/glfw/blob/master/src/x11_init.c#L941-L949
> 
> I added a `#else` code block,
> 
> ```c
> #else
>     setlocale(LC_CTYPE, "");
> ```
> 
> then i can get right input characters from IME(fcitx).
> 
> i decide not to open a PR since i'm not familiar with X11 and i don't know if it's right or not.
> i'm glad if it get to be fixed, thanks.
Hi,I want to know how to get a Chinese characters through glfw?
