### ISSUE TITLE
Proper window decorations via libdecor

### ISSUE THREAD

**Issue by christianrauch** [glfw/glfw#1639]
I am working on `libdecoration`, a project originated by Jonas Ådahl. I implemented a ["proper" title bar](https://gitlab.gnome.org/jadahl/libdecoration/merge_requests/2), which is still under review for merging this upstream.

I was wondering if there is interest in using this library for GLFW to implement Wayland client-side window decorations with title, min/max/close buttons and shadows to resizing windows:
![libdecoration_cairo](https://user-images.githubusercontent.com/8573621/73985965-6cc1f900-4934-11ea-8d96-4e5821450962.png)
and replace the older `viewporter`-based decorations that are missing buttons and shadows.

**Comment by elmindreda** [comment]
Yes, I definitely want to add libdecor support as soon as possible and considering GNOME's lack of server-side decorations, this is a blocking issue for a 3.4 release of any scope.

**Comment by flysand7** [comment]
The documentation for this option are missing from HTML docs. Maybe they should be added?
