### ISSUE TITLE
menubar not clickable on macOS Catalina until it lost and regained focus.

### ISSUE THREAD

**Issue by zhuah** [glfw/glfw#1648]
It may related to #1165 and  this [commit](https://github.com/glfw/glfw/commit/9aa15aa710ff5adbdbccb124da96864df84b2479)

**Comment by andydotxyz** [comment]
This is an issue that I was hoping to solve for Fyne as well (fyne-io/fyne#505) but I can't even figure how to begin debugging.

**Comment by elmindreda** [comment]
If possible, please bundle your macOS GUI applications.

That said, this is clearly a bug and hopefully it can be fixed.

**Comment by andydotxyz** [comment]
I completely agree. This is really only a developer facing issue. But I still wnated to try and help fix it ;)
