### ISSUE TITLE
Cocoa pre-window-creation event processing fix causes glfwPostEmptyEvent to crash program when called from non-main thread

### ISSUE THREAD

**Issue by dmitshur** [glfw/glfw#1649]
Issue #1543 was resolved by commit 6e6805000ac7ddf39c8c5f6be3e877770cba5083.

Commit 6e6805000ac7ddf39c8c5f6be3e877770cba5083 adds the following code to `_glfwPlatformPostEmptyEvent`:

```diff
+    if (!_glfw.ns.finishedLaunching)
+        [NSApp run];
```

I'm not sure if this is safe to do.

`glfwPostEmptyEvent` is [documented](https://www.glfw.org/docs/latest/group__window.html#gab5997a25187e9fd5c6f2ecbbc8dfd7e9) to be safe to call from any thread. Documentation for `NSApp.run` itself doesn't say anything about what thread it may be run on, but in practice, it seems to call another method, which is not safe to call on non-main thread, and throws NSInternalInconsistencyException.

Consider the following trivial Go program (sorry, I don't remember how to write threaded code in C by now) that uses GLFW 3.3.2 and calls `glfwPostEmptyEvent` on non-main thread:

```Go
package main

import (
	"log"
	"runtime"

	"github.com/go-gl/glfw/v3.3/glfw"
)

func init() { runtime.LockOSThread() } // arrange for main function to run main thread

func main() {
	err := glfw.Init()
	if err != nil {
		log.Fatalln(err)
	}
	defer glfw.Terminate()

	go glfw.PostEmptyEvent() // call PostEmptyEvent in non-main thread

	select {} // wait forever
}
```

It was tested on macOS 10.15.3 with Xcode 11.3.1.

Before commit 6e6805000ac7ddf39c8c5f6be3e877770cba5083, it works fine.

After commit 6e6805000ac7ddf39c8c5f6be3e877770cba5083, it crashes with:

```
$ go run .                                     
2020-02-22 13:50:10.100 m[22196:92162] *** Assertion failure in +[NSUndoManager _endTopLevelGroupings], /BuildRoot/Library/Caches/com.apple.xbs/Sources/Foundation/Foundation-1674.114/Foundation/Misc.subproj/NSUndoManager.m:363
2020-02-22 13:50:10.100 m[22196:92162] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '+[NSUndoManager(NSInternal) _endTopLevelGroupings] is only safe to invoke on the main thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff394778ab __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6f731805 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff394a0d10 +[NSException raise:format:arguments:] + 88
	3   Foundation                          0x00007fff3bb99241 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   Foundation                          0x00007fff3bad7d5e +[NSUndoManager(NSPrivate) _endTopLevelGroupings] + 440
	5   AppKit                              0x00007fff365b016c -[NSApplication run] + 864
	6   m                                   0x00000000040b0046 _glfwPlatformPostEmptyEvent + 54
	7   m                                   0x000000000405cc90 runtime.asmcgocall + 112
)
libc++abi.dylib: terminating with uncaught exception of type NSException
SIGABRT: abort
PC=0x7fff70be67fa m=3 sigcode=0
```

This may be somewhat related to #1588.

/cc @elmindreda

**Comment by elmindreda** [comment]
Hi @dmitshur! You're right; it's not safe to do. 6e6805000ac7ddf39c8c5f6be3e877770cba5083 was the least bad fix I could come up with without introducing a behavior change.

The bug should be fixed properly now with 1e7dfec89ac85fc5323261158d00cc7ef5a48cf2, though because it changes the existing behavior for command-line programs I'm not sure whether or not it belongs in the `3.3-stable` branch. 

> sorry, I don't remember how to write threaded code in C by now

No worries! Go made for a clearer example than the equivalent C11 would have been. Thank you also for remembering #1588!
