### ISSUE TITLE
Input Guide Documentation 

### ISSUE THREAD

**Issue by ForeverZer0** [glfw/glfw#1650]
For some reason or another, the extremely popular [SDL_GameControllerDB](https://github.com/gabomdq/SDL_GameControllerDB) was taken down due to some DCMA issues.

The [complaint](https://github.com/github/dmca/blob/master/2020/02/2020-02-19-SDL-GameController.md) seems to indicate that re-instating the copyright notice of some of the files would be sufficient for restoring the repo, but you may want to keep on an eye on the issue in case it does not. Currently the link in the GLFW documentation still points to the page, which is currently not a viable solution for gamepad mappings.

As a minor suggestion if it the GLFW team agrees, the [SDL2 Gamepad Tool](http://www.generalarcade.com/gamepadtool/) might be worth a link in the docs, and runs on all the major platforms GLFW is supported on.

**EDIT:**
The author of SDL_GameControllerDB made a clone repo [here](https://github.com/gabomdq/gamecontrollerdb).

**Comment by tombsar** [comment]
It looks as though the repository issue has been resolved:

> The repo is now back online, so please head over there for any updates.

SDL2 Gamepad Tool looks interesting.
