### ISSUE TITLE
Vulkan example crash on any window move/resize event. 

### ISSUE THREAD

**Issue by blackball** [glfw/glfw#1651]
Hi, 

I am using the latest master (03453246464cdd414c2f76d4a2569d2d5511870b). For vulkan, I am using mesa-vulkan-driver for debian 10. 

cmake and make build the example smoothly. When I ran the example and tried to move/resize the glfw window, it crashed, with following error messages: 
```
VkResult -1000001004
Aborted
```

Any idea ?

**Comment by jpbruyere** [comment]
ErrorOutOfDateKHR may be returned by vkAcquireNextImageKHR if swapchain configuration has changed (sizing or other..). You have to check for this error after acquire and recreate your swapchain if thrown.

**Comment by blackball** [comment]
It's fixed. Thanks!
