### ISSUE TITLE
Homebrew installation

### ISSUE THREAD

**Issue by militaryCoder** [glfw/glfw#1652]
I'm trying to build and install glfw3 under MacOS High Sierra through Homebrew and as far as I know, the `libglfw3.a` should be installed during library building. It should be placed in `/usr/local/lib`. Well, installation completes successfully.
After that, I'm trying to build next project which uses libglfw3 with CMake but it says that I haven't got `libglfw3.a` installed. I've searched for the missing file in `/usr/local/lib` and found pretty nothing.
Maybe I forget to provide installation flags or something.
If you need, I can send installation logs or something like that.

**Comment by ByunghoonKim** [comment]
`brew install glfw` installs the shared library `libglfw.dylib` in `/usr/local/Cellar/glfw/3.3.2/lib` unless you have changed the global setting of Homebrew. It will not install the static library `libglfw.a`(or `libglfw3.a`) for you; there is no installation flag for it at the moment.

If using the shared library is fine with you, please consult [Building applications](https://www.glfw.org/docs/latest/build_guide.html). If you must use the static library for some reason, you have to install glfw manually either by cloning the current GitHub repository or downloading the .zip file from [glfw.org](https://www.glfw.org), and then compile it yourself.

**Comment by militaryCoder** [comment]
Thanks for help. I tried to install library manually and finally got static archive.

**Comment by tombsar** [comment]
Can this issue be closed?

**Comment by militaryCoder** [comment]
@tombsar, surely.
