### ISSUE TITLE
Outdated linmath.h

### ISSUE THREAD

**Issue by peko** [glfw/glfw#1653]
Seems like the `deps/linmath.h` library is quite outdated and contains bugs, at least at [quat_mul_vec3](https://github.com/glfw/glfw/blob/6aca3e99f03617df1dd9081f20bd5408baf2a5d6/deps/linmath.h#L494) function. This bug was fixed in the original repository back in 2015 https://github.com/datenwolf/linmath.h/commit/de72a69abaffbf4a0861018727e10befb6cec7ff

**Comment by tombsar** [comment]
Just noting that linmath.h is only used in the glfw examples and tests not the core library, so this isn't a show-stopper. Should still be updated imo.

**Comment by elmindreda** [comment]
Updated, with slight modifications, with 350ba73267271d71984ad69af1e006f35ded1078. Thanks!
