### ISSUE TITLE
Documentation about OpenGL::GL

### ISSUE THREAD

**Issue by ghuser404** [glfw/glfw#1658]
It says "above", but it's below.
>If OpenGL is found, the OpenGL::GL target is added to your project, containing library and include directory paths. Link against this like above.
>`target_link_libraries(myapp OpenGL::GL)`

**Comment by elmindreda** [comment]
Thank you!

**Comment by elmindreda** [comment]
I was trying to say "like we did with the `glfw` target above" but yeah, it didn't work at all.

**Comment by elmindreda** [comment]
This should hopefully be improved somewhat now with 9516df52a4745a67f4e1d58d3de32c74b8c33ecf.
