### ISSUE TITLE
fixed phantom keys but removed simultaneous keys

### ISSUE THREAD

**Issue by basil-underscore** [glfw/glfw#1663]
Take a look on https://github.com/glfw/glfw/commit/4ff66a7818e3eaa5362c828a18220b12f1cd9bc8

checking `lastKeyTime < time` is ok - **if** we test `lastkey == key`, otherwise we discard other keys pressed simultaneous.

Pressing multiple keys at the same time is a basic feature which is missing due to this.

Is it time to remove that hack and let the user deal with it ? 

Is it better to not use IM at all ?

cheers.

**Comment by basil-underscore** [comment]
related to https://github.com/glfw/glfw/issues/1112

**Comment by elmindreda** [comment]
Thank you for reporting this. It should be mostly fixed now with 9a3664b4a992a5a9b669179098542b0f882dece7.
