### ISSUE TITLE
Fullscreen mode high usage cpu core 100%

### ISSUE THREAD

**Issue by Belvarm** [glfw/glfw#1669]
Hello. With Glfw 3.3.2 i have in fullscreen mode high usage cpu one core 100%. And not reproduced problem when windowed fullscreen.
About environment:
GPU: gtx 1060.
CPU: i5-4690
OS: Windows 7.
use: x86_64-w64-mingw32 9.3.0
opengl: glad

code on which me reproduce issue:

```
#include <iostream>
#include <glad/glad.h>
#include <GLFW/glfw3.h>

void key_callback(GLFWwindow* window, int key, int scancode, int action, int mode);

int main()
{
    std::cout << "Starting GLFW context, OpenGL 3.3" << std::endl;
    glfwInit();
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
    glfwWindowHint(GLFW_RESIZABLE, GL_FALSE);
    glfwWindowHint(GLFW_DECORATED, GL_FALSE);

    GLFWmonitor* monitor = glfwGetPrimaryMonitor();
    const GLFWvidmode* mode = glfwGetVideoMode(monitor);
    glfwWindowHint(GLFW_RED_BITS, mode->redBits);
    glfwWindowHint(GLFW_GREEN_BITS, mode->greenBits);
    glfwWindowHint(GLFW_BLUE_BITS, mode->blueBits);
    glfwWindowHint(GLFW_REFRESH_RATE, mode->refreshRate);

    // Create window with graphics context
    GLFWwindow* window = glfwCreateWindow(mode->width, mode->height, "example", monitor, NULL);
    if (window == NULL)
    {
        std::cout << "Failed to create GLFW window" << std::endl;
        glfwTerminate();
        return -1;
    }
    glfwMakeContextCurrent(window);

    glfwSetKeyCallback(window, key_callback);
    if (!gladLoadGLLoader((GLADloadproc) glfwGetProcAddress))
    {
        std::cout << "Failed to initialize OpenGL context" << std::endl;
        return -1;
    }
    glfwSwapInterval(1);

    glViewport(0, 0, mode->width, mode->height);
    while (!glfwWindowShouldClose(window))
    {
        glfwPollEvents();

        glClearColor(0.2f, 0.3f, 0.3f, 1.0f);
        glClear(GL_COLOR_BUFFER_BIT);

        glfwSwapBuffers(window);
    }

    glfwDestroyWindow(window);
    glfwTerminate();
    return 0;
}

void key_callback(GLFWwindow* window, int key, int scancode, int action, int mode)
{
    std::cout << key << std::endl;
    if (key == GLFW_KEY_ESCAPE && action == GLFW_PRESS)
        glfwSetWindowShouldClose(window, GL_TRUE);
}
```
Creating window with null param monitor not high load cpu.
Any ideas? All thanks.

**Comment by tombsar** [comment]
Likely this behavious comes from your graphics driver. Please check if there is a newer version to install, and also that you don't have it configured to force vsync off for 3D applications (I believe that's a setting in Nvidia Control Panel).

You could also verify what framerate you are rendering at by adding some timing to your program. If vsync is off and you are rendering at 1000+fps, that would explain the high CPU load.

Also not that Windows 7 is now officially end-of-life, so will no longer receive bug fixes from Microsoft. I don't know glfw's policy on legacy support, though.

**Comment by Belvarm** [comment]
Thanks for answer. I was check driver version, i have last version.
Vsync enabled. i have 60 fps and average frame duration 16.666 ms. but fullscreen have 100% cpu one core usage, are windowed mode issue not reproduce.

**Comment by Belvarm** [comment]
Really video driver problem, i could fix using hint 'GLFW_REFRESH_RATE' with set target fps and disable vsync in glfw, but not disabled in nvidia control panel. In this case I have an acceptable level cpu usage and stable 60 fps.
