### ISSUE TITLE
opensuse/sl77: less than fullscreen

### ISSUE THREAD

**Issue by fastrgv** [glfw/glfw#1670]
date: 12april2020
version glfw v3.3.2 (and 3.3.1)
OS: OpenSuse & Scientific Linux version 7.7 (from redhat)
DisplayMgr: gnome
ErrorMsgs: none
Problem:
While running an app in fullscreen...
Actual Screensize is 1920x1080 but glfw displays window height
of 981 rather than 1080. Reproduceable every time.

other note:  runs perfectly on Windows, Mac/OSX, and Linux Mint.
See following addenda...

Thx,
fastrgv@gmail.com

**Comment by fastrgv** [comment]
Additional data:
.) same problem on OpenSuse and CentOS.
.) a hint of glfw_decorated = gl_false SHOULD not affect a fullscreen window,
BUT, in fact, it increases the height from 981/1080 to 1018/1080...
better but not a fix.  However this might signal that size is NOT fullscreen.

**Comment by elmindreda** [comment]
It could be that the window hasn't reached its final position and size before the program you linked queries it. It can take a little while (milliseconds) for the window manager to finish.

If the window size is wrong even with a program that sticks around and processes events that then that could be a bug in GLFW.

**Comment by fastrgv** [comment]
Yes, I was aware that X11 acts asynchronously...
The full programs that first exhibited this behavior are OpenGL games that I wrote where the odd size persisted indefinitely [after many events].  My short example is merely the most minimal that I could think of.  I have variations of that minimal program with a glfwWaitEvent (looking for a keystroke, for example) that still produce output of "1920 x 981", as does my "ccode.txt" example.

**Comment by fastrgv** [comment]
I think I'll close this issue.  If I can get you a C++ example that demonstrates my problems, then I'll open another.  As I said above, I have a work around FTTB, and since I program in Ada, I don't have a good C++ example in my pocket.  Thx.
