### ISSUE TITLE
glfwSwapBuffers() using nsgl_context calls UI API that should only be called from the main thread.

### ISSUE THREAD

**Issue by crujose** [glfw/glfw#1674]
**OS and version:** MacOS 10.14.6
**Release or commit:** 3.3-stable (0ac013381be83fcd6e53ea874f09b1895943bd9e)

https://github.com/glfw/glfw/blob/0ac013381be83fcd6e53ea874f09b1895943bd9e/src/nsgl_context.m#L54

This creates a problem when rendering to a window from a background thread.
`Main Thread Checker: UI API called on a background thread: -[NSWindow occlusionState]`

In my application, windows are created and polled from the main thread, but each window is given its own rendering thread where the window is made current and `glfwSwapBuffers(window)` is called when a new frame is rendered.

This breaks the documented behavior of glfwSwapBuffers which claims `@thread_safety This function may be called from any thread.`

**Comment by elmindreda** [comment]
This was fixed with 949275bbedaa58a5399c6ce5276adc190ae6a16b in response to your code line comment but I didn't notice until now that there was an issue open as well.

Thank you for reporting this!
