### ISSUE TITLE
Borderless Window issues/question

### ISSUE THREAD

**Issue by Speiger** [glfw/glfw#1675]
Sorry for the weird title I am not sure how to define this topic/issue.

So I am writing a program with LWJGL3 which uses GLFW bindings and I am trying to write a dynamic window that can change states on the fly, (Fullscreen/Windowed/Borderless/AAChange)

Fullscreen & Windowed work fine without any issues with glfwSetWindowMonitor.
But Switching to a borderless window requires that you use GLFW.glfwWindowHint and then create a new window and delete the old one and then updating the callbacks with the new WindowID.

To show the code that is required (I tested most things and the code is required "as is" to achieve things without forcing a program restart or cause a crash)

```java
public void setBorderless(boolean value)
{
	if(borderless == value || fullScreen)
	{
		return;
	}
	try
	{
		GLFW.glfwWindowHint(GLFW.GLFW_VISIBLE, 1); //Required else it will crash the program
		long lastValue = windowID;
		createWindow(name, width, height, false, value, antialiasing, false);
		GameManager.getReloader().reloadResources(); //Reloads shaders textures etc.
		GLFW.glfwDestroyWindow(lastValue);
		for(CallbackHandler entry : callbacks) //Automated Cache to store GLFW callbacks to make stuff easier
		{
			entry.destroy();
			entry.reload(windowID);
		}
		updateViewPort();
		GLFW.glfwWindowHint(GLFW.GLFW_VISIBLE, 1);
	}
	catch(Exception e)
	{
		e.printStackTrace();
	}
}
```
Create window function
```java
public void createWindow(String name, int width, int height, boolean fullScreen, boolean borderless, int antiAlias, boolean create) throws Exception
{
	this.name = name;
	GLFW.glfwWindowHint(GLFW.GLFW_SAMPLES, antiAlias);
	GLFW.glfwWindowHint(GLFW.GLFW_DECORATED, !fullScreen && borderless ? 0 : 1);
	GLFWVidMode screenSize = GLFW.glfwGetVideoMode(GLFW.glfwGetPrimaryMonitor());
	if(fullScreen)
	{
		width = screenSize.width();
		height = screenSize.height();
	}
	windowID = GLFW.glfwCreateWindow(width, height, name, fullScreen ? GLFW.glfwGetPrimaryMonitor() : 0, windowID);
	if(windowID == 0)
	{
		throw new RuntimeException("Game Window couldn't be created");
	}
	this.width = width;
	this.height = height;
	this.fullScreen = fullScreen;
	this.borderless = borderless;
	anti = antiAlias;
	validateBounds();
	GLFW.glfwMakeContextCurrent(windowID);
	GLFW.glfwSwapInterval(vSync ? 1 : 0);
	GLFW.glfwWindowHint(GLFW.GLFW_VISIBLE, 1);
	GLFWErrorCallback.createPrint(System.err).set();
}
```

Now my question is: Is this hack required always? Or am I doing something wrong? Because I can not find anything on this how to make a proper borderless window without recreating the window frame from scratch.

It would be really nice if you could provide some info about how to "properly" switch between borderless mode and non borderless mode, or if I found the "proper" way to do it.

Edit: Expanded on things and tried to make code more clear

**Comment by ghuser404** [comment]
In GLFW 3.3 there is a `glfwSetWindowAttrib` that you can use with `GLFW_DECORATED`. I'm not sure which version LWJGL3 is using and when it will be updated to use 3.3.

**Comment by Speiger** [comment]
let me try it maybe that fixes the issue

**Comment by Speiger** [comment]
yep that works.

**Comment by Speiger** [comment]
thanks @ghuser404 for that! Maybe write a tutorial in the wiki about that?
