### ISSUE TITLE
Connecting/Disconnecting Monitor on Windows 10 rewrites properties in Primary monitor

### ISSUE THREAD

**Issue by nvmsocool** [glfw/glfw#1676]
I am using the latest release in 32 bit mode on a 64 bit Windows 10 machine (with no other libraries) using Visual Studio 2019, and found that disconnecting or connecting a monitor causes issues with the properties of the primary monitor. The properties I noticed were the working width and height were set to 0, and the content scale was set to a very large number.

I have attached the sample code that recreates the issue.  
[GLFWPOC.txt](https://github.com/glfw/glfw/files/4495998/GLFWPOC.txt)

Steps to recreate:
1) Run the application
2) Right click to display the working width and height of the primary monitor
3) Connect a monitor
4) Right click again to see that the width and height are now 0.

Left clicking at any time will try to go into fullscreen, which behaves unpredictably after the connect/disconnect issue happens.

**Comment by elmindreda** [comment]
Thank you for reporting this! It should be fixed now with 166611cef5967313e6a3d50849e57ddbcdc33f26 by @dougbinks.
