### ISSUE TITLE
Change Samples after a window got created?

### ISSUE THREAD

**Issue by Speiger** [glfw/glfw#1677]
Is it possible to change the Anti Aliasing effect after the window got created?
So that it's not required to recreate windows for every time you change anti aliasing, like with borderless mode and fullscreen mode?
Edit: I mean GLFW.GLFW_SAMPLES

**Comment by mmozeiko** [comment]
In OpenGL changing framebuffer samples would require completely destroying context and recreating it. This means you would need to recreate all your textures, buffers, shaders, etc...

You can do it more efficiently by creating your own renderbuffer with whatever samples you want. And at the end of drawing, just before call to glfwSwapBuffers, use the glBlitFramebuffer function to copy contents of your render buffer to window framebuffer (which now can have 0 samples for multisampling). This way you'll be able to destroy and recreate randerbuffer as much as you want.

**Comment by Speiger** [comment]
Ok, thanks for the confirmation, i already have a system for that since I have callbackproviders for that exact reason anyways.
So not really an issue I just wanted to make sure I am not doing something stupid like it was with borderless Mode.
