### ISSUE TITLE
glfwGetKeyName throws Access violation reading location exception

### ISSUE THREAD

**Issue by reu24** [glfw/glfw#1679]
glfwGetKeyName works in the most cases. But if I click the Space key or Escape it throws an exception.
![grafik](https://user-images.githubusercontent.com/55582367/79684509-4ffa4980-8232-11ea-916d-263df7e0452e.png)
Here's an example code that it throws the exception:

```
#include <GLFW/glfw3.h>
#include <iostream>

int main()
{
	if (!glfwInit())
	{
		std::cout << "GLFW Error";
	}

	std::cout << glfwGetKeyName(GLFW_KEY_SPACE, 57); // 57 is the scancode of Space
}
```
Does anyone have an idea how to fix this?

Edit:
If I return 0 it still doesn't work.
Edit 2:
glfwGetKeyName() returns NULL when using keys like space/escape.

**Comment by kyy13** [comment]
I don't know if this is the issue, but try returning a value at the end of `int main()`.

fyi-
> If the key is GLFW_KEY_UNKNOWN, the scancode is used to identify the key, otherwise the scancode is ignored.

**Comment by tombsar** [comment]
> Try returning a value at the end of `int main()`

This is not required in C; main implicitly returns 0 unless otherwise specified.

**Comment by tombsar** [comment]
The exception is most likely caused by `glfwGetKeyName` returning `NULL` for those keys. Since this function is documented to be able to return a `NULL` pointer, you should always test before trying to use the value as a string.

I'm not sure why there is no string returned for space or escape.

**Comment by kyy13** [comment]
> This is not required in C; main implicitly returns 0 unless otherwise specified.

Okay, I wasn't sure if it was something specific to visual studio debugger. The snippet works for me.

**Comment by elmindreda** [comment]
> I'm not sure why there is no string returned for space or escape.

My (dubious) reasoning behind this was that `glfwGetKeyName` would return names only for keys that vary with keyboard layout, while the remaining keys vary with application language.

What I probably ought to have done instead is return known English names for them instead.

**Comment by reu24** [comment]
As I said above it doesn't return NULL. It throws an exception.

**Comment by tombsar** [comment]
Is the exception coming from inside glfw, or the constructor of std::string? Please examine the call stack.

**Comment by ghuser404** [comment]
@tombsar In the picture posted by OP it looks like exception is coming from a string constructor, trying to read nullptr.

**Comment by tombsar** [comment]
@ghuser404 I know that, but I'm trying to get reu24 to believe it. There's always a possibility I'm wrong, too.

**Comment by reu24** [comment]
I found a part of the error. As @tombsar said it returns NULL. It threw the exception since I was using std::string instead of const char*. But I still don't know why it returns NULL.

**Comment by tombsar** [comment]
@reu24 See elmindreda's reply here (https://github.com/glfw/glfw/issues/1679#issuecomment-620092398). Special keys such as space don't change name according to keyboard layout, so they aren't handled in this function by design.

Thanks for bringing attention to this; it will definitely be considered for revision in a future release.

**Comment by reu24** [comment]
So that means I have to handle those keys by myself?

**Comment by tombsar** [comment]
@reu24 I'm afraid so, for now. I would suggest a function that looks something like this:

```
std::string getKeyName (int key, int scancode = 0) {
    char const * str = glfwGetKeyName(key, scancode);
    if (str) return str::string(str);
    switch (key) {
        case GLFW_KEY_SPACE: return "SPACE";
        case GLFW_KEY_ESCAPE: return "ESCAPE";
        case GLFW_KEY_ENTER: return "ENTER";
        /* TODO: Add the rest of the keys you need here */
        default: return "(UNKNOWN)";
    }
}
```

(Might need tweaking depending on what compiler version of C++ you are using; some are more or less permissive about automatic casting to and from std::string)
