### ISSUE TITLE
Is meson support dead in the water?

### ISSUE THREAD

**Issue by Jkmcameron** [glfw/glfw#1684]
I just started using meson and it doesn't I tried adding both 'glfw' and 'glfw3' as dependencies in my build file, both turned up as "not found" which is a bit of a drag. I see online a way of setting up glfw as a subproject after downloading the library manually, but this route disregards the reason I started using a packaging system. 

I see [in this post](https://github.com/glfw/glfw/issues/870#issuecomment-369909264) and [in this pull request](https://github.com/glfw/glfw/pull/1546) that meson support was a thing at some point, but alas doesn't seem to be working for me. 

```
#glfw3.wrap
[wrap-git]
url = https://github.com/glfw/glfw.git
revision = head
```

```
project('src/main', 'cpp', default_options : ['cpp_std=c++2a'])
subproject('glfw3')

vulkan = dependency('vulkan')   

exe = executable('Adventum', 'src/main.cpp', dependencies : [vulkan])
```

> Building in: C:\Users\jkmca\Workspace\Adventum\build\default
> [0/1] "C:\Program Files\Meson\meson.exe" --internal regenerate "C:\Users\jkmca\Workspace\Adventum" "C:\Users\jkmca\Workspace\Adventum\build\default" --backend ninja
> Cloning into 'glfw3'...
> The Meson build system
> Version: 0.54.0
> Source dir: C:\Users\jkmca\Workspace\Adventum
> Build dir: C:\Users\jkmca\Workspace\Adventum\build\default
> Build type: native build
> Project name: src/main
> Project version: undefined
> C++ compiler for the host machine: c++ (gcc 8.1.0 "c++ (x86_64-win32-seh-rev0, Built by MinGW-W64 project) 8.1.0")
> C++ linker for the host machine: c++ ld.bfd 2.30
> Host machine cpu family: x86_64
> Host machine cpu: x86_64
> 
> ..\..\meson.build:2:0: ERROR: Subproject exists but has no meson.build file
> 
> A full log can be found at C:\Users\jkmca\Workspace\Adventum\build\default\meson-logs\meson-log.txt
> FAILED: build.ninja 
> "C:\Program Files\Meson\meson.exe" --internal regenerate "C:\Users\jkmca\Workspace\Adventum" "C:\Users\jkmca\Workspace\Adventum\build\default" --backend ninja
> ninja: error: rebuilding 'build.ninja': subcommand failed
> Build complete: C:\Users\jkmca\Workspace\Adventum\build\default
>

**Comment by Jkmcameron** [comment]
I'm currently using [this fork](https://github.com/henry4k/glfw-meson) that supports meson integration

**Comment by elmindreda** [comment]
There are no plans to support Meson upstream. Nothing against Meson specifically, which I use for personal projects.
