### ISSUE TITLE
Alternative to GLFW_PLATFORM_ERROR for unimplemented/unimplementable

### ISSUE THREAD

**Issue by hanetzer** [glfw/glfw#1692]
For instance: https://github.com/glfw/glfw/blob/master/src/wl_window.c#L883
Setting a window icon is and will never be a thing wayland does via code. While
it is probably a good idea to return something other than `GLFW_NO_ERROR`
for information's sake, if this function and 'real' errors both return the same code
its impossible to filter both. This partially causes an issue in the game Minecraft
when ran with the wayland backend, and as of right now it can't safely ignore what
could be.

Perhaps something like `GLFW_ERROR_NOOP`?

[MC-92393](https://bugs.mojang.com/browse/MC-92393)

**Comment by elmindreda** [comment]
Agreed, there really should be some error message to tell "something went wrong right now" from "this is never going to work on this platform". Other platforms would benefit from this as well.

**Comment by elmindreda** [comment]
Separate from that, GLFW can almost always roll back to a known state on errors, including platform errors. Treating all errors as fatal is possibly overkill. Instead I would suggest checking with `glfwGetError` after important calls that don't return an error value.

**Comment by elmindreda** [comment]
Looking at the existing cases, I propose two new errors.

`GLFW_FEATURE_UNAVAILABLE` for failures caused by platform limitations like those discussed above. The Cocoa code also has a couple of places where this would make sense.

`GLFW_FEATURE_UNIMPLEMENTED` for when the GLFW platform code is incomplete but the platform itself does support the functionality. This may also have some utility between releases.

**Comment by hanetzer** [comment]
Sounds good, MC could ignore `GLFW_FEATURE_UNAVAILABLE` errors
and maybe do something with `GLFW_FEATURE_UNIMPLEMENTED`.

**Comment by elmindreda** [comment]
Please see the `feature-errors` branch for the proposed fix.

**Comment by hanetzer** [comment]
This seems quite reasonable. I really can't test too hard on account of the nature of
minecraft itself but this looks to at least give the hooks needed to make this possible.
