### ISSUE TITLE
Robustness of GL header include guard

### ISSUE THREAD

**Issue by tombsar** [glfw/glfw#1695]
Yesterday I tried to integrate glad into a project using OpenGL ES, and had to spend an hour diagnosing the most frustrating compile errors of my life (thanks gcc!) caused by, it turns out, inclusion of both glad.h (explicitly by me) and gl.h (implicitly by glfw).

I understood from the documentation (https://www.glfw.org/docs/latest/context_guide.html#context_glext_auto) that:

> By including the glad header before the GLFW header, it suppresses the development environment's OpenGL or OpenGL ES header.

However I don't see any mechanism in glfw3.h that enforces this; it looks as though in the absence of any `GLFW_INCLUDE_*` defines, GL/gl.h is included unconditionally (https://github.com/glfw/glfw/blob/master/include/GLFW/glfw3.h#L210).

gl.h has an include guard to prevent duplicate inclusion, but the guard has a different name for each version of OpenGL. Hence, the inclusion of GLES/gl.h (or equivalent glad.h) does not prevent the inclusion of GL/gl.h.

Easy to work around once I found the issue, (`#define GL_INCLUDE_NONE`), but it would be great if I didn't need to do that.

At the moment I'm wondering why `GL_INCLUDE_NONE` isn't the default behaviour, making the user specifically ask if they want glfw to include an OpenGL header. ~~Obviously that's a breaking change, so could only be considered for glfw 4.~~ Significant change, but not necessarily **breaking**.

In the meantime, I think we need at least an update to the documentation to make this behaviour more obvious, if not an actual fix.

Thoughts?

**Comment by elmindreda** [comment]
Agreed, `GLFW_INCLUDE_NONE` is a much better default. That decision carried over from 2.x and I didn't reexamine it until 3.0 was already out.

Let's see what we can do about it in 3.x.

**Comment by elmindreda** [comment]
Since mixing any of these headers is a bad idea, we could perhaps add the falsely promised mechanism. Detect the canonical inclusion guards early on and define `GLFW_INCLUDE_NONE` if any are present.

Switching the default would be the cleaner solution but it would also break the compilation of a lot of tutorial code, including our widely copied [minimal example](https://www.glfw.org/documentation.html).

**Comment by elmindreda** [comment]
Sorry, that was mostly just restating what you had already said.

Does this seem reasonable?
```diff

-#elif !defined(GLFW_INCLUDE_NONE)
+#elif !defined(GLFW_INCLUDE_NONE) && \
+      !defined(__gl_glcorearb_h_) && \
+      !defined(__gl_h_) && \
+      !defined(__gles2_gl32_h_) && \
+      !defined(__gles2_gl31_h_) && \
+      !defined(__gles2_gl3_h_) && \
+      !defined(__gles2_gl2_h_) && \
+      !defined(__gles1_gl_h_)

```

**Comment by tombsar** [comment]
@elmindreda Glad you agree with me!

I'm reluctant to endorse that solution because there is such a long list of defines that appear in the wild, and it would need to be updated every time Khronos or a loader library adds or changes any of them.

Case in point, your proposed patch would not have avoided my issue as the header I get from glad guards with the following defines:

```
#ifndef __glad_h_
#define __glad_h_

#ifdef __gl2_h_
#error OpenGL ES 2 header already included, remove this include, glad already provides it
#endif
#define __gl2_h_

#ifdef __gl3_h_
#error OpenGL ES 3 header already included, remove this include, glad already provides it
#endif
#define __gl3_h_
```

not the `__gles`-prefixed ones. That's probably a bug in glad (I'll file an issue), but it proves how brittle this solution can be.

You could maybe add `__glad_h_` to the list (it's probably at least as stable as Khronos' identifiers), but there are a lot of other loader libraries out there...

IMHO the simplest fix right now would be to change the documentation to simply say that if using a loader library such as glad, the user *must* define `GLFW_INCLUDE_NONE` to guarantee no duplicate definitions.

You could do both, of course; I don't think there's any actual harm in guarding the most common identifiers.

**Comment by elmindreda** [comment]
Both sounds like a good solution.

**Comment by elmindreda** [comment]
105cf32e0b05e207d4cd5efa462887569ca2116a should help a bit.

**Comment by elmindreda** [comment]
This is admittedly me trying to have my cake and eat it but does 47c766d8177f2ee786086136e70506e12a7b5523 seem adequate?

**Comment by tombsar** [comment]
I'm happy with that for a resolution. Thanks!

**Comment by elmindreda** [comment]
Merged, including the last-minute fix.
