### ISSUE TITLE
GLFW window opening slows down  on RTX2070 May2020 drivers

### ISSUE THREAD

**Issue by salimp2009** [glfw/glfw#1709]
hi
i am trying to use GLFW to create a window for a game engine(learning) ...basic windows only background color...no objects...it works OK for a couple F5 runs on VS Studio 2019 with Nvidia RTX2070 and Windows 10 Pro all are updated as of May 31,2020. I did even a clean reinstall of Nvidia drivers and contacted to Nvidia too but no change. GLWF window works ok 4-5 times then starts opening late to get a coffee. I saw several similar issues dated back from 2018-2019 . I was wondering the same issue was happening again..a conflict with recent Nvidia drivers and GLFW ...the older issue were about "ChoosePixelFormat calls getPixelFormatAttrib......" here is the link on previous issue 
 
https://discourse.glfw.org/t/glfw-has-long-delay-when-creating-a-window/1072

And some solutions created from that link was ;
"...ChoosePixelFormat calls getPixelFormatAttrib around 20x per loop. This in turn calls wglGetPixelFormatAttribivARB which could be slow on your system for some reason....."

"Calling wglGetPixelFormatAttribivARB once for all required attributes might improve performance if this is the case by up to 20x, which could get you within reasonable performance times for your setup...."

**Comment by elmindreda** [comment]
That change was made in version 3.3 with babafc13dbdf6b031659ef54259185f72263e1d3 so if you have that or a newer version it should already be using this faster path.

**Comment by elmindreda** [comment]
Since you're already using running it with a debugger, break when it stops like this and post the call stack here.

**Comment by salimp2009** [comment]
ok i will do  the debugging thanks..I am using pretty latest GLFW version; forked it a month ago...thanks again for the response...I will keep posted :)

**Comment by salimp2009** [comment]
i tried to debug and put a break point on where i initiliaze the GLFW and stops there at glfwCreateWindow and the stack disappears and cannot  do "jump in" int the debugger to see where it is. it waits for 40 secs everytime. I tried on a different code too...this when it slows down
if not it opens up around 500-700 milliseconds . I posted on Nvidia developer forum and also Geforce Forum . Also found some old twitter conversation about those old issue where one of Nvidia folks responded at that time and sent him a msg too...i keep working on my code (not on this one but the engine one) but still annoys me  and disappointed on RTX card.

int MyWindow::Initialise()
{
	//initialize GLFW
	if (!glfwInit())
	{
		printf("GLFW Initialization failed!!!...");
		glfwTerminate();
		return 1;
	}

	// Setup GLFW window properties
	// OpenGL version
	glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
	glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);

	// Core profile means no backward compatibility
	glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);

	// Allow forward compatibility
	glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);

	mainWindow = glfwCreateWindow(width, height, "Test Window", NULL, NULL);

**Comment by tombsar** [comment]
> the stack disappears and cannot do "jump in" int the debugger

Have you compiled glfw with debug symbols? It should be a CMake setting that looks like this: `CMAKE_BUILD_TYPE:STRING=Debug`. Might give you more information.

**Comment by salimp2009** [comment]
I will look into tht One of the project uses ready binaries the other one was compiled wiith the engine but using premake to build both glfw and engine But both cases exactly has the same issue :( I see people s window pop up right away :(

**Comment by salimp2009** [comment]
hi i did ran the debugger with a couple of breakpoints in GLFW src as you mentioned
when i ran the first 3-4 times there is no problem where there is hold it waits  in window.c file on line 152; held there for 40 secs;

GLFWAPI GLFWwindow* glfwCreateWindow(int width, int height,
                                     const char* title,
                                     GLFWmonitor* monitor,
                                     GLFWwindow* share)
after that;
i did another breakpoint in wgl_context.c , line 69 it helld over there for 40 secs (at the begining of the loop at line 69)
static int choosePixelFormat(_GLFWwindow* window,
                             const _GLFWctxconfig* ctxconfig,
                             const _GLFWfbconfig* fbconfig)

Even on one instance the system was frozen at somewher with win32.dll but i was paniced cause nothing worked waited for a while and powered off...this was the first time . 

Please let me know if you need me to breakpoint at specific points that might help to resolve this

**Comment by salimp2009** [comment]
hi 
I did some debugging starting from 
- The wait was somewhere before the function  wglGetPixelFormatAttribivARB;

- so I chased down the calls 
it waits 40 sec at glfwInit() function

and I chased down the calls all the way to 

- line 574 win32_init.c 
there is a if loop and the wait is in  DirectInput8_EnumDevices 

-  DirectInput8_EnumDevices  refers #define in file dinput.h
line 2673 #define IDirectInput8_EnumDevices(p,a,b,c,d) (p)->lpVtbl->EnumDevices(p,a,b,c,d)

-  >lpVtbl refers to a call       const AsyncIAdviseSinkVtbl * AsyncIAdviseSink::lpVtbl  
in file "ObjIdl.h"    at location C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um

- Not sure how far is i should go now it is windows 10 cplusplus file????

Any ideas why it stays so long in a joystick function ???????????????
I also opened the issue on Nvidia developer forum and someone from there kinda directed to make those debugging to help and tought someone here might know a little bit more ???

*****this is where the last call was referred 

if (_glfw.win32.dinput8.api)
    {
        if (FAILED(IDirectInput8_EnumDevices(_glfw.win32.dinput8.api,
                                             DI8DEVCLASS_GAMECTRL,
                                             deviceCallback,
                                             NULL,
                                             DIEDFL_ALLDEVICES)))
        {
            _glfwInputError(GLFW_PLATFORM_ERROR,
                            "Failed to enumerate DirectInput8 devices");
            return;
        }
    }
}

**Comment by intrigus** [comment]
Could you try to unplug every device (gamepad, keyboard, printer, ...) besides the mouse?
Then start your test program and try if opens faster.

**Comment by salimp2009** [comment]
I have only keyboard & mouse. No printer, joystick or gamepad or any extra device attached. I was surprised that it goes into that function and spends that much time there

**Comment by intrigus** [comment]
Did you try removing your keyboard and checking your speed?
(I'm on my phone, but there have been similar problems like this. Search the tracker for "slow device enumeration". That my bring that issue up)

**Comment by salimp2009** [comment]
i am away from that computer right now and will try to remove the keyboard as you said.
and will search for that "slow device enumeration"...thnks...I really appreciate :) hopefully getting closer to solve it...:)

**Comment by salimp2009** [comment]
I searched through the issues for "slow device enumeration" but did not come up with any...I will try the keyboard removal later today..

**Comment by aloucks** [comment]
This seems pretty relevant: 

https://stackoverflow.com/questions/10967795/directinput8-enumdevices-sometimes-painfully-slow

**Comment by tombsar** [comment]
For some reason I can't find the issue that I remember about this, but I believe it was found to be a Corsair keyboard driver that was causing a similar problem before (see also the responses on that stackoverflow link). By any chance is your keyboard Corsair brand?

At any rate, the slowdown is most likely not related to your NVidia graphics driver.

**Comment by salimp2009** [comment]
Yes yes my keyboard Corsair 55 shall get another one or get a new driver for it Wht do you recommend. Maybe just unplug and see if it is gone. But how will i know the other o e wont cause probably try and error Do you recommend one...Thank you you made my day i spent hours debugging I dont have any other keyboard at this point . I was thinking my Gpu was the problem Any recommendations to do now

**Comment by tombsar** [comment]
First thing is making sure you have the latest up-to-date driver and software available from Corsair. If you do, then perhaps try uninstalling and reinstalling anything Corsair-related; it's possible there is something old left over that is no longer needed.

**Comment by salimp2009** [comment]
Ok i will try that right away when i get to my computer later today. Is there way that you recommend to safely to remove any Corsair driver related driver I can try first updating it If it does not work i can remove from device manager and reinstall with the new driver . I wonder if i need to clean registry or any thing related👍

**Comment by tombsar** [comment]
I'm afraid I don't have personal experience, but it looks as though there's something of a guide here: https://help.corsair.com/hc/en-us/articles/360025166712-Perform-a-clean-reinstallation-of-the-Corsair-Utility-Engine-iCUE-

Good luck! Let us know if it helps at all.

**Comment by salimp2009** [comment]
I will keep you posted and close the issue as soon as i resolve it thanks again

**Comment by salimp2009** [comment]
good news..no awesome news....i just update drivers corsair k55 driver from the web site and installed the software for it ...the problem did not go away but then the keyboard software did another update itself..and the problem is gone...i tested hitting F5 30-4 times in a row while 7 you tube videos and unreal engine open and 3 other visual studio project open...i also had another project with the opengl and tried even that one at the same time...no problem the window opens 565-650 milliseconds and never slowed down...Before it was taking 20-40 seconds when it slowed down.....so the issue is closed thank you guys for the support i could never think it would be keyboard and thinking it is GPU causing conflict with GLFW Anyway....thank you all of you..i will be happy to help if i can anyway ...thnk ..it is a good day for me :=)
