### ISSUE TITLE
Key repeat timer race condition causing freeze

### ISSUE THREAD

**Issue by annacrombie** [glfw/glfw#1710]
Some info about my environment:

I'm running `sway version 1.4-f681d529`, and the latest master of glfw built with wayland support.  My program is single threaded and calls glfwPollEvents every frame, which is capped at 30 fps.

Occasionally my glfw program will completely freeze.  Attaching with gdb revealed the following backtrace:

```
#0  __cp_end () at src/thread/x86_64/syscall_cp.s:29
#1  0x00007fafcbcacc6d in __syscall_cp_c (nr=0, u=8, v=140721514594888, w=<optimized out>,
    x=<optimized out>, y=<optimized out>, z=0) at src/thread/pthread_cancel.c:33
#2  0x00007fafcbcb2b16 in read (fd=<optimized out>, buf=<optimized out>, count=<optimized out>)
    at src/unistd/read.c:6
#3  0x000055777d5240c8 in handleEvents ()
#4  0x000055777d524c8e in _glfwPlatformPollEvents ()
#5  0x000055777d51d825 in glfwPollEvents ()
#6  0x000055777d4fbb18 in opengl_ui_handle_input (ctx=0x7fafcbc4bde0, km=0x7ffc47e3c388,
    hf=0x7fafcbc4bc80) at ../client/ui/opengl/ui.c:125
#7  0x000055777d4ee559 in ui_handle_input (ctx=0x7fafcbc4bda0, km=0x7ffc47e3c388,
    hf=0x7fafcbc4bc80) at ../client/ui/common.c:82
#8  0x000055777d4eda24 in main (argc=3, argv=0x7ffc47e3eb78) at ../client/main.c:65
```

After doing some digging I think I found a race condition.  When I hold a key, the repeat timer is properly set and detected with poll().  However, if I release the key after glfw has polled the repeat timerfd, but before the timerfd is read, the key handling code disarms the timer and the resulting read blocks, freezing my program.

Printf debugging supports my hypothesis:

[src/wl_window.c](https://github.com/glfw/glfw/blob/master/src/wl_window.c#L746)

```
  if (poll(fds, 3, timeout) > 0) {
       printf("done polling\n");

       ...
       if (fds[1].revents & POLLIN)
       {
            printf("about to read\n");
->          read_ret = read(_glfw.wl.timerfd, &repeats, sizeof(repeats));
```

[src/wl_init.c](https://github.com/glfw/glfw/blob/master/src/wl_init.c#L598)

```
    printf("setting timer: %ld, %ld, %ld, %ld\n", timer.it_value.tv_sec,
	    timer.it_value.tv_nsec, timer.it_interval.tv_sec,
	    timer.it_interval.tv_nsec);

    timerfd_settime(_glfw.wl.timerfd, 0, &timer, NULL);
```

output:
```
...
done polling
done polling
done polling
setting timer: 0, 600000000, 0, 40000000
done polling
done polling
done polling
done polling
done polling
done polling
done polling
done polling
done polling
done polling
done polling
done polling
done polling
done polling
done polling
done polling
done polling
done polling
done polling
about to read
done polling
about to read
done polling
about to read
done polling
about to read
done polling
setting timer: 0, 0, 0, 0
about to read
```

I have fixed this problem for now by simply setting O_NONBLOCK on the timerfd, but I'm not sure if that is the best solution.

**Comment by BailShamber** [comment]
Reverse engineered GTA 3 and Vice City (re3 and reVC) freeze within 1~3 minutes of playing on wayland, patching current glfw upstream with the change from this pull request https://github.com/glfw/glfw/pull/1711 fixes it.
