### ISSUE TITLE
XCloseDisplay returns BadWindow on linux when stop app

### ISSUE THREAD

**Issue by zhuah** [glfw/glfw#1721]
i'm typing something, and then close the window, the window is closed normally, but got a fatal error when stop app.
```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  2 (X_ChangeWindowAttributes)
  Resource id in failed request:  0x3800012
  Serial number of failed request:  964
  Current serial number in output stream:  968
```

**Comment by elmindreda** [comment]
What IME are you using and which version of GLFW?

**Comment by zhuah** [comment]
I'm using my own glfw fork [https://github.com/zhuah/glfw](https://github.com/zhuah/glfw), and the IME is fcitx, in English mode.

**Comment by zhuah** [comment]
Sorry, it seems that this is caused by `XCloseDisplay` not `XCloseIM`

**Comment by elmindreda** [comment]
I can't reproduce this exactly but GLFW definitely seems to be doing something bad to fcitx.

**Comment by zhuah** [comment]
thank you for your effort 😄 .
and did you have any ideas about how to totally destroy a Window? 
it seems that the Window is still being referenced in Display or internal Xlib states, so it could produce a `BadWindow` error even if window has been closed by `XDestroyWIndow`

**Comment by zhuah** [comment]
Sorry so much, it's my fault, i'm update cursor to IBeam for input box after window destroyed.

**Comment by elmindreda** [comment]
> Sorry so much, it's my fault, i'm update cursor to IBeam for input box after window destroyed.

No worries and thank you for the follow-up!

> GLFW definitely seems to be doing something bad to fcitx.

Turns out I could reproduce this problem without GLFW and it is probably me not knowing enough about the user end of fcitx.
