### ISSUE TITLE
glfwInit() takes 5 to 10 sec to complete

### ISSUE THREAD

**Issue by hacker104** [glfw/glfw#1732]
https://pastebin.com/zHDdZmjW
this is my code 
i don't know why please help

**Comment by hacker104** [comment]
opengl version: 4.6.0 NVIDIA 451.67

**Comment by elmindreda** [comment]
This may be the same issue as #1284 and #1646. If you can, test the `joystick-delay-init` branch and see if that resolves this issue.

**Comment by hacker104** [comment]
the boing example works fine and start almost instatly

**Comment by hacker104** [comment]
this fix my code too

**Comment by elmindreda** [comment]
Thank you for testing! I'll clean up and merge this change.

**Comment by salimp2009** [comment]
make sure also that usb input device drivers are upto date. I had a similar problem a while ago and it was gone after updating keyboard drivers.(Corsair K55) but  I had the similar issue #1709 resolved . The bottom of that issue #1709 has the call back info that was holding....I wish you had this branch back then :)

**Comment by elmindreda** [comment]
Delayed initialization of joystick support has been merged as 782e6b6cefc9ac2a2b6779f9e658ab948809253b.
