### ISSUE TITLE
glfwInit() changes current working directory

### ISSUE THREAD

**Issue by ghost** [glfw/glfw#174]
I tried the following code that uses cyglfw3

https://pypi.python.org/pypi/cyglfw3/0.0.2

import os
import cyglfw3 as glfw
print os.getcwd()
glfw.Init()
print os.getcwd()

The output is:

$ python bug.py 
/Users/xxx/code/python/glfwtest
/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/Resources

This is on OS X 10.9, with GLFW 3.03

**Comment by keiwanjamaly** [comment]
Is there another established solution instead of saving and restoring the CWD? The flag -DGLFW_USE_CHDIR=0 doesn't seem to exist any more.
