### ISSUE TITLE
Unable to compile from source using gcc on macOS

### ISSUE THREAD

**Issue by Haiderahandali** [glfw/glfw#1743]
I switched from clang++ to g++ (gcc version 9.3)
I noticed I can't compile GLFW from source code using CMake. linking against the precompiled libs with GCC does work tho.
I am just using the example in documentation, and I have included glad.c (but I did remove it and it didn't work either)

I get the following errors (the full list of errors can be seen here https://pastebin.com/HLJ2y9cy) 
those are just the first few.

I want to note again, that with clang11 it works perfectly fine, no issues or warnings.

[proc] Executing command: /usr/local/bin/cmake --build /Users/aliabdul-kareem/dev/OPENGL/build --config Debug --target myapp -v -- -j 6
[build] [6/19   5% :: 1.179] /usr/local/bin/gcc-9  -I../include -I../deps/glfw/include -iframework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -MD -MT CMakeFiles/myapp.dir/src/glad.c.o -MF CMakeFiles/myapp.dir/src/glad.c.o.d -o CMakeFiles/myapp.dir/src/glad.c.o   -c ../src/glad.c
[build] [7/19  10% :: 2.568] /usr/local/bin/g++-9   -I../include -I../deps/glfw/include -iframework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -MD -MT CMakeFiles/myapp.dir/src/main.cpp.o -MF CMakeFiles/myapp.dir/src/main.cpp.o.d -o CMakeFiles/myapp.dir/src/main.cpp.o -c ../src/main.cpp
[build] [8/19  15% :: 4.131] /usr/local/bin/gcc-9 -D_GLFW_USE_CONFIG_H -I../deps/glfw/include -I../deps/glfw/src -Ideps/glfw/src -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -fPIC   -Wall -std=gnu99 -Wdeclaration-after-statement -MD -MT deps/glfw/src/CMakeFiles/glfw.dir/context.c.o -MF deps/glfw/src/CMakeFiles/glfw.dir/context.c.o.d -o deps/glfw/src/CMakeFiles/glfw.dir/context.c.o   -c ../deps/glfw/src/context.c
[build] FAILED: deps/glfw/src/CMakeFiles/glfw.dir/context.c.o 
[build] /usr/local/bin/gcc-9 -D_GLFW_USE_CONFIG_H -I../deps/glfw/include -I../deps/glfw/src -Ideps/glfw/src -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -fPIC   -Wall -std=gnu99 -Wdeclaration-after-statement -MD -MT deps/glfw/src/CMakeFiles/glfw.dir/context.c.o -MF deps/glfw/src/CMakeFiles/glfw.dir/context.c.o.d -o deps/glfw/src/CMakeFiles/glfw.dir/context.c.o   -c ../deps/glfw/src/context.c
[build] In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Security.framework/Headers/AuthSession.h:32,
[build]                  from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Security.framework/Headers/Security.h:42,

**Comment by dougbinks** [comment]
As I've mentioned on issue:
https://discourse.glfw.org/t/unable-to-compile-from-source-gcc-10-macos/1630

This appears to be your version of GCC having problems with OS X framework headers, which use Objective C. For example the error:

```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGPDFArray.h:103:15: error: expected identifier or '(' before '^' token
[build]   103 | typedef bool (^CGPDFArrayApplierBlock)(size_t index,
[build]       |               ^
```

I think it's possible to force GCC to compile files as objective-C but I don't know the details.
Is GCC being unable to compile the Objective-C caret symbol which defines a block:
https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/WorkingwithBlocks/WorkingwithBlocks.html

**Comment by josekoalas** [comment]
As a heads up for anyone facing this same issue, glfw can be compiled successfully if using g++ as the c++ compiler and apple clang as the c compiler. This way all the framework issues go away. You just need to set your environmental variables/cmake settings accordingly. Check how Vulkan-Hpp does it in their [CI pipeline](https://github.com/KhronosGroup/Vulkan-Hpp/blob/master/.github/workflows/ci-macos.yml). This should also apply to issue #2147.

**Comment by the13fools** [comment]
Omg thank you!!!
