### ISSUE TITLE
Cmake Warnings : CMAKE_INTERPROCEDURAL_OPTIMIZATION

### ISSUE THREAD

**Issue by hdf89shfdfs** [glfw/glfw#1753]
I'm getting this warning when using glfw currently.

```
CMake Warning (dev) at build/_deps/glfw-src/src/CMakeLists.txt:82 (add_library):
  Policy CMP0069 is not set: INTERPROCEDURAL_OPTIMIZATION is enforced when
  enabled.  Run "cmake --help-policy CMP0069" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.       

  INTERPROCEDURAL_OPTIMIZATION property will be ignored for target 'glfw'.
This warning is for project developers.  Use -Wno-dev to suppress it. 
```

This is because I set these variables:
```
    # Turn off IPO for every config except release
    set(CMAKE_INTERPROCEDURAL_OPTIMIZATION OFF)
    set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE ON)
```

I believe the easiest way to solve this problem is like this:

```
cmake_minimum_required(VERSION 3.1...3.12)
```

**Comment by hdf89shfdfs** [comment]
To be clear I realize you could just set the policy explicitly, however I believe accepting a range like as shown above would be beneficial for newer projects that use newer versions of cmake.

**Comment by hdf89shfdfs** [comment]
Accidentally closed the issue.

**Comment by elmindreda** [comment]
> ```cmake
> cmake_minimum_required(VERSION 3.1...3.12)
> ```

Neat, TIL. Enabling the specific policy will still be necessary in order to cover CMake 3.9 to 3.11, but it may be a good idea to specify a maximum version too.
