### ISSUE TITLE
Did you consider applying for GitHub Sponsors program?

### ISSUE THREAD

**Issue by raysan5** [glfw/glfw#1758]
I'd like to contribute to this project with some donation, did you considered GitHub Sponsors program?

I think many developers (like me) love GLFW project and having the GitHub Sponsors option to show and share that love for the project would benefit GLFW (and not only in economic terms but also exposure).

In any case, thank you very much for your amazing work!

**Comment by abnercoimbre** [comment]
I second @raysan5's sentiment. In the meantime, is there another way for people to donate? Nowhere immediately clear from the GLFW website 🤔. 

It must sometimes get overwhelming dealing with all the issues and pull requests -- thank you, a bunch of us appreciate you!
