### ISSUE TITLE
glfwInit() Failed, Error code is 0x10008

### ISSUE THREAD

**Issue by dx12346789** [glfw/glfw#1760]
# glfwInit() Failed
**The error I printed with glfwSetErrorCallback is 'Win32: Failed to register window class' and the error code is 65544**  
What should i do?

**Comment by dx12346789** [comment]
glfwVersion is 3.3.2

**Comment by elmindreda** [comment]
Are there multiple copies of the GLFW library in that process?

**Comment by dx12346789** [comment]
Thank you。glfwInit was called by another thread
