### ISSUE TITLE
glfwInit may cause GLFW_INVALID_VALUE error due to plugged in joystick having invalid mapping in 3.3.2

### ISSUE THREAD

**Issue by dmitshur** [glfw/glfw#1763]
Please consider the following observations, which seem to apply to version 3.3.2 (latest release version) but do not apply on latest master commit (bb1d917c2fc0db03debf77c711fc37bef5231c88):

1. `glfwInit` is a part of GLFW public API. Its [documentation](https://www.glfw.org/docs/latest/group__init.html#ga317aac130a235ab08c6db0834907d85e) says that the possible errors include `GLFW_PLATFORM_ERROR`. It does not say that `GLFW_INVALID_VALUE` is a possible error.

2. `glfwInit` calls `_glfwPlatformInit`, which in turn calls `_glfwInitJoysticksLinux`, which in turn calls `openJoystickDevice`, which in turn calls `_glfwAllocJoystick`, which in turn calls `findValidMapping`.

3. `findValidMapping`,  a part of GLFW internal API, calls `_glfwInputError(GLFW_INVALID_VALUE, "Invalid button in gamepad mapping %s (%s), ...)` when it finds an invalid element for a joystick.

Based on my current understanding, this seems unexpected given the documentation. Is there a bug, either in the documentation, or the implementation?

It seems this can trigger when running `glfwInit` with an Xbox One Wireless Controller plugged in. I can't reproduce this myself, this is based only on analyzing an issue report at https://github.com/libretro/ludo/issues/342 and https://github.com/go-gl/glfw/issues/292 and reading the code.

The Go wrapper `github.com/go-gl/glfw/v3.3/glfw` [accepts](https://github.com/go-gl/glfw/blob/5321531c36a27bf07a44ce335c3fc26b284183c3/v3.3/glfw/glfw.go#L36-L37) only `GLFW_API_UNAVAILABLE`¹ and `GLFW_PLATFORM_ERROR` error categories from `glfwInit`, and panics on any other error category. So it panics when it sees `GLFW_INVALID_VALUE`, leading to issue https://github.com/go-gl/glfw/issues/292.

I'm reporting this here to understand if this is a problem in GLFW 3.3.2 or if it's a problem in how the go-gl GLFW bindings use it. It's possible this is already resolved on master thanks to deferred joystick initialization (commit 782e6b6cefc9ac2a2b6779f9e658ab948809253b, issue #1646). Issues https://github.com/go-gl/glfw/issues/127 and https://github.com/glfw/glfw/issues/833 may also be related. Thank you.

---

¹ I'm not sure why `GLFW_API_UNAVAILABLE` is accepted despite not being documented, but I guess it's outside the scope of this issue. Edit: After looking into git blame history, I think the answer is related to https://github.com/go-gl/glfw/issues/118#issuecomment-70607912.

**Comment by elmindreda** [comment]
> I'm reporting this here to understand if this is a problem in GLFW 3.3.2 or if it's a problem in how the go-gl GLFW bindings use it.

This is on GLFW, not go-gl. `glfwInit` should definitely not be spamming `GLFW_INVALID_VALUE`. There are several levels of fail in the gamepad mapping logic. I've removed the error message for now and am working on proper fixes that will let us use the full upstream database unmodified again.

**Comment by hajimehoshi** [comment]
Thank you for fixing this!

Does the same issue happen on SDL? If not, does GLFW have different joystick table than SDL's or some logics?

**Comment by elmindreda** [comment]
SDL did have the same issue but has since resolved it. Looking into exactly how is part of the work I mentioned above.

We have the same data tables as SDL, via the SDL_GameControllerDB project, but we are currently stuck on an older version of it.

**Comment by hajimehoshi** [comment]
Thank you!

We found that the same issue can happen not only at `glfwInit` but also at `glfwPollEvents`. I'd be happy if you could update `glfwPollEvents` too.

https://github.com/hajimehoshi/ebiten/issues/1229#issuecomment-880030199 (This is an error log by a Go wrapper of GLFW)

**Comment by elmindreda** [comment]
@hajimehoshi Those should all have been fixed by the commit above as they all in the end call that same function (`findValidMapping`). I do want the error to be completely gone, so if I've somehow missed it I'll gladly fix it but I can't currently see how it would still be happening.
