### ISSUE TITLE
Tiny Documentation Typo

### ISSUE THREAD

**Issue by brianzuvich** [glfw/glfw#1764]
Hey,

Just thought I'd point this one out. Noticed it in the source and then checked the website docs and of course, since I assume the website docs are generated from the source code, I found the same mistake.

The second line should read "maximized" instead of "iconified".

Just a friendly heads up.

![Source Code Image](https://i.imgur.com/T8gE7CR.png)

**Comment by linkmauve** [comment]
Thanks, this is now fixed in master. :)
