### ISSUE TITLE
glfwSwapInterval not working on Windows 7

### ISSUE THREAD

**Issue by stegu** [glfw/glfw#177]
I noticed in the FAQ that you wanted this reported, so here goes:
The call to glfwSwapInterval() in GLFW 3.0.3 seems to go unnoticed where I have tried it under Windows 7, not just on AMD hardware, but Nvidia as well. I made double sure the system-level setting for vertical blanking was "allow the 3D application to decide".
Tested on Windows 7 64-bit, with an old Nvidia GTS450 and a new GTX760, both with  the latest Nvidia drivers.

**Comment by elmindreda** [comment]
This has received what may be a more appropriate fix with 8309e0ecb09fe5cf670dff5df1e7ca71821c27bd.
