### ISSUE TITLE
Swaywm resizing not respected

### ISSUE THREAD

**Issue by muevoid** [glfw/glfw#1771]
I have not been able to test this on other wayland compositors however in sway in particular even when setting the no resizing flag for a window it will resize anyways and be able to be resized. This may be due to the fact that swaywm has undecorated windows so how would you force glfw to not resize even though it isn't decorated?

**Comment by christianrauch** [comment]
Does https://github.com/glfw/glfw/pull/1693 help? It will use `xdg-decoration` to negotiate the decoration mode and should use server-side decorations on sway.

**Comment by muevoid** [comment]
I don't have dbus so unfortunately that isn't an option for me :(

**Comment by christianrauch** [comment]
@muevoid Mind testing https://gitlab.gnome.org/jadahl/libdecoration/-/merge_requests/34 to check that libdecoration also works without dbus installed?

**Comment by muevoid** [comment]
Can do in a few here
