### ISSUE TITLE
is there any way to use latest versions of OpenGL & GLFW with old GPUs ? 

### ISSUE THREAD

**Issue by Mouradouchane** [glfw/glfw#1773]
- i'am trying to use last version of GLFW but code exit with error message say your GPU not supported v3 and up .
- my GPU it's sooo old & cheap 64MB with OpenGL v1.1 .

- my question is there any way or trick to use latest versions of OpenGL & GLFW with old  Graphics Card .

& thanks 😄

**Comment by linkmauve** [comment]
If you’re on Linux you probably already have Mesa installed, which ships llvmpipe, a CPU driver which doesn’t rely on your GPU to do 3D stuff.  It isn’t fully up to date OpenGL, it was stuck on 3.3 for quite a long time and only recently reached 4.5.  To run your GLFW application with it, `export LIBGL_ALWAYS_SOFTWARE=1` before running your application.

On other systems, you may have to get Mesa on your own.
