### ISSUE TITLE
Remove GLFW_VULKAN_STATIC: Vulkan is no longer is statically linkable.

### ISSUE THREAD

**Issue by charles-lunarg** [glfw/glfw#1776]
The PR #820 added a flag that Vulkan (the loader specifically) no longer supports. It appears that using the flag won't fail to compile, rather it will dynamically link instead, and fail to run, reporting: `Error code 65542: Vulkan: Window surface creation extensions not found`.

While it wouldn't be too hard for me to make a PR to remove the flag, it is a breaking change that should warrant some discussion, in case there is some facet to this that I am unfamiliar with.

**Comment by charles-lunarg** [comment]
Vulkan-Loader commit which removed the option to build statically for reference.
https://github.com/KhronosGroup/Vulkan-Loader/commit/161b28c1e9a9894ca11f67fc9593dbcf64866bfe

**Comment by elmindreda** [comment]
Yup, `GLFW_VULKAN_STATIC` is a misleading name and it should be deprecated, renamed or removed. Deprecating it now and removing it with the addition of #1374 seems good.

GLFW shouldn't emit that error regardless of the option setting, though. That might be a bug on our end. I tried reproducing the error but couldn't. In what environment did you encounter it?

**Comment by charles-lunarg** [comment]
Unfortunately, I was not the person who encountered this issue directly. So it may be incorrect usage of glfw on their end, and isn't worth investing a ton of time into reproducing. This person described their issue to me in a public chat (vulkan community discord) and so there isn't an easily accessible history that I could link.

Deprecation and removal is the route to go, as there just doesn't exist the ability to static link anymore. (Except if you are on macOS where you ship moltenVK with the app, but thats not even really supported, just allowed). 

Adding #1374 is good for users that want to manually load vulkan directly such as when using a fallback API if vulkan isn't supported or using volk/vulkan.hpp/glad to do function pointer loader. There shouldn't be any harm if an application loads the vulkan-1.dll multiple times since global state in the loader is kept to a minimum, so its not absolutely necessary to add 1374.

**Comment by elmindreda** [comment]
The `GLFW_VULKAN_STATIC` option has finally been removed and the `glfwInitVulkanLoader` function has been added just in case. Thank you for a much needed prodding!
