### ISSUE TITLE
Fix clang cl issue

### ISSUE THREAD

**Issue by hdf89shfdfs** [glfw/glfw#1780]
GLFW doesn't compile with clang-cl.

**Comment by hdf89shfdfs** [comment]
Here is how I fixed the issue locally.

Here is the clang-cl user manual:
https://clang.llvm.org/docs/UsersManual.html#clang-cl

```cmake
if ("${CMAKE_C_COMPILER_ID}" STREQUAL "Clang") 
    if ("${CMAKE_C_SIMULATE_ID}" STREQUAL "MSVC")
        set(glfw_clang_cl ON)
    else()
        set(glfw_clang ON)
    endif()
endif()

if ("${CMAKE_C_COMPILER_ID}" STREQUAL "GNU" OR
    glfw_clang OR glfw_clang_cl OR
    "${CMAKE_C_COMPILER_ID}" STREQUAL "AppleClang")

    # Make GCC and Clang warn about declarations that VS 2010 and 2012 won't
    # accept for all source files that VS will build
    set_source_files_properties(context.c init.c input.c monitor.c vulkan.c
                                window.c win32_init.c win32_joystick.c
                                win32_monitor.c win32_time.c win32_thread.c
                                win32_window.c wgl_context.c egl_context.c
                                osmesa_context.c PROPERTIES
                                COMPILE_FLAGS -Wdeclaration-after-statement)
    
    if (glfw_clang_cl)
        # This is equivalent to -Wall
        # https://clang.llvm.org/docs/UsersManual.html#clang-cl
        target_compile_options(glfw PRIVATE "/W1")
    else()
        # Enable a reasonable set of warnings (no, -Wextra is not reasonable)
        target_compile_options(glfw PRIVATE "-Wall")
    endif()
endif()
```

Basically without this change clang-cl essentially will compile with -Weverthing. Because -Wall becomes -Weverthing in clang-cl. That's because clang-cl tries to emulate MSVC. And -Wall is also a flag in MSVC. Which results in this unfortunate problem...

**Comment by hdf89shfdfs** [comment]
Here are the instructions for generating the necessary visual studio solution:
```
cmake -G"Visual Studio 2019" -T ClangCL ..
```

**Comment by Perksey** [comment]
What was the actual compiler error here before you fixed it? If it's regarding intrinsic.h, it (and some other clang errors) will be fixed in next month's Visual Studio 2019 preview version 16.9 Preview 2.

**Comment by elmindreda** [comment]
@Perksey No errors, just tons of not very useful warnings. They seem to have been fixed with 16.8.0, but it would be nice to have this work on earlier versions too.

**Comment by Perksey** [comment]
Fair enough.

**Comment by elmindreda** [comment]
@hdf89shfdfs Thank you!
