### ISSUE TITLE
USE_MSVC_RUNTIME_LIBRARY_DLL unnecessary for cmake 3.15 and above

### ISSUE THREAD

**Issue by jpr89** [glfw/glfw#1783]
In cmake 3.15 "CMAKE_MSVC_RUNTIME_LIBRARY" was introduced to solve the problem that GLFW's USE_MSVC_RUNTIME_LIBRARY_DLL  addresses.

Cmake Documentation:
https://cmake.org/cmake/help/latest/release/3.15.html#variables
https://cmake.org/cmake/help/latest/variable/CMAKE_MSVC_RUNTIME_LIBRARY.html#variable:CMAKE_MSVC_RUNTIME_LIBRARY

I propose 2 things.

1.)
If the client is using cmake 3.15 or above then don't bother making this variable at all. It really only confuses things since the official cmake approach will override whatever GLFW does anyway. This creates unnecessary build complexity/confusion.
Since users will have a cmake-gui option that doesn't do anything.

2.)
If this variable continues to exist prefix it with GLFW_* to make it clear what project it belongs to. In cmake-gui/ccmake you can order cache variables by Groups (Groups essentially just be prefixes). You can see what I mean in the picture below.
 
![image](https://user-images.githubusercontent.com/31327577/95607904-62f41680-0a2a-11eb-89f3-3702caaeed66.png)

In larger cmake projects, not using grouped entries confuses regular developers. Personally the first time I saw it, I thought it was part of cmake like BUILD_SHARED_LIBS.

**Comment by elmindreda** [comment]
> If the client is using cmake 3.15 or above then don't bother making this variable at all. It really only confuses things since the official cmake approach will override whatever GLFW does anyway. This creates unnecessary build complexity/confusion.
Since users will have a cmake-gui option that doesn't do anything.

Agreed, will fix.

> If this variable continues to exist prefix it with GLFW_* to make it clear what project it belongs to. In cmake-gui/ccmake you can order cache variables by Groups (Groups essentially just be prefixes). You can see what I mean in the picture below.

The name was picked because a number of other projects are also using it, so it may be a good idea to keep the current name.

**Comment by hdf89shfdfs** [comment]
"The name was picked because a number of other projects are also using it, so it may be a good idea to keep the current name."

Out of curiosity what other projects? The only I'm aware that does this is GLFW.

**Comment by hdf89shfdfs** [comment]
I've created a pull request:
https://github.com/glfw/glfw/pull/1796
