### ISSUE TITLE
Iconify then restore multiple window at the same time

### ISSUE THREAD

**Issue by VaderY** [glfw/glfw#180]
Hi, Iconify then restore multiple window at the same time like below will result only one window to be restored. Win 7 x64, glfw 3.0.3, mingw4.8.1

    GLFWwindow window;
    GLFWwindow window2;
    window = glfwCreateWindow(640, 480, "I wont come back", NULL, NULL);
    window2 = glfwCreateWindow(640, 480, "I will come back", NULL, NULL);
    //Some code here...
    glfwIconifyWindow(window);
    glfwIconifyWindow(window2);
    //Some code here...
    glfwRestoreWindow(window);
    glfwRestoreWindow(window2);

But Twisting the Iconify order will result both window to be restored just fine.

    GLFWwindow window;
    GLFWwindow window2;
    window = glfwCreateWindow(640, 480, "I will come back", NULL, NULL);
    window2 = glfwCreateWindow(640, 480, "I will come back too", NULL, NULL);
    //Some code here...
    glfwIconifyWindow(window2);
    glfwIconifyWindow(window);
    //Some code here...
    glfwRestoreWindow(window);
    glfwRestoreWindow(window2);

**Comment by elmindreda** [comment]
Is this still an issue with 3.1?

**Comment by VaderY** [comment]
Confirmed, its no longer an issue with 3.1+. (Sorry for the long delay, had no time)

**Comment by elmindreda** [comment]
@VaderY Thank you for the follow-up!
