### ISSUE TITLE
Creating a GLFW_MAXIMIZED and GLFW_DECORATED window on Windows causes window to overlap taskbar

### ISSUE THREAD

**Issue by Squareys** [glfw/glfw#1806]
As [requested](https://github.com/glfw/glfw/issues/899#issuecomment-730074468):

From #899, which was fixed to make `glfwMaximizeWindow()` maximize to workarea rather than to full screen size.

> This is still an issue for windows created with glfwWindowHint(GLFW_MAXIMIZED, GLFW_TRUE) and glfwWindowHint(GLFW_DECORATED, GLFW_FALSE).
> A possible workaround is to call glfwMaximizeWindow() after window creation.

A similar fix as with https://github.com/glfw/glfw/commit/80d181f12dbb3b19fa649638252fa90eacf3d6a2 is required for the initial creation of the window here.

Best,
Jonathan

**Comment by elmindreda** [comment]
This should finally be fixed now with a730acf8e50e7efa70e79e42c511a97f27c97e4d. Thank you for your patience!
