### ISSUE TITLE
Virus PUA:Win32/Puwaders.B!m possibly detected in master\CMakeFiles\3.19.1\CompilerIdC\a.exe

### ISSUE THREAD

**Issue by drsoaring** [glfw/glfw#1813]
Microsoft Defender on Windows 10 reported virus PUA:Win32/Puwaders.B!m detected in master\CMakeFiles\3.19.1\CompilerIdC\a.exe
Malwarebytes and ZoneAlarm did not report this as a virus.

**Comment by elmindreda** [comment]
Yup, this happens to me sometimes as well. Windows Defender sometimes doesn't like these binaries. It is not a virus, however.
