### ISSUE TITLE
error: Failed to initialize GLFW

### ISSUE THREAD

**Issue by qiaozun** [glfw/glfw#1814]
Hello
When I was developing on the Ubuntu 18.04 board, I changed the x11 display to wayland display by -DGLFW_USE_WAYLAND target, and then compiled to execute ./examples/boing and other demos, Error: Failed to initialize GLFW, and whether some special environment or configuration is needed for development on the board.

I have installed some of the packages I need：

$ apt-get install libxrandr-dev
$ apt-get install doxygen
$ apt-get install libwayland-dev
$ apt-get install wayland-protocols
$ apt-get install extra-cmake-modules

The version of wayland-protocols I installed through the command is 1.13, but I put the required xdg-decoration from the Internet to the corresponding path and generate the corresponding file.

**Comment by elmindreda** [comment]
Please try one of the programs that output the GLFW error description, for example glfwinfo, and post that here.

**Comment by qiaozun** [comment]
Ubuntu18.04 does not appear to support glfw3.3.2. GlfwInit succeeded after I changed to GLFW3.2.1.

**Comment by elmindreda** [comment]
Closing this as it sounds like this issue was resolved. If that's not the case, please re-open or post a follow-up.

**Comment by awsdert** [comment]
This seemed the appropriate place to dump this issue, I'm trying to initialise glfw on manjaro cinnamon, however I keep getting `Wayland: Failed to connect to display`, at 1st I though, maybe it's just an issue from being launched as a sub-process of make which was also a sub-process of geany (the editor I'm using) so I tried launching it directly but no dice, anyone know what I should look for (and probably edit) to resolve this?

**Comment by awsdert** [comment]
> @awsdert Do you have a Wayland compositor running? I haven't used Cinnamon for a while but at a glance it doesn't look as if it supports Wayland yet.

No, I had made the mistake of thinking cinnamon was switching to wayland also like other desktop managers, maybe they are but the version I was supposed to use was the X11 version, once I switched to that everything ran hunky dory (besides my own coding mistakes)
