### ISSUE TITLE
glfwDestroyWindow() erase data?

### ISSUE THREAD

**Issue by thewoz** [glfw/glfw#1835]
Hi I have a question.

after call glfwDestroyWindow() all the VertexArrays BufferData and so on will be destroy or I should call  glDeleteBuffers() and
        glDeleteVertexArrays() before call  glfwDestroyWindow()?

**Comment by tombsar** [comment]
OpenGL assets should all be freed automatically when the context is destroyed, so there is no need to delete everything individually.

**Comment by thewoz** [comment]
ok thanks
I take the "should" for good :)
