### ISSUE TITLE
Minecraft Forge Glfw error M1 apple silicon

### ISSUE THREAD

**Issue by dm312-1** [glfw/glfw#1841]
java.lang.IllegalStateException: GLFW error before init:
[0x10008]Cocoa: Failed to find service port for display

I don't know how to mention issues but here is the link to the main issue 

I found that no one brought it up down stream down here at the base level so yeah

https://github.com/MinecraftForge/MinecraftForge/issues/7558

**Comment by nevyn** [comment]
@dm312-1 I fixed this recently, and it's merged to master: https://github.com/glfw/glfw/pull/1833

**Comment by ll3macorn** [comment]
it is still doing it lmao

**Comment by dm312-1** [comment]
This is closed. Minecraft did not update
