### ISSUE TITLE
Detect Retina Display

### ISSUE THREAD

**Issue by thewoz** [glfw/glfw#1842]
Hi,
there is a way to detect if a program is running on a Retina display?
thanks

**Comment by papr** [comment]
@thewoz Checkout https://www.glfw.org/docs/latest/window_guide.html#window_scale

Also, be aware that `framebuffer size = 2 * window size` on retina displays.

**Comment by thewoz** [comment]
if I understand correctly in retina display the framebuffer size is twice the window size.
Thus if I call glfwGetWindowContentScale() I should get xscale and yscale equal to two. right?

**Comment by orange451** [comment]
xscale and yscale = glfwGetWindowSize() / glfwGetFramebufferSize()

**Comment by orange451** [comment]
Other way around, actually. Apologies. Cant edit email comments...

**Comment by thewoz** [comment]
ok I will try.
May be it would be nice in the future to add a bool glfwDetectRetina() in the API :)

**Comment by papr** [comment]
@thewoz 
>  May be it would be nice in the future to add a bool glfwDetectRetina() in the API :)

I do not think this would be worth it, given that `glfwGetWindowContentScale()` already exists, which is cross-platform compatible. Each new API comes with a high burden for the maintainer.

**Comment by thewoz** [comment]
You are in  right!
