### ISSUE TITLE
GLFW with glad leads to opengl version inconsistency and native window crashing when setting opengl to use core profile

### ISSUE THREAD

**Issue by Pikachuxxxx** [glfw/glfw#1849]
OS and version: windows 10 1909
GPU and driver: Geforce RTX 2060 461.40
Release or commit: Stable3.3
Version string: Opengl 4.6

`glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE)` setting up this window hint messes up the opengl version when used with third party dependencies such as Dear Imgui, the GL_VERSION is set to 0.0 and also leads to inconsistent crashing of  `glfwGetWin32Window` because it receives a nullptr

**Comment by tombsar** [comment]
Would you mind sharing a few more details about your application? I exclusively use core profile, and I haven't run into any problems with either glad or dear imgui.

What are you setting the other context hints to? i.e. `GLFW_CONTEXT_VERSION_MAJOR`, `GLFW_CONTEXT_VERSION_MINOR`, and `GLFW_OPENGL_FORWARD_COMPAT`.

**Comment by Pikachuxxxx** [comment]
I tried it with 3.3, and from 4.1-4.6, while doing this `GLFW_OPENGL_FORWARD_COMPAT` = true/false. The `glfwCreateWindow` returns a nullptr. Is it because since I downloaded glad with just coreprofile means that glfw need not set this windowHint explicitly. Every time I enable this I get a NULL window. Disabling that window hint makes sure everything works fine.

Here's the little snippet from my engine:

```

 RZX_CORE_INFO("Creating Window... \n \t\t\t Title : {0} (Width : {1}, Height : {2})", properties.Title, properties.Width, properties.Height);

        // TODO: Replace all this with WIN32 API
        if (!sGLFWInitialized)
        {
            int success = glfwInit();
            RZX_CORE_ASSERT(success, "Could not initializr GLFW");

            sGLFWInitialized = true;
        }

        glfwWindowHint(GLFW_VERSION_MAJOR, 4);
        glfwWindowHint(GLFW_VERSION_MINOR, 6);
        glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE); // Disabling this solved the multi viewports crashing error
        #ifdef __APPLE__
        glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, true);
        #endif
        // Crashes because of this !!!
        m_Window = glfwCreateWindow((int)properties.Width, (int)properties.Height, properties.Title.c_str(), nullptr, nullptr);
        
        m_Context = new OpenGLContext(m_Window);
        // ^
        //glfwMakeContextCurrent(m_WindowHandle);
        //int status = gladLoadGLLoader((GLADloadproc)glfwGetProcAddress);
        //RZX_CORE_ASSERT(status, "Cannot initialize GLAD!");
        m_Context->Init();

        glfwMakeContextCurrent(m_Window);

        glfwSetWindowUserPointer(m_Window, &m_Data);
```

**Comment by Pikachuxxxx** [comment]
In addition to this the `glfwNativeWindow` sometimes (used by ImGui) gets a null `HWND` when used that particular window hint.

**Comment by tombsar** [comment]
If `glfwCreateWindow` is returning NULL, something is going wrong with trying to create the OpenGL context - that shouldn't have anything to do with glad or dear imgui, which are only initialized later. You should probably check for a NULL window pointer and terminate your code at that point, rather than trying to continue.

You might get more information about the error with an error callback: https://www.glfw.org/docs/3.0/group__error.html

**Comment by Pikachuxxxx** [comment]
![image](https://user-images.githubusercontent.com/45527623/107964174-0784f700-6fcf-11eb-92d5-8e6d9d853c7d.png)
So what this means is that the error is being reported for every window hint, I never had such an issue

**Comment by tombsar** [comment]
Oh, spotted the error. You are passing `GLFW_VERSION_MAJOR` where it should be `GLFW_CONTEXT_VERSION_MAJOR`, and the same for `MINOR`.

**Comment by Pikachuxxxx** [comment]
Blimey me! I had 10 people look at this code and you're the one who spotted it. Thanks for  it. Stupid Macro!!!
