### ISSUE TITLE
glfwUpdateGamepadMappings doesn't update gamepad name

### ISSUE THREAD

**Issue by KiralyCraft** [glfw/glfw#1850]
OS and version: Ubuntu L4T 18.04 REL32
Release: 3.3.2 (Official)
Error messages: None

I've been trying to update gamepad mappings with some in SDL format using a gamecontrollerdb.txt file. I am doing this with reVC, and [here](https://github.com/GTAmodding/re3/blob/bf7280b55bffd568b00d5145f5799c7f73114ffc/src/skel/glfw/glfw.cpp#L885 ) is the part that handles controllers. 

The contents of the file are: 
```
060000004e696e74656e646f20537700,Cheese,a:b0,b:b1,back:b9,dpdown:b15,dpleft:b16,dpright:b17,dpup:b14,guide:b11,leftshoulder:b5,leftstick:b12,lefttrigger:b7,leftx:a0,lefty:a1,rightshoulder:b6,rightstick:b13,righttrigger:b8,rightx:a2,righty:a3,start:b10,x:b3,y:b2,platform:Linux,
```
And I've added this piece of code to identify controllers:
```
debug("Using controller: \"%s\" with GUID: %s\n",glfwGetJoystickName(PSGLOBAL(joy1id)),glfwGetJoystickGUID(PSGLOBAL(joy1id)));
```
However, this line is still printing:
> [DBG]: Using controller: "Nintendo Switch Combined Joy-Cons" with GUID: 060000004e696e74656e646f20537700

Instead of "Cheese". I have added the line after the `if (PSGLOBAL(joy1id) != -1) {` line, and the devs confirmed this was unexpected too.

EDIT: The actual mappings are updated, and the update on line 902 does not fail. It is only the name that stays the same.

**Comment by elmindreda** [comment]
The joystick name isn't affected by the gamepad mapping. See [glfwGetGamepadName](https://www.glfw.org/docs/3.3.2/group__input.html#ga5c71e3533b2d384db9317fcd7661b210) to get the name that the mapping associated with the device. This name should update if the mapping is successfully parsed. If it isn't, that will need to be fixed.

**Comment by KiralyCraft** [comment]
Sorry for the late reply. Unfortunately, I no longer have the test environment set up. If I recall correctly, the name never updated. The repository I was working on was sadly taken down. I will spin up another testing scenario in the near future and re-test.

**Comment by elmindreda** [comment]
I'm going to assume based on the code provided that the issue was checking the joystick name, no the gamepad [mapping] name. If this issue was caused by something else, please re-open or post a follow-up.
