### ISSUE TITLE
mingw-w64 build absent

### ISSUE THREAD

**Issue by fastrgv** [glfw/glfw#1852]
25feb21
In the main website, when I download the prebuilt binaries for Windows64 (v3.3.3)
I do not see any lib-minw-w64 directory. 
Thx.

**Comment by sduzzx857** [comment]
me neither...

**Comment by fastrgv** [comment]
I have since learned that the "glfw3.dll" file under ./lib-static-ucrt/ works for my APP that requires a mingw-64 dll. But I still think that should be officially clarified!

**Comment by elmindreda** [comment]
This was my mistake. I forgot to run the MinGW-w64 build script for 3.3.3 and so those were left out. I will be releasing 3.3.4 as soon as possible to correct for this. I've merged the various Windows build scripts so this never happens again.

The static UCRT files do mostly work as a replacement in the meantime but not fully.

**Comment by fastrgv** [comment]
Thank You Camilla.
