### ISSUE TITLE
glfwSetWindowIcon segfaults if image is NULL

### ISSUE THREAD

**Issue by brenthuisman** [glfw/glfw#1862]
`glfwSetWindowIcon` checks if the passed image array has at least one image, but it doesn't check that the image(s) have pixels. If you pass in a 0x0 image (which in my case `stbi_load` unfortunately generates when it couldn't find the file I asked it to open), `glfwSetWindowIcon` segfaults, because it tries to access the pixel data:
https://github.com/glfw/glfw/blob/4afa227a056681d2628894b0893527bf69496a41/src/x11_window.c#L2121

It would be nice if there could be a check and an error thrown.

**Comment by elmindreda** [comment]
The way I see it, the error is signaled by `stbi_load` returning NULL and that is where your error check should be. If GLFW is compiled in debug mode then there are also asserts that will catch stray NULL pointers passed into GLFW, and many other kinds of invalid values.

GLFW currently does not check for invalid pointers resulting from application bugs, as opposed to bugs in GLFW or the operating system, which it does try to check for.

**Comment by brenthuisman** [comment]
That is indeed what we do now (check for null). Didn't know that debug mode will warn me about this, thanks!

Since I couldn't come up with a scenario in which `glfwSetWindowIcon` could continue with a 0x0/null input, it made sense to mention it here.

**Comment by elmindreda** [comment]
Turns out there were a bunch of missing checks and asserts for `GLFWimage` related functions, including for this case. They should be in place now with 66a4882eb14344115e9cda9f8c0f0c5d0362ca6e. Thank you for reporting this!
