### ISSUE TITLE
Turning on/off window decorations while in full screen won't work properly.

### ISSUE THREAD

**Issue by p-pap** [glfw/glfw#1863]
When I am switching on/off window decorations in full screen mode, then return back to windowed mode, the change is not visible, although `glfwGetWindowAttrib()` reports that `GLFW_DECORATED` was changed correctly. For example, assume the window has decorations on, I switch to full screen and turn decorations off; then I switch back to windowed mode, and I still see the decorations, although `GLFW_DECORATED` is set to `GLFW_FALSE` (0). Note that the problem appears only when I try to switch on/off decoration in full screen mode.
I am using GLFW 3.3.3 on GNU/Linux 64-bit. Display server is X11 and window manager is XFCE. The code used is as follows.
```
void toggleFullScreen(GLFWwindow* window, GLFWmonitor **monitor) {
  static int xpos,ypos,width,height;
  const GLFWvidmode* mode;
  if (*monitor==NULL) {
    glfwGetWindowPos(window, &xpos, &ypos);
    glfwGetFramebufferSize(window, &width, &height);
    *monitor=glfwGetPrimaryMonitor();
    mode=glfwGetVideoMode(*monitor);
    glfwSetWindowMonitor(window, *monitor, 0, 0, mode->width, mode->height,
                         mode->refreshRate);
  } else {
    *monitor=NULL;
    glfwSetWindowMonitor(window, *monitor, xpos, ypos, width, height, 0);
  }
}

void toggleWindowDecorations(GLFWwindow* window) {
    glfwSetWindowAttrib(window, GLFW_DECORATED, !glfwGetWindowAttrib(window, GLFW_DECORATED));
}

void keyCallback(GLFWwindow* window, int key, int scancode, int action,
                 int mods) {
  switch (key) {
  case GLFW_KEY_ESCAPE:
    running=0; break;
  case GLFW_KEY_D:
    if (action==GLFW_RELEASE) toggleWindowDecorations(window); break;
  case GLFW_KEY_ENTER:
    if (action==GLFW_RELEASE) toggleFullScreen(window, &currentMonitor); break;
  }
}
```

**Comment by elmindreda** [comment]
Thank you for reporting this! It should be fixed now with 4afa227a056681d2628894b0893527bf69496a41.
