### ISSUE TITLE
how does one call eglGetPlatformDisplayEXT on the EGL context created by GLFW, I need to specify custom display attributes

### ISSUE THREAD

**Issue by LAX1DUDE** [glfw/glfw#1866]

**Comment by LAX1DUDE** [comment]
Hi I am using ANGLE and I am required to call eglGetPlatformDisplayEXT with a custom attribute set for selecting a specific backend (d3d, opengl, vulkan, etc). I can't find a way to use this function in the EGL environment created by GLFW because it appears to be hard coded somewhere in the glfwCreateWindow function with no customization available

**Comment by elmindreda** [comment]
Currently yes, that is true. The main branch has the [GLFW_ANGLE_PLATFORM_TYPE](https://www.glfw.org/docs/3.4/intro_guide.html#GLFW_ANGLE_PLATFORM_TYPE_hint) init hint for selecting the ANGLE backend but the full range of options from the ANGLE EGL extensions is not currently supported.

**Comment by LAX1DUDE** [comment]
than you, GLFW_ANGLE_PLATFORM_TYPE is what I needed
