### ISSUE TITLE
MinGW-w64  unknown type name ‘POINTER_INPUT_TYPE’ 

### ISSUE THREAD

**Issue by batcholi** [glfw/glfw#1871]
The CMakeLists of glfw will add a compile definition WINVER=0x0501
which I think is a version of the windows API that is too old for certain features of GLFW. 
I can "fix" the error by overriding the compile definition after including glfw's CMakeLists to set a more recent windows api version (0x0A00 in my specific case), altough it causes a warning instead, because of the redefinition of WINVER.

**Comment by elmindreda** [comment]
This is not a bug, it's a feature! Bits of the Win32 API newer than Windows XP need to be declared in `win32_platform.h`, so we can build on really old versions of VS and make sure we dynamically load any API function not available on XP. That's unfortunately the cost of backward compatibility.

It's a good idea to override `WINVER` the way you describe during development, however, so one doesn't need to start out doing that when experimenting with solutions.
