### ISSUE TITLE
Linker Error on Windows x86 with GLFW_VULKAN_STATIC enabled

### ISSUE THREAD

**Issue by jaredmulconry** [glfw/glfw#1878]
OS and version: Windows 10 64-bit
Compiler version: Visual Studio 16.9.3 Toolset v142
Release or commit: 3.3.3
Vulkan Instance Version: 1.2.148
Building from source

The source of the issue logged below appears to be the forward declaration of vkGetInstanceProcAddr and vkEnumerateInstanceExtensionProperties in internal.h. The Vulkan API (vulkan_core.h) specifies those two functions as __stdcall on Windows, but the forward declarations in GLFW do not. When statically linking, this causes the linker error below on x86. Not an issue for x64 as __stdcall is ignored on x64, so both have a default __cdecl calling convention. Adding a __stdcall or equivalent to the forward declarations in internal.h resolves this issue.
Relevant CMake configuration information attached

Build Log:
Rebuild started...
1>------ Rebuild All started: Project: Vulkan, Configuration: Release Win32 ------
1>main.cpp
1>glfw3.lib(vulkan.obj) : error LNK2001: unresolved external symbol _vkGetInstanceProcAddr
1>glfw3.lib(win32_window.obj) : error LNK2001: unresolved external symbol _vkGetInstanceProcAddr
1>  Hint on symbols that are defined and could potentially match:
1>    _vkGetInstanceProcAddr@8
1>glfw3.lib(vulkan.obj) : error LNK2001: unresolved external symbol _vkEnumerateInstanceExtensionProperties
1>  Hint on symbols that are defined and could potentially match:
1>    _vkEnumerateInstanceExtensionProperties@12
1>C:\Users\jared\source\repos\Vulkan\Release\Vulkan.exe : fatal error LNK1120: 2 unresolved externals
1>Done building project "Vulkan.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

![image](https://user-images.githubusercontent.com/9778934/113401104-98345c80-93ee-11eb-9186-a6da66865f42.png)

**Comment by charles-lunarg** [comment]
Vulkan-Loader no longer supports static linking on Windows and Linux (but has an exception for Apple).
https://github.com/KhronosGroup/Vulkan-Loader/blob/master/loader/LoaderAndLayerInterface.md#static-linking

This issue shows that GLFW is trying to statically link these functions but cannot find them, which is expected since there is no static library available for the Vulkan-Loader. 

PR #1890 restricts the `GLFW_STATIC_LOADER` option to Apple platforms which prevents this situation on windows/linux.

**Comment by elmindreda** [comment]
This is fixed now by removing this CMake option altogether, thanks to @charles-lunarg. See `glfwInitVulkanLoader` in the main branch if you need to point the library to a specific Vulkan loader.
