### ISSUE TITLE
glfw "Wayland: Failed to connect to display" error message in an Xorg session

### ISSUE THREAD

**Issue by Venemo** [glfw/glfw#1880]
The `glfwInit()` function fails with the following message: `Wayland: Failed to connect to display`

I'm running an Xorg session. Why does glfw try to connect to a Wayland display?

**Comment by gracicot** [comment]
As far as I know glfw cannot choose at runtime of it uses Wayland or X. It is specified in the compile flags and implemented as a CMake option. Try recompiling glfw without Wayland support to make it work on X.

**Comment by Venemo** [comment]
I see. I think then the problem is that Fedora (the Linux distro I use) ships it with Wayland enabled.

**Comment by Venemo** [comment]
If choosing between the two in runtime is not supported, then I think I'll just close this issue now. Thank you for your quick answer.

**Comment by IzzDarki** [comment]
Do I need to compile glfw with either X11 or Wayland and add the compiled library to my project?
Or is there another way to specifiy if I want it to use X11 or Wayland before building (maybe with CMake?) while still linking against the glfw library provided by the system?
