### ISSUE TITLE
Documentation of glfwGetVideoModes sort order isn't exhaustive

### ISSUE THREAD

**Issue by CuriouserThing** [glfw/glfw#1889]
Documentation of `glfwGetVideoModes` omits the final search criteria, width and refresh rate.

https://github.com/glfw/glfw/blob/33cd8b865d9289cfbcf3d95e6e68e4050b94fcd3/include/GLFW/glfw3.h#L2418-L2421

https://github.com/glfw/glfw/blob/33cd8b865d9289cfbcf3d95e6e68e4050b94fcd3/src/monitor.c#L51-L64

**Comment by elmindreda** [comment]
Thank you!
