### ISSUE TITLE
GLFW_OPENGL_CORE_PROFILE prevents app from creating window

### ISSUE THREAD

**Issue by lfg-oliveira** [glfw/glfw#1894]
Whenever I use CORE_PROFILE as a window hint, the program cannot create the window. It is however possible to get over this using ANY_PROFILE. The following code will exit with an error because it is impossible to create the window.

```
#include <GLFW/glfw3.h>
#include <iostream>
int main(){
	glfwInit();
	glfwWindowHint(GLFW_VERSION_MAJOR, 3);
	glfwWindowHint(GLFW_VERSION_MINOR, 3);
	glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE); // line 1
        // glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_ANY_PROFILE); // line 2
	auto window = glfwCreateWindow(800,600,"Test", NULL, NULL);
	if(!window) {
		std::cout << "Unable to create window" << std::endl;
		return 1;
	}
	return 0;
}

```
However if I comment line 1 and uncomment line 2, the program runs just fine.

Some info about my system:
OS: Artix Linux
CPU: 7th gen Core i5
GPU: Nvidia 1050 4gb
Build system: Cmake

**Comment by tombsar** [comment]
You are mistakenly using `GLFW_VERSION_MAJOR` and `GLFW_VERSION_MINOR` instead of `GLFW_CONTEXT_VERSION_MAJOR` and `GLFW_CONTEXT_VERSION_MINOR`.
