### ISSUE TITLE
Vulkan instance missing VK_KHR_win32_surface extension

### ISSUE THREAD

**Issue by Moocow9m** [glfw/glfw#1900]
I have a vkinstance made using the tutorial here: https://vulkan-tutorial.com/Drawing_a_triangle/Presentation/Window_surface

I can initialize the surface using `vkCreateWin32SurfaceKHR` but `glfwCreateWindowSurface` complains of a missing extension that I know is enabled(`VK_KHR_win32_surface`). 

I have (GLFW: 3.3.4), (Vulkan 1.2.176.1), (Nvidia Drivers: 466.27).
All libraries are linked dynamically at runtime(dll for glfw and vulkan are in a specified folder at runtime)

**Comment by Moocow9m** [comment]
After lengthy experimentation, turns out the was a simple solution... Vulkan being linked at runtime in a designated location seems to break GLFW. By linking with the system dll(C://Windows/System32/vulkan-1.dll), I am able to create a surface though GLFS. However, this breaks the idea of system independent code I was using.

**Comment by elmindreda** [comment]
Yeah, that can happen and it's incredibly frustrating to debug when it does. Looking into adding a feature that will let one point GLFW at a specific Vulkan loader.
