### ISSUE TITLE
the header version in the glfw 3.4 release still says glfw 3.3

### ISSUE THREAD

**Issue by coderedart** [glfw/glfw#1905]
I don't know if it is supposed to be that way, but i was trying to use the latest glfw 3.4 as i needed the window hint GLFW_MOUSE_PASSTHROUGH. 

when i download the zip file of source, i see that the headers in the include folder still say glfw 3.3 and they don't have the mouse_passthrough hint.

**Comment by gracicot** [comment]
Most likely you link to the wrong glfw version. Something like you have the correct include directory, but you're still using your system's glfw library to link against.

**Comment by coderedart** [comment]
OH, i am sorry. it seems i got confused between 3.4 and 3.3.4.  i was looking at the docs of https://www.glfw.org/docs/3.4/window_guide.html#GLFW_MOUSE_PASSTHROUGH_hint

and was using the glfw 3.3.4 libraries. and comparing it to the master branch of the repo which has 3.4 headers. so, i thought the release accidentally included the wrong headers from the previous release. 

apologies for wasting your time :(

**Comment by tombsar** [comment]
I was about to say, I didn't think 3.4 had released yet. No worries!
