### ISSUE TITLE
glfwInit() hangs on MacOS (M1)

### ISSUE THREAD

**Issue by undersquire** [glfw/glfw#1915]
This issue occurs on the latest version of GLFW (3.3.4) when calling `glfwInit();` on MacOS, and causes the application to hang indefinitely. This issue is coming from my [other issue from the raylib library.](https://github.com/raysan5/raylib/issues/1817)

I'm not entirely sure what else to provide, but here is the code raylib uses to initialize glfw:

`glfwSetErrorCallback(ErrorCallback);`

`#if defined(__APPLE__)`
    `glfwInitHint(GLFW_COCOA_CHDIR_RESOURCES, GLFW_FALSE);`
`#endif`

   ` if (!glfwInit())`
    `{`
       ` TRACELOG(LOG_WARNING, "GLFW: Failed to initialize GLFW");`
        `return false;`
    `}`

**Comment by benbeshara** [comment]
I can't reproduce this on my machine - do you have any log output to share? This is what I get from my code atm:
```
INFO: Initializing raylib 3.7
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 1280 x 800
INFO:     > Render size:  800 x 450
INFO:     > Screen size:  800 x 450
INFO:     > Viewport offsets: 0, 0
INFO: GL: Supported extensions count: 43
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Apple
INFO:     > Renderer: Apple M1
INFO:     > Version:  4.1 Metal - 71.0.7
INFO:     > GLSL:     4.10
INFO: TEXTURE: [ID 1] Texture loaded successfully (1x1 - 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Vertex shader compiled successfully
INFO: SHADER: [ID 2] Fragment shader compiled successfully
INFO: SHADER: [ID 3] Program shader loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
INFO: RLGL: Default OpenGL state initialized successfully
INFO: TEXTURE: [ID 2] Texture loaded successfully (128x128 - 1 mipmaps)
INFO: FONT: Default font loaded successfully
INFO: TIMER: Target time per frame: 16.667 milliseconds
```
Also, what does your window initialisation code/main function look like? I find that if the program isn't boilerplated appropriately or something fails before the main loop, it sometimes fails after the window initialisation but before the drawing routines
```C
#include "raylib.h"

int main(void) {
  const int screenWidth = 800;
  const int screenHeight = 450;

  InitWindow(screenWidth, screenHeight, "Basic Window");

  SetTargetFPS(60);

  while (!WindowShouldClose())
  {
    BeginDrawing();

    ClearBackground(RAYWHITE);

    EndDrawing();
  }

  CloseWindow(); // Close window and OpenGL context

  return 0;
}
```

**Comment by elmindreda** [comment]
@undersquire I cannot reproduce this on any Mac I have, using Raylib or other examples, and unfortunately I don't have an M1 machine. I looked in the linked issue. Were you able to get a call stack inside `glfwInit` and see where exactly it had deadlocked?

**Comment by undersquire** [comment]
I am on an M1 Mac, which may make the difference. I did not even get a call stack in glfwInit, as it didn't deadlock. It just hangs there, no errors/crashes. I will try to debug the glfw source code inside glfwInit.

**Comment by undersquire** [comment]
Interestingly, I was able to get raylib running now (I guess there was something wrong with my cloned repo before?). It does not hang anymore but has lots of visual problems. I have no idea why it was hanging like this before.

**Comment by elmindreda** [comment]
That is weird, but yay for working and thank you for the follow-up! Please bump this or open a new issue if it happens again. Hopefully I will have access to a newer machine by then.
