### ISSUE TITLE
GLFW.glfwGetMonitorPhysicalSize returns 0 inside VirtualBox

### ISSUE THREAD

**Issue by ichernev** [glfw/glfw#1916]
First reported here: https://github.com/libgdx/libgdx/issues/6537

Basically `GLFW.glfwGetMonitorPhysicalSize` returns 0 inside VirtualBox (Linux guest/host). The docs says it returns an approximation, so I guess it makes sense to guess something rather than return 0 (which is infinite orders of magnitude worse :))

**Comment by elmindreda** [comment]
What version of GLFW are you running on the guest, and is it X11 or Wayland? There is a workaround in both backends now that assumes 96 DPI and derives the physical size from that if the OS doesn't provide that data.

**Comment by ichernev** [comment]
It is X11, the version ... whatever is bundled with libgdx 1.10.0, I couldn't figure it out :(

If the problem is fixed on master (assuming 96 DPI is fine), you can close this without worries :)
