### ISSUE TITLE
GLFW_MOUSE_PASSTHROUGHT does not exist

### ISSUE THREAD

**Issue by wawahuy** [glfw/glfw#1917]
- Lib: 3.3.4
- Visual studio 2019
`glfwSetWindowAttrib(window, GLFW_MOUSE_PASSTHROUGH, true);`
GLFW_MOUSE_PASSTHROUGHT does not exist

**Comment by tombsar** [comment]
The mouse passthrough feature is set to be added in the next minor release (https://github.com/glfw/glfw/issues/1236#issuecomment-658914060). If you want to preview it, you should check out the master branch rather than using 3.3.4.
