### ISSUE TITLE
GLFW tries to connect to Wayland display in an X11 session

### ISSUE THREAD

**Issue by octowaddle** [glfw/glfw#1919]
Calling `glfwInit()` results in the following errors:

```
GLFW error occurred (65544): Wayland: Failed to connect to display.
sandbox: /builddir/build/BUILD/glfw-3.3.4/src/posix_thread.c:64: _glfwPlatformGetTls: Assertion `tls->posix.allocated == GLFW_TRUE' failed.
```

I am not using Wayland though:

```
$ echo $XDG_SESSION_TYPE
x11
```

I am using Fedora with the DNF package manager. I think this could also be due to incorrect packaging but I don't know for sure.

**Comment by tombsar** [comment]
At the moment glfw is compiled for either X11 or Wayland, and cannot choose at runtime. IIRC Fedora ships with Wayland as default these days, so it makes sense that they are distributing glfw compiled for Wayland.

I'd suggest downloading and compiling glfw yourself, if that's possible. IMO the best solution might be for Fedora to provide separate glfw-wayland and glfw-x11 packages, but that's out of our control (and there's probably a good reason not to; I'm not very knowlegeable about packaging).

See also https://github.com/glfw/glfw/issues/1880

**Comment by octowaddle** [comment]
That's what I thought. Thank you for your advice!
