### ISSUE TITLE
PS5 DualSense controller not detected

### ISSUE THREAD

**Issue by mokiat** [glfw/glfw#1920]
Hi,

I have an app where I am successfully able to use a PS4 DualShock controller. However, the PS5 DualSense controller is not detected for some reason. I have verified with a commercial app that the controller is properly wired and at least the axis are measured correctly.

Has anyone tried with the PS5 DualSense controller? Is this a feature that is missing due to the controller still being fairly new, a bug, or am I doing something wrong?

I am using `Ubuntu 20.04.2 LTS` and I believe `libglfw3-dev/focal 3.3.2-1 amd64` is the version of GLFW I am using.

Sorry if this is not the correct channel to report this. I wasn't sure if this is a bug, feature request, or a question, so could figure out on whether to write it here or in the dev blogs.

**Comment by mokiat** [comment]
P.S. Ok, I did some investigating, which I should have done beforehand, and it seems that `glfwJoystickPresent` returns `true` for `GLFW_JOYSTICK_1` but `glfwJoystickIsGamepad` returns `false`.

Maybe glfw does not yet contain mappings for the buttons and axes for DualSense?

**Comment by ambye85** [comment]
The latest [controllerdb.txt](https://github.com/gabomdq/SDL_GameControllerDB/) has support for PS5 on Linux. You can download it and update your controller mapping at runtime with `glfwUpdateGamepadMappings`, e.g.:

```
curl https://raw.githubusercontent.com/gabomdq/SDL_GameControllerDB/master/gamecontrollerdb.txt --output "${SCRIPT_DIR}/../data/gamecontrollerdb.txt"


struct debug_file mappings = debug_file_read("data/gamecontrollerdb.txt");
if (mappings.data) {
    glfwUpdateGamepadMappings(mappings.data);
}
```

**Comment by mokiat** [comment]
Thank you, I will give it a try.

**Comment by mokiat** [comment]
Yes, using the latest SDL mappings works. Thanks again.
