### ISSUE TITLE
How to make a menu bar?

### ISSUE THREAD

**Issue by AnnoyingB** [glfw/glfw#1921]
I would like to make a menu bar with glfw but I don't know how to. I don't really prefer using cocoa but is there any way to use glfw for the windows etc and glut for the menu bars and popup menus etc?

**Comment by tombsar** [comment]
Drawing GUIs etc is really out of scope for glfw, so you'll need to use an extra library. I don't think glfw plays well with glut, but https://github.com/ocornut/imgui is great for making functional GUIs (although they won't look the same as native or cross-platform ones).

**Comment by AnnoyingB** [comment]
Yes I am using ImGui.
