### ISSUE TITLE
[macOS 10.15.7][GLFW 3.3.2] Key callback no longer invoked after 6 keys pressed

### ISSUE THREAD

**Issue by jameskr97** [glfw/glfw#1924]
I work on a rhythm game where it's not unusual for a user to possibly be holding down 6+ keys while using spare fingers to tap some other keys. I'm rewriting our input system, using GLFW at the backend, and I've noticed that when I'm pressing and holding 6 keys, and try pressing more, I get no output from the callback. I've only been able to test this on macOS.

[Here is a gist](https://gist.github.com/jameskr97/fb081e887160213a2a0834cdf1edc96d) with the least amount of code I need to reproduce this.

**Comment by tombsar** [comment]
The number of simultaneous keypresses is usually (in my limited experience) limited by the keyboard hardware, not the software stack. It also depends on which keys are pressed at the same time, as different groups share circuits.

Are you able to test a) a different keyboard on the same system, and b) the same keyboard in a piece of software that doesn't use glfw?

**Comment by jameskr97** [comment]
Oh you're right. It's a hardware issue. Switching software had no change, switching keyboards did change it. Thanks for helping me figure that out.
