### ISSUE TITLE
Memory leak from `XRegisterIMInstantiateCallback`

### ISSUE THREAD

**Issue by Th3T3chn0G1t** [glfw/glfw#1929]
Heya, sorry if this is already mentioned but looking up this particular function call in relation to GLFW memory leaks gives nothing on Google.

GLFW seems to leak a few bytes from a call to `XRegisterIMInstantiateCallback` in x11_init here: https://github.com/glfw/glfw/blob/6876cf8d7e0e70dc3e4d7b0224d08312c9f78099/src/x11_init.c#L1378 (at least on trunk that's where it is) according to valgrind:
```
408 bytes in 1 blocks are definitely lost in loss record 840 of 939
calloc (vg_replace_malloc.c:1117)
_XimOpenIM (in /usr/lib/libX11.so.6.4.0)
_XimRegisterIMInstantiateCallback (in /usr/lib/libX11.so.6.4.0)
XRegisterIMInstantiateCallback (in /usr/lib/libX11.so.6.4.0)
_glfwPlatformInit (x11_init.c:1378)
glfwInit (init.c:243)
...
main (main.c:81)
```

I am calling `glfwTerminate` and this is the only "definitely lost" leak that valgrind reports for GLFW.

Its possible that this is an issue with X11 since it seems like `XUnregisterIMInstantiateCallback` does get called in `_glfwPlatformTerminate` for X targets - but I thought it would be better to mention it here first just to check.

The version of GLFW in my repo is at master at the time I sent this, I'm compiling using CMake as a dynamic lib under Arch with Zen 5.12.14, with x11 6.4.0 (according to the version number in the library name).

Since the code block this is in seems to deal with locale code - I am using `en_IE.UTF-8` according to `$LANG` with no other locale env vars set. The same thing does seem to happen with `LC_ALL=C valgrind --leak-check=full ...`

If you need any other details just give me a holler!

**Comment by elmindreda** [comment]
The leak seems to be from the call to `XOpenIM` by our `inputMethodInstantiateCallback` callback.

Running valgrind with debug symbols, it points [here](https://github.com/mirror/libX11/blob/libX11-1.7.0/modules/im/ximcp/imInt.c#L207), so the allocation of the XIM object itself. Debugging this I can see `XCloseIM` being called with the correct pointer and pass it to `free`. This could be a false positive or an incorrect attribution by the debug symbols. I don't remember how to get valgrind to output the address of the leaked block, so I can't be sure.

**Comment by Th3T3chn0G1t** [comment]
The trace doesn't seem to show any calls originating in `inputMethodInstantiateCallback`? The call to `XRegisterIMInstantiateCallback` itself seems to leak

**Comment by Th3T3chn0G1t** [comment]
I'll set a BP and try to verify the trace through `lldb`

**Comment by Th3T3chn0G1t** [comment]
Yeah it seems like it is actually some internal call to `_XOpenIM` in `XRegisterIMInstantiateCallback` which isn't being cleaned up - is there a possibility that this is a bug in X11 where `XUnregisterIMInstantiateCallback`doesn't cleanup properly?

**Comment by Th3T3chn0G1t** [comment]
On looking closer - X11 doesn't seem to be cleaned up much at all through `glfwTerminate` as a "still reachable block" is generated by `XOpenDisplay`:
```
3 bytes in 1 blocks are still reachable in loss record 15 of 4,141
malloc (vg_replace_malloc.c:380)
strdup (in /usr/lib/libc-2.33.so)
XOpenDisplay (in /usr/lib/libX11.so.6.4.0)
_glfwPlatformInit (x11_init.c:1343)
glfwInit (init.c:243)
...
main (main.c:89)
```
Is it possible `_glfwPlatformTerminate` is made ineffective by my config or smthn?

**Comment by elmindreda** [comment]
I think this is a false positive. Reading the code to `XOpenIM`, `_XimOpenIM` and `XCloseIM`, I can't see how the XIM struct wouldn't be freed. Also, since Xlib is using standard library `calloc` and `free`, I tried freeing it myself right after `XCloseIM` and got a report where valgrind complains both about a leak and a double free for seemingly the same block.

If more information turns up showing that GLFW is misusing some API, please post a follow-up or create a new issue. I want every memory leak fixed, but right now this doesn't seem to be one.
