### ISSUE TITLE
[Question] Why pass GLFWwindow into clipboard string functions?

### ISSUE THREAD

**Issue by Journeyman-dev** [glfw/glfw#1945]
Isn't the clipboard global? Why do we need to pass in a window into glfwGetClipboardString() and glfwSetClipboardString()? Are there any platform related reasons for the window being required? On what platforms is this relevant and why?

**Comment by elmindreda** [comment]
Some window systems require a window to access the clipboard. Clipboard support was added to GLFW before it got its own private hidden helper window to use for the APIs like this.

You don't need to pass in a window to `glfwGetClipboardString` and `glfwSetClipboardString` since GLFW 3.3 and can just pass `NULL` instead. Whatever you pass in nowadays GLFW will use its own hidden window.

**Comment by Journeyman-dev** [comment]
Is there a way I can access this hidden window for my own uses?

**Comment by elmindreda** [comment]
Not currently. What would you use it for?

**Comment by Journeyman-dev** [comment]
> 
> 
> Not currently. What would you use it for?

I am using GLFW for the input and windowing stuff in my library called TUIC. I use a hidden GLFWwindow to create all the graphics data on and do all rendering to framebuffers, and then all user created windows share its context. This allows for graphics resources to work independently from windows in from user's perspective. I would use the hidden window already created by GLFW for this base context if that was possible. 

Thank you for answering my questions. I have another followup question: are there any other situations in GLFW where this hidden window is used and I don't have to pass in a window as an argument?

**Comment by elmindreda** [comment]
The helper window is just a native window. It doesn't have a context or even a `GLFWwindow` structure. I would recommend you keep creating your own hidden window, that can be created according to your needs.

It's used in a number of places, for example WGL initialization and monitor connection events, but there are iirc no other places where it has replaced an argument to a GLFW API function.
