### ISSUE TITLE
[Question] Support for changing ANGLE rendering backend on Linux

### ISSUE THREAD

**Issue by kuwarabbit** [glfw/glfw#1959]
Does ( or Will ) GLFW support for the following types of choosing ANGLE backend ?
glfwInitHint ( GLFW_ANGLE_PLATFORM_TYPE, GLFW_ANGLE_PLATFORM_TYPE_VULKAN ) ;

https://www.glfw.org/docs/3.4/intro_guide.html#GLFW_ANGLE_PLATFORM_TYPE_hint

Thanks !

**Comment by elmindreda** [comment]
If you're using the X11 backend on Linux then it should already be supported by the main branch, but it hasn't been included in any release yet.
