### ISSUE TITLE
[Question] Failing to load ANGLE EGL extensions.

### ISSUE THREAD

**Issue by kuwarabbit** [glfw/glfw#1963]
On Linux, using X11 I loaded ANGLE library, libGLESv2 and libEGL.
And tried to change backend. 
glfwInitHint(GLFW_ANGLE_PLATFORM_TYPE, GLFW_ANGLE_PLATFORM_TYPE_VULKAN);
glfwInit();

However, eglQueryString does not return ANGLE extension and unable to change backend to Vulkan. (EGL_EXT_platform_base and EGL_EXT_platform_x11 are active, EGL_ANGLE_platform_angle is not)
https://github.com/glfw/glfw/commit/0dea8a4441828311af4c31de8ba798ba330c4755#diff-21938cdabc3c2b2f9924afd55e59cb74fb7da35f896e97f9c99783db9088f8a4R412-R421

Does really support ANGLE backend changing on Linux?

thanks!

**Comment by elmindreda** [comment]
> Does really support ANGLE backend changing on Linux?

It should do so, yes. Could it be that GLFW has loaded the system `libEGL` instead of your ANGLE one? Check the `EGL_VENDOR` string from the `eglQueryString` that GLFW calls.

**Comment by kuwarabbit** [comment]
As you indicated, I was loading system EGL and GLESv2. It worked for me ! Thanks.
