### ISSUE TITLE
GLFW Error: GLX: GLX extension not found

### ISSUE THREAD

**Issue by kalingaru48** [glfw/glfw#1971]
I have setup Open3d with X11 forwarding on a Ubuntu Docker container.  I used XQuartz  on Mac M1 to render the graphics.

But I get following error on the docker container:

INFO - 2021-09-15 01:05:21,020 - font_manager - Generating new fontManager, this may take some time...
[Open3D WARNING] GLFW Error: GLX: GLX extension not found
[Open3D WARNING] Failed to create window
[Open3D WARNING] [DrawGeometries] Failed creating OpenGL window.

Can anyone help?

**Comment by nnop** [comment]
Met the same problem, have you solved it?

**Comment by dingangui** [comment]
hi, have you solved your problem now? I met the same problem

**Comment by YonatanSimson** [comment]
Same issue here trying to use open3d in a docker container

**Comment by paulsung97** [comment]
I have resolved that issue.
https://github.com/paulsung97/Solved-a-problem._GLFW_Error_-GLX-GLX_extension_not_found
