### ISSUE TITLE
glfwSetScrollCallback's callback offesets are zeros

### ISSUE THREAD

**Issue by tempdeltavalue** [glfw/glfw#1976]
glfwSetInputMode(window, GLFW_STICKY_KEYS, GL_TRUE);
glfwSetScrollCallback(window, scroll_callback_2);

void scroll_callback_2(GLFWwindow* window, double xoffset, double yoffset)
{
	printf("\n x % d", xoffset);  <- always zero
	printf("\n y % d", yoffset); <- always zero
}

Windows 10, visual studio 2019

**Comment by elmindreda** [comment]
The `%d` conversion specifier is for printing integer values in decimal. Use `%f` instead, which prints floating-point values like doubles.
