### ISSUE TITLE
Black screen after one second of run time on Mac

### ISSUE THREAD

**Issue by FlightBlaze** [glfw/glfw#1983]
Hi!

GLFW clears the window in black after one second

<img width="1440" alt="Screenshot 2021-10-30 at 00 26 30" src="https://user-images.githubusercontent.com/18074076/139503852-d0c67d6c-8b88-448d-8f8e-9dcfa05bfbcd.png">

https://user-images.githubusercontent.com/18074076/139504254-5d88847f-18f1-4cf3-a41d-deb4372061ac.mov

Tested on bgfx which uses Metal and Diligent Engine which uses MoltenVk.

I tried to replace GLFW with SDL and it work just fine.

**Steps to reproduce on Mac:**
1. git clone https://github.com/FlightBlaze/MyProject-BGFX
2. cd MyProject-BGFX
3. git submodule update --init --recursive
4. Build bgfx
5. Build and run MyProject

**Hardware and Software:**
MacBook Air on M1 chip
macOS Monterey
Visual Studio Code
Xcode 13.1

**Comment by elmindreda** [comment]
I built this project on macOS 10.15 and it deadlocks in `bgfx::Context::frame` so I can't reproduce this. I don't yet have a Mac capable of Monterey.

If anyone does, please do help diagnose this.

**Comment by FlightBlaze** [comment]
I forgot to push my latest commits to MyProject-BGFX. Please try again. : )

**Comment by elmindreda** [comment]
It does! The program now appears to draw (well, clear the screen) correctly as long as I disable OpenGL context creation by setting the [GLFW_CLIENT_API](https://www.glfw.org/docs/latest/window_guide.html#GLFW_CLIENT_API_hint) window hint to `GLFW_NO_API`.
