### ISSUE TITLE
macOS < 12 not supported anymore?

### ISSUE THREAD

**Issue by vincent1114** [glfw/glfw#1985]
![image](https://user-images.githubusercontent.com/50698701/139578692-4a14310d-cd0c-478b-ba0d-068f6e59489b.png)

On glfwinit(), segfaults on this line.
I don't see losing support for macOS 12 on release note, so I assume this was probably missed.

**Comment by saschasc** [comment]
Something like this could probably work.

```
#if (MAC_OS_X_VERSION_MAX_ALLOWED < 120000) // Before macOS 12 Monterey
  #define kIOMainPortDefault kIOMasterPortDefault
#endif
```

I had to add the following definition to CMakeLists.txt to make it compile after upgrading to XCode 13.1 (using llvm@12).

`add_definitions("\"-DNS_FORMAT_ARGUMENT\(A)=\"")`

**Comment by jeeb** [comment]
@vincent1114 can you check if #1994 helps? In the end it seems like `MACH_PORT_NULL` is the same as the value of this extern symbol (looking at the IOKit header comments, as well as https://developer.apple.com/documentation/iokit/kiomasterportdefault?language=objc ).

Kind of hilarious that this is an extern symbol and not just an enum or define, so instead of just checking whether your SDK is new enough, you also have to take into account target if you want to utilize the new version of this symbol :)

**Comment by saschasc** [comment]
@jeeb For me it works. But I still have to add

`add_definitions("\"-DNS_FORMAT_ARGUMENT\(A)=\"")`

when using LLVM 12.

**Comment by jeeb** [comment]
With Xcode 13.1 on macOS 11.6 (and thus targeting 11.6 by default) I can just do the following (at least with the current master)
```
rm -rf macos_build/ && mkdir -p macos_build/ && cd macos_build/
cmake -G "Ninja"  ..
ninja
```
which outputs the following
```
-- The C compiler identification is AppleClang 13.0.0.13000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Including Cocoa support
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/jeeb/projects/glfw/macos_build
```

**Comment by elmindreda** [comment]
OP should be fixed now with 544790666bb2a9a2dcd3ee6dc8c45716207e65d7 by @jeeb. Thank you everyone!

**Comment by jeeb** [comment]
> @jeeb For me it works. But I still have to add
> 
> `add_definitions("\"-DNS_FORMAT_ARGUMENT\(A)=\"")`
> 
> in CMakeLists.txt when using LLVM 12.

I just tested with a copy of Xcode 12.5.1 (which contains LLVM/clang 12) that I also have around for testing (from the times when Xcode 13.0 was the latest and was thoroughly broken with Swift at least).
```bash
sudo xcode-select -s /Applications/Xcode_12.5.1.app/

rm -rf macos_build/ && mkdir -p macos_build/ && cd macos_build/
cmake -G "Ninja"  ..
ninja
```
which then ends up working, configure outputting the following:
```
-- The C compiler identification is AppleClang 12.0.5.12050022
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode_12.5.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Including Cocoa support
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/jeeb/projects/glfw/macos_build
```
So unfortunately your issue - whatever it is - seems to be specific to your environment. I would recommend trying a clear environment (say a VM with just Xcode's SDK and no homebrew etc). You can get cmake from their site and then you add the `bin/` location included to PATH).

**Comment by saschasc** [comment]
Yes. That could be that it is specific to my environment. Actually I am not using AppleClang but Clang. I suppose when using XCode 12.x the error will not occur. It didn't with XCode 13.0. It seems that the combination of Clang 12.0.x with XCode 13.1 introduces this error.

```
-- The C compiler identification is Clang 12.0.1
-- The CXX compiler identification is Clang 12.0.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
```

Other have similar problems and solved it also like this (e.g. https://github.com/facebook/infer/issues/1535#issuecomment-940818555).
