### ISSUE TITLE
ecm dependency came back in

### ISSUE THREAD

**Issue by jwinarske** [glfw/glfw#1987]
Why did the ecm build dependency make it back in?

**Comment by linkmauve** [comment]
Hi, `grep`ping in master doesn’t return any result for this old cmake dependency, are you sure you are on master and not some older branch?

**Comment by jwinarske** [comment]
My bad!  I was thinking it was already released!  When is a release going to happen without ecm?

**Comment by elmindreda** [comment]
@jwinarske The removal of ECM has been in the main branch for a while now without issues so I'll look into possibly merging it into the stable branch. Can't give any dates, though.
