### ISSUE TITLE
Can't use gamepad mappings with already connected joysticks

### ISSUE THREAD

**Issue by racz16** [glfw/glfw#1996]
If I plug in a joystick into the computer before I call the _glfwInit_ function (for example I plug in before I start the application), GLFW doesn't assign a gamepad mapping to my joystick. If I'm correct, this is because in the function _glfwInit_, it detects the already connected joysticks in function __glfwPlatformInit_, and after that it initializes the gamepad mappings in function __glfwInitGamepadMappings_. This means that function _findMapping_ won't find a mapping to any already connected joysticks. There are no errors and the joystick functions work, only the gamepad related functions don't. If I disconnect and then reconnect my joystick, it works fine.
I use GLFW 3.3.5, Windows 10 (19043) and I tested with 2 different joysticks, but based on the code it only depends on the order of the function calls and not on the different joysticks or operating systems.

**Comment by elmindreda** [comment]
Thank you for reporting this! It should be fixed now with bfd9eaf0926320493f5257e9d57bf5d4f3c5cc53. This was a bug and fix specific to the `3.3-stable` branch. Will do a 3.3.6 release as soon as possible.
