### ISSUE TITLE
Does X11_Xcursor_INCLUDE_PATH pass include path of Xcursor to generated Makefile?

### ISSUE THREAD

**Issue by zhmlcg** [glfw/glfw#1999]
I'm trying to build up `glfw` from source on Ubuntu 20.04. It's a remote machine in which I'm only a normal user. At the `cmake` phase, it complains that it could not find `Xcursor`. I found that the complaint arises from line 209 of `src/CMakeLists.txt`:
```
if (NOT X11_Xcursor_INCLUDE_PATH)
```
So, I installed `Xcursor`’s development package `libxcursor-dev`, among others, in my user space folder `.bin`. Then I set the value of `X11_Xcursor_INCLUDE_PATH` to the path containing the header file `X11/Xcursor/Xcursor.h`, i.e., the parent directory of X11, by `-D` command-line option of `cmake`:
```
cmake --clean-first .. .  <many other variables> -DX11_Xcursor_INCLUDE_PATH=$HOME/.bin/usr/include
```
After that, cmake finished successfully.

Then, at the `make` phase, however, I received an error:
```
[  1%] Building C object src/CMakeFiles/glfw.dir/context.c.o
In file included from $HOME/testglfw/glfw/src/platform.h:62,
                 from $HOME/testglfw/glfw/src/internal.h:330,
                 from$HOME/testglfw/glfw/src/context.c:30:
$HOME/testglfw/glfw/src/x11_platform.h:36:10: fatal error: X11/Xcursor/Xcursor.h: No such file or directory
   36 | #include <X11/Xcursor/Xcursor.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
My question is: since I have told `cmake` the directory containing `Xcursor`'s header `X11/Xcursor/Xcursor.h` via variable `X11_Xcursor_INCLUDE_PATH`, why can’t cmake set the `gcc`'s `-I` option accordingly? Does the `glfw` source code attempt to form the `-I` option in generated Makefile using values in `X11_Xcursor_INCLUDE_PATH` variable? If so, did I miss anything in the `cmake` phase for this purpose? If not, I'd like to request add this function to the glfw source, that is, when generating Makefile, the `gcc` command line can read the value of `X11_Xcursor_INCLUDE_PATH` variable as an extra include path for `#include <X11/Xcursor/Xcursor.h>`, if the user has specified this in `cmake` command line.

PS, I know I can set environment variable to specify additional include path during make, but I just want to know whether I can use the value of `X11_Xcursor_INCLUDE_PATH` variable set in `cmake` command line to specify this, and request this function to `glfw` source if not. Thanks.

**Comment by elmindreda** [comment]
Is `X11_X11_INCLUDE_PATH` one of those many other variables?

If not, the answer to your question is probably that the GLFW CMake logic for X11 currently assumes that this variable contains the same directory as all the extension include path variables (as long as everything has been found). While it checks that all the variables contain valid values, it only adds `X11_X11_INCLUDE_PATH` as an include directory for the GLFW target.
