### ISSUE TITLE
Making the window fullscreen enables client-side decorations

### ISSUE THREAD

**Issue by Zamundaaa** [glfw/glfw#2001]
If I make the window fullscreen from the compositor (KWin) side, glfw seems to add its client side decorations. These don't go away when un-fullscreening - and the server side decorations are still enabled as well, which causes a few weird effects with moving and resizing.

While I doubt that it matters, this is on the latest KWin from git master. Glfw version is 3.3.5

**Comment by elmindreda** [comment]
Thank you for reporting this! That's definitely not ideal. There are Wayland improvements coming that should fix this as well.

**Comment by Zamundaaa** [comment]
it does works correctly now, thanks you!
