### ISSUE TITLE
Switch from fullscreen window to windowed window: missing decoration

### ISSUE THREAD

**Issue by petitg1987** [glfw/glfw#2009]
Hi,

OS: Windows 10 (21H2 - 19044.1387)
GLFW: reproduced in v3.3.4 & v3.3.5

I create a window in fullscreen mode and then I switch in windowed mode and the window decoration is missing (title bar, close button, border...)

Here is the code to reproduce:
```
//compile: g++ glfw.cpp -lglfw3 -lgdi32 -lwinmm
#include <GLFW/glfw3.h>
#include <iostream>

bool closeWindow = false;

void keyCallback(GLFWwindow* window, int key, int, int, int) {
	if (key == GLFW_KEY_SPACE) {
		glfwSetWindowMonitor(window, nullptr, 0, 0, 900, 600, GLFW_DONT_CARE); //switch in windowed mode
	} else if (key == GLFW_KEY_ESCAPE) {
		closeWindow = true;
	}
}

int main(void) {
	int width, height;
	glfwInit();
	GLFWmonitor* monitor = glfwGetPrimaryMonitor();
	const GLFWvidmode* mode = glfwGetVideoMode(monitor);
	
	glfwWindowHint(GLFW_DECORATED, GLFW_TRUE); //line added to force decoration but has no effect
	GLFWwindow* window = glfwCreateWindow(mode->width, mode->height, "Simple example", monitor, nullptr); //create window in fullscreen

	glfwSetKeyCallback(window, keyCallback);

	while(!closeWindow)
		glfwPollEvents();
	
	glfwDestroyWindow(window);
	glfwTerminate();
	exit(EXIT_SUCCESS);
}
```

Additional info:
- This source code works well on Linux (X11). 
- If I create the window directly in windowed mode: the decoration is well present

Thank you !

**Comment by elmindreda** [comment]
I was unable to reproduce this on Windows 10 21H2 with GLFW 3.3.5 and the above code. Do you have the Spy++ tool? What window styles and extended styles does it say that the GLFW window has after the switch to windowed mode?

**Comment by petitg1987** [comment]
Thank you for your answer.

I don't use VisualStudio but I found an old version of Spy++.

- Window Styles: 16CF0000 (WS_OVERLAPPEDWINDOW, WS_VISIBLE, WS_CLIPSIBLINGS, WS_CLIPCHILDREN)
- Extended Styles: 00040110 (WS_EX_ACCEPTFILES, WS_EX_WINDOWEDGE, WS_EX_APPWINDOW).

See: https://imgur.com/5w8dms7

Hope this helps.

**Comment by elmindreda** [comment]
It looks like the window does have decorations according to the window styles (i.e. WS_OVERLAPPEDWINDOW). Could it be that they're not visible because the window content area is placed at 0,0?

**Comment by petitg1987** [comment]
Oh shittt, you're right. The title bar exists but outside my screen. How did I not think about it !

I haven't noticed that 0,0 were the coordinates of the content because on Linux the window (not the content) is placed at 0,0.
Moreover, I didn't notice the window border because it is so thin (1 pixel on a 4K screen and almost the same color as my background)

Sorry for wasting your time.

**Comment by elmindreda** [comment]
No worries and thank you for the follow-up!
