### ISSUE TITLE
Installed on M1 MacBook...

### ISSUE THREAD

**Issue by slerman12** [glfw/glfw#2012]
Installed via pip (pip install glfw) but when I run 

```
python
>>>import glfw
```

I get this error:

```
_default_error_callback = _GLFWerrorfun(_handle_glfw_errors)
MemoryError
```

Not sure what's going on.

**Comment by slerman12** [comment]
Update: just tested deactivating my conda env and installing/running in a simple vanilla python virtualenv and the import worked.

Is there a conda incompatibility?

**Comment by ByunghoonKim** [comment]
[Python binding](https://pypi.org/project/glfw/) for GLFW seems to be a separate project. I would suggest that you may ask [them](https://github.com/FlorianRhiem/pyGLFW) directly to get a fine-tuned answer, especially if it is about how to install the module.

**Comment by elmindreda** [comment]
Agreed, this seems related to the bindings. Leaving this open for a bit longer just in case.

**Comment by elmindreda** [comment]
Closing this on the assumption it's an issue with the binding, not GLFW itself. Please re-open or create a new issue if that's not the case.
