### ISSUE TITLE
glfwCreateWindow returns null

### ISSUE THREAD

**Issue by AnnoyingB** [glfw/glfw#2019]
``` c++
void Window::Create(std::string title) {
		glfwSetErrorCallback(error_callback);

		if (GL_TRUE != glfwInit()) {
			AC_CORE_ASSERT("Failed to initialize GLFW. This could be a problem with your hardware or software.");
		}
		else {
			window = glfwCreateWindow(500, 600, "Acorn Engine", nullptr, nullptr);
		}

		if (!window) {
			glfwTerminate();
			AC_CORE_ASSERT("GLFW failed to create the window.");
		}
		else {
			glfwMakeContextCurrent(window);
			AC_CORE_INFO("Successfully created GLFW window.");
		}
	}
```

Settings glfw hints don't work. This code is in a dll. I am using a lib for glfw (glfw3_mt.lib)

**Comment by Snowiiii** [comment]
maybe try to replace nullptr to NULL

**Comment by AnnoyingB** [comment]
Nope

**Comment by Snowiiii** [comment]
check out https://www.glfw.org/documentation.html

**Comment by AnnoyingB** [comment]
I already have. That is why I asked this question, not to be rude or anything.

**Comment by thedmd** [comment]
You can check what [glfwGetError](https://www.glfw.org/docs/latest/group__init.html#ga944986b4ec0b928d488141f92982aa18) or [glfwSetErrorCallback](https://www.glfw.org/docs/latest/group__init.html#gaff45816610d53f0b83656092a4034f40) will tell you. You can read more about error handling [here (Error handling)](https://www.glfw.org/docs/latest/intro_guide.html#error_handling).

**Comment by AnnoyingB** [comment]
> glfwSetErrorCallback(error_callback);

As you can see in my code, I have made one. Except, it shows no error. If you want to see the callback funtion, here:
``` c++
void error_callback(int error, const char* msg) {
	std::string s;
	s = " [" + std::to_string(error) + "] " + msg + '\n';
	std::cerr << s << std::endl;
}
```

**Comment by thedmd** [comment]
> As you can see in my code, I have made one. 

I missed that. My bad. : )


You can try to lower OpenGL version with hints or create window without context to see if that works.

**Comment by AnnoyingB** [comment]
The error is on the creation line though.

**Comment by Snowiiii** [comment]
i think this is an error with linking or library

**Comment by AnnoyingB** [comment]
I don't think so. I am using premake but I don't think that would be affecting it?

**Comment by Snowiiii** [comment]
does the glfw work at all or are there only problems with window calls?

**Comment by AnnoyingB** [comment]
The problem is, glfwCreateWindow() returns null. glfwInit() works fine though.

**Comment by AnnoyingB** [comment]
Also, as I have written, 

> it triggers a breakpoint.

just making sure you understand the problem.

**Comment by AnnoyingB** [comment]
I have tried building the source project of glfw and linked it to my project but when I build the glfw project into a lib and try to use it in my project it gives a lot of errors.

**Comment by Snowiiii** [comment]
1. You don't have to build the lib yourself. We have pre-compiled binaries for that
2. Are you sure that you have linked everything correctly?
First you have to add the Include and Lib folders in VC ++ Directories then under Linker-> Input glfw.3lib and opengl32.lib don't forget that we also need the %(AdditionalDependencies)

**Comment by AnnoyingB** [comment]
Yes, I have done that. That still gives null for glfwCreateWindow.

**Comment by AnnoyingB** [comment]
![Screenshot 2021-12-31 094612](https://user-images.githubusercontent.com/81764357/147816169-ac86cbbf-6a26-4f10-b8eb-6d05d587bac6.png)

**Comment by AnnoyingB** [comment]
```opengl32.lib;glfw3.lib;%(AdditionalDependencies)```

**Comment by AnnoyingB** [comment]
All of these are errors from the pre-compiled ones.

**Comment by AnnoyingB** [comment]
If I use `glfw3_mt.lib` then glfwCreateWindow returns null.

**Comment by AnnoyingB** [comment]
fixed it.

**Comment by linkmauve** [comment]
Hi, what was the issue?

**Comment by AnnoyingB** [comment]
read the title

**Comment by linkmauve** [comment]
I mean, what was the cause of your issue, and how did you solve it, so that someone reading this later could fix it without digging like you had to.

**Comment by Snowiiii** [comment]
> `opengl32.lib;glfw3.lib;%(AdditionalDependencies)`



> If I use `glfw3_mt.lib` then glfwCreateWindow returns null.

**Comment by AnnoyingB** [comment]
`glfw3_mt.lib` gives null when calling glfwCreateWindow.
My linker input was: `opengl32.lib;%(AdditionalDependencies)`
got a premake file off the internet for glfw and referenced glfw from my main proj. Hopefully this will help :)

**Comment by AnnoyingB** [comment]
The premake file is:
``` lua
project "GLFW"
	kind "StaticLib"
	language "C"
    architecture "x64"

	targetdir ("bin/" .. outputdir .. "/%{prj.name}")
	objdir ("bin/int/" .. outputdir .. "/%{prj.name}")

	files
	{
		"include/GLFW/glfw3.h",
		"include/GLFW/glfw3native.h",
		"src/internal.h",
		"src/platform.h",
		"src/mappings.h",
		"src/context.c",
		"src/init.c",
		"src/input.c",
		"src/monitor.c",
		"src/platform.c",
		"src/vulkan.c",
		"src/window.c",
		"src/egl_context.c",
		"src/osmesa_context.c",
		"src/null_platform.h",
		"src/null_joystick.h",
		"src/null_init.c",
		"src/null_monitor.c",
		"src/null_window.c",
		"src/null_joystick.c"
	}
filter "system:linux"
    pic "On"

    systemversion "latest"
    staticruntime "On"

    files
    {
        "src/x11_init.c",
        "src/x11_monitor.c",
        "src/x11_window.c",
        "src/xkb_unicode.c",
        "src/posix_time.c",
        "src/posix_thread.c",
        "src/glx_context.c",
        "src/egl_context.c",
        "src/osmesa_context.c",
        "src/linux_joystick.c"
    }

    defines
    {
        "_GLFW_X11"
    }

filter "system:windows"
    systemversion "latest"
    staticruntime "On"
    
    -- buildoptions{
    --     "/MT"
    -- }

    files
    {
        "src/win32_init.c",
        "src/win32_module.c",
        "src/win32_joystick.c",
        "src/win32_monitor.c",
        "src/win32_time.h",
        "src/win32_time.c",
        "src/win32_thread.h",
        "src/win32_thread.c",
        "src/win32_window.c",
        "src/wgl_context.c",
        "src/egl_context.c",
        "src/osmesa_context.c"
    }

    defines 
    { 
        "_GLFW_WIN32",
        "_CRT_SECURE_NO_WARNINGS"
    }

filter "configurations:Debug"
    runtime "Debug"
    symbols "On"

filter "configurations:Release"
    runtime "Release"
    optimize "On"
```

outputdir should be set to your output directory. My output dir is:
`outputdir = "%{cfg.buildcfg}-%{cfg.system}-%{cfg.architecture}"`

**Comment by AnnoyingB** [comment]
In your main premake file you should have the outputdir and include this file.

**Comment by AnnoyingB** [comment]
I used `git clone https://github.com/glfw/glfw`
for the source files to use premake with.
