### ISSUE TITLE
(New?) GLFW Error on macOS arm64 (Apple Silicon)

### ISSUE THREAD

**Issue by Pyrotex7** [glfw/glfw#2023]
_OK I closed this issue before because I had not actually written anything in the description, but now I have, so I reopened it._

So I have been experimenting with a python based Minecraft launcher I've been developing to work on the new Apple Silicon Macs. All has gone well, but as of recent(it may have been always, but if my memory is correct I did get it working _once or twice_) I have been having an issue when launching Minecraft, specifically version 1.15, with the following error upon launch, `GLFW error 65548: Cocoa: Regular windows do not have icons on macOS`, proceeded by Minecraft never launching, as it crashes before the window appears. I am using the latest version of LWJGL with macOS arm64 natives. I've seen some other issues with GLFW and Apple Silicon, that seem to have been fixed in the recent LWJGL versions, but I have not found a comprehensive fix for this error. 

I would just like to ask if there is any current fix or patch for this issue, or if it will be coming in a later version of GLFW, or if it is already fixed and there may be a issue with my current launch environment.

Please let me know if I may help by providing any more info.

Thanks,
Pyrotex7

**Comment by Pyrotex7** [comment]
Sorry I will close this issue for now, I opened this on accident without completing the issue.

**Comment by Pyrotex7** [comment]
Alright this is like 30 seconds

**Comment by Snowiiii** [comment]
Please no bindings issues, you can report your issue to LWJGL here: https://github.com/LWJGL/lwjgl3/issues

**Comment by Pyrotex7** [comment]
Alright, thanks.

**Comment by FailureSam** [comment]
## MacOS Cocoa Hot Fix

Precompiled Library is included with my [Personal Fork Solution](https://github.com/FailureSam/glfw-fix/releases/tag/v3.3.8)

Specify GLFW Library use via a location path using [Prism Launcher](https://github.com/PrismLauncher/PrismLauncher) global settings
