### ISSUE TITLE
Fails to build on GhostBSD 

### ISSUE THREAD

**Issue by LeavesOfFruit** [glfw/glfw#2027]
Trying to compile a project using glfw on GhostBSD. It fails giving me a huge backlog of errors referring to `'_GLFWjoystick' has no member named 'linjs'`. :

```
/usr/home/../Desktop/client/libs/RaZ/extern/glfw/src/linux_joystick.c: In function 'handleKeyEvent':
/usr/home/../Desktop/client/libs/RaZ/extern/glfw/src/linux_joystick.c:53:32: error: '_GLFWjoystick' has no member named 'linjs'
   53 |                              js->linjs.keyMap[code - BTN_MISC],
      |                                ^~
/usr/home/../Desktop/client/libs/RaZ/extern/glfw/src/linux_joystick.c:53:54: error: 'BTN_MISC' undeclared (first use in this function)
   53 |                              js->linjs.keyMap[code - BTN_MISC],
      |                                                      ^~~~~~~~
/usr/home/../Desktop/client/libs/RaZ/extern/glfw/src/linux_joystick.c:53:54: note: each undeclared identifier is reported only once for each function it appears in
/usr/home/../Desktop/client/libs/RaZ/extern/glfw/src/linux_joystick.c: In function 'handleAbsEvent':
/usr/home/../Desktop/client/libs/RaZ/extern/glfw/src/linux_joystick.c:61:25: error: '_GLFWjoystick' has no member named 'linjs'
   61 |     const int index = js->linjs.absMap[code];
      |                         ^~
/usr/home/../Desktop/client/libs/RaZ/extern/glfw/src/linux_joystick.c:63:17: error: 'ABS_HAT0X' undeclared (first use in this function)
   63 |     if (code >= ABS_HAT0X && code <= ABS_HAT3Y)
      |                 ^~~~~~~~~
/usr/home/../Desktop/client/libs/RaZ/extern/glfw/src/linux_joystick.c:63:38: error: 'ABS_HAT3Y' undeclared (first use in this function)
   63 |     if (code >= ABS_HAT0X && code <= ABS_HAT3Y)
      |                                      ^~~~~~~~~
/usr/home/../Desktop/client/libs/RaZ/extern/glfw/src/linux_joystick.c:74:24: error: '_GLFWjoystick' has no member named 'linjs'
   74 |         int* state = js->linjs.hats[hat];
      |                        ^~
/usr/home/../Desktop/client/libs/RaZ/extern/glfw/src/linux_joystick.c:89:47: error: '_GLFWjoystick' has no member named 'linjs'
   89 |         const struct input_absinfo* info = &js->linjs.absInfo[code];

```
Additional info:

- gcc10 compiler
- OS is GhostBSD 13.0-STABLE GENERIC
-  cmake version 3.22.1

What is the solution to this? I am not using any gamepads or joysticks in my project, so how do i supresses the errors (other than deleting parts of the glfw codebase)?

**Comment by elmindreda** [comment]
The `linux_joystick.c` should not currently be built on BSD and I'm not sure why it is here. I was unable to reproduce this with the GLFW CMake files. Are you using a custom build setup?

**Comment by LeavesOfFruit** [comment]
Ok I see. I'm not too sure of the exact build setup, as it's part of a game framework I am using which abstracts some of the GLFW functions. I've just realized their GLFW version being used seems out of date, using v3.3.2. Maybe that could be the reason for it? I might try and update it to the more recent v3.3.6 and see if it solves it. 
![Screenshot_2022-01-23_19-26-16](https://user-images.githubusercontent.com/97350236/150694765-375eb88a-df1a-4fed-9e46-8f453c803c3b.png)

**Comment by LeavesOfFruit** [comment]
Nevermind, I think the issue might lie with the graphics framework setup. I'll close this issue

**Comment by elmindreda** [comment]
Thank you for the follow-up! Hope you were able to find the source of the issue!
