### ISSUE TITLE
glfwCreateWindow freezes when called in DllMain

### ISSUE THREAD

**Issue by vsbn** [glfw/glfw#2029]
When `glfwCreateWindow` is called in `DllMain`, the application freezes with CPU usage dropping to 0%, and a window is not created. 

Here is an example:

```
BOOL WINAPI DllMain(
    HINSTANCE hinstDLL,
    DWORD fdwReason,
    LPVOID lpReserved)
{
    GLFWwindow* window;
    /* Initialize the library */
    if (!glfwInit())
    {
        std::cout << "glfw init failed" << std::endl;
        return;
    }

    std::cout << "1" << std::endl;

    /* Create a windowed mode window and its OpenGL context */
    window = glfwCreateWindow(640, 480, "Hello World", NULL, NULL);
    if (!window)
    {
        std::cout << "window creation failed" << std::endl;
        glfwTerminate();
        return;
    }

    std::cout << "2" << std::endl;

    /* Make the window's context current */
    glfwMakeContextCurrent(window);

    return TRUE;
}
```

In this example, 1 is printed to the console, however 2 is never printed as the application freezes when `glfwCreateWindow` is called.

**Comment by elmindreda** [comment]
For anyone reading this issue: you are very limited in [what you can do from inside DllMain](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-best-practices).

**Comment by vsbn** [comment]
Thank you for your response! I realised that soon after I posted the problem. 

However, it is possible to use `CreateThread` and `FreeLibraryAndExitThread` to bypass this problem, even though it is heavily unadvisable to do so. For information can be found [here](https://stackoverflow.com/questions/1688290/creating-a-thread-in-dllmain).
