### ISSUE TITLE
Why does the static version of the GLFW library need other libraries to be linked during compilation?

### ISSUE THREAD

**Issue by nilTheDev** [glfw/glfw#2037]
I am using Fedora 34. 

I cloned this repository and built the library on my machine. After building I used the `make install` command to install the library on my machine. I believe the library that is installed is a static library as the name of the installed library is `libglfw3.a`.

However, to compile the [first example given in the documentation](https://www.glfw.org/documentation.html) I had to link other libraries as well. The command which compiled the code is `gcc main.c -lglfw3 -lpthread -ldl -lOpenGL -lm`. Linking an implementation of the OpenGL library (`-lOpenGL`) makes sense because the code is using `glClear()`. However, why did I have to link libraries other than glfw3 (`-lglfw3`), such as pthread (`-lpthread`), dl (`-ldl`), math(`-lm`)?

Isn't a static library supposed to bundle all its dependencies with itself? I expected `gcc main.c -lglfw3 -lOpenGL` to work. Or I am missing something?

**Comment by Adnn** [comment]
> Isn't a static library supposed to bundle all its dependencies with itself?

It is the contrary: a dynamic library does, but a static library does not. A static library only contains symbols, and they have to be resolved at link time when assembling an executable image.

**Comment by ronchaine** [comment]
`-pthread` `-ldl`, `-lm` and OS threading support, the dynamic linker and maths, respectively. 

These are provided by glibc (the GNU C standard library), but they are separated into different files (not sure why, musl libc doesn't do it, for example), and not linked automatically.

**Comment by nilTheDev** [comment]
@Adnn Hmm. Makes sense. After your input, I experimented a little bit with some dynamic and static libraries. So, when I link to a dynamic library it resolves its dependencies at the runtime. However, if I use a static library the actual code of the library gets copied in the executable. Therefore it becomes my duty to link the dependencies of the static library at compile time. 

Either way, the library's dependencies must be present in the system. Otherwise, the code won't run.
