### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by anantha-vidhya** [glfw/glfw#2038]
CMake Error at /home/futura/ti-processor-sdk-linux-am437x-evm-04.02.00.09/linux-devkit/sysroots/x86_64-arago-linux/usr/share/cmake-3.6/Modules/FindX11.cmake:439 (message):
  Could not find X11
Call Stack (most recent call first):
  src/CMakeLists.txt:186 (find_package)

**Comment by nilTheDev** [comment]
Which distro are you using? Building the `glfw` library requires `X11` library to be present in the system. So, you need to find the package for your distro that provides the `X11` library.

**Comment by anantha-vidhya** [comment]
No ti forum talks about this as it won't support x11. In such case what should i do?

**Comment by elmindreda** [comment]
If the target Linux system doesn't provide X11 or Wayland then GLFW will currently not work there. Sorry.

**Comment by ryleymcc** [comment]
echo $XDG_SESSION_TYPE

**Comment by elmindreda** [comment]
Closing this as there doesn't seem to be anything to do.
