### ISSUE TITLE
Relying on undefined behavior for key deduplication starting with 9a3664b

### ISSUE THREAD

**Issue by ashpil** [glfw/glfw#2044]
I noticed that if you compile versions 3.3.3+ with `-fsanitize=undefined`, you get a crash the second time you press any key. Not sure what exactly is causing it but I was able to isolate it to commit 9a3664b.

**Comment by elmindreda** [comment]
Thank you for reporting this! This will very likely be fixed by #1951.

**Comment by elmindreda** [comment]
#1951 has been merged. In case this issue persists, please re-open this issue.
