### ISSUE TITLE
GetWindowSize not updated before window size callback is called on all platforms.

### ISSUE THREAD

**Issue by NogginBops** [glfw/glfw#2046]
In the win32 and cocoa backends the size of the window is set before calling the window size callback but the wayland and X11 backends doesn't do this. Fixing this issue would just be a matter of changing the order of some code in the wayland and X11 backends and it would make calling `glfwGetWindowSize` always have the correct new size of the window when the size callback is called.

### Win32:
https://github.com/glfw/glfw/blob/97da62a027794d9ff0f4512268cb9a73a8fb5073/src/win32_window.c#L989-L996

### Cocoa:
https://github.com/glfw/glfw/blob/97da62a027794d9ff0f4512268cb9a73a8fb5073/src/cocoa_window.m#L271-L277

### Wayland:
https://github.com/glfw/glfw/blob/97da62a027794d9ff0f4512268cb9a73a8fb5073/src/wl_window.c#L496-L498
https://github.com/glfw/glfw/blob/97da62a027794d9ff0f4512268cb9a73a8fb5073/src/wl_window.c#L905-L910
Here the setting of the window size could easily be moved out of `_glfwSetWindowSizeWayland` and placed before the call to `_glfwInputWindowSize`. `_glfwSetWindowSizeWayland` can be completely removed as it's only called from one place for some simplifications and cleanup of the code.

### X11:
https://github.com/glfw/glfw/blob/97da62a027794d9ff0f4512268cb9a73a8fb5073/src/x11_window.c#L1470-L1483
Here the setting of the internal variables could be set before calling the callback.

**Comment by elmindreda** [comment]
Thank you for the bug report! This was indeed a bug on Wayland. It was fixed at some point during the refactoring of the Wayland backend.

Unlike on Wayland, on X11 the cached size is only used to filter out duplicate size events. It's still good practice to update the cache first, though, and this has been done with f0ec791386b24bcea6210e37d9ad1c79b2722911.
