### ISSUE TITLE
glfwGetKeyScancode ambiguity

### ISSUE THREAD

**Issue by TheChocolateOre** [glfw/glfw#2055]
Quoting from [Input guide](https://www.glfw.org/docs/3.3/input_guide.html#input_key):

> You can query the scancode for any named key on the **current platform** with glfwGetKeyScancode.

Quoting from [glfwGetKeyScancode](https://www.glfw.org/docs/3.3/group__input.html#ga67ddd1b7dcbbaff03e4a76c0ea67103a) function documentation:

> If the key is GLFW_KEY_UNKNOWN or does not exist **on the keyboard** this method will return -1.

I'm confused.
1. If glfwGetKeyScancode returns -1, does that mean that the named key does not exist on the keyboard or on the platform? Either or? Both? How can I differentiate?
2. If glfwGetKeyScancode returns not -1, does that mean that the named key does exist on the keyboard or on the platform? On both?

The reason I'm bringing this up, other than the platform/keyboard ambiguity stated above, is that I got a non -1 scancode, from glfwGetKeyScancode, given a named key that does not exist on my keyboard. Specifically, they were the F13-F24 keys. Surprisingly, F25 returns -1, or should I say, as expected.

Digging a little bit further, turns out you _can_ press the F13-F24 keys of a F1-F12 keyboard, just by using the _Shift +_ scheme. Still I didn't manage to replicate that. Is that the reason why I don't get -1 on those high F keys?

I think it could be useful to know what keys the keyboard actually has, and not just wait for a non-existent key to be pressed. Of course, maybe I'm asking too much, and it's impossible to have such an information from the OS.

Going a little bit further, why the mouse does not have a scancode as well? Joystick? Is it just an only keyboard thing. _possibly my ignorance starts shining now_ 

GLFW 3.3.6
Windows 10
Keyboard Logitech K120

**Comment by elmindreda** [comment]
Thank you for reporting this! I had completely missed how vague and contradictory those sections were. 9959dc69cadd1f7790060846ffbc44e7da56fc56 is my attempt to improve them somewhat, in these and a few other ways.
