### ISSUE TITLE
Wayland/GTK backend: set up to only load if installed to system

### ISSUE THREAD

**Issue by jgcodes2020** [glfw/glfw#2062]
The developers of GLFW have previously stated that creating a GTK backend would be a relatively large dependency. Unfortunately, GNOME forces CSD and the alternative of creating cross-platform decorations isn't exactly great.

Hence, this is my proposal: Create a GTK backend, but only use GTK if it is installed on the system. Although this backend would need to be maintained, it would remove the problem of GLFW being bloated, as the system install is likely already in use for other GTK apps.

**Comment by christianrauch** [comment]
Do you mean something like https://github.com/glfw/glfw/pull/1693?

**Comment by DragonSWDev** [comment]
There is already pull request with support for libdecor. Libdecor is pretty light library that handles decorations for Wayland clients. It's pretty good solution, SDL already has support for it and some distributions packaged it so there is probably no point of creating brand new backend from scratch.

**Comment by elmindreda** [comment]
Yup, libdecor definitely seems like the better choice here.
