### ISSUE TITLE
glfwPollEvents freezes for 500ms the first time command key is pressed

### ISSUE THREAD

**Issue by invrainbow** [glfw/glfw#2063]
OS: macOS Monterey 12.0.1
Hardware: M1 Mac mini
GLFW version: 3.3

Here's how I'm creating my window:

```c++
glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 0);
glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
glfwWindowHint(GLFW_MAXIMIZED, GLFW_TRUE);

auto window = glfwCreateWindow(1280, 720, WINDOW_TITLE, NULL, NULL);
```

The first time I press any command-key combination, like cmd+p or cmd+a or cmd+anything, my program freezes for about 500ms, which I tracked down to `glfwPollEvents` taking about 500ms to return. This happens even if I completely comment out my key and char handlers (i.e. I don't even register the callback).

This only happens the first time I press a command-key combo; after that, all keys work again. Any ideas?

**Comment by elmindreda** [comment]
Was this issue resolved?

**Comment by invrainbow** [comment]
No, I ended up ripping out glfw and writing my own macOS UI code. There is still a bit of a delay when pressing a command-key combo for the first time, but not as much (about 100 ms), so I wonder if this is just intrinsic to macOS. It's no longer as noticeable, so I haven't bothered to dig deeper.
