### ISSUE TITLE
glfw.initialized false in .cpp, but on header true (what?)

### ISSUE THREAD

**Issue by iamfobey** [glfw/glfw#2067]
Sorry for my English.

Hello, I try to write function definition on my .cpp file, but when I run project - glfw always return "The GLFW library is not initialized", but window is created (window creating requiring initializing glfw).
If I write function definition on header file - glfw not return "The GLFW library is not initialized".

I dont understand how it works, lol.

How compiling: dll and links to exe;
Compiler: mingw64;

Code: https://pastebin.com/LVAiHf4D

**Comment by DezlowNG** [comment]
Video: https://youtu.be/I55Pdcxh_JY

If remove _GLFW_REQUIRE_INIT glfw not crash

**Comment by DezlowNG** [comment]
![image](https://user-images.githubusercontent.com/74720936/161378538-fa0390c1-0405-4149-ab08-8b23cf1a1702.png)
![image](https://user-images.githubusercontent.com/74720936/161378545-d2a6e3b8-ed68-4918-a796-1916138cdf58.png)
