### ISSUE TITLE
Joystick initialization very slow in some cases

### ISSUE THREAD

**Issue by mylocameron** [glfw/glfw#207]
I just discovered that glfwInitJoysticks on OSX ( Mavericks, running glfw 3.0.4 ) was significantly slowing down my apps startup time.

I commented out the call to _glfwInitJoysticks() ( 'cause I'm not making use of joysticks ), and startup time was greatly improved.

**Comment by elmindreda** [comment]
This should be fixed with b4d4fc8f79918bbd6dbf288fb43c4ce5ee22bdaf in 3.1.
