### ISSUE TITLE
GLFW Error Handling: Getting error message for specific error code

### ISSUE THREAD

**Issue by bugravirgomercury** [glfw/glfw#2071]
Hello,

I can use `int code = glfwGetError(&description);` to get the last error and description string. Is there some way I can use to execute these steps separately, as needed by the design of my abstractions?

I know I can use `int code = glfwGetError(NULL);` to get the error code, but is there a way to get description string for *specific* error code? For example, something like `glfwGetErrorDescription(code, &description);`?

I have a PR implementing `glfwGetErrorDescription` if you're interested.

I appreciate your help in advance.

**Comment by elmindreda** [comment]
> I can use `int code = glfwGetError(&description);` to get the last error and description string. Is there some way I can use to execute these steps separately, as needed by the design of my abstractions?

There isn't, because...

> I know I can use `int code = glfwGetError(NULL);` to get the error code, but is there a way to get description string for *specific* error code?

...a GLFW error code can have many different descriptions depending on what went wrong where, and sometimes include information specific to that call including erroneous values and error descriptions for the underlying OS error. It's more similar to something like `GL_KHR_debug` than `strerror`.

The error descriptions in `_glfwInputError` are only generic fallback descriptions in case the caller didn't provide its own. Those are not much more than transcriptions of the names of the error codes and often not very useful.

**Comment by bugravirgomercury** [comment]
> You can retrieve both the error code and description before creating the exception object and pass them to its constructor, or you can have the exception object constructor itself do it.

My current implementation takes the error code only at the constructor, then it retrieves the description mapped to that specific code by calling `what_for_error_code(error_code_t error_code)` method. I'll add another constructor that takes both error code and the description now, skipping the `error code -> description` mapping function altogether.

> This is why I won't merge https://github.com/glfw/glfw/pull/2072. A function that only returns the generic error descriptions would cause people to miss out on the information in the specific ones, if they use that instead of the description from glfwGetError. If one wants only generic error descriptions then they can be copied from init.c or one can write one's own.

Looks like I need to refactor my own code to accommodate for it. I saw the caveat in my code now. This concludes my issue.

Thanks for all your diligence and help. Have a nice day.
