### ISSUE TITLE
GLFW is slower at rendering with GLFW_CONTEXT_VERSION 3.3 core profile than with compatibility profile (OpenGL)

### ISSUE THREAD

**Issue by violin21** [glfw/glfw#2075]
I am on x64 Windows 11 with OpenGL version 4.5 on my graphics card. I'm using Glad2 as my loader and GLFW v3.3.6.
I have the following code:

```
#define GLFW_INCLUDE_NONE
#include <GLFW/glfw3.h>
#include <glad/gl.h>

#include <stdio.h>

int main()
{
    if(!glfwInit())
    {
        printf("Failed to initialize GLFW. Fatal error.\n");
        return -1;
    }

    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);

    GLFWwindow *window = glfwCreateWindow(800, 600, "hi", NULL, NULL);

    glfwMakeContextCurrent(window);
    gladLoadGL(glfwGetProcAddress);
    glfwSwapInterval(1);

    while(!glfwWindowShouldClose(window))
    {
        glClearColor(0.0f, 0.5f, 1.0f, 1.0f);
        glClear(GL_COLOR_BUFFER_BIT);

        glfwSwapBuffers(window);
        glfwPollEvents();
    }

    glfwDestroyWindow(window);

    glfwTerminate();
    return 0;
}
```

When I resize the window that this code creates, it lags a bit in spreading the blue part across the whole window even after I have stopped resizing, as can be seen here:
![image](https://user-images.githubusercontent.com/100453578/161608013-97bd33f4-85d2-439e-8a68-815bf908ded7.png)
When I set GLFW_OPENGL_PROFILE to GLFW_OPENGL_COMPAT_PROFILE however, it works fine.

**Comment by elmindreda** [comment]
GLFW doesn't handle windows differently based on what OpenGL profile its context has. It connects you to the OpenGL API but doesn't implement it. Any difference like that would be in the GPU driver.

**Comment by violin21** [comment]
> GLFW doesn't handle windows differently based on what OpenGL profile its context has. It connects you to the OpenGL API but doesn't implement it. Any difference like that would be in the GPU driver.

So then it's probably my GPU. That also answers my issue/question [here](https://github.com/glfw/glfw/issues/2073). Thanks!
