### ISSUE TITLE
Warning about _GNU_SOURCE macro redefined in 3.3.7

### ISSUE THREAD

**Issue by Jacalz** [glfw/glfw#2076]
I recently opened a PR to update [go-gl/glfw](https://github.com/go-gl/glfw) to the new 3.3.7 version (https://github.com/go-gl/glfw/pull/350). Everything is working as expected but I am getting warnings about `_GNU_SOURCE` being redefined:
```
# github.com/go-gl/glfw/v3.3/glfw
In file included from ../glfw/v3.3/glfw/c_glfw_lin.go:20:
../glfw/v3.3/glfw/glfw/src/x11_window.c:30: warning: "_GNU_SOURCE" redefined
   30 | #define _GNU_SOURCE
      | 
<command-line>: note: this is the location of the previous definition
```

This is on Fedora Linux 35 although it is similar to https://github.com/glfw/glfw/issues/2010. The issue here though is that it will be a lot more noticeable now that there is a warning on Linux and not just on BSD systems. This warning was not present with 3.3.6.

**Comment by elmindreda** [comment]
I believe this is an issue with the build files in the Go bindings but I'm leaving this open until that issue is resolved.

**Comment by Jacalz** [comment]
I'm afraid that I don't have enough knowledge to say anything about that. The issue did only show itself after upgrading so I'm not entirely sure that the issue lies in the Go package. However, I'm afraid that I don't really have enough knowledge to be certain. Perhaps @dmitshur has better knowledge of the code base?

**Comment by dmitshur** [comment]
> I believe this is an issue with the build files in the Go bindings

The Go bindings are indeed defining `_GNU_SOURCE` on Linux in `build.go`:

[https://github.com/go-gl/glfw/blob/277f93cf/v3.3/glfw/build.go#L29-L30](https://github.com/go-gl/glfw/blob/277f93cfa958a6d7e2f7ca5be59ae85360b1f953/v3.3/glfw/build.go#L29-L30)

Now that GLFW source code does it too in `x11_window.c` (as of 3.3.7 via commit https://github.com/glfw/glfw/commit/9f73e9afa34b1c0902023d5d80be1c0f954135e5 and commit 35a65361ffb937188aebfda5e00c39c108ce9797), it seems we can adjust the `build.go` file not to do it and thus avoid the redefinition. I'll also comment this on https://github.com/go-gl/glfw/pull/350.

**Comment by Jacalz** [comment]
Thanks for looking into it @dmitshur. I will try to get this resolved in my PR over there and close this. Sorry for all the fuss over here.

**Comment by Distortions81** [comment]
I had this error recently when updating packages (go get -u) deleting go.mod and go.sum fixed it.
(Posting this here since it's what comes up when googling the error)
