### ISSUE TITLE
X11: add user callback for ReparentNotify

### ISSUE THREAD

**Issue by jjYBdx4IL** [glfw/glfw#2081]
I'm plugging in (XEmbed, plugin) child windows into other apps and I want to call glfwShowWindow only *after* the reparenting has finished. For that I'm currently using an X connection directly to wait for the ReparentNotify event.

Maybe this could be more generalized like:

- glfwAttachWindowToParent(child, parent)
- glfwSetWindowAttachedCallback
- maybe glfwCreateEmbeddableChildWindow(parent) (no decoration, initially invisible)

On Windows the callback would probably be called immediately.

**Comment by elmindreda** [comment]
I won't add this feature. Embedding is outside the current scope of GLFW and there's plenty left to do that's in scope.

However, I may add one where you get to preview each `XEvent` as it's received, which should let you achieve this.
