### ISSUE TITLE
M1 Macbook Glfw: missing architectures required by target: arm64

### ISSUE THREAD

**Issue by BR4YD3N-G** [glfw/glfw#2083]
MacBook Pro (13-inch, M1, 2020), Mac OS 12.4, Xcode 13.3.1, Vulkan 1.3.204.1, Glfw 3.3.7.
Each time I try to build my project I get this error: “/Documents/C++/VulkanTest/VulkanTest.xcodeproj The linked library 'libglfw.3.3.dylib' is missing one or more architectures required by this target: arm64.”
<img width="679" alt="Screen Shot 2022-04-15 at 12 33 58 PM" src="https://user-images.githubusercontent.com/11237770/163608269-d0dfd4e1-956f-4662-af4b-5d4fb2d4d75b.png">

**Comment by elmindreda** [comment]
Are you using the GLFW 3.3.7 macOS binary archive? If so, did you pick the `libglfw.3.3.dylib` binary from the `lib-arm64` or the `lib-universal` directory?

**Comment by mcsantiago** [comment]
I believe the issue is related to my homebrew installation not installing the arm64 version of glfw correctly. This goes back to my original installation of homebrew itself not being the correct arm64 version.

https://github.com/Homebrew/install/issues/767

**Comment by Saadeh009** [comment]
check [this](https://stackoverflow.com/questions/71830787/make-building-for-x86-64-but-glfw-installed-from-homebrew-is-for-arm64-aarch64) thread
