### ISSUE TITLE
glfwSwapInterval a NOP in Vista and later...

### ISSUE THREAD

**Issue by blitz-research** [glfw/glfw#209]
Not sure if this is really a bug, but the swapInterval function in wgl_context.c ignores the swapInterval request if desktop compositing is enabled - which seems to be true in both windowed/fullscreen on vista or later.

Not a big deal with swap interval of 1, since vsync is on by default, but it means you can't turn off vsync on vista or later at all. Perhaps understandable in windowed mode, but fullscreen too?

**Comment by elmindreda** [comment]
This has received what may be a more appropriate fix with 8309e0ecb09fe5cf670dff5df1e7ca71821c27bd.
