### ISSUE TITLE
Window icon support

### ISSUE THREAD

**Issue by jgcodes2020** [glfw/glfw#2095]
GLFW's current Wayland driver does not support this, but there is a hacky way around it. You can create a temporary .desktop file and icon file with the correct window class, then delete them when the app closes.

**Comment by linkmauve** [comment]
Correct, there is no way to specify an icon in the code on Wayland.  What you should actually do is install the .desktop and the icon alongside your program, and keep it there for the entire time it is installed on the user’s computer.
