### ISSUE TITLE
Question: why is ToUnicode called twice?

### ISSUE THREAD

**Issue by hajimehoshi** [glfw/glfw#2100]
`ToUnicode` is called twice at `_glfwUpdateKeyNamesWin32` (https://github.com/glfw/glfw/blob/7dfd84c458dfa12b351c932b8281b13faf7b50b9/src/win32_init.c#L499-L508). This was introduced five years ago (https://github.com/glfw/glfw/commit/f8668c5a9fcec29adbfc6c2e096c88f1c985ce09).

From the document of `ToUnicode` (https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-tounicode), I could not find the reason why `ToUnicode` should be called twice. I'd be happy if there was a comment about this hack.

Thanks,

**Comment by elmindreda** [comment]
Oh, yes, that needs a comment. It's to get the key name for [dead keys](https://en.wikipedia.org/wiki/Dead_key). A call to `ToUnicode` is essentially a key press, and you need two to get a dead key to produce output.
