### ISSUE TITLE
what is the purpose of this function call?

### ISSUE THREAD

**Issue by samas69420** [glfw/glfw#2104]
in win32_init file at line 74 this function is called, i thought getmodulehandleexw was used for loading DLLs and i am a bit confused about why here it is called using &_glfw
`    if (!GetModuleHandleExW(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS |...`

**Comment by elmindreda** [comment]
That call retrieves the module handle (or [instance handle](https://devblogs.microsoft.com/oldnewthing/20040614-00/?p=38903)) of the binary (EXE or DLL) that contains that copy of GLFW. Some Win32 objects and operations are per-module so GLFW needs to know its own identity.

The `GetModuleHandle*` functions don't load DLLs but they can return the handle of any currently loaded module.

**Comment by samas69420** [comment]
oh ok thank you very much
