### ISSUE TITLE
`glfwSwapBuffers` Hangs On Wayland When The Window Is Invisible

### ISSUE THREAD

**Issue by TheBrokenRail** [glfw/glfw#2109]
### Expected Behavior

`glfwSwapBuffers` never hangs, if there aren't any events, it should return almost immediately.

### Actual Behavior

When the window is visible, `glfwSwapBuffers` works fine, but when it's invisible (doesn't even have to be minimized), `glfwSwapBuffers` hangs.

### Steps To Reproduce

Apply this patch and run the `gears` example, notice how it stops printing `polling` debug messages when it's invisible.

```patch
--- a/examples/gears.c
+++ b/examples/gears.c
@@ -339,6 +339,7 @@ int main(int argc, char *argv[])
     init();
 
     // Main loop
+    int i = 0;
     while( !glfwWindowShouldClose(window) )
     {
         // Draw gears
@@ -349,6 +350,7 @@ int main(int argc, char *argv[])
 
         // Swap buffers
         glfwSwapBuffers(window);
+        fprintf(stderr, "polling %i\n", i++);
         glfwPollEvents();
     }
 
```

### System Information

Ubuntu 22.04 Wayland

**Comment by TheBrokenRail** [comment]
After further testing, this seems to be `glfwSwapBuffers`, not `glfwPollEvents`. Still hangs though.

**Comment by TheBrokenRail** [comment]
And even further testing reveals that this isn't even related to the Wayland windowing code, but also occurs on X11 windows as long as you're using XWayland. It also seems to affect other GL calls like `glClear`. Is this even GLFW's fault?

**Comment by TheBrokenRail** [comment]
Looks like SDL had a similar issue: https://github.com/libsdl-org/SDL/issues/4335

**Comment by TheBrokenRail** [comment]
After more research, this just seems to be a Wayland problem.

**Comment by elmindreda** [comment]
This should no longer be the case since 094aa6d3c721397825cb1095c156353463ecafb5.
