### ISSUE TITLE
Mechanism for identifying a Rift

### ISSUE THREAD

**Issue by jherico** [glfw/glfw#212]
The current GLFW monitors api, at least on Windows and OSX really identifies 'screens' rather than monitor (working from the terminology that a screen represents a virtual desktop area, while a monitor identifies a physical display device).  

This poses problems for developers attempting to target the Oculus Rift, particularly if they're using cloned displays, as the top level monitor only identifies itself by the name of "Generic PnP Monitor".  

Potential solutions could involve changing the behavior to include both virtual screens and actual monitors, or providing a parallel API for physical devices in addition to the current API for screens.  Alternatively, providing an API to access the EDID information for each monitor might prove useful.  

I'll look into the code and see if there's an easy way to adapt for the first approach, listing all monitors, active, inactive, cloned or otherwise.

**Comment by elmindreda** [comment]
@jherico Have you had any success making OpenGL rendered direct HMD mode output independent of the default framebuffer size, with or without GLFW? The tip from the Oculus forums to call `ovrHmd_AttachToWindow` before context creation seems to make no difference.

**Comment by jherico** [comment]
No I haven't.  It seems that while the Direct3D window size isn't related
to the Rift resolution, the OpenGL window you create must be the same
resolution as the Rift (or rather, if you scale it down, the resulting
image quality on the Rift suffers).  I've also found that unlike the
Direct3D window, which can be hidden, the OpenGL window has to, at least
initially, be visible on the screen.  It seems that after a bit you can
hide it and still have the Rift work, but I'm not clear on the delay
involved.

I suspect that because more of the OpenGL implementation is baked into the
vendor drivers with GL than with D3D that there are fewer touchpoints
available into which Oculus can inject their code.  Hopefully the big
vendors will get on board and start providing some decent VR extensions in
OpenGL soon.
