### ISSUE TITLE
Warning about "_GNU_SOURCE" redefined

### ISSUE THREAD

**Issue by alexballas** [glfw/glfw#2133]
Compiling for Linux x86_64 (Ubuntu 18.04) throws a Warning
```
# github.com/go-gl/glfw/v3.3/glfw
In file included from ../../go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20220516021902-eb3e265c7661/c_glfw_lin.go:20:0:
../../go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20220516021902-eb3e265c7661/glfw/src/x11_window.c:30:0: warning: "_GNU_SOURCE" redefined
 #define _GNU_SOURCE
 
<command-line>:0:0: note: this is the location of the previous definition
```
I understand that this is just a Warning, but it would be good if it could be silenced or fixed.
Let me know if you'd like more info on this

**Comment by dmitshur** [comment]
I agree this looks like a duplicate of #2076, and should be discussed in go-gl/glfw#351.

We've just pushed a fix that should resolve that issue, @alexballas please feel free to try again with the latest version (e.g., `go get github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20220622232848-a6c407ee30a0`), and comment in go-gl/glfw#351 if the issue with the Go package persists.

**Comment by alexballas** [comment]
thanks for that. The new go-gl version did fix the issue.
