### ISSUE TITLE
Win32 - Custom WNDPROC support

### ISSUE THREAD

**Issue by jb-perrier** [glfw/glfw#2144]
I recently needed to use a custom [WNDPROC](https://github.com/glfw/glfw/blob/da6713cd096a40a4512f468b34c189017e73f987/src/win32_window.c#L538) implementation.
I haven't found anything related in issues or PRs, maybe i've missed something.
For sure i can change the window proc using SetWindowLongPtr, but i would miss all window initialization events.

It would require to be able to set a custom default `WNDPROC` implementation, so new windows use it directly.
The [orignal one](https://github.com/glfw/glfw/blob/da6713cd096a40a4512f468b34c189017e73f987/src/win32_window.c#L538), should be exposed too, so a custom one can call it in order to keep all glfw features working.

It should probably be exposed using [glfw3native.h](https://github.com/glfw/glfw/blob/master/include/GLFW/glfw3native.h).

Should i go forward and push a PR ? That would be a great addition in terms of flexibility.

**Comment by jb-perrier** [comment]
Thx for the quick response, i did not think it would break that much code.

**Comment by dvoyni** [comment]
@elmindreda 
> You can set the window procedure of the main GLFW window class with SetClassLongPtrW **before** creating the first window, and fetch the current one with GetClassLongPtrW.

How can I get HWND to do it if window is not created yet?
I tried to do it after window creation -- without success, my WindowProc is not being called.
