### ISSUE TITLE
glfwInit() fails to create a window when on discord call.

### ISSUE THREAD

**Issue by Dromader2137** [glfw/glfw#2154]
There is no error it just stops the program, but doesn't crash.

**Comment by FuzzyQuills** [comment]
Maybe try disabling the Discord Overlay if it's enabled?

**Comment by Dromader2137** [comment]
Sorry for the really long wait, but the problem disappeared and I forgot about this issue. It was probably something very configuration specific.

**Comment by elmindreda** [comment]
No worries and thank you for the update!
