### ISSUE TITLE
msys2 build missing lib and dll

### ISSUE THREAD

**Issue by HoneyTorres** [glfw/glfw#2156]
using msys2 build target missing lib and dll, i has used pacman installed make and gcc/g++,i consider this is a uncompletable feature

ENV:
  GLFW 3.3.7
  cmake 3.23.2
  gcc 11.3.0
  make 4.3

**Comment by HoneyTorres** [comment]
> 

i use the default command to config and build, but when i open the shared library, i get the dll and lib, but i still need copy dll and a to example

**Comment by JG-Adams** [comment]
Might be similar to mine.
I use codeblock and targeted GLFW and only got the libglfw3.a file.
I notice that libglfw3dll.a is missing as well as the .dll How do you get that out of a cmake project?

**Comment by JG-Adams** [comment]
Question, a little off topic.
But, if I compile with window binary, will it work on other platform?
How does that work?
