### ISSUE TITLE
glfwGetCurrentContext() returns NULL, although a context has been set as current.

### ISSUE THREAD

**Issue by aryanbaburajan** [glfw/glfw#2165]
Short:
![image](https://user-images.githubusercontent.com/51789606/183281666-1d8dac2d-0b2a-43fd-840f-7576786ad279.png)
I'll let this image here itself explain the issue. Is there *any* scenario where this would happen?
And I can confirm that `engine->window.window` is a valid `GLFWwindow*`, and is the one I intend to use.

Now for context:
I am working on a game engine, in which the core part would initialize GLFW, create a window, and handle all systems. It would then load components from a DLL at runtime, one of which is supposed to render graphics onto the same context. So the code above is inside that dll.
If I try to use `gladLoadGLLoader((GLADloadproc)glfwGetProcAddress)` (inside the dll), GLFW errors out saying
```
GL::ERROR::65538: Cannot query entry point without a current OpenGL or OpenGL ES context
```
and glad fails to initialize.

I would appreciate some help on this, thank you.

Extra note: The only possibility that I can think of, is that `glfwMakeContextCurrent()` somehow sees the `GLFWwindow*` object as invalid and sets it as `NULL` instead.

**Comment by aryanbaburajan** [comment]
Seems like GLFW loses its context in the dll, from some testing.

**Comment by aryanbaburajan** [comment]
Late but, incase anyone comes across this: linking to GLFW as a shared library, and making the Engine and the Dll link to it the same way fixed the issue.

**Comment by paulwgw88** [comment]
> Late but, incase anyone comes across this: linking to GLFW as a shared library, and making the Engine and the Dll link to it the same way fixed the issue.

Thanks for your note, it helps a lot for me.
Here is an interesting thing. I have a shared library built both for linux(.so) and windows(.dll).
On linux, it works fine when my library linking GLFW as a static library, and calling "gladLoadGLLoader((GLADloadproc)glfwGetProcAddress)" to load OpenGL functions.
However, on windows this method is not working. The library has to link GLFW as a shared library. Maybe it has something to do with the difference between dll and so.

**Comment by expfunction** [comment]
> Late but, incase anyone comes across this: linking to GLFW as a shared library, and making the Engine and the Dll link to it the same way fixed the issue.

Thanks a lot for this suggestion, I was struggling with the lost context because of not using glfw3dll.lib.
