### ISSUE TITLE
Add support for cairo?

### ISSUE THREAD

**Issue by milasudril** [glfw/glfw#2174]
Sometimes, you simply  want to display an array of pixels, or other simple graphics. You can go for this solution: https://gist.github.com/tobyp/a4cb297c866fe53cc044467c9a866457, but it is X11 specific. It would be nice to be able to use cairo without a hard dependency to the display server backend.

**Comment by ByunghoonKim** [comment]
Hi, 
I do not know on what basis a new feature gets implemented. But I would say that this [FAQ item](https://www.glfw.org/faq#12---what-is-glfw-not) 

> GLFW is by design not…

> -  capable of rendering anything at all. Rendering is up to you and/or other libraries.

suggests any direct support for the cairo library is not coming any time soon. This [discussion thread](https://discourse.glfw.org/t/glfw-and-cairo-use/1697) might be of interest to you.

**Comment by bmitc** [comment]
I don't think such a graphics utility will be or should be built into GLFW. It is a windowing library only.

I am using Skia with GLFW just fine. Can Cairo not draw to an OpenGL context? Every GLFW window gets a context that can be drawn to.

https://www.cairographics.org/OpenGL/

**Comment by milasudril** [comment]
@bmitc I did not meant that it should be "built-in". GLFW doesn't wrap OpenGL or Vulkan either.  What I want is to get a cairo_context_t given a GLFWWindow, without having to write platform specific glue code.

**Comment by bmitc** [comment]
I am not familiar with Cairo enough to comment on that code, but I wouldn't be so sure that that example needed to call the platform-specific functions in GFLW. I am using SkiaSharp with GFLW and do not call any platform-specific code in either GFLW or SkiaSharp. I have posted a [GitHub Gist here as an example](https://gist.github.com/bmitc/e4d4399a1d7b71e1036914b8be5e337e). The functions prefixed with `glfw` are direct bindings to the corresponding GLFW functions. You can see that all you need is the window's context and the `glfwGetProcAddress` to be able to bind a Skia surface to the context and then draw to it. I would guess that Cairo is not much different. Hopefully you can use my example and the example you posted, but removing or replacing the window specific functions, to get something working.

You might move this to the [GLFW forum](https://discourse.glfw.org/) since this isn't really a GLFW issue.

Actually, just looking into backing up my last sentence, I searched the Cairo documentation. [For surfaces, it states that](https://www.cairographics.org/manual/cairo-cairo-surface-t.html#cairo-cairo-surface-t.description):

> A cairo surface is created by using backend-specific constructors, typically of the form cairo_*backend*_surface_create().

So this issue of needing platform-specific constructors is a Cairo limitation/constraint and not a GLFW one.

**Comment by milasudril** [comment]
> A cairo surface is created by using backend-specific constructors, typically of the form cairo_backend_surface_create().

The same must be true for OpenGL as well. Depending on platform (GLX, Wayland, Windows), you need a different set of functions. So the request is to add wrappers for all cairo_*backend*_surface_create, and GLFW should substitute *backend* properly.

**Comment by rjopek** [comment]
I believe GLFW should provide output for the function! `cairo_image_surface_create_for_data`

Just like SDL:

``` c
        SDL_FillRect( sdl_surface, NULL, 0 );

        /* Create a cairo surface which will write directly to the sdl surface */
        cairo_surface_t *cairo_surface = cairo_image_surface_create_for_data (
            (unsigned char *)sdl_surface->pixels,
            CAIRO_FORMAT_RGB24,
            sdl_surface->w,
            sdl_surface->h,
            sdl_surface->pitch
        );
        cairo_t *cr = cairo_create(cairo_surface);
```

On the other hand, you can ask what `nuklear_glfw_gl2.h` is doing here?
Is it an inseparable element of GLFW?

Kind regards,
--Rafał

**Comment by rjopek** [comment]
I believe GLFW should provide output for the function! `cairo_image_surface_create_for_data`

Just like SDL:

``` c
        SDL_FillRect( sdl_surface, NULL, 0 );

        /* Create a cairo surface which will write directly to the sdl surface */
        cairo_surface_t *cairo_surface = cairo_image_surface_create_for_data (
            (unsigned char *)sdl_surface->pixels,
            CAIRO_FORMAT_RGB24,
            sdl_surface->w,
            sdl_surface->h,
            sdl_surface->pitch
        );
        cairo_t *cr = cairo_create(cairo_surface);
```

On the other hand, you can ask what `nuklear_glfw_gl2.h` is doing here?
Is it an inseparable element of GLFW?

Kind regards,
--Rafał

**Comment by rjopek** [comment]
I believe GLFW should provide output for the function! `cairo_image_surface_create_for_data`

Just like SDL:

``` c
        SDL_FillRect( sdl_surface, NULL, 0 );

        /* Create a cairo surface which will write directly to the sdl surface */
        cairo_surface_t *cairo_surface = cairo_image_surface_create_for_data (
            (unsigned char *)sdl_surface->pixels,
            CAIRO_FORMAT_RGB24,
            sdl_surface->w,
            sdl_surface->h,
            sdl_surface->pitch
        );
        cairo_t *cr = cairo_create(cairo_surface);
```

On the other hand, you can ask what `nuklear_glfw_gl2.h` is doing here?
Is it an inseparable element of GLFW?

Kind regards,
--Rafał

**Comment by rjopek** [comment]
I will gladly accept a wave of criticism.

**Comment by milasudril** [comment]
@rjopek The idea here is that GLFW should provide some internal framebuffer, that cairo renders to, as opposed to what you get if you would dig up the X11 reference, right? This would require an extra blit operation I guess.

**Comment by milasudril** [comment]
@rjopek You should probably keep the texture object alive and write to it using glTextureSubImage2D. Also, gl_00.c uses the legacy OpenGL (fixed-function) pipeline, not necessarily available. How much overhead is it to use a texture rather than a raw blit?

**Comment by milasudril** [comment]
Another usecase for setting up a cairo context is as a graceful fallback in case the accelerator driver fails to initialize due to a bad driver. Then, it is not a viable option to rely on an open gl or vulkan surface.
