### ISSUE TITLE
glfwSetWindowPos memory leak

### ISSUE THREAD

**Issue by Renardjojo** [glfw/glfw#2182]
Hello ! 
I am using glfw for an application that needs to stay open for a long time but this application is leaking. 
After some research, I saw that the leak was coming from the "glfwSetWindowPos" function.
I made a quick example to illustrate the memory leak:
```c
#include <windows.h>
#include <GLFW/glfw3.h>
#include <cmath>

int CALLBACK WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR pCmdLine, int nCmdShow)
{
    int  frame = 0;

    if (!glfwInit()) exit(-1);

    GLFWwindow* window = glfwCreateWindow(500, 500, "Leak", NULL, NULL);
    glfwMakeContextCurrent(window);
    glfwShowWindow(window);

    while (!glfwWindowShouldClose(window))
    {
        glfwPollEvents();
        frame += 1;
        glfwSwapBuffers(window);
        glfwSetWindowPos(window, std::cos(frame / 100.f) * 50.f, std::sin(frame / 100.f) * 50.f);
    }
    return 0;
}
```
After 5 minutes, my application allocated 25MB in RAM. 10 minutes later, 50MB was allocated for the above code example.
I tested directly on a release build (run with .exe).
I ran the application on Windows 11.
![image](https://user-images.githubusercontent.com/55276408/190223377-6946367d-70f6-4188-999a-53c36050865b.png)

Based on Visual Leak Detector, it seems to be a memory allocation (not a memory leak) with std::vector behaviour: 
![image](https://user-images.githubusercontent.com/55276408/190247347-d4b2cb7b-5935-48a0-ba16-ab03c26878e4.png)

Thank you for help !

**Comment by Renardjojo** [comment]
Here the call stack where provide the memory issue : 
![image](https://user-images.githubusercontent.com/55276408/190261484-880f955a-e52e-44e5-8b05-6bdc07561bf9.png)

**Comment by tquante** [comment]
If atig6txx.dll is leaking then its probably not an issue of glfw, but an issue of your AMD GPU driver or the windows layer calling it. glfwSetWindowPos does not allocate anything and calls only win32 functions (see win32_window.c line 1591).

**Comment by Renardjojo** [comment]
Issue reported to AMD, I am waiting for an answer about that.

**Comment by Renardjojo** [comment]
Relative to this post (https://community.amd.com/t5/opengl-vulkan/high-memory-usage-leak-when-moving-window/td-p/548101), the issue provided from an old driver version. 
I close the ticket
