### ISSUE TITLE
wl_display_roundtrip does not ensure the xdg_configure event has been sent

### ISSUE THREAD

**Issue by markbolhuis** [glfw/glfw#2197]
Currently when creating a toplevel window glfw uses `wl_display_roundtrip` after committing the surface as a way to ensure the configure event has been received: https://github.com/glfw/glfw/commit/f2617a671f7003a57a52e6f84afc6903e0a824f6
However this is an incorrect assumption since the configure event may not be sent immediately, and the roundtrip may return before the configure event has been received and dispatched.

After speaking to one of the wayland devs on IRC it seems that the spec isn't clear on this behavior.
Some requests, such as `wl_display_get_registry`, have their resulting events sent immediately, whilst others like `wl_surface_commit` only schedule an event for the future and will send it later. 
The only guarantee that `wl_display_roundtrip` provides is that all events that glfw has received so far have been read and dispatched, it says nothing about the server having sent all events it's supposed to.

This is the behavior of both kwin and wlroots.

**Comment by elmindreda** [comment]
Thank you for the bug report! That definitely was a bug. It should be fixed now as of 3.3.8 or earlier. This issue was helpful when initially restructuring this bit of the Wayland backend but then I forgot to put it into a milestone.
