### ISSUE TITLE
Wayland window is always resizable 

### ISSUE THREAD

**Issue by mulle-nat** [glfw/glfw#2203]
If if I add  `glfwWindowHint(GLFW_RESIZABLE, GLFW_FALSE);` to the [triangle-opengl](https://github.com/glfw/glfw/blob/master/examples/triangle-opengl.c#L92) example, the window becomes non-resizable in X11 but the hint does not affect Wayland. Even, if one were to reset the window size manually after the resize attempt, the user would still see "resize cursors" and would be disappointed that resize isn't working.

Also there are a load of `Error: Wayland: Standard cursor shape unavailable` errors, when mousing over the wayland window border.

**Comment by vadtec** [comment]
> If if I add `glfwWindowHint(GLFW_RESIZABLE, GLFW_FALSE);` to the [triangle-opengl](https://github.com/glfw/glfw/blob/master/examples/triangle-opengl.c#L92) example, the window becomes non-resizable in X11 but the hint does not affect Wayland.

I have noticed this as well with code that I am working on separately. It also seems to ignore the minimum/maximum size hints as well.

**Comment by Ardn0** [comment]
I have same issue, glfwWindowHint(GLFW_RESIZABLE, GLFW_FALSE) is ignored.

**Comment by elmindreda** [comment]
With 690a15f92963b4ad2add09a91ccb2ee5b4085909 the GLFW_RESIZABLE window hint and attribute should now work for all decoration paths. Thank you for the bug report!
