### ISSUE TITLE
Resizing with fallback decorations can cause viewport protocol error

### ISSUE THREAD

**Issue by mulle-nat** [glfw/glfw#2204]
Easy to reproduce with `examples/triangle-opengl`. Resize the window, until its width and or height become zero or negative. The window closes and the app exits with `wp_viewport@33: error 0: all values must be either positive or -1`.

Remedy: set a minimum window size. glfw should do this during window initialization for wayland windows, because the default behaviour is obviously non-sensible.

Also: When running any of the examples with a wayland window, I always get `libEGL warning: DRI2: failed to create dri screen`.

**Comment by elmindreda** [comment]
Thank you for the bug report! This should be fixed for all paths now with b61f3fc4796a5b998d70aeb5e4723ea8b681403d. Please let me know if you would like the credit line changed.

**Comment by mulle-nat** [comment]
Thanks for the credit, though you can leave it out, since it was just a bug report. Otherwise "Nat!" or "mulle_nat" would be preferred. Thanks for all the work on glfw3.

**Comment by elmindreda** [comment]
A good bug report is just as helpful as a PR. Updated with dbf7cfc4dc69517cd8618ca01c49053aa9373f63.
