### ISSUE TITLE
glfwSwapBuffers always vsyncs

### ISSUE THREAD

**Issue by mulle-nat** [glfw/glfw#2205]
This is also easy to reproduce with [`examples/triangle-opengl`](https://github.com/glfw/glfw/blob/master/examples/triangle-opengl.c). First make the animation non-time dependent so you can "see" the framerate. Also change `glfwSwapInterval` to zero:

``` c
// line #84
   float x = 0.0;
...
// line #105
   glfwSwapInterval( 0);
...
// line #152
   x += 1 / 60.0;
   mat4x4_rotate_Z(m, m, x);
```

When run as/with X11 the triangle will spin like crazy. As wayland code the triangle spins smoothly. Which in this case is not wanted.

#### Expected behaviour:
  
*If the interval is zero, the swap will take place immediately when `glfwSwapBuffers` is called without waiting for a refresh.*

**Comment by gracicot** [comment]
Note that even if `glfwSwapBuffers` returns immediately, it won't actually disable vsync and will act more like triple buffering do. Disabling vsync will require an explicit Wayland protocol which don't exists yet.

**Comment by FuzzyQuills** [comment]
> This is also easy to reproduce with [`examples/triangle-opengl`](https://github.com/glfw/glfw/blob/master/examples/triangle-opengl.c). First make the animation non-time dependent so you can "see" the framerate. Also change `glfwSwapInterval` to zero:
> 
> ```c
> // line #84
>    float x = 0.0;
> ...
> // line #105
>    glfwSwapInterval( 0);
> ...
> // line #152
>    x += 1 / 60.0;
>    mat4x4_rotate_Z(m, m, x);
> ```
> 
> When run as/with X11 the triangle will spin like crazy. As wayland code the triangle spins smoothly. Which in this case is not wanted.
> #### Expected behaviour:
> 
> _If the interval is zero, the swap will take place immediately when `glfwSwapBuffers` is called without waiting for a refresh._

Could there be a glFinish in there somewhere? I observed that if glFinish instead of glFlush is called when running an application on Wayland, it (incorrectly?) waits for vsync. The fix is to use glFlush.

Not sure if glClientWaitSync is affected in the same way.

**Comment by elmindreda** [comment]
An explicit Wayland protocol for this [exists now](https://wayland.app/protocols/tearing-control-v1), but it's for us to implement. Once this is adopted by the proper layers a swap interval of zero will suddenly work. Closing this as a resolved external bug.
