### ISSUE TITLE
[Win32] glfwInit() hangs forever

### ISSUE THREAD

**Issue by Khrysys** [glfw/glfw#2216]
Platform: Windows 10 64-bit
Compiler: MSVC 16 2019
Release or Commit: Using the tagged 3.3.8 version.

I'm creating a C++ Vulkan Game engine, and I'm using GLFW for window creation. Everything works up until win32_joystick creation. 

Call Stack:
```txt
win32_joystick.c!_glfwJoysticksWin32() Line 500
win32_init.c!_glfwPlatformInit() Line 591
init.c!glfwInit() Line 324
init.cpp!createEngine(Engine* pEngine, CreateInfo* pCreateInfo, std::function<void(Message::Message*)> pCallback) Line 9
``` 
It hangs on this line:
```c
if (FAILED(DirectInput8Create(_glfw.win32.instance,
                                      DIRECTINPUT_VERSION,
                                      &IID_IDirectInput8W,
                                      (void**) &_glfw.win32.dinput8.api,
                                      NULL)))
```
And maybe I'm doing something wrong, but I went through the getting started code and it's the same initialization as I have here. It does actually call it, but the last call is on ntdll.dll.

Here's my first few lines of the initialization. 
```cpp
DGAPI DgBool32 Dragon::createEngine(Engine* pEngine, CreateInfo* pCreateInfo, std::function<void(Message::Message*)> pCallback) {
    // Copy the message name pointer into the engine
    pEngine->name = pCreateInfo->name;

    // Message Init
    if(DRAGON_MESSAGE_ENABLED) {
        pEngine->message.pCallback = pCallback;
    }

    // Verbosity Message for debugging
    if(pCreateInfo->verbosity >= 1) {
        Message::Message message;
        message.code = 0x11100000FFFFFFFF;
        message.message = "Dragon::createEngine called";
        Message::sendMessage(pEngine, &message);
    }

    if(!glfwInit()) {
        Message::Message message;
        message.code = 0xFF12000000000000;
        message.message = "GLFW failed to be initialized";
        Message::sendMessage(pEngine, &message);
        return DG_FALSE;
    }
    //... Etc
}

**Comment by MarkusMiller** [comment]
This here is the reason: https://github.com/glfw/glfw/issues/1284#issuecomment-1462108519

Might be fixed in 3.4 (nobody knows when) and it's bugging me ever since I started using GLFW in 2015...

**Comment by Khrysys** [comment]
I somehow worked around this, not sure how. It no longer hangs at all, and initialization takes the expected amount of time now.

**Comment by MarkusMiller** [comment]
From my experience, fiddling around with USB peripherals triggers that behaviour pretty well.  Every time I reboot it's fine and after a while (if I simply touch my headphones for example) it's messed up and takes ages... looking forward to 3.4 :-(
