### ISSUE TITLE
How to get NSView/contentView?

### ISSUE THREAD

**Issue by mightgoyardstill** [glfw/glfw#2234]
so i currently need to get NSView as i'm making a window to pipe through some graphics for a VST3 plugin (using the vst3sdk).

i've looked here:
https://www.glfw.org/docs/latest/group__native.html#gac3ed9d495d0c2bb9652de5a50c648715
but unfortunately i can only get: `id: glfwGetCocoaWindow (GLFWwindow *window)`

i've figured something out where i can do:
`[glfwGetCocoaWindow(editorWindow)contentView]
`
but unfortunately that requires me to compile in obj-c++ to access the contentView.

is there anyway i can get NSView/contentView in a c++ friendly manor?

would it be worth adding something like:

```
GLFWAPI id glfwGetCocoaView(GLFWwindow* handle)
{
    _GLFWwindow* window = (_GLFWwindow*) handle;
    _GLFW_REQUIRE_INIT_OR_RETURN(nil);

    if (_glfw.platform.platformID != GLFW_PLATFORM_COCOA)
    {
        _glfwInputError(GLFW_PLATFORM_UNAVAILABLE,
                        "Cocoa: Platform not initialized");
        return NULL;
    }

    return window->ns.view;
}
```

to the cocoa_window.m file?

**Comment by mightgoyardstill** [comment]
would it be worth adding something like:

`GLFWAPI id glfwGetCocoaView(GLFWwindow* handle)
{
    _GLFWwindow* window = (_GLFWwindow*) handle;
    _GLFW_REQUIRE_INIT_OR_RETURN(nil);

    if (_glfw.platform.platformID != GLFW_PLATFORM_COCOA)
    {
        _glfwInputError(GLFW_PLATFORM_UNAVAILABLE,
                        "Cocoa: Platform not initialized");
        return NULL;
    }

    return window->ns.view;
}`

to the cocoa_window.m file?

**Comment by codedcosmos** [comment]
I am finding that I need the same thing for a Rust project. The more obvious use case to me is C++/Metal + GLFW.

**Comment by elmindreda** [comment]
This was just added with 1fb7f0e1205a44b69983ddf38079fd1d04dc49b7.

**Comment by codedcosmos** [comment]
Thank you!
