### ISSUE TITLE
X11, tiny logical operator bug

### ISSUE THREAD

**Issue by zmn28hgbn59kcmlpio8unfh7fdre523esd28q9a** [glfw/glfw#2236]
https://github.com/glfw/glfw/blob/57cbded0760a50b9039ee0cb3f3c14f60145567c/src/x11_init.c#L717-L718

the comment says:
**// The GLFW RandR path requires at least version 1.3**

the logical or should be replaced with logical and. (&& instead of ||)

**Comment by elmindreda** [comment]
Hi! The logic here is that any version from 1.3 and later would be valid. If the expression used `&&` then neither version 1.3 nor version 2.2 would be valid.
