### ISSUE TITLE
WSL GLFW Wayland - Can't build?

### ISSUE THREAD

**Issue by Hallett-K** [glfw/glfw#2261]
Hello,

I'm trying to build a project using GLFW 3.3.8 from source on a fresh Ubuntu install,  I've done an apt-get for libwayland-dev, libxkbcommon-dev and wayland-protocols. On trying to build with make I'm told that "wayland-xdg-shell-client-protocol.h" can't be found.

**Comment by Hallett-K** [comment]
I'm new to Linux, and am porting over a game project made in Visual Studio where I've just included the necessary files in the 'include' and 'src' folders, and I guess I was just hoping this was also possible with Linux

**Comment by elmindreda** [comment]
You could generate those header files once, by hand, and then add them to your project to get things building. They're supposed to be generated fresh, as they contain inline marshalling code between the public Wayland API and its protocol, but if you're going to be selling a binary then they'll be frozen in time as part of it anyway.

**Comment by elmindreda** [comment]
The easiest way to get them is to configure and build GLFW with CMake and then get them from the build tree. You will need the `cmake` and `extra-cmake-modules` packages in addition to the ones you mentioned above.
```sh
$ cd glfw
$ cmake -B build -D GLFW_USE_WAYLAND=1
$ make -C build
```
They'll be in `build/src/`.

You can also generate them directly with only `wayland-scanner`.
```sh
$ wayland-scanner client-header /usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml xdg-shell-client-protocol.h
$ wayland-scanner public-code /usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml xdg-shell-protocol.c
```
...and so on for each required protocol.

**Comment by Hallett-K** [comment]
Thank you!
