### ISSUE TITLE
WSL, glfw, GLFW_CURSOR_DISABLED, and other not-so-minor annoyances

### ISSUE THREAD

**Issue by vadtec** [glfw/glfw#2271]
microsoft/wslg#376
(and many many many others...)

[https://www.youtube.com/watch?v=0-YAoPrs6pI](url) - A short video that showcases the issue

In the above video, I hadn't yet taken the steps of upgrading everything like drivers. You can see the specs for my PC and software in the wslg issue linked above. Putting slightly old drivers aside, I wanted to link the video here anyways to provide a visual reference as to what is happening.

Though I'm pretty sure the answer to this is no, I'll ask anyways: is there not some way to trace out the events as they are happening within WSLg/wayland/x11 that wouldn't involve custom compiling everything in an attempt to trace down the bug(s)?

This seems to be such a prevalent issue I'm surprised some "expert" hasn't identified the cause and fixed it.

So far, my only solution has been to cross-compile for Windows, which has it's own set of challenges.

Has anyone, anywhere, even found where to start looking? I've resorted to modifying the GLFW source checking Xlib calls for failures or unexpected results, or just anything that seems out of place. I am by no means an expert in GLFW or Xlib, so the best I can do is make educated guesses about what should be happening.

On my short list of things that do not appear to work when running a GLFW app on WSL:

- glfwSetWindowSizeLimits(window, 1024, 768, GLFW_DONT_CARE, GLFW_DONT_CARE);
    - this doesn't honor the minimum or maximum sizes requested, regardless of how they are set
- glfwSetWindowAspectRatio(window, 4, 3);
    - same as above
- glfwSetInputMode(window, GLFW_CURSOR, GLFW_CURSOR_DISABLED);
    - doesnt hide the mouse cursor
    - doesnt capture the mouse within the programs window
    - doesnt return the mouse cursor to the center of the screen with glfwSetCursorPos()
- glfwSetInputMode(window, GLFW_CURSOR, GLFW_CURSOR_HIDDEN);
    - same as above
 
I'm curious why GLFW is checking screen coordinates against DBL_MAX and -DBL_MAX in places like glfwGetCursorPos() (input.c:714) when that range should really be the minimum/maximum extents of the users screen. Though I can't recall them at the moment, there are other places where I have observed similar oddities.

I'm simply pointing out the things that are causing issues, though I'm fully prepared to admit I'm not nearly well versed enough in them to offer any real insights. Though, that won't stop me from trying to figure them out.

Is glfw/glfw#1795 still a thing? Seems like it was slated for review and never went anywhere.

So, does anyone have a status or road map on GLFW running on WSL and it's associated issues? I'm sure we'd all enjoy it if we could simply drop GLFW in the source dir and start coding without having to deal with these issues.

**Comment by vadtec** [comment]
NOTE: I'm basing my investigation of this issue on [3.3.8](https://github.com/glfw/glfw/blob/3.3.8/), so all files referenced will be relative to that.

So I dug into this more deeply.

The first thing I noticed was that if I called glfwSetInputMode(window, GLFW_CURSOR, GLFW_CURSOR_DISABLED) nearly instantly after creating the window, the check at x11_window.c:2856 was failing. This lead me to believe the call was being made far to quickly and the window didn't have time to really catch up. I changed the structure of the program and made it wait until the window reported it had focus, at which point I made the call and allowed event processing to proceed normally.

Immediately after the window focus callback is called, this is the code pathway I see:

```
glfwSetInputMode (input.c:514) [returns back to my code]
    _glfwPlatformGetCursorPos (x11_window.c:2824) [returns back to glfwSetInputMode]
    _glfwPlatformSetCursorMode (x11_window.c:2852)
        _glfwPlatformWindowFocused (x11_window.c:2532) [returns back to _glfwPlatformSetCursorMode]
    disableCursor (x11_window.c:557) [returns to glfwSetInputMode]
        _glfwPlatformGetCursorPos (x11_window.c:2824) [returns back to disableCursor]
        updateCursorImage (x11_window.c:507) [returns back to disableCursor]
            calls XDefineCursor on line 521 in x11_window.c (which returns 1, not BadCursor=6 or BadWindow=3 or 0, so assuming this is a good thing)
        _glfwCenterCursorInContentArea (input.c:476) [returns to disableCursor]
            _glfwPlatformGetWindowSize (x11_window.c:2198) [returns to _glfwCenterCursorInContentArea]
                calls XGetWindowAttributes on line 2201 in x11_window.c (which returns 1, , not BadCursor=6 or BadWindow=3 or 0, so assuming this is a good thing)
            _glfwPlatformSetCursorPos (x11_window.c:2841) [ returns to _glfwCenterCursorInContentArea]
                calls XWarpPointer on line 2847 in x11_window.c  (which returns 1, , not BadCursor=6 or BadWindow=3 or 0, so assuming this is a good thing)
                calls XFlush on line 2849 in x11_window.c  (which returns 1, , not BadCursor=6 or BadWindow=3 or 0, so assuming this is a good thing)
        calls XGrabPointer on line 568 in x11_window.c (which returns GrabSuccess)
    calls XFlush on line 2864 of x11_window.c  (which returns 1, , not BadCursor=6 or BadWindow=3 or 0, so assuming this is a good thing)
```

And yet the problem persists. After having shoved my arm up the backside of the code...it's fairly apparent GLFW is doing what it is supposed to and getting back results that make sense.

I'm going to try running this code on a bare metal Ubuntu box and see if my results change.

**Comment by vadtec** [comment]
Dropped Ubuntu 22.04 on the venerable ThinkPad W520, compiled the code, and unsurprisingly it worked flawlessly.

At this point, it's clear to me the issue lies with WSLg/WSL/RDP/etc.

**Comment by elmindreda** [comment]
I've tried GLFW on WSLg and it's fairly flaky, X11 and Wayland both. Not sure yet where the issues lie. Will look into it but it's fairly low priority at the moment.
