### ISSUE TITLE
Official site = https://www.glfw.org doesn't work

### ISSUE THREAD

**Issue by DarekBDarekB** [glfw/glfw#2272]
Official site https://www.glfw.org doesn't work.

**Comment by ws909** [comment]
It does for me. Mind specifying what is broken?

**Comment by DarekBDarekB** [comment]
You haven't paid for the domain or server. Hasn't been working for a long time :) All documantation, contacts, everything...

**Comment by ws909** [comment]
What are you talking about? The server responds just fine, and provides a website that works seemingly flawlessly in WebKit and Gecko, at least.

**Comment by ws909** [comment]
> You haven't paid for the domain or server. Hasn't been working for a long time :) All documantation, contacts, everything...

Is this some sort of personal message to the repository owner? You created your profile today, and haven't specified who you are.

**Comment by DarekBDarekB** [comment]
Mhhhm. Everything with my internet works but with this site i get: Check your DNS settings.

**Comment by ws909** [comment]
You need to specify more information, such as your browser, country of origin, etc. Do you live in a country without net neutrality? Could your ISP be causing problems? There is no useful information here to help solving the issue. The only possible thing would be to check the server logs. Those are not available to contributors like myself.

**Comment by DarekBDarekB** [comment]
![obraz_2023-02-12_194917573](https://user-images.githubusercontent.com/125214103/218330739-39f17dc6-d00b-4350-8154-cef05b56753b.png)

Poland, Warsaw, tested: Chrome, Opera... Problem only with this site in the internet.

**Comment by mcjurij** [comment]
Can reach the site.

ERR_NAME_NOT_RESOLVED == DNS problem of your ISP.

"You haven't paid for the domain or server."
To make such an assumption only because oneself cannot reach a site... ouch.

Cheers,
Jurij

**Comment by elmindreda** [comment]
Closing this as it doesn't seem to not be an issue with the website.
