### ISSUE TITLE
Win32: Connecting/disconnecting monitor AFTER startup results in PLATFORM_ERROR

### ISSUE THREAD

**Issue by maximusgrey** [glfw/glfw#2274]
We have an application that uses GLFW via the Java LWJGL implementation and when connecting/disconnecting a monitor AFTER the app has started results in the error code 65544 (PLATFORM_ERROR).

Some details:
- Issue happens consistently only in Win32 in not in e.g. Linux (Wayland X11).
- Tested it on version 3.4 and 3.3 on multiple machines/monitors.
- Calling glfwGetMonitors afterwards returns a single monitor (when two are connected).
- glfwSetMonitorCallback is triggered in Linux (Wayland X11) but not in Win32.
- Restarting the application solves the error and both Monitors are recognized.

I am curious if others also experience this issue? (or that it might be something specific to our app)

**Comment by elmindreda** [comment]
What error description do you get for the platform error? Is your application processing GLFW events?

**Comment by maximusgrey** [comment]
Thank you for the response.
First I start the application with a single monitor connected (everything works fine). Then I connect a second monitor:
- Calling glfwGetError now result in code 65544 (0x10008) => PLATFORM_ERROR.
- Before the error I also set a callback via glfwSetMonitorCallback. However no event is fired in Windows (same code in Linux results in CONNECTED event.
- Calling glfwGetMonitors returns a single monitor instead of two.

**Comment by maximusgrey** [comment]
I found the issue in our app. A previous GLFW context was not properly terminated and caused issues later on.
