### ISSUE TITLE
glfwSetWindowAttrib GLFW_FLOATING attribute lost after hiding and showing window.

### ISSUE THREAD

**Issue by triplehoon** [glfw/glfw#2276]
I'm developing a GUI application in Ubuntu 20.04 using GLFW and OpenGL 3.2. My application has two windows: Window1 based on custom-made ImGui and Window2 based on Open3D Visualizer. I want to make Window2 always appear on top of Window1.

To achieve this, I'm using `glfwSetWindowAttrib(window2, GLFW_FLOATING, GL_TRUE);` in every refreshment. This works fine, but the floating attribute is lost when I hide and show Window2 using `glfwHideWindow()` and `glfwShowWindow()`.

I also tried setting `GLFW_FLOATING` as a window hint using `glfwWindowHint(GLFW_FLOATING, GL_TRUE)` before calling `glfwShowWindow()`, but it didn't work either.

Is this behavior by design, or could it be a bug?

**Comment by elmindreda** [comment]
> Is this behavior by design, or could it be a bug?

Not sure. It could be a bug somewhere or the policy of the window manager. Which desktop environment are you using and is it running on X11 or Wayland?

> I also tried setting `GLFW_FLOATING` as a window hint using `glfwWindowHint(GLFW_FLOATING, GL_TRUE)` before calling `glfwShowWindow()`, but it didn't work either.

Window hints will have no effect on windows that have already been created.

**Comment by triplehoon** [comment]
@elmindreda 
I am using X11.

**Comment by elmindreda** [comment]
Thanks! Which desktop environment or window manager are you using? Is it the default Ubuntu one?
