### ISSUE TITLE
The Wiki must Change

### ISSUE THREAD

**Issue by Snowiiii** [glfw/glfw#2279]
So im had worked on the GitHub Wiki longer time ago, So if you see the Changes you will see that "bad people" adding "bad things" so ye its Great that everyone can add something Helpfull to the Wiki but Please disable this Feature and just give People who are Safe the Permission to do that, Btw im Still want to Contuine to Maintain the Wiki

**Comment by ad8e** [comment]
Checking recent edits, I see https://github.com/glfw/glfw/wiki/Home/_compare/e630ce833b161f6470a49a637db69a96595649b9...84b7aaa46a65b6c28424451c4c7842ef5ceaadd8 and https://github.com/glfw/glfw/wiki/Home/_compare/21b2a366068de31c9e2b9994e14edbf6ce0c4a93...b76df690e2640628e219cf364edf1b435c558ae5; people are changing the official download links to malware on the wiki.

**Comment by Snowiiii** [comment]
Ye it was, Today i guess

**Comment by ws909** [comment]
https://github.com/glfw/glfw/issues/1009#issuecomment-1368325261
