### ISSUE TITLE
Is content scale equal to the ratio between framebuffer and window sizes?

### ISSUE THREAD

**Issue by coderedart** [glfw/glfw#2282]
I am running KDE/Manjaro a 14" laptop with FHD resolution. So, i use display settings to set the scale to 125%.

I tried running the `simple` example from master, I observed that content scale is shown as 1.25 (both x and y), but the sizes returned by glfwGetWindowSize AND glfwGetFramebufferSize are equal. they correspond directly to physical pixels -> 1920x1080 in my case. cursor position (both in callbacks and getCursorPos function) also use the same content area coordinates.  This was a normal window and not fullscreen. 

Glfw never specifies that content scale is the same as the ratio between content area and screen coordinates, but i assumed that's how it worked until now. Is that not the case? or am i dealing with a bug?

**Comment by coderedart** [comment]
I am trying to port emscripten from glfw 3.2 -> glfw 3.3 https://github.com/emscripten-core/emscripten/issues/18729 , and I am trying to understand how the coordinates of mouse/sizes are related to scale/dpi.

**Comment by coderedart** [comment]
I basically edited the `simple` example, by inserting the following code before entering the while eventloop.
```C
float sx = 0.0, sy = 0.0;
    glfwGetWindowContentScale(window, &sx, &sy);
    printf("scale x: %f; y: %f;\n", sx, sy);
    GLFWmonitor* mon = glfwGetWindowMonitor(window);
    printf("mon: %p\n", mon);
    glfwGetTime();
    if (mon != NULL) {
        glfwGetMonitorContentScale(mon, &sx, &sy);
        printf("monitor x: %f; y: %f;\n", sx, sy);
    }
    int ww = 0, wh = 0;
    glfwGetWindowSize(window, &ww, &wh);
    printf("window width: %d; height: %d;\n", ww, wh);

    glfwGetFramebufferSize(window, &ww, &wh);
    printf("framebuffer width: %d; height: %d;\n", ww, wh); 
```
on gnome (xorg and wayland backends) with 200% scaling on a normal (non-hidpi) monitor, i get the output
```
➜  glfw git:(7482de60) ✗ ./build/examples/simple
scale x: 2.000000; y: 2.000000;
mon: (nil)
window width: 640; height: 480;
framebuffer width: 640; height: 480;
```

**Comment by elmindreda** [comment]
> Is content scale equal to the ratio between framebuffer and window sizes?

No, not necessarily. The content scale is supposed to be "the factor you need to scale the pixel dimensions of your window content by for it to appear at a size pleasant to the user", where _content_ is things like text and UI elements.

How this is calculated varies between platforms. On macOS it happens to be the ratio between framebuffer and window sizes but that usually isn't a helpful way to think about it.

**Comment by coderedart** [comment]
nice. understood. so, virtual coordinates *may be* equal to physical coordinates. but physical coordinates *must be* equal to raw pixels. and content scale is independent of both.

I was wondering if there's any plans on  supporting emscripten here in glfw itself like sdl2 does.

If not, I will work in emscripten upstream to deal with this. because browser/webgl requires that canvas style width/height be in "css pixels" which are virtual and canvas width/height should be in raw pixels. and the ratio between both should be equal to `window.device_pixel_ratio`. atleast according to https://www.khronos.org/webgl/wiki/HandlingHighDPI .

**Comment by elmindreda** [comment]
> I was wondering if there's any plans on supporting emscripten here in glfw itself like sdl2 does at https://github.com/libsdl-org/SDL/tree/main/src/video/emscripten .

No plans at the moment, just because of lack of time.
