### ISSUE TITLE
Where to download 58cc4b2c5c2c9a245e09451437dd6f5af4d60c84 ?

### ISSUE THREAD

**Issue by erikaemma** [glfw/glfw#2288]
I have a demo, and it is using glfw 58cc4b2c5c2c9a245e09451437dd6f5af4d60c84, but I can't find it.

**Comment by dougbinks** [comment]
This commit is included in release 3.3 and beyond, so the latest release should have it: https://github.com/glfw/glfw/releases/tag/3.3.8

However the linked commit is simply an internal change, which shouldn't effect your demo.
