### ISSUE TITLE
GLFW crashes when run under ASAN on Windows

### ISSUE THREAD

**Issue by spaderthomas** [glfw/glfw#2294]
Hi! First off, thanks for the wonderful library. It's one of my favorite and I've used it countless times.

I compiled a very minimal GLFW program on Windows which opens a window and busy waits. When run with ASAN disabled, it works. As soon as I enable ASAN, it doesn't! More specifically, it crashes [here ](https://github.com/glfw/glfw/blob/3.3.8/src/wgl_context.c#L456) with a highly useful and cool `Critical error detected c0000374`, although this would appear to be heap corruption at some other point manifesting itself, if that is indeed the issue.

I reproduced this across:
- Several machines
- Pre-built binaries (pulled from GitHub -> VS 2022 version), as well as binaries compiled from source
- Static and dynamic linkage

I link the CRT with /MDd as recommended in the README. I also linked to the following system libraries:
```
opengl32.lib
kernel32.lib
user32.lib
gdi32.lib
winspool.lib
shell32.lib
ole32.lib
oleaut32.lib
uuid.lib
comdlg32.lib
advapi32.lib
```

I've included a branch of my repository that has _only_ a minimal GLFW program. It's [here ](https://github.com/spaderthomas/gl-sample/tree/what-the-fuck) (make sure to get the linked branch). As an aside, you'll see lots of `Access violation reading location` from ASAN -- according to Microsoft this is [Totally Expected and Not A Bug](https://developercommunity.visualstudio.com/t/access-violation-writing-location-in-output-window/1383196). They seem to be benign.

Please let me know if I can add any more information or add to the repro branch, & thanks very much for your time!

**Comment by spaderthomas** [comment]
No, it doesn't, I'm just an idiot. I didn't realize that libraries had to be compiled with ASAN in addition to the executable itself. After compiling GLFW with ASAN enabled, this works fine. Closing!

**Comment by spaderthomas** [comment]
Mistakenly closed, sorry.

**Comment by elmindreda** [comment]
I was unable to reproduce this with the above program or a similar small program.

**Comment by spaderthomas** [comment]
Hm, I forgot about this issue. I couldn't reproduce the issue on a secondary machine, and after I cleaned out my VS2022 install and reinstalled, it worked. Thank you for trying my repro!
