### ISSUE TITLE
Not defined GLFW_MOUSE_PASSTHROUGH macro.

### ISSUE THREAD

**Issue by amaoai** [glfw/glfw#2297]
my glfw version is: glfw-3.3.8.bin.WIN32

when i include **glfw.h** i want use **GLFW_MOUSE_PASSTHROUGH** macro implements mouse passthrogh feature. but when i use **GLFW_MOUSE_PASSTHROUGH** macro ide tell me this macro not defined.

i search **GLFW_MOUSE_PASSTHROUGH** macro in **glfw.h** not found.

but i see glfw website find this marco join in 3.4 version and github repository **glfw.h** have this macro. so i want know why my 3.3.8 version not this macro.

so what should i do!

**Comment by ws909** [comment]
It’s not available in 3.3.8. It’s in 3.4 (the master branch). 

There’s been 3 other issues with the same problem:
https://github.com/glfw/glfw/issues?q=GLFW_MOUSE_PASSTHROUGH

**Comment by amaoai** [comment]
> 它在 3.3.8 中不可用。它在 3.4（主分支）中。
> 
> 同一问题还有其他 3 个问题：https://github.com/glfw/glfw/issues?q=GLFW_MOUSE_PASSTHROUGH

so i need download 3.4 version or i self compile 3.4 master.

**Comment by ws909** [comment]
No, that’s 3.3.4, not 3.4. 

3.4 has not yet been released. You’ll have to compile it yourself, yes.

**Comment by amaoai** [comment]
> 不，这是 3.3.4，而不是 3.4。
> 
> 3.4 尚未发布。你必须自己编译它，是的。

thank you for your answer. i think i understand you see.
