### ISSUE TITLE
Specify thread safety requirements for GLFW memory allocator

### ISSUE THREAD

**Issue by ws909** [glfw/glfw#2298]
The GLFW documentation for the new 3.4 memory allocator that users can initialize and pass to GLFW, does not specify threading requirements. It is unclear if this allocator must support multi-threaded access, or if it will only be used on the main thread. 

- [Custom allocator guide](https://www.glfw.org/docs/3.4/intro_guide.html#init_allocator)
- [Structure reference](https://www.glfw.org/docs/3.4/structGLFWallocator.html)

Requirement: 
> May be called from any thread. Thread-safety must be ensured.

**Comment by elmindreda** [comment]
There is a thread-safety line for each callback type, but I definitely agree this is too little. Thank you for spotting this!
