### ISSUE TITLE
Is it possible to recreate the OpenGL framebuffer?

### ISSUE THREAD

**Issue by Univstar** [glfw/glfw#2301]
Sometimes it is useful to change some framebuffer properties (e.g., GLFW_SAMPLES) when the app is running. In the current version (3.3.8), it seems that all these properties must be specified before glfwCreateWindow() by glfwWindowHint().

Although I can recreate a framebuffer object by OpenGL dynamically and blit its content to the default framebuffer, recreation of the default framebuffer itself is more convenient.

Is it (or will it be) possible to do so? Thank you very much.

**Comment by ws909** [comment]
See #1677

**Comment by Univstar** [comment]
> See #977 and #1677

Thanks!
