### ISSUE TITLE
Captured cursor mode not working on Xwayland

### ISSUE THREAD

**Issue by GamesTrap** [glfw/glfw#2308]
The function `glfwSetInputMode(window, GLFW_CURSOR, GLFW_CURSOR_CAPTURED);` in the tests/cursor program doesn't work on Xwayland.

Compiled with GCC 12.2.0 using latest glfw on master branch.

OS Info:
```
OS: Kubuntu 22.10 x86_64 
Kernel: 5.19.0-35-generic 
Shell: fish 3.6.1 
Resolution: 2560x1440 
DE: Plasma 5.27.3 
WM: kwin 
Terminal: tilix 
CPU: AMD Ryzen 7 5800X (16) @ 3.800GHz 
GPU: NVIDIA GeForce RTX 2080 Rev. A 
Memory: 7531MiB / 31816MiB
```

Ignore the glitching in the video, those are coming from the typical NVIDIA Wayland capture issues.

https://user-images.githubusercontent.com/16561717/228824979-b6180c22-9567-4e87-b797-40b0bda39165.mp4

**Comment by elmindreda** [comment]
I can reproduce this but I'm not sure there is anything GLFW can do about it.

**Comment by GamesTrap** [comment]
I'm closing this as it is likely a KWin issue and not a GLFW one.

Everything works correctly when testing the captured cursor mode using rootful XWayland, so I see no problem with GLFWs X11 code.

Tested with my own application (which uses a customized version of GLFW) with the following commands:
```
Xwayland -noreset :12
DISPLAY=:12 TRAP_WM=x11 ./Tests
```

Re-tested on
```
OS: Kubuntu 23.10 x86_64 
Kernel: 6.5.7-060507-generic 
Shell: fish 3.6.1 
Resolution: 5120x1440 
DE: Plasma 5.27.9 
WM: kwin 
Terminal: tilix 
CPU: AMD Ryzen 7 5800X (16) @ 3.800GHz 
GPU: AMD ATI Radeon RX 7900 XT/7900 XTX 
Memory: 8077MiB / 31987MiB
```
