### ISSUE TITLE
Can't link GLFW; "Undefined reference to ____"

### ISSUE THREAD

**Issue by sdfdger** [glfw/glfw#2314]
OS and version: Windows 10 64-bit
Compiler version: MinGW (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 12.2.0
Release: https://github.com/glfw/glfw/releases/download/3.3.8/glfw-3.3.8.bin.WIN32.zip, `glfw-3.3.8.bin.WIN32/lib-mingw/`

I can't get this to compile. I keep getting "undefined reference" when compiling. Per the README in the .zip release, all I should need is to link `libglfw3.a` as a static library.

#### File structure:
- 	code.cpp
- 	glfw3.dll
- 	libglfw3.a
- 	libglfw3dll.a

I copied `glfw3.dll` `libglfw3.a` `libglfw3dll.a` to `x86_64-w64-mingw32\lib`.
#### code.cpp:
```
#include <GLFW/glfw3.h>
int main(){ glfwCreateWindow(800, 600, "Name", nullptr, nullptr); }
```

#### I tried:

Reading the [GLFW documentation](https://www.glfw.org/docs/latest/). Under [Building applications#With MinGW or Visual C++ on Windows](https://www.glfw.org/docs/latest/build_guide.html#build_link_win32) I found `#define`ing `GLFW_DLL` is required to link to the DLL, and `gdi32` is required for static builds, but adding those had no effect.

	>> g++ code.cpp libglfw3.a -lgdi32
	/bin/ld.exe: undefined reference to `glfwCreateWindow'
	collect2.exe: error: ld returned 1 exit status

	>> g++ code.cpp libglfw3dll.a -lgdi32	## with `#define GLFW_DLL` at the top of `code.cpp`
	/bin/ld.exe: undefined reference to `__imp_glfwCreateWindow'
	collect2.exe: error: ld returned 1 exit status

	>> g++ code.cpp -lgdi32 -lglfw3
	/bin/ld.exe: skipping incompatible /mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/lib/../lib/libglfw3.a when searching for -lglfw3
	/bin/ld.exe: skipping incompatible /mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/lib/../lib/glfw3.dll when searching for -lglfw3
	/bin/ld.exe: skipping incompatible /mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/lib/../lib\libglfw3.a when searching for -lglfw3
	/bin/ld.exe: skipping incompatible /mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/lib/libglfw3.a when searching for -lglfw3
	/bin/ld.exe: skipping incompatible /mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/lib/glfw3.dll when searching for -lglfw3
	/bin/ld.exe: skipping incompatible /mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/lib\libglfw3.a when searching for -lglfw3
	/bin/ld.exe: skipping incompatible /mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/lib/../lib/libglfw3.a when searching for -lglfw3
	/bin/ld.exe: skipping incompatible /mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/lib/../lib/glfw3.dll when searching for -lglfw3
	/bin/ld.exe: skipping incompatible /mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/lib/libglfw3.a when searching for -lglfw3
	/bin/ld.exe: skipping incompatible /mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/lib/glfw3.dll when searching for -lglfw3
	/bin/ld.exe: cannot find -lglfw3: No such file or directory
	/bin/ld.exe: skipping incompatible /mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/lib/../lib/libglfw3.a when searching for -lglfw3
	/bin/ld.exe: skipping incompatible /mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/lib/../lib/glfw3.dll when searching for -lglfw3
	/bin/ld.exe: skipping incompatible /mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/lib/libglfw3.a when searching for -lglfw3
	/bin/ld.exe: skipping incompatible /mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/lib/glfw3.dll when searching for -lglfw3
	collect2.exe: error: ld returned 1 exit status

**Comment by orbitgw** [comment]
Try to build a static lib instead. Or you must add the `#define GLFW_DLL` before your `#include`:
```cpp
#define GLFW_DLL
#include <GLFW/glfw3.h>
int main(){ glfwCreateWindow(800, 600, "Name", nullptr, nullptr); }
```

**Comment by sdfdger** [comment]
> https://github.com/glfw/glfw/issues/2314#issuecomment-1503773104



I tried both.
> ```
> g++ code.cpp libglfw3.a -lgdi32
> ```
> ```
> g++ code.cpp libglfw3dll.a -lgdi32	## with `#define GLFW_DLL` at the top of `code.cpp`
> ```
> ```
> g++ code.cpp -lgdi32 -lglfw3
> ```

**Comment by orbitgw** [comment]
Have you tried building a static lib yet？

**Comment by orbitgw** [comment]
then build it by yourself

**Comment by Lisoph** [comment]
I hardly use MinGW, but could it be possible that the lib-mingw subfolder is x86 and that lib-mingw-w64 is x86_64? Maybe just try the other one.

**Comment by sdfdger** [comment]
Fixed with `g++ code.cpp glfw3.dll -lopengl32 -lgdi32 --std=c++2a` from `glfw-3.3.8.bin.WIN64.zip/lib-mingw-w64/glfw3.dll`

Requires `GL/gl.h`, no idea how to get it or where I got it, but I put it here. [gl.h](https://github.com/glfw/glfw/files/13064327/gl.h.txt)
