### ISSUE TITLE
Gamepad not properly detected by GLFW

### ISSUE THREAD

**Issue by vanfanel** [glfw/glfw#2315]
Hi there,

I have been testing GLFW on Debian Stable and Debian Testing with Wayland (no X11 libs at all on this system: hand-built Wayland desktop using the labwc compositor).

The problem so far is that my XBOX360-compatible gamepads don't work in games built against GLFW.
I see this message on the "joysticks" test program included with GLFW:
**joystick has no gamepad mapping**
However, on the  "joysticks" test program included with GLFW, I can see levers and buttons being activated as I press them on the gamepads, so the gamepads themselves works and problem seems to be related to this  **joystick has no gamepad mapping** message.

This gamepads work on Wayland with everything works on my system: SDL2, RetroArch, etc.
It's only GLFW that fails to detect it as a gamepad.

This game for example fails to detect the gamepad via GLFW:
https://github.com/Rubberduckycooly/Sonic-Mania-Decompilation.git
It only uses the joystick if it's a gamepad, as seen here:
https://github.com/Rubberduckycooly/RSDKv5-Decompilation/blob/205404dd1caeda54add3a0c726e14270a9e36450/RSDKv5/RSDK/Input/GLFW/GLFWInputDevice.cpp#L184

Any ideas?
Maybe the gamepads are missing from the gamepad database in GLFW while they are present on SDL2? Isn't GLFW using the exact same gamepad database that SDL2 uses?
Maybe the GLFW database is outdated?

These are my gamepads according to gamepadtool:

1) "Xbox 360 Controller", 030000005e0400008e02000073060000
2) "Arduino LLC Arduino Leonardo", 03000000412300003680000001010000

As I said, both of them work perfectly well with SDL2.

**Comment by ws909** [comment]
Which version of GLFW are you using? Tried the master branch?

GLFW uses the SDL database for gamepad mapping, so this database is likely outdated in the version of GLFW you're using.

**Comment by vanfanel** [comment]
I have tried both the latest GIT code and the latest stable (3.3.8).
The gamepads I have are not present in SDL2 database either, apparently...
Maybe I should do a PR to include them. I guess that should me done in SDL2 then it would propagate to GLFW, right?

**Comment by GamesTrap** [comment]
GLFW uses the gamepad mappings file from https://github.com/gabomdq/SDL_GameControllerDB so you probably should make the PR there.

**Comment by ws909** [comment]
How come the gamepad mapping is missing in all versions of the database, yet works with SDL? Does SDL guess a mapping for it, or did you create a mapping for it yourself, a while ago, which is added to the in-memory database at runtime?

**Comment by vanfanel** [comment]
> How come the gamepad mapping is missing in all versions of the database, yet works with SDL? Does SDL guess a mapping for it, or did you create a mapping for it yourself, a while ago, which is added to the in-memory database at runtime?

Ah well, I thought that the problem is that some engines only support gamepads and not general joysticks, but in the end I don't know the same engine works in SDL2 but not using the GLFW backend...
I guess one backend of the engine supports joysticks and the other supports gamepads only.

In any case, this is not a GLFW bug, so I am closing this.
I really thank you for trying to shed some light.
