### ISSUE TITLE
Replace winmm with XInput and DirectInput

### ISSUE THREAD

**Issue by elmindreda** [glfw/glfw#232]
[Start here](http://msdn.microsoft.com/en-us/library/windows/desktop/ee417014.aspx).

**Comment by Sheado** [comment]
Hi,
Does this issue also cover the shared trigger axis problem for the Xbox controller? Or should a new issue be opened for that specifically?

**Comment by elmindreda** [comment]
@Sheado Yes, it does.

**Comment by theagentd** [comment]
Has this been implemented? We're having the shared trigger axis problem over here... >_<

**Comment by Sonickidnextgen** [comment]
Hi, I just noticed this issue myself. I've been using GLFW for quite some time, in side projects and through [Monkey](https://github.com/blitz-research/monkey). If this is still an issue, I'd be happy to add XInput support. I've already written several dynamic-linking setups, similar to [what Dolphin does](https://github.com/dolphin-emu/dolphin/blob/49ea15b9502d98f08c47429ce93827073cefdaad/Source/Core/InputCommon/ControllerInterface/XInput/XInput.cpp#L77). Only, you know, it doesn't tend to break *as much*. I'm not very familiar with DirectInput, however. That being said, with both WinMM and XInput, what would be a benefit of supporting DirectInput? Also, what would be the best way to structure a change like this? Conditional support when compiling? Support WinMM as a fall-back?

Either way, I'm quite familiar with C and very familiar with C++. [This project](https://github.com/Regal-Internet-Brothers/IOSync/blob/1b70968e1fd85f031a9a159d2195899aeee73521/IOSync/src/devices/native/winnt/Real_XInput_Wrapper.cpp#L103), and [this project](https://github.com/Regal-Internet-Brothers/xinput/blob/bdd1590eea3bb8cefdcb58854c152f7915cb51e3/native/xinput.cpp#L303) both use function-pointers, 'LoadLibrary', and 'GetProcAddress'. They also support 'XInputGetStateEx' when available, meaning the guide button (Button 10) works.

If you're not interested, I understand. I'm also not the first guy to go to, where git is concerned.

**Comment by theagentd** [comment]
Has there been any progress on this? It's really something we need to fix Xbox controllers and performance issues with the current controller polling.

**Comment by elmindreda** [comment]
@theagentd I'm about halfway done and it should make it into 3.2.

**Comment by theagentd** [comment]
Thanks for the update! Do you have a more precise ETA?

**Comment by elmindreda** [comment]
@theagentd I don't right now.

**Comment by haikarainen** [comment]
Is there anything I can do to speed this process up? I need Xbox 360 controller support for my game (which uses GLFW3 for input). I could make time for about 1 working week (40 hours) into this issue.

**Comment by ImmutableOctet** [comment]
@haikarainen What isn't working currently? The current WinMM support should be compatible with any XInput controller.

The issue here comes from the bottleneck of checking for connected controllers. There's a few benefits from being able to use the XInput API behind the scenes, but it's nothing major. Just check for controllers less often, or on a dedicated screen.

**Comment by haikarainen** [comment]
@ImmutableOctet Oh I see! Nevermind then! I just googled "GLFW3 xbox 360 controller" and was led to believe that there was no working support for it, and was redirected here... I really should've read up on it properly beforehand, sorry!

**Comment by elmindreda** [comment]
The [dekdevy](https://github.com/glfw/glfw/tree/dekdevy) branch is the (oddly named) staging branch for this. It has XInput support done. There is also a joystick connection callback, so you don't need to poll, although polling should be faster as well.
