### ISSUE TITLE
The glfw compilation failed

### ISSUE THREAD

**Issue by 0DWADE0** [glfw/glfw#2326]
Hello, why did it fail when compiling glfw? I took a screenshot of the reason for the failure
![image](https://user-images.githubusercontent.com/121961555/233787940-57478e9d-b274-4d11-9f9a-98163d6d758d.png)

**Comment by Lisoph** [comment]
Please translate the error messages to English.

**Comment by Madman10K** [comment]
This is not really a meaningful error. "错误计数超过 100; 正在停止编译" roughly translates to "Error count exceeds 100; stopping compilation". Googling for error C1003 gives [this page on MSDN](https://learn.microsoft.com/en-us/CPP/error-messages/compiler-errors-1/fatal-error-c1003?view=msvc-140) which is basically the same as the translation of the error.

There must be something else that makes so many errors appear.
