### ISSUE TITLE
no function 'glfwCreateWindowSurface'

### ISSUE THREAD

**Issue by sudokit** [glfw/glfw#2330]
```
Call to undeclared function 'glfwCreateWindowSurface'; ISO C99 and later do not support implicit function declarations
```
It still compiles, but the IDE doesn't seem to find it. I know its in glfw3.h but under ```#if defined(VK_VERSION_1_0)```
GLFW lib is up to date since i directly build it with my project.

**Comment by ByunghoonKim** [comment]
VK_VERSION_1_n, where n = 0, 1, 2, or 3 as of today, is `#define`d in vulkan_core.h. You may solve this issue with [Including the Vulkan and GLFW header files](https://www.glfw.org/docs/latest/vulkan_guide.html#vulkan_include).

**Comment by dougbinks** [comment]
In addition to the GLFW Vulkan Guide linked to above do check out the following resources:

- [GLFW Vulkan test](https://github.com/glfw/glfw/blob/master/tests/triangle-vulkan.c)
- [Vulkan Tutorial using GLFW](https://vulkan-tutorial.com/)
