### ISSUE TITLE
How to create multi window when using Vulkan?

### ISSUE THREAD

**Issue by jianweidou134** [glfw/glfw#2336]
glfwMakeContextCurrent will log error: 
GLFWAPI void glfwMakeContextCurrent(GLFWwindow* handle)
{
    _GLFWwindow* window = (_GLFWwindow*) handle;
    _GLFWwindow* previous = _glfwPlatformGetTls(&_glfw.contextSlot);

    _GLFW_REQUIRE_INIT();
   
   //When using Vulkan, using glfwWindowHint(GLFW_CLIENT_API, GLFW_NO_API);
    if (window && window->context.client == GLFW_NO_API)
    {
        _glfwInputError(GLFW_NO_WINDOW_CONTEXT,
                        "Cannot make current with a window that has no OpenGL or OpenGL ES context");
        return;
    }

    if (previous)
    {
        if (!window || window->context.source != previous->context.source)
            previous->context.makeCurrent(NULL);
    }

    if (window)
        window->context.makeCurrent(window);
}

**Comment by GamesTrap** [comment]
When using Vulkan aka `GLFW_NO_API` you must not use `glfwMakeContextCurrent()` and `glfwSwapBuffers()`.
See [Docs Windows without contexts](https://www.glfw.org/docs/latest/context_guide.html#context_less).

**Comment by dougbinks** [comment]
I recommend you look at the following resources:

- [GLFW Vulkan Guide](https://www.glfw.org/docs/latest/vulkan_guide.html)
- [GLFW Vulkan test](https://github.com/glfw/glfw/blob/master/tests/triangle-vulkan.c)
- [Vulkan Tutorial using GLFW](https://vulkan-tutorial.com/)
- [Dear ImGui Vulkan Example](https://github.com/ocornut/imgui) - see the [example_glfw_vulkan](https://github.com/ocornut/imgui/tree/master/examples/example_glfw_vulkan). If you use the Docking branch this has the ability to create multiple windows.

After you have achieved a decent understanding of how to create a Vulkan window, creating multiple windows uses the same process, and to share graphics data you simply need to use the same logical device for your rendering.
