### ISSUE TITLE
Get rid of title bar but keep resizing and rounded corners in window 11

### ISSUE THREAD

**Issue by YasTheGoat** [glfw/glfw#2344]
I'm trying to make a custom title bar. 
I used (GLFW_DECORATED, GL_FALSE) to disable it but that also removed the rounded corners and I can't resize anymore.

Is there any way to specify what I want to keep and what I want to remove?

**Comment by dougbinks** [comment]
> Is there any way to specify what I want to keep and what I want to remove?

No, currently there is no way to specify what you want to keep/remove.

If you want a resizable undecorated window you can handle your resizing via trapping mouse drag on a specific part of the window and using [glfwSetWindowSize](https://www.glfw.org/docs/latest/group__window.html#ga371911f12c74c504dd8d47d832d095cb).

For rounded corners, you could use the `GLFW_TRANSPARENT_FRAMEBUFFER` window hint to create a transparent framebuffer and then draw the transparent corners yourself.

**Comment by Khrysys** [comment]
Potentially, you could use transparent framebuffer and render the window slightly larger than the actual render framebuffer. I know this works with Vulkan via viewport and scissor, but I don’t exactly know how to do it in OpenGL, then just use the extra space so it seems like you’re actually holding the edge of the window like you normally would. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dougbinks** [comment]
Thanks for closing this. Note that in future GLFW may support resizing, you might want to watch #990.
