### ISSUE TITLE
Support 8.1 per-monitor DPI

### ISSUE THREAD

**Issue by retep998** [glfw/glfw#235]
Windows 8 and 8.1 have proper DPI settings including DPI per monitor and DPI change events.
Some information can be found here: http://msdn.microsoft.com/en-ca/magazine/dn574798.aspx
Ideally any API created to work with windows DPI would also work with Apple's retina displays.

**Comment by elmindreda** [comment]
Please see if the `per-monitor-dpi` branch works for you.

**Comment by elmindreda** [comment]
The remaining bit is HMONITOR DPI.
