### ISSUE TITLE
glfwCreateWindow should honor wShowWindow for the first window

### ISSUE THREAD

**Issue by lostmsu** [glfw/glfw#2359]
Because it does not, the universal way to launch programs hidden or minimized does not work for GLFW-based games: `ShellExecute(IntPtr.Zero, "open", "game.exe", null, null, SW_HIDE)` (also does not launch minimized regardless of shortcut properties).

## Steps
1. Build `boing` example
2. Create a desktop shortcut for it (right click on .exe -> Send To -> Desktop (create shortcut))
3. Open the shortcut properties and set "Run" to "Minimized"

## Expected
The game starts minimized

## Actual
The game opens regular window and steals focus

**Comment by elmindreda** [comment]
Agreed, at the very least it should be an option for GLFW to honor this. I've been meaning to do this but haven't had the time. Just removing the workaround in `createHelperWindow` didn't work reliably for me.

**Comment by elmindreda** [comment]
There is now the `GLFW_WIN32_SHOWDEFAULT` window hint for enabling this behavior per-window.
