### ISSUE TITLE
Remove hidden cursor mode

### ISSUE THREAD

**Issue by elmindreda** [glfw/glfw#236]
This can be achieved using `glfwSetCursor`. No need for a separate cursor mode.

**Comment by tombsar** [comment]
May I ask what changed?

**Comment by elmindreda** [comment]
Always, and sorry, I should have written it without you needing to ask.

The disabled cursor mode requires us to have an invisible cursor or the ability to hide it anyway, so offering it as hidden cursor mode is a nice convenience.
