### ISSUE TITLE
undefined：glfw.Init()

### ISSUE THREAD

**Issue by bupt-he** [glfw/glfw#2360]
system:windows
ide: vs code
go:1.20 
glfw:"github.com/go-gl/glfw/v3.3/glfw"

glfw cannot get any method. 

![image](https://github.com/glfw/glfw/assets/59814713/723f6749-3f07-4389-9df0-5e1c4ef5638e)
![image](https://github.com/glfw/glfw/assets/59814713/c66e16d1-86ed-464d-999d-6eadeb562490)

**Comment by subspecs** [comment]
Ya know, you kind of need to [import](https://github.com/go-gl/glfw) some stuff before libraries like this start working.
You know, like the library you're trying to use.

**Comment by dougbinks** [comment]
This is `go`, presumably using the [go-gl bindings](https://github.com/go-gl/glfw). Please check their Usage guide and refer any issues to that repository.
