### ISSUE TITLE
java.lang.IllegalStateException: Failed to initialize GLFW, errors: GLFW error during init: [0x10008]46246386352

### ISSUE THREAD

**Issue by tseaholtz** [glfw/glfw#2363]
I am experiencing a GLFW error in my Minecraft instance and upon googling it, it tells me to report it here so I will link the crash log below. I have asked many people using discord on how to fix this issue but it seems nobody knows what's going on. I hope you guys can be of assistance with this since it involves GLFW.

https://mclo.gs/g013ObI

I am using the following components in case it's needed. More detailed information is in the crash log...

Intel I9-13900K
NVIDIA RTX 4070TI
64GB DDR5
Windows 10

**Comment by dougbinks** [comment]
We cannot solve issue in Minecraft, please address this issue to them.
