### ISSUE TITLE
simple glfwDestroyWindow call throws GL_INVALID_OPERATION, no async, everything on main thread. (Sample included)

### ISSUE THREAD

**Issue by subspecs** [glfw/glfw#2366]
I've been writing a minor library of my own, and for some reason trying to destroy ANY window I created with **glfwDestroyWindow** and then error checking with **glGetError()** will always throw '**GL_INVALID_OPERATION**' forever.

Normally when you **glGetError()** again it should reset to **GL_NO_ERROR**, but it still keeps returning **GL_INVALID_OPERATION** basically for infinity, making it impossible to continue using this method for error checking.

Bellow I attached '**source.zip**' and the included sample code that produces this error.
All of this is running only on the main thread as you see.
I am using a fresh and latest copy of **Windows 10 Pro x64** and with the latest **NVIDIA RTX 3060 Ti drivers**.
There is **only one dedicated GPU(no iGPUs)** and there is only **ONE hooked up monitor** and **no random 'software' drivers or anything.**

NOTE: I am using the latest [release](https://github.com/glfw/glfw/releases/tag/3.3.8) build (3.3.8) for this(included in source.zip)
And I am not going to compile the entire damn source for this, have no time nor the patience.
If basic features like closing a damn window does this, then maybe it's time to update the latest releases yourselves. (Last were 07/2022)
EDIT: I also took a look at commits and issues regarding **glfwDestroyWindow**, and I've seen no changes made to it since the 2022 release.

I am using mingw64 on windows, with the build string below: (gcc actually links to the x64 version, not the 32bit, just like to keep naming clean.)
**gcc "src/glad/gl.c" "main.c" -L "lib" -lglfw3dll -O3 -o Work.exe**

Also Note: **I have no other issues with glfw, all rendering/processing I do works like it should, the only issue ever was this, and it's a problem since I can't probe for errors.**

EDIT: And before you get smart and say: well add "**glfwSetWindowShouldClose(Window, 1);**" before **glfwDestroyWindow** duh, note that it makes no difference whatsoever.

```
//#define GLFW_INCLUDE_NONE //Forces GLFW to use GLAD loader.
#include "include/glad/gl.h" //GLAD
#include "include/glfw/glfw3.h"
#include <stdio.h>

int main()
{
	if(!glfwInit()) { printf("Failed to initialize GLFW!\n"); return -1; }

	glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4); glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3); //Set the opengl API to 4.3.
	glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);

	//There is only one dedicated GPU(no iGPUs) and there is only ONE hooked up monitor.
	//No random 'software' drivers or anything. Just a standard install of the latest Windows 10 x64 and NVIDIA Drivers(MSI RTX 3060 Ti).

	const GLFWvidmode* mode = glfwGetVideoMode(glfwGetPrimaryMonitor());  //Get the current monitors video mode. (glfwGetPrimaryMonitor() is NOT null btw)

	GLFWwindow* Window = glfwCreateWindow(mode->width, mode->height, "", NULL, NULL);  //Create a new window. It opens and stays open, works like you'd expect all with draw calls/rendering etc.

	glfwMakeContextCurrent(Window);

	if(!gladLoadGL(glfwGetProcAddress)) { printf("Failed to initialize GLAD!\n"); return -1; } 

	glfwWaitEvents(); //Just in-case.

	if(glGetError() != GL_NO_ERROR) { printf("Error Code: %d\n", glGetError()); } //Receives NO ERRORS at all.

	glfwDestroyWindow(Window); //Calling glGetError() BEFORE glfwDestroyWindow at any point produces NO ERROR at all, only after destroying the window.
	glfwWaitEvents(); //Just in-case.

	int ErrorCounter = 0; 
	while(glGetError() == GL_INVALID_OPERATION) //Generates and infinite amount of 'GL_INVALID_OPERATION' errors.
	{
		printf("Error 'GL_INVALID_OPERATION' Count: %d\n", ErrorCounter++);
	}

	printf("Done!\n");
	return 0;
}
```
[source.zip](https://github.com/glfw/glfw/files/12051677/source.zip)

**Comment by subspecs** [comment]
UPDATE: I've built the latest source, both the lib and the dll and the same things been happening.

**Comment by subspecs** [comment]
For future reference for anyone looking for this:
<ins>**glGetError()**</ins> doesn't work well with GLFW.
So they added their own method <ins>**glfwGetError()**</ins>, this one works like intended.
Was hard to find, while looking through the internet and developing my own [library](https://github.com/subspecs/CocaineNET), I haven't come across a single example or even a mention of their own implementation of **glfwGetError** until I saw it myself in the documentation. Weird but there you go.

**Comment by ws909** [comment]
@subspecs It is my understanding that [glfwGetError](https://www.glfw.org/docs/latest/group__init.html#ga944986b4ec0b928d488141f92982aa18) only reports errors with GLFW itself, and not OpenGL. The documentation for that function makes no mention of OpenGL, and this function is to be used regardless of which rendering API is used.

**Comment by ws909** [comment]
> Pretty sure lots of ppl destroy their windows rather than closing/terminating the entire app.

Just make sure not to make any OpenGL calls unless there’s an active, valid OpenGL context. So just omit all OpenGL related calls unless the thread has a current OpenGL contex.

> Also [glfwGetError](https://www.glfw.org/docs/latest/group__init.html#ga944986b4ec0b928d488141f92982aa18) doesn't throw any errors even IF there is no valid context, like it should be.

`glfwGetError` isn’t meant for OpenGL-related errors. It’s not a part of OpenGL, and neither is it a substitute for `glGetError`. It only reports errors with GLFW, or your usage of GLFW, not anything with OpenGL. 

> Otherwise, how do you know that the window actually closed gracefully?

Use `glfwGetError` before closing the window, to reset the last error, then call it again after destroying the window. Either that, or set a GLFW error callback, and you’ll be notified each time an error occurs. 

Don’t make any OpenGL related calls for a GLFW window’s context after destroying that window. If you need to use OpenGL without rendering to the screen, you still need an active context, which is only acquired by creating a window (keep it hidden). That’s because the design of OpenGL is not very friendly. 

`glGetError` is **only** for OpenGL; it doesn’t report any errors outside the responsibility of OpenGL. Window handling is not the responsibility of OpenGL. There’s a clear separation between OpenGL errors and GLFW errors.
