### ISSUE TITLE
GLFW_LIB_NAME overrides CMAKE_DEBUG_POSTFIX

### ISSUE THREAD

**Issue by erincatto** [glfw/glfw#2373]
https://github.com/glfw/glfw/blob/3eaf1255b29fdf5c2895856c7be7d7185ef2b241/src/CMakeLists.txt#L127

I found that using Visual Studio in cmake mode, it has CMAKE_DEBUG_POSTFIX defaulting to "d". But GLFW_LIB_NAME overrides this. This leads to a failed link.

I can provide more details if needed.

**Comment by elmindreda** [comment]
I will need more details for this.

I wasn't been able to reproduce VS adding a debug postfix on its own in either CMake or folder mode. Adding one myself seems to work in both the JSON file UI and on the command-line.

**Comment by erincatto** [comment]
This problem seems to have gone away. Maybe fixed on the MS side.
