### ISSUE TITLE
[HARDWARE-caused issue] Weird behaviour when multiple arrow keys pressed

### ISSUE THREAD

**Issue by RotschkeJAR** [glfw/glfw#2374]
_Short history:_
I try to program my own game engine in C++, that uses OpenGL for rendering, including GLAD and GLFW. So far the game itself has a cube, that can be moved by pressing the arrow keys. I tried to trick my game for exposing bugs by pressing multiple arrow keys. My cube moved weirdly when pressing, holding, releasing keys in a specific order. I found out, that the bug's cause is inside GLFW.

_Scenario:_
When I press and hold left and right at the same time, my cube doesn't move as expected, so do up and down. I keep holding left and right, now I press up and the cube doesn't move upwards as expected, but if I press down, he goes down. And the most confusing part of this is, that if I hold down, then press and hold up and release down, he continues going down.
The same scenario happens when holding up and down and playing with left and right. In this case right only works and left doesn't.

I already tracked down the cause of the bug inside my game engine and it led me to GLFW. I implemented the error callback, but it wasn't triggered. I tested my theory in a simple code:
```c++
#include <GLFW/glfw3.h>
#include <iostream>

bool keys[4];

void errCallback(int err, const char* des) {
	std::cerr << "GLFW " << err << ": " << des << std::endl;
}

void keyCallback(GLFWwindow* window, int key, int scan, int action, int mod) {
	if (key == GLFW_KEY_LEFT)
		key = 0;
	else if (key == GLFW_KEY_RIGHT)
		key = 1;
	else if (key == GLFW_KEY_DOWN)
		key = 2;
	else if (key == GLFW_KEY_UP)
		key = 3;
	if (action == GLFW_PRESS)
		keys[key] = true;
	else if (action == GLFW_RELEASE)
		keys[key] = false;
}

int main() {
	if (!glfwInit())
		return 1;
	glfwSetErrorCallback(errCallback);
	glfwDefaultWindowHints();
	GLFWwindow* win = glfwCreateWindow(1000, 700, "GLFW", NULL, NULL);
	if (!win)
		return 2;
	glfwMakeContextCurrent(win);
	glfwSetKeyCallback(win, keyCallback);
	std::cout << glfwGetVersionString() << "\n";
	while (!glfwWindowShouldClose(win)) {
		glfwPollEvents();
		std::cout << keys[0] << " : " << keys[1] << " \\ " << keys[2] << " : " << keys[3] << std::endl;
	}
	glfwDestroyWindow(win);
	glfwSetErrorCallback(NULL);
	glfwTerminate();
	return 0;
}
```

_Technical information:_
**OS:** Ubuntu 22.04.1 LTS
**Compiler:** g++ 11.3.0
**GLFW version:** 3.3.6 X11 GLX EGL OSMesa clock_gettime evdev shared
(_g++ uses GLFW 3.3.6 instead of 3.3.8 because I installed it by using Ubuntu's package installer APT. I tried to update it with APT and by compiling from source and installing, however it keeps stuck with 3.3.6_)
**Errors:** /
**Architecture:** x86_64 (64-bit)
**Processor:** AMD Ryzen 5 3600 6-Core Processor
**GPU:** NVIDIA Corporation - GP106 [GeForce GTX 1060 6GB]

**Compile command:** g++ *.cpp -lglfw

**Comment by combolek** [comment]
FWIW, I tried to reproduce the issue with your test program and could not. The program behaves like you would expect. All four arrow keys register press and release independently of each other, no matter how many are pressed simultaneously.
This was on Fedora 38 with GLFW 3.3.8

**Comment by gracicot** [comment]
Try this page: https://drakeirving.github.io/MultiKeyDisplay/

If the issue happen here too, the problem might just be your keyboard itself due to ghosting.
