### ISSUE TITLE
Pressing opposing d-pad buttons at the same time causes assertion failure at debug mode

### ISSUE THREAD

**Issue by BigETI** [glfw/glfw#2383]
The issue lies within pressing opposing d-pad buttons at the same time, which causes assertion failure at debug mode.

See [_glfwInputJoystickHat](https://github.com/glfw/glfw/blob/3eaf1255b29fdf5c2895856c7be7d7185ef2b241/src/input.c#L468)

It is entirely possible to press all d-pad buttons at the same time.

This has been tested with a Logitech F510 on Windows 10.

**Comment by elmindreda** [comment]
Thank you for the bug report! This should now be fixed with 80d45cdfd7d17fd45a3bf323fb02604e71e3ea21, which was included in the 3.3.9 release.
