### ISSUE TITLE
 glfw is not work in mac Parallels Desktop  v18 virtual machine！

### ISSUE THREAD

**Issue by qq1053831109** [glfw/glfw#2406]
glfw is not work in mac Parallels Desktop  v18 virtual machine！

**Comment by ws909** [comment]
You’ll need to add more information, and clarify what «doesn’t work» means. Does it run? Does it crash? Certain components failing?

**Comment by dougbinks** [comment]
Could you provide more information. See our [Bug Reporting Guide](https://github.com/glfw/glfw/blob/master/docs/CONTRIBUTING.md#reporting-a-bug) for how to make a good bug report.

**Comment by gezhaoyou** [comment]
I have same error, error message:
```shell
[65544] WGL: Failed to retrieve pixel format attributes:
```
My glfw version is 3.3.9 and parallels is 19

**Comment by gezhaoyou** [comment]
> I have same error, error message:
> 
> ```shell
> [65544] WGL: Failed to retrieve pixel format attributes:
> ```
> 
> My glfw version is 3.3.9 and parallels version is 19.0

I test glfw 3.3.8 work well for me

**Comment by dougbinks** [comment]
This looks like the same issue as #2467
