### ISSUE TITLE
glfwWaitEventsTimeout doesn't process QS_SENDMESSAGE on Windows

### ISSUE THREAD

**Issue by BloCamLimb** [glfw/glfw#2408]
#### Description
https://github.com/glfw/glfw/blob/3eaf1255b29fdf5c2895856c7be7d7185ef2b241/src/win32_window.c#L2122-L2127  `MsgWaitForMultipleObjects` doesn't include `QS_SENDMESSAGE` flag. This will result in some messages not being processed.

I first encountered this issue when I use [tiny file dialogs](https://sourceforge.net/projects/tinyfiledialogs/). To reproduce:
1. Create a GLFW window on main thread.
2. Use `glfwWaitEventsTimeout` in main thread loop.
3. Open a `tinyfd` dialog from non-main thread (a background thread).

You will see `glfwWaitEventsTimeout` won't return and process input events for the dialog window, so the dialog is not responding. It only returns after `timeout` seconds has expired. Of course, `glfwWaitEventsTimeout` works for input events for the GLFW window.

#### My workaround
1. Only use `glfwWaitEvents` and `glfwPollEvents` in main thread loop, they can process input events for the background dialog window.
2. Use `tinyfd` only on main thread. In this case, the dialog window is responding, but it will block application's main thread.

#### Possible solution
Replace `QS_ALLEVENTS` with `QS_ALLINPUT`.

**Comment by elmindreda** [comment]
This should be fixed now with 509f4131bec5303b04e30617a123e7ce18a95798. Thank you for the bug report and fix!
