### ISSUE TITLE
glfwCreateWindowSurface not defined for vulkan_raii.hpp

### ISSUE THREAD

**Issue by Omasyo** [glfw/glfw#2410]
OS and version: Debian GNU/Linux 12 (bookworm) - Gnome Version 43.6
Compiler version: gcc (Debian 12.2.0-14) 12.2.0
Release or commit: 3.3.8-1
Build log: 
> [main] Building folder: XTVulcan build-debug
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /home/omaka/Documents/GitHub/XTVulcan/build --config Debug --target build-debug -j 6 --
[build] [ 25%] Building CXX object CMakeFiles/application.dir/src/application.cpp.o
[build] /home/omaka/Documents/GitHub/XTVulcan/src/application.cpp: In member function ‘void Application::createSurface()’:
[build] /home/omaka/Documents/GitHub/XTVulcan/src/application.cpp:320:62: error: ‘surfaceHandle’ was not declared in this scope
[build]   320 |     if (glfwCreateWindowSurface(*instance, window, nullptr, &surfaceHandle) != VK_SUCCESS)
[build]       |                                                              ^~~~~~~~~~~~~
[build] /home/omaka/Documents/GitHub/XTVulcan/src/application.cpp:320:9: error: ‘glfwCreateWindowSurface’ was not declared in this scope; did you mean ‘glfwCreateWindow’?
[build]   320 |     if (glfwCreateWindowSurface(*instance, window, nullptr, &surfaceHandle) != VK_SUCCESS)
[build]       |         ^~~~~~~~~~~~~~~~~~~~~~~
[build]       |         glfwCreateWindow
[build] gmake[3]: *** [CMakeFiles/application.dir/build.make:76: CMakeFiles/application.dir/src/application.cpp.o] Error 1
[build] gmake[2]: *** [CMakeFiles/Makefile2:111: CMakeFiles/application.dir/all] Error 2
[build] gmake[1]: *** [CMakeFiles/Makefile2:92: CMakeFiles/build-debug.dir/rule] Error 2
[build] gmake: *** [Makefile:124: build-debug] Error 2
[proc] The command: /usr/bin/cmake --build /home/omaka/Documents/GitHub/XTVulcan/build --config Debug --target build-debug -j 6 -- exited with code: 2
[driver] Build completed: 00:00:06.896
[build] Build finished with exit code 2

It seems like the error is cause because the compiler thinks VK_VERSION_1_0 is not defined in glfw3.h
> #if defined(VK_VERSION_1_0)

But I can confirm it is defined when vulkan_raii.hpp is included. I don't know what else could cause this.

The issue can be fixed by manually including vulkan_core.h in the source file. But this shouldn't be necessary since vulkan_core.h is included in the vulkan_raii.hpp.

**Comment by dougbinks** [comment]
Are you including the `vulkan_raii.hpp` header before the GLFW one?

**Comment by Omasyo** [comment]
My header file was included last in my source file. What a silly mistake, I had even forgotten about it completely.

Thanks.

**Comment by dougbinks** [comment]
Header & library order issues are a pain. Glad you've resolved it!
