### ISSUE TITLE
_glfwRegisterWindowClassWin32 calls LoadImageW incorrectly

### ISSUE THREAD

**Issue by fgenolini** [glfw/glfw#2415]
In win32_window.c 
`GLFWbool _glfwRegisterWindowClassWin32(void)`
line 1442

the loading of user-provided icon will not work because
```
wc.hIcon = LoadImageW(GetModuleHandleW(NULL),
                                         L"GLFW_ICON", IMAGE_ICON,
                                         0, 0, LR_DEFAULTSIZE | LR_SHARED);

```
will always return NULL.

LoadImageW will only accept
`MAKEINTRESOURCE(GLFW_ICON)`

**Comment by elmindreda** [comment]
That is [not correct](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-loadimagew). The function accepts both ordinals ("int resources") and names. If it isn't working for you then your resource file or one of its header files may be defining `GLFW_ICON` to some integer value.

**Comment by fgenolini** [comment]
Thanks, I have read the manual and experimented, and the documented behaviour does not work for me.  I have a workaround in my own code.  Thanks for looking into this

**Comment by elmindreda** [comment]
Do the GLFW examples get the orange window icon on your machine? They use this method.

**Comment by fgenolini** [comment]
you are correct, thanks for pointing this out, I can now see what I have done wrong, sorry for the incorrect bug report
