### ISSUE TITLE
[LWJGL] GLFW_PLATFORM_ERROR error, Not able to see the window in macOs, M1 Chip, Ventura, Version 13.4 

### ISSUE THREAD

**Issue by rjritik1137** [glfw/glfw#2432]
I am facing this issue in one Kotlin project.
When I ran this project first time, I saw some window coming (Not completely sure about this), after that the window just gets stuck. I have attached a video for reference.

> [LWJGL] GLFW_PLATFORM_ERROR error
> 	Description : Cocoa: Failed to find service port for display
> 	Stacktrace  :
> 		org.lwjgl.glfw.GLFW.glfwInit(GLFW.java:830)
> 		openGL.main.HelloWorld.init(HelloWorld.kt:24)
> 		openGL.main.HelloWorld.<init>(HelloWorld.kt:15)
> 		openGL.main.MainClass$Companion.main(MainClass.kt:8)
> 		openGL.main.MainClass.main(MainClass.kt)

build.gradle
		
`plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.9.0'
    id ('application')
}

group = 'org.example'

version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}
project.ext.lwjglVersion = "3.2.3"
project.ext.lwjglNatives = "natives-macos"
project.ext.jomlVersion = "1.10.0"
project.ext.jomlPrimVersion = "1.10.0"

dependencies {
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    implementation platform("org.lwjgl:lwjgl-bom:$lwjglVersion")
    implementation "org.lwjgl:lwjgl"
    implementation "org.lwjgl:lwjgl-glfw"
    implementation 'org.lwjgl:lwjgl-opengl'

    runtimeOnly "org.lwjgl:lwjgl::${lwjglNatives}"
    runtimeOnly "org.lwjgl:lwjgl-glfw::${lwjglNatives}"
    runtimeOnly "org.lwjgl:lwjgl-opengl::${lwjglNatives}"
}

test {
    useJUnitPlatform()
}

tasks.register('runMain', JavaExec) {

    mainClass = 'openGL.main.MainClass' // Adjust the fully qualified name of your main class
    classpath = sourceSets.main.runtimeClasspath
}

kotlin {
    jvmToolchain(8)
}

application {
    mainClassName = 'openGL.main.MainClass'
}`

`
package openGL.main

import org.lwjgl.glfw.Callbacks
import org.lwjgl.glfw.GLFW
import org.lwjgl.glfw.GLFWErrorCallback
import org.lwjgl.glfw.GLFWVidMode
import org.lwjgl.opengl.GL
import org.lwjgl.opengl.GL11.*
import org.lwjgl.system.MemoryUtil

class HelloWorld {
    private var window: Long = 0

    init {
        init()
        run()
    }

    private fun init() {
        // Set up GLFW error callback
        GLFWErrorCallback.createPrint(System.err).set()

        println("Initializing GLFW...")
        if (!GLFW.glfwInit()) {
            throw IllegalStateException("Unable to initialize GLFW")
        }
        println("GLFW initialized successfully.")

        // Configure GLFW
        GLFW.glfwDefaultWindowHints()
        GLFW.glfwWindowHint(GLFW.GLFW_VISIBLE, GLFW.GLFW_FALSE)
        GLFW.glfwWindowHint(GLFW.GLFW_RESIZABLE, GLFW.GLFW_TRUE)

        // Create the GLFW window
        println("Creating GLFW window...")
        window = GLFW.glfwCreateWindow(800, 600, "Hello World!", MemoryUtil.NULL, MemoryUtil.NULL)
        if (window == MemoryUtil.NULL) {
            throw RuntimeException("Failed to create the GLFW window")
        }
        println("GLFW window created successfully.")

        // Explicitly specify the primary monitor
        val monitor = GLFW.glfwGetPrimaryMonitor() ?: throw RuntimeException("Failed to get primary monitor")
        val vidMode = GLFW.glfwGetVideoMode(monitor) ?: throw RuntimeException("Failed to get video mode")
        GLFW.glfwSetWindowPos(window, (vidMode.width() - 800) / 2, (vidMode.height() - 600) / 2)

        // Make the OpenGL context current
        GLFW.glfwMakeContextCurrent(window)
        GL.createCapabilities()

        // Show the window
        GLFW.glfwShowWindow(window)
    }

    private fun run() {
        glClearColor(0.0f, 0.0f, 0.0f, 0.0f)

        // Main loop
        while (!GLFW.glfwWindowShouldClose(window)) {
            glClear(GL_COLOR_BUFFER_BIT)

            // Your rendering code goes here

            GLFW.glfwSwapBuffers(window)
            GLFW.glfwPollEvents()
        }

        // Cleanup
        Callbacks.glfwFreeCallbacks(window)
        GLFW.glfwDestroyWindow(window)
        GLFW.glfwTerminate()
    }

    companion object {
        @JvmStatic
        fun main(args: Array<String>) {
            HelloWorld()
        }
    }
}

`

Issue Video - https://drive.google.com/file/d/10kVHAF0m_bkdqi2dcHkSeqiLGXKuOm-m/view?usp=sharing

**Comment by dougbinks** [comment]
The error `Cocoa: Failed to find service port for display` is the same as #1791 which is fixed in https://github.com/glfw/glfw/commit/955fbd9d265fa95adf9cb94896eb9a516aa50420

This fix was released in GLFW version 3.3.8: https://github.com/glfw/glfw/releases/tag/3.3.8

If you could update to that version that should resolve this particular issue. I will close this issue given that it should not be possible to get the same error.
