### ISSUE TITLE
Compile glfw with emscripten

### ISSUE THREAD

**Issue by Patricksd56** [glfw/glfw#2440]
Im having bit of trouble finding following functions from entire repository and Im missing couple of them to compile them to wasm.

wasm-ld: error: /data/data/com.termux/files/usr/tmp/emscripten_temp_c89nvaly/test_0.o: undefined symbol: glfwSetErrorCallback
wasm-ld: error: /data/data/com.termux/files/usr/tmp/emscripten_temp_c89nvaly/test_0.o: undefined symbol: glfwInit
wasm-ld: error: /data/data/com.termux/files/usr/tmp/emscripten_temp_c89nvaly/test_0.o: undefined symbol: glfwWindowHint
wasm-ld: error: /data/data/com.termux/files/usr/tmp/emscripten_temp_c89nvaly/test_0.o: undefined symbol: glfwWindowHint
wasm-ld: error: /data/data/com.termux/files/usr/tmp/emscripten_temp_c89nvaly/test_0.o: undefined symbol: glfwWindowHint
wasm-ld: error: /data/data/com.termux/files/usr/tmp/emscripten_temp_c89nvaly/test_0.o: undefined symbol: glfwWindowHint
wasm-ld: error: /data/data/com.termux/files/usr/tmp/emscripten_temp_c89nvaly/test_0.o: undefined symbol: glfwCreateWindow
wasm-ld: error: /data/data/com.termux/files/usr/tmp/emscripten_temp_c89nvaly/test_0.o: undefined symbol: glfwWindowHint
wasm-ld: error: /data/data/com.termux/files/usr/tmp/emscripten_temp_c89nvaly/test_0.o: undefined symbol: glfwCreateWindow
wasm-ld: error: /data/data/com.termux/files/usr/tmp/emscripten_temp_c89nvaly/test_0.o: undefined symbol: glfwTerminate
wasm-ld: error: /data/data/com.termux/files/usr/tmp/emscripten_temp_c89nvaly/test_0.o: undefined symbol: glfwSetKeyCallback
wasm-ld: error: /data/data/com.termux/files/usr/tmp/emscripten_temp_c89nvaly/test_0.o: undefined symbol: glfwMakeContextCurrent
wasm-ld: error: /data/data/com.termux/files/usr/tmp/emscripten_temp_c89nvaly/test_0.o: undefined symbol: glfwSwapInterval
wasm-ld: error: /data/data/com.termux/files/usr/tmp/emscripten_temp_c89nvaly/test_0.o: undefined symbol: glfwWindowShouldClose
wasm-ld: error: /data/data/com.termux/files/usr/tmp/emscripten_temp_c89nvaly/test_0.o: undefined symbol: glfwGetFramebufferSize
wasm-ld: error: /data/data/com.termux/files/usr/tmp/emscripten_temp_c89nvaly/test_0.o: undefined symbol: glfwGetTime
wasm-ld: error: /data/data/com.termux/files/usr/tmp/emscripten_temp_c89nvaly/test_0.o: undefined symbol: glfwSwapBuffers
wasm-ld: error: /data/data/com.termux/files/usr/tmp/emscripten_temp_c89nvaly/test_0.o: undefined symbol: glfwPollEvents
wasm-ld: error: /data/data/com.termux/files/usr/tmp/emscripten_temp_c89nvaly/test_0.o: undefined symbol: glfwDestroyWindow
wasm-ld: error: /data/data/com.termux/files/usr/tmp/emscripten_temp_c89nvaly/test_0.o: undefined symbol: glfwTerminate
wasm-ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)

**Comment by Patricksd56** [comment]
Found it.

**Comment by gracicot** [comment]
@Patricksd56 can you write what did you found, just to help future readers if this issue?
