### ISSUE TITLE
GLFW_FLOATING not working

### ISSUE THREAD

**Issue by riedingermatthieu** [glfw/glfw#2441]
Hi,
I'm trying to setup a window as "always-on-top" with a wayland backend with the GLFW_FLOATING window hint set to GLFW_TRUE.
It does not seem to work on my side at runtime, the window does not stay on top.
Is this supported with a wayland backend ?

**Comment by elmindreda** [comment]
Hi! No, floating is currently not supported by any branch of GLFW on Wayland.
