### ISSUE TITLE
Switching a window to fullscreen on the current monitor?

### ISSUE THREAD

**Issue by VioletGiraffe** [glfw/glfw#2454]
Hi! I love GLFW, it's a very convenient and feature-rich library that works great on different systems. There is one thing I didn't find how to do, though: switching to fullscreen on the currently selected monitor. This is because a non-fullscreen window does not have a monitor associated with it, so how can I find out which monitor a window is currently on? Surely, every OS provides this info. 

It would not be below me to implement this for Windows myself, if you gave me access to the window `HWND` and monitor's `HMONITOR` handles (so that I could trace from `HMONITOR` monitor back to the matching GLFW monitor struct) via something like a `void* nativeHandle(GLFWindow*)` function (and it could return null on platforms where it's not possible or too difficult to implement).

If there is actually the way to do this - please point me to it, and sorry for missing it (but it doesn't look like there is one).

**Comment by kayoscode** [comment]
```
static int mini(int x, int y) {
    return x < y ? x : y;
}

static int maxi(int x, int y) {
    return x > y ? x : y;
}

static GLFWmonitor* getBestMonitor(GLFWwindow *window) {
    int nmonitors, i;
    int wx, wy, ww, wh;
    int mx, my, mw, mh;
    int overlap, bestoverlap;
    GLFWmonitor *bestmonitor;
    GLFWmonitor **monitors;
    const GLFWvidmode *mode;

    bestoverlap = 0;
    bestmonitor = NULL;

    glfwGetWindowPos(window, &wx, &wy);
    glfwGetWindowSize(window, &ww, &wh);
    monitors = glfwGetMonitors(&nmonitors);

    for (i = 0; i < nmonitors; i++) {
        mode = glfwGetVideoMode(monitors[i]);
        glfwGetMonitorPos(monitors[i], &mx, &my);
        mw = mode->width;
        mh = mode->height;

        overlap =
            maxi(0, mini(wx + ww, mx + mw) - maxi(wx, mx)) *
            maxi(0, mini(wy + wh, my + mh) - maxi(wy, my));

        if (bestoverlap < overlap) {
            bestoverlap = overlap;
            bestmonitor = monitors[i];
        }
    }

    return bestmonitor;
}
```
I believe this is what you’re looking for. This finds the monitor the window overlaps with most.

**Comment by VioletGiraffe** [comment]
Hmm, I see what you did there, didn't know position is global and not local to the current monitor. Thanks a lot.
