### ISSUE TITLE
glfwCreateWindow reportedly can produce GLFW_NO_WINDOW_CONTEXT but isn't documented to

### ISSUE THREAD

**Issue by dmitshur** [glfw/glfw#2456]
Hello, I'm following up on a downstream bug report at https://github.com/go-gl/glfw/issues/389.

It seemingly uncovered that it's possible for the `glfwCreateWindow` function to report the `GLFW_NO_WINDOW_CONTEXT` error code. However, the docs of [`glfwCreateWindow`](https://www.glfw.org/docs/latest/group__window.html#ga3555a418df92ad53f917597fe2f64aeb) currently don't include `GLFW_NO_WINDOW_CONTEXT` as one of the possible errors.

Looking at the code briefly (at latest head commit, b4c3ef9d0fdf46845f3e81e5d989dab06e71e6c1), there is indeed at least one path for that to happen (on any platform):

glfwCreateWindow
⤷
_glfwIsValidContextConfig
⤷
_glfwInputError(GLFW_NO_WINDOW_CONTEXT, NULL)

Perhaps the current implementation is working as intended and the bug is in the documentation, or vice versa.

Thanks.

**Comment by dmitshur** [comment]
Thanks for the fix!

**Comment by elmindreda** [comment]
Thank you for the bug report!
