### ISSUE TITLE
Feature Request: branch that points to latest stable released version.

### ISSUE THREAD

**Issue by dmitshur** [glfw/glfw#246]
Would it make sense to have a branch named `latest` or similar, that simply points to the latest stable released version of glfw?

That would make the act of compiling glfw from scratch more friendly towards a script that doesn't need to be changed every time there's a new version. Related to https://github.com/sourcegraph/sourcegraph.com/issues/29#issuecomment-36067717.

For instance, the following current step:

```
git clone https://github.com/glfw/glfw.git
cd glfw
git checkout 3.0.4
```

Could be replaced with:

```
git clone https://github.com/glfw/glfw.git
cd glfw
git checkout latest
```

Some projects opt to use the `master` branch for this purpose, and have bleeding development happen in other branches (like `dev`). But that would be a slightly more disruptive change.

**Comment by elmindreda** [comment]
So here is my proposal: `latest` behaves as before, I get more serious about using branches even for minor-but-cross-platform changes and `master` contains stuff ready for the next release.

**Comment by elmindreda** [comment]
@shurcooL Does that sound sane?

**Comment by shurcooL** [comment]
That sounds great.

It doesn't sound different from before, aside from you merging branches into `master` only after it's more thoroughly reviewed and ready, right?

**Comment by elmindreda** [comment]
Yep, pretty much.
