### ISSUE TITLE
Please merge this PR [# 2130] to add IME support for each platform

### ISSUE THREAD

**Issue by larks-x** [glfw/glfw#2473]
Please merge this PR [#2130](https://github.com/glfw/glfw/pull/2130). IME support is very useful to us. thanks

**Comment by elmindreda** [comment]
IME support is next up once Wayland support is stable. See my update in the PR. It hasn't been forgotten, there's just been very limited time available for a long while.

There's no need to make another issue about an existing one. We get notified equally about new issues and updates in existing ones.
