### ISSUE TITLE
How to get 1:1 ratio of window size to frame buffer size?

### ISSUE THREAD

**Issue by chaoticbob** [glfw/glfw#2478]
This is more of a question than an issue and may be related to #2079.

I'm trying to debug a render macOS and I need the window and the framebuffer to be 1:1 so there's not any scaling done to the pixels. I've tried using:
```
glfwWindowHint(GLFW_COCOA_RETINA_FRAMEBUFFER, GLFW_FALSE);
```

But this seems to have no effect. Setting this value to GLFW_FALSE or GLFW_TRUE seems to produce screenshots of the exact same size. Both of which are 2784x1720. The window size passed into `glfwCreateWindow` is 1280x720.

Afterwards:
`glfwGetWindowSize` returns 1280x720
`glfwGetFramebufferSize` returns 2560x1440

I've scoured the docs and various posts but I can't seem to find anything that's helped so far. Is there something else that I'm missing? 

Using commit 00e86d4b733103a23278fe53ce58a0d14dd47d32 on Apple Silicon MacBookPro with macOS 14.2.1.

**Comment by elmindreda** [comment]
macOS screenshots will use the full resolution of the display, regardless of what scaling is done of window contents. This is true also for fullscreen windows.

Does the size retrieved from `glfwGetFramebufferSize` stay the same with `GLFW_COCOA_RETINA_FRAMEBUFFER` set to both true and false on your machine? I was unable to reproduce that on an M1 machine running macOS 14.3.1.

**Comment by chaoticbob** [comment]
Thanks for the reply. After posting I found out via conversation with someone more familiar with macOS that the behavior is as you described. 

> Does the size retrieved from glfwGetFramebufferSize stay the same with GLFW_COCOA_RETINA_FRAMEBUFFER set to both true and false on your machine? I was unable to reproduce that on an M1 machine running macOS 14.3.1.

IIRC, on my machine the value had no effect. 

Thanks for looking into it, I was able to sort out what I was trying to do by other means.

**Comment by giogadi** [comment]
I ran into this same issue. I believe the bug is in GLFW, as I mentioned in this comment: https://github.com/glfw/glfw/issues/1800#issuecomment-2691494965

**Comment by alexanderk23** [comment]
I have also encountered this issue (M1/M4, Sequoia 15.4.1, `glfwGetFramebufferSize` returns the same size regardless of the `GLFW_COCOA_RETINA_FRAMEBUFFER` value) and can confirm that the proposed fix works in my case.
