### ISSUE TITLE
Error when mouse is over window corner on macOS

### ISSUE THREAD

**Issue by paulocoutinhox** [glfw/glfw#2485]
Hi,

Im getting an error when mouse is over window corner on macOS.

The app simply crash.

The stack is:

![image](https://github.com/glfw/glfw/assets/395096/7d8e329d-f8a4-4003-95fd-f2cf313d7a68)

Move the mouse to:

<img width="752" alt="Screenshot 2024-02-13 at 06 03 29" src="https://github.com/glfw/glfw/assets/395096/1d4c5422-40c5-41f4-be07-079b779e4e39">

Code to test:

```
#include <GLFW/glfw3.h>

int main() {
    if (!glfwInit()) {
        return -1;
    }

    GLFWwindow* window = glfwCreateWindow(640, 480, "Test GLFW", nullptr, nullptr);
    if (!window) {
        glfwTerminate();
        return -1;
    }

    glfwMakeContextCurrent(window);

    while (!glfwWindowShouldClose(window)) {
        glfwPollEvents();
        glfwSwapBuffers(window);
    }

    glfwDestroyWindow(window);
    glfwTerminate();
    return 0;
}
```

Video:

https://github.com/glfw/glfw/assets/395096/38adf707-5d06-4e96-bc23-5765e7078402

**Comment by elmindreda** [comment]
Unable to reproduce with current HEAD on macOS 14.3.1.  Do you have a full text version of the call stack?  What version of macOS are you running?  Apple Silicon or Intel?

**Comment by paulocoutinhox** [comment]
I tested from head and it stop happen, thanks.

**Comment by elmindreda** [comment]
Glad to hear it, thank you for the update!
