### ISSUE TITLE
Cannot link release binaries with Xcode 13 and earlier

### ISSUE THREAD

**Issue by Finxx1** [glfw/glfw#2488]
The current released macOS binaries found on https://glfw.org/download.html are compiled with msgsend selector stubs enabled, which causes many unresolvable symbol errors when compiling with Xcode versions before 14. [This](https://stackoverflow.com/a/74108260) StackOverflow post seems to detail a potential solution to this.

**Comment by elmindreda** [comment]
Unable to reproduce with Xcode 12.4 on an Intel Mac using either the Intel or Universal binaries from the 3.3.9 package.

**Comment by elmindreda** [comment]
What steps do I need to take to reproduce this?

**Comment by Finxx1** [comment]
I have set up an MRE here. https://github.com/Finxx1/glfw-mre
As it is, it fails
![image](https://github.com/glfw/glfw/assets/46616745/47331085-09ae-4f3b-98e1-0aafaa7a8164)
This is what Xcode tells me.
I am running Xcode 13.4.1 on a 2020 M1 MacBook air. This might only affect the ARM part of the universal binaries? Not sure.

**Comment by elmindreda** [comment]
This appears to be a thing. I will add this flag manually to Mac builds for the upcoming releases and look into a better solution later.

**Comment by elmindreda** [comment]
Please see if the binaries from the 3.3.10 release work better for you on pre-14 Xcode.

**Comment by Finxx1** [comment]
The build succeeds with 3.3.10. Thanks for fixing this.
