### ISSUE TITLE
Memory corruption on joystick disconnect during iconify (FALSE ALARM, my bad)

### ISSUE THREAD

**Issue by philipguin** [glfw/glfw#2489]
# FALSE ALARM, my bad

I was getting a disconnection callback immediately upon polling the joystick, which was setting my values to zero/null by design, but unexpectedly during my poll handling logic.

I will say that firing these callbacks during polling feels like an error prone pattern, but seeing as it's separate from the main GLFW event loop anyway, perhaps it's a necessary evil. If it's not documented, then it definitely should be!

I removed a lot of unnecessary information below, but kept the core description of the problem I was experiencing.

## Details

Repro steps:

1. Have joystick connected and window up.
2. Iconify (i.e. click on minimize button).
3. Disconnect the joystick.
4. Poll Joystick while still iconified.

Result: memory related to joystick polling in my application is set to 0 during a call to any of `glfwGetJoystickAxes`, `glfwGetJoystickButtons`, or `glfwGetJoystickButtons`. I believe `glfwGetGamepadState` may also be affected.

Un-focusing instead of iconify-ing does _not_ appear to repro.

Setting/unsetting window refresh callback makes no difference.

Error callback evidently not reporting anything.

**Comment by elmindreda** [comment]
Thank you for the update! I have a fix in mind for this for the release after this one.
