### ISSUE TITLE
X11 re-implementation

### ISSUE THREAD

**Issue by kanryu** [glfw/glfw#2490]
Hi,

I'm currently trying to implement IME support for a Go-based GUI toolkit called Fyne, and it's mostly completed, but it's difficult to improve the level of completion.

The problem is simply that glfw's implementation is immature, and in particular the X11 layer is not very complete.
Among them, the structure of X11 event processing is far different from other popular implementations, and the existence of XIM is not taken into consideration at all.

Why is it that the clear-node team has been approaching you for years and still can't merge?
https://github.com/glfw/glfw/pull/2130

I would like them to perform a destructive reimplementation and provide highly complete event processing by referring to existing implementations such as GTK+ and Wine.

**Comment by elmindreda** [comment]
I haven't had enough time to take on large new features for a while now, for reasons. What time I have had has gone towards keeping existing features and platforms running, especially now that distributions are moving to Wayland.

IME is first up among the various large PRs waiting to be merged. The release after 3.4, which is imminent, will be mostly about that.  I'm sorry it's taken so long.

GLFW does talk to XIM already, but only in the most basic way possible.

Improvements to X11 event processing are very welcome.
