### ISSUE TITLE
CMake: `glfw/include` dirictory propagates not as SYSTEM include

### ISSUE THREAD

**Issue by Challanger524** [glfw/glfw#2512]
Program build results in next include paths:
`cl.exe   /TP  -IC:\<projpath>\src -IC:\<projpath>\deps\glfw\include -external:IC:\<projpath>\deps ...`
`-IC:\<projpath>\deps\glfw\include` - not a **system include** (`-I` while must be `-external:I`)

Consider using `target_include_directories(glfw SYSTEM PUBLIC **/include)`
https://github.com/glfw/glfw/blob/bf945f1213728a98f7647380616f9cff9f6b3611/src/CMakeLists.txt#L132-L134
Add **`SYSTEM`**: `glfw PUBLIC` -> `glfw SYSTEM PUBLIC`:
https://stackoverflow.com/a/61797712/11753532

**Comment by Challanger524** [comment]
The one more caveat is a need to conditionalize `SYSTEM` apply, so internal _tests_ and/or _examples_ builds will keep produce warnings

**Comment by Challanger524** [comment]
Looks like more of a **CMake**-wide issue coz every library is being setup this way.
Workaround is to add **same** or **root* include like:
``` cmake
target_include_directories(${PROJECT_NAME} SYSTEM PRIVATE
  "${CMAKE_SOURCE_DIR}/deps" # all upper dirs will be treated as SYSTEM, even if opposite stated explicitly (with: -I)
)
```

**Comment by gracicot** [comment]
If you install glfw in a particular directory and add the prefix to your other project, you'll get system headers by default for any library. CMake solved this but only for `find_package`.
