### ISSUE TITLE
GLFW Window is too big if wayland monitor is scaled

### ISSUE THREAD

**Issue by enesaltinkaya** [glfw/glfw#2527]
I'm using Hyprland and Gnome desktop managers on Linux.
With a 4k monitor at 3840x2160 resolution.
Monitor scaling is set to 2x on desktop manager settings.

When I try to create a window at 1920x1080 resolution it covers the whole screen as if it is 3840x2160.
If i disable scaling on desktop manager options, it works as expected.

```c
#define GLAD_GL_IMPLEMENTATION
#include "glad.h"
#include "GLFW/glfw3.h"

int main(void) {
  glfwInit();
  GLFWwindow* window = glfwCreateWindow(1920, 1080, "Ales", NULL, NULL);
  glfwMakeContextCurrent(window);
  gladLoadGL(glfwGetProcAddress);
  glClearColor(1, 0, 0, 1);
  int width, height;
  while (!glfwWindowShouldClose(window)) {
    glfwPollEvents();
    glfwGetFramebufferSize(window, &width, &height);
    glViewport(0, 0, width, height);
    glClear(GL_COLOR_BUFFER_BIT);
    glfwSwapBuffers(window);
  }
}
```
OS: Arch Linux x86_64
Kernel: 6.8.4-arch1-1
Resolution: 3840x2160
DE: Hyprland
GPU: NVIDIA GeForce GTX 1080 Ti 
Driver version: 550.67

> pacman -Q | grep glfw
> glfw 3.4-2

https://github.com/glfw/glfw/assets/8594559/4f497bc3-d78b-4a6d-b254-8b4273a4bad5

**Comment by enesaltinkaya** [comment]
Hi, yes libdecor is installed.
> [enes@redmi ~] $ pacman -Q libdecor 
libdecor 0.2.2 -

I have kde-plasma installed right now besides hyprland, so i tried that, result was the same.

wayland-info hyprland, https://pastebin.com/rsVZNqvZ
wayland-info kde-plasma, https://pastebin.com/06M8vqWF


Also i printed out values from _glfwGetFramebufferSize_ and _glfwGetWindowSize_ like this;
Same output for kde-plasma and hyprland.
```c 
int windowWidth, windowHeight;
int frameBufferWidth, frameBufferHeight;
while (!glfwWindowShouldClose(window)) {
  ... 
  glfwGetFramebufferSize(window, &frameBufferWidth, &frameBufferHeight);
  glfwGetWindowSize(window, &windowWidth, &windowHeight);
  printf("fb:%d %d window:%d %d\n", frameBufferWidth, frameBufferHeight, windowWidth, windowHeight);
  ...
}
```

> fb : 3840 2160 window : 1920 1080 
> fb : 3840 2160 window : 1920 1080 
> fb : 3840 2160 window : 1920 1080 
> fb : 3840 2160 window : 1920 1080 
> fb : 3840 2160 window : 1920 1080 
> fb : 3840 2160 window : 1920 1080 
> fb : 3840 2160 window : 1920 1080

And this output is from _hyprctl clients_ when running on hyprland;
It says "size: 1920,1080" but it covers the whole screen :S

```
Window 57227fbf74a0 -> Ales:
	mapped: 1
	hidden: 0
	at: 0,0
	size: 1920,1080
	workspace: 3 (3)
	floating: 1
	monitor: 0
	class: 
	title: Ales
	initialClass: 
	initialTitle: Ales
	pid: 80209
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
	focusHistoryID: 2
```

**Comment by elmindreda** [comment]
> Also i printed out values from _glfwGetFramebufferSize_ and _glfwGetWindowSize_ like this; Same output for kde-plasma and hyprland.
> 
> > fb : 3840 2160 window : 1920 1080
> > fb : 3840 2160 window : 1920 1080
> > fb : 3840 2160 window : 1920 1080
> > fb : 3840 2160 window : 1920 1080
> > fb : 3840 2160 window : 1920 1080
> > fb : 3840 2160 window : 1920 1080
> > fb : 3840 2160 window : 1920 1080
> 
> And this output is from _hyprctl clients_ when running on hyprland; It says "size: 1920,1080" but it covers the whole screen :S
> 
> ```
> Window 57227fbf74a0 -> Ales:
> 	size: 1920,1080
> ```

That does look like it's a bug in Hyprland. What does GLFW say the window content scale is?

**Comment by enesaltinkaya** [comment]
```c
  float windowScaleX, windowScaleY;
  float monitorScaleX, monitorScaleY;

  while (!glfwWindowShouldClose(window)) {
    ...
    glfwGetMonitorContentScale(glfwGetPrimaryMonitor(), &monitorScaleX, &monitorScaleY);
    glfwGetWindowContentScale(window, &windowScaleX, &windowScaleY);
    printf("monitorScale:%f %f windowScale:%f %f\n", monitorScaleX, monitorScaleY, windowScaleX, windowScaleY);
    ...
  }
```

> monitorScale:2.000000 2.000000 windowScale:2.000000 2.000000
monitorScale:2.000000 2.000000 windowScale:2.000000 2.000000
monitorScale:2.000000 2.000000 windowScale:2.000000 2.000000
monitorScale:2.000000 2.000000 windowScale:2.000000 2.000000
monitorScale:2.000000 2.000000 windowScale:2.000000 2.000000

This looks correct.

**Comment by elmindreda** [comment]
Thank you! This looks to me very much like a compositor bug, in which case there's nothing GLFW can do or even any way to find out it's happening.

**Comment by enesaltinkaya** [comment]
Alright. For now I'll compile glfw with only X11 support and work with Xwayland. Thanks.

**Comment by VagueLobster** [comment]
> Alright. For now I'll compile glfw with only X11 support and work with Xwayland. Thanks.

There _IS_ a better fix than sticking with X11... If you're using `glfwSetWindowSizeCallback` don't!
Instead use `glfwSetFramebufferSizeCallback` and just put the same things from `glfwSetWindowSizeCallback` into it
and of course set everything up to use native wayland, including glfw!

Also on another note regarding speed, with X11 i can get around 3900-4000 fps on the gpu (converted from my gpu's frame time)
In Windows i can get around 4400-4600 fps on the gpu in both debug and release.
But when using native Wayland through glfw i can get 11000 fps on the gpu in debug, but in release i get 21000 fps...
For some reason glfw's implementation for native Wayland is soooo much better than both their X11 impl and even Win32 impl 👍 

EDIT: I forgot to mention that all of these fps results are while my editor is maximized, and my program runs in x86_64 👍

**Comment by JustComputer** [comment]
(Sorry for my poor English)
If you would like to keep the window size fixed, this might work.

Add a func like this:
```
void keepWindowSizeFixed(GLFWwindow* window, int bufferWidth, int bufferHeight){
    int w=100,h=300;
    glfwGetWindowSize(window, &w, &h);
    if(w!=bufferWidth){
        w=float(w);
        h=float(h);
        glfwSetWindowSize(window, w*w/bufferWidth, h*h/bufferHeight);
    }
}
```

and use this before your main loop:
```
int w,h;
glfwGetFramebufferSize(window,&w,&h);
keepWindowSizeFixed(window,w,h);
```
