### ISSUE TITLE
Can't link glfw application on mac

### ISSUE THREAD

**Issue by oleksandrh324110** [glfw/glfw#2545]
command: 
```bash
clang src/main.o -o ./bin/main.exe lib/glfw/src/libglfw3.a lib/glad/src/gl.o -lm -framework Cocoa -framework OpenGL -framework IOKit -framework CoreVideo
```

error:
```bash
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_CAMetalLayer", referenced from:
       in libglfw3.a[21](cocoa_window.m.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [link] Error 1
```

main.c is a basic example code from glfw.org

I build glfw with this makefile target:
```makefile
lib: 
    cd lib/glfw && cmake . && make
```

versions:
- macos -> 14.4.1
- cmake -> 3.29.2
- make -> 3.81
- glfw -> 3.4

**Comment by dougbinks** [comment]
Have you tried cloning the source from git and then using CMake to build GLFW with tests and examples, or alternatively using the [GLFW-CMake-starter](https://github.com/juliettef/GLFW-CMake-starter) and following the instructions in the readme to build?

**Comment by oleksandrh324110** [comment]
Yes. I added the glfw repo as a submodule and successfully compiled it with `cd lib/glfw && cmake . && make`
<img width="630" alt="Screenshot 2024-04-26 at 14 31 39" src="https://github.com/glfw/glfw/assets/58668303/e6c1ebbd-22ec-4ab5-b36c-e740a62d7bbb">

But the problems starts while linking

Also i tried to build some examples and got the same linking error:
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_CAMetalLayer", referenced from:
       in libglfw3.a[21](cocoa_window.m.o)
ld: symbol(s) not found for architecture arm64
```

**Comment by oleksandrh324110** [comment]
It's something about cocoa_window.m file in glfw

**Comment by dougbinks** [comment]
If you have successfully compiled GLFW with cmake and make then you should also have compiled and linked the tests and examples, so the problem is not with linking to GLFW in general but how you are linking to it. So you should see there are test executables built in the `tests` folder, and examples in the `examples` folder.

As mentioned you could [check the documentation on how to compile and link to GLFW on MacOS](https://www.glfw.org/docs/latest/build_guide.html#build_link_osx), or use the [GLFW-CMake-starter](https://github.com/juliettef/GLFW-CMake-starter). If either of these fail then let us know here along with the details.

**Comment by oleksandrh324110** [comment]
Finally fixed it.
As i understood, since the last macos update, developers now also need to link `-framework QuartzCore` on linking stage,
so we can say that for today, it's not enough to link only these `-framework Cocoa -framework OpenGL -framework IOKit`

**Comment by oleksandrh324110** [comment]
Also note that, i guess, ALL latest versions of macos (for example: BigSur, Monterey, Ventura) need this additional framework while linking (since i downgraded macos from Sonoma to BigSur and the problem still was there:( )

Would be pretty lovely if you update information about this at https://www.glfw.org/docs/latest/build_guide.html#build_link_osx

**Comment by oleksandrh324110** [comment]
I see there's some guy who [already fixed this](https://github.com/glfw/glfw/commit/97892c60373f2e3c12e3f119d3788ad38a18c170) in documentation coming with sources but not on the website (since last website update was on Fri Feb 23 2024)
