### ISSUE TITLE
GLFW Wayland Support

### ISSUE THREAD

**Issue by SaifOwleN** [glfw/glfw#2558]
For some reason glfw is not using wayland. It's not even giving wayland support

```cpp
#include <GL/gl.h>
#include <GLFW/glfw3.h>
#include <fmt/core.h>

int main() {
  GLFWwindow *window;
  if (!glfwInit())
    return -1;
  glfwWindowHint(GLFW_SAMPLES, 4);
  glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
  glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 6);
  glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
  glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);

  if (glfwPlatformSupported(GLFW_PLATFORM_WAYLAND)) {
    glfwInitHint(GLFW_PLATFORM, GLFW_PLATFORM_WAYLAND);
  } else {
    fmt::println("No Wayland Support");
  }

  window = glfwCreateWindow(800, 800, "GLFW", NULL, NULL);

  if (window == NULL) {
    glfwTerminate();
    return 0;
  }

  glfwMakeContextCurrent(window);

  while (!glfwWindowShouldClose(window)) {
    glfwSwapBuffers(window);
    glfwPollEvents();
  }

  glfwDestroyWindow(window);

  glfwTerminate();
  return 0;
}
```
It returns ``` No Wayland Support ``` And a window appears but it uses x11 and pitch black.

**Comment by dougbinks** [comment]
Are you certain that Wayland is supported?

> a window appears but it uses x11 and pitch black.

If you want another colour try setting `glClearColor` and then use `glClear` prior to drawing and swapping buffers..

**Comment by SaifOwleN** [comment]
That's my question. 
Why is it not supported. The wayland support function returns false.

**Comment by dougbinks** [comment]
Sorry, I meant are you certain that Wayland is supported **by your system**?

**Comment by dougbinks** [comment]
Hi, 

It looks like your GLFW library was compiled without Wayland support. The `_GLFW_WAYLAND` option [needs to be defined at compile time](https://www.glfw.org/docs/latest/compile_guide.html#compile_manual).

I also just noticed you are calling the init hint prior to calling init. This should be called prior to the init as follows:

```C
  if (glfwPlatformSupported(GLFW_PLATFORM_WAYLAND)) {
    glfwInitHint(GLFW_PLATFORM, GLFW_PLATFORM_WAYLAND);
  } else {
    fmt::println("No Wayland Support");
  }
  if (!glfwInit())
    return -1;
```

**Comment by SaifOwleN** [comment]
> Sorry, I meant are you certain that Wayland is supported **by your system**?

Yes, am sure its supported i already use a Wayland wm.

Also i use vcpkg for the library management and here is the cmake command
`cmake -DGLFW_USE_WAYLAND=ON ..`

and for the hints i fixed it but it still doesn't work

**Comment by dougbinks** [comment]
What version of GLFW have you got? According to vcpkg it should be 3.4 which is the latest.

`GLFW_USE_WAYLAND` is now deprecated:
https://github.com/glfw/glfw/blob/master/CMakeLists.txt#L30-L33

**Comment by SaifOwleN** [comment]
Thank you it worked

**Comment by dougbinks** [comment]
Excellent, then I shall mark this as closed.
