### ISSUE TITLE
GLFW window crashes after copying/cutting data to clipboard on Hyprland Wayland compositor

### ISSUE THREAD

**Issue by FearlessOne07** [glfw/glfw#2562]
### Summary
When trying to open a GLFW window, it opens properly initially but  after copying/cutting anything (text, files etc) subsequent attmpets result in the window crashing with this error:

```
listener function for opcode 1 of wl_data_offer is NULL
```

### Steps to reproduce

1. Set up a simple GLFW project on Hyprland

This is the one I used 

``` cpp
#include <GLFW/glfw3.h>
#include <iostream>

int main() {

  // Initialize GLFW
  if (!glfwInit()) {
    std::cerr << "Failed to initialize GLFW" << std::endl;
    return -1;
  }

  // Create a windowed mode window and its OpenGL context
  GLFWwindow *window = glfwCreateWindow(800, 600, "OpenGL", NULL, NULL);
  if (!window) {
    std::cerr << "Failed to create GLFW window" << std::endl;
    glfwTerminate();
    return -1;
  }

  // Make the window's context current
  glfwMakeContextCurrent(window);

  // Render loop
  while (!glfwWindowShouldClose(window)) {

    glfwSwapBuffers(window);
    // Poll for and process events
    glfwPollEvents();
  }

  // Clean up and exit
  glfwDestroyWindow(window);
  glfwTerminate();
  return 0;
}

```
2. Copy/cut anything
3. Try to run the code and watch the window fail to open

### Additional Info

I tried this with sdl2 and didn't get this issue. I also tried this in Gnome on wayland and did not get the issue.

Killing all wl-clipboard related processes solves the issue until something is copied to the clipboard

### Environment

- Arch Linux
- GLFW built from the latest commit
- Mesa 24.0.7 OpenGL Drivers 
- Hyprland Wayland Compisitor
- wl-clipboard as clipboard manager

Here Is a video demonstrating the problem

https://github.com/glfw/glfw/assets/140640715/cc532ae9-0800-4e2e-b8fe-d21ea9390e51

**Comment by xTrayambak** [comment]
The same thing happens to me on Linux and Hyprland, except any GLFW app will immediately crash without needing to read the clipboard state.

# Environment
- NixOS 24.11
- GLFW 3.4
- Mesa 24.0.7
- Hyprland built from the latest commit
- wl-clipboard as clipboard manager

Compiling without Wayland support works fine as well.

**Comment by Ty026** [comment]
It seems to be an issue with WM. The latest Hypyland has fixed it:
https://github.com/hyprwm/Hyprland/issues/6444
not sure about the situation with NixOS.

**Comment by NamitBhutani** [comment]
> The same thing happens to me on Linux and Hyprland, except any GLFW app will immediately crash without needing to read the clipboard state.
> 
> # Environment
> * NixOS 24.11
> * GLFW 3.4
> * Mesa 24.0.7
> * Hyprland built from the latest commit
> * wl-clipboard as clipboard manager
> 
> Compiling without Wayland support works fine as well.

Did you manage to fix it? I am also facing the exact same issue on NixOS 24.11, the window opens for a split second and closes and I get the error - `listener function for opcode 1 of wl_data_offer is NULL
Aborted (core dumped)`

**Comment by xTrayambak** [comment]
> > The same thing happens to me on Linux and Hyprland, except any GLFW app will immediately crash without needing to read the clipboard state.
> > 
> > # Environment
> > * NixOS 24.11
> > * GLFW 3.4
> > * Mesa 24.0.7
> > * Hyprland built from the latest commit
> > * wl-clipboard as clipboard manager
> > 
> > Compiling without Wayland support works fine as well.
> 
> Did you manage to fix it? I am also facing the exact same issue on NixOS 24.11, the window opens for a split second and closes and I get the error - `listener function for opcode 1 of wl_data_offer is NULL
> Aborted (core dumped)`

No, I just forced GLFW to use the X11 backend for now.
