### ISSUE TITLE
IS this a bug:  sharing.c example, should resize of window independent to each other. 

### ISSUE THREAD

**Issue by ziyuanbaby** [glfw/glfw#2563]
### **IS this a bug:  sharing.c example, should resize of window independent to each other.** 
I made a small change to sharing.c example, let viewPort change by call back. call back function is simple as following:

```
            void reshape(GLFWwindow *window, int width, int height)
            {
                glViewport(0, 0, (GLint)width, (GLint)height);
            }
```
call back is set by:
```
            glfwSetFramebufferSizeCallback(windows[0], reshape);
            glfwSetFramebufferSizeCallback(windows[1], reshape);
```

```
and draw function i comment out the glviewport and glfwGetFramebufferSize, as following
for (i = 0; i < 2; i++)
        {
            //  int width, height;
            mat4x4 mvp;

            //  glfwGetFramebufferSize(windows[i], &width, &height);
            glfwMakeContextCurrent(windows[i]);

            //   glViewport(0, 0, width, height);

            mat4x4_ortho(mvp, 0.f, 1.f, 0.f, 1.f, 0.f, 1.f);
            glUniformMatrix4fv(mvp_location, 1, GL_FALSE, (const GLfloat *)mvp);
            glUniform3fv(color_location, 1, colors[i]);
            glDrawArrays(GL_TRIANGLE_FAN, 0, 4);

            glfwSwapBuffers(windows[i]);
        }
```

however, when i resize the first window. it will not work as expected. with comprison, the origial sharing.c works as expected.

![image](https://github.com/glfw/glfw/assets/35264651/8988d7d7-8fdf-4518-a173-263e8cc1b369)

**Comment by GamesTrap** [comment]
You probably need to call `glfwMakeContextCurrent(window);` inside your `reshape()` function before you call make the `glViewport()`.

**Comment by dougbinks** [comment]
GLFW cannot change the context itself, since user code could have the context active on another thread.

**Comment by dougbinks** [comment]
I am closing this issue as it looks like it is resolved, if not please re-open with further information about the issue.
