### ISSUE TITLE
Ubuntu can't run glfwGetX11Display is null

### ISSUE THREAD

**Issue by wuxianggujun** [glfw/glfw#2564]
## Platform
**Window11**
**Clion Nova**
**Vmware + Ubuntu 22.04LTS**

ubuntu installation library script

```shell
sudo apt install libgl1-mesa-dev
sudo apt-get install libglfw3-dev
sudo apt-get install pkg-config
sudo apt install libwayland-dev libxkbcommon-dev xorg-dev
sudo apt-get install libx11-dev libxext-dev libxtst-dev libxrender-dev libxmu-dev libxmuu-dev

```

This is my project GLFW+BGFX used together, and it works normally on the window platform, but when I compile and run it in Ubuntu, I get the following error.
```
Glfw Error: 65550 : X11: Platform not initialized
Glfw Error: 65550 : X11: Platform not initialized
/tmp/tmp.fqo2sWa37B/dependencies/bgfx.cmake/bgfx/src/bgfx.cpp (3558): BGFX Init...
/tmp/tmp.fqo2sWa37B/dependencies/bgfx.cmake/bgfx/src/bgfx.cpp (3565): BGFX Version 1.127.8709 (commit: 2ad67a4dfd721c266d2286ce5ad19a64e1373531)
/tmp/tmp.fqo2sWa37B/dependencies/bgfx.cmake/bgfx/src/bgfx.cpp (1898): BGFX WARN bgfx platform data like window handle or backbuffer is not set, creating headless device.
/tmp/tmp.fqo2sWa37B/dependencies/bgfx.cmake/bgfx/src/bgfx.cpp (1904): BGFX Initializing headless mode, resolution of non-existing backbuffer can't be larger than 0x0!
/tmp/tmp.fqo2sWa37B/dependencies/bgfx.cmake/bgfx/src/bgfx.cpp (3576): BGFX Init failed.
```
I found that glfwGetX11Display in the code keeps being null and can't get it
```
#if BX_PLATFORM_LINUX || BX_PLATFORM_BSD
        bgfxInit.platformData.ndt = glfwGetX11Display();
         bgfxInit.platformData.nwh = (void*)(uintptr_t)glfwGetX11Window(window);
#elif BX_PLATFORM_OSX
        bgfxInit.platformData.nwh = glfwGetCocoaWindow(window);
#elif BX_PLATFORM_WINDOWS
        bgfxInit.platformData.nwh = glfwGetWin32Window(window);
#endif
```
It's just empty.,But I've ubuntu installed these libraries according to the documentation tutorial.,There's no problem with compiling these libraries.,It's just not working.。

The following code is what I searched for on the Internet, and it works normally in ubuntu, but I added a sentence auto x11= glfwGetX11Display(); Found to be null all the time, and I'm not sure why.
```
// settings
const unsigned int SCR_WIDTH = 800;
const unsigned int SCR_HEIGHT = 600;

int main(int argc, char *argv[]) {
    //初始化GLFW
    glfwInit();
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
    //创建一个窗口对象
    GLFWwindow *window = glfwCreateWindow(SCR_WIDTH, SCR_HEIGHT, "GLFW 3.3.1", NULL, NULL);
    if (window == nullptr) {
        std::cout << "Failed to create GLFW window" << std::endl;
        glfwTerminate();
        return -1;
    }
    //通知GLFW将我们窗口的上下文设置为当前线程的主上下文
    glfwMakeContextCurrent(window);
    //对窗口注册一个回调函数,每当窗口改变大小，GLFW会调用这个函数并填充相应的参数供你处理
    glfwSetFramebufferSizeCallback(window, framebuffer_size_callback);

    auto x11= glfwGetX11Display();

    //渲染循环
    while(!glfwWindowShouldClose(window)) {
        // 输入
        processInput(window);
        // 渲染指令
        glClearColor(0.2f, 0.3f, 0.3f, 1.0f);
        glClear(GL_COLOR_BUFFER_BIT);
        // 检查并调用事件，交换缓冲
        glfwSwapBuffers(window);//检查触发事件
        glfwPollEvents();    //交换颜色缓冲
    }
    //释放/删除之前的分配的所有资源
    glfwTerminate();
    return EXIT_SUCCESS;
}

//输入控制，检查用户是否按下了返回键(Esc)
void processInput(GLFWwindow *window) {
    if(glfwGetKey(window, GLFW_KEY_ESCAPE) == GLFW_PRESS) {
        glfwSetWindowShouldClose(window, true);
    }
}

// 当用户改变窗口的大小的时候，视口也应该被调整
void framebuffer_size_callback(GLFWwindow *window, int width, int height) {
    // 注意：对于视网膜(Retina)显示屏，width和height都会明显比原输入值更高一点。
    glViewport(0, 0, width, height);
}
```
ubuntu22.04 under vmware
![image](https://github.com/glfw/glfw/assets/39469560/25b0d78a-980e-488c-8517-bd8fa93e0428)
In CLion Nova it is indeed null directly
![image](https://github.com/glfw/glfw/assets/39469560/17c97526-c0d5-471b-9e10-d2cd4c27523d)

Then the last link is my project, everyone is welcome to help me see if there is any problem
https://github.com/wuxianggujun/Tina/tree/dev

**Comment by dougbinks** [comment]
GLFW now has runtime platform selection, and it looks like it has defaulted to Wayland on your system so X11 is not initialized. See the documentation on runtime platform selection:

https://www.glfw.org/docs/latest/intro_guide.html#platform

So you could either set an init hint to use X11, or use the [Wayland native access functions](https://www.glfw.org/docs/latest/group__native.html) when the Wayland platform has been selected.

**Comment by wuxianggujun** [comment]
> GLFW now has runtime platform selection, and it looks like it has defaulted to Wayland on your system so X11 is not initialized. See the documentation on runtime platform selection:
> 
> https://www.glfw.org/docs/latest/intro_guide.html#platform
> 
> So you could either set an init hint to use X11, or use the [Wayland native access functions](https://www.glfw.org/docs/latest/group__native.html) when the Wayland platform has been selected.

I set up `glfwInitHint(GLFW_PLATFORM, GLFW_PLATFORM_X11)` as per the docs; However, the error is the same, and the output is still the same as exit code 139

**Comment by wuxianggujun** [comment]
> GLFW now has runtime platform selection, and it looks like it has defaulted to Wayland on your system so X11 is not initialized. See the documentation on runtime platform selection:
> 
> https://www.glfw.org/docs/latest/intro_guide.html#platform
> 
> So you could either set an init hint to use X11, or use the [Wayland native access functions](https://www.glfw.org/docs/latest/group__native.html) when the Wayland platform has been selected.

First, specify glfwInitHint(GLFW_PLATFORM, GLFW_PLATFORM_X11); is valid, secondly, using clion remote ubuntu build is the build exe can not run, I create the build folder here after the build has been able to run normally, thank you!
