### ISSUE TITLE
Question - Mouse passthrough and transparent window - click changing focus?

### ISSUE THREAD

**Issue by J7mbo** [glfw/glfw#2572]
Hello,

I have a question about using mouse passthrough from 3.4 along with a transparent frame buffer.

I'm using some go bindings, btw, so if this isn't a problem here then I'll create an issue there.

When using a floating, transparent window with passthrough set to true, I can see that my non-clicking mouse events (hovering, moving) do trigger in the underlying window whilst my floating window is in focus.

However, when clicking, the focus switches to the window underneath, and does not stay on the floating glfw window. 

So my question is - is this expected behavior, or is the intended behavior that the floating window still remains floating and just passes the mouse click through to the window underneath without focussing on that underneath window?

**Comment by dougbinks** [comment]
This is expected behaviour. Focus is set by the OS so there may be OS level differences however.

**Comment by J7mbo** [comment]
Thanks for your response @dougbinks!

Is there any way to programmatically change this? I would like to be able to click through but still maintain focus on the floating window.

**Comment by dougbinks** [comment]
> Is there any way to programmatically change this? I would like to be able to click through but still maintain focus on the floating window.

There is not a simple way to avoid the focus changing at the moment - as I mentioned focus on mouse click is an OS level feature. There is likely a way to work around this on all platforms but it would probably take a significant amount of effort to get working.

However it is possible to [use a focus callback](https://www.glfw.org/docs/3.3/window_guide.html#window_focus) to detect loss of focus, and then set the window as focused. In most situations this would be unwanted as users typically do not like having an application steal focus, but in some situations it could be a workable solution.

**Comment by J7mbo** [comment]
Thanks Doug, I'll mark this as closed and something that isn't planned. Cheers!
