### ISSUE TITLE
How to use osmesa?

### ISSUE THREAD

**Issue by songtianhui** [glfw/glfw#2594]
I want to run an application glfw. The case is that the machine does not have display, so I try to use osmesa backend and I am struggling with it.

Here is my simple original code:
```c
int main(int argc, char *argv[])
{
    GLFWwindow* window;
    int width, height;

    printf("%s\n", glfwGetVersionString());
    if( !glfwInit() )
    {
        fprintf( stderr, "Failed to initialize GLFW\n" );
        exit( EXIT_FAILURE );
    }

    glfwWindowHint(GLFW_DEPTH_BITS, 16);
    glfwWindowHint(GLFW_TRANSPARENT_FRAMEBUFFER, GLFW_TRUE);

    window = glfwCreateWindow( 300, 300, "Gears", NULL, NULL );
    if (!window)
    {
        fprintf( stderr, "Failed to open GLFW window\n" );
        glfwTerminate();
        exit( EXIT_FAILURE );
    }

    // do something
}
```
It works well, with X11.

Now I am trying to replace it with osmesa, so I add these lines:
```
    glfwWindowHint(GLFW_DEPTH_BITS, 16);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    glfwWindowHint(GLFW_TRANSPARENT_FRAMEBUFFER, GLFW_TRUE);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);  
    glfwWindowHint(GLFW_CONTEXT_CREATION_API, GLFW_OSMESA_CONTEXT_API);
```
When running the program, it crashes with "Failed to initialize GLFW". And with error_callback there is error: [65543]: OSMesa: Failed to create context.
What is the correct approach to switch the normal mode to osmesa?
Thanks!

**Comment by dougbinks** [comment]
I've been handling this issue on the [GLFW forum}(https://discourse.glfw.org/t/how-to-use-osmesa-backend/2697), answers there.

I've added a documentation tag as ideally we'd document how to use OSMesa headless.

**Comment by songtianhui** [comment]
Forgive my repeated issues. It has been solved perfectly.
Appreciate.

**Comment by xunshengliuyin** [comment]
@songtianhui hellow，  I want to know how you solved it. Are you using OSMesa? Can you tell me how to solve it? I am working on a glfw container rendering. Thank you very much.

**Comment by xunshengliuyin** [comment]
@songtianhui Or can you give me a very simple example of glfw and OSMesa and tell me how you implemented it? Thanks
