### ISSUE TITLE
Can a user event transmission interface be implemented？

### ISSUE THREAD

**Issue by irscript** [glfw/glfw#2602]
SDL3 now has an interface for pushing user event. Can our GLFW be further developed and implemented?

**Comment by dougbinks** [comment]
I personally do not think this is within the remit of GLFW, which is a much more lightweight layer than SDL3. Additionally, GLFW does not have an event interface but instead uses a number of specific callbacks.

User events can be implemented in a platform agnostic fashion fairly simply, and there are likely a number of libraries for this.
