### ISSUE TITLE
Small cursor with fractional scaling wayland

### ISSUE THREAD

**Issue by ninja-** [glfw/glfw#2629]
The cursor inside the game is smaller than the system cursor, it's size should be multiplied by fractional-scale instead.

GLFW version is 3fa2360720eeba1964df3c0ecf4b5df8648a8e52 (3.4)

edit: I just realized how ancient of a version this is in PrismLauncher flatpak build...

**Comment by dougbinks** [comment]
As I understand it from #2630 this is an issue with Minecraft.

Please direct issues with Minecraft to their support. If they confirm the issue is with GLFW they can then file an issue here.
