### ISSUE TITLE
Wayland surface is exactly 37 pixels taller than set

### ISSUE THREAD

**Issue by diniamo** [glfw/glfw#2643]
I'm trying to use Raylib with the GLFW backend, and I've traced the issue back to GLFW (the SDL backend works properly). As I mentioned in the title, the window created is exactly 37 pixels bigger in height than what I'd set (I currently subtract 37 from the actual height to make it work). Disabling window decorations doesn't make a difference.

**Comment by dougbinks** [comment]
Could you post details of the system you are using (OS, along with windowing system and compositor if on Linux).

Have you tried any of the GLFW tests on their own without Raylib to see if they also suffer from this issue?

**Comment by diniamo** [comment]
- OS: NixOS
- Windowing ~~system~~ protocol: Wayland
- Compositor: Hyprland

How exactly do I build the examples?

**Comment by dougbinks** [comment]
The easiest way to build the examples and tests is to clone this repository and use [CMake to generate the build files and then build as per the documentation instructions](https://www.glfw.org/docs/latest/compile_guide.html#compile_compile) with the default options. You could also [download the latest release source code](https://github.com/glfw/glfw/releases) and do the same.

The `test/window.c` test is a good test to try, this should create a 600x660 sized window and also report the size in it's GUI.

**Comment by diniamo** [comment]
Running the clipboard example, it seems like the window size is correct.

**Comment by diniamo** [comment]
I'm pretty sure I've tried that before, but I'll try again I guess.

**Comment by diniamo** [comment]
Still happens. Note that I use raylib-rs. I'll try and reproduce it in C.

**Comment by diniamo** [comment]
Alright, this is getting weirder by the second.

With
```c
#include <raylib.h>

int main(void) {
    InitWindow(200, 200, "raylibtest");
    SetTargetFPS(15);

    while (!WindowShouldClose()) {
        BeginDrawing();
        EndDrawing();
    }
}
```
the window size is 207, 237 (it should be 200, 200).

Although I'm starting to suspect that this *is* actually something in Raylib.

**Comment by GamesTrap** [comment]
On KDE Wayland the clipboard program has a manually measured surface size of 200x200 + decoration size of 200x28.

Using glfwGetWindowSize, glfwGetFramebufferSize and glfwGetWindowFrameSize i get the following:
```
Framebuffer size: 200x200
Window size: 200x200
Window frame size: Left 0 Top 0 Bottom 0 Right 0
```

**Comment by dougbinks** [comment]
The window and framebuffer size look correct (unless the monitor has scaling), but the frame size is wrong because [glfwGetWindowFrameSize](https://github.com/glfw/glfw/blob/master/src/wl_window.c#L2354-L2369) does not support returning the size for server side decorations, due to [limitations in the Wayland protocol](https://github.com/glfw/glfw/issues/2435#issuecomment-1845455348).

This should be documented, I've assigned myself issue #2646.

**Comment by diniamo** [comment]
We can close this issue, after some more testing, this is a Hyprland only issue.

See hyprwm/Hyprland#8495 for more details.
