### ISSUE TITLE
Pointer warp on windows doesn't move cursor

### ISSUE THREAD

**Issue by buzmeg** [glfw/glfw#2647]
On Windows, cursor warp causes the reported cursor coordinates to warp but not the actual cursor pointer/picture/icon itself.

If you warp the cursor to new coordinates, and then press a mouse button, the reported coordinates in the button event are the warped coordinates in spite of the fact that the cursor pointer remains at the old coordinates.  

However, if you move the mouse motion even a subpixel, the reported coordinates from any event revert to the old coordinates (ie where the cursor is still displayed).

Windows 10 -- Freetype 2.13.3 

Thanks.

**Comment by elmindreda** [comment]
I was unable to reproduce this on Windows 10. Are you moving the cursor with `glfwSetCursorPos`?

**Comment by buzmeg** [comment]
Yes, I am using glfwSetCursorPos().  This works on X11 but does not when I move the code to Windows 10.

And why did I tell you the Freetype version and not GLFW version?  That's stupid.  WTF was I thinking?

GLFW version 3.4.0.

I'm using Zig and Vulkan.  If you can't reproduce, I'll try to cough up a cut down case.

**Comment by buzmeg** [comment]
Can confirm that with Zig on Windows 10 with GLFW 3.4.0 downloaded and using lib-vc2022 glfw3_mt.lib that cursor warp does work on a straight GLFW window.

This is either a compilation problem or a Vulkan issue.  Closing issue for now.

If I diagnose this further, I will reopen a different issue.
