### ISSUE TITLE
Legacy WGL context, Old WGL context, Virtualbox, Windows

### ISSUE THREAD

**Issue by dafadey** [glfw/glfw#2650]
Sorry If my question is not relevant to project goals but I always thought that with GLFW I can create 1.1 context.
I tried to specify MAJOR=1 and MINOR=1 but I still have 3.1 on real Windows and a failure of window creation on virtual box-ed Windows. On virtual Windows I've tried mesa3D with a hint asking for 1.1 context, window was created but I still have 3.2 context.
In cases when GL 1.1 is enough it would be a pleasure to have GLFW3 working on virtual box-ed OS-es and ones without proper drivers or really old cards. I have tried to change GLFW3 code but found it quite confusing.
I'm not sure if GLFW is officially capable of creating a legacy WGL context. From GLFW documentation I see that 1.1 hint seems to be valid but it turns to be not working.

**Comment by GamesTrap** [comment]
I'm able to create a glfw Window with an OpenGL 1.1 context using the following window hints:

```c
glfwWindowHint(GLFW_CLIENT_API, GLFW_OPENGL_API);
glfwWindowHint(GLFW_CONTEXT_CREATION_API, GLFW_NATIVE_CONTEXT_API);
glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 1);
glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 1);
glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GLFW_FALSE);
```

You also have to disable the check for hardware acceleration that is done in [`wgl_context.c:160`](https://github.com/glfw/glfw/blob/b35641f4a3c62aa86a0b3c983d163bc0fe36026d/src/wgl_context.c#L160)

Result:
![image](https://github.com/user-attachments/assets/fd848f6a-d15c-4e79-ac43-43d006ac41e2)

**Comment by dafadey** [comment]
Thanks for the hint! I have some problems with texturing but it definitely glClears and draws unextured white rectangle. That is a win! GLFW 3.4, Windows 10, Oracle Virtual Box

**Comment by dafadey** [comment]
Thanks for the hint! I have some problems with texturing but it definitely glClears and draws unextured white rectangle. That is a win! GLFW 3.4, Windows 10, Oracle Virtual Box
