### ISSUE TITLE
glfwMakeContextCurrent does not create context in another thread (I think)

### ISSUE THREAD

**Issue by Maximilian560** [glfw/glfw#2658]
I write a dll to the main program, the dll receives a window from the main program and tries to create a context, and everything seems to work, even OpenGL functions work correctly, but glfwGetCurrentContext returns nullptr and the glfwSwapInterval function does not work (it throws an error 0x00010002 "Cannot set swap interval without a current OpenGL or OpenGL ES context").  
Example:
dll:
```cpp
#include<iostream>
#include <glad/glad.h>
#include <GLFW/glfw3.h>
using namespace std;
extern "C" __declspec(dllexport) void Set_Window(GLFWwindow* win){
  if(!glfwInit()){cout<<"glfw init error\n";}
  glfwMakeContextCurrent(win);
  if(!glfwGetCurrentContext()&&glfwGetCurrentContext()!=win){
    cout<<"Strange error\n";
  }
  // some code
}
```
main program:
```cpp
#include<iostream>
#include <windows.h>
#include <glad/glad.h>
#include <GLFW/glfw3.h>
using namespace std;
int main(){
  if(!glfwInit()){cout<<"glfw init error\n";}
  GLFWwindow* win = glfwCreateWindow(800, 600, "Test", nullptr, nullptr); 
  glfwMakeContextCurrent(win);
  
  // some code
    glfwMakeContextCurrent(nullptr);
    HMODULE dll= LoadLibrary("dll.dll");
    auto dll_func = (void(*)(GLFWwindow*))GetProcAddress(dll, "Set_Window");
    dll_func(win);
}
```
Actually the project where this bug was noticed is big and this code was made up on the fly, but it would be embarrassing if this code worked as it should, so I decided to check it, and it doesn't work either.

**Comment by Maximilian560** [comment]
There may be some missing dependencies, I checked the code in my project with separate functions, there are many more dependencies in the project

**Comment by Maximilian560** [comment]
Sorry, didn't know I needed more information, here it is:
OS and version: Windows 11
GPU and driver: RTX 3050; NVIDIA 566.14
Release or commit: 3.4.0
Version string: 3.4.0 Win32 WGL Null EGL OSMesa MinGW-w64
glfwinfo output:
GLFW header version: 3.4.0
GLFW library version: 3.4.0
GLFW library version string: "3.4.0 Win32 WGL Null EGL OSMesa MinGW-w64"
GLFW platform: Win32
GLFW supported platforms:
 Win32
 Null
OpenGL context version string: "4.6.0 NVIDIA 566.14"
OpenGL context version parsed by GLFW: 4.6.0
OpenGL context flags (0x00000000):
OpenGL context flags parsed by GLFW:
OpenGL profile mask (0x00000000): unknown
OpenGL profile mask parsed by GLFW: compat
OpenGL robustness strategy (0x00008261): none
OpenGL robustness strategy parsed by GLFW: none
OpenGL context renderer string: "NVIDIA GeForce RTX 3050 Laptop GPU/PCIe/SSE2"
OpenGL context vendor string: "NVIDIA Corporation"
OpenGL context shading language version: "4.60 NVIDIA"
OpenGL framebuffer:
 red: 8 green: 8 blue: 8 alpha: 8 depth: 24 stencil: 8
 samples: 0 sample buffers: 0
 accum red: 16 accum green: 16 accum blue: 16 accum alpha: 16 aux buffers: 4
Vulkan loader: available
Vulkan loader API version: 1.3
Vulkan window surface required instance extensions:
 VK_KHR_surface
 VK_KHR_win32_surface
Vulkan window surface created successfully
Vulkan conformant discrete GPU device: "NVIDIA GeForce RTX 3050 Laptop GPU" (API version 1.3)
Vulkan device queue family presentation support:
 0: supported
 1: no
 2: supported
 3: no
 4: no
 5: no
Vulkan conformant integrated GPU device: "AMD Radeon(TM) Graphics" (API version 1.3)
Vulkan device queue family presentation support:
 0: supported
 1: supported
 2: supported

**Comment by GamesTrap** [comment]
The `"Cannot set swap interval without a current OpenGL or OpenGL ES context"` error you are getting happens because the main executable **and** your DLL each hold global static data that glfw uses **independently** of each other. This means when you for example set the current context on the main executable then the DLL won't know about this because the context will only be set in the global static data of the main executable and **not** in the DLLs global static data.

To solve this you should either do *all* glfw operations in the main executable **or** in the DLL such that only one global static data exists for glfw.

**Comment by Maximilian560** [comment]
I looked at the source code of the window context creation function, this error is thrown only if the window exists and if its context.client is GLFW_NO_API (defined as 0). I can't guess why it becomes 0 if in another thread it is not 0. The window definitely exists, if the pointer was 0 that "strange error" from my code would not be called. I also looked for static variables and did not find any. Maybe I'm missing something.

**Comment by Maximilian560** [comment]
I decided to make sure that in the main thread context.client is not equal to zero, defined undefined structures, print the context.client pointer (it turns out that it is defined as void*), and it is equal to 0. How then glfwMakeContextCurrent does not throw an error in the main thread I have no idea

**Comment by dougbinks** [comment]
Some quick thoughts:

1. Make sure you are linking the DLL and exe to the DLL version of GLFW, on Windows using [GLFW_DLL](https://www.glfw.org/docs/latest/build_guide.html#build_macros) macro.
2. You should only [call glfwInit once from the executable on the main thread](https://www.glfw.org/docs/latest/group__init.html#ga317aac130a235ab08c6db0834907d85e).

**Comment by Maximilian560** [comment]
Didn't help.
I also forgot to clarify, I use static glfw on mingw w64

**Comment by dougbinks** [comment]
> I also forgot to clarify, I use static glfw on mingw w64

The most important change to make is point 1, make sure you are linking the DLL and exe to the DLL version of GLFW, on Windows using [GLFW_DLL](https://www.glfw.org/docs/latest/build_guide.html#build_macros) macro.

If you use a static library you will have two versions of GLFW. This is not supported, and you can't share contexts between two versions of GLFW.

**Comment by Maximilian560** [comment]
I read it more carefully and saw that it is not supported. Anyway, thank you very much for your help

**Comment by dougbinks** [comment]
Glad you have resolved this.
