### ISSUE TITLE
Transparent attribute is invalid on Windows with angle-vulkan backend.

### ISSUE THREAD

**Issue by wzhengsen** [glfw/glfw#2663]
When I use angle-d3d11 as a backend, the window is correctly transparent using the GLFW_TRANSPARENT_FRAMEBUFFER attribute, but with the angle-vulkan backend, the window changes to a black background and transparency fails.

**Comment by dougbinks** [comment]
With the exception of the [GLFW_ANGLE_PLATFORM_TYPE hint](https://www.glfw.org/docs/latest/intro_guide.html#GLFW_ANGLE_PLATFORM_TYPE_hint) GLFW doesn't explicitly have any interaction with Angle, so I think this issue is a limitation or issue in angle-vulkan rather than GLFW.
