### ISSUE TITLE
GLFW scales window but not OpenGL viewport

### ISSUE THREAD

**Issue by Skulduggerry** [glfw/glfw#2666]
I started using scaling with Linux because I recently got a UHD monitor.

When working with OpenGL and GLFW I noticed that the screen was scaled up by a factor of two however the OpenGL viewport was not. This resulted in my programm looking like this.

![Screenshot](https://github.com/user-attachments/assets/f1222241-fa42-437e-af8b-3b51dbb6e1d6)

As you can see MangoHud reports a resolution of 1600x1200 instead of the 800x600 I set in my code. This would not be such big of a deal if GLFW would not only scale up the window but also the viewport of OpenGL.

From my research I found that setting the ```GLFW_SCALE_FRAMEBUFFER``` window hint to false kind of fixes the issue because now the whole window is filled. But because the window is still twice the size I said it should be the whole image looks blurry.

I would really appreciate if someone knows a solution to this or if the only thing I can do is setting the viewport manually and code everything as if the resolution was Full HD?

**Comment by dougbinks** [comment]
The framebuffer size and window size can be two different things, so you need to check the [framebuffer size](https://www.glfw.org/docs/latest/window_guide.html#window_fbsize) and set your OpenGL viewport accordingly.

**Comment by Skulduggerry** [comment]
Thank you
