### ISSUE TITLE
Add Windows binaries to GitHub releases

### ISSUE THREAD

**Issue by jayschwa** [glfw/glfw#273]
GitHub's Releases feature [allows arbitrary files to be added](https://help.github.com/articles/listing-and-editing-releases), which makes them available for download. Please upload the Windows binary archives, at least for v3.0.4 and beyond. SourceForge sucks and its download links are not easily usable with `curl` and friends.

I am in the process of updating my [Julia bindings](https://github.com/jayschwa/GLFW.jl) and would like to have my package automagically get a DLL on Windows. Direct links to the archives will make that task easier.

P.S. If this request is fulfilled, I suggest changing the [download buttons](https://github.com/glfw/website/blob/master/download.md#windows-pre-compiled-binaries) on the site to direct links as well.

**Comment by jayschwa** [comment]
Congrats on the new point release. Bumping this so it doesn't get lost. @elmindreda @siavashserver

**Comment by elmindreda** [comment]
Thank you.

**Comment by siavashserver** [comment]
@elmindreda  Is there anything blocking this change?

**Comment by elmindreda** [comment]
*Finally* got round to [this](https://github.com/glfw/glfw/releases/tag/3.1). There is afaik no way to disable the useless **Source archive** links, so just ignore those.
