### ISSUE TITLE
glfwSetWindowPos sets position of frame on Xfwm4

### ISSUE THREAD

**Issue by arampl** [glfw/glfw#274]
I've written small program which stores in the text file window position on exit and retrieves it on start and found that glfwGetWindowPos gets position of the client area, but glfwSetWindowPos uses position of the whole window (including title bar, etc.).
As a result each run moves window down and to the right in accordance with the window's decorations.

Solution:
function "_glfwPlatformSetWindowPos" in file "x11_window.c" should be like this:

```c
void _glfwPlatformSetWindowPos(_GLFWwindow* window, int xpos, int ypos)
{
    int x,y;

    Window child;
    XTranslateCoordinates(_glfw.x11.display, _glfw.x11.root, window->x11.handle,
                          xpos, ypos, &x, &y, &child);

    XMoveWindow(_glfw.x11.display, window->x11.handle, x, y);
    XFlush(_glfw.x11.display);
}
```

instead of:

```c
void _glfwPlatformSetWindowPos(_GLFWwindow* window, int xpos, int ypos)
{
    XMoveWindow(_glfw.x11.display, window->x11.handle, xpos, ypos);
    XFlush(_glfw.x11.display);
}
```

Regards :)

**Comment by elmindreda** [comment]
This appears to work with Xfwm 4.12. The position of the client area is that is set, for both decorated and undecorated windows.
