### ISSUE TITLE
Support a Joystick Hat-switch

### ISSUE THREAD

**Issue by usagi** [glfw/glfw#278]
Joystick **hat switch** is not supporting in GLFW-3.0.4 currently.

The hat switch is a popular gamepad feature. For example XBOX360 gamepad has hat switch at the left-side, PS3 controller has it in the same. And any other game controllers has the hat switch feature.

In commonly, say a "supporting a game controllers" then it will support hat switch, digital buttons and analog axes/triggers.

Please plan to support hat switch of joystick.

Related old time discussion?: http://sourceforge.net/p/glfw/discussion/247562/thread/d4f45381/

**Comment by CreamyCookie** [comment]
@elmindreda Hello! :)

I'd like to use [gamecontrollerdb.txt](https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt), but there are a lot of hat switches. Do you have an idea how one could transform them to axis (or buttons, on OSes where that's the case)?

For example, the line for "Microsoft X-Box 360 pad" on Linux is correct regarding buttons and axis, but then there's this part:

`dpleft:h0.8,dpdown:h0.4,dpright:h0.2,dpup:h0.1,`

Using GLFW the hat switch / DPAD is reported as two axis:

```java
DPAD_HORIZONTAL_AXIS = 6;
DPAD_VERTICAL_AXIS = 7;
```

Currently, I'd just use the last two axes for the DPAD but that will likely not work everywhere. (Especially on operating systems where hat switches are buttons.)

**Comment by elmindreda** [comment]
@CreamyCookie My plan is to add direct support for that database (#341) along the lines of the SDL2 interface.

**Comment by CreamyCookie** [comment]
Great! I'm looking forward to this. =)

FYI, the issue (#341) you mentioned is already closed. Is there an open report that I could subscribe to?

**Comment by CreamyCookie** [comment]
Oh.. and will this be for 3.3? I'd also be interested in how this would work. 

This is how I'm imagining it currently: (in pseude code)

    GLFWController c = LoadControllerFromMapping();
    if (c.isUpPressed() || !c.wasXPressed()) {
        // ..
    }

**Comment by CreamyCookie** [comment]
@elmindreda ?
