### ISSUE TITLE
cannot build glfw as shared and another cmake library as static

### ISSUE THREAD

**Issue by onqtam** [glfw/glfw#279]
The only way (reasonable) to build glfw as a shared lib through cmake is to set BUILD_SHARED_LIBS to ON.
This has the effect of changing every library that does not explicitly specify itself as STATIC or SHARED to be SHARED so it is not suitable when multiple cmake files are in the same "cache domain" of this variable.
PLEASE provide a different way to specify how glfw is built. Maybe add a supplementary option to test against, one that is only for glfw?

if (BUILD_SHARED_LIBS OR GLFW_BUILD_AS_SHARED)
    set(_GLFW_BUILD_DLL 1)
endif()
...
if(GLFW_BUILD_AS_SHARED)
    add_library(glfw SHARED ${glfw_SOURCES} ${glfw_HEADERS})
else()
    add_library(glfw ${glfw_SOURCES} ${glfw_HEADERS})
endif()

**Comment by onqtam** [comment]
still thinking about this..

**Comment by mcclure** [comment]
I have just got burned by this issue... GLFW "namespaces" its other CMake variables so it's strange this one is not "namespaced". This is a real inconvenience with the way CMake works, a CMakeLists include_directorying another CMakeLists has no good way to work around namespace stomping performed by the included CMake file

**Comment by hdf89shfdfs** [comment]
Personally I'd rather GLFW not do this.

When you set BUILD_SHARED_LIBS the expectation is that every library that didn't manually specify it's type will conform to what you said.

Creating custom conventions is never ideal, and age very badly in cmake.
(Speaking as someone who is revamping my company's cmake infrastructure...)

Here is a way you can handle this situation in cmake, without having to modify the cmake code.

```
set(BUILD_SHARED_LIBS_OLD ${BUILD_SHARED_LIBS})

# OFF or ON whatever you want.
set(BUILD_SHARED_LIBS OFF)

add_subdirectory(glfw)

set(BUILD_SHARED_LIBS ${BUILD_SHARED_LIBS_OLD})
```

**Comment by elmindreda** [comment]
Thank you for your feedback and your patience.

You can now (finally) control the library type of GLFW separately with the optional `GLFW_LIBRARY_TYPE` CMake variable added by d83849792b0cf3e40c402f299c867ac6e1fd0e20. When set this will override the value of `BUILD_SHARED_LIBS` without affecting other libraries.
