### ISSUE TITLE
OSMesa context support

### ISSUE THREAD

**Issue by andrewcorrigan** [glfw/glfw#281]
Can GLFW please support creating an OSMesa context for pure software rendering, as an alternative to GLX or EGL on Linux?

My OpenGL 2.0+ application needs to support rendering on remote systems with X forwarding over SSH, without VNC or anything.  With X forwarding, I can get at most an OpenGL 1.x context regardless of the hardware supported on the client, and even worse, large three-dimensional datasets need to be transferred over the network prior to being rendered on the client.  With Mesa, I can get an OpenGL 2.1 rendering context, with all rendering performed on the server (albeit in software), and then only the final 2D image needs to be transferred back to the client.

Currently my application uses a weird combination of SDL2, software rendering only, and OSMesa, but it would ideal to be able to just compile GLFW to use X11 + OSMesa, without GLX or EGL.

Alternatively, if it would be possible to get GLFW to just setup a window and handle input, but not context management, that would be helpful.  I could then figure out how to blit pixels to the screen via the existing Native Access functionality.

Finally, if anyone has a better way to perform OpenGL 2.0+ rendering on a remote server, without transferring large 3D data sets to the client, and using only X forwarding (no VNC), I would really appreciate any advice.  Perhaps there is a simpler way to accomplish these things?

**Comment by chuanqichen** [comment]
@elmindreda What's the status of OSMesa support? I am looking for doing offscreen rendering even without video driver. Great work guys, please let me know how can I do that.

**Comment by jshin49** [comment]
@elmindreda Any status updates regarding this issues? Very appreciated guys!

**Comment by elmindreda** [comment]
See the `osmesa` branch for a headless implementation of OSMesa support.

**Comment by elmindreda** [comment]
Support for OSMesa context creation on all supported backends has been added with e9560ef021c101def23a5c3b383d057b2a0e58d3.

Sorry for the long delay. Perhaps this is still useful to some of you.
