### ISSUE TITLE
Video modes don't take monitor rotation into account

### ISSUE THREAD

**Issue by capnm** [glfw/glfw#284]
In the structure given from `glfwGetVideoMode(monitor)` should be the width and the height value swapped if the monitor is left or right rotated (or at least the rotation status should be exposed).

Also `glfwCreateWindow()` behaves on rotated monitor differently in windowed (w/h correct) and fullscreen (w/h swapped) mode.

Note: The wm (XEvent ConfigureNotify) provides (however after a while) the right w/h values.
E.g. ubuntu's unity-compiz sends after the switch on the monitor [1680 0]1050x1680 (rotated) the window to fullscreen:

```
XEvent:ConfigureNotify [0 0]1680x1050
XEvent:ConfigureNotify [0 0]1629x996
XEvent:ConfigureNotify [50 53]1629x996
XEvent:ConfigureNotify [50 53]1629x996
XEvent:ConfigureNotify [0 0]1629x1626
XEvent:ConfigureNotify [1681 53]1629x1626
XEvent:ConfigureNotify [0 0]1048x1626
XEvent:ConfigureNotify [1681 53]1048x1626
XEvent:ConfigureNotify [0 0]1050x1680
XEvent:ConfigureNotify [1680 0]1050x1680
XEvent:ConfigureNotify [1680 0]1050x1680
XEvent:ConfigureNotify [1680 0]1050x1680
XEvent:ConfigureNotify [1680 0]1050x1680
...
```

Tested only on  Linux.

**Comment by Lassebq** [comment]
Same issue on wayland
