### ISSUE TITLE
Option to disable cursor position restoration

### ISSUE THREAD

**Issue by arampl** [glfw/glfw#289]
Hi all!

I have a problem with mouse cursor. I think it is related (collided?) with #193 issue.

Situation:

1. User moves mouse over the gui button -> button highlighted.
2. User presses left mouse button -> application sets cursor to GLFW_CURSOR_DISABLED mode (i need this mode, not GLFW_CURSOR_HIDDEN)
3. User drags mouse somewhere and releases button -> application sets cursor to GLFW_CURSOR_NORMAL mode.
4. Cursor position is now in the center, so application sets it to the new position with glfwSetCursorPos.

- But the library sets cursor to the old position, which was before GLFW_CURSOR_DISABLED and gui button still thinks that it is highlighted.
- New position becomes actual only after moving mouse a little.

I understand, that restoring old cursor position may be useful in other situations, but can this behavior be controlled with some parameter?

**Comment by elmindreda** [comment]
The problem with not restoring the cursor position after leaving disabled cursor mode is that the position the application has been told is often far outside the screen. I understand that in your case this is not an issue, but I'm not sure this is a sufficiently common need to warrant complicating the code.

**Comment by shurcooL** [comment]
I'm a little confused by your description,

> Cursor position is now in the center, so application sets it to the new position with glfwSetCursorPos.

What is the _new position_?

**Comment by arampl** [comment]
@shurcooL : new position = actual position to where user dragged mouse cursor. After restoring GLFW_CURSOR_NORMAL mode library sets mouse cursor position to position where it was set to GLFW_CURSOR_DISABLED last time.

@elmindreda : Well then. I'm against unwanted complexity in the library. I think I just will use my own image cursors (including "empty" cursor instead of GLFW_CURSOR_DISABLED) for all situations. It is even more generalized way to deal with different cursors.

**Comment by shurcooL** [comment]
> new position = actual position to where user dragged mouse cursor.

That doesn't make sense to me. If the cursor is disabled, it can't be moved by the user.

> After restoring GLFW_CURSOR_NORMAL mode library sets mouse cursor position to position where it was set to GLFW_CURSOR_DISABLED last time.

It sounds like you do want to use GLFW_CURSOR_HIDDEN instead of GLFW_CURSOR_DISABLED, so why do you use GLFW_CURSOR_DISABLED? Can you elaborate?

**Comment by arampl** [comment]
"If the cursor is disabled, it can't be moved by the user."
You can get mouse coords through glfwSetCursorPosCallback even if the cursor is disabled.

"...you do want to use GLFW_CURSOR_HIDDEN instead of GLFW_CURSOR_DISABLED"
Tried to use "hidden" and it seems to work, but it was my old project. Need to refresh it in memory to remember why I use "disabled" and not "hidden". May be something with very fast moving of the cursor to the window bounds.
Also as stated in the docs: "If you wish to implement mouse motion based camera controls or other input schemes that require unlimited mouse movement, set the cursor mode to GLFW_CURSOR_DISABLED."
