### ISSUE TITLE
Xfce4 moves window on map

### ISSUE THREAD

**Issue by arampl** [glfw/glfw#290]
When my app is about to close i need to save window position wherever it is. Even if its x = -100 & y = -100 for example.
In the next run window created initially invisible, then app sets window's position saved earlier, then app shows window (as recommended).
It all works fine if the whole window fit on the screen:
~~~~~~~
glfwWindowHint(GLFW_VISIBLE, GL_FALSE);
window = glfwCreateWindow(640, 480, title, NULL, NULL);
glfwSetWindowPos(window, 50, 50);
glfwShowWindow(window);
~~~~~~~
But if the window doesn't fit on the screen, it will be automatically moved so that it fit on screen.
For this reason i must set window's position again after showing it:
~~~~~~~
glfwWindowHint(GLFW_VISIBLE, GL_FALSE);
window = glfwCreateWindow(640, 480, title, NULL, NULL);
glfwSetWindowPos(window, -50, -50);
glfwShowWindow(window);
glfwSetWindowPos(window, -50, -50);
~~~~~~~
Also, if window's width > screen width and / or window's height > screen height, it will be automaticaly resized to screen width / height, so after showing it i need to set window size again.

**Comment by elmindreda** [comment]
I've tried every combination of pre-map requests I know of but Xfwm4 will not be dissuaded. Sorry. The protocols give window managers a lot of freedom in how to place windows and as clients we are expected to cope.
