### ISSUE TITLE
Cannot hide cursor using glfwSetInputMode

### ISSUE THREAD

**Issue by hpohl** [glfw/glfw#309]
```c++
glfwSetInputMode(window, GLFW_CURSOR, GLFW_CURSOR_HIDDEN);
assert(glfwGetInputMode(window, GLFW_CURSOR) == GLFW_CURSOR_HIDDEN);
```

It simply does not work, the cursor is still shown. The assertion passes. I'm on the latest Fedora using KDE.

**Comment by imaginationcoin** [comment]
This is open a very long time

**Comment by imaginationcoin** [comment]
Workaround:
GLFWcursor* CursorManager::BlankCursor()
{
	int w=1;//16;
	int h=1;//16;
	unsigned char pixels[w * h * 4];
	memset(pixels, 0x00, sizeof(pixels));
	GLFWimage image;
	image.width = w;
	image.height = h;
	image.pixels = pixels;
	return glfwCreateCursor(&image, 0, 0);
}

**Comment by elmindreda** [comment]
That's pretty much what GLFW does internally. Without this workaround, how what the cursor look like when it's supposed to be invisible?

**Comment by elmindreda** [comment]
This also affects Fluxbox 1.3.6.

**Comment by alekseyrybalkin** [comment]
JFYI, git bisect shows [this commit](https://github.com/glfw/glfw/commit/e0a26aa62f12545d7999f3c8486d9b832f76f0a0) as the first bad commit.

**Comment by alekseyrybalkin** [comment]
https://github.com/glfw/glfw/pull/431 that fixed the issue for me, please review

**Comment by evenex** [comment]
#431 makes the cursor disappear but doesn't have the correct window location. so I can see the cursor when its in the window, and it is hidden when its on the other side of the screen. Debian 3.2.0-4-amd64 debian 3.2.65-1+deb7u1, running gnome shell 3.4.2

**Comment by evenex** [comment]
#431 fixed the issue for me as well

**Comment by elmindreda** [comment]
@hpohl Does #431 work for you?
