### ISSUE TITLE
Make XInput2 optional

### ISSUE THREAD

**Issue by andrewcorrigan** [glfw/glfw#314]
Any chance of not requiring XInput2.h? I still have to use many systems that just have RHEL 5, which is still supported through 2017, but is lacking XInput2. For now, I have SDL2, but definitely prefer GLFW when possible. If this might be possible, I could try to submit a pull request.

**Comment by andrewcorrigan** [comment]
Thank you!  I really appreciate it.

**Comment by elmindreda** [comment]
I suspect I won't like the answer but what's the CMake version on those ancient systems?

**Comment by andrewcorrigan** [comment]
To answer your question directly, for the latest point releases, CentOS 5 has 2.6.4 [1], CentOS 6 has 2.8.12 [2].  I was under the impression that earlier version of CentOS 6 had a significantly older CMake, since that's actually newer than what's included in CentOS 7.

I appreciate greatly your consideration of those of us required to support these legacy systems, however, upgrading cmake in user-space is not a big deal, my two cents would be to just worry about maintaining compatibility with more fundamental system components like X11, and to just do what is most convenient for you in terms of the build system.

[1] http://mirror.centos.org/centos/5/os/x86_64/CentOS/
[2] http://mirror.centos.org/centos/6/os/x86_64/Packages/

**Comment by elmindreda** [comment]
@andrewcorrigan Thank you, I'll do that then.

**Comment by elmindreda** [comment]
@andrewcorrigan This is a heads-up; I will be merging the `dynamic-glx` branch for 3.1.2. It's possible that it will need updating for your systems.

**Comment by chuanqichen** [comment]
@elmindreda Is "XInput2 optional" in latest code? I am working on a project that customer need supports Redhat EL5 which don't have XInput2. I am interested in test out "Making XInput2 optional" as soon as it's available. Thanks!

**Comment by elmindreda** [comment]
@chuanqichen As you can see to the right it was merged into 3.1.1, which was released in March.

**Comment by andrewcorrigan** [comment]
@elmindreda I'l give it a try as soon as I can, but I might just have to wait to file any issues later as I'm bogged down for the foreseeable future.

**Comment by fgfxf** [comment]
https://github.com/fgfxf/centos5-opengl2-glfw3/tree/main

no thinks
