### ISSUE TITLE
Registered GLFWwindowclosefun not called with glfwSetWindowShouldClose

### ISSUE THREAD

**Issue by raselneck** [glfw/glfw#340]
I have a close callback registered with a window, and it is called when I manually close the window (press the X) but it is not called when I call `glfwSetWindowShouldClose(window, true)`.

If it helps, I'm using 3.0.4 on Windows 8.1.

**Comment by Chamberlain91** [comment]
Might be useful to put this into the guides, I didn't think of this option until a search brought me here.
