### ISSUE TITLE
Context creation fails on ANGLE

### ISSUE THREAD

**Issue by mumin16** [glfw/glfw#343]
I want to use angle project with glfw3. But glfwCreateWindow is unsuccessful. the return error is unsuitable eglconfig... help please...

**Comment by ArcaneEngineer** [comment]
@mumin16 Would it be possible to show a full example, including app code that sets up EGL context / window? I too would like to get ANGLE working with glfw. As I don't want to hijack this thread, perhaps you might be so kind as to email me at arcaneingenuity at gmail dot com.

**Comment by lygstate** [comment]
The angle is fixed the issue in:
https://code.google.com/p/angleproject/issues/detail?id=501
