### ISSUE TITLE
Mode setting fails for 25-30Hz modes

### ISSUE THREAD

**Issue by BryceMehring** [glfw/glfw#350]
While on Windows, creating a fullscreen window sometimes fails with the following error: `Win32: Failed to set video mode`. Windowed mode works just fine though. This is with the latest version of glfw on github.

modes.exe -t: http://pastebin.com/7rz5Uf7E
modes.exe: http://pastebin.com/7Lkt821z

System specs:
* Windows 8.1
* AMD 6970 with the 14.4 driver

**Comment by elmindreda** [comment]
Please see if the `cds-test` branch resolves this issue.

**Comment by BryceMehring** [comment]
Just tested the cds-test branch and ran the monitors test without error.

**Comment by elmindreda** [comment]
Cool! Thank you for testing!

Just one more thing: does `glfwInit` in that branch take a long time to complete on your system?

**Comment by BryceMehring** [comment]
`glfwInit` on that branch takes around 0.012 seconds to complete.

**Comment by elmindreda** [comment]
Thank you! I'll go ahead and merge this then.
