### ISSUE TITLE
Function to return key state array

### ISSUE THREAD

**Issue by emanuelpalm** [glfw/glfw#359]
When dealing with keyboard key combinations, I've found it very convenient to be able to look in a keyboard state table rather than having to get each relevant key. This is [something you can do with SDL2](http://hg.libsdl.org/SDL/file/9ecf775ead1b/src/events/SDL_keyboard.c#l843), and is something I believe could be of benefit to the GLFW3 API.

Using it could look something like this:

    vector2_t velocity = {.x = 0.0, .y = 0.0};
    const char *keyboard = glfwGetKeyboardState(window);
    if (keyboard[GLFW_KEY_UP]    || keyboard[GLFW_KEY_W]) velocity.y -= 1.0;
    if (keyboard[GLFW_KEY_DOWN]  || keyboard[GLFW_KEY_S]) velocity.y += 1.0;
    if (keyboard[GLFW_KEY_LEFT]  || keyboard[GLFW_KEY_D]) velocity.x -= 1.0;
    if (keyboard[GLFW_KEY_RIGHT] || keyboard[GLFW_KEY_A]) velocity.x += 1.0;
    return vector2_normalize(velocity);

I read through the GLFW source code and started hacking on a possible implementation, but then I realized that the whole sticky key deal makes things more complicated. As `_GLFW_STICK` keys may not be reported to the GLFW user, those key states have to be changed to either `GLFW_PRESS` or `GLFW_RELEASE` when calling the function.

The solutions I've thought of are to either (1) prevent the user from using the function if sticky keys are enabled, (2) arbitrarily set all `_GLFW_STICK` keys to `GLFW_PRESS` when calling the function, or (3) somehow mimic the behavior of the `glfwGetKey()` function.

Is this a function people would use, and whats thought do you have regarding its implementation in relation to sticky keys?

**Comment by elmindreda** [comment]
```c
#define keyboard(key) glfwGetKey(window, key)
vector2_t velocity = {.x = 0.0, .y = 0.0};
if (keyboard(GLFW_KEY_UP)    || keyboard(GLFW_KEY_W)) velocity.y -= 1.0;
if (keyboard(GLFW_KEY_DOWN)  || keyboard(GLFW_KEY_S)) velocity.y += 1.0;
if (keyboard(GLFW_KEY_LEFT)  || keyboard(GLFW_KEY_D)) velocity.x -= 1.0;
if (keyboard(GLFW_KEY_RIGHT) || keyboard(GLFW_KEY_A)) velocity.x += 1.0;
return vector2_normalize(velocity);```

**Comment by et1337** [comment]
One way this could be useful is with multithreading. It would be nice to be able to call glfwGetKeyboardState on the main thread, then copy it off for another thread's use.
