### ISSUE TITLE
glfwGetVideoModes lists unsupported modes

### ISSUE THREAD

**Issue by EmJayJay** [glfw/glfw#370]
Self-explanatory, instead of returning first value pointed by glfwGetVideoModes(...) with glfwGetVideoMode(...) you should get the monitor's native video modes if available.

glfwGetVideoMode(...) can return struct which can hold resolution value of 320x240 when the user's screen is well above it. And glfwGetVideoModes(...)'s final values can be well above the screen's real capabilities.

Would this kind of function be possible and easily done?

**Comment by elmindreda** [comment]
@EmJayJay Did you upgrade your system? Does the bug persist on the newer system?
