### ISSUE TITLE
Any way to get error message/reason a glfwCreateWindow crashes?

### ISSUE THREAD

**Issue by tmason101** [glfw/glfw#374]
Hello,

I am developing for the Oculus Rift and in certain instances calling glfwCreateWindow() crashes with an exception.

I am wondering how I would go about troubleshooting this as when I don't have the Oculus Rift plugged in everything works fine.

I understand it may not be a problem with GLFW but I need to know why glfwCreateWindow() crashed. Is there a way to get a detailed error message or reason why a crash would occur (and not just a NULL handle)?

Thank you.

**Comment by elmindreda** [comment]
Is it okay to close this? It seems unlikely that Oculus would add support for older Intel cards to their SDK.
