### ISSUE TITLE
glfwWaitEvents spinning on cursor rect updates

### ISSUE THREAD

**Issue by zhanggyb** [glfw/glfw#375]
Hello, 

I'm trying the GLFW 3.1 in OS X and Linux, and found that: with the latest code from git repository, the glfwWaitEvent() takes too much CPU consumption in OS X 10.10 when the mouse cursor is hovering on the glfw window.
![activity_monitor_screenshot](https://cloud.githubusercontent.com/assets/1978235/4825234/ded4c9ee-5f62-11e4-9be2-16e0c7113db0.png)

It's very easy to reproduce this issue:
1. just use the example code on http://www.glfw.org/documentation.html to create a glfw window.
but replace the "glfwPollEvents();" with "glfwWaitEvents();"
2. Build and run your program, check the activity monitor in OS X.
3. Move your cursor and you'll find that when the cursor hovers on the window, the CPU consumption will increase (more than 50% on my iMac: i7 3.5GHz) immediately.

The Xcode/Instruments/Time Profiler may help to find the root cause:
![time_profiler_screenshot](https://cloud.githubusercontent.com/assets/1978235/4825250/163bc040-5f63-11e4-8e81-54dc27bb2858.jpg)

**Comment by marcj** [comment]
Does resolved mean that CPU usage is very low when moving the mouse? When I use the example from the documentation (no matter if I use `glfwPollEvents` or `glfwWaitEvents`) and just move over the active window I get 10% constant CPU usage, having nothing in the black window. Is this considered as normal? I'm using version `3.2.1 Cocoa NSGL chdir menubar retina dynamic` on Mac OS 10.12.4.
