### ISSUE TITLE
Integrating Coverity Scan

### ISSUE THREAD

**Issue by siavashserver** [glfw/glfw#385]
[Coverity Scan](https://scan.coverity.com/) is getting popular among opensource projects, what do you think about integrating its static analysis service into the GLFW repository?

**Comment by elmindreda** [comment]
This seems like a Good Thing.

**Comment by elmindreda** [comment]
This and Travis CI builds are [in](https://travis-ci.org/glfw/glfw) [progress](https://scan.coverity.com/projects/3184).

**Comment by siavashserver** [comment]
Looks great! :)

**Comment by siavashserver** [comment]
@elmindreda @bkaradzic One doesn't simply advertise [bgfx](https://github.com/bkaradzic/bgfx) here :stuck_out_tongue_winking_eye:   I was in rush and didn't check the coverity scan page (for some reason it takes ages to load here), [here is the link to the glfw's](https://scan.coverity.com/projects/4884).

**Comment by bkaradzic** [comment]
:+1: for bgfx coverity page. I did the scan while back and didn't really see huge benefit from it. Already GCC, clang, VS + valgrind cover most of it.

BTW, bgfx nicely interops with GLFW. Only if I knew someone who would go and fill up the blanks here: https://github.com/bkaradzic/bgfx/blob/master/examples/common/entry/entry_glfw.cpp :smiley:

**Comment by elmindreda** [comment]
So Coverity [doesn't seem to find any of the bugs](https://scan.coverity.com/projects/glfw-glfw).

**Comment by siavashserver** [comment]
Hmm, there are 10 bugs listed ... are they false positives?

**Comment by elmindreda** [comment]
Nine of them are in example code. Six of them are about calls to `random` in rendering code not being cryptographically secure.

**Comment by siavashserver** [comment]
Oh, I see. Good job on keeping the GLFW simple, secure and stable for all these years ^^

offtopic: MSVC 2015 (should) fully support C99. What benefits can C89->C99 have for GLFW?

**Comment by elmindreda** [comment]
The thing I'm looking forward to the most with C99 is not having to declare all variables at the start of a control block. There are other minor conveniences too but that's the main one for me. Have to wait until it's feasible to drop support for older versions of VS, though.
