### ISSUE TITLE
XkbGetKeyboard can return NULL

### ISSUE THREAD

**Issue by linkmauve** [glfw/glfw#389]
On Xwayland, it makes glfw segfault in:
#0  updateKeyCodeLUT () at /home/linkmauve/dev/glfw/src/x11_init.c:252

**Comment by fooishbar** [comment]
The reason this returns NULL is because we don't send the map name at all in Wayland; in fact, it may not have originally been XKB. Using XkbGetMap instead of XkbGetKeyboard will fix that.

**Comment by elmindreda** [comment]
@fooishbar Thank you, and interesting blog!

**Comment by fooishbar** [comment]
@elmindreda Heh, thanks. Also note that using XkbGetMap() instead will actually fix a real bug with X11: when you get the keyboard name and compile it yourself, this will ignore any modifications that users have made themselves with xmodmap or setting local XKB maps. Calling XkbGetMap() is the only way to guarantee that you're using the exact same keymap as the server and clients in general.

**Comment by elmindreda** [comment]
This has now been seen [in the wild](http://sourceforge.net/p/glfw/discussion/247562/thread/01bf8acc/).

**Comment by elmindreda** [comment]
@fooishbar Does 252ccb7c8dd6c475fee7fade4390f8bb87f6e8ef look right?

**Comment by fooishbar** [comment]
Yep, looks fine to me! Note that you can't necessarily rely on the names
being sensible (or non-empty) but the rest seems great.

**Comment by elmindreda** [comment]
@fooishbar There is a [fallback](https://github.com/glfw/glfw/blob/master/src/x11_init.c#L169). I don't yet know enough XKB to properly evaluate it, though.

**Comment by elmindreda** [comment]
@fooishbar Thank you for all your help!

**Comment by fooishbar** [comment]
Fallback looks fine to me. And, no problem! :)
