### ISSUE TITLE
Implement 'DISABLED' cursor mode in Wayland

### ISSUE THREAD

**Issue by jadahl** [glfw/glfw#394]
The 'DISABLED' cursor mode is so far unimplementable in the stable Wayland protocol, but work is going on to specify the needed protocol. This bug is meant to keep track of the progress of that in relation to GLFW, and the GLFW implementation itself. It can currently be tested by applying this commit: https://github.com/jadahl/glfw/commit/8b5a5e896263551535f2ebb0161b893b43bbaecd . Note that it needs the corresponding weston patches and libinput 0.7.

**Comment by elmindreda** [comment]
Fixed with #708.
