### ISSUE TITLE
_glfwPlatformMakeContextCurrent get's a nullptr window on all OpenGL versions above 3.1 

### ISSUE THREAD

**Issue by Joshhua5** [glfw/glfw#400]
firstly glfw error callback doesn't get called.

When calling glfwCreateWindow I'll get a GL_INVALID_ENUM on the glwMakeCurrent inside of the function _glfwPlatformMakeContextCurrent (Windows API).
I am including GLEW correctly aswell.

As far as I could go with tracing it back down was line 498 in wgl.context.c as this point window must be a nullptr.

EDIT: 
setting glewExperimental = true; doesn't change anything.

Call stack:
_glfwPlatformMakeContextCurrent - Core_Test.exe
_glfwCreateContext - Core_Test.exe
_glfwPlatformWaitEvents - Core_Test.exe
_glfwPlatformCreateWindow - Core_Test.exe
glfwCreateWindow - Core_Test.exe
Pro::Graphics::Window::window_constructor - window.cpp, line 49
 
My code:
	if (init == false)
		glfwInit();

	glfwSetErrorCallback(&glfw_error_callback);

	glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, def.gl_major);
	glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, def.gl_minor);
	glfwWindowHint(GLFW_RESIZABLE, def.resizable);
	glfwWindowHint(GLFW_VISIBLE, def.visible);
	glfwWindowHint(GLFW_DECORATED, def.decorated);
	glfwWindowHint(GLFW_STEREO, def.sterioscopic);
	glfwWindowHint(GLFW_RED_BITS, def.red_bits);
	glfwWindowHint(GLFW_GREEN_BITS, def.green_bits);
	glfwWindowHint(GLFW_BLUE_BITS, def.blue_bits);
	glfwWindowHint(GLFW_ALPHA_BITS, def.alpha_bits);
	glfwWindowHint(GLFW_DEPTH_BITS, def.depth_bits);
	glfwWindowHint(GLFW_STENCIL_BITS, def.stencil_bits);
	glfwWindowHint(GLFW_ACCUM_RED_BITS, def.accum_red_bits);
	glfwWindowHint(GLFW_ACCUM_GREEN_BITS, def.accum_green_bits);
	glfwWindowHint(GLFW_ACCUM_BLUE_BITS, def.accum_blue_bits);
	glfwWindowHint(GLFW_ACCUM_ALPHA_BITS, def.accum_alpha_bits);
	glfwWindowHint(GLFW_AUX_BUFFERS, def.aux_buffers);
	glfwWindowHint(GLFW_SAMPLES, def.samples);
	glfwWindowHint(GLFW_REFRESH_RATE, def.refresh_rate);
	glfwWindowHint(GLFW_SRGB_CAPABLE, def.srgb_capable);
	glfwWindowHint(GLFW_OPENGL_DEBUG_CONTEXT, def.debug);

	if (def.ogl_core_profile)
		glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_ANY_PROFILE);

// ERROR HERE
	window = glfwCreateWindow(def.width, def.height, def.title.data(), NULL, NULL);
	// triggers OpenGL Breakpoint inside of CodeXL on all versions 3.1+

The default values of def are(the same default values as found in glfw docs) :

		struct WindowDefinition {
			unsigned width = 800, height = 600;
			unsigned char gl_major = 3, gl_minor = 2;
			string title = "Protheus Engine";
			bool resizable = true;
			bool visible = true;
			bool decorated = true;
			bool sterioscopic = false;
			unsigned red_bits = 8;
			unsigned blue_bits = 8;
			unsigned green_bits = 8;
			unsigned alpha_bits = 8;
			unsigned depth_bits = 24;
			unsigned stencil_bits = 8;
			unsigned accum_red_bits = 0;
			unsigned accum_blue_bits = 0;
			unsigned accum_green_bits = 0;
			unsigned accum_alpha_bits = 0;
			unsigned aux_buffers = 0;
			unsigned samples = 0;
			unsigned refresh_rate = 0;
			bool srgb_capable = false;
			bool debug = true;
			bool ogl_core_profile = false;
		};

**Comment by Joshhua5** [comment]
This problem is present on Mac as well.
I'll get around to compiling a version with debugging info and finding the source.

**Comment by elmindreda** [comment]
What were your findings?

**Comment by Joshhua5** [comment]
OpenGL Debug Output: API - Error, Using glGetIntegerv in a Core context with parameter <pname> and enum '0x84e2' which was removed from Core OpenGL (GL_INVALID_ENUM)

84e2 is MAX_TEXTURE_UNITS

**Comment by elmindreda** [comment]
Thank you.

GLFW does not ever retrieve `GL_MAX_TEXTURE_UNITS`.

**Comment by elmindreda** [comment]
It sounds like the kind of error a GPU debugger would cause if it didn't support core profile contexts.
