### ISSUE TITLE
Original desktop resolution doesn't get reset after program terminated (fullscreen window)

### ISSUE THREAD

**Issue by IcyTesseract** [glfw/glfw#404]
When making a fullscreen window, after closing said window, the desktop resolution stays the same as the window resolution. The resolution does not get reset. I know this is a duplicate of #371, but this is happening on Ubuntu 14.10 now. 

According to #371, the issue was fixed by calling glfwTerminate, but this does not fix the issue and I had been doing this since the beginning. 

The way I'm initializing a window is by using this

```c
window = glfwCreateWindow(WINDOW_WIDTH, WINDOW_HEIGHT, WINDOW_TITLE, glfwGetPrimaryMonitor(), NULL);
```

**Comment by elmindreda** [comment]
Is this still an issue? Does 3.1 build on your machine?

**Comment by IcyTesseract** [comment]
I apologize. I should have closed this a long time ago. The issue has since been resolved.

**Comment by elmindreda** [comment]
Thank you for following up!
