### ISSUE TITLE
Single buffering?

### ISSUE THREAD

**Issue by blitz-research** [glfw/glfw#415]
How do I disable double buffering, ie: I want to draw directly to the frontbuffer with minimal latency?

I tried glfwWindowHint( GLFW_DOUBLEBUFFER,GL_FALSE ) but ended up with no display output at all - ie: just a black screen.

Also added glDrawBuffer( GL_FRONT )/glReadBuffer( GL_FRONT ) just in case but with no luck.

I'm using Windows 7 + nVidia GTX460 + latest glfw on github.

**Comment by elmindreda** [comment]
That is the correct hint. You don't need to change any buffers, but replace `glfwSwapBuffers` with `glFlush` or `glFinish`.

**Comment by blitz-research** [comment]
Thanks - changing glfwSwapBuffers to glFlush did the trick.

Only problem now is lack of vsync - I was kind of hoping swapbuffers would
(only) do vsync. There's probably nothing I can do about this I guess.

**Comment by elmindreda** [comment]
If you're going to wait for vsync then you might as well use double buffering.

**Comment by blitz-research** [comment]
Well, it's for a oculus rift vr app, and one of the goals with vr is to reduce the time between when the headset orientation is sampled (by the cpu) and when the results end up on the screen as much as possible. Double buffering adds a 16ms lag, which is OK but not ideal.

But I suspect I need to be exploring ovr's 'direct mode' instead, which sounds like it's basically single buffering but properly synced - more info here: http://doc-ok.org/?p=1057

This actually mentions a GL extension (GLX_SGI_video_sync) that can be used to wait for sync, so I can also have a play with that.

**Comment by elmindreda** [comment]
Yes, direct mode is the correct solution.
