### ISSUE TITLE
Secondary Monitor Position

### ISSUE THREAD

**Issue by Cooldude234** [glfw/glfw#417]
I am trying to center the window on my second monitor (not the primary one).
So initially I decided to get the size of the first monitor and then add to that half the width of the second one to find its center. But I realized this wasn't going to work when I remembered I moved the monitors position within windows so that it could be centered with my primary one.

The issue caused by this means that when I set the position of my window I have no way of indicating where the second monitor (or others) are; so what ends up happening is I move the window into the void of screen space (it went off screen to the point I couldn't see it).

And to take this further I realized that I couldn't even have my application figure out if another monitor was to the right or left, or even up or down. Now I was planning on implementing an options menu for multiple monitors and letting the user decide all of that but for one of my projects I was hoping to have my application do this automatically.

So is there a way to achieve this with the current version of GLFW or should I hope for an implementation (if its even possible) of some-sort of monitor position state/parameter?
(P.S I did do some searching on this topic but didn't find anything relating to GLFW so sorry in advanced if I missed anything and or posting something someone already has)

**Comment by elmindreda** [comment]
Set the window position to the monitor position plus half the monitor resolution minus half the window size.

**Comment by Cooldude234** [comment]
but should the application know the monitors position? Is there something I am missing?

**Comment by shurcooL** [comment]
It appears that you should be able to get the monitors position with `glfwGetMonitorPos`:

http://www.glfw.org/docs/latest/group__monitor.html#ga102f54e7acc9149edbcf0997152df8c9

**Comment by Cooldude234** [comment]
Thank you, but weird, when I tried searching for it it never came up anywhere.
Thanks again!

**Comment by Cooldude234** [comment]
I see, apparently the doxygen's search engine is word specific. Would have been nice if it had some sort of tag functionality for search reasons.
