### ISSUE TITLE
Native access functions

### ISSUE THREAD

**Issue by elmindreda** [glfw/glfw#419]
The native API lacks functions for Wayland and Mir.

**Comment by elmindreda** [comment]
@jadahl Do the Wayland parts of 5f2a32cff4e770376776600f939847d90b6c5417 look sane?

**Comment by elmindreda** [comment]
@BrandonSchaefer Do the Mir parts of 5f2a32cff4e770376776600f939847d90b6c5417 look sane?

**Comment by jadahl** [comment]
Yes, looks reasonable. Though, note that one "window" may potentially consist of multiple wl_surface's (for example YUV video frame with RGBA controls), so it could be good to clarify that its the "main" wl_surface.

**Comment by BrandonSchaefer** [comment]
Yup looks good to me
