### ISSUE TITLE
Shared context framebuffer size calculation question

### ISSUE THREAD

**Issue by imaginationcoin** [glfw/glfw#421]
Hello there!

With the release of 3.1.0 coming up fast I am eager to have my questions heard!

My situation:

I have two monitors, therefore a three or more monitor scenario is not being taken into account.

My program starts with two windows sharing the same context, both at a resolution of 640x480px, the contexts are shown full screen, by default the desktops on both monitors are set to high resolution.

The framebuffer matches the size of the two desktops at their original size.

Because of the low resolution fullscreen, combined with the high desktop resolutions, there is a large gap between both glfw windows.

A screen grab shows that the left screen is rendered to the top left of the framebuffer, and the right to the lower right of the frame buffer.

When I move the cursor from one screen to the other, it takes a very long time to move the cursor from one to the other due to the vortex inbetween.

My questions are; is this a cause for concern? can this be tackled before the upcoming release? do I have to use seperate contexts and load the data twice to work around? should I just stick to using the same resolutions that the monitors are set to?

I intend on using all monitors or just that of one screen, which interestingly I noticed then initializes a frame buffer the size of both desktops combined unless seperate contexts are used. However I intended on testing provision for additional configurations.

My guess is that it is either not simple to resize, or this functionality is to avoid creating a lot of work to have the framebuffer resize dynamically.

I am unsure what would happen in a three monitor scenario with windows loaded on the opposite two.

If someone wants to buy me one I will test it, hint hint ;-)

Thank you all glfw is fantastic and youre making a superb framework that I am fully enjoying learning and using.

**Comment by imaginationcoin** [comment]
I have found that during a render to texture procedure the framebuffer has to be disposed of as it cannot be resized, and then recreated at the correct resolution, maybe this is what is needed here, taking into account any change of the frame buffer id.

**Comment by imaginationcoin** [comment]
This was added to 3.2 then removed, did it become to much of a problem when you looked into it?

**Comment by elmindreda** [comment]
There is no bug here.

GLFW does not support moving monitor viewports and likely never will. If you are making a multi-monitor application, I would recommend that you not change any resolutions. In fact, I would recommend that even for single-monitor applications. If you want to render at lower resolutions, use framebuffer objects.

**Comment by imaginationcoin** [comment]
Thankyou for the advice.
