### ISSUE TITLE
Low resolution titlebar on Retina Macs on 10.10

### ISSUE THREAD

**Issue by floooh** [glfw/glfw#422]
I just bought a 13" Retina Mac and noticed that GLFW-created windows have a low-resolution titlebar (the window buttons in the top left corner and the window title text). The GLFW_USE_RETINA cmake flag is on, but I think this only affects the GL rendering surface (but on the screenshot it looks like the rendering is also low resolution, the _GLFW_USE_RETINA flag is definitely set though and in the debugger the setWantsBestResolution code path is taken):

```cpp
#if defined(_GLFW_USE_RETINA)
#if MAC_OS_X_VERSION_MAX_ALLOWED >= 1070
    if (floor(NSAppKitVersionNumber) > NSAppKitVersionNumber10_6)
        [window->ns.view setWantsBestResolutionOpenGLSurface:YES];
#endif /*MAC_OS_X_VERSION_MAX_ALLOWED*/
#endif /*_GLFW_USE_RETINA*/
```

![lowres-titlebar-osx](https://cloud.githubusercontent.com/assets/1699414/5793193/679a7b4e-9f3b-11e4-923c-a1e53cf6230e.png)

**Comment by shurcooL** [comment]
Since this is an app bundle, I know it's possible to fix this problem by adding:

```XML
<key>NSHighResolutionCapable</key>
<true/>
```

To the app bundle's `Info.plist` file (located at `*.app/Contents/Info.plist` path).

In fact, I do not know of any other way except doing that. If you don't include that, the app may or may not get treated as HiDPI-capable, which results in low resolution window decorations, etc.

If someone knows an alternative, feel free to share.

**Comment by elmindreda** [comment]
What @shurcooL said.

I will add a better plist template for the next release.

**Comment by floooh** [comment]
Thanks that worked! It's explained in the lower half of this page: https://developer.apple.com/library/mac/documentation/GraphicsAnimation/Conceptual/HighResolutionOSX/Explained/Explained.html#//apple_ref/doc/uid/TP40012302-CH4-SW10

**Comment by elmindreda** [comment]
Was this a change from 10.9 or has it always worked this way? I can't recall anyone mentioning this before 10.10 was released.

**Comment by FelikZ** [comment]
If someone will end up here using search. This indeed fixes an issue but if does not for you, try to change application path. It appears that OSX caching plist partially. After I moved app to a /tmp (for testing) the option have applied.
Have fun.

**Comment by cblc** [comment]
FWIW: SDL can do this programmatically on MacOS, with the SDL_WINDOW_ALLOW_HIGHDPI flag. And it works, you get the window in hidpi mode or in normal mode depending on whether you set that flag or not, no matter if you don't even have a plist.

**Comment by elmindreda** [comment]
@cblc Does this not work for you with [GLFW_SCALE_FRAMEBUFFER](https://www.glfw.org/docs/3.4/window#GLFW_SCALE_FRAMEBUFFER_hint)? At a glance, SDL seems to do the same thing.

**Comment by cblc** [comment]
> @cblc Does this not work for you with [GLFW_SCALE_FRAMEBUFFER](https://www.glfw.org/docs/3.4/window#GLFW_SCALE_FRAMEBUFFER_hint)? At a glance, SDL seems to do the same thing.

Oh, I thought that was just related to how resize callbacks behave, not to the actual resolution of the created window...
