### ISSUE TITLE
Window live resizing example

### ISSUE THREAD

**Issue by TuomLarsen** [glfw/glfw#424]
The issue tracker lists several instances of problematic repaint when the window gets resized (#1, #185, #408). You mentioned that the way around this is to use "window size or refresh callbacks".

Please, could you provide a canonical example which keeps the window updated even during resizing?

**Comment by elmindreda** [comment]
Yup, absolutely.

**Comment by TuomLarsen** [comment]
Thank you very much! It works like a charm on my 10.9.

PS: What is difference between `framebufferSizeFun` and `windowRefreshFun` with respect to the resizing of windows? Am I assuming correctly, that they both get called on resize so it doesn't really matter which on does the redrawing?

**Comment by tombsar** [comment]
> What is difference between framebufferSizeFun and windowRefreshFun with respect to the resizing of windows?

In some circumstances the window or framebuffer sizes can change independently. From the glfw docs (http://www.glfw.org/docs/latest/window.html#window_fbsize):

> The size of a framebuffer may change independently of the size of a window, for example if the window is dragged between a regular monitor and a high-DPI one.

**Comment by elmindreda** [comment]
The refresh callback is called whenever the client area needs to be redrawn. There are events other than resizing that leads to that, especially (but not only) on non-compositing window systems.

**Comment by elmindreda** [comment]
What I meant to say is yes, they both get called on resize, but the refresh callback is the one intended for redrawing on demand regardless of the reason for content damage.
