### ISSUE TITLE
Fluxbox claims to support _NET_REQUEST_FRAME_EXTENTS

### ISSUE THREAD

**Issue by alekseyrybalkin** [glfw/glfw#425]
After upgrading to glfw 3.1 my programs (see minimal example below) just hang on glfwCreateWindow. Git bisect shows [this commit](https://github.com/glfw/glfw/commit/0c58df06d507) as the first bad commit. My guess this happens because [fluxbox](http://fluxbox.org/) does not support _NET_REQUEST_FRAME_EXTENTS ( http://fluxbox.sourceforge.net/docs/ewmh-support.html )

The same happens on git master.

program example:
```c++
#include <GLFW/glfw3.h>
int main() {
    glfwInit();
    glfwCreateWindow(640, 480, "OpenGL", glfwGetPrimaryMonitor(), nullptr);
    glfwTerminate();
}
```

**Comment by elmindreda** [comment]
If a WM doesn't support _NET_REQUEST_FRAME_EXTENTS then it isn't used, unless it claims to support it and then doesn't. What is the output of `xprop -root`?

**Comment by alekseyrybalkin** [comment]
Output is as follows, and _NET_REQUEST_FRAME_EXTENTS is in _NET_SUPPORTED(ATOM) array, so I guess it claims the support:
```
$ xprop -root
_NET_ACTIVE_WINDOW(WINDOW): window id # 0x800006
_NET_WORKAREA(CARDINAL) = 0, 0, 1366, 768, 0, 0, 1366, 768, 0, 0, 1366, 768, 0, 0, 1366, 768, 0, 0, 1366, 768
_NET_DESKTOP_GEOMETRY(CARDINAL) = 1366, 768
_NET_DESKTOP_VIEWPORT(CARDINAL) = 0, 0
_NET_CLIENT_LIST_STACKING(WINDOW): window id # 0x800006, 0xa00006, 0xe0007c
_NET_CLIENT_LIST(WINDOW): window id # 0x800006, 0xa00006, 0xe0007c
_NET_DESKTOP_NAMES(UTF8_STRING) = "Workspace 1", "Workspace 2", "Workspace 3", "Workspace 4", "Workspace 5"
_NET_CURRENT_DESKTOP(CARDINAL) = 1
_NET_NUMBER_OF_DESKTOPS(CARDINAL) = 5
_NET_SUPPORTED(ATOM) = _NET_WM_STRUT, _NET_WM_STATE, _NET_WM_NAME, _NET_WM_ICON, _NET_WM_ICON_NAME, _NET_WM_STATE_STICKY, _NET_WM_STATE_SHADED, _NET_WM_STATE_MAXIMIZED_HORZ, _NET_WM_STATE_MAXIMIZED_VERT, _NET_WM_STATE_FULLSCREEN, _NET_WM_STATE_HIDDEN, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_MODAL, _NET_WM_STATE_BELOW, _NET_WM_STATE_ABOVE, _NET_WM_STATE_DEMANDS_ATTENTION, _NET_WM_WINDOW_TYPE, _NET_WM_WINDOW_TYPE_DOCK, _NET_WM_WINDOW_TYPE_DESKTOP, _NET_WM_WINDOW_TYPE_SPLASH, _NET_WM_WINDOW_TYPE_DIALOG, _NET_WM_WINDOW_TYPE_MENU, _NET_WM_WINDOW_TYPE_TOOLBAR, _NET_WM_WINDOW_TYPE_NORMAL, _NET_WM_ALLOWED_ACTIONS, _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_SHADE, _NET_WM_ACTION_STICK, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_CLOSE, _NET_CLIENT_LIST, _NET_CLIENT_LIST_STACKING, _NET_NUMBER_OF_DESKTOPS, _NET_CURRENT_DESKTOP, _NET_ACTIVE_WINDOW, _NET_CLOSE_WINDOW, _NET_MOVERESIZE_WINDOW, _NET_WORKAREA, _NET_RESTACK_WINDOW, _NET_REQUEST_FRAME_EXTENTS, _NET_WM_MOVERESIZE, _NET_FRAME_EXTENTS, _NET_WM_DESKTOP, _NET_DESKTOP_NAMES, _NET_DESKTOP_VIEWPORT, _NET_DESKTOP_GEOMETRY, _NET_SUPPORTING_WM_CHECK
_NET_SUPPORTING_WM_CHECK(WINDOW): window id # 0x400026
ESETROOT_PMAP_ID(PIXMAP): pixmap id # 0x600003
_XROOTPMAP_ID(PIXMAP): pixmap id # 0x600003
_BLACKBOX_PID(CARDINAL) = 11941
_XKB_RULES_NAMES(STRING) = "evdev", "pc104", "us,ru", "", "grp:caps_toggle,grp_led:caps,terminate:ctrl_alt_bksp"
XFree86_has_VT(INTEGER) = 1
XFree86_VT(INTEGER) = 1
```

**Comment by elmindreda** [comment]
That's two WMs that fail to implement it (the first was Unity). I'll write a workaround.

**Comment by elmindreda** [comment]
What version of Fluxbox is this and is it an actual release or a snapshot that some package manager grabbed?

**Comment by alekseyrybalkin** [comment]
This is fluxbox 1.3.6 built from official tarball located at http://downloads.sourceforge.net/fluxbox/fluxbox-1.3.6.tar.bz2

**Comment by elmindreda** [comment]
Not sure what's wrong. At first glance their code looks fine.

**Comment by alekseyrybalkin** [comment]
Yeah, looks like they actually implement it. Okay, I'll try to debug this issue more closely today/tomorrow and will report back.

**Comment by alekseyrybalkin** [comment]
This is most probably fluxbox issue.

I tested with jwm in the same environment and jwm claims to support and actually supports _NET_REQUEST_FRAME_EXTENTS and everything works fine with glfw 3.1, except glfwSetInputMode(window, GLFW_CURSOR, GLFW_CURSOR_HIDDEN); does not work, but this is another issue with 3.1 (I saw it in fluxbox too after hacking it to not claim support for _NET_REQUEST_FRAME_EXTENTS).

So this issue is fluxbox bug, I'll file the bug to fluxbox-devel. This issue can be closed I think.

**Comment by elmindreda** [comment]
Is the issue with disabled cursor mode continuous motion?

**Comment by mgumz** [comment]
@alekseyrybalkin do you file bugs regularly to mailing-lists? or rather to bug-trackers? :)

https://sourceforge.net/p/fluxbox/bugs/?source=navbar

**Comment by alekseyrybalkin** [comment]
@mgumz I am lazy one, I didn't have sourceforge account (which is needed for filing bugs) and I saw the description of the mailing-list which said "Here the development takes place. Send bugs, patches and related stuff over here" and I just did what it said taking the short path :-)

**Comment by alekseyrybalkin** [comment]
@elmindreda no, the issue is that the mouse cursor does not hide itself, the arrow is visible.

**Comment by elmindreda** [comment]
The Unity WM had a bug in their implementation as well (#368).

**Comment by mgumz** [comment]
ok, https://sourceforge.net/p/fluxbox/bugs/1121/ contains a fix for fluxbox. can you please try and report back?

**Comment by alekseyrybalkin** [comment]
I confirm that the fix resolves the issue for fluxbox. Thanks.

**Comment by alekseyrybalkin** [comment]
I see the issue with cursor was already reported in #309 so this one can be closed.
