### ISSUE TITLE
Cursor images: Pre-multiplied alpha?

### ISSUE THREAD

**Issue by slimsag** [glfw/glfw#426]
Hi, the docs on [custom cursor objects](http://www.glfw.org/docs/3.1/input.html#cursor_object) say:

> The image data is 32-bit RGBA, i.e. eight bits per channel. The pixels are arranged canonically as sequential rows, starting from the top-left corner.

Just to be clear, that is pre-multiplied alpha, yes?

**Comment by shurcooL** [comment]
Whether it's premultiplied or not seems to be completely unspecified; that sounds like an issue.

**Comment by elmindreda** [comment]
You specify non-premultiplied alpha data, as can be seen with the animated cursor in the `cursor` test.
