### ISSUE TITLE
Window mode switching

### ISSUE THREAD

**Issue by elmindreda** [glfw/glfw#43]

**Comment by theagentd** [comment]
Is there an ETA on this? It's an important feature for us.

**Comment by elmindreda** [comment]
@theagentd I'm sorry, I can't give an ETA, but I will help if I can. What is the time frame of your need? I'm about to release 3.1.2 and this is one of the first things I will tackle after that.

**Comment by theagentd** [comment]
It's not extremely urgent, but within one or two months would be great so we can bug-test and integrate the functionality into our engine and menu system. We're working on some big rewrites/library switched right now.

**Comment by CreamyCookie** [comment]
@elmindreda Does this restore the window on the monitor it was previously on? I'm currently having a problem in LibGDX where after going from fullscreen to windowed, the window ends up on the primary monitor instead of the one it was before.

**Comment by elmindreda** [comment]
@CreamyCookie It places the window where you specify.

**Comment by CreamyCookie** [comment]
@elmindreda Oh.. true. I should have seen that. It depends on the xpos and ypos, right?

And LibGDX does this when going from fullscreen to windowed.

```java
Lwjgl3DisplayMode currentMode = (Lwjgl3DisplayMode) getDisplayMode();
int windowPosX = (currentMode.width - width) / 2;
int windowPosY = (currentMode.height - height) / 2;
GLFW.glfwSetWindowMonitor(window.getWindowHandle(), 0,
		windowPosX, windowPosY, width, height, currentMode.refreshRate);
```

Now, I think they did that because they didn't know what the windowPosX (and Y) was before it was set to fullscreen.. Is there a way to get that from GLFW? Or should they just store the position it was before setting it to fullscreen?

**Comment by elmindreda** [comment]
@CreamyCookie You need to save it if you want to restore it.

**Comment by CreamyCookie** [comment]
@elmindreda Thank you!
