### ISSUE TITLE
Random pixels appear in cursor image that change intermittently that are not there when rendered as a texture, also loading last GLFWimage loaded instead of image provided.

### ISSUE THREAD

**Issue by imaginationcoin** [glfw/glfw#435]
I managed to get libpng to load an image which looks fine when rendered as a texture.

If I convert the image to GLFWimage using the following code, random pixels appear distored intermittently when ever the image is used as a cursor.

GLFWimage CursorManager::LoadImageFromFile(string filename)
{
    FILE* file = fopen(filename.c_str(), "rb");
    unsigned int width = 0;
    unsigned int height = 0;
    unsigned char* buffer = NULL;
    int error = png_rgba_load(file,&width,&height,&buffer);
    if(error == 0)
    {
        GLFWimage image;
        unsigned char pixels[width * height * 4];
        memcpy(pixels, buffer, sizeof(pixels));
        image.width = width;
        image.height = height;
        image.pixels = pixels;
        return image;
    }
    fclose(file);
}

I will try to achieve uploading a screen shot but like I say its different any time, and I am kind of hoping you may have an idea as to whats going wrong, as like I say the image renders fine as a texture leaving me to believe the problem may be with some internal processing or something.

Also when I save a group of GLFWimage for my different cursors, then attempt to apply one using
cur = glfwCreateCursor(&theglfwimage,0,0);

it does not load the image provided, it sets the cursor to the last GLFWimage to be created.

http://stackoverflow.com/questions/28132285/c-glfwimage-via-libpng

**Comment by arampl** [comment]
Try my function:

~~~~~~~
GLFWcursor* createcursor(char *filename)
{
	GLFWimage *image;

	FILE *file = fopen(filename, "rb");
	png_structp png_ptr = png_create_read_struct(PNG_LIBPNG_VER_STRING, NULL, NULL, NULL);
	png_infop info_ptr = png_create_info_struct(png_ptr);
	png_init_io(png_ptr, file);

	png_bytepp row_pointers;
	int bit_depth, color_type, interlace_type;

	png_read_info(png_ptr, info_ptr);
	png_get_IHDR(png_ptr, info_ptr, (png_uint_32*)&image->width, (png_uint_32*)&image->height, &bit_depth, &color_type, &interlace_type, NULL, NULL);

	row_pointers = (png_bytep*) malloc(sizeof(png_bytep) * height);

	int bits = (color_type == PNG_COLOR_TYPE_RGB) ? 3 : 4;

	image->pixels = (GLubyte*)malloc(image->width * image->height * bits);

	for(int row = 0; row < (int)image->height; row++)
		row_pointers[row] = (png_bytep)(GLubyte*)image->pixels + row * image->width * bits;

	png_read_image(png_ptr, row_pointers);

	fclose(file);

	return glfwCreateCursor(image, 0, 0);
}
~~~~~~~

**Comment by imaginationcoin** [comment]
I get a Segfault using this in c++ once the mallocs are cast.

**Comment by imaginationcoin** [comment]
image.pixels is only storing 16 bytes .. why!?!?

**Comment by imaginationcoin** [comment]
segfault @ row_pointers = (png_bytepp)malloc(sizeof(png_bytep) * image->height);

**Comment by arampl** [comment]
Well, allocate memory with "new" instead of mallocs.
