### ISSUE TITLE
Enhancement proposal: glfwCloneCallbacks(GLFWwindow* dst, GLFWwindow* src)

### ISSUE THREAD

**Issue by wizofoz** [glfw/glfw#438]
I think it would be useful if all the callback pointers of one window could be copied to another one.

This function could be used in different scenarios: for example when the window has to be destroyed and re-created ( fullscreen switching, changing some context attributes etc...) or to make it trivial to share the same callbacks between multiple windows, expecially for game engines built on top of GLFW.

If I'm not wrong actually there is no way to get back a callback pointer ( for ex. glfwGetKeyCallback ).

Thanks for your attention and for this very useful library.

**Comment by elmindreda** [comment]
The callback setter functions return the previously set callback, so there is a way, although perhaps not as convenient as your proposal. However, you usually know what they're set to if you created the original window and it's usually possible to create the new window with the same function.

**Comment by wizofoz** [comment]
Thank you very much for your feedback. I'm using GLFW to handle windows, timing and input devices in my C++ game engine through a layer of abstraction. The engine sets up one or more callback functions of GLFW only when a particular event listener is added to handle that event.  

When I have to destroy the GLFWwindow and recreate it ( for example for fullscreen switching ) I lose all these informations and I have to recalculate all the callbacks that are actually used. 

I know this is a particular case and that it's not the purpose of this library to handle these type of things, thanks again for your feedback and for your great work!
