### ISSUE TITLE
Monitor physical size in Windows 7 and later

### ISSUE THREAD

**Issue by bornskilled200** [glfw/glfw#439]
For Windows 7-8 and maybe XP but Excluding 8.1 GetDeviceCaps do not return the correct values.

There is a way to get the correct values in all versions of Windows albeit in a hacked way. This is documented in the sites below using C++.

http://ofekshilon.com/2011/11/13/reading-monitor-physical-dimensions-or-getting-the-edid-the-right-way/
http://ofekshilon.com/2014/06/19/reading-specific-monitor-dimensions/

I ported the code to C but did not clean it up all the way yet. However because this is a hack and should not be rely to be consistent it would handy to have an option in CMake to enable it.
https://github.com/bornskilled200/dpi

**Comment by theagentd** [comment]
It does not produce correct sizes for me either. It says my monitor is 903x508 mm, but it's closer to 600x340...

**Comment by bornskilled200** [comment]
Well let us get all the facts straight to make sure of everything.

Some things to note, GetDeviceCaps in 8.1 and my current method relies and EDID data from the monitor to give back the correct measurements of the monitor. This is not always reliable.

This was done on an Windows 8.1 machine.

Output from tests/monitors
```
Name: Generic PnP Monitor (primary)
Current mode: 1920 x 1080 x 24 (8 8 8) 60 Hz
Virtual position: 0 0
Physical size: 531 x 299 mm (91.84 dpi)

Name: Generic PnP Monitor (secondary)
Current mode: 1920 x 1080 x 24 (8 8 8) 60 Hz
Virtual position: 1920 0
Physical size: 476 x 268 mm (102.45 dpi)

Name: G215H (Digital) (secondary)
Current mode: 1920 x 1080 x 24 (8 8 8) 60 Hz
Virtual position: -1920 0
Physical size: 477 x 268 mm (102.24 dpi)
```

Output from my hack
```
Generic PnP Monitor: width: 531, height: 299
Generic PnP Monitor: width: 476, height: 268
G215H (Digital): width: 477, height: 268
```

All of this is a neatly in a table

| Windows 8.1 | tests/monitors (mm) | hack (mm) | measured (mm) |
| ---------------- | ------------------------- | -------------- | --------------------- |
| Monitor 1      | 531 x 299                | 531 x 299   | 525 x 300            |
| Monitor 2      | 476 x 268                | 476 x 268   | 475 x 275            |
| Monitor 3      | 477 x 268                | 477 x 268   | 475 x 265            |

In the end I expect these measurements to wildly differ on the other versions of Windows.

**Comment by elmindreda** [comment]
Related to this, please check out the `per-monitor-dpi` branch for an attempt at Windows 8.1 per-monitor DPI support. I don't have a Windows 8.1 machine myself, so any testing would be most appreciated.

**Comment by bornskilled200** [comment]
Got the same result, which is the correct result.
Tested on Windows 8.1

```
Name: Generic PnP Monitor (primary)
Current mode: 1920 x 1080 x 24 (8 8 8) 60 Hz
Virtual position: 0 0
Physical size: 531 x 299 mm (91.84 dpi)

Name: G215H (Digital) (secondary)
Current mode: 1920 x 1080 x 24 (8 8 8) 60 Hz
Virtual position: -1920 0
Physical size: 477 x 268 mm (102.24 dpi)

Name: Generic PnP Monitor (secondary)
Current mode: 1920 x 1080 x 24 (8 8 8) 60 Hz
Virtual position: 1920 0
Physical size: 476 x 268 mm (102.45 dpi)
```
