### ISSUE TITLE
No monitors found on Windows XP guest on VMware

### ISSUE THREAD

**Issue by Harridrone** [glfw/glfw#441]
This is a bit of a trivial issue (and is clearly related to running on a virtual machine) but I thought I would bring it up anyways. After calling glfwInit() on a Windows XP virtual machine the glfw error callback says "No monitors found". This happens before calling any OpenGL or other glfw functions so I believe this is not due to the obvious hardware rendering limitations of using a virtual machine but some problem actually getting the monitor.

**Steps to reproduce:**

Run the following code on a Windows XP virtual machine (vmware):
```
#include "GLFW/glfw3.h"

void error_func(int ec, const char* errStr);

int main(int argc, char *argv[])
{
	GLFWwindow* cWindow;

	glfwSetErrorCallback(error_func);

	if (!glfwInit())
	{
		printf("Failed to initialize GLFW");
	}
}

void error_func(int ec, const char* errStr)
{
	printf("\n %s \n",errStr);
}
```

**Comment by linkerstorm** [comment]
I confirm the same bug on Windows 8 x64 (so not related to VM environment in my case).

Same error message as Harridrone and same steps to reproduce the bug.

If it can help a bit further, after a GetLastError and a FormatMessage, the system error message is "The specified image file did not contain a resource section".

**Comment by linkerstorm** [comment]
To show the problem, following I've extracted and adapted a part of the `_glfwPlatformGetMonitors` (method called on lib init), located in the `win32_monitor.c` source file and made a little console app.

The output on my PC is :

	No display device 0 for adapter 0
	Not active adapter : 1
	Not active adapter : 2
	Not active adapter : 3
	No more adapter : 4

Here is the source :

	#include "windows.h"

	int main(int argc, char const *argv[])
	{
		int size = 0, found = 0;
		DWORD adapterIndex, displayIndex;

		for (adapterIndex = 0;  ;  adapterIndex++)
		{
		    DISPLAY_DEVICEW adapter;

		    ZeroMemory(&adapter, sizeof(DISPLAY_DEVICEW));
		    adapter.cb = sizeof(DISPLAY_DEVICEW);

		    if (!EnumDisplayDevicesW(NULL, adapterIndex, &adapter, 0))
			{
				printf("No more adapter : %i\n", adapterIndex);
				break;
			}

		    if (!(adapter.StateFlags & DISPLAY_DEVICE_ACTIVE))
		    {
				printf("Not active adapter : %i\n", adapterIndex);
		        continue;
		    }

		    for (displayIndex = 0;  ;  displayIndex++)
		    {
		        DISPLAY_DEVICEW display;
		        char* name;
		        HDC dc;

		        ZeroMemory(&display, sizeof(DISPLAY_DEVICEW));
		        display.cb = sizeof(DISPLAY_DEVICEW);

		        if (!EnumDisplayDevicesW(adapter.DeviceName, displayIndex, &display, 0))
	            {
	            	printf("No display device %i for adapter %i\n", displayIndex, adapterIndex);
	            	break;
	            }

		        if (found == size)
		        {
		            size += 4;
		            printf("Monitor found : %i\n", displayIndex);
		        }

		        found++;
		    }
		}

		return 0;
	}

**Comment by linkerstorm** [comment]
And finally, when I use the `EnumDisplayMonitors` WinAPI function ([adapted from this SO question](http://stackoverflow.com/questions/9829083/how-does-windows-assign-display-device-names-eg-display1-and-determine-di)), my unique monitor is well detected with the correct resolution.

The ouput : `Monitor: 00010001 (X,Y): (0,0) (Width, Height): (1920,1080)`

The source :

    #include "windows.h"

        BOOL CALLBACK enumMonitorCallback(
    		HMONITOR hMonitor,
    		HDC hdcMonitor,
    		LPRECT lprcMonitor,
    		LPARAM dwData
    )
    {
        printf("Monitor: %p (X,Y): (%d,%d) (Width, Height): (%d,%d) \n", hMonitor, lprcMonitor->left, lprcMonitor->top, lprcMonitor->right - lprcMonitor->left, lprcMonitor->bottom - lprcMonitor->top);
        return TRUE;
    }

    int main(int argc, TCHAR* argv[], TCHAR* envp[])
    {
        int nRetCode = 0;
        BOOL res = EnumDisplayMonitors(NULL, NULL, enumMonitorCallback, NULL);
        getchar();
        return nRetCode;
    }

**Comment by keithjohnston** [comment]
I'm using VirtualBox on OSX and the free MS virtual machines from here: https://www.modern.ie/en-us/virtualization-tools#downloads. Windows7 and Vista were able to find monitors. XP had the "No monitors found" error as mentioned above.

**Comment by RyanGoat** [comment]
glfwInit() is giving me the same "No Monitors Found" error as above.  My setup is as follows:
Compiler: Visual Studio 2013
VM Guest OS: Windows 7 Ultimate 64 bit
VM Platform: Virtualbox 4.3.24 accelerated 3d enabled
VM Host OD: Debian Linux Jessie w/Nvidia binary graphics driver

**Comment by pushrax** [comment]
Having the same issue in a Server 2012 qemu-kvm VM hooked up with PCI passthrough. The GPU actually has no physical monitors attached, but there is a framebuffer which acts as a virtual monitor. With @linkerstorm's test programs:

EnumDisplayDevicesW:
```
No display device 0 for adapter 0
Not active adapter : 1
Not active adapter : 2
Not active adapter : 3
No more adapter : 4
```

EnumDisplayMonitors:
```
Monitor: 0000000000010001 (X,Y): (0,0) (Width, Height): (1920,1080)
```

**Comment by elmindreda** [comment]
This will have a fix in 3.2.

**Comment by wjakob** [comment]
This issue also occurs on native Windows machines with an improper display setup (https://github.com/wjakob/instant-meshes/issues/13). However, windows and most other applications work just fine in this situation, and it is GLFW that is being extra-picky. It would be nice if the "No monitors found" error message would be a warning rather than causing glfwInit() to fail.

**Comment by elmindreda** [comment]
@wjakob That test was removed in the latest release.
