### ISSUE TITLE
Crash while resizing the application window

### ISSUE THREAD

**Issue by salino** [glfw/glfw#443]
The GLFW application crashes when I resize the window vertically towards to zero. This happens with any example I tried so far.

- OS X Yosemite (10.10.2)
- GLFW master

In cocoa_window.m, line 646ff:

    // From http://cocoadev.com/index.pl?GameKeyboardHandlingAlmost
    // This works around an AppKit bug, where key up events while holding
    // down the command key don't get sent to the key window.
    - (void)sendEvent:(NSEvent *)event
    {
        if ([event type] == NSKeyUp && ([event modifierFlags] & NSCommandKeyMask))
            [[self keyWindow] sendEvent:event];
        else
            [super sendEvent:event]; // <-------------- Thread 1: EXC_BAD_ACCESS
    }

![event](https://cloud.githubusercontent.com/assets/4344802/6201273/7e4115f0-b49f-11e4-8e7b-4e2ca2f47fad.png)
![glfw_error](https://cloud.githubusercontent.com/assets/4344802/6201258/f743843e-b49e-11e4-9677-99f097cc624f.png)

**Comment by jaredjones** [comment]
I can't seem to figure this one out... NSZombieEnabled is turned on and I can't seem to figure out what virtual memory address does not exist that's causing the EXE_BAD_ACCESS. I wouldn't be surprised if the bug is in the Cocoa API somewhere.

**Comment by shurcooL** [comment]
I can confirm this happens.

**Comment by elmindreda** [comment]
If those really are stack frame indices then it's likely that the workaround cited above causes a recursion loop.

**Comment by jaredjones** [comment]
Nope, not a recursion loop. I placed a printf in that method and didn't get any output right before it crashed.

**Comment by jaredjones** [comment]
Left Side: x86 Code of the Crash
Right Side: [NSApplication SendEvent:]; implementation.
![screen shot 2015-04-20 at 2 20 34 pm](https://cloud.githubusercontent.com/assets/1316894/7238503/877e53c0-e768-11e4-8b2b-4a4542cb0ee9.png)

**Comment by elmindreda** [comment]
Please see if the above commit resolves this issue for you.

**Comment by jaredjones** [comment]
It worked. :+1:

**Comment by salino** [comment]
Works for me as well :smile:
