### ISSUE TITLE
Is GLFW_PLATFORM_ERROR really a bug in GLFW / OS ?

### ISSUE THREAD

**Issue by slimsag** [glfw/glfw#450]
We've run into [an issue](https://github.com/go-gl/glfw/issues/127) where we presumed that `GLFW_PLATFORM_ERROR` is a bug in GLFW / OS, as described by [the GLFW Error Code docs](http://www.glfw.org/docs/latest/group__errors.html):

> A platform-specific error occurred that does not match any of the more specific categories.
>
> Analysis
>    A bug in GLFW or the underlying operating system. Report the bug to our issue tracker.

In particular, we've received a `GLFW_PLATFORM_ERROR` due to a strange/non-existent joystick support on a Linux box:

> Linux: Failed to watch for joystick connections in /dev/input: No space left on device

My question boils down to:

- Should `GLFW_PLATFORM_ERROR` only be generated if there is a bug in GLFW or the OS?
  - If so, this is a bug in GLFW / the OS.
- Or does `GLFW_PLATFORM_ERROR` get generated in many more situations (such as a user's invalid system-configuration)?
  - If so, the GLFW docs should probably be updated to reflect this stance more clearly.

**Comment by elmindreda** [comment]
The answer is option two. I will clarify the documentation.
