### ISSUE TITLE
Joystick Effects

### ISSUE THREAD

**Issue by imaginationcoin** [glfw/glfw#452]
This is a long shot, but is anyone willing to work on adding gamepad rumble?

I know that this can be done on windows, and linux (using ioctl) most likley mac too.

Example code for this already:

https://github.com/elanthis/gamepad/blob/master/gamepad.c
http://lxr.free-electrons.com/source/drivers/input/joystick/xpad.c
http://freej.dyne.org/codedoc/joy__ctrl_8cpp_source.html

**Comment by imaginationcoin** [comment]
https://code.google.com/p/safeteleoperation/source/browse/trunk/libjoyrumble-v0.1.3/libjoyrumble.c?spec=svn71&r=71

**Comment by imaginationcoin** [comment]
This might go hand in hand with https://github.com/glfw/glfw/issues/232

**Comment by BryceMehring** [comment]
I believe this is already an issue, #57.

**Comment by elmindreda** [comment]
So it is.
