### ISSUE TITLE
Window icon support

### ISSUE THREAD

**Issue by imaginationcoin** [glfw/glfw#453]
I do hope I am not recreating this issue but I did a search and cannot find another.

It is mentioned on the website documentation however that x11 currently supports no window icon, I would however like to keep a track of the status of this to see its progression.

Is it possible to set the window icon on X11 some how? I see that fluxbox may not be supported.

Usefull link:
http://stackoverflow.com/questions/9634451/how-can-i-change-the-taskbar-icon-using-xiconifywindow

**Comment by elmindreda** [comment]
X11 supports it just fine, but GLFW doesn't.

**Comment by elmindreda** [comment]
Icon support will be added at some point. In the meantime, it is possible to achieve via _NET_WM_ICON and the native API.

**Comment by elmindreda** [comment]
Since there isn't an issue for window icon support yet, I'll hijack this one.
