### ISSUE TITLE
Input redesign

### ISSUE THREAD

**Issue by dv343** [glfw/glfw#455]
I know this would be a very big change on the external interface, but I think that at the end it would be good enought.
My idea is to change the way users prompt for input status. Now, this is achieved by using callbacks(one for each type of input: key callback, mouse button callback, mouse position callback...) and glfwGet* (getKey, getCursor...). My proposal is to unify all input events to just one type, this way all input could be prompted by using something like:
float glfwGetInput(unsigned long code, int mods);
The code paramter will be an identifier of keys, mouse buttons, mouse wheel, joysticks... Each key would have three identifiers, for example: KEY_ESCAPE_PRESS, KEY_ESCAPE_RELEASE and KEY_ESCAPE_PRESSING (the key has been pressed and it is not released). The returning float would be 1.0 if code is KEY_ESCAPE_PRESS and is the key pressed, 0.0 otherwise. For cursor and joysticks the returning float would be the position of the prompted axe.
A getAllInputs function (a function which returns an array of all events) would be very useful too.
I did an input module (a glfw wrapper), which do exactly this and it's only 200 lines long plus a 100 lines long hashmap module, so I think this can be achieved without bloating GLFW.

I think this would be a very good simplification. Moreover, it provides an easy to use interface for a mapping module (ie.: GLFW_KEY_ESCAPE_PRESS => INPUT_EXIT_PROGRAM). That's on my wrapper module too, but I guess that mapping would be considered outside the scope of GLFW.

I don't know a lot of GLFW internals, but I read some of the input system code and I think I could re-write, at least, the X11 module.

**Comment by shurcooL** [comment]
> For cursor and joysticks the returning float would be the position of the prompted axe.

What about the scroll wheel. It has no absolute position, only relative deltas.

Would it return the accumulated relative delta since last query?

Can you link to your wrapper?

**Comment by dv343** [comment]
Would it return the accumulated relative delta since last query?
I think that would be ok.

Can you link to your wrapper?
Yes, I uploaded to github [here](https://github.com/dv343/glfw-input-wrapper-example). It was developed fast and some things are missing, but it works. However, mi idea is more like a rewrite-redesign, not an addition.

**Comment by capnm** [comment]
> KEY_ESCAPE_PRESSING (the key has been pressed and it is not released)

I already tried to implement this in glfw, but unfortunately it seems to be not possible to get
always corresponding press/release events from the window manager reliably. IIRC there was missing release event by loosing/entering window focus, etc.

**Comment by dv343** [comment]
@capnm That cannot be resolved by automatically release all pressed keys in KEY_ESCAPE_PRESSING status when the window loose its focus?

**Comment by capnm** [comment]
Maybe ;-) I couldn't found an universal way, so I ended up implementing this at the app level (a ring buffer + bunch of workarounds).

**Comment by elmindreda** [comment]
I will not be taking the API in this direction, but I'll be happy to point people wishing for such an API to a small library that implements it on top of GLFW. I've done the same for the [event queue](https://github.com/elmindreda/gleq) style.

**Comment by shurcooL** [comment]
> I will not be taking the API in this direction, but I'll be happy to point people wishing for such an API to a small library that implements it on top of GLFW. I've done the same for the [event queue](https://github.com/elmindreda/gleq) style.

That's neat! I've done something similar on top of GLFW too. It converts all inputs to pointers with buttons/axes/sliders and pushes them into one queue. See source [here](https://github.com/shurcooL/Conception-go/blob/73e4105db1ad4aeede4578501f9408a74eaec679/pages/events/main.go#L65-L76).

There's a web version you can try in your browser [here](dmitri.shuralyov.com/projects/events/index.html). Just open the console (before navigating there).

![image](https://cloud.githubusercontent.com/assets/1924134/6657238/a067481a-cb02-11e4-9b9c-5b148a73af41.png)

**Comment by elmindreda** [comment]
@shurcooL That's pretty cool. Seemed to work in Firefox, too.
