### ISSUE TITLE
Dead keys not working

### ISSUE THREAD

**Issue by nether-cat** [glfw/glfw#456]
I did not test this on another platform yet. I am working with OS X SDK 10.10 and GLFW 3.1.0 at the moment. The documentation states that GLFW character callbacks even support composing characters using dead keys. This is not working. Any other characters are working correctly and correspond to the current locale, but the dead keys are being ignored. My key callback though is being called e.g. with the key code GLFW_KEY_WORLD_1 when pressing the dead key on the left hand to '1' and below 'ESC'.

**Comment by elmindreda** [comment]
This is a known bug. OS X is the only affected platform. Will look into this for the next release.

**Comment by jaredjones** [comment]
I'm pretty sure the key he referenced isn't a dead key unless you hold down option with it at the same time.

**Comment by elmindreda** [comment]
The issue is real, though. Dead key character composition does not work on OS X.

**Comment by nether-cat** [comment]
Yep, And furthermore I am pretty sure it is a dead key. I am sorry for leaving the info out, but in my case I was using the German keyboard layout when testing this. There it is a dead key for: ^
