### ISSUE TITLE
Ubuntu 14.10

### ISSUE THREAD

**Issue by imaginationcoin** [glfw/glfw#457]
I updated Ubuntu to Ubuntu 14.10 and glfwCreateWindow does nothing, no window, program still running. I rebuilt 3.1 from source but the problem persists. I know this is proberbly a problem with me upgrading to 14.10 as 3.1 worked previously, but I was wondering if anyone else has experienced this or knows anything about this, and/or can help me to fix this, or has any advice on debugging. I'm not sure if I can roll back. All else on the operating system seems fine but GLFW.

**Comment by imaginationcoin** [comment]
I wonder why there is no glfw error or any exception

**Comment by imaginationcoin** [comment]
I'm using x11 - is this related? https://github.com/glfw/glfw/issues/368

**Comment by arampl** [comment]
Hi, imaginationcoin!

I've recompiled my project on Xubuntu 14.10 (previous version was 13.10) 64-bit. GLFW 3.1 works fine.
Check that you've installed proprietary drivers after installing system (if they are needed). My card is Nvidia GeForce GTX 560Ti, so I installed proprietary nvidia driver (331.113).
Then check what OpenGL version supported by the driver and which context version your project tries to create.

Regards.

**Comment by imaginationcoin** [comment]
ubuntu-drivers devices
== /sys/devices/pci0000:00/0000:00:03.0/0000:02:00.0 ==
model    : GF106M [GeForce GT 445M]
vendor   : NVIDIA Corporation
modalias : pci:v000010DEd00000DD2sv00001028sd0000046Cbc03sc00i00
driver   : xserver-xorg-video-nouveau - distro free builtin
driver   : nvidia-331-updates - distro non-free
driver   : nvidia-304 - distro non-free
driver   : nvidia-331 - distro non-free recommended
driver   : nvidia-304-updates - distro non-free

**Comment by imaginationcoin** [comment]
ubuntu-drivers list
nvidia-304-updates
nvidia-331-updates
nvidia-331
nvidia-304

context version is default

**Comment by imaginationcoin** [comment]
apt-get update; apt-get upgrade; sudo apt-get install nvidia-current
Now I get an error - Xlib:  extension "NV-GLX" missing on display ":0".

**Comment by arampl** [comment]
I don't have "nvidia-current" installed.
331.113 driver was installed through the "Additional drivers" in the "Settings" (Ubuntu must have something similar), not using command line.

And one note. After driver installation there was some error on my system. Solution was to use:

sudo dpkg-reconfigure nvidia-331
then
sudo dpkg-reconfigure nvidia-331-uvm

**Comment by elmindreda** [comment]
It's easy to verify with a debugger if the issue is #368.

Drivers shouldn't matter unless you're requesting a version not supported by that driver. What version are you requesting?

**Comment by Gnomorian** [comment]
if its nothing to do with the driver, i have the same issue, glfwCreateWindow never returns. however im on Manjaro, so a fix from ubuntu probably isnt going to help.

sorry if im hyjacking, i assumed this is the correct place.
