### ISSUE TITLE
What is wrong with www.glfw.org

### ISSUE THREAD

**Issue by Barr-find** [glfw/glfw#459]
Well Your page "http://www.glfw.org/" is not working for couple of days. I wish to get some informations how to build GLFW on Windows 7 64bit using minGW_x86_64 and CodeBlocks IDE or get preBuild binary library for Windows 64bit. I hope You guys and girls are not out of the buissnes are You?

**Comment by Barr-find** [comment]
Well. Page is up and running now so You can close the isue.

**Comment by elmindreda** [comment]
Not sure yet what's going on with it, but this is the repository for the library.

**Comment by elmindreda** [comment]
For anyone reading this, please submit website related issues to the website repository.
