### ISSUE TITLE
ver3.1 GLFWkeyfun called with args: int key, int scancode, int action, int mods

### ISSUE THREAD

**Issue by briantilley** [glfw/glfw#461]
callback for key input has prototype GLFWkeyfun (\*key_callback)(GLFWwindow\*, int, int, int, int), but values printed from the callback indicate window handle is not passed in.

To reproduce, register this callback using glfwSetKeyCallback:

```
void key_callback( GLFWwindow* window, int key, int scancode, int action, int mods )
{
    printf( "[keypress] window: %l key: %d scancode: %d action: %d mods: %d\n", (long)window, key, scancode, action, mods );
}
```

**Comment by elmindreda** [comment]
Does the `events` test work?

**Comment by briantilley** [comment]
`glfwPollEvents()`? Yes, the callback runs on every key event, but the arguments are wrong. `window` receives the `key` value (must be cast from GLFWwindow* to long int), `key` receives the `scancode` value, et cetera.

**Comment by shurcooL** [comment]
What operating system are you running on?

**Comment by elmindreda** [comment]
@briantilley No, the `events` test program.

**Comment by briantilley** [comment]
Ubuntu 14.04, and I configured GLFW to compile with dependencies.

**Comment by briantilley** [comment]
Accidentally closed issue, disregard.

**Comment by briantilley** [comment]
@elmindreda Yes, the events test works properly.

**Comment by elmindreda** [comment]
Then the key callback passes on valid window handles. Otherwise it would segfault.

**Comment by briantilley** [comment]
@elmindreda 

```
void GLviewer::key_callback( GLFWwindow* cb_window, int key, int scancode, int action, int mods )
{
	mods      = action;
	action    = scancode;
	scancode  = key;
	key       = ( long )cb_window;
	cb_window = window;

	printf("[keypress] key: %d scancode: %d action: %d mods: %d\n", key, scancode, action, mods );
}
```

The above function prints key 256 with action 1 when escape is pressed, key 256 action 0 when released, key 256 action 2 when repeated. The code below, under the same conditions, prints key 9, and all actions are printed as 0.

```
void GLviewer::key_callback( GLFWwindow* cb_window, int key, int scancode, int action, int mods )
{
	printf("[keypress] key: %d scancode: %d action: %d mods: %d\n", key, scancode, action, mods );
}
```

**Comment by elmindreda** [comment]
Is that method static?

**Comment by briantilley** [comment]
No, it is not static. The method appears exactly the same in my project.

**Comment by elmindreda** [comment]
Your code is broken because your method is not static. [Use static methods or regular functions as callbacks](http://www.glfw.org/faq.html#how-do-i-use-c-methods-as-callbacks).

**Comment by briantilley** [comment]
Thank you, the behavior does not persist when I declare the callback as static.
