### ISSUE TITLE
virtual key Home reported as numpad 7

### ISSUE THREAD

**Issue by andrewrk** [glfw/glfw#463]
When I press the Home key on my keyboard, which looks like this: http://superjoe.s3.amazonaws.com/blog-files/laptop-review-bonobo-extreme/bonox-keyboard.jpg

GLFW virtual key code is reported as numpad 7. It should be reported as virtual key home. Here is the xev event:

```
KeyPress event, serial 37, synthetic NO, window 0x4800001,
    root 0x28b, subw 0x0, time 74498988, (109,61), root:(816,165),
    state 0x0, keycode 79 (keysym 0xff95, KP_Home), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

This is a bug in SDL as well: https://bugzilla.libsdl.org/show_bug.cgi?id=2876

**Comment by elmindreda** [comment]
You are referring to the *Home* key on the top row?

**Comment by andrewrk** [comment]
From the picture, the Home key on the numpad. It shares space with 7, which is probably why GLFW thinks I'm pressing 7 instead of home.

Now that I am thinking about it again, I wonder if this might be a duplicate of #464

**Comment by elmindreda** [comment]
In that case, yes it is.

**Comment by andrewrk** [comment]
This might be a separate issue. If it's really number 7, then the key should come through as a character with unicode point 55. However it's *not* coming through in the char event, it's coming through as a key event as key 327.

**Comment by elmindreda** [comment]
The physical key counts, according to the scancode provided by the hardware to the OS, as part of the keypad. Whether pressing the key *additionally* generates the codepoint 57 depends on things like NumLock and the current OS keyboard layout.

**Comment by andrewrk** [comment]
Hmm I see - if I turn NumLock on, then GLFW reports a codepoint callback with value 55, which is correct. If I turn NumLock off, then GLFW reports no codepoint callback, and instead reports a key callback with key 327. This is consistent with it being a duplicate of the other issue.
