### ISSUE TITLE
Query for key text

### ISSUE THREAD

**Issue by andrewrk** [glfw/glfw#464]
0. Choose Dvorak keyboard layout
0. Press Ctrl+S in a GLFW window
0. Notice that the key comes in via `glfwSetKeyCallback` as Ctrl+(semicolon)
0. Note that you get no charmods event (`glfwSetCharModsCallback`) so you cannot work around by handling the event via text input

```
andy@andy-bx:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.10
Release:	14.10
Codename:	utopic
```

**Comment by shurcooL** [comment]
Are you looking at the key callback or char callback?

**Comment by andrewrk** [comment]
key callback in step 3 and char mod callback in step 4.

**Comment by elmindreda** [comment]
This is by design. The key callback deals with physical keys and *names them* according to the US layout. Each key token corresponds to a location on the keyboard, not to where (if anywhere) that symbol is placed by the current layout.

**Comment by elmindreda** [comment]
This is the gap that `glfwGetKeyText` is meant to fill.

**Comment by andrewrk** [comment]
Yes we talked about this on IRC, I hope it's okay that I made an issue to track progress.

**Comment by andrewrk** [comment]
May I nominate this for 3.2 milestone?

**Comment by elmindreda** [comment]
It's already on my shortlist.

**Comment by shurcooL** [comment]
Is `glfwGetKeyText` described anywhere? What gap/problem exactly is it meant to solve?

I am unable to see a problem from what has been described in this issue so far, can you please elaborate on what you're trying to achieve @andrewrk?

**Comment by elmindreda** [comment]
Not really, but here's the idea:
```c
const char* glfwGetKeyText(int key, int scancode)
```

It returns a UTF-8 encoded string of what the specified *printable* key produces with the current keyboard layout with no modifier keys used. This lets the application explain key bindings to users.

If the key is `GLFW_KEY_UNKNOWN` then the scancode is used, otherwise it's ignored.

For non-printable keys, there's a choice to be made because Windows provides localized strings for these, Xkb can probably be coaxed to provide English language ones and OS X doesn't provide anything for them. Thus either GLFW comes with its own strings or the function returns `NULL`.

**Comment by andrewrk** [comment]
https://github.com/andrewrk/genesis/issues/2
https://github.com/andrewrk/genesis/issues/1

can't fix these bugs without this feature.

**Comment by shurcooL** [comment]
> It returns a UTF-8 encoded string of what the specified printable key produces with the current keyboard layout with no modifier keys used. This lets the application explain key bindings to users.

I see, that sounds helpful. Thanks for explaining!

**Comment by Extrawurst** [comment]
so in a onKey callback i can `glfwGetKeyText(key, scancode)` and it would return "z" for the key that is labeled as "z" on my given keyboard (assuming the layout matches the settings in my OS) no matter if a QWERTZ, QWERTY or AZERTY (or whatever there is) keyboard is built in ? cause thats a problem right now ? on my win32 machine with a german keyboard glfw returns the enum value of the y-key when pressing the z-key...

**Comment by Extrawurst** [comment]
would this function allocate or where do these strings it returns come from ?

**Comment by elmindreda** [comment]
> so in a onKey callback i can glfwGetKeyText(key, scancode) and it would return "z" for the key that is labeled as "z" on my given keyboard (assuming the layout matches the settings in my OS) no matter if a QWERTZ, QWERTY or AZERTY (or whatever there is) keyboard is built in ?

Yes.

> would this function allocate or where do these strings it returns come from ?

They are queried from the OS.

**Comment by Extrawurst** [comment]
@elmindreda wow ok that is nice, when is 3.2 release due ? ^^

**Comment by elmindreda** [comment]
When it's done.

**Comment by elmindreda** [comment]
There's a sketch in `devel` now. No OS X support yet.

**Comment by Extrawurst** [comment]
Too bad, I am on osx. I will test once this is in.

**Comment by elmindreda** [comment]
It's coming. I just haven't had Mac access the past few days.

**Comment by Extrawurst** [comment]
great to see this get worked on, take your time. awesome work - thank you!

**Comment by elmindreda** [comment]
There is now code sane enough for testing in the `keyname` branch. It supports Windows, X11 and OS X.

**Comment by andrewrk** [comment]
I tested this with Xfce and X11 just now. It's looking good and it will solve one bug that I have. However, I still have issue #463. 

The events for that key with no modifiers look like this. The expected value for the key is "Home".

```
00000031 to 1 at 39.281: Key 0x0147 Scancode 0x004f (KEYPAD 7) (with no mods) was pressed
00000032 to 1 at 39.372: Key 0x0147 Scancode 0x004f (KEYPAD 7) (with no mods) was released
```

If I turn NumLock on, and then press it with no modifiers:

```
0000000f to 1 at 7.519: Key 0x0147 Scancode 0x004f (KEYPAD 7) (with no mods) was pressed
00000010 to 1 at 7.519: Character 0x00000037 (7) with modifiers (with no mods) input
00000011 to 1 at 7.519: Character 0x00000037 (7) input
00000012 to 1 at 7.716: Key 0x0147 Scancode 0x004f (KEYPAD 7) (with no mods) was released
```

When NumLock is off, that key is supposed to act as Home key. With NumLock on, it is supposed to be key pad 7. NumLock off behavior is incorrect; NumLock on behavior is correct.

When I press the key with NumLock off in xev, this is what I get:

```
KeyPress event, serial 37, synthetic NO, window 0x2c00001,
    root 0x28b, subw 0x0, time 1098862949, (428,302), root:(1299,744),
    state 0x0, keycode 79 (keysym 0xff95, KP_Home), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x2c00001,
    root 0x28b, subw 0x0, time 1098863147, (428,302), root:(1299,744),
    state 0x0, keycode 79 (keysym 0xff95, KP_Home), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

When I press the key with NumLock on in xev, I get:

```
KeyPress event, serial 37, synthetic NO, window 0x2c00001,
    root 0x28b, subw 0x0, time 1098907559, (504,204), root:(1375,646),
    state 0x10, keycode 79 (keysym 0xffb7, KP_7), same_screen YES,
    XLookupString gives 1 bytes: (37) "7"
    XmbLookupString gives 1 bytes: (37) "7"
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x2c00001,
    root 0x28b, subw 0x0, time 1098907725, (504,204), root:(1375,646),
    state 0x10, keycode 79 (keysym 0xffb7, KP_7), same_screen YES,
    XLookupString gives 1 bytes: (37) "7"
    XFilterEvent returns: False
```

**Comment by andrewrk** [comment]
Another problem. If I perform `Ctrl+A`, it looks like this:

```
00000004 to 1 at 0.479: Key 0x0155 Scancode 0x0025 (LEFT CONTROL) (with no mods) was pressed
00000005 to 1 at 0.690: Key 0x0041 Scancode 0x0026 (A) (a) (with control) was pressed
00000006 to 1 at 0.832: Key 0x0041 Scancode 0x0026 (A) (a) (with control) was released
00000007 to 1 at 1.123: Key 0x0155 Scancode 0x0025 (LEFT CONTROL) (with control) was released
```

So far so good. If I perform `Ctrl+Period` on my dvorak keyboard layout, I get this:

```
000000c9 to 1 at 234.469: Key 0x0155 Scancode 0x0025 (LEFT CONTROL) (with no mods) was pressed
000000ca to 1 at 234.896: Key 0x0045 Scancode 0x001a (E) (.) (with control) was pressed
000000cb to 1 at 234.896: Character 0x0000002e (.) with modifiers (with control) input
000000cc to 1 at 235.039: Key 0x0045 Scancode 0x001a (E) (.) (with control) was released
000000cd to 1 at 235.329: Key 0x0155 Scancode 0x0025 (LEFT CONTROL) (with control) was released
```

The character event is unexpected. Note that `Ctrl+A` did not produce character events.

For reference if I just press Period, these are the (correct) events:

```
000000c3 to 1 at 226.963: Key 0x0045 Scancode 0x001a (E) (.) (with no mods) was pressed
000000c4 to 1 at 226.963: Character 0x0000002e (.) with modifiers (with no mods) input
000000c5 to 1 at 226.963: Character 0x0000002e (.) input
000000c6 to 1 at 227.195: Key 0x0045 Scancode 0x001a (E) (.) (with no mods) was released
```

This might be a separate issue. I noticed that when I switched to QWERTY layout, Ctrl+Period still produced a character event. I also noticed that `(`, `)`, `[`, and `]` all produced character events in addition to key events, same as period, when pressed with Control.

xev gives this output when pressing Ctrl+Period on dvorak:

```
KeyPress event, serial 37, synthetic NO, window 0x3400001,
    root 0x28b, subw 0x0, time 1099834984, (69,-9), root:(825,76),
    state 0x0, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 37, synthetic NO, window 0x3400001,
    root 0x28b, subw 0x0, time 1099836226, (69,-9), root:(825,76),
    state 0x4, keycode 26 (keysym 0x2e, period), same_screen YES,
    XLookupString gives 1 bytes: (2e) "."
    XmbLookupString gives 1 bytes: (2e) "."
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x3400001,
    root 0x28b, subw 0x0, time 1099836328, (69,-9), root:(825,76),
    state 0x4, keycode 26 (keysym 0x2e, period), same_screen YES,
    XLookupString gives 1 bytes: (2e) "."
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x3400001,
    root 0x28b, subw 0x0, time 1099836508, (69,-9), root:(825,76),
    state 0x4, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

**Comment by elmindreda** [comment]
> The events for that key with no modifiers look like this. The expected value for the key is "Home".

The key callback is concerned only with physical keys, not their values, as this is what makes sense for most games. `GLFW_KEY_HOME` is a separate physical key from `GLFW_KEY_KP_7` and is the same key regardless of layout, indicator state or modifier state.

    000000cb to 1 at 234.896: Character 0x0000002e (.) with modifiers (with control) input

That is a charmods event, not a regular character event. The charmods callback by design passes along any character the text input system provides.

**Comment by andrewrk** [comment]
> The key callback is concerned only with physical keys, not their values, as this is what makes sense for most games. GLFW_KEY_HOME is a separate physical key from GLFW_KEY_KP_7 and is the same key regardless of layout, indicator state or modifier state.

xev knows that I pressed home. GLFW does not expose this information. I think this is a problem with GLFW's API. Other applications on this desktop respect this home key; an application using GLFW should as well.

**Comment by elmindreda** [comment]
Yep, that's a limitation of the current API, because of its focus on games. May add a lock key state query to fill that gap.

**Comment by elmindreda** [comment]
Still remaining is re-acquiring keyboard layout data on `kTISNotifySelectedKeyboardInputSourceChanged`.

**Comment by andrewrk** [comment]
Are there issues to track these two missing features?

**Comment by elmindreda** [comment]
@andrewrk Nope. Is key lock state query something you would want?

**Comment by andrewrk** [comment]
If key lock state query is what enables my application to make all the keyboard buttons work correctly like they do for the rest of the applications on my system, then yes, key lock state query is part of my application's requirements.

**Comment by elmindreda** [comment]
@andrewrk Sorry, what I should have said was: would that feature be useful and sufficient for your needs?

**Comment by elmindreda** [comment]
I.e. something like

```c
int glfwLockKeyOn(GLFWwindow* window, int key);
```

where `key` may be `GLFW_KEY_CAPS_LOCK`,  `GLFW_KEY_NUM_LOCK` or `GLFW_KEY_SCROLL_LOCK` and the return value `GLFW_TRUE` or `GLFW_FALSE`.

I haven't added an issue for this because I haven't yet checked whether it's possible to implement in a sane way on all platforms.

**Comment by andrewrk** [comment]
I don't think that would help. Here's my keyboard:

![](http://superjoe.s3.amazonaws.com/blog-files/laptop-review-bonobo-extreme/bonox-keyboard.jpg)

See the numpad 7 key? It also has home on it. On this keyboard, and other keyboards, a key like that is the only realistic way to press Home, End, Page Up, and Page Down with one hand.

I don't really care about numpad state; I just want to be able to detect when home is pressed. As I pointed out, query for key text is not able to provide this detection, and xev does detect this key correctly. So GLFW should be able to provide this detection as well.

If I queried lock key state, that might let me put a workaround hack for a single keyboard, but I don't want a workaround hack for a single keyboard; I want a general solution that works for all keyboards that x11 detects correctly.

**Comment by Hanprogramer** [comment]
Still have this issue. 

> I don't think that would help. Here's my keyboard:
> 
> ![](https://camo.githubusercontent.com/0ce36e6ad027e564b5c6a3f40b5017bb67bd98723a0d96b1e59bf9ee4fbefcff/687474703a2f2f73757065726a6f652e73332e616d617a6f6e6177732e636f6d2f626c6f672d66696c65732f6c6170746f702d7265766965772d626f6e6f626f2d65787472656d652f626f6e6f782d6b6579626f6172642e6a7067)
> 
> See the numpad 7 key? It also has home on it. On this keyboard, and other keyboards, a key like that is the only realistic way to press Home, End, Page Up, and Page Down with one hand.
> 
> I don't really care about numpad state; I just want to be able to detect when home is pressed. As I pointed out, query for key text is not able to provide this detection, and xev does detect this key correctly. So GLFW should be able to provide this detection as well.
> 
> If I queried lock key state, that might let me put a workaround hack for a single keyboard, but I don't want a workaround hack for a single keyboard; I want a general solution that works for all keyboards that x11 detects correctly.
