### ISSUE TITLE
Support for swap groups

### ISSUE THREAD

**Issue by andrewrk** [glfw/glfw#465]
Use case: you have multiple windows and you want vsync on.

If you have multiple windows then you need to call `glfwSwapBuffers` on all the windows. But if you have `glfwSetSwapInterval(1)` (vsync) set on all the windows, then the frame rate of each window will be `MonitorRefreshRate / NumberOfWindows` instead of simply `MonitorRefreshRate`.

The solution to this is "swap groups" for which there are assorted vendor specific extensions.

As a workaround, you can set the swap interval to 0 for all windows except one, and swap that window first. This is not ideal because it suffers from a race condition - you want the driver to do the swapping in sync with the vblank instead of the CPU calling swap buffers when it thinks the vblank is happening.

We talked about this on IRC briefly, so this is an issue to track progress.

**Comment by elmindreda** [comment]
These extensions are sadly only supported by Radeon and Quadro cards and only on Windows and X11.

**Comment by andrewrk** [comment]
Hmm, sounds like given an application which has this use case (multiple OpenGL windows with vsync on), the best option is not swap groups, since it's not widely supported, but one thread per context/window.

**Comment by elmindreda** [comment]
I agree.

**Comment by andrewrk** [comment]
Related: http://stackoverflow.com/questions/29617370/multiple-opengl-contexts-multiple-windows-multithreading-and-vsync
