### ISSUE TITLE
Access to CGL

### ISSUE THREAD

**Issue by ThibaultReuille** [glfw/glfw#466]
I am building a particle system using OpenGL and OpenCL. I need to share VBOs between OpenGL and OpenCL and therefore create an OpenCL context with the appropriate properties.

I am aware that glfw3 exposes some native API functions however I can't figure out how to access the CGL ones.

https://github.com/glfw/glfw/blob/master/include/GLFW/glfw3native.h

I basically need to find how to run this within glfw3:

```c++
[...]
cl_int error;
cl_device_id deviceID;

CGLContextObj kCGLContext = CGLGetCurrentContext();
CGLShareGroupObj kCGLShareGroup = CGLGetShareGroup(kCGLContext);
 
cl_context_properties properties[] =
{
    CL_CONTEXT_PROPERTY_USE_CGL_SHAREGROUP_APPLE,
    (cl_context_properties)kCGLShareGroup,
    0
};
clCreateContext(&properties, 1, deviceID, NULL, NULL, &error)
[...]
```

The problem is also discussed on the glfw github but doesn't answer the question for OSX. https://github.com/glfw/glfw/issues/104

Thank you very much guys, keep up the good work. I love your project ;).

Cheers,

**Comment by elmindreda** [comment]
The above code doesn't even need the native functions, as you're retrieving the context made current by `glfwMakeContextCurrent'. Just include the CGL headers and you're set.

However, you can also access the CGL context of a GLFW window with `glfwGetNSGLContext` and `NSOpenGLContext CGLContextObj` without making it current first, if you don't mind using a tiny bit of Objective-C.

**Comment by elmindreda** [comment]
I'll see about adding an OpenCL guide similar to the current Rift one.

**Comment by elmindreda** [comment]
CGL is provided by OpenGL.framework, iirc, so it should already be declared if you let the GLFW header include the OS X OpenGL header.

**Comment by ThibaultReuille** [comment]
Hi Elmindreda!

Thank you very much for your help. I am now finally able to compile / run that code.
Just reference, if anybody runs into the same problem here is what I did.

```c++
#ifdef __APPLE__
# define GL_GLEXT_PROTOTYPES
# define EGL_EGLEXT_PROTOTYPES
# include <GL/glew.h>
# include <GLFW/glfw3.h>
# include <OpenGL/OpenGL.h> // <---- That line was missing
# include <OpenCL/opencl.h>
# include <OpenCL/cl_gl.h>
#endif
```

For some reason, I just expected glfw3 to include it for me ;)

Cheers,
