### ISSUE TITLE
Compile platform specific code as modules

### ISSUE THREAD

**Issue by Cloudef** [glfw/glfw#468]
This is a suggestion. While I understand the simplicity of making this compile-time.
It is also major PITA to recompile projects or use different version of library when running program in different environments (mainly on linux). 

Such combinations include wayland + egl + glfw program, x11 + glx + glfw program, x11 + egl.
It would be great if platform code was compiled into modules, and then automatically try pick the best one, but overrideable with env variable. Modules that support both GLX/EGL, should probably default to what makes most sense, but allow overriding with env variable as well.

In future we might even have vulkan support to complicate this scheme even further.

It could also be possible to use dlopen instead of compiling to modules, to avoid issue where program needs to provide the modules + libglfw, however dlopen brings burden of maintaining function declarations.

**Comment by elmindreda** [comment]
This overlaps with #145.

**Comment by Cloudef** [comment]
>Yes, that is a long-term goal for GLFW.
I'm happy to read that.
