### ISSUE TITLE
No monitors found

### ISSUE THREAD

**Issue by Zilarrezko** [glfw/glfw#471]
Hey guys. I was following the quick start guide and while noticed that glfwInit was returning false. I slapped on the error callback and it says no monitors found. I ask on the glfw forums and they pointed me here. I looked on the issues here on github and I am not using a VM for my OS, though I do have 2 monitors.

Here's the source code: 

```cpp
#include <iostream>

#include "glfw3.h"

void
error_callback(int error, const char* description)
{
   puts(description);
}

int
main()
{
   glfwSetErrorCallback(error_callback);

   if(!glfwInit())
   {
      std::cout << "ERROR: GLFW failed to Initialize" << std::endl;
      //TODO: Logging
      return -1;
   }

   char *WindowTitle = "Hello World";
   GLFWwindow* Window = glfwCreateWindow(960, 540, WindowTitle, NULL, NULL);

   if(!Window)
   {
      glfwTerminate();
      //TODO: Logging
      return -1;
   }

   //TODO: Running loop

   //NOTE: Yay
   std::cout << "Window Created successfully" << std::endl;
   glfwTerminate();

   system("pause");

   return 0;
}
```

Though everything after glfwInit is pretty superfluous here, as it doesn't get past that for me.

If you need anymore info of course, I'll be checking my email every so often (about every hour or so).

EDIT: forgot to mention I'm using Windows 8.1

**Comment by Zilarrezko** [comment]
Do you guys need more information? Anyway I can help?

**Comment by elmindreda** [comment]
I'm writing a tool that may be of use.

In the meantime, are you logged in locally or via RDP?

**Comment by Zilarrezko** [comment]
Locally, although sometimes I use Team viewer to do development elsewhere. Though I haven't used it while working on this.

**Comment by elmindreda** [comment]
I'll get back to GLFW on Sunday, but note that I have a *lot* of issues to resolve.

If you can, please check if any adapters or displays are enumerated but rejected.

**Comment by Zilarrezko** [comment]
Hmmm.. Looking into device manager, and the monitors to check on details. Looks like I have two monitors (I have two monitors), but both are PnP monitors with TeamViewer GmbH as the manufacturer.  Possibly a culprit?

**Comment by elmindreda** [comment]
It's just a [fancy word](https://en.wikipedia.org/wiki/Enumeration) for listed. For example, the Windows function used for this is named `EnumDisplayDevices`.

**Comment by Zilarrezko** [comment]
perhaps this helps?

![enumdisplaydevice](https://cloud.githubusercontent.com/assets/8561784/6745032/50557f94-ce6e-11e4-9385-6c0b789dac9e.png)

**Comment by Zilarrezko** [comment]
Problem was teamviewer. I'm assuming the problem was when setting up remote desktop (even though I wasn't using it). Perhaps something that can be added in the future. It was unfortunate it took so long to find the problem, I'm sorry you spent to much time on it.

![noerror](https://cloud.githubusercontent.com/assets/8561784/6746157/bcadbbae-ce80-11e4-8bbe-8dc032a7129d.png)

**Comment by elmindreda** [comment]
I will be looking further into it because of #441.

**Comment by mmostajab** [comment]
anyone has anything new about this bug? I cannot run my application on our server only because of this problem :(

**Comment by elmindreda** [comment]
@mmostajab Try current master.

**Comment by fishkingsin** [comment]
particularly on TeamViwer 9  can cause glfw could not find  monitor

**Comment by elmindreda** [comment]
This issue should be fixed now.

**Comment by lijunzi** [comment]
![image](https://user-images.githubusercontent.com/15012817/114332005-da406980-9b77-11eb-80b8-0bf3ee169940.png)
How to solve it？
