### ISSUE TITLE
Main Thread Freezes on Window Resizing

### ISSUE THREAD

**Issue by jaredjones** [glfw/glfw#472]
When the window is resizing the main thread of the application is frozen due to polling and event processing. In other 3D applications and games, the program should continue to run as the window is being resized and graphics content should continue to render as well.

This is likely the cause of: #443
I imagine that these issues are related because the AppKit API is likely trying to send an event to something that is locked up.

Revision: 5268914b3fc222e5a54d0d42a5c0956a64334b53
OS: OS X 10.10.2
GPU: NVidia GTX 560 Ti

**Comment by elmindreda** [comment]
How should event processing be made not to block?

**Comment by jaredjones** [comment]
Well anything that involves the UI or user input should be polled at the monitor's refresh rate. So 60Hz=16.6ms per poll. After the refresh rate of the monitor has passed, the program will give control back to the main thread and then will continue polling UI events on the next loop.
Or a more complicated approach would be a priority queue of events to be scheduled and then processed.

**Comment by elmindreda** [comment]
OS X event processing blocks when a window is resized. This happens inside Cocoa, not GLFW. How should that be made to not occur?

**Comment by jaredjones** [comment]
I'm looking into it. I know one thing for certain though, is that using an NSOpenGLView in storyboards will not block rendering when the window is being resized. So there is obviously an issue with out GLFW is processing events differently then how Apple does it with automated storyboards.

**Comment by shurcooL** [comment]
If you `glfwSetRefreshCallback`, doesn't it get called while window is resizing, giving you a chance to redraw and give the illusion that it's not blocked? See [here](https://github.com/glfw/glfw/commit/cb11b7ca6f06195d361c74b8db71166f1a716047#commitcomment-10204473).

**Comment by jaredjones** [comment]
@shurcooL is correct; this is a non-issue. However glfwSetRefreshCallback does not fix #443
