### ISSUE TITLE
No way to query received context parameters

### ISSUE THREAD

**Issue by clbr** [glfw/glfw#476]
The documentation states

> To find out the actual attributes of the created window and context, use the glfwGetWindowAttrib function.

But the function doesn't allow most of the parameters (rgba bits, depth/stencil bits, did we get multisampling, etc etc), returning 0 for them all.

**Comment by clbr** [comment]
I was kinda hoping this would be solved by adding the functionality. As is, there is no way to query them, and this is exactly glfw's task, because only it has that info.

**Comment by elmindreda** [comment]
Are you using a core profile context?

**Comment by elmindreda** [comment]
This was removed from GLFW because OpenGL already provides the information.

If you are using a context that supports FBO, you can query these attributes with [glGetFramebufferAttachmentParameter](http://docs.gl/gl3/glGetFramebufferAttachmentParameter). Otherwise you can use [glGet](http://docs.gl/gl3/glGet).

**Comment by clbr** [comment]
No, OpenGL does not provide those values. I mean the window's attributes, those cannot be queried in GL, only in the platform-specific GLX/AGL/WGL.

For specific examples: How many bits does the window have for alpha? How many MSAA samples?

**Comment by clbr** [comment]
Hm, I see the rgba and ds bits are provided with that function, but only in core contexts, I'm using 2.1 and so don't have access to it.

Regardless, there are also parameters that it does not provide, MSAA samples being a prime example.

**Comment by elmindreda** [comment]
> No, OpenGL does not provide those values. I mean the window's attributes, those cannot be queried in GL, only in the platform-specific GLX/AGL/WGL.

The attributes you are after are those of the default framebuffer. Those are returned via the methods listed.

> Hm, I see the rgba and ds bits are provided with that function, but only in core contexts, I'm using 2.1 and so don't have access to it.

Read the whole paragraph.

> Regardless, there are also parameters that it does not provide, MSAA samples being a prime example.

`GL_SAMPLES` was made core in 1.3.

**Comment by clbr** [comment]
My apologies. It would help if the docs listed the alternative for each, because with GLX they are all in one place, like they used to be with GLFW.

**Comment by elmindreda** [comment]
That's true. I'll add it.

**Comment by elmindreda** [comment]
@clbr Would 427c79b24b0b322aba955a1efc6eb8c66f6d5b91 have been helpful?

**Comment by clbr** [comment]
Yes, thanks.
