### ISSUE TITLE
High level question/discussion of GLFW's two major responsibilities and their coupling.

### ISSUE THREAD

**Issue by shurcooL** [glfw/glfw#479]
Hi @elmindreda,

This is a high level question about GLFW and its scope, and design. I have some thoughts I wanted to discuss. Please don't consider this as a request for action or me suggesting GLFW change in any way, my goal is have a better understanding about some aspects, not increase the workload or maintenance for this great library.

It seems to the that responsibilities of GLFW can be described as two major categories:

- Window creation with the ability to get user input events (keyboard, mouse, touch, joysticks, etc.)
- OpenGL context creation (contained by the window) and switching

To give you some context (no pun intended) of where I'm coming from, I've been working on a package at https://github.com/shurcooL/goglfw that implements the same interface as GLFW but runs on an additional platform. Namely, it runs on all platforms that GLFW runs on (OS X, Linux, Windows), but tackles an additional platform, the web browser.

It has been an interesting and educational experience trying to implement the web backend, but so far I've had great success and was able to have small GLFW-using apps run in the browser. `goglfw` creates an HTML canvas element (spanning entire html document) in its `CreateWindow` func and creates a WebGL context. Keyboard input is done via "keydown" and "keyup" listeners, mouse movement and click events via "mousedown", "mousemove", "scroll", etc. Modern browsers have powerful APIs including mouse lock so I can even implement disabling and hiding the mouse cursor, etc.

![image](https://cloud.githubusercontent.com/assets/1924134/6818145/e2b24b2c-d267-11e4-8556-4fb855da5ab0.png)

One challenge I ran into when connecting all the pieces to make it work was that the WebGL context is very explicit and needs to be created from the underlying HTML canvas element, and kept track of. All WebGL calls on top of it need to reference that WebGL context object. My initial hacky solution was to simply create the WebGL context (using another library, which accepts the HTML canvas element in its [`Init`](https://github.com/shurcooL/gogl/blob/a1076ec75320e715b8407ff488f62a5648610bad/browser.go#L363-L366) func) inside `goglfw.CreateWindow` and expose it to the program. So the user code looked like this:

```Go
func main() {
	err := goglfw.Init()
	if err != nil {
		panic(err)
	}
	defer goglfw.Terminate()

	// On the web platform, goglfw.CreateWindow would create the WebGL context and expose it.
	window, err := goglfw.CreateWindow(800, 600, "Demo", nil, nil)
	if err != nil {
		panic(err)
	}
	window.MakeContextCurrent() // On web, this actually does nothing.

	// Hacky solution... but it worked.
	gl = window.Context

	gl.ClearColor(0.8, 0.3, 0.01, 1)
	gl.Clear(gl.COLOR_BUFFER_BIT)
	...
```

It was good enough for a prototype, but clearly there's room for improvement. The main limitation was that the goglfw package had to import the webgl package I used, so the user application had no choice but to use it. If someone else made better WebGL bindings, they'd have to make changes to goglfw to use it.

@crawshaw made the following suggestion in https://github.com/google/gxui/issues/49#issuecomment-84708676 and I agree with his suggested ideal:

> One extra ideal I'd try to reach for: no external references to any gl packages. That way it could be used by other drivers (for example, html5 canvas, or one of the many GL replacement languages that are appearing).

That makes a lot of sense to me. GLFW takes care of two distinct tasks. Creating a window and getting user input is valuable on its own, and it could be used even if you're not using a typical OpenGL context. For example, you could want to use alternative bindings, or draw using another API, or maybe even use Vulkan in the future. Regardless, if the context creation aspect could be outsourced, GLFW's window creation and user input would be great to have.

I've been reading http://www.glfw.org/docs/latest/context.html and thinking about an ideal solution. It seems to be that if context creation could be decoupled, it would be better. I understand that might not be  a realistic goal for the GLFW C library in the short term, but I was curious what your thoughts on this are on a more theoretical level?

---

Noticing that my `window.MakeContextCurrent()` was a noop on the web, I started thinking how I could potentially make use of it to enable the decoupling of GLFW from a context creation mechanism. I came up with the following solution in Go:

I declare an interface inside `goglfw`:

```Go
// ContextManager is a general mechanism for creating and switching
// between contexts.
type ContextManager interface {
	// NewContext takes some notion of a "window" - the parent container, and
	// creates a contained context. It returns the created context and error if any.
	NewContext(window interface{}) (context interface{}, err error)

	// MakeContextCurrent takes a previously created context (by this context manager)
	// and makes it current. If given context is nil, then the current context is detached.
	MakeContextCurrent(context interface{})
}
```

The idea now is to change the signature of `goglfw.Init` to accept a type that satisfies the `ContextManager` interface, and then `goglfw` can use it to perform custom context creation and switching. That allows the user to use `goglfw` and a package they wish that provides a `ContextManager`.

With that, the user code becomes much cleaner and more flexible:

```Go
import "your/favorite/gl"

func main() {
	// gl.ContextManager has the actual implementation details of context creation/switching.
	err := goglfw.Init(gl.ContextManager)
	if err != nil {
		panic(err)
	}
	defer goglfw.Terminate()

	// goglfw.CreateWindow uses gl.ContextManager to create new context.
	window, err := goglfw.CreateWindow(800, 600, "Demo", nil, nil)
	if err != nil {
		panic(err)
	}
	window.MakeContextCurrent() // This uses the gl.ContextManager to set current context.

	gl.ClearColor(0.8, 0.3, 0.01, 1)
	gl.Clear(gl.COLOR_BUFFER_BIT)
	...
```

If possible, I'd love feedback on what I'm doing. Does this make sense? Or am I doing something wrong and there are better ways?

Are there good reasons for desktop platforms to keep their context creation mechanisms tightly coupled within the internals of GLFW?

Do you think future versions of GLFW (4.0+) would ever want to decouple window creation+user input from context creation details and allow users to "bring their own"? Is it a good or a bad direction to head in?

Thanks!

**Comment by elmindreda** [comment]
> Are there good reasons for desktop platforms to keep their context creation mechanisms tightly coupled within the internals of GLFW?

They're not tightly coupled internally and less coupled every release. That's what lets us swap in EGL. There's an internal standard API for context creation: `_glfwInitContextAPI`, `_glfwTerminateContextAPI`, `_glfwCreateContext` and `_glfwDestroyContext`. I've been looking into potentially making this its own library, since people keep wanting to combine GLFW with... everything, but its interface wouldn't be entirely platform independent and would likely end up looking like TinyEGL.

> Do you think future versions of GLFW (4.0+) would ever want to decouple window creation+user input from context creation details

[Yes](https://github.com/glfw/glfw/wiki/GLFW-4.0-sketchbook).

> and allow users to "bring their own"?

Their own handles? [Yes](https://github.com/glfw/glfw/issues/25). Their own APIs? See below.

> Is it a good or a bad direction to head in?

Being able to take control of existing native handles, for well-defined cases, is likely a good thing. Fully separating out context creation into a reusable component (that GLFW would ship inline) may possibly be a good thing.

Using GLFW for window and input, however, is very likely a bad thing. That's what proper UI toolkits are for. Qt even has sane context creation nowadays, with context flags and everything. People will inevitably do it anyway once it's possible, but it's not something I'll support or encourage.

As for other APIs, the only relevant ones are OpenVG and Vulkan. OpenVG would be simple to support with the EGL back-end. That's what `GLFW_CLIENT_API` is for. I don't know that anyone is using OpenVG for anything on the desktop, though. Vulkan may be a little trickier if it resembles the Mantle WSI and may require #25 in order to be sane.

The problem above doesn't really apply to the C library. GLFW doesn't use or need any client API bindings. Any drawing API provided by Khronos should probably be supported, WebGL excluded of course. Any drawing API provided by anyone else might as well not exist, because it'll be platform specific and why aren't you using the native toolkit?

**Comment by shurcooL** [comment]
Thank you very much for the reply, it has been very helpful.

**Comment by elmindreda** [comment]
Do we close this now?

**Comment by shurcooL** [comment]
This is the current state, which was definitely influenced by your reply.

After discussion and thinking, I've decided to move the WebGL context creation into my `goglfw` library, similar to how GLFW takes care of context creation of other contexts (instead of having it externally or inside the WebGL bindings library), see https://github.com/shurcooL/goglfw/pull/1. I still needed some way of connecting the WebGL bindings to the WebGL context created by goglfw, but I provide a minimal interface needed for that:

```Go
// ContextSwitcher is a general mechanism for switching between contexts.
type ContextSwitcher interface {
	// MakeContextCurrent takes a context and makes it current.
	// If given context is nil, then the current context is detached.
	MakeContextCurrent(context interface{})
}
```

I am still in the process of completing the CL for `x/mobile/gl` package, so depending on the review there, this approach may change, but so far it seems to work quite well and I expect it to likely remain as is.

I'll close this now, and if something unexpected comes up and I have additional feedback/questions, I can reopen. Thanks again for the helpful discussion!
