### ISSUE TITLE
Memory leak in glfwInit

### ISSUE THREAD

**Issue by caupetit** [glfw/glfw#480]
Hi, I got a memory leaks on Mac os-x Yosemite  version 10.10.2 (14C109)

It happends during the call of glfwInit(), I use glfw version 3.1 with the followings defines.
(not 3.1.1 but i didn't see fix for it in  version history)

```shell
# define GLFW_INCLUDE_GLCOREARB
# include <GLFW/glfw3.h>
```

The leaks message is the following:
```shell
Process:         nibbler [12538]
Path:            /Volumes/Data/nfs/zfs-student-5/users/2013/caupetit/c++/nibbler/./nibbler
Load Address:    0x10d86b000
Identifier:      nibbler
Version:         0
Code Type:       X86-64
Parent Process:  zsh [2720]

Date/Time:       2015-03-25 16:00:52.853 +0100
OS Version:      Mac OS X 10.10.2 (14C109)
Report Version:  7
Analysis Tool:   /usr/bin/leaks
----

leaks Report Version:  2.0
Process 12538: 4193 nodes malloced for 1138 KB
Process 12538: 1 leak for 48 total leaked bytes.
Leak: 0x7fb511d17a70  size=48  zone: DefaultMallocZone_0x10d87f000   __NSCFString  ObjC  CoreFoundation  "Mac-FC02E91DDD3FA6A4"
```

**Comment by jaredjones** [comment]
Here is the call tree for the leak.
![screen shot 2015-03-28 at 8 45 45 am](https://cloud.githubusercontent.com/assets/1316894/6881295/e622f628-d526-11e4-893c-74f60fc17d06.png)

**Comment by elmindreda** [comment]
@jaredjones Thank you!

**Comment by elmindreda** [comment]
This was reported before, in #326. I still don't get where the leak on our end is supposed to be. The `CFDictionary` returned by `IODisplayCreateInfoDictionary` is released in all paths. The value retrieved from it (and the value retrieved from that) uses the Get rule.

**Comment by jaredjones** [comment]
I believe the leak is inside of the Cocoa API, might also be part of the reason it was deprecated. Since the leak is super small and only occurs when glfwInit() is ran which isn't often, I say leave it. Eventually GLFW will need a replacement for the deprecated API call, when that happens the leak will be gone.

**Comment by elmindreda** [comment]
Agreed on both counts.
