### ISSUE TITLE
glfw3Config.cmake installs into wrong directory and hence breaks find_package for 3rd party cmake based projects

### ISSUE THREAD

**Issue by MaikBeckmann** [glfw/glfw#483]
If a cmake based project, like glfw, installs an *-config,cmake or *Config,cmake it automatically enables other cmake based projects to just find it using the <code>find_package</code> command.  Since glfw's config file is glfw3Config.cmake putting this inside a CMakeLists.txt should just work
```cmake
find_package(glfw3 REQUIRED)
```
But it doesn't.  The above <code>find_package</code> statement searches for glfw3Config.cmake in a number of locations, among then
```sh
$INSTALL_PREFIX/lib/cmake/glfw3/glfwConfig.cmake
```
The problem is that you guys install it to
```sh
$INSTALL_PREFIX/lib/cmake/glfw
```
rather than
```sh
 $INSTALL_PREFIX/lib/cmake/glfw3
```
The solution is to either install the config file to
```sh
$INSTALL_PREFIX/lib/cmake/glfw3
```
or to keep the installation dir, rename the config file to glfwConfig.cmake and tell people to use
```cmake
find_package(glfw REQUIRED)
```

Regards,
Maik

**Comment by elmindreda** [comment]
Please see #460.

**Comment by MaikBeckmann** [comment]
Thank you, I searched for issues but not pull request, my bad.

FYI, there are more issues with with the config file, see
 - http://www.cmake.org/Wiki/CMake/Tutorials/Packaging

Usually one is meant to use find_package like this
```cmake
find_package(foo REQUIRED)
...
add_executable(bar ..)
set_target_properties(bar PROPERTIES
  INCLUDE_DIRECTORIES ${foo_INCLUDE_DIRS}
)
target_link_libraries(bar
    ${foo_LIBRARIES)
)
```
You guys don't set any of these variables.  This is just inconvenient though, since a dev is required to find and open the glfw3Config.cmake and read the comments at its top, rather than having the above just work.

**Comment by elmindreda** [comment]
@MaikBeckmann Please bring those issues up in #460.

**Comment by ngvitovitch** [comment]
@MaikBeckmann acknowledged, will patch to export plural forms of var names
and match cmake conventions.

In making this change, would it be appropriate to mark the singular forms
(i.e. GLFW_INCLUDE_DIR) as advanced?  This caught my eye in the following
example:
http://www.cmake.org/Wiki/CMake:How_To_Find_Libraries#Writing_find_modules

**Comment by MaikBeckmann** [comment]
@ngvitovitch This is what people usually do, because it works for both simple and more involved config files,  Imagine you're writing a library  which depends on glfw.  Your config file calls find_package on glfw and aside from your own ?_INCLUDE_DIR adds GLFW_INCLUDE_DIRS to your ?_INCLUDE_DIRS.

The singular ?_INCLUDE_DIR variable is for directly reaching inside the include directory, for whatever reason (3rd party tool that requires full paths, i.e.)
