### ISSUE TITLE
Fullscreen on Yosemite

### ISSUE THREAD

**Issue by kveale** [glfw/glfw#484]
On OS X Yosemite, I am trying to get GLFW to create a fullscreen window. I am creating the window with the current desktop resolution and primary monitor, but it creates a 'maximized' window on the desktop, not a true fullscreen window. I have tried many combinations of screen coordinates and hints to get it to work. I am using a mac book pro with a retina display.

When I click the fullscreen button on the title bar of the window, the window changes to fullscreen. But I noticed that the frame buffer size is 1440 x 900. I thought it should be 2880 x 1800 (double) since this is a retina display. 

Thanks.

**Comment by elmindreda** [comment]
Which version of GLFW are you using?

**Comment by kveale** [comment]
I am using GLFW 3.1.1

Thanks.

**Comment by jaredjones** [comment]
Yup I've noticed the same thing as well. If I move the mouse and exit my right monitor that is running a full screen GLFW application and click on my left monitor the program minimizes. It appears that currently GLFW is resizing the resolution and going fullscreen (windowless), not true native full screen.

**Comment by elmindreda** [comment]
> On OS X Yosemite, I am trying to get GLFW to create a fullscreen window. I am creating the window with the current desktop resolution and primary monitor, but it creates a 'maximized' window on the desktop, not a true fullscreen window.

Please define "true full screen window." OS X has at least four kinds of full screen for OpenGL applications: NSView full screen with display capture, CGL full screen with display capture, Lion full screen in an ephemeral Space and manual borderless floating window full screen.

GLFW currently uses the last one, as it is the one recommended by the [OpenGL Programming Guide for Mac](https://developer.apple.com/library/mac/documentation/GraphicsImaging/Conceptual/OpenGL-MacProgGuide/opengl_intro/opengl_intro.html) and the one that interacts best with the window system.

**Comment by jaredjones** [comment]
The issue with the current implementation of full screen is that it takes a good 5 seconds to CMD+TAB and you can't slide to a different space. I think he wants Lion full screen where it takes up a space.

**Comment by elmindreda** [comment]
On what configuration does it take five seconds? It's fairly instantaneous here.

**Comment by jaredjones** [comment]
Kveale The pixel doubling you are referring to on a retina display is not done automatically for a GLContext. Every video game I've played specifies the full 2880x1800 as an option along with 1440x900. So that is a non issue, GLFW in that way is behaving adequately.

**Comment by jaredjones** [comment]
It takes time of the resolution is set to something different than the OS resolution is set at. If the OS and the GLFW application are the same resolution it is instant.

Now that I think about it... Lion full screen would be horrible because every time you move your mouse to either the top of a window or the bottom the dock or menu bar would show up.

**Comment by jaredjones** [comment]
Unless this project wants to have platform specific window flags, where the programmer can specify what type of window they want on OS X, I'd say this issue should be closed.

**Comment by elmindreda** [comment]
@kveale [Video modes use _screen coordinates_, not _pixels_](http://www.glfw.org/docs/latest/monitor.html#monitor_modes). The [size of the framebuffer](http://www.glfw.org/docs/latest/window.html#window_fbsize) is provided in pixels.

@jaredjones Yes, that's one of the reasons why I rejected Lion full screen. I'll at least look into making an option for it, if that's what @kveale really wants.

**Comment by jaredjones** [comment]
Actually the Lion full screen allows you to specify if the menu bar and dock can be hidden.
Struct OSXPresentationWindowOptions

https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSApplication_Class/index.html#//apple_ref/c/tdef/NSApplicationPresentationOptions

**Comment by elmindreda** [comment]
@jaredjones Cool, but does Lion full screen allow you to choose which screen you end up on?

**Comment by kveale** [comment]
With the latest version of GLFW I have, the full screen feature seems to be working great on Yosemite. Also I am able to use retina mode as needed. So for me this issue is now fixed. Thanks!

**Comment by Bilalmirza** [comment]
I think this is the issue  that is back to haunt me :P
https://github.com/cocos2d/cocos2d-x/issues/16561
