### ISSUE TITLE
How to type texts into OpenGL?

### ISSUE THREAD

**Issue by chaosink** [glfw/glfw#488]
Does GLFW have an interface to type texts easily into OpenGL?

**Comment by elmindreda** [comment]
Please explain what you mean.

**Comment by evrimoztamur** [comment]
My assumption is that he's looking for a glfwDrawText(char* string, int x, int y) function. If that is the case then no, GLFW does not have anything like that. It's for context creation and context-related IO.

**Comment by elmindreda** [comment]
@chaosink If you mean text *input* then see the [character callback](http://www.glfw.org/docs/latest/input.html#input_char).
