### ISSUE TITLE
Ignore the build folder

### ISSUE THREAD

**Issue by sudhanvas** [glfw/glfw#489]
Could you please add the "build/" folder to the .gitignore? I'm trying to use this as a submodule in a project; git keeps saying that there is untracked content and the build folder is what's causing that.

**Comment by elmindreda** [comment]
Place the build directory outside of the GLFW source tree.

**Comment by elmindreda** [comment]
An in-tree build of GLFW works very well too.

I've corrected the documentation, as it recommended placing the out-of-tree build directory inside the source tree.
