### ISSUE TITLE
Context creation freezes when switching to discrete GPU

### ISSUE THREAD

**Issue by Leandros** [glfw/glfw#490]
First of all, I'am using a `MacBookPro11,3`, with a discrete nVidia GeForce GT 750M.

When I'am trying to use a GLFW application, without the discrete GPU being active, GLFW stucks at `glfwCreateWindow` and can't open the window.

**Comment by elmindreda** [comment]
Do you mean that the call fails or that it never returns?

**Comment by Leandros** [comment]
It never returns.

**Comment by elmindreda** [comment]
A call stack for the freeze would be very helpful.

**Comment by jaredjones** [comment]
I'm unable to replicate this...
Hardware: MacBook Pro (Retina, 15-Inch, Late 2013) a.k.a. "MacBookPro11,3"
--
Whenever I launch a GLFW application the program always switches to my discrete GPU automatically unless I create a plist value and tell it not to. In either case, the program never freezes for me. So basically I'm running the exact same hardware as you and this issue isn't happening for me.

**Comment by Leandros** [comment]
I couldn't as well, unfortunately. Are crash logs saved by OS X somewhere?
Maybe it's still there and I could upload it to help and solve the issue.

On Friday, May 15, 2015, Jared Jones <notifications@github.com> wrote:

> I'm unable to replicate this...
> Hardware: MacBook Pro (Retina, 15-Inch, Late 2013) a.k.a. "MacBookPro11,3"
>
> Whenever I launch a GLFW application the program always switches to my
> discrete GPU automatically unless I create a plist value and tell it not
> to. In either case, the program never freezes for me. So basically I'm
> running the exact same hardware as you and this issue isn't happening for
> me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/glfw/glfw/issues/490#issuecomment-102419810>.
>


-- 
Mit freundlichen Grüßen, / Yours sincerely,

Arvid Gerstmann <dev@arvid-g.de>

---
Portfolio: http://arvid-gerstmann.de
Twitter: http://twitter.com/ArvidGerstmann
Google+: http://google.com/+ArvidGerstmann
---

**Comment by elmindreda** [comment]
Has anyone been able to reproduce this and produce a call stack?

**Comment by shurcooL** [comment]
> Are crash logs saved by OS X somewhere?

They _might_ be in the Console app. It's a standard app that ships with macOS.

![image](https://cloud.githubusercontent.com/assets/1924134/24381128/96fe449a-131c-11e7-9b5d-c2db70431b44.png)

(It's not completely clear to me how to use it and what gets logged vs doesn't, so YMMV.)

**Comment by jaredjones** [comment]
User process crashes go here
~/Library/Logs/DiagnosticReports

**Comment by elmindreda** [comment]
Was this ever resolved?

**Comment by Leandros** [comment]
I try if I can still reproduce this. Still got a dedicated GPU in my MacBook.

**Comment by xtexChooser** [comment]
The same reproduced with openSUSE Tumbleweed + KDE Plasma + NV 750Ti
For more BloCamLimb/ModernUI#160
