### ISSUE TITLE
windowicon merge ETA

### ISSUE THREAD

**Issue by evrimoztamur** [glfw/glfw#491]
For a while I have been using GLFW with Java through LWJGL. Unfortunately, as I am developing with Java and not compiling executables, it is not possible for me to include a GLFW_ICON resource. I saw that there is a [branch that adds window icon compatibility with GLFWimages](https://github.com/glfw/glfw/compare/windowicon). Any idea so as to when this will become available in the master branch?

**Comment by elmindreda** [comment]
No idea at the moment.

This is a duplicate of #453.
