### ISSUE TITLE
Switching back to a fullscreen application on Yosemite with multiple monitors crashes the application

### ISSUE THREAD

**Issue by chanchikwan** [glfw/glfw#492]
The problem should be reproducible by running the following code on OS X Yosemite with a dual-monitor setup.  The code creates a fullscreen window.  Simply press "Cmd+Tab" twice to switch to a different application and switch back, the code crashes.

	#include <GLFW/glfw3.h>
	
	int main()
	{
		glfwInit();
	
		GLFWmonitor *m = glfwGetPrimaryMonitor();
		GLFWwindow  *w = glfwCreateWindow(640, 480, "buggy", m, NULL);
	
		while(!glfwWindowShouldClose(w))
			glfwPollEvents();
	
		glfwTerminate();
	
		return 0;
	}

**Comment by elmindreda** [comment]
If the object is prone to disappearing it's probably better not to cache it in the first place. The screen of a `GLFWmonitor` isn't used very often anyway. Or, if it is to be cached, it should be updated on `NSApplicationDidChangeScreenParametersNotification`.
