### ISSUE TITLE
glfwSetWindowTitle() is not working (title remains unchanged), unless glfwPollEvents() is also called.

### ISSUE THREAD

**Issue by Adnn** [glfw/glfw#495]
Hi,

  I am working on OS X 10.9.5, glfw was installed through brew which reports version "stable 3.0.4".

The title says pretty much all. I am using the window title to display basic textual information, so making a call to glfwSetWindowTitle() each frame. This call does not change the title --which remains at the value set by glfwCreateWindow()-- unless I also call glfwPollEvents().
Since I do not see an entry in glfwSetWindowTitle() documentation requiring to call the poll method, am I right to assume it is a bug ?

FYI: The glfwPollEvents() fix was found here: https://www.opengl.org/discussion_boards/showthread.php/176229-glfwSetWindowTitle-not-working-for-me?p=1230516&viewfull=1#post1230516

Thank you for taking the time to read this issue and maintain this project !

**Comment by elmindreda** [comment]
Yup, that's a documentation bug.

**Comment by elmindreda** [comment]
Thank you for spotting it!
