### ISSUE TITLE
charmods callback not called in multi-window application

### ISSUE THREAD

**Issue by andrewrk** [glfw/glfw#501]
0. use the code below
 0. click on window 1
 0. type a few characters
 0. notice that nothing is printed to stderr - this is unexpected
 0. click on window 2
 0. type a few characters
 0. notice that window 2 got charmod callbacks - this is expected

```c
#include <GLFW/glfw3.h>
#include <stdio.h>

static void charmods_callback(GLFWwindow* window, unsigned int codepoint, int mods) {
    fprintf(stderr, "charmod %p\n", (void*)window);
}

int main(int argc, char * argv[]) {
    glfwInit();

    GLFWwindow *window1 = glfwCreateWindow(800, 600, "window 1", NULL, NULL);
    glfwSetCharModsCallback(window1, charmods_callback);

    GLFWwindow *window2 = glfwCreateWindow(800, 600, "window 2", NULL, NULL);
    glfwSetCharModsCallback(window2, charmods_callback);

    for (;;)
        glfwWaitEvents();
}
```

Other callbacks, such as close, cursor pos, window size, etc., work fine for each window.

My system is:

 * Ubuntu 14.10 Utopic Unicorn
 * XFCE 4.10.1

**Comment by andrewrk** [comment]
in x11_window.c:

```c
                if (XFilterEvent(event, None))
                {
                    // Discard intermediary (dead key) events for character input
                    break;
                }
```

In the window where the charmod callbacks are getting called, `XFilterEvent` is returning false; in the window where the charmod callbacks are not getting called but they should be, `XFilterEvent` is returning true and the event is discarded as a dead key.

I'm not sure how to resolve this.

**Comment by andrewrk** [comment]
If I simply remove this `XFilterEvent` check, the problem goes away. What's the point of that function call?

Further, if I create many windows and attach listeners for all of them, only the callbacks for the last window created get fired. Perhaps in the X11 API you are supposed to tell it when a window is activated, so `XFilterEvent` returns false for that window's events?

**Comment by elmindreda** [comment]
An easy way to test this and similar issues is `events -n2`.

**Comment by andrewrk** [comment]
woo hoo!
