### ISSUE TITLE
Borderless full screen window disappears on focus loss

### ISSUE THREAD

**Issue by piermorel** [glfw/glfw#506]
In Mac OS X Yosemite and Mavericks with glfw 3.1.1,  when the desired fullscreen video mode is the current one, the doc says the video mode will not be changed and that a borderless full screen window is created. However, when this is the case, any loss of focus in the app (command line app for me) result in the disappearance of this fullscreen window, no matter what the GLFW_AUTO_ICONIFY hint is. This is not the case when a different video mode is requested.

**Comment by elmindreda** [comment]
Oops.

**Comment by elmindreda** [comment]
Thank you for reporting this!

**Comment by piermorel** [comment]
This doesn't seem to solve the issue for me, now it actually looks like the fullscreen window disappears whenever the application is not in focus anymore, no matter how the window was created or which GLFW_AUTO_ICONIFY flag is set.

**Comment by elmindreda** [comment]
Unable to reproduce.

**Comment by piermorel** [comment]
My bad, Xcode kept linking against an older version. All is good, thanks for the quick fix !
