### ISSUE TITLE
Window with SRGB framebuffer gives SIGSEGV when entering fullscreen

### ISSUE THREAD

**Issue by neon64** [glfw/glfw#514]
I have enabled `GL_FRAMEBUFFER_SRGB` to gamma correct the outputs from my shaders .

Entering fullscreen using the built in button in the mac os x menu bar crashes.

Firstly, I am suspicious because I was allowed to use that enable without first requesting it through GLFW like so:

     glfwWindowHint(GLFW_SRGB_CAPABLE, GL_TRUE);

However I tried adding that line as well and there was the same crash.

In my application I am using LWJGL's glfw binding but the error indicates it is the fault of the native library not the java code.

    SIGSEGV (0xb) at pc=0x0000000117e135a4, pid=87613, tid=1299

    Problematic Stack Frame:
    C  [liblwjgl.dylib+0x155a4]  _glfwInputWindowSize+0x4

Here's a link to the full error log:

http://pastebin.com/7wuLucrS

**Comment by elmindreda** [comment]
I am unable to reproduce this with any native example on 10.10.3.

`GLFW_SRGB_CAPABLE` is a no-op on OS X as sRGB is supported by all framebuffer pixel formats.

**Comment by Spasi** [comment]
This looks like it might be an LWJGL issue, although I cannot reproduce it either. Could you post a simplified version of your code? (maybe on the LWJGL forum)

Btw, are you sure it happens only if `GL_FRAMEBUFFER_SRGB` is enabled?

**Comment by neon64** [comment]
Thanks for the information. I'll take another look at it when I have more time.

**Comment by elmindreda** [comment]
Was this resolved?
