### ISSUE TITLE
Q: GLFW CMake version

### ISSUE THREAD

**Issue by Eric89GXL** [glfw/glfw#515]
Recently my Travis CI builds that use GLFW broke because of a CMake version requirement bump:

```
CMake Error at CMakeLists.txt:3 (cmake_minimum_required):
  CMake 2.8.12 or higher is required.  You are running version 2.8.11.2
```

Would it be possible to relax this restriction? It makes builds not work on Ubuntu 12.04 LTS. If not, I can go to using a commit number before the CMake change, but that's not ideal.

**Comment by elmindreda** [comment]
Yep, I know I broke Travis builds for the moment but I cannot wait any longer. 2.8.12 brought important features that I'll be using in the coming weeks. The current version is 3.2.2, so it's not exactly bleeding edge. That Travis runs such ancient software is frankly on them at this point.

There are also rumors (travis-ci/travis-ci#3480) that there's a PPA that might work while we wait for them to update to 14.04. When time permits I'll push a container-based Travis setup to master.

**Comment by Eric89GXL** [comment]
Fair enough, we'll use an older commit for the time being. Thanks for the quick response (and of course the great software!).
