### ISSUE TITLE
Joystick test has high cpu usage

### ISSUE THREAD

**Issue by expipiplus1** [glfw/glfw#516]
This certainly isn't a major issue, it might not even be worth correcting just for a test.

The joysticks test fully "utilizes" the cpu on machines I've tested it on. Is it worth enabling vsync or sleeping every frame to prevent this?
I sometimes use this test as a quick way of debugging joystick inputs, it would be nice if it wasn't quite as wasteful :)

**Comment by elmindreda** [comment]
That test already has vsync [enabled](https://github.com/glfw/glfw/blob/master/tests/joysticks.c#L219).

**Comment by expipiplus1** [comment]
So it seems as though this was caused by an issue with vsync on Windows 10. Solved in the dwmflush branch at the moment. Thanks!

**Comment by elmindreda** [comment]
I'm stealing this for the bugfix. I hope that's all right.

**Comment by expipiplus1** [comment]
no problem.
