### ISSUE TITLE
Stuttering full screen graphics with non-zero swap interval

### ISSUE THREAD

**Issue by softwarefailure** [glfw/glfw#519]
The latest workaround for vsync'ed buffer swapping on systems with compositing enabled leads to stuttering when in fullscreen mode. In windowed mode it's working fine. 

I have three different test machines. 

1) XP with a Radeon 9250
2) Vista with an ATI Mobility Radeon HD 2400 XT
3) Windows 7 with an AMD Radeon HD 6450

On machine 1 it's working correctly in both windowed and fullscreen mode. On machines 2 and 3 only windowed mode is good. In fullscreen mode the movement is clearly not smooth and there's some stuttering / refresh artifacts.

Here's the test code that I used:

```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <windows.h>

#include <GLFW/glfw3.h>

int main(void)
{
	GLFWwindow* window;
	int i = 0, mode = 0;
	GLFWmonitor **mons;
	int count;
			
	if(!glfwInit()) return -1;

 	mons = glfwGetMonitors(&count);
 
	window = glfwCreateWindow(640, 480, "Hello World", *mons, NULL);
	if(!window) {
		glfwTerminate();
		return -1;
	}

	glfwMakeContextCurrent(window);
	glfwSwapInterval(1);
	
	glMatrixMode(GL_PROJECTION);
 	glLoadIdentity();
 	glOrtho(0, 640, 0, 480, -1, 1);		
	glDisable(GL_DEPTH_TEST);
	glDisable(GL_BLEND);	
	glDisable(GL_TEXTURE_2D);	
	glMatrixMode(GL_MODELVIEW);
 	glLoadIdentity();
	
	glColor3f(1.0, 1.0, 1.0);
	
	while(!glfwWindowShouldClose(window)) {
		
		glClear(GL_COLOR_BUFFER_BIT|GL_DEPTH_BUFFER_BIT);
		glRecti(i, 190, i + 100, 290);		
		
		glfwSwapBuffers(window);
		glfwPollEvents();
		
		if(!mode) {
			i++;
			if(i >= 539) mode = 1;
		} else {
			i--;
			if(i <= 0) mode = 0;
		}			
	}

	glfwTerminate();
	
	return 0;
} 
```

It simply moves a white box from left to right and back again. The aim is to have it moving without any refresh artefacts. Currently this only happens on the XP machine. On Vista and 7 it's stuttering with refresh artefacts in fullscreen mode. In windowed mode it works perfectly on all three systems.

**Comment by elmindreda** [comment]
I put together a Radeon machine and I can verify this.

**Comment by elmindreda** [comment]
Also verified with a GeForce card.

**Comment by hypernewbie** [comment]
does it go away when aero is disabled?
are multiple monitors connected?

**Comment by elmindreda** [comment]
If Aero is disabled then WGL swap interval is used.

**Comment by softwarefailure** [comment]
In case this can't be solved I am proposing to implement a workaround that sleeps until the next vertical refresh. IMHO this is a better solution that just doing nothing as it is currently. The current implementation is not really portable because on Linux & Mac OS glfwSwapInterval(1) will correctly synchronize with the vertical refresh while on Windows it does nothing, thus causing projects to run at lightning speed. I've already played around with a workaround that waits until the next vertical refresh and it's working quite well but of course there is the disadvantage that it will hog the CPU because you need to poll the performance counter because Win32's Sleep() function is not precise enough for this kind of task. See here for some more elaborations on this topic by me: http://stackoverflow.com/questions/30437756/glfwswapbuffers-and-vertical-refresh-on-windows

Of course I'm still hoping that you can come up with a nice solution which works everywhere and doesn't hog the CPU but in case it's not possible, I'd suggest to use a polling timer to do the vertical refresh synchronization for portability's and consistency's sake.
