### ISSUE TITLE
Does the GLFW API allow for toggling an existing window fullscreen<->windowed?

### ISSUE THREAD

**Issue by shurcooL** [glfw/glfw#523]
Hi, this is a question.

In the current GLFW API, is it possible to take an existing window that was opened in normal "windowed" mode and make it go "fullscreen" (either "windowed fullscreen" or otherwise) but _without_ closing the existing window and opening a new window?

From my reading of http://www.glfw.org/docs/latest/window.html#window_creation, it sounds like the API does not provide such ability, is that correct? (Please let me know if the question is unclear.)

I just want to confirm that's the case. Perhaps I am missing something, maybe it's possible to do the above via `glfwSetWindowSize` or so.

The reason I ask is because there are some operating systems/platforms where it's possible to do such an operation without having to destroy the window and the associated GL context, and I'd like to see if I can implement such a backend while staying true to the GLFW API.

Thank you!

**Comment by elmindreda** [comment]
Correct. This will be added by #43 in 3.2. The groundwork was laid in 3.1.

**Comment by shurcooL** [comment]
Excellent news, thank you!
