### ISSUE TITLE
Framebuffer doesn't actually resize under nouveau

### ISSUE THREAD

**Issue by papertoilet** [glfw/glfw#524]
I'm still fresh with GLFW but I believe that framebuffer should scale respectively to the window. Theoretically it does, because I've setup a callback which tells me size of framebuffer after resizing and it does change as I resize window, but in practice framebuffer's size doesn't change after window is created.

Basically it looks like this:
![screenshot](http://i.imgur.com/qprxouu.png)

I'm using:
Kernel 4.0.4
Mesa 10.5.6
Nouveau as my GPU driver
Plasma 5.3.1 as my desktop environment
Xorg 1.17.1

Also I don't know if it's helpful, but in ancient mesa docs I have found that:
"Mesa can't determine when a window is resized. When the on-screen window is resized the ancillary (depth, stencil, accumulation) buffers should be resized. The work-around is for Mesa to query the window size whenever glViewport is called. This is usually sufficient since glViewport is usually called soon after a window has been resized. When this isn't sufficent the programmer can include a call to glResizeBuffersMESA() which forces Mesa to query the current window size and resize the ancillary buffers if needed." - from http://www.mesa3d.org/brianp/sig97/mesadoc.htm

**Comment by tombsar** [comment]
Can you confirm that in response to the resize callback your application is calling both `glViewport` and `glClear`? Unless I'm mistaken, the result in your screenshot can be achieved by the application failing to clear the framebuffer after it has been resized.

**Comment by papertoilet** [comment]
Hm, if I glClear in a callback everything works just fine, but afaik I shouldn't need to clear the framebuffer on my own in a callback function, because if I remember correctly on Windows GLFW clears the framebuffer for you after it is being resized.

**Comment by tombsar** [comment]
> if I remember correctly on Windows GLFW clears the framebuffer for you after it is being resized

Perhaps @elmindreda can comment on this, but I don't recall anything in the docs saying that this is guaranteed behaviour.

You don't have to `glClear` in the callback function itself, just make sure your application redraws itself after the framebuffer is resized. http://www.glfw.org/docs/latest/window.html#window_refresh might be of use to you.

**Comment by elmindreda** [comment]
In fact, GLFW explicitly tells Windows never to erase the window contents in any circumstances. It's possible that the larger framebuffer is initially cleared by DWM when running Aero, as it would otherwise contain bits of other applications.
