### ISSUE TITLE
Static glfw3.lib is linked with dynamic MSVCRT by default

### ISSUE THREAD

**Issue by xlz** [glfw/glfw#528]
Windows users sometimes perfer to build static binary to avoid the hassle of managing DLLs.

Building from source, `cmake -DBUILD_SHARED_LIBS=OFF` will create the static library glfw3.lib, which is linked with the dynamic link library MSVCRT (`/MD`). To verify, `grep __imp_qsort glfw3.lib` will match, and `__imp_qsort` only appears in MSVCRT, not LIBCMT (`/MT`, the static link library).

The users will be unable to build static executables with glfw3.lib and other objects compiled with `/MT`. Linking will fail due to symbol conflicts between LIBCMT referenced by user objects, and MSVCRT referenced by glfw3.lib.

The official binary package also contains glfw3.lib with the same issue.

Perhaps, `USE_MSVC_RUNTIME_LIBRARY_DLL` should be automatically turned off when building glfw3.lib.

**Comment by elmindreda** [comment]
The default in VC++ is multithreaded DLL. A user who knows to change that setting in the application's project file should also know how to do it in the GLFW project file.

**Comment by xlz** [comment]
What about the prebuilt binary glfw-3.1.1.bin.WIN64.zip? The static version glfw3.lib in it is linked with dynamic version. Users who want to build static binary cannot use this prebuilt binary.

**Comment by elmindreda** [comment]
That's correct. Those packages don't provide debug mode binaries either, or binaries with all combinations of compilation options. It's a convenience aimed at the most common common use case.

**Comment by xlz** [comment]
I'l take that as a EWONTFIX.

**Comment by elmindreda** [comment]
Yes.

It would be unreasonable to include every combination of bitness, compiler version, libc and compilation options. There are people wanting different settings for all of those. The best option will always be to compile the version you want and that is what the download page recommends.

**Comment by xlz** [comment]
There is no point in providing the static glfw3.lib if you are not going to support its use case of building static binary.

**Comment by JamesTheHacker** [comment]
This needs reopening. @xlz is correct.

I use the C++ build tools for Windows using CL from the command prompt to statically link libs. The exact issue @xlz discusses is the issue I'm having. I can't recompile. I don't have VS installed and I don't have the bandwidth to install it.

So frustrating that a static library is compiled with /MD. Why exactly?!

**Comment by elmindreda** [comment]
You're right. I was wrong. Releases now contain both /MT and /MD static libraries for all supported versions of VS, as well as a single /MT DLL built with the latest version of VS.
