### ISSUE TITLE
Cursor isn't restored when breakpoint is hit

### ISSUE THREAD

**Issue by DavidDanielsson** [glfw/glfw#530]
I'm running Ubuntu 14.04.02 LTS and using CLion.

I disable the cursor using `glfwSetInputMode(window, GLFW_CURSOR, GLFW_CURSOR_DISABLED)` when the program is started, and when I hit a breakpoint the cursor mode isn't set back to normal. This of course makes it impossible to debug. I'm assuming this is a bug since it gives me the cursor back whenever I alt+tab.

I also noticed that if I put
```
if(focus)
    glfwSetInputMode(DLib::Input::GetListenWindow(), GLFW_CURSOR, GLFW_CURSOR_DISABLED);
else
    glfwSetInputMode(DLib::Input::GetListenWindow(), GLFW_CURSOR, GLFW_CURSOR_NORMAL);
```
in my focus callback the cursor remains disabled even if I alt+tab. Is this a bug or something I just don't know about?

**Comment by elmindreda** [comment]
If the program hit a breakpoint then by definition execution has stopped, so how would GLFW re-enable the cursor?

**Comment by DavidDanielsson** [comment]
Oh wow, that's embarrassing... Now I feel stupid...

I got so hung up on the problem with my focus callback that I got it into my head that the focus callback would be called when I hit a breakpoint.

**Comment by elmindreda** [comment]
No worries, it happens to us all.

If you replace the body of `disableCursor` for your platform with that of `hideCursor` and recompile GLFW, you should be able to use the mouse during a breakpoint.

**Comment by DavidDanielsson** [comment]
Alright, thank you for the tip!
