### ISSUE TITLE
Iconify function does not work properly

### ISSUE THREAD

**Issue by qirlib** [glfw/glfw#531]
Hello everyone,
I want to iconify a fullscreen window. The problem is when I try to do it, something very strange happens: callback is called, GLFW window loses focus, other windows gain focus, but the black screen - the one that used to represent my fullscreen application - still remains. I mean, I still see my application and I can't see other windows until I do an Alt-Tab.

P. S. Configuration: 2 monitors as 1 window, NVidia drivers 349.16, Linux Mint 17.1 Cinnamon 64-bit (2.4.8), X11
P. P. S. And due to documentation, when glfwIconifyWindow is called, the original video mode should be restored. That does not happen.

**Comment by elmindreda** [comment]
This is related to #405.
