### ISSUE TITLE
key codes on non-us keyboards

### ISSUE THREAD

**Issue by blitz-research** [glfw/glfw#535]
Not sure if this is new to glfw3, but I'm getting reports that the key codes no longer map to correct keys on non-us keyboards. The keyboard docs confirm this, but this is different from glfw2, isn't it?

How do I deal with this? My game framework needs to send key codes to apps in glfw2 (ie: 'localized') format, but there doesn't seem to be an easy way to do this.

edit: OK, I'm not sure glfw2 didn't do this too now, but I still need a way to work out the key hit.

**Comment by elmindreda** [comment]
See #464.
