### ISSUE TITLE
Allow changes to GLFW_DECORATED, GLFW_RESIZABLE and GLFW_FLOATING

### ISSUE THREAD

**Issue by xanather** [glfw/glfw#537]
Right now I see it is not possible to change the state of these window properties after the window has been created. Are there any plans to allow this?

If its possible to prevent an OpenGL context from being recreated, then a worthwhile solution for me could be to recreate the window when one of those properties change. At the moment however recreating the window means recreating the OpenGL context which means reloading all my textures, setting up frame buffers etc... If there is a way to stop the context being deleted and sharing it between windows then please let me know

This framework is fantastic even without this, it's what GLUT should have been, thanks.

**Comment by xanather** [comment]
Just read about context sharing, but not really what I am after and seems to have downsides (unchangable frame buffers and OS X creating a menu). I'll just bite the bullet and reload everything graphics-related when window properties are changed, I'll leave this issue open though since I think GLFW_DECORATE GLFW_RESIZE and full-screen state should be changeable in the future.

**Comment by elmindreda** [comment]
> Right now I see it is not possible to change the state of these window properties after the window has been created. Are there any plans to allow this?

Yes, at some point after glfwSetWindowMonitor and glfwSetWindowSizeLimits, as they intersect.

What are you planning to use it for?

**Comment by xanather** [comment]
Thanks for the reply, it's mainly just being able to have the ability to change change from say fullscreen mode, to windowed mode (with a window border) to fullscreen-windowed mode, etc, without having reload the graphics/window.

**Comment by elmindreda** [comment]
Ah, then you need neither; just #43.

**Comment by xanather** [comment]
I think as long as there would be a settable windowed-borderless option as well for the window mode then yes I think that issue would suffice :), upon realization of that issue, this one could be closed if you want.

**Comment by elmindreda** [comment]
The thing you are likely referring to is [already done automatically](http://www.glfw.org/docs/latest/window.html#window_windowed_full_screen).

**Comment by xanather** [comment]
I know the feature already exists, I am talking about changing between the modes however.

**Comment by elmindreda** [comment]
The window border will be toggled by glfwSetWindowMonitor. Everything will be as if the window was created with that mode.

**Comment by xanather** [comment]
Sounds good, will be interested to try it out when it releases

**Comment by theagentd** [comment]
Is there any chance of getting this change in 3.2? It'd complement the new fullscreen-windowed mode switching features that have just been added really well (thanks a lot for those!).

**Comment by elmindreda** [comment]
@theagentd Not 3.2, possibly 3.3.

**Comment by theagentd** [comment]
Alright, thanks a lot for the info!

**Comment by theagentd** [comment]
Hey, me again. >__> We have decided on a January 2017 release for our game, and we would really like to have a feature to switch between windowed, fullscreen and borderless windowed mode without having to restart for borderless switching. We'd really appreciate if this feature could make it into GLFW by December or so, so that we have time to implement and test it properly! Sorry for double posting!

**Comment by elmindreda** [comment]
@theagentd That shouldn't be a problem.

**Comment by elmindreda** [comment]
@theagentd What platforms are you releasing on?

**Comment by elmindreda** [comment]
@theagentd Implemented for Windows. Other platforms to follow. See `setwindowattrib` branch. API not final (as always up until release).

**Comment by theagentd** [comment]
Awesome! We'll try this out on Windows soon!

**Comment by elmindreda** [comment]
@theagentd Initial implementation for Windows, macOS and X11 available.

**Comment by theagentd** [comment]
Can finally confirm that this seems to be working perfectly well on Windows 7!

**Comment by xanather** [comment]
@elmindreda thanks for this, works good :)
