### ISSUE TITLE
glfwGetWindowFrameSize returns incorrect value on Windows 10.

### ISSUE THREAD

**Issue by xanather** [glfw/glfw#539]
glfwGetWindowFrameSize returns incorrect sizes on windows 10 (larger than they should be).

For a resizable (default) window I get:

Left: 8
Top: 31
Right: 8
Bottom: 8

Windows 10's style has window borders that are only 1 pixel in width/height (excluding the title bar).

I am guessing this is because it may be hard-coded and not updated for Win10 yet?

The Win32 function GetWindowRect can be used for calculating correct sizes of the window border at runtime no matter the windows OS. My D3D11 backend uses this and it works fine on Win10.

**Comment by elmindreda** [comment]
The border size is not hard-coded and border sizes could vary before Windows 10. It is calculated with AdjustWindowRectEx, as you can verify from the source.

This bug is likely a result Microsoft's belief that programs can't handle the truth unless it winks to the OS via yet another back channel.

**Comment by xanather** [comment]
That's odd, my D3D backend also uses AdjustWindowRectEx for correctly sized window creation, will investigate further...

**Comment by xanather** [comment]
Yeah, this is not a problem with GLFW :+1:
