### ISSUE TITLE
Wrong arrow cursor image

### ISSUE THREAD

**Issue by andrewrk** [glfw/glfw#541]
When I use `glfwSetCursor` to set the cursor to a cursor created with `glfwCreateStandardCursor(GLFW_ARROW_CURSOR)` I get this weirdo cursor:

![](http://i.imgur.com/lsS4rdH.png)

But my actual system cursor is:

![](http://i.imgur.com/HQGUe5z.png)

According to the [docs](http://www.glfw.org/docs/latest/group__shapes.html#ga8ab0e717245b85506cb0eaefdea39d0a) this should be getting me "the regular arrow cursor."

This is XFCE 4.12 running on NixOS 15.06pre64030.e1af50c with GLFW 3.1.1.

**Comment by elmindreda** [comment]
See if that helps.

**Comment by andrewrk** [comment]
Fix confirmed. Thanks!

**Comment by andrewrk** [comment]
Oops, I'll leave it to you to close the issue when you merge the code into master.
