### ISSUE TITLE
Move borderless (undecorated) window

### ISSUE THREAD

**Issue by beaucoralk** [glfw/glfw#542]
Hi all,

I come to you, because, since two days I try to Drag'n'Drop my GLFWwindow who are the GLFW_DECORATED to GL_FALSE, with LEFT_CLICK PRESS of MOUSE and the cursorPosCallback.

It work, but my cursor he's all the time on TOP LEFT CORNER of my window : 
```c++
cursorPositionCallback(GLFWwindow* p1Window, double p2CursorXPos, double p3CursorYPos) {
    LOG.info({"MOUSE MOVING ", to_string(cursorXPos), ",", to_string(cursorYPos), " TO ", to_string(p2CursorXPos), ",", to_string(p3CursorYPos)});
    if (glfwGetMouseButton(p1Window, GLFW_MOUSE_BUTTON_LEFT) == GLFW_PRESS) {
        int _windowXPos, _windowYPos, _newWindowXPos, _newWindowYPos;
        glfwGetWindowPos(p1Window, &_windowXPos, &_windowYPos);
        _newWindowXPos = _windowXPos + (int)p2CursorXPos;
        _newWindowYPos = _windowYPos + (int)p3CursorYPos;
        glfwSetWindowPos(p1Window, _newWindowXPos, _newWindowYPos);
    }
    cursorXPos = p2CursorXPos;
    cursorYPos = p3CursorYPos;
}
```

Can you help me please ?
If I change this algorithme to try to move the cursorPos after moving the windowPos, it do bad thing...

Sorry if it's not the good place to answer that, but I need help.

**Comment by beaucoralk** [comment]
My bad, I found, it was me that I do shit...

**Comment by codeyash** [comment]
Correct Solution will help others like me :) If possible please share code.
