### ISSUE TITLE
Disabling cursor defeats glfwWaitEvents

### ISSUE THREAD

**Issue by nanolion** [glfw/glfw#543]
On windows 7 with glfw 3.1.1

While the cursor is DISABLED with glfwSetInputMode() all calls to glfwWaitEvents() return immediately. This does not happen when the cursor is set to NORMAL or HIDDEN.

Since glfw can't wait for events while the cursor is disabled this can be demanding on threaded applications where the cursor is disabled most of the time e.g. for controlling a camera with the mouse.

I used the code below to test this behavior when disabling the cursor the while loops at seemingly unrestrained frequency:

	#include <stdio.h>
	#include <GLFW/glfw3.h>

	int main(int argc, char **argv)
	{
		if( !glfwInit() ) { return -1; }
		GLFWwindow* window = glfwCreateWindow( 500, 500, "WaitForEvents", NULL, NULL );
		if( !window ) { glfwTerminate(); return -1; }
		glfwMakeContextCurrent( window );

		glfwSetInputMode( window, GLFW_CURSOR, GLFW_CURSOR_DISABLED );
		
		int counter = 0;
		while( !glfwWindowShouldClose( window ) )
		{
			printf( "%i\n", ++counter );
			glfwWaitEvents();
		}
		return 0;
	}

Also I noticed calling glfwSetCursorPos() some short time before glfwWaitEvents() will prevent waiting for events too. If this is expected how would I disable the mouse and efficiently wait for events?

**Comment by elmindreda** [comment]
This was broken in 3.1.

**Comment by elmindreda** [comment]
> Also I noticed calling glfwSetCursorPos() some short time before glfwWaitEvents() will prevent waiting for events too. If this is expected how would I disable the mouse and efficiently wait for events?

The process will be woken when the mouse moved regardless of what GLFW does with the cursor motion event. If you want to wait for a specific kind of event, I suggest calling `glfwWaitEvents` until it arrives.
