### ISSUE TITLE
glfwSetKeyCallback registering key events as char events

### ISSUE THREAD

**Issue by romanlarionov** [glfw/glfw#548]
Since the last release, as far as I can tell, something went wrong with the key callback function. 
I am running Ubuntu 14.04 with a GTX 970.

This is the output of `nvidia-smi` : 

Mon Jul  6 20:42:28 2015       
+------------------------------------------------------+                       
| NVIDIA-SMI 343.19     Driver Version: 343.19         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 970     Off  | 0000:01:00.0     N/A |                  N/A |
| 32%   33C    P8    N/A /  N/A |    272MiB /  4095MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Compute processes:                                               GPU Memory |
|  GPU       PID  Process name                                     Usage      |
|=============================================================================|
|    0            Not Supported                                               |
+-----------------------------------------------------------------------------+

My key callback function works perfectly on OS X 10.10, but fails specifically on my ubuntu machine.
I traced through the glfw code to see where the problem was and found that when I would press keys (W, A, S, D, etc.) the event handler found them to be 'chars' within the processEvent function in x11_window.c. 

I managed to solve my issue by checking out to glfw version 3.1.1.

**Comment by elmindreda** [comment]
Are you using an input method, and if so which one?

Please post the `events` log of you pressing a key.

**Comment by Spasi** [comment]
[Sounds like](http://forum.lwjgl.org/index.php?topic=5850.msg31209#msg31209) one of our users has the same issue. LWJGL uses a GLFW build with the latest changes too.

**Comment by elmindreda** [comment]
That's adventurous of them.

**Comment by romanlarionov** [comment]
This is what happens when I run the events executable from command line:

```
00000005 to 1 at 1.554: Character 0x00000077 (w) with modifiers (with no mods) input
00000006 to 1 at 1.554: Character 0x00000077 (w) input
00000007 to 1 at 1.850: Character 0x00000061 (a) with modifiers (with no mods) input
00000008 to 1 at 1.850: Character 0x00000061 (a) input
00000009 to 1 at 2.154: Character 0x00000073 (s) with modifiers (with no mods) input
0000000a to 1 at 2.154: Character 0x00000073 (s) input
0000000b to 1 at 2.450: Character 0x00000064 (d) with modifiers (with no mods) input
0000000c to 1 at 2.450: Character 0x00000064 (d) input
0000000d to 1 at 2.722: Character 0x00000077 (w) with modifiers (with no mods) input
0000000e to 1 at 2.722: Character 0x00000077 (w) input
0000000f to 1 at 3.042: Character 0x00000061 (a) with modifiers (with no mods) input
00000010 to 1 at 3.042: Character 0x00000061 (a) input
00000011 to 1 at 3.330: Character 0x00000073 (s) with modifiers (with no mods) input
00000012 to 1 at 3.330: Character 0x00000073 (s) input
00000013 to 1 at 3.586: Character 0x00000064 (d) with modifiers (with no mods) input
00000014 to 1 at 3.586: Character 0x00000064 (d) input
```

While this is the output for glfw 3.1.1:

```
00000005 to 1 at 1.555: Key 0x0057 Scancode 0x0019 (W) (with no mods) was pressed
00000006 to 1 at 1.555: Character 0x00000077 (w) with modifiers (with no mods) input
00000007 to 1 at 1.555: Character 0x00000077 (w) input
00000008 to 1 at 1.691: Key 0x0057 Scancode 0x0019 (W) (with no mods) was released
00000009 to 1 at 1.907: Key 0x0041 Scancode 0x0026 (A) (with no mods) was pressed
0000000a to 1 at 1.907: Character 0x00000061 (a) with modifiers (with no mods) input
0000000b to 1 at 1.907: Character 0x00000061 (a) input
0000000c to 1 at 2.019: Key 0x0041 Scancode 0x0026 (A) (with no mods) was released
0000000d to 1 at 2.235: Key 0x0053 Scancode 0x0027 (S) (with no mods) was pressed
0000000e to 1 at 2.235: Character 0x00000073 (s) with modifiers (with no mods) input
0000000f to 1 at 2.235: Character 0x00000073 (s) input
00000010 to 1 at 2.363: Key 0x0053 Scancode 0x0027 (S) (with no mods) was released
00000011 to 1 at 2.643: Key 0x0044 Scancode 0x0028 (D) (with no mods) was pressed
00000012 to 1 at 2.643: Character 0x00000064 (d) with modifiers (with no mods) input
00000013 to 1 at 2.643: Character 0x00000064 (d) input
00000014 to 1 at 2.763: Key 0x0044 Scancode 0x0028 (D) (with no mods) was released
00000015 to 1 at 3.131: Key 0x0057 Scancode 0x0019 (W) (with no mods) was pressed
00000016 to 1 at 3.131: Character 0x00000077 (w) with modifiers (with no mods) input
00000017 to 1 at 3.131: Character 0x00000077 (w) input
00000018 to 1 at 3.267: Key 0x0057 Scancode 0x0019 (W) (with no mods) was released
00000019 to 1 at 3.459: Key 0x0041 Scancode 0x0026 (A) (with no mods) was pressed
0000001a to 1 at 3.459: Character 0x00000061 (a) with modifiers (with no mods) input
0000001b to 1 at 3.459: Character 0x00000061 (a) input
0000001c to 1 at 3.603: Key 0x0041 Scancode 0x0026 (A) (with no mods) was released
0000001d to 1 at 3.819: Key 0x0053 Scancode 0x0027 (S) (with no mods) was pressed
0000001e to 1 at 3.819: Character 0x00000073 (s) with modifiers (with no mods) input
0000001f to 1 at 3.819: Character 0x00000073 (s) input
00000020 to 1 at 3.931: Key 0x0053 Scancode 0x0027 (S) (with no mods) was released
00000021 to 1 at 4.115: Key 0x0044 Scancode 0x0028 (D) (with no mods) was pressed
00000022 to 1 at 4.115: Character 0x00000064 (d) with modifiers (with no mods) input
00000023 to 1 at 4.115: Character 0x00000064 (d) input
00000024 to 1 at 4.227: Key 0x0044 Scancode 0x0028 (D) (with no mods) was released
```

Also, I don't know what you mean by  input method. I set a key callback function within my code, that I then use to fill a `key_pressed_tracker_` boolean array, but the callback function is never even entered.

**Comment by arisudesu** [comment]
I second this issue. Latest changes with XIM detection broke the callback for keys. Only the characters callback is called. But all works fine on 3.1.1-release.

**Comment by Dav1dde** [comment]
A user on IRC reported an Issue that the ESC key event did not register, I found out that commit cf4206d987d8b74964b11d1ccac38efddc0b7684 broke the ESC key event.

Reproduce: launch `events` and press the ESC key. I assume this is related to this issue.

**Comment by Muzza** [comment]
I've experienced this too.
Using the current master branch, keyboard input is broken on SteamOS, but works on Ubuntu 14.
v3.1.1 works on both.

**Comment by elmindreda** [comment]
Which [input method](https://en.wikipedia.org/wiki/Input_method) frameworks are you all using?

**Comment by dprandle** [comment]
Cloned and built master branch and key callback is not called for me as well. Using linux mint 17.1 Rebecca. I verified event output as shown in previous post (ie event test never calls key callback). Also verified with qt creator debugger that all other callbacks do fire - its only the key callback

**Comment by romanlarionov** [comment]
I use a standard English QWERTY keyboard layout with X11 on Ubuntu 14.04 for an input method.

**Comment by wjh** [comment]
[This](https://github.com/glfw/glfw/commit/cf4206d987d8b74964b11d1ccac38efddc0b7684) commit seems to be what broke it, on my system at least - Arch Linux, i3 window manager. I'll have a look to see if I can make a PR to fix it.

**Comment by elmindreda** [comment]
What is the `XMODIFIERS` environment variable set to on your machines?

**Comment by elmindreda** [comment]
Please try the `ximfilter` branch.
