### ISSUE TITLE
win32-glfw3.1.1，glTranslatef函数对z轴无效

### ISSUE THREAD

**Issue by jwcpp** [glfw/glfw#549]
win32+vs2013+glfw3.1.1
glTranslatef(0.0,0.0,-5.0);
设置z轴后，屏幕一片空白......什么都不显示了

**Comment by hypernewbie** [comment]
你有没有用compatibility context(兼容模式）? 检查一下glGetError(）怎么说。
新的GL没有glTranslate, 已经被淘汰了

**Comment by jwcpp** [comment]
#include <stdio.h>
#include <stdlib.h>
#include "glfw3.h"
#include <Windows.h>
#include <gl\GL.h>
#include <gl\GLU.h>

int main(void)
{
	GLFWwindow* window;

	/* Initialize the library */
	if (!glfwInit())
		return -1;

	glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
	glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 1);
	//glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
	//glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
	
	/* Create a windowed mode window and its OpenGL context */
	window = glfwCreateWindow(640, 480, "Hello World", NULL, NULL);
	if (!window)
	{
		glfwTerminate();
		return -1;
	}

	/* Make the window's context current */
	glfwMakeContextCurrent(window);

	/* Loop until the user closes the window */
	while (!glfwWindowShouldClose(window))
	{
		/* Render here */
		glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
		glLoadIdentity();
		// Move down the z-axis.
		//glTranslatef(0.0, 0.0, -2.0);

		glBegin(GL_TRIANGLES);

		glColor3f(1.0, 0.0, 0.0);    // Red
		glVertex3f(0.0, 1.0, 0.0);

		glColor3f(0.0, 1.0, 0.0);    // Green
		glVertex3f(-1.0, -1.0, 0.0);

		glColor3f(0.0, 0.0, 1.0);    // Blue
		glVertex3f(1.0, -1.0, 0.0);

		glEnd();

		/* Swap front and back buffers */
		glfwSwapBuffers(window);

		/* Poll for and process events */
		glfwPollEvents();

	}

	glfwTerminate();
	return 0;
}

刚学习glfw3,.....新手一枚。
glTranslatef(0.0, 0.0, -2.0);
为啥一加这句就什么也不显示了呢？

**Comment by tombsar** [comment]
This is not an issue with glfw.

Since you're drawing in screen-coordinates, anything outside the range -1 to +1 will be clipped. I suggest you read some tutorials on how to use OpenGL.

**Comment by hypernewbie** [comment]
tombsar说的对。你没有设定投影矩阵(perspective matrix)，所以Z轴方面的移动一点给都没有效果。则不是glfw的问题，是你没有正确使用GL。

**Comment by jwcpp** [comment]
谢谢大家的帮助

**Comment by jaredjones** [comment]
I never knew that Chinese was a language that everyone spoke on Github...?

**Comment by tombsar** [comment]
I just used Google translate...

**Comment by slitazcn** [comment]
中文也有回应啊，不错啊，建议用glew，gl.h支持的opengl版本太低了，只有1.2还有在这里最好说英文的

**Comment by hypernewbie** [comment]
I think we can close this one; OP question answered.
