### ISSUE TITLE
Support for EXT_framebuffer_sRGB

### ISSUE THREAD

**Issue by fastmarch** [glfw/glfw#553]
Hi -- despite having a very recent NVIDIA GPU and driver, there is no support for WGL_ARB_framebuffer_sRGB, only WGL_EXT_framebuffer_sRGB.  As such, I cannot create an sRGB backbuffer.  Adding support looks pretty straightforward, I'd be happy to do it if it would be accepted.  I'd also potentially say that it's extremely likely all drivers that support WGL_EXT_framebuffer_sRGB will support WGL_ARB_framebuffer_sRGB, so just swapping the extension would be simpler.

**Comment by elmindreda** [comment]
That sounds very strange. Have you updated your drivers?

**Comment by elmindreda** [comment]
Are you creating an OpenGL ES context?

**Comment by fastmarch** [comment]
Yes, and no.

**Comment by elmindreda** [comment]
Fixed with 04c057238b422785b487d32b5d4865511b20f2f7.
