### ISSUE TITLE
Support for window size limits

### ISSUE THREAD

**Issue by xanather** [glfw/glfw#555]
Is it possible to have such a function (doesn't have to be exact name)?

On Windows WM_GETMINMAXINFO wnd msg needs to be handled, not sure about other platforms.

**Comment by elmindreda** [comment]
This is already in `devel` and will be in 3.2.

**Comment by elmindreda** [comment]
The function is `glfwSetWindowSizeLimits`.

**Comment by xanather** [comment]
Okay thanks for that, I will compile the dev source for now so I can use the function straight away

**Comment by xanather** [comment]
I think the devel branch is unstable, I am unable to create a window, glfwCreateWindow always crashes me. Compiling glfw with exact same methods for the master branch is fine.

**Comment by elmindreda** [comment]
It is, yes.

**Comment by theagentd** [comment]
This is something we need to ensure our game window isn't made too small. Currently adding a size listener which calls glfwSetWindowSize() if the size is too small works, but is hackish.

**Comment by theagentd** [comment]
Can confirm that this is working as intended. Thanks!
