### ISSUE TITLE
Win32 Modal Loop

### ISSUE THREAD

**Issue by xanather** [glfw/glfw#561]
Due to the Win32 modal message loop whenever the window is being dragged or resized the rendering/updating stops due to the thread being locked in the glfwPollEvents() function.

The Win32 implementation should call the WindowRefreshCallback whenever the window is in a modal loop. It is possible through the use of Win32 timers and dispatching constant WM_TIMER events (Windows supports a rate greater than 60 FPS with this).

I am unsure how glfw handles this on other platforms but I am willing to implement this on Windows at-least since I have it already done on in my own code for the Direct3D back-end and it works well.

I'll test to see what happens when dragging/resizing on other platforms soonish.

**Comment by elmindreda** [comment]
If you want to keep rendering while the window is being moved, do it from another thread.

**Comment by xanather** [comment]
Is that really the only option? I prefer not to have a separate thread to do this.

I will fork and add support for it since is quite straightforward, I'll link the changes here and let you decide since I think it fits well with the definition of WindowRefreshCallback (contents of the window become outdated when dragging).

**Comment by elmindreda** [comment]
Any serious game or tool should already be multi-threaded nowadays and any toy program can probably do without rendering during window dragging.

**Comment by shurcooL** [comment]
> Any serious game or tool should already be multi-threaded nowadays and any toy program can probably do without rendering during window dragging.

I agree. As far as I know, there's no better solution because the Win32 API is the way it is.

**Comment by xanather** [comment]
https://github.com/xanather/glfw/commit/7b205ed2dea4ab78d9781377aece9c19f1cd217f Opinion? It's fine if you'd prefer not to have it added to the main repo. I'll just use it locally for now.

**Comment by elmindreda** [comment]
I won't be merging this. Multi-threading is the robust solution and adds just a few lines in its simplest form.

**Comment by shurcooL** [comment]
> Multi-threading is the robust solution and adds just a few lines in its simplest form.

Does one of the examples demonstrate this?

**Comment by elmindreda** [comment]
@shurcooL https://github.com/glfw/glfw/blob/master/tests/threads.c

**Comment by xanather** [comment]
Multhi-threading is an overkill for a lightweight 2D engine/spritebatcher like mine, there is also a reason why I didn't even bother implementing it for my Direct3D backend as described here https://msdn.microsoft.com/en-us/library/windows/desktop/ee417025.aspx#Multithreading_and_DXGI. Would OpenGL/glfw be affected by anything like this? Synchronizing all possible input and windowing events doesn't seem worth it and I think actually has the tendency to increase input lag. I am sure many apps would be bottle-necked by the GPU first and the CPU time wasted on PollEvents is negligible.

**Comment by MirrasHue** [comment]
I got curious and tried to add you solution (since it's very short) to an older project of mine, using GLFW 3.4, and it didn't work. I wonder if it's because of the many changes to GLFW since then, it's been almost 10 years, jeez
