### ISSUE TITLE
Triple Buffering

### ISSUE THREAD

**Issue by alexge50** [glfw/glfw#563]
As Double Buffering is an enchantment over Single Buffering, Triple Buffering is an enchantment over Double Buffering because Triple Buffering would reduce screen tearing. More information: http://www.anandtech.com/show/2794/2
I found Triple Buffering very useful, so would be useful for some users to have this option.

**Comment by slimsag** [comment]
From https://www.opengl.org/wiki/Common_Mistakes#Triple_Buffering

> You cannot control whether a driver does triple buffering. You could try to implement it yourself using a FBO. But if the driver is already doing triple buffering, your code will only turn it into quadruple buffering. Which is usually overkill.

**Comment by mirh** [comment]
Driver might even do triple buffering (if user forces it, for the records), but after #516 without some sort of decoupling between compositor and program, this gets "frame locked".
