### ISSUE TITLE
When released, modifier keys held during window creation are reported as pressed

### ISSUE THREAD

**Issue by GHF** [glfw/glfw#566]
Reproducible on OS X 10.10.4 for GLFW 3.1.1 and the latest in master:

1. Hold down any (up to all) modifier keys
2. Launch `tests/events`
3. Release modifier key(s) after window is created and in focus

Results:

```
xw@Lotus ~/glfw> ./tests/events
Library initialized
Creating windowed mode window 1 (640x480)
Main loop starting
00000000 to 1 at 0.145: Window focused
00000001 to 1 at 0.680: Key 0x0154 Scancode 0x0038 (LEFT SHIFT) (with no mods) was pressed
```

I looked into the Cocoa logic (I haven't tried this on any other platform) and there's a few ways for it break:

1. It looks like the modifiers are initialized to zero upon window creation and not to the user state.
2. The modifier key logic detects changes over the entire `NSEvent modifierFlags` vector, not just the one corresponding to the relevant key in `NSEvent keyCode`. This makes it harder to fix the case of multiple simultaneous modifiers (e.g. CTRL+SHIFT) while the window opens.
3. Left/right modifier handling is done by toggling the corresponding key's state when a `flagsChanged` comes in with no change in flags. This should instead be, "with no change in flags and the corresponding `modifierFlags` bit set," since if the mod bit is clear it doesn't make sense to report a key pressed event.

**Comment by GHF** [comment]
I don't really need to know which modifier keys are held while a window opens, but reporting a modifier key press when it's released causes a logic flip for any applications doing their own bookkeeping for modifier states, like imgui now does: https://github.com/ocornut/imgui/pull/183

I'd be OK with the application not knowing about the initially held modifiers nor the first modifier key releases.

The alternative is reporting the held modifiers, but it's impossible to know what key caused it and there isn't a callback for reporting *only* modifiers. It'd be extra complexity for very little gain.

**Comment by elmindreda** [comment]
Seemed easier to just update the cache whenever the window becomes key.
