### ISSUE TITLE
Move glfwSwapBuffer sleep time.

### ISSUE THREAD

**Issue by zgron** [glfw/glfw#569]
As I have noticed, if I'm not misstaken the glfwSwapBuffer puts the thread to sleep a certain time before it swaps the buffer to not exceed a certain refresh rate. However because of that my program now has a < 1/60 seconds delay between whiched rendering and actuall rendering, which causes moving stuff with the mouse to look very bad synced. However if the sleep would be put after the swap, to still make the whole loop fullfill the time needed for the refresh rate too be as it should. The rendering would be much more instant. I for myself added such a sleep behind the glfwSwapBuffer, so that the glfwSwapBuffer itself wouldn't have to sleep next time. The differens was tremendous and the experience from the mouse now appears to be almost instant: I just think such a future should be standarized. But maybe the sleep is something the monitor does and it is not possible to change that through glfw, which would mean people should just go along with my solution instead.

**Comment by shurcooL** [comment]
> if I'm not misstaken the glfwSwapBuffer puts the thread to sleep a certain time before it swaps the buffer to not exceed a certain refresh rate.

Are you familiar with [`glfwSwapInterval`](http://www.glfw.org/docs/latest/group__context.html#ga6d4e0cdf151b5e579bd67f13202994ed)?

> #### void glfwSwapInterval	(	int 	interval	)	
>
> This function sets the swap interval for the current context, i.e. the number of screen updates to wait from the time `glfwSwapBuffers` was called before swapping the buffers and returning. This is sometimes called _vertical synchronization_, _vertical retrace synchronization_ or just _vsync_.

**Comment by zgron** [comment]
Hmm so it only swap buffer whenever the monitor refreshes?

**Comment by leestripp** [comment]
Is this correct, that swap buffer uses a wait call?? If so then you need to rewrite glfw to not do this... It would explain why I only get 60fps even when my refresh rate is set to 120hz

**Comment by tombsar** [comment]
@leestripp You can view the code yourself: https://github.com/glfw/glfw/blob/3d62c9ed9d1ba4c6c285248d839c17bc5c5028f7/src/context.c#L606 glfw doesn't explicitly put the thread to sleep; it just delegates swapping to the underlying graphics stack.

That said, there is some kind of a busy-wait loop happening on Windows (https://github.com/glfw/glfw/blob/3d62c9ed9d1ba4c6c285248d839c17bc5c5028f7/src/wgl_context.c#L260), but only when using compositing and the window is not fullscreen.

**Comment by leestripp** [comment]
Thanks for the response, I'm currently writing some tests for GLFW, SDL2 and SFML to sort out where this issue is coming from. I have a similar issue on Antergos Linux but need to do more testing to figure it out.
I will check out the source if the tests don't show anything.

Cheers
Lee

**Comment by zgron** [comment]
Hmm I believe this is a very old post. However if this is what I think it
is, my suggestion was that as it looks now, when I'm making a game I update
then wait < 1/60 sec for the frame too update which means whenever the draw
is made we have a slight delay of < 1/60 seconds between the update and the
draw.

My suggestion was too move that delay until after the draw was done so that
the entire frame still takes 1/60 seconds but will make the update and draw
MUCH MUCH MUCH corelational and smoother. This is for example super
appearant when one tries to drag something rendered through opengl with the
hardware cursor.

I confirmed my theory myself through putting the thread to sleep about 1/60
seconds before updating so that the draw will come instantaneously after my
update.

2016-08-29 15:55 GMT+02:00 Lee Stripp <notifications@github.com>:

**Comment by tombsar** [comment]
@zgron If I understand correctly, what you are doing is *adding* delay to your code so that your update happens as close to the next vsync as possible. This approach is valid for reducing input latency. However, the risk of doing this is that if your sleep takes a bit too long (poor timer resolution on some platforms), or your update code takes too long to run, and you over-shoot the target 1/60 seconds, the swapBuffers call will block until the *next* vsync period, causing a full 1/60 second delay.

I don't think this is an issue with glfw, so I suggest that further questions be directed at the forum: http://discourse.glfw.org/. That is, unless @leestripp uncovers something else.

**Comment by zgron** [comment]
I see your point @Tombs, I suppose that you can always compensate with a lower delay or none if the previous one would take too long time. Since the goal is to not start the update until the next 1/60 second stamp begins. I drew a time line and I don't see how that problem could occur with my suggestion compared to how it currently is.

**Comment by leestripp** [comment]
I misunderstood this as being that GLFW had a wait call. So my issue is
different. I'll open a new issue once I find out why its happening.

@zgron If you have zSync working correctly there is no need for a wait in
your app.

**Comment by leestripp** [comment]
All tests run show this was not a GLFW problem. It also happens in fullscreen mode, vSync on, 120hz using SDL2

**Comment by leestripp** [comment]
## Just finished tests using SFML. It does NOT have this issue.

**Comment by codedcosmos** [comment]
I am having similar problem, with the in Java with LWJGL. I am able to fix the issue with glfwSwapInterval(0); but that removes vsync. Not an ideal compromise.
