### ISSUE TITLE
Key callback doesn't work

### ISSUE THREAD

**Issue by boddicheg** [glfw/glfw#573]
I dont know why, but when I compile glfw3 from sources 
```
cd glfw/
cmake .
make && sudo make install
```
... and use simple example:
```
CC = g++
CFLAGS = -std=c++11 -Wall -g -pedantic
LFLAGS = -lm -lGL -lGLU -lX11 -lXxf86vm -lXrandr -lpthread -lXi -ldl -lXinerama -lXcursor
GLFW = -L/usr/local/lib -lglfw3
...
```

```cpp
#include <iostream>
#include <GLFW/glfw3.h>

using namespace std;

void key_callback(GLFWwindow* window, int key, int scancode, int action, int mods) {
  cout << "Key: " << char(key) << endl;
}

int main(void) {
  GLFWwindow* window;

  if (!glfwInit()) {
    return -1;
  }

  window = glfwCreateWindow(640, 480, "Hello World", NULL, NULL);
  if (!window) {
    glfwTerminate();
    return -1;
  }

  glfwMakeContextCurrent(window);
  // !!!
  glfwSetKeyCallback(window, key_callback);

  while (!glfwWindowShouldClose(window)) {
    glfwSwapBuffers(window);
    glfwPollEvents();
  }
  glfwTerminate();
  return 0;
}
```

When i'm running an app, and press key, nothing is happened.

p.s.: sorry for my english
Thanks!

**Comment by shurcooL** [comment]
Try the `events` test in `tests` folder. Does it work?

**Comment by boddicheg** [comment]
@shurcooL, 
After compiling events.c: 
./events
```
000000de to 1 at 57.621: Character 0x00000064 (d) with modifiers (with no mods) input
000000df to 1 at 57.621: Character 0x00000064 (d) input
```
I am confused,  because my test app still not working and i dont know why

**Comment by elmindreda** [comment]
@boddicheg Is that an official release or a repo snapshot? A bug similar to what you describe was just fixed in `master`.

**Comment by boddicheg** [comment]
@elmindreda, repo snapshot
```
git clone git@github.com:glfw/glfw.git
cd glfw/
cmake .
make && sudo make install
```
Thanks, i am trying to reproduce bug in 3.1.1 release

**Comment by boddicheg** [comment]
Works on 3.1.1. Thanks a lot

**Comment by elmindreda** [comment]
@boddicheg What is the `XMODIFIERS` environment variable set to?

**Comment by boddicheg** [comment]
@elmindreda,
```
$ echo $XMODIFIERS
@im=none
```

**Comment by elmindreda** [comment]
@boddicheg Thank you. The snapshot you used at first, which commit is it on?

**Comment by boddicheg** [comment]
@elmindreda, last commit on Jul 21, 2015, [460e5d7] (https://github.com/glfw/glfw/commit/460e5d792dac0d2de16ba0a38a1181a1e4340f2c)

**Comment by elmindreda** [comment]
@boddicheg Do you have time to test an up-to-date repo snapshot? The bug should be fixed as of 527952102a13d0caad479a75a4385950f10d79d7.

**Comment by boddicheg** [comment]
@elmindreda, pull last changes and test. Works perfect:)

**Comment by elmindreda** [comment]
@boddicheg Thank you for testing.
