### ISSUE TITLE
translateKey function exists in multiple files

### ISSUE THREAD

**Issue by pquiring** [glfw/glfw#574]
I'm tring to compile GLFW monolithic style (including all .c files into one file).
My development environment is Java so makefiles are not possible, I execute gcc directly.
It works under Windows.
Under Linux the function translateKey() is declared in two files:
  x11_window.c and x11_init.c
Could you give one a slightly different name?

Thanks.

**Comment by elmindreda** [comment]
There is no reason to ever do this.

**Comment by pquiring** [comment]
No worries, I just place a #define translateKey translateKey2 before including the 2nd file and it works.

**Comment by andrewrk** [comment]
It's unreasonable to ask a project to have every static function be named differently, considering the very point of `static` is to localize the function and not let it be exposed outside the file that it's in.

**Comment by pquiring** [comment]
Some projects do offer a monolithic option.
Anyways, not a problem since there is a simple workaround.

**Comment by elmindreda** [comment]
@pquiring I misread your issue at first. If this really is the only thing preventing a monolithic build then I see no reason not to fix it. Might not get to it today, though.

**Comment by pquiring** [comment]
Ok, thanks.  I'm not releasing my project for a while so there's no rush.
