### ISSUE TITLE
Wrong window/framebuffer size for windowed fullscreen in Gnome 3

### ISSUE THREAD

**Issue by gustafullberg** [glfw/glfw#575]
When creating a "windowed full screen" window as described in the GLFW Window guide on a monitor with resolution 1920x1080, I end up with a window that covers the whole screen but glfwGetWindowSize and glfwGetFramebufferSize returns a size of 1920x1016. The size of the missing area seems to be of the same size as the Gnome top panel and a normal window title bar.

If i set the window hint GLFW_DECORATED to GL_FALSE (which should not affect fullscreen windows), I end up with a resolution of 1920x1053. The missing area now seems to be of the same size as the Gnome top panel only.

Interestingly, if I disable the call to glClear in glfwCreateWindow the window is created at the full resolution (1920x1080). Adding a delay (like sleep(1) ) before the call to glClear also helps.

Is glClear somehow called before the window system is "ready"?

This is how the window is created:
    GLFWmonitor* monitor = glfwGetPrimaryMonitor();
    const GLFWvidmode* mode = glfwGetVideoMode(monitor);
    glfwWindowHint(GLFW_RED_BITS, mode->redBits);
    glfwWindowHint(GLFW_GREEN_BITS, mode->greenBits);
    glfwWindowHint(GLFW_BLUE_BITS, mode->blueBits);
    glfwWindowHint(GLFW_REFRESH_RATE, mode->refreshRate);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
    window = glfwCreateWindow(mode->width, mode->height, "Game", monitor, NULL);
    glfwMakeContextCurrent(window);

I am using Arch Linux, Gnome 3.16, Intel graphics.
Works fine on Windows.

**Comment by gustafullberg** [comment]
Mini test program:
```
#include <GLFW/glfw3.h>
#include <stdio.h>

int main()
{
    glfwInit();

    GLFWmonitor* monitor = glfwGetPrimaryMonitor();
    const GLFWvidmode* mode = glfwGetVideoMode(monitor);
    glfwWindowHint(GLFW_RED_BITS, mode->redBits);
    glfwWindowHint(GLFW_GREEN_BITS, mode->greenBits);
    glfwWindowHint(GLFW_BLUE_BITS, mode->blueBits);
    glfwWindowHint(GLFW_REFRESH_RATE, mode->refreshRate);
    GLFWwindow *window = glfwCreateWindow(mode->width, mode->height, "Test", monitor, NULL);
    glfwMakeContextCurrent(window);
    
    int w,h;
    glfwGetFramebufferSize(window, &w, &h);
    printf("w: %d, h: %d\n", w, h);

    glfwDestroyWindow(window);
    glfwTerminate();
    return 0;
}
```

Thanks

**Comment by gustafullberg** [comment]
Seems like it happens in KDE aswell, albeit not as often. I end up with a resolution of 1920x1021.

**Comment by elmindreda** [comment]
A desktop system on X11 is very asynchronous, with the application, server, window manager and compositor often being separate processes all communicating over the X11 protocol. It may take a few ms for everything to settle down and the final window size to be reached. __Don't sleep while this is happening__. Process events as usual and the final size will arrive.

**Comment by elmindreda** [comment]
The part with `GLFW_DECORATED` affecting full screen windows is a bug. I'll have a fix for it shortly.

**Comment by elmindreda** [comment]
Run `iconify -f` (quit with Escape) and look at its output.

**Comment by elmindreda** [comment]
If you are using a deferred renderer or similar tech where resizing is very expensive, you should be able to assume that windowed full screen will succeed (eventually) and create your FBOs accordingly.

**Comment by gustafullberg** [comment]
Thanks for quick and helpful replies!
I never realized that the size of the full screen window could change after creation. "iconify -f" shows clearly that this is the case (window created at 1920x1016 and then resized to 1920x1080). I will implement the necessary callback in my game to handle the framebuffer size changes.

Perhaps we could mention somewhere in the docs that the window size might change shortly after creation? I am probably not the only one that will be surprised..

The problem with assuming that the windowed full screen will succeed eventually is that one still doesn't know the final size of the framebuffer (which might be different from the window size).   

Thanks again and keep up the excellent work!

Closing issue.
