### ISSUE TITLE
Use loadImage instead of LoadIcon

### ISSUE THREAD

**Issue by xanather** [glfw/glfw#585]
The https://github.com/glfw/glfw/blob/362751e4efe75649db0b9a92575b5da6dbcc38ce/src/win32_window.c line uses LoadIcon instead of LoadImage. LoadIcon is now deprecated according to MS docs https://msdn.microsoft.com/en-us/library/windows/desktop/ms648072%28v=vs.85%29.aspx. LoadIcon also does not work with .ico files.

If I submit a change to use the LoadImage instead of LoadIcon would it be used? This would allow for icons of multiple sizes.

LoadImage MS docs:
https://msdn.microsoft.com/en-us/library/windows/desktop/ms648045%28v=vs.85%29.aspx

**Comment by xanather** [comment]
https://github.com/xanather/glfw/commit/911f0fe887b026d9045daee8e003f2ebaf04b158

Send us a message if you would like me to submit a PR for those changes, could also do yourself since its only a few lines, either way those changes work good. Not to mention the implementation will still support loading a GLFW_ICON bmp resource (though it attempts .ico first).

**Comment by elmindreda** [comment]
Sorry, just finishing up 3.1.2. Will revisit this once it's out.
