### ISSUE TITLE
Crash in _glfwRefreshContextAttribs

### ISSUE THREAD

**Issue by Sly14** [glfw/glfw#586]
Information:
- Build version is from 2015/08/25
- Tested with Power VR SDK and Google Angle
- Window with EGL

I'm trying to make a version that use GLES 2.0 on Windows.
After tracing, context and a surface is ok.
But its crashing in _glfwRefreshContextAttribs.

The reason is that glfwGetProcAddress for glGetIntegerv/glGetString/glClear return NULL
I don't know why.

Sylvain.

**Comment by elmindreda** [comment]
Which commit are you on?

**Comment by Sly14** [comment]
On the latest : ba4504a9c7e053e688d201a22e4d37fcf93f9bca

**Comment by elmindreda** [comment]
This shouldn't have worked before either. GLFW only uses `eglGetProcAddress`, which does not return the addresses of core functions.

I've been working on a patch for this, as a companion to 7e13a4909e9ac0b4ae82b94cc31dcff93464b748. It'd be very helpful to know all the various file names for client libraries in the various SDKs you use, to make the dynamic loading more robust.

**Comment by Sly14** [comment]
i'm working with PowerVR SDK 3.5
Libs used:
    Path: PowerVR_SDK\SDK_3.5\Builds\Windows\x86_64\Lib  
    Files: libEGL.dll, libGLESv2.dll

Headers used:
    Path: PowerVR_SDK\SDK_3.5\Builds\Include
    Files: all files in this folders (EGL|GLES|GLES2|KHR)

**Comment by elmindreda** [comment]
Please try the `dynamic-client` branch.

**Comment by Sly14** [comment]
I've tested with the sample heightmap.
i've just added this line to choose the appropriate GLES version:

glfwWindowHint(GLFW_CLIENT_API, GLFW_OPENGL_ES_API);
glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 2);
glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 0);

and updated the shader to be compatible with GLES 2.0.

All works fine.
Thanks!

**Comment by elmindreda** [comment]
Excellent. Thank you for testing!
