### ISSUE TITLE
glfwSwapInterval negative values causes almost infinity loop

### ISSUE THREAD

**Issue by verybigbadboy** [glfw/glfw#587]
platform: windows 8

reason of negative value is comment near glfwSwapInterval  function:
 *  Contexts that support either of the `WGL_EXT_swap_control_tear` and
 *  `GLX_EXT_swap_control_tear` extensions also accept negative swap intervals,

code:
https://github.com/glfw/glfw/blob/master/src/wgl_context.c#L605

**Comment by elmindreda** [comment]
Thank you!
