### ISSUE TITLE
Joypad connection/disconnection not discovered

### ISSUE THREAD

**Issue by sulewicz** [glfw/glfw#588]
Hi,

It seems that at the moment connected joypads are discovered only during GLFW initialization.
glfwJoystickPresent function always reflects the initial state, it is impossible to detect that the user disconnected the joypad or connected a new one.
I have this issue on OSX, but I think it will apply to every platform.

Cheers,
Sz

**Comment by elmindreda** [comment]
What version of GLFW are you using?

**Comment by sulewicz** [comment]
I am using GLFW 3.1.1.
Additionally I am using XBox 360 Wireless joypad for testing.

**Comment by elmindreda** [comment]
This is fixed in `master`.

**Comment by sulewicz** [comment]
Thank you! I'll give it a try and get back to you tomorrow.

**Comment by sulewicz** [comment]
Works perfectly! Thanks!
