### ISSUE TITLE
glfwIconifyWindow does not restore the desktop video mode if GLFW_AUTO_ICONIFY is disabled

### ISSUE THREAD

**Issue by theagentd** [glfw/glfw#590]

**Comment by theagentd** [comment]
Wow, that was fast! Thanks a lot! I will verify the fix as soon as possible.

**Comment by theagentd** [comment]
I just tried this out. Although the video mode is restored when the fullscreen windows are iconified, the fullscreen windows suddenly appear as borderless windows on the screen, and they won't go back to fullscreen again when they are restored/uniconified.

**Comment by elmindreda** [comment]
@theagentd The current branch may work better.

**Comment by elmindreda** [comment]
This may appear not to work on OS X, but that's because of a different bug.

**Comment by theagentd** [comment]
I've confirmed that the issue has been fixed on Windows 7 with Nvidia drivers. A problem is that my monitors flicker excessively when I switch to fullscreen on multiple monitors, but it eventually works after a few seconds and I think it's due to Windows just being annoying.
