### ISSUE TITLE
[REQUEST] make glfwPollEvents return the number of events in queue

### ISSUE THREAD

**Issue by gensss** [glfw/glfw#591]
or just non-null if there are events

**Comment by elmindreda** [comment]
What would you use this for?

**Comment by gensss** [comment]
instead of using callbacks and sticky keys, to organize code a bit more to my liking

but i see now that i can not get key release events that way

**Comment by elmindreda** [comment]
You are using callbacks _and_ sticky keys?

**Comment by gensss** [comment]
neither, i poll then check keys via glfwGetKey
but if a key gets pressed-released-pressed in between two polls..

actually never mind, i think i misread the documentation about sticky keys
can i get GLFW_REPEAT from glfwGetKey, or just from callbacks ?

**Comment by elmindreda** [comment]
You cannot get `GLFW_REPEAT` from `glfwGetKey`.

**Comment by elmindreda** [comment]
What would you use the suggested return value for?

**Comment by gensss** [comment]
to see if i need to check for key presses

but i will have to use callbacks to get all the events so it doesn't matter (to me)
ty anyway, glfw is good
