### ISSUE TITLE
add support for std::functions for glfw callbacks?

### ISSUE THREAD

**Issue by giordi91** [glfw/glfw#599]
Hi would it be possible to provide std::function support for all the glfw callbacks? like the errors etc?

I have been using it to generate function pointers to instance methods and I would like to do the same for the generic callbacks that glfw offers

reference:
http://en.cppreference.com/w/cpp/utility/functional/function

**Comment by elmindreda** [comment]
The GLFW API is C89.

**Comment by elmindreda** [comment]
You can dispatch from regular callbacks to `std::function` objects in your own C++ code, but GLFW does not use C++.

**Comment by giordi91** [comment]
thanks for the answer I did not know about the C89, yes that s what I am doing already but having the possibility to directly call my function would remove a level of indirection. but no problem. Thanks for the fast answer
