### ISSUE TITLE
Ability to choose the color a window is cleared to during creation

### ISSUE THREAD

**Issue by theagentd** [glfw/glfw#600]
GLFW currently always clears the window to white. We would prefer black to be our default color. Our previous windowing library supported setting a default frame buffer color.

**Comment by elmindreda** [comment]
GLFW clears the window to black, i.e. the default for `glClearColor`. On what platform is it white?

Make the window initially hidden and clear the window to whatever colour you wish before showing it.

**Comment by theagentd** [comment]
The window is completely white on Windows 7/Nvidia GTX 770 until glfwSwapBuffers() is called the first time.

**Comment by elmindreda** [comment]
What version of GLFW are you using?

**Comment by theagentd** [comment]
Uhm, not sure. I'm using GLFW through LWJGL 3. Which version it uses I am unsure of. I'll try to ask @Spasi.

**Comment by elmindreda** [comment]
[glfwGetVersionString](http://www.glfw.org/docs/latest/group__init.html#ga23d47dc013fce2bf58036da66079a657)

**Comment by theagentd** [comment]
It prints:
3.1.2 Win32 WGL VisualC

**Comment by theagentd** [comment]
A workaround is to add a call to glfwSwapBuffer(window) right after creating the window.

**Comment by elmindreda** [comment]
Do you have Aero enabled?

**Comment by theagentd** [comment]
Yes, I do.

**Comment by elmindreda** [comment]
The proposed workaround (swapping buffers) is the correct solution. GLFW disables window contents clearing by Windows for performance reasons, but this leaves the OS with no clue what to do when the window is shown.
