### ISSUE TITLE
glfwSwapInterval() different behavior on win 8 and centos 7

### ISSUE THREAD

**Issue by giordi91** [glfw/glfw#603]
Hi there, I notice and odd behavior during cross compiling my project, I implemented two game loop one that runs as fast as it can one that i lock the thread until is not time to render the next frame, fixed frame rate (60fps). 
//lets compute how much we need sleep
        long long offset = next_game_tick + Constants::TICKS_PER_FRAME;
        long long sleep_time = offset - m_clock->get_ticks();
        if (sleep_time >= 0)
        {
            m_clock->sleep(sleep_time);
        }
        return;

On centos it works all good and nice with both swap interval set to 0 and 1, on windows instead of reaching 60 fps i reach 30 fps if i have the setIntervalTo 1. I don't think is a glfw bug but I was curious to know if you guys had any Idea of what is going on, Might it be that my call comes right after the lock of glfw of the swap frame so I get twice the lock and so get 30 fps rather then 60? If that the case, any clue  why this doesn't happen on Linux? 

Cheers

**Comment by tombsar** [comment]
By default Windows schedules threads in intervals of 15.6ms, so any call to sleep will usually round up to that. If this is the issue, you can try calling a Windows API function to increase the timer resolution: https://msdn.microsoft.com/en-us/library/windows/desktop/dd757624(v=vs.85).aspx

**Comment by giordi91** [comment]
Hi since I am cross compiling I am not calling anything OS specific so far, I am using the high resolution clock in nanoscecond introduced in the std library with c++ 11, in the sleep function i just do a dumb while loop until I have not waited enough.

template<typename T>
void Clock<T>::sleep(const long long amount) const
{
	const high_res_time_point t = now();
	while (get_delta(t) < amount);
	{ }
}
So I am not sure if the problem is related to the windows thread scheduling?

**Comment by tombsar** [comment]
Well that does make it less likely, but I wouldn't rule it out without testing.

Only other thing I can suggest is adding debug code to record timestamps at key parts of your program, e.g. frame_begin, input_processed, rendering_finished, etc. That should narrow down which function calls are taking longer than they should.

**Comment by giordi91** [comment]
well, I have an "empty" game loop, I am draing a single triangle and that s it, no fancy processing , not even processing inputs etc. if i remove the fps caps run on at 8000 and more FPS, also the computation of the sleep time looks correct since it works fine if I don't have the glfw frame lock.
I mean that s not a problem overall, I am just curious to see if I can find the source of the different behavior. As you might suggest might very well be an OS related thing rather the glfw

**Comment by giordi91** [comment]
might be useful if I try to create a stripped down example? just the window and the event loop nothing else?

**Comment by elmindreda** [comment]
@giordi91 It might, yes. Also, do you have Aero enabled?

**Comment by giordi91** [comment]
@elmindreda  nope I got solid window  borders. I am gonna make a test sample and upload it. 
M.

**Comment by tombsar** [comment]
Is this still an issue for you, @giordi91 ? I'm not sure there's anything we can do in glfw to help with this.

**Comment by giordi91** [comment]
Apologies for never replying to this, honestly It has been so long I don't recall if the issue was solved. Thank you for the help
