### ISSUE TITLE
Doesn't work on Visual Studio 14 2015

### ISSUE THREAD

**Issue by KaareZ** [glfw/glfw#604]
Hello

I would just like to inform that GLFW is incompatible with Microsoft Visual Studio Community 14 2015.
I've also tested with Microsoft Visual Studio 12 2013, and this time it succeeds.

Is there anything I need to do different when creating a project on 2015 than 2013, or is it just not possible at this time?

Thank you

**Comment by giordi91** [comment]
mmmm I am compiling on vs 2015 no problem, using the community edition. what s the problem exactly?

**Comment by tombsar** [comment]
Are you using precompiled libs? The current glfw source compiles fine under MSVC 2015, but lib files compiled with older versions may be incompatible.

**Comment by KaareZ** [comment]
Can't tell them all now as I'm in class, but as far as I remember, a few of them was LNK2019 and LNK2010. Something like that. I will post a full error log when I get home.

**Comment by KaareZ** [comment]
This is the errors. Keep in mind that I do exactly the same for VS 12 2013, and no problems.
https://i.gyazo.com/b7f45dffedbbf98bed8e5988b39e5eee.png
![b7f45dffedbbf98bed8e5988b39e5eee](https://cloud.githubusercontent.com/assets/12858029/9851386/b492826a-5af8-11e5-98e1-484fc6ed9749.png)

Tomsbar How do I compile my own? I've tried with cMake, and the downloaded the "source package" file from http://www.glfw.org/download.html

**Comment by elmindreda** [comment]
@KaareZ It's not incompatible; there's just no pre-compiled binary for VS 2015 in the archive you downloaded. Install CMake, configure the source directory for and compile it with VS 2015.

**Comment by IonutHurjui** [comment]
@elmindreda Hello could you please write how to configure cmake and compile glfw with vs 2015 because i have the source but i dont understand how.
I have compiled SDL2 for vs 2015  but they provided a .sln solution.Might be a stupid request but im still a beginner.
