### ISSUE TITLE
empty clipboard is considered as an error (and it is not in the doc)

### ISSUE THREAD

**Issue by bmorel** [glfw/glfw#605]
Hello.
I just tried to use clipboards and it seems that an empty clipboard is considered as an error (on linux).
I think that it should at least be written in the documentation, or glfw could return an empty string (instead of a null pointer).
Another (maybe the cleaner one?) way would be to have a function to check if there is something in the clipboard.

It does not really annoy me since I only wanted to give it a try, anyway.

**Comment by elmindreda** [comment]
Yep, the documentation needs fixing. Thank you!

Note that an empty clipboard is not the same as an empty string and many applications treat these differently. A function for checking whether a format is available is a great idea and should go into #260.
