### ISSUE TITLE
cmake does not work after a "make install"

### ISSUE THREAD

**Issue by bmorel** [glfw/glfw#606]
Hello.
On Linux, after having compiled and installed glfw3 from the git repo, using Find_package( glfw3 REQUIRED ) in a project using glfw3 does not work.

Renaming /usr/local/lib/cmake/glfw into /usr/local/lib/cmake/glfw3 allowed things to work.

**Comment by pcjohn3** [comment]
Fix seems pretty easy in CMakeLists.txt (line 441):

    install(FILES "${GLFW_BINARY_DIR}/src/glfw3Config.cmake"
                  "${GLFW_BINARY_DIR}/src/glfw3ConfigVersion.cmake"
            DESTINATION lib${LIB_SUFFIX}/cmake/glfw3)

    install(EXPORT glfwTargets DESTINATION lib${LIB_SUFFIX}/cmake/glfw3)

cmake/glfw path need to be changed to cmake/glfw3 and it worked for me on CentOS-7
John
