### ISSUE TITLE
Cmake Fails

### ISSUE THREAD

**Issue by ThePixelPony** [glfw/glfw#610]
I'm on OS X Yosemite, the following errors are produced.

>loading initial cache file MAKE_C_COMPILER=/Users/Pixel/Desktop/glfw-master/CMake/i686-pc-mingw32.cmake
CMake Error: Error processing file: MAKE_C_COMPILER=/Users/Pixel/Desktop/glfw-master/CMake/i686-pc-mingw32.cmake
-- The C compiler identification is unknown
CMake Error at CMakeLists.txt:1 (project):
  The CMAKE_C_COMPILER:
    i586-mingw32msvc-gcc
  is not a full path and was not found in the PATH.
  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.
-- Configuring incomplete, errors occurred!
See also "/Users/Pixel/Desktop/glfw-master/CMakeFiles/CMakeOutput.log".
See also "/Users/Pixel/Desktop/glfw-master/CMakeFiles/CMakeError.log".

The error file contains the following:
> Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
>Compiler: i586-mingw32msvc-gcc 
>Build flags: 
>Id flags: 
>
>The output was:
>No such file or directory
>
>
>Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
>Compiler: i586-mingw32msvc-gcc 
>Build flags: 
>Id flags: -c
>
>The output was:
>No such file or directory
>
>
>Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
>Compiler: i586-mingw32msvc-gcc 
>Build flags: 
>Id flags: -Aa
>
>The output was:
>No such file or directory
>
>
>Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
>Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
>Compiler: i586-mingw32msvc-gcc 
>Build flags: 
>Id flags: 
>
>The output was:
>No such file or directory
>
>
>Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
>Compiler: i586-mingw32msvc-gcc 
>Build flags: 
>Id flags: -c
>
>The output was:
>No such file or directory
>
>
>Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
>Compiler: i586-mingw32msvc-gcc 
>Build flags: 
>Id flags: -Aa
>
>The output was:
>No such file or directory
>
>
>Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
>Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
>Compiler: i586-mingw32msvc-gcc 
>Build flags: 
>Id flags: 
>
>The output was:
>No such file or directory
>
>
>Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
>Compiler: i586-mingw32msvc-gcc 
>Build flags: 
>Id flags: -c
>
>The output was:
>No such file or directory
>
>
>Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
>Compiler: i586-mingw32msvc-gcc 
>Build flags: 
>Id flags: -Aa
>
>The output was:
>No such file or directory
>
>
>Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
>Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
>Compiler: i586-mingw32msvc-gcc 
>Build flags: 
>Id flags: 
>
>The output was:
>No such file or directory
>
>
>Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
>Compiler: i586-mingw32msvc-gcc 
>Build flags: 
>Id flags: -c
>
>The output was:
>No such file or directory
>
>
>Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
>Compiler: i586-mingw32msvc-gcc 
>Build flags: 
>Id flags: -Aa
>
>The output was:
>No such file or directory
>
>
>Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
>Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
>Compiler: i586-mingw32msvc-gcc 
>Build flags: 
>Id flags: 
>
>The output was:
>No such file or directory
>
>
>Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
>Compiler: i586-mingw32msvc-gcc 
>Build flags: 
>Id flags: -c
>
>The output was:
>No such file or directory
>
>
>Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
>Compiler: i586-mingw32msvc-gcc 
>Build flags: 
>Id flags: -Aa
>
>The output was:
>No such file or directory
>
>
>Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
>Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
>Compiler: i586-mingw32msvc-gcc 
>Build flags: 
>Id flags: 
>
>The output was:
>No such file or directory
>
>
>Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
>Compiler: i586-mingw32msvc-gcc 
>Build flags: 
>Id flags: -c
>
>The output was:
>No such file or directory
>
>
>Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
>Compiler: i586-mingw32msvc-gcc 
>Build flags: 
>Id flags: -Aa
>
>The output was:
>No such file or directory
>
>
>Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
>Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
>Compiler: i586-mingw32msvc-gcc 
>Build flags: 
>Id flags: 
>
>The output was:
>No such file or directory
>
>
>Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
>Compiler: i586-mingw32msvc-gcc 
>Build flags: 
>Id flags: -c
>
>The output was:
>No such file or directory
>
>
>Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
>Compiler: i586-mingw32msvc-gcc 
>Build flags: 
>Id flags: -Aa
>
>The output was:
>No such file or directory
>
>
>Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
>Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
>Compiler: i586-mingw32msvc-gcc 
>Build flags: 
>Id flags: 
>
>The output was:
>No such file or directory
>
>
>Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
>Compiler: i586-mingw32msvc-gcc 
>Build flags: 
>Id flags: -c
>
>The output was:
>No such file or directory
>
>
>Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
>Compiler: i586-mingw32msvc-gcc 
>Build flags: 
>Id flags: -Aa
>
>The output was:
>No such file or directory
>
>
>Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":

Any help is appreciated.

**Comment by elmindreda** [comment]
Why are you trying to use MinGW on OS X?

**Comment by ThePixelPony** [comment]
MinGW? I don't know. I just ran "cmake ."

**Comment by elmindreda** [comment]
Is it a build tree you have moved from a Windows machine? If so you need to remove the current CMake cache.

**Comment by ThePixelPony** [comment]
Oh, I see. I've re-downloaded the zip and it works now. The includes also work in Eclipse too but when it attempts to compile the project, the following error is produced:

>/usr/local/include/GLFW/glfw3native.h:90:3: error: "No window API selected"
> #error "No window API selected"
>  ^
>/usr/local/include/GLFW/glfw3native.h:102:3: error: "No context API selected"
> #error "No context API selected"
>  ^
>2 errors generated.
>make: *** [src/Prototype-RP.o] Error 1

**Comment by elmindreda** [comment]
To quote the header file causing the errors above:
> By using the native access functions you assert that you know what you're doing and how to fix problems caused by using them.  If you don't, you shouldn't be using them.

**Comment by elmindreda** [comment]
If you are building someone else's project and it uses the native access functions then it may not yet support OS X.

**Comment by ThePixelPony** [comment]
Ah, I'll do a bit of reading up on this because I'm new to C++ (moving from Java) so I'll need to learn how to use the compiler/linker properly.

Your library appears to work perfectly though, thank you for the info!
