### ISSUE TITLE
GLFW_CURSOR_DISABLED - Mouse click registered outside the window

### ISSUE THREAD

**Issue by opengl-tutorial** [glfw/glfw#617]
When creating a windowed (not full screen) ogl context on mac osX, with the cursor mode as GLFW_CURSOR_DISABLED, the cursor stays exactly where it was right before opening the windows, so if the windows doesn't overlay the cursor position, the cursor is still visible.

When moving the event are sent to the glfw windows, but when I click the click is actually registered outside the glfw window (ie the window lost focus).

Would it be possible that when setting the cursor to GLFW_CURSOR_DISABLED mode, itmoves to the center of the windows automatically to avoid this kind of issue ?

**Comment by elmindreda** [comment]
What version of GLFW are you using?

**Comment by opengl-tutorial** [comment]
The version: 3.1.2

**Comment by elmindreda** [comment]
Note to self: Another `cursorWindow` race. Death to all caches.
