### ISSUE TITLE
Iconifying a window triggers a window size callback with width and height 0

### ISSUE THREAD

**Issue by theagentd** [glfw/glfw#624]
Happens both with GLFW_AUTO_ICONIFY enabled, and with GLFW_AUTO_ICONIFY disabled with manual calls to glfwIconifyWindow(). Reproducable with both normal windows and fullscreen windows. This is something recent as I haven't seen it before.

Example:

SIZE CALLBACK: 1920, 1080
SIZE CALLBACK: 0, 0
SIZE CALLBACK: 1920, 1080
SIZE CALLBACK: 0, 0
SIZE CALLBACK: 1920, 1080
SIZE CALLBACK: 0, 0
SIZE CALLBACK: 1920, 1080
SIZE CALLBACK: 0, 0
SIZE CALLBACK: 1920, 1080
SIZE CALLBACK: 0, 0
SIZE CALLBACK: 1920, 1080
SIZE CALLBACK: 0, 0
SIZE CALLBACK: 1920, 1080
SIZE CALLBACK: 0, 0
SIZE CALLBACK: 1920, 1080
SIZE CALLBACK: 0, 0
SIZE CALLBACK: 1920, 1080
SIZE CALLBACK: 0, 0

**Comment by elmindreda** [comment]
Are you on Windows?

**Comment by theagentd** [comment]
Yes, Windows 7 64-bit.

**Comment by elmindreda** [comment]
This is not a bug. That is the new size of the window.

**Comment by theagentd** [comment]
So it is intended behaviour?

**Comment by elmindreda** [comment]
Reproduced with GLFW 3.0 on Windows 7 64-bit.

**Comment by elmindreda** [comment]
Run the `events` test from any version.

**Comment by xanather** [comment]
@theagentd its normal, you can add a check in the resize to ignore sizes of zero if you want. When a window is minimized on Win32 the new size of the window becomes (0, 0).

**Comment by theagentd** [comment]
I see, thanks for the information. That is exactly the workaround I added. xd
