### ISSUE TITLE
Cocoa AWT: Not running on AppKit thread 0 when expected.

### ISSUE THREAD

**Issue by cafarm** [glfw/glfw#630]
I have some [GLFW3 MATLAB bindings](https://github.com/Stage-VSS/matlab-glfw3) that have been working great for a while. A recent update to OS X El Capitan and GLFW 3.1.2 have caused some odd behavior with `glfwCreateWindow` on OS X however. 

When the function is called within MATLAB to create a windowed-mode window, it creates a window but the window does not display on the screen until explicitly focused by the user. This is new behavior and does not occur on Windows or in fullscreen mode.

Below is the (truncated) error I get in console. Is anyone aware if something has changed in GLFW that would cause glfwCreateWindow to run on a different thread than thread 0? I'm not sure if this is an El Capitan, Java, or GLFW issue.  

```
10/29/15 1:26:34.179 PM MATLAB_maci64[2717]: Cocoa AWT: Not running on AppKit thread 0 when expected. (
    0   liblwawt.dylib                      0x00000001213390b9 -[AWTWindow windowDidResignKey:] + 40
    1   CoreFoundation                      0x00007fff98497c9c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
    2   CoreFoundation                      0x00007fff98497c2f ___CFXRegistrationPost_block_invoke + 63
    3   CoreFoundation                      0x00007fff98497ba7 _CFXRegistrationPost + 407
    4   CoreFoundation                      0x00007fff98497912 ___CFXNotificationPost_block_invoke + 50
    5   CoreFoundation                      0x00007fff984546d2 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1922
    6   CoreFoundation                      0x00007fff98453925 _CFXNotificationPost + 693
    7   Foundation                          0x00007fffa063c0fa -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
    8   AppKit                              0x00007fff95687bb6 -[NSWindow resignKeyWindow] + 748
    9   AppKit                              0x00007fff955af550 _NXSendWindowNotification + 252
    10  AppKit                              0x00007fff955aee2c -[NSWindow _changeKeyAndMainLimitedOK:] + 833
    11  AppKit                              0x00007fff956796c9 -[NSWindow _makeKeyRegardlessOfVisibility] + 98
    12  AppKit                              0x00007fff95679609 -[NSWindow makeKeyAndOrderFront:] + 27
    13  libglfw3.3.dylib                    0x000000012a9cc5ea glfwCreateWindow + 725
    14  glfwCreateWindow.mexmaci64          0x0000000124e70e29 mexFunction + 185
    15  libmex.dylib                        0x0000000111b01cc5 mexRunMexFile + 85
...
```

**Comment by elmindreda** [comment]
GLFW doesn't run code on any other thread than it's called from.

**Comment by cafarm** [comment]
Thanks for the info. After more investigation, this appears to be an El Capitan issue and the AWT message is not the root cause. Running the same code on Yosemite produces the same log message but correct behavior. It must have something to do with window management changes in El Capitan.

**Comment by elmindreda** [comment]
Are you sure MATLAB is calling your code on thread zero?

**Comment by cafarm** [comment]
Yeah, I'm pretty sure. It's hard to get a second thread in Matlab and the same code runs fine on Yosemite and Windows 7. Maybe someone else will notice similar behavior in El Capitan... although I haven't seen anything in my searches.

**Comment by elmindreda** [comment]
So this is not a bug in GLFW?

**Comment by cafarm** [comment]
I don't believe so but I haven't looked into it any further.
