### ISSUE TITLE
FindGLFW[3].cmake

### ISSUE THREAD

**Issue by barczynsky** [glfw/glfw#634]
Just a small request:

Isn't it worth to provide your own "FindGLFW[3].cmake" variant to close up on cross-platformization, or maybe you can recommend a good one you would willingly use? Then, maybe I'm the one who's wrong - feel free to scold me.

**Comment by andrewrk** [comment]
here's one: https://github.com/andrewrk/genesis/blob/master/cmake/FindGLFW.cmake

rather trivial, actually.

**Comment by belkiss** [comment]
GLFW comes with glfw3Config.cmake, which has the same effect as a Find module :)

**Comment by tamaskenez** [comment]
`glfw3Config.cmake` is installed to the wrong place so it is not working for now (#460 needs to be solved).
It is working on the [shaxbee fork](https://github.com/shaxbee/glfw) and on the [adasworks fork](https://github.com/shaxbee/glfw)

**Comment by elmindreda** [comment]
The GLFW config-file package should work now.
