### ISSUE TITLE
Support for menus

### ISSUE THREAD

**Issue by TuomLarsen** [glfw/glfw#638]
I understand that GLFW primary goal is to manage OpenGL context, windows and I/O in "lightweight" manner. Even FAQ says "No menus, no buttons."

However, the problem is that on MacOS applications must use the menubar and the provided `GLFW_USE_MENUBAR` is often not enough, meaning one has to use Cocoa anyway. That means platform-specific code in otherwise platform-agnostic code base.

Please, is there any chance GLFW gains support for cross-platform menus?

**Comment by elmindreda** [comment]
What would you like to add beyond what the menu bar already provides?

**Comment by TuomLarsen** [comment]
The ability to define custom menu items with keyboard shortcuts and the ability to enable/disable the items during runtime. For example "Undo" which depends on the state of the content at hand or "Zoom In" which may have a maximum allowable value.

**Comment by elmindreda** [comment]
Sounds like you would be better off using a real UI toolkit at that point, because the alternative is that GLFW has to do so on anything other than OS X and Windows.

I will be adding loading of nibs, which may be enough if all you want is custom menus on OS X.

**Comment by TuomLarsen** [comment]
Sorry, maybe I misunderstood: on MacOS an app must use the system-wide menu. If I decided to take advantage of it and use the menu for more than just exiting the app, I have to implement similar functionality for (system-wide) integration on other platforms, too. If I could load nibs, I still had to code the menus for each other platform.
In other words, if MacOS was not forcing me to use menu, I would just draw/populate the menu/buttons myself inside the window and that would work cross-platform. But since I have to use the menu on MacOS, wouldn't it make more sense to implement it just once, with the help of GLFW?
But it could be that I'm missing the "to do so on anything other than OS X and Windows" part...

**Comment by elmindreda** [comment]
OS X is the only platform where the system menu is considered mandatory. On Windows nearly every application uses its own custom widgets and on X11, Wayland and Mir they use one of a handful of popular toolkits. Look at Blender, which gets away with an even more minimal OS X system menu than GLFW provides and which uses its own consistent toolkit for everything else.

X11, Wayland and Mir don't have blessed UI toolkits, so GLFW would either have to choose one of the popular ones (adding a dependency on vast amounts of code and hoping everyone has it installed) or implement its own menu rendering, which is a significant amount of work and wouldn't look anything like other applications.

If you want to write an application that integrates with the native UI then you should use that or something like Qt that is portable and emulates it.

**Comment by gingerBill** [comment]
WARNING!!! This is not necessarily safe nor advised.

If people really want make win32 menu bars work with GLFW, what you will need to do is intercept the WNDPROC messages that are being passed to the GLFW WNDPROC. The way I have done it is to get the pointer to the procedure that GLFW uses through `GetWindowLongPtrW` and `GWLP_WNDPROC` and then storing that to be called a the end of my custom procedure. The custom procedure is then set using `SetWindowLongPtrW`.

This is a little bit of a hack but it works for my actual needs and does not require any change to the GLFW code base (such as adding windows specific callbacks).
