### ISSUE TITLE
NetBSD has non-standard libGL soname

### ISSUE THREAD

**Issue by iamleot** [glfw/glfw#646]
Installing glfw on NetBSD/amd64 -current I have noticed that libGL.so
have the version number hardcoded in glfw/glx_context.c:158 (while here
I have "libGL.so.2").

Is there any reason for that or could *soname be changed to just "libGL.so"
(instead of "libGL.so.1")? (it is just a one-line change or maybe
two-lines change if also Cygwin can be affected and so I am not
attaching a patch... if it is needed please let me know!)

I have changed it and tested with mupdf-gl and can confirm that getting
rid of the .1 fixes the problem that I reproduced with mupdf-gl.

Thank you!
Ciao,
L.

**Comment by elmindreda** [comment]
> Is there any reason for that or could *soname be changed to just "libGL.so"
(instead of "libGL.so.1")?

The reason is was chosen is that it's the runtime form of the library according to the [Linux OpenGL ABI](https://www.opengl.org/registry/ABI/) and so the safest bet. Cygwin needs the form it has, but I can make the same workaround for GLX as for EGL.

**Comment by iamleot** [comment]
Hello Camilla,

Camilla Berglund writes:
> The reason is was chosen is that it's the runtime form of the library
> according to the [Linux OpenGL ABI](https://www.opengl.org/registry/ABI/)
> and so the safest bet. Cygwin needs the form it has, but I can make the
> same workaround for GLX as for EGL.
Thank you very much for the quick response!

Regarding the [Linux OpenGL ABI](https://www.opengl.org/registry/ABI/)
it seems that they describe that too:

> libGL.so and libGLU.so should be symbolic links pointing to the
> runtime names, so that future versions of the standard can be
> implemented transparently to applications by changing the link.


Ciao,
L.
