### ISSUE TITLE
Segfault on DISP_CHANGE_RESTART from CDS_TEST

### ISSUE THREAD

**Issue by zajo** [glfw/glfw#647]
A previously working program that uses GLFW on Windows crashed inside GLFW, which I traced to the _glfwChooseVideoMode returning NULL, which I traced to the ChangeDisplaySettingsExW call in _glfwPlatformGetVideoModes failing with DISP_CHANGE_RESTART, which is documented as "The computer must be restarted for the graphics mode to work".

I'm not sure if this platform-specific error should be exposed through the GLFW API, but assuming I'm not using GLFW incorrectly, at least it shouldn't lead to a crash.

**Comment by elmindreda** [comment]
That's an unusual system setting nowadays.

**Comment by zajo** [comment]
To clarify, this happened on a 2015 MacBook Pro running Windows 8.1 on two external displays with the laptop display off.
