### ISSUE TITLE
Does GLFW support creating OpenGL contexts for headless rendering (to an offscreen buffer)?

### ISSUE THREAD

**Issue by shurcooL** [glfw/glfw#648]
GLFW is described as:

> GLFW is an Open Source, multi-platform library for creating windows with OpenGL contexts and receiving input and events.

I've looked through the documentation, the FAQ, and issues, but could not find an answer to this.

Does GLFW support creating an OpenGL context in a "headless" mode? For rendering to an offscreen buffer and perhaps writing generated images to disk or using it in some other way.

This is not a feature request, it's a question. Asking on behalf of https://github.com/goxjs/gl/issues/12#issuecomment-158864753.

**Comment by slimsag** [comment]
https://github.com/glfw/glfw/issues/525 has some relevant info for using a hidden window.

AFAIK doing headless rendering without a hidden window is not really possible due to how tightly coupled GL is with most windowing systems.

**Comment by shurcooL** [comment]
Thanks. It turns out it was there in the docs but I missed it, sorry.

http://www.glfw.org/docs/latest/context.html#context_offscreen

**Comment by elmindreda** [comment]
@shurcooL Where did you look? Perhaps I should add a link.

**Comment by shurcooL** [comment]
I looked [here](http://www.glfw.org/docs/latest/) and [here](http://www.glfw.org/faq.html), but I forgot to check [here](http://www.glfw.org/docs/latest/context.html).

I think it's fine. Perhaps it's worth adding as a FAQ if you think it is.

**Comment by elmindreda** [comment]
Yes, the FAQ is a great place. Thank you!

**Comment by RobotCaleb** [comment]
With EGL and osmesa support is the following still true?
`GLFW doesn't support creating contexts without an associated window. However, contexts with hidden windows can be created with the GLFW_VISIBLE window hint.`

I need GPU accelerated headless contexts. Please move to a new issue if this isn't a good spot for this question.

**Comment by elmindreda** [comment]
@RobotCaleb How headless do you need it and on what platforms? Do you mean without requiring the window system to be running, or just without creating a hidden window?

**Comment by RobotCaleb** [comment]
It needs to be on a system without X running. It seems EGL supports this but my first test was by providing the EGL hint to the window creation, but that just created a window. Which makes sense.

**Comment by elmindreda** [comment]
@RobotCaleb There is no support in GLFW for accelerated headless rendering at the moment. There is a OSMesa / no-op backend and I will soon merge an EGLDevice / Linux backend (you can find it in the `egldevice` branch).

**Comment by RobotCaleb** [comment]
@elmindreda Thanks for the info. I'll look through the code in `egldevice`. Will this be enough to have accelerated headless rendering or will I need to look into adding that functionality?

**Comment by elmindreda** [comment]
@RobotCaleb It's enough, but only on drivers that support it. I think it's still Nvidia only.

**Comment by RobotCaleb** [comment]
Outstanding, thanks for the info. I'm eager to check it out. If I have any further questions I'll put them in a new issue.

**Comment by devshgraphicsprogramming** [comment]
@RobotCaleb the problem is that you must have a legacy gl window to query support for core 3.2 context creation functions... so X11 is necessary in this chain.

Has anyone tried pbuffers? It wont absolve you of X11 but at least you will get a window-less context after the start-up (unless this is what GLFW hidden window actually is).

OpenGL 3.2 core spec actually allows for context with no drawable, you'll just get an invalid default framebuffer object.

**Comment by MadcowD** [comment]
Can anyone tell me how this is done now?

**Comment by slimsag** [comment]
@MadcowD See https://www.glfw.org/docs/latest/context.html#context_offscreen for using a hidden window.

**Comment by harlowja** [comment]
Did the egldevice branch merge? Seems like it has a bunch of code that never made it in :(

**Comment by elmindreda** [comment]
@harlowja Not yet, please follow #786 for updates.
