### ISSUE TITLE
Cursor y-position offset by 30 pixels in fullscreen on 10

### ISSUE THREAD

**Issue by mumin16** [glfw/glfw#652]
In fullscreen mode the cursor is not at the same place as windowed mode. To be able to click on something i have to aim to the right and down from whatever i want to click. In windowed mode the cursor is at the right place but fullscreen is problem.

**Comment by elmindreda** [comment]
What version of GLFW are you using?
What OS are you using?
What is the offset?

**Comment by mumin16** [comment]
GLFW Version 3.1.2 x64 released.
windows 10(1511) x64.

offset?

my monitor resolution is 1360x768 but my app's window size is 1024x768.
this is problem?

**Comment by elmindreda** [comment]
What is the difference between the reported and actual cursor positions?

**Comment by mumin16** [comment]
I looked again: xpos is not problem. glfwGetCursorPos reports 240 for ypos over a nanovg's gui. But it must be 210.

**Comment by elmindreda** [comment]
Odd. There's [not a lot of code](https://github.com/glfw/glfw/blob/3.1.2/src/win32_window.c#L1069) involved here.

**Comment by haikarainen** [comment]
The height of the window titlebars in Windows 10 is exactly 30 pixels (matches your offset perfectly), how do you create your window @mumin16? Is it maximized or is it completely fullscreen? What happens if you create an undecorated window exactly the size of your monitor resolution, and position it exactly at 0, 0?

**Comment by trashuj** [comment]
hi all,
I'm having an issue that might be related.
it happens only on windows 10, windowed mode.
full screen or removing the decoration fixes it. Also it works fine on linux.
i'm using the latest version (I just cloned github)

I attached several screenshots.
basically i'm displaying 5 times the same test texture, so the y position should be 0, 0.2, 0.4, 0.6, 0.8
what i expect is shown in 02_nodeco.png. the red cross shows where the pointer was when i took the screenshot.
other screenshots show the bug.
in 02.png, it should be 0.2. instead it's 0.16, and we can see that the top of the texture ("top") is missing.
in 04.png, it should be 0.4 instead it's 0.38
in 08.png, it should be 0.8 instead it's 0.79 (somehow catching up)

do you have any idea on what could cause this?
any help/hint would be welcome.

thanks a lot in advance!

![04](https://user-images.githubusercontent.com/9165398/33331569-e605605e-d49c-11e7-95ba-c1b61146ae43.png)
![00](https://user-images.githubusercontent.com/9165398/33331212-faed4c76-d49b-11e7-9172-58263e0eaf5f.png)
![02](https://user-images.githubusercontent.com/9165398/33331213-fb23fe74-d49b-11e7-9c9b-38b3bacf6ebd.png)
![02_nodeco](https://user-images.githubusercontent.com/9165398/33331214-fb5785aa-d49b-11e7-9de6-63bf4117ccf7.png)
![08](https://user-images.githubusercontent.com/9165398/33331216-fb8f541c-d49b-11e7-8a2a-331406278c94.png)

**Comment by trashuj** [comment]
created a new bug, because the problem is more about ratio than offset.
#1148

**Comment by tombsar** [comment]
Is this still an issue for you using the 3.3 release, @mumin16 ?
