### ISSUE TITLE
Inverted joystick enumeration

### ISSUE THREAD

**Issue by SeeK-ntr0py** [glfw/glfw#654]
Linux Mint 17.2 (kernel 4.1.6).

Having a problem where all the joystick devices provided by udev are enumerated from last-to-first by GLFW.  So if I have 4 joystick devices, GFWL will expose the *highest* enumerated /dev/input/js* (or /dev/input/event*) device provided by udev as joy[0]/GLFW_JOYSTICK_1.

Consistently able to produce this output:
/dev/input/js0  ->  /dev/input/event19  ->  GLFW_JOYSTICK_4 (joy[3])
/dev/input/js1  ->  /dev/input/event20  ->  GLFW_JOYSTICK_3 (joy[2])
/dev/input/js2  ->  /dev/input/event21  ->  GLFW_JOYSTICK_2 (joy[1])
/dev/input/js3  ->  /dev/input/event22  ->  GLFW_JOYSTICK_1 (joy[0])

Reproduced on three machines running Mint 17.2, using both Hidromancer and the kernel xboxdrv.  Built GLFW from source using master; BUILD_SHARED_LIBS ON, RelWithDebInfo.

I haven't experience this behaviour with any other application.  evtest, jstest-gtk and every other game and API (SD2/SFML/libudev) seems to address them in the correct order.  I verified GLFW_JOYSTICK_n macros are all correct.

**Comment by elmindreda** [comment]
So GLFW doesn't guarantee any ordering of joysticks, and it looks like SDL mostly returns them in the order you desire by accident. SDL guesses a bunch of file names in ascending order while GLFW uses `readdir` and `regexec` (and it's a todo in SDL to do it the GLFW way).

Are you suggesting that the indices should always match, even if it leaves holes in the index space on init?

**Comment by SeeK-ntr0py** [comment]
Well, I think making a case for ordering is easy enough.  Joystick[0]/GLFW_JOYSTICK_1 should always represent the first joystick enumerated by the system.  With hidromancer, xpad (kernel) and xboxdrv, the driver reserves a block of devices and assigns the each physical device that connects to it the next available js*/event* device within the block in ascending order.

So, for example, if you connect a usb xbox receiver, 4 devices become exposed to a GLFW application.  As far as GLFW can see all the devices are valid, but the user probably only has one controller connected.  If the enumeration is inverted and the application assigns GLFW_JOYSTICK_1 for, say, menu navigation.  The user would then have to connect 3 additional controllers to the receiver, using the 4th, in order to 'be' player one.

Making a case for literal mapping is a little trickier, but I think it's best that input API's expose the functions of the driver/hw as directly as possible with regard to crossplatform uniformity.  This is one of the reasons that I prefer GLFW to SDL and SFML.  SDL makes some ridiculous assumptions and implements them with dirty hacks (axis remapping and obscuration) which break a the uniform model.  SFML obtusely limits all hardware on all platforms to the worst joystick api on them all (mmsystem.)

If I create a udev joystick device under linux with axes 0-20 enabled, GLFW exposes all the axes without trying to second-guess the intent of the driver.  Through GLFW all axes are available and enumerated just as the driver provided them.  To me this is the only sane behaviour, since only the driver knows how the hardware works.  It's not much of a jump to apply the same principals to device enumeration as to axis/button enumeration.

Another good case for literal mapping of OS enumerated devices might be hotplugging.  The onus is already on the OS to handle the enumeration of devices as they are connected and lost in no predictable order.  We already have to consider this a reliable subsystem, and in the case of linux, the I've found the behaviour of udev to be simple and reliable.

I think the case of having index 'holes' on init will be somewhat uncommon.  This is only expected to happen when, say, player1 disconnects, but player2 remains.  This might be because batteries are being swapped out, in which case, reconnecting the device will restore it to the first available index anyway.  Hidromancer has a mechanism to selectively change to any available udev vport with a block, but otherwise, the behaviour would be consistent with OS enum and most (if not all) consoles.

**Comment by elmindreda** [comment]
Ah, you want it because the USB Xbox receiver driver lies. Thank you.

**Comment by SeeK-ntr0py** [comment]
Not really, no.  

Please do me the dignity of reading the entirety and conversing with me about this.  Giving me a condescending brush-off is inappropriate.

Anyway, the conclusion you've reached about this bug/proposal is incorrect.

If I need to qualify my position further, what M$ has done the landscape of input devices is cancerous.  By no means am I looking for a hacky xbox-specific rectification so I can directly support a terrible way of handling input.  I'm interested in simple, crossplatform unified support of every reasonably-possible joystick that someone might connect to a computer.

Hidromancer, which I mentioned, is a bluetooth DS3 driver which I have written from the ground up.  I've looked at the source for xpad and xboxdrv.  I've also written [linux] input drivers for the wiimote, wiiu-pro, DS4 (partially), and a few random old usb/db15 joysticks that I just cant stop loving, heh.

While the xpad and xboxdrv do perform some ugly shenanigans with axis/button mapping, the way the devices are enumerated by udev is rational.  This bug, however, seems to be affecting every joystick in my system, as long as there are multiple joysticks, GLFW seems to be inverting the OS recognized order of them.

I can probably even find time to fix this, provided we can agree on a consistent and rational behavioural definition for device enumeration.

Cheers

**Comment by elmindreda** [comment]
I didn't brush you off; I summarised the cause of this bug report, which is that the driver exposes device nodes for non-existent joysticks.

It's easy to fix. I'll just sort the joysticks after initial enumeration. The ordering of inotify events should ensure that hotplugged receivers will get their fake device nodes in the desired order as well.

You might want to know that I will be adding axis/button remapping in this release so that Xbox controllers and compatible devices will have the same number of buttons and axes in the same order across supported platforms.

**Comment by SeeK-ntr0py** [comment]
Great, sorting the identified devices should resolve the ordering for the most part.  Thanks!

I would like to point out again, however, this is not endemically an xbox receiver issue.  It has nothing to do with drivers or hardware lying, per se.  I have 3 Logitech  F710 Gamepads, each connects to their own USB port.  If I connect them one at a time, the third one I connect (which is /dev/input/js2) still ends up being recognized by GLFW as GLFW_JOYSTICK_1.  In this case there are no device nodes being block-reserved -- just one gamepad, one USB port, one driver instance, one device node each.

There always exists the possibility of holes in the enum, depending on when a device is lost.  Since, again, the OS bears the onus of enumerating, it still seems to me to best to trust the OS to handle it, rather than reimplement the wheel.

I actually really like using GLFW for input becuase it properly exposes the driver as a flat list of buttons and axes without performing any dirty hacks.  Now... am I misunderstanding this, or is the next version you mentioned going to essentially overwrite the driver defined axis/button enum and break the flat model?

**Comment by elmindreda** [comment]
I understand that it's not specific to your receiver device and that the bug applied to any set of more than one joystick.

I know that holes are unavoidable once you start plugging things out, but due to a sentence in the GLFW API spec I need the initial set to be packed.

The remapping will _only_ apply to a specific list of devices that I know will be expected to behave like an Xbox controller. Anything not in that list will not be affected and will work exactly as before. Initially, if anything, the list will be too short and we will have to crowd-source the necessary IDs.

**Comment by elmindreda** [comment]
The reason for this remapping is so that games written for Xbox-like controllers on one platform will behave as expected when compiled on another. Actual joysticks and wheels have such variance that any game making use of them need to be able to handle that anyway.
