### ISSUE TITLE
osx 10.11.1 xcode 7.1.1 glfw3 cannot link correctly

### ISSUE THREAD

**Issue by joye** [glfw/glfw#655]
I have already added OpenGL, Cocoa, CoreVideo, IOKit framework and libglfw3.a, but still 5 link error happen.

Undefined symbols for architecture x86_64:
  "_LMGetKbdType", referenced from:
      __glfwPlatformGetKeyName in libglfw3.a(cocoa_window.m.o)
  "_TISCopyCurrentKeyboardLayoutInputSource", referenced from:
      __glfwPlatformInit in libglfw3.a(cocoa_init.m.o)
  "_TISGetInputSourceProperty", referenced from:
      __glfwPlatformInit in libglfw3.a(cocoa_init.m.o)
  "_kTISPropertyUnicodeKeyLayoutData", referenced from:
      __glfwPlatformInit in libglfw3.a(cocoa_init.m.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by elmindreda** [comment]
Those are in Carbon.

**Comment by elmindreda** [comment]
So you need to add Carbon to the list.

**Comment by joye** [comment]
Thanks, after adding Carbon no link error happen.

**Comment by xmkevinchen** [comment]
@joye, Actually if you build glfw as dynamic library you could like with flags like this
```
OTHER_LDFLAGS = -lglew -lglfw -framework Cocoa -framework OpenGL -framework IOKit -framework CoreVideo -framework CoreFoundation
```
