### ISSUE TITLE
MinGW import library has no prefix

### ISSUE THREAD

**Issue by dougbinks** [glfw/glfw#657]
The library for dll builds in the MinGW folders of the download packages is missing the lib prefix.

Renaming glfw3dll.a to libglfw3dll.a solves link errors.

Note: I'm no MinGW expert, but other folk have also spotted this issue, see this answer by Che-Hsun Liu here: http://stackoverflow.com/questions/12886609/setting-up-glfw-with-mingw

**Comment by elmindreda** [comment]
Thank you!
