### ISSUE TITLE
Implicit function declaration warning in win32_init.c

### ISSUE THREAD

**Issue by skorezore** [glfw/glfw#659]
The following errors are emitted upon an attempt at compilation:

    deps/glfw/src/win32_init.c: In function '_glfwPlatformInit':
    deps/glfw/src/win32_init.c:383:5: warning: implicit declaration of function '_glfwInitJoysticksWin32'     [-Wimplicit-function-declaration]
         _glfwInitJoysticksWin32();
         ^
    deps/glfw/src/win32_init.c: In function '_glfwPlatformTerminate':
    deps/glfw/src/win32_init.c:405:5: warning: implicit declaration of function     '_glfwTerminateJoysticksWin32' [-Wimplicit-function-declaration]
         _glfwTerminateJoysticksWin32();
         ^

**Comment by elmindreda** [comment]
Cool. This means there is a compiler detection bug in the CMake files.
