### ISSUE TITLE
Detect window position while window is being dragged.

### ISSUE THREAD

**Issue by ckaran** [glfw/glfw#665]
I'm using `glfwGetWindowPos()` to get the window's current position to determine what should be drawn. The idea is to simulate what you might see if you were looking at an object through a pair of X-ray glasses; the image in the glasses correlates to what is in the background, but is completely different from it. To see what I'm talking about, clone https://github.com/ckaran/glfw and build the example at https://github.com/ckaran/glfw/blob/transparent_windows/examples/filters.c.  Note that this might only work on OS X; I know it won't work under Linux because the window transparency isn't working there.  When you have the code running, drag the blue window over the other windows.  When you pass over the red window, you should see a triangle rendered in the blue window, but whose position is centered relative to the red window.

The problem is that the window's position is updated too slowly; the triangle jumps all over the place as I move the window, snapping into place only when the window has stopped moving for little less than a second.  This is **horribly** distracting; is there any way to get the current position of the window when I call `glfwGetWindowPos()`, rather than what it was at some point in the past?

**Comment by elmindreda** [comment]
Try disabling vsync.

**Comment by ckaran** [comment]
Tried both `glfwSwapInterval(0)` and `glfwSwapInterval(-1)`.  Didn't help.  Is there another way to disable vsync?

**Comment by ckaran** [comment]
This is now fairly well fixed by https://github.com/glfw/glfw/pull/667.
