### ISSUE TITLE
glfwsleep question

### ISSUE THREAD

**Issue by hodiizidor** [glfw/glfw#669]
I recently moved from glfw 2.7.2 to latest version, and found out that glfwSleep is missing. I didn't saw any mention of it in header, or which function replaces it.

Is it completely removed, or is there substitute for it?

**Comment by tombsar** [comment]
glfw 3 removed threading-related functions entirely, so you will need to use an external library. More details in the documentation: http://www.glfw.org/docs/latest/moving.html#moving_threads

**Comment by hodiizidor** [comment]
Thank you
