### ISSUE TITLE
Fullscreen on Windows on HDPI screen not working if upscaling is enabled

### ISSUE THREAD

**Issue by badlogic** [glfw/glfw#676]
By default, Windows 10 enables upscaling for executables that don't set the respective properties in the executables manifest. 

On a HDPI monitor (e.g. 4k) and with the Windows wide HDPI scaling set to > 100%, GLFW fails to properly create a fullscreen window at below native-resolution if upscaling is enabled. Instead of the entire screen being covered, only parts of it are allocated to the fullscreen window.

In the same scenario (4k monitor, below native resolution fullscreen window), but with the global HDPI scale set to 100%, GLFW manages to create the fullscreen window properly such that it covers the entire screen. However, the window never gains focus, neither automatically not by switching focus from and back to the window.

If the fullscreen window uses native resolution, GLFW succeeds in creating it and having the input focus work correctly for both 100% scale and scale != 100%.

If upscaling is explicitely disabled, either via a manifest entry or by manually setting it in the properties of the executable in Windows Explorer, all scenarios (scale != 100%, resolution != native, resultion == native) work as intended.

**Comment by slime73** [comment]
> On a HDPI monitor (e.g. 4k) and with the Windows wide HDPI scaling set to > 100%, GLFW fails to properly create a fullscreen window at below native-resolution if upscaling is enabled. Instead of the entire screen being covered, only parts of it are allocated to the fullscreen window.

That's a problem with Windows itself I think.

https://msdn.microsoft.com/en-us/library/windows/desktop/dn469266(v=vs.85).aspx#partial_rendering_of_a_full_screen_application

> Partial Rendering of a Full-screen Application

> DPI virtualization sometimes causes partial rendering of a full screen application. In most cases, this side effect of DPI virtualization occurs in full-screen gaming applications because they commonly do programmatic screen resolution mode changes. This issue affects only Windows Vista or later applications that do not declare themselves as DPI–aware. Because virtualized applications get scaled system metrics, an application that changes the display mode based on these metrics may change the display to an incorrect mode while virtualized. Since full screen applications like games are natively resolution-independent, in most cases this means they are also natively DPI independent. The recommended solution for this class of applications is to declare themselves as per monitor-DPI aware. Note that some applications may have windowed-mode installers and uninstallers, so it is important to do an application test pass according to the DPI testing guidelines to ensure that the application behaves properly at high DPI.

**Comment by elmindreda** [comment]
I unfortunately can't work on this one because I don't have a spare machine I can infest with Windows 10.

**Comment by badlogic** [comment]
I'd happily pay for a cheap(ish) machine if this helps. Not sure what your
policies are regarding such sponsorship.

**Comment by elmindreda** [comment]
@badlogic Um, wow, thank you! That would be extremely helpful. I don't expect this to be the last bug specific to 10. If you think it'd be worth it to you then I accept.

There's no policy for GLFW. My own, such as it is, is to accept donations when it'll help me work on the project.

**Comment by badlogic** [comment]
Please contact me at mario at badlogicgames dot com and we can figure out
the details!

**Comment by elmindreda** [comment]
Windows 10 machine: achieved

**Comment by miroandel** [comment]
In visual studio 2015 this setting does the trick and solves the fullscreen issue.
![skarmklipp 2016-03-08 08 24 54](https://cloud.githubusercontent.com/assets/2983422/13595212/baae0976-e509-11e5-9b33-e2c3953c5b5b.png)

However it would be nice setting this using cmake. Need to investigate this a bit. However, it would be good to add a feature to GLFW to be able to retrieve the per monitor scaling variable to be able to render fonts and other objects correctly. When not running fullscreen the scaling also affects the positioning of windows.

**Comment by fralken** [comment]
Hello, now that version 3.2 is out I can see that the per-monitor-DPI-awareness is managed, that is, even if the manifest property is not set, it is set by GLFW itself at runtime and hence the WM_DPICHANGED event is triggered when moving a window across two monitors with different DPI. That's ok.

Anyway, it still doesn't manage a monitor with DPI != 100%.
For example, my primary monitor has DPI=240 (that is 250% since the default is 96), while btw my secondary monitor has DPI=96.

A window created on the primary monitor is still created in actual pixels and not in screen coordinates, as stated in the documentation.
Any plan on trying addressing this issue? :)
Thanks

**Comment by elmindreda** [comment]
With the addition of the content scale queries and callback and `GLFW_SCALE_TO_MONITOR` I believe high-DPI support in GLFW is usable.
