### ISSUE TITLE
glfwSwapBuffers does not block with swap interval > 0 when window is minimized or covered by another window

### ISSUE THREAD

**Issue by badlogic** [glfw/glfw#680]
The docs of [`glfwSwapBuffers`](http://www.glfw.org/docs/latest/group__window.html#ga15a5a1ee5b3c2ca6b15ca209a12efd14) say that this call will vsync (to it's best ability in windowed mode i guess) if the swap interval is > 0.

This works if the window is partially visible (either full-screen or windowed mode). It actually doesn't "vsync" if the window is fully covered by another window or if the window is minimized. Is this by design? Only tested on Mac OS X.

I'm not sure if this could/should be "fixed" in GLFW or if it's the responsibility of the application to take care of it. However, it should at least be documented in the glfwSwapBuffers docs that no vsync'ing happens in case the window is fully covered or minimized.

**Comment by elmindreda** [comment]
That is by design, but it's Apple's design. OS X ignores the NSOpenGL swap interval when the window is obscured. No other OS does this.

I will look into working around this with display link at some point. If that doesn't work, I don't think there's anything GLFW can do.

**Comment by elmindreda** [comment]
I will add a note to the documentation for the next release.

**Comment by meshula** [comment]
This is an energy saving feature called App Nap. You need to disable it in applications that expect to do background processing such as render serving, or that should continue running when obscured. It can be accomplished from code, and would probably be a good option for glfw to expose. Look for App Nap on this page:

https://developer.apple.com/library/mac/releasenotes/MacOSX/WhatsNewInOSX/Articles/MacOSX10_9.html

**Comment by elmindreda** [comment]
That looks like yet another good candidate for the platform specific hints I'm sketching out.

**Comment by shurcooL** [comment]
If App Nap is working as I understand, is this a problem? Hopefully, what's happening is that `glfwSwapBuffers` isn't blocking, but the app is still being suspended enough that the power savings are even greater than with just vsync.

Or did you want to disable that power saving functionality instead?

**Comment by meshula** [comment]
If you implement a render server, for example, an application that creates images to be displayed on some other device, or just for screenshots, that application might run in the background. App Nap might suspend it. A primary reason to disable app nap is to enable server applications.

**Comment by badlogic** [comment]
My use case is to put the app mostly to sleep when obscured/minified. Doable from the application code itself. Thanks for the clarification @elmindreda!

**Comment by ithron** [comment]
I think an application should suspend its rendering when the window is occluded. There is no point continue rendering when there is nothing to see.
But as far as I know there is no way to check the occlusion state with GLFW. Maybe one could change glfwGetWindowAttrib(window, GLFW_VISIBLE) to return 0 if the window is occluded?

When a window changes its occlusion state windowDidChangeOcclusionState:(NSNotification *) is called on the window delegate. I don't know if there is an easy way to check occasion state on there systems.

**Comment by claudiofantacci** [comment]
> I think an application should suspend its rendering when the window is occluded. There is no point continue rendering when there is nothing to see.

This is not always true.
Have a look at my use case [here](https://github.com/glfw/glfw/issues/975).

I will looking into this issue as well.
Maybe, I can be of help 😄

**Comment by elmindreda** [comment]
As a side-effect of fixing #1337, OpenGL vsync now uses a display link and is not affected by window occlusion.
