### ISSUE TITLE
Fullscreen not working for most resolutions

### ISSUE THREAD

**Issue by badlogic** [glfw/glfw#682]
GLFW reports various valid video modes on a Mac Book Pro Retina 15" early 2013:

```
640x480
800x600
1024x768
1280x800
1440x900
1680x1050
2048x1280
2560x1600
2880x1800
```

The first issue is that not all possible resolutions are reported. Here's what the display really supports according to SwitchResX, which also allows setting those modes:

![http://libgdx.badlogicgames.com/uploads/Screen%20Shot%202016-01-03%20at%2023.04.36-IOKaSoTsRz.png](http://libgdx.badlogicgames.com/uploads/Screen%20Shot%202016-01-03%20at%2023.04.36-IOKaSoTsRz.png)

As a test, i simply modified [simple.c](https://github.com/glfw/glfw/blob/master/examples/simple.c#L89), passing in any of the video mode resolutions that GLFW reports. Here's the results for various resolutions set in line 89, using the primary monitor:

800x600
![http://libgdx.badlogicgames.com/uploads/Screen%20Shot%202016-01-03%20at%2023.08.17-cGh6gJ3lSa.png](http://libgdx.badlogicgames.com/uploads/Screen%20Shot%202016-01-03%20at%2023.08.17-cGh6gJ3lSa.png)

1280x800
![http://libgdx.badlogicgames.com/uploads/Screen%20Shot%202016-01-03%20at%2023.09.25-wPQnDQ5anU.png](http://libgdx.badlogicgames.com/uploads/Screen%20Shot%202016-01-03%20at%2023.09.25-wPQnDQ5anU.png)

1440x900
![http://libgdx.badlogicgames.com/uploads/Screen%20Shot%202016-01-03%20at%2023.10.23-5ClAKXH3FU.png](http://libgdx.badlogicgames.com/uploads/Screen%20Shot%202016-01-03%20at%2023.10.23-5ClAKXH3FU.png)

1680x1050
![http://libgdx.badlogicgames.com/uploads/Screen%20Shot%202016-01-03%20at%2023.12.09-eKMd9CKkAH.png](http://libgdx.badlogicgames.com/uploads/Screen%20Shot%202016-01-03%20at%2023.12.09-eKMd9CKkAH.png)

2880x1800
![http://libgdx.badlogicgames.com/uploads/Screen%20Shot%202016-01-03%20at%2023.13.04-ZKSGzdRuxg.png](http://libgdx.badlogicgames.com/uploads/Screen%20Shot%202016-01-03%20at%2023.13.04-ZKSGzdRuxg.png)

Only 1440x900 and 2880x1800 work. This seemed a bit to convenient (the latter being a multiple of the former), so i checked my system settings. Low and behold:

![http://libgdx.badlogicgames.com/uploads/Screen%20Shot%202016-01-03%20at%2023.13.50-aX6cYaLdof.png](http://libgdx.badlogicgames.com/uploads/Screen%20Shot%202016-01-03%20at%2023.13.50-aX6cYaLdof.png)

It looks only resolutions that are a multiple of the currently set screen resolution work. To test this theory, i set the current scaled resolution to this:

![http://libgdx.badlogicgames.com/uploads/Screen%20Shot%202016-01-03%20at%2023.14.31-0SrT1qWnRp.png](http://libgdx.badlogicgames.com/uploads/Screen%20Shot%202016-01-03%20at%2023.14.31-0SrT1qWnRp.png)

And as expected, only 1680x1050 worked, the others showed either a black screen or an incomplete triangle.

This must obviously have something to do with HDPI scaling. I used `GLFW_USE_RETINA` for this build.

Disabling `GLFW_USE_RETINA` does not help:

![http://libgdx.badlogicgames.com/uploads/Screen%20Shot%202016-01-03%20at%2023.20.31-Ow7SNCd1zE.png](http://libgdx.badlogicgames.com/uploads/Screen%20Shot%202016-01-03%20at%2023.20.31-Ow7SNCd1zE.png)

I'd be happy to help any way i can to resolve this issue.

**Comment by slime73** [comment]
> The first issue is that not all possible resolutions are reported. Here's what the display really supports according to SwitchResX, which also allows setting those modes: [...]

FWIW those additional modes are not officially supported by OS X. I believe SwitchResX might be using private Apple APIs which will get Mac App Store apps rejected. ResXtreme does the same thing: http://resxtreme.com

**Comment by elmindreda** [comment]
The full screen window positioning part of this appears to be a bug. I will look into it.

As for what video modes are exposed, have a look at `modeIsGood`.

Also FWIW, I don't think there are any valid reasons for games to change the resolution nowadays. It's slow, bug-prone, messes up window and monitor viewport positions, makes application switching flaky and on OS X forces you to choose between disabling Cmd+Tab and messing up the desktop icons, all of which annoys users. If you want to render at a lower resolution, render to a texture.

**Comment by shurcooL** [comment]
> Also FWIW, I don't think there are any valid reasons for games to change the resolution nowadays.

The only valid remaining reason should be if you're doing it in order to switch to another (higher) refresh rate. If that's not the goal (but rather the resolution change), then completely agreed.

**Comment by badlogic** [comment]
Totally agree that switching the resolution is mostly bad and should be avoided. We strongly recommend that to our users. But since we also expose other modes reported by GLFW, we'd rather have it working for obvious reasons :)

**Comment by elmindreda** [comment]
Have been looking into this one and am officially stumped.

**Comment by shurcooL** [comment]
Have you tried a really old version of GLFW to see how it compares?

There's a chance this is a regression in OS X 10.11.3 since full screen resolutions that are not native resolution are used so seldomly these days.

**Comment by elmindreda** [comment]
A bisect says 6743761c2c3893f95125dfd12b28620b9cf3dfa5, unfortunately. Considering how old it is and how late 3.2 is, I won't consider this blocking but I'll keep working on this once 3.2 is out.

**Comment by mokafolio** [comment]
Does anybody know if this is fixed? Almost no fullscreen works for me on OSX 10.11 .

**Comment by elmindreda** [comment]
@mokafolio It has not been fixed yet. Please use the desktop resolution, if possible.

**Comment by elmindreda** [comment]
I started on this again today and found it had been fixed already. A bisect points to 77a8f103d8f8519d1a723bbd8b0490b448f1f430. Turns out the fix was adding the (required but previously missing) context update on screen parameter change.
