### ISSUE TITLE
Wayland compile error

### ISSUE THREAD

**Issue by BananaKiller** [glfw/glfw#684]
When I Compiled glfw with EGL & Wayland, the following issue was happened.
I find that "XK_KP_Space" is define in <X11/keysymdef.h>,and the definition in xkbcommon is "XKB_KEY_KP_Space ". 
Is there something error In this process ？

/media/work/user02/work/glfw-touch/src/xkb_unicode.c:830:5: error: ‘XK_KP_Space’ undeclared here (not in a function)
/media/work/user02/work/glfw-touch/src/xkb_unicode.c:831:5: error: ‘XK_KP_Equal’ undeclared here (not in a function)
/media/work/user02/work/glfw-touch/src/xkb_unicode.c:832:5: error: ‘XK_KP_Multiply’ undeclared here (not in a function)
/media/work/user02/work/glfw-touch/src/xkb_unicode.c:833:5: error: ‘XK_KP_Add’ undeclared here (not in a function)
/media/work/user02/work/glfw-touch/src/xkb_unicode.c:834:5: error: ‘XK_KP_Separator’ undeclared here (not in a function)
/media/work/user02/work/glfw-touch/src/xkb_unicode.c:835:5: error: ‘XK_KP_Subtract’ undeclared here (not in a function)
/media/work/user02/work/glfw-touch/src/xkb_unicode.c:836:5: error: ‘XK_KP_Decimal’ undeclared here (not in a function)
/media/work/user02/work/glfw-touch/src/xkb_unicode.c:837:5: error: ‘XK_KP_Divide’ undeclared here (not in a function)
/media/work/user02/work/glfw-touch/src/xkb_unicode.c:838:5: error: ‘XK_KP_0’ undeclared here (not in a function)
/media/work/user02/work/glfw-touch/src/xkb_unicode.c:839:5: error: ‘XK_KP_1’ undeclared here (not in a function)
/media/work/user02/work/glfw-touch/src/xkb_unicode.c:840:5: error: ‘XK_KP_2’ undeclared here (not in a function)

**Comment by elmindreda** [comment]
What version of GLFW are you using?

**Comment by BananaKiller** [comment]
The latest version：GLFW 3.1.2

**Comment by BananaKiller** [comment]
By the way,glfw-touch branch also have the same error

**Comment by elmindreda** [comment]
But does master?

**Comment by BananaKiller** [comment]
I mean the master branch version GLFW 3.1.2 and touch branch got the same error when I compiled.

**Comment by elmindreda** [comment]
This was fixed with 67c6a45e0e7fe09959fdbbdb0da7dfc6712d46e1 but I forgot to tag the commit.
