### ISSUE TITLE
Monitor Callback and Window User Pointer

### ISSUE THREAD

**Issue by Blacklands** [glfw/glfw#686]
I'm currently facing a problem with the monitor callback function:

It seems that, in contrast to all the other callback functions, it is not possible to get the window user pointer from this one. For all other callback functions (except the error callback function, although I believe that has the same problem), I have defined those as static member functions of a class and I'm getting the instance of the class like this:

```c++
	void *data = glfwGetWindowUserPointer(window);
	MyClass* wrapperClass = static_cast<MyClass*>(data);
```

This works great for all the other callback functions, however the monitor callback has no "window" argument, only the monitor and the action/event.

Is this by design, and I am just missing something here? If it is not, I would like to know what else I could to to work around this issue. I would need a pointer to the class because I'd need to call some methods on it for reacting to a (possible) monitor switch.
Thanks in advance!

**Comment by elmindreda** [comment]
It's by design, yes. There is no window involved when a monitor is connected to a machine.

You have a single class instance that wraps all of GLFW?

**Comment by Blacklands** [comment]
Thanks for the fast response!

I have a class that wraps a single GLFW window. The class has a member object that basically models the OpenGL context that is associated with that window.
I'm not even sure any more that what I was thinking makes sense.
Basically, I thought that if the user disconnects his monitor and connects a different one, that second monitor might have totally different video modes. So if the monitor gets switched, I would have to get its video modes and (possibly) set the current video mode (still of the old monitor) of the window to one of the new modes. [I read that this is currently not easily possible (specifically, without destroying the context in the process), but I heard it will probably be in GLFW 3.2?]

Now I guess what I would need to do instead is to have some global or static collection holding the video modes of the current monitor, and have the instances of my wrapper class access that instead?
The only caveat I can see with this is that if one had multiple window wrapper class instances associated with multiple monitors, things get more complicated. There would have to be some kind of static associative container which maps the different window wrapper class instances to different monitors. And all of that would have to be managed statically (e.g. "from the outside"), too. In contrast, if each class could access the monitor AND its instance (what the window user pointer can do for all the other callback methods), they could manage themselves if the monitor their windows are currently on gets switched.

As I said, I might be approaching this totally differently from how it is expected by GLFW. I come from a Java background, and I'm still having trouble with NOT trying to solve everything with classes (and given that GLFW is inherently a C library, not a C++ library, if I'm not mistaken...).

**Comment by elmindreda** [comment]
You don't need to handle the case where the user unplugs the monitor they're playing on. It's really not something people tend to do and that time is better spent elsewhere.

If there are full screen windows associated with a monitor that gets disconnected they will switch to windowed mode, but like I said, this is very unlikely to occur.

**Comment by elmindreda** [comment]
Also, it takes a very long time (from the perspective of the program) between when the old monitor is disconnected and the new one is connected. During that time, there would be no corresponding monitor and the system has no idea whether one will be connected.

**Comment by elmindreda** [comment]
You heard correctly. There will be a mechanism for switching between full screen and windowed mode.

**Comment by Blacklands** [comment]
Thanks again for your answers!
I guess you are right. I probably went a little overboard with this. Sometimes I get a bit carried away with handling corner cases. Also, yeah, the fact that it would take the user quite a while to connect the new monitor would further complicate matters. It's really not someone one should worry about I guess.
Since you cleared up my questions, I'm going to close this now. Godspeed!
