### ISSUE TITLE
Can't compile under Linux(ubuntu based distro) - pthread_key_t error

### ISSUE THREAD

**Issue by Murii** [glfw/glfw#687]
/home/omx/Desktop/Development/Love/src/3rdparty/glfw/src/glx_platform.h:98: error: unknown type name 'pthread_key_t'
     pthread_key_t   current;
     ^
Class: glx_platform.h -> typedef struct _GLFWlibraryGLX -> line 98

**Comment by Murii** [comment]
I just upgrade the version of glfw and now it's working

**Comment by jeffro256** [comment]
Try using '-lpthread' on the command line?
