### ISSUE TITLE
OpenGL 4.1 creation on El Capitan

### ISSUE THREAD

**Issue by robertsdionne** [glfw/glfw#692]
Very similar to https://github.com/glfw/glfw/issues/87 but occuring on OS X 10.11 El Capitan.

I have the following example program that is failing:

```c++
#include <cassert>
#include <iostream>

#include <GLFW/glfw3.h>

int main(int argument_count, char *arguments[]) {
  assert(glfwInit());

  glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
  glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 1);
  glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
  glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);

  GLFWwindow *window = glfwCreateWindow(1024, 768, "test", nullptr, nullptr);
  assert(window);

  glfwMakeContextCurrent(window);

  std::cout << glGetString(GL_VERSION) << std::endl;

  glClearColor(1., 1., 1., 1.);

  while (!glfwWindowShouldClose(window)) {
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

    glfwSwapBuffers(window);
    glfwPollEvents();
  }

  glfwTerminate();
  return 0;
}
```

which results in:
```bash
Assertion failed: (window), function main, file wheels/wheels.cpp, line 15.
```

while commenting out forward compatibility and core profile hints:
```c++
#include <cassert>
#include <iostream>

#include <GLFW/glfw3.h>

int main(int argument_count, char *arguments[]) {
  assert(glfwInit());

  glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
  glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 1);
  // glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
  // glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);

  GLFWwindow *window = glfwCreateWindow(1024, 768, "test", nullptr, nullptr);
  assert(window);

  glfwMakeContextCurrent(window);

  std::cout << glGetString(GL_VERSION) << std::endl;

  glClearColor(1., 1., 1., 1.);

  while (!glfwWindowShouldClose(window)) {
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

    glfwSwapBuffers(window);
    glfwPollEvents();
  }

  glfwTerminate();
  return 0;
}
```

results in a working application with the following reported OpenGL context version:
```bash
2.1 NVIDIA-10.8.14 310.42.15f01
```

However, version 4.1 was requested. Any ideas?

**Comment by shurcooL** [comment]
What version of OS X El Capitan do you have? Is it 10.11.2?

What video card do you have? Does it support 4.1?

What happens if you try requesting OpenGL 3.2 instead of 4.1?

```C++
glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 2);
glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
```

**Comment by robertsdionne** [comment]
I have a NVIDIA GeForce GT 650M card, with El Capitan 10.11.2 (15C50).

However, I notice that normally the Intel HD Graphics 4000 1536 MB card is active.

When requesting 3.2 in the window hints, it has the same behavior in both cases.

**Comment by robertsdionne** [comment]
Further information: disabling "Automatic Graphics Switching" under "Energy Saver" in system preferences and rebooting now shows the NVIDIA card as active, yet the above examples behave exactly the same in both cases.

**Comment by shurcooL** [comment]
That hardware should definitely support 3.2 and maybe even 4.1.

Which GLFW version are you using? Latest `master` branch or 3.1.2?

**Comment by robertsdionne** [comment]
The 3.1.2 source download zip https://github.com/glfw/glfw/releases/download/3.1.2/glfw-3.1.2.zip compiled with cmake/clang. I also tested with the homebrew version 3.1.2.

**Comment by shurcooL** [comment]
I could reproduce... which was very odd since similar programs worked fine for me, and I have a very similar setup. I could not find the issue until I did this:

```C++
static void error_callback(int error, const char* description)
{
    fprintf(stderr, "Error: %s\n", description);
}

glfwSetErrorCallback(error_callback);
```

Then it was immediately obvious where the problem was. You have a copy/paste error in these lines of your program:

```C++
glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 1);
```

Both lines are setting major version, instead of major and minor.

**Comment by robertsdionne** [comment]
Ah, oh wow. Of course, how did I miss that. Sorry for the time wasted.
