### ISSUE TITLE
Logging capability needed/helpful

### ISSUE THREAD

**Issue by IntellectualKitty** [glfw/glfw#695]
As someone new to GLFW, the main concern that I have with the library is the lack of ability to notify the user of problems, particularly during application initialization and startup, that prevent the application from running.  If the user's hardware or software is inadequate and GLFW cannot be initialized or an OpenGL context cannot be created, it makes a diagnostic nightmare both for the customer and the support specialist if no information about the failure is provided.  I have read the explanation in the FAQ regarding the lack of message box support in GLFW, and I think it ignores the critical case I have described above.  Nevertheless, adding some form of logging capability would at least help to alleviate this problem if message boxes are not available.

**Comment by tombsar** [comment]
Does the error callback not fulfil this need? You need to write very little code to output the error code and description to a log file, or pop up a modal message window (on Windows OS at least).

http://www.glfw.org/docs/latest/intro.html#error_handling

IMO everyone wants to do something different with error information, and logging is usually unified by the application rather than each library, so it doesn't make sense to standardize it within glfw.

**Comment by elmindreda** [comment]
@IntellectualKitty Yes, that's definitely a shortcoming. Initialization shouldn't fail, but window creation might. Hoping to add message box support at some point.

As for logging, not sure what GLFW could add above what fprintf already provides.

**Comment by IntellectualKitty** [comment]
These are all good points.  Since my experience with other operating systems is extremely limited (I'm only familiar with Mac OS X), I look at GLFW as the component that would handle all cross-platform operations, which is why I was thinking that logging would be a good capability to provide since it could then be handled in a platform-agnostic way.  For instance, syslog is available on both Mac OS X and Linux, but not on Windows (as I understand it).  My concern about using fprintf was simply that I thought it would better for messages to be logged to a standard location so that they could be found more easily (such as the Console on Mac OS X); also, since there might be additional information in system logs – e.g., an indication of driver failure – that related to the problem, it might help provide a more complete picture for diagnosis.

**Comment by IntellectualKitty** [comment]
I've thought more about it, and I think that I should withdraw my original request.  While I do think cross-platform logging capability is certainly beneficial, it's not something that would or should be unique to GLFW.  Nevertheless, I appreciate your consideration about this issue.
