### ISSUE TITLE
glfwInit() fails on Ubuntu 14.04 on EC2 server

### ISSUE THREAD

**Issue by jasjuang** [glfw/glfw#696]
glfwInit() fails on a Ubuntu 14.04 on EC2 server, where the same code runs fine on a local computer, I am guessing this might be related to #482 because the only difference between the EC2 server and the local computer is there are no monitors on the EC2 server. Please advice.

EDIT: I am on the latest glfw trunk

**Comment by jcowgill** [comment]
What does "fails" mean exactly? Do you have glfw 3.1.2 which has the fix for #482 in it?

**Comment by jasjuang** [comment]
Fails means GL_FALSE is returned by glfwInit(), and I am on the latest trunk

**Comment by jcowgill** [comment]
Any messages sent to the error callback?

**Comment by jasjuang** [comment]
The error message is X11: The DISPLAY environment variable is missing
But I am not running X11. I use ssh to connect to the server.

**Comment by jcowgill** [comment]
If you want the program to use the display server on the client machine (the one you're connecting from), use `ssh -X` to connect with. How could GLFW create windows (or really do anything) if it can't access an X11 server?

**Comment by jasjuang** [comment]
I am creating an invisible window in order to create context for offscreen rendering unit tests. Is there a way to not create a window but just create a context? Here is my code
```
  if (!glfwInit()) exit(EXIT_FAILURE);

  glfwWindowHint(GLFW_VISIBLE, GL_FALSE);

  glfw_window_ = glfwCreateWindow(10, 10, "", NULL, NULL);

  if (!glfw_window_) glfwTerminate();

  glfwMakeContextCurrent(glfw_window_);

  glewExperimental = GL_TRUE;
  if (glewInit() != GLEW_OK)
  {
    std::cout << "glewInit() error" << std::endl;
    exit(EXIT_FAILURE);
  }

  uint32_t id;
  glGenTextures(1, &id);  

  // and so on
```

**Comment by jcowgill** [comment]
I'm not sure if it is possible - I think you at least need an X11 server connection. But if all you want this for is for testing, you could use something like `Xvfb` to setup a "fake" X11 server before running your tests.

**Comment by jasjuang** [comment]
Thanks for all the help. xvfb is showing Xlib:  extension "GLX" missing on display ":99", and I have no idea how to debug it. I will just take a step back and figure out how to use glx/wgl to create a context without a window.

**Comment by jcowgill** [comment]
Woops I forgot Xvfb doesn't implement GLX. You could try Xdummy, which is newer and a bit more complicated - I've never tried it before though.

**Comment by elmindreda** [comment]
GLX is an extension of X11. It cannot be used without a running server.
