### ISSUE TITLE
Better documentation for Retina support

### ISSUE THREAD

**Issue by ataiya** [glfw/glfw#698]
It would be good to have a fully functional code sample to show how to deal with retina displays in a transparent fashion.

**Comment by elmindreda** [comment]
What is missing from the existing examples?

**Comment by ataiya** [comment]
I would like to see an example with runtime resizable window that behaves at is should across monitor types (retina v.s. not). It has been difficult to understand how to setup it properly by just looking at the documentation. 

Current behavior: If I redefine the window resize callback, the first image only uses 1/4 of the window, but as soon as I resize it goes back to normal behavior (full window). If I don't redefine the callback the image is distorted (stretched horizontally or vertically) but the window is always fully used.

**Comment by elmindreda** [comment]
Have you read [this](http://www.glfw.org/docs/latest/window.html#window_fbsize)?

**Comment by ataiya** [comment]
Hi Camilla, yes I did, but that's exactly why I am asking for a full example. It's very difficult to debug this problem unless I have a retina display (and the ability to swap between retina and not). Seeing a full example will allow me to integrate a (more likely to work) fix.

**Comment by elmindreda** [comment]
Every test and example that comes with GLFW works on Retina displays. Some poll, others use the callback.

**Comment by ataiya** [comment]
Hi Camilla, thanks for your reply. It seems that this seems to be the correct solution.
I would kindly ask you to point directly to an example in your documentation!
(it could be clearer on how to approach this problem)

```
Window(){
   /// context + window creation of size (width,height)
   /// ...
   glfwGetFramebufferSize(window, &width, &height);
   reshape(window, width, height);
}
```

**Comment by elmindreda** [comment]
When I find the time I'm going to add a page with sections on common issues. Cross-platform high-DPI support will definitely be one of them.

**Comment by ataiya** [comment]
Thanks Camilla, this will definitely be appreciated by many people. As you know what I reported above is still a bit of a hack, so it would be good to have it clearly presented.
