### ISSUE TITLE
Xbox 360 controller acting differently than Xbox One controller

### ISSUE THREAD

**Issue by dekdevy** [glfw/glfw#700]
Hello,

Im working on a game that recently released on steam; I have impemented controller support that works just fine on my local machine with a wireless xbox 360 controller. However, it seems that _some_ people have very weird issues using their xbox one controllers - but not all of them. One user sent me a video of him playing the game with his XB1 controller and it appears that the game is receiving constant input on some axis, as well has not having both triggers on one axis, but two axis rather (the way it would be expected for Xbox 360). It appears that the Y-axis of the Right analog stick on the 360 controller is the equivalent to the R-Trigger on the Xbox one controller.
Unfortunately this is breaking the controller support for a large part of my userbase and Im a bit in trouble now. Any help / ideas / alternatives would be appreciated.

thank you.

**Comment by elmindreda** [comment]
Would getting a version right away that supports XInput but not DirectInput be useful to you?

**Comment by dekdevy** [comment]
Hey, my knowledge on controller support is pretty limited, but I did a voting on the community and it seems that a large part is using Xbox (360 or XBone) controllers; some might be using misc. controllers. In general though I think that its an acceptable solution to allow Xinput and force users with devices that are incapable of generating xinput to use some kind of remapping tool or emulator.

So yes, it would definitely be incredibly useful as it would allow me to fix the input problems for a large part of the userbase. Thank you very much for your time and for GLFW in general, its amazing.

**Comment by elmindreda** [comment]
This is only a stop-gap until DirectInput support is done, of course.

I'll have the XInput code for you later today.

**Comment by elmindreda** [comment]
Have a look at the `dekdevy` branch. I threw in the joystick callback as well, in case it'll be useful.

**Comment by dekdevy** [comment]
Thank you so much, @elmindreda ! ill try it and report back.

**Comment by elmindreda** [comment]
Should be fixed now. Sorry about that.

**Comment by elmindreda** [comment]
Should I take a stab at [this](https://twitter.com/dahzeeh/status/696749888512638976) in your branch as well?

**Comment by dekdevy** [comment]
@elmindreda Any help is appreciated! :)
I'll have to grab an xbox1 controller soon. Since its happening on both mac and windows, it might be that they really generate some kind of different outputs and it can only be properly interpreted by xinput. I supposed thats why its also happening for him on mac; the xbox controllers only work though an emulator software which is probably reporting the same "fautly" signal.
All in all it wouldnt be a problem if I just left the controller schemes up to the users configuration, but its still bugging me that its not working out of the box. Ill allow configuration in the future but it might take quite some time for me to implement.

**Comment by elmindreda** [comment]
Yep. This is what #341 is meant to solve. I definitely want this to work out of the box.

**Comment by dekdevy** [comment]
Alright, here is an update from my side. 
I purchased a Xbox one controller for testing, since my 360 controller broke (unfortunately before you released the xinput fix) so I am unable to test if the 360 and the xbox one generate the same signals per axis on xinput. I suppose they do though. Ill upload a test build today so people can check it out.
However, if anyone cares, I noted down the differences that were generated between the old GLFW version (based on directInput?) and the one with Xinput.


**Direct Input (current glfw version: xbox 360 controller)**
Axis 1 - **L Stick Horizontal**
Axis 2 - **L Stick Vertical**
Axis 3 -** L Trigger + R Trigger **(-1.0 to 1.0 depending on which trigger is pressed, 0.0 if neither or both are pressed)
Axis 4 - **R Stick Vertical** (Thats right, vertical first instead of horizontal. for maximum confusion)
Axis 5 - **R Stick Horizontal **

**Xinput (current glfw version: xbox one controller, dekdevy branch: xbox one + probably xbox 360 )**
Axis 1 - **L Stick Horizontal**
Axis 2 - **L Stick Vertical**
Axis 3 - **R Stick Horizontal**
Axis 4 - **R Stick Vertical**
Axis 5 - **L Trigger** (-1.0 in idle state, 1.0 in pressed state)
Axis 6 - **R Trigger** (-1.0 in idle state, 1.0 in pressed state)

Its not like this should matter THAT much when you properly implement a user-based mapping, but it will completely mess with any preset or default mappings , so its probably worth knowing about. i havent ever read about this anywhere so i thought its worth noting down here for future reference.

**Comment by elmindreda** [comment]
The old path used winmm, not DirectInput. In the new path, DirectInput will be used only for devices that don't support XInput, so the mapping of controllers supported by the `dekdevy` branch will not be affected once DirectInput support is added. All controllers that support XInput have the same mapping.

**Comment by elmindreda** [comment]
XInput support (with DirectInput fallback) has been merged, which should have resolved this issue.

**Comment by CreamyCookie** [comment]
@dekdevy Is it resolved?

**Comment by dekdevy** [comment]
Sorry.
Yes it resolved it for me. Thank you for the fix.
