### ISSUE TITLE
Error when initializing/terminating GLFW multiple times.

### ISSUE THREAD

**Issue by ShchAlexander** [glfw/glfw#704]
When I trying to initialize glfw every second launch throws **GLFW_PLATFORM_ERROR: Win32: Failed to register window class.**
This can be reproduced with the current master of GLFW at 386b603 using this app.

```c++
#include <glfw3.h>
#include <stdio.h>
int main(int argc, char** argv) {
    int succ = glfwInit();
    fprintf(stderr, "%d\n", succ);
    glfwTerminate();
    succ = glfwInit();
    fprintf(stderr, "%d\n", succ);
    glfwTerminate();
}
```
It prints 1 followed by 0.

**Comment by httpdigest** [comment]
You should probably name this issue "Error when initializing/terminating GLFW multiple times."

**Comment by elmindreda** [comment]
Thanks!

**Comment by HwanWoongLee** [comment]
Hi.
Has this issue been resolved?
I have same problem

**Comment by elmindreda** [comment]
@HwanWoongLee It should be resolved, yes. Please open a new issue if this is happening for you.
