### ISSUE TITLE
Ubuntu 14 error when Compiling GLFW:  /usr/bin/ld: cannot find -lpthreads

### ISSUE THREAD

**Issue by lcmarte** [glfw/glfw#705]
Newer version of gcc under Ubuntu 14  will use "-pthread" to link to pthread library, however, the older version of gcc uses "-lpthreads". It seems that cmake still uses "-lpthreads".
I solve this issue from a clean Ubuntu 14 installation by make this commands:

sudo apt-get install xorg-dev build-essential libglu1-mesa-dev libc6-dev
sudo apt-get install g++ libboost-dev cmake make git doxygen

**Comment by elmindreda** [comment]
Do you mean 14.04 or 14.10?

**Comment by elmindreda** [comment]
It works fine with `-lpthread` on 14.x and 15.x.
