### ISSUE TITLE
Where I can found GLFW Vulkan example?

### ISSUE THREAD

**Issue by acterhd** [glfw/glfw#709]
Hello. Where I can found GLFW Vulkan example? Need in 1-2 files with example.

**Comment by shurcooL** [comment]
I know of these examples:

https://github.com/SaschaWillems/Vulkan#readme

**Comment by elmindreda** [comment]
@acterhd There is port of the Vulkan triangle program to GLFW in `tests/vulkan.c`. See the [Khronos Vulkan page](https://www.khronos.org/vulkan/) for a list of Vulkan example collections.
