### ISSUE TITLE
Disable F11 fullscreen toggle

### ISSUE THREAD

**Issue by imaginationcoin** [glfw/glfw#710]
F11 seems to default to a fullscreen toggle, even if I havent enabled it. How do I disable this? or change it to a different key? I cant find anything in the documentation about it. I believe I am using 3.1.2

**Comment by elmindreda** [comment]
This functionality is provided by your window manager, not GLFW. Check the settings for your window manager and/or desktop environment.

**Comment by imaginationcoin** [comment]
Ah, you are correct, toggle fullscreen is configured in ~/.config/openbox/*.xml
Thankyou
