### ISSUE TITLE
I'm sorry (hInstance of GLFW window)

### ISSUE THREAD

**Issue by acterhd** [glfw/glfw#711]
In parallel site. 
https://renderdoc.org/vulkan-in-30-minutes.html

I want to know, how to get hInstance of GLFW window?

**Comment by elmindreda** [comment]
You can get a usable `HINSTANCE` by calling `GetModuleHandle(NULL)`, but note that the current master branch of GLFW provides `glfwCreateWindowSurface` that takes care of these details for you.
