### ISSUE TITLE
[Vulkan] glfwSwapBuffers causes flickering

### ISSUE THREAD

**Issue by Sciolyte** [glfw/glfw#713]
I've used the triangle example from the Vulkan SDK and replaced the Window Context code with a GLFW Window.
The example works fine, but if you call _glfwSwapBuffers_, it causes some weird flickering. Without calling it, everything is being rendered just fine, but recording software (e.g. Bandicam) won't pick up on the window, so I'm guessing there's more to it.

**Comment by elmindreda** [comment]
You should not call glfwSwapBuffers unless you are rendering with an OpenGL or OpenGL ES context. I don't know why Bandicam isn't working.

You can find an adaption of the triangle example to GLFW in `tests/vulkan.c`.

**Comment by Temtaime** [comment]
@elmindreda hi, is there any plans about implementing swapbuffers for vulkan ? Thanks for a reply.

**Comment by elmindreda** [comment]
@Temtaime There is no need for GLFW to do that. See the `VK_KHR_swapchain` extension.
