### ISSUE TITLE
Vulkan 1.0.2 version unsupported?

### ISSUE THREAD

**Issue by acterhd** [glfw/glfw#718]
Hello. GLFW does not support AMD Vulkan 1.0.2 version? 
Also, I think `vulkan-1.dll` not detected in Windows. 
Used: Visual Studio 2015.

**Comment by elmindreda** [comment]
GLFW should work fine with Vulkan 1.0.2. The relevant differences with 1.0.3 are extremely minor.

**Comment by elmindreda** [comment]
Does GLFW report any error?

**Comment by acterhd** [comment]
How can I see error with Vulkan support?
I see that surface can't be created.

**Comment by acterhd** [comment]
Aha! You forget in documentation of Vulkan add: 
```
        if (!glfwInit()) {
		return 0;
	}
```
