### ISSUE TITLE
The autorelease pool should be drained on glfwDestroyWindow

### ISSUE THREAD

**Issue by Spasi** [glfw/glfw#721]
Currently `_glfw.ns.autoreleasePool` is drained and re-allocated on every call to `glfwPollEvents`. This is fine for most GLFW programs, i.e. doing memory clean-up once per frame.

It is a problem though for programs that only create (multiple) hidden GLFW windows for offscreen rendering/computation. Such programs may never call `glfwPollEvents`, there's never a need to and the documentation doesn't mention any memory-management side effects. The end result is that a lot of memory ends up leaking when the hidden windows are destroyed.

The proposal is that `glfwDestroyWindow` should also drain and re-allocate the `_glfw.ns.autoreleasePool`. This fixes the leak and there's no need to call `glfwPollEvents`.

**Comment by elmindreda** [comment]
That's a good point. I'll add something like the above.

Are you really seeing leaks, though? An autorelease pool is created by `glfwInit` and drained by `glfwTerminate`.

**Comment by Spasi** [comment]
`glfwTerminate` indeed drains the autorelease pool. Here's the problem, as reported by one of our users: 

> I have an application that uses LWJGL3 to do offscreen rendering. The result is copied to a JavaFX Canvas. When using the application, rendering needs to be done for multiple Canvas-es that can be dynamically created. Whenever a Canvas is shown, a separate OpenGL context is created. Whenever the canvas is hidden, I would like to free all associated resources.

In the above use-case, a canvas may be hidden while others are still active, so context resources need to be freed without calling `glfwTerminate`.

**Comment by elmindreda** [comment]
Ah, I see! Thanks!

**Comment by elmindreda** [comment]
The root cause of this seems to again be my amazing documentation writing skills. The [Event Processing](http://www.glfw.org/docs/3.1/input.html#events) section says
> Event processing must be done regularly while you have visible windows

but this needs to be done at least while _any_ windows exist, whether or not they are visible, at least to prevent the system event queue from filling up.
