### ISSUE TITLE
Sporadic crash in destroyWindow() when using Vulkan

### ISSUE THREAD

**Issue by cdwfs** [glfw/glfw#725]
I mentioned this problem on Twitter (https://twitter.com/postgoodism/status/708466175890432001) and you volunteered to take a look at the call stack. I think it's time to take you up on that offer.

I've attached as minimal a repro case I can manage; it creates a vulkan instance, device, swapchain, initializes GLFW, and immediately shuts it all down without rendering anything. Every 3-4 runs, I get a crash in GLFW's destroyWindow() function inside my call to glfwTerminate(). I'm building with MSVC 2013 (project include), and linking against GLFW commit id 793eef1d0a7. OS is Windows 7 x64, GPU is NVIDIA GTX 860M (drivers 364.47).

[vulkswagen.zip](https://github.com/glfw/glfw/files/170709/vulkswagen.zip)

One potential clue: my debug report callback reports this error when I create the swapchain:

> ERROR: [Swapchain] Code 4 : vkCreateSwapchainKHR() called with pCreateInfo->surface that was not returned by vkGetPhysicalDeviceSurfaceSupportKHR() for the device.

When I skip swapchain creation entirely, I can't seem to reproduce the crash.

**Comment by elmindreda** [comment]
I can reproduce the error message but not the crash. Windows 7 64-bit, GTX 660M with 364.47, 1.0.3.1 SDK and runtime.

**Comment by elmindreda** [comment]
Also tested with the 1.0.5.0 SDK and runtime with the same result.

**Comment by sharhar** [comment]
I managed to reproduce the swapchain error but i couldn't recreate the crash.
OS: Windows 10
GPU(s): AMD r9 270x and AMD r9 270 in crossfire
Driver: AMD Crimson 16.3 (beta)
Vulkan SDK: 1.0.3.1

**Comment by cdwfs** [comment]
Nuts. Yeah, I can't reproduce it on my desktop PC either (same environment but with a GTX 680); just my laptop. Thanks for checking; I'll keep poking around.

**Comment by elmindreda** [comment]
Did you ever find the cause of this?

**Comment by sharhar** [comment]
From my experience with Vulkan, the error is probably due to an issue with memory allocation. The error that Vulkan gives should not be the cause of the crash. Make sure that you don't under allocate memory anywhere in your code.

**Comment by cdwfs** [comment]
Nope, no sign of it in close to a year. I'd be fine with closing the issue.
