### ISSUE TITLE
vulkan.c: visible triangle 'tearing' on Geforce 940M, Win10

### ISSUE THREAD

**Issue by floooh** [glfw/glfw#726]
I'm getting a strange visible tearing effect in the vulkan.c test where the triangle is not completely rendered before the display flipping happens. Here's a screenshot of one such incomplete frame:

<img width="155" alt="glfw_vulkan_tearing" src="https://cloud.githubusercontent.com/assets/1699414/13728733/d26cc004-e921-11e5-84f2-ad664e19cbe6.png">

The LunarG cube sample looks alright on the same machine:
<img width="256" alt="lunar" src="https://cloud.githubusercontent.com/assets/1699414/13728736/e27b5d52-e921-11e5-9cbd-102f4943195a.png">

Since everything is so new, I'm not sure whether the problem is in the GLFW demo of course, could also be the driver or Vulkan SDK. But I think it's better if you're aware of it :)

I have attached a DxDiag.txt which has most of the config details (it's a dual-GPU Intel/NVIDIA Zenbook with Optimus). The Vulkan SDK version is 1.0.3.1.

Attachment: [DxDiag.txt](https://github.com/glfw/glfw/files/170965/DxDiag.txt)

**Comment by elmindreda** [comment]
Oh, you mean the animation. That's inherited from the LunarG version (which comes with the SDK) and is done [on purpose](https://github.com/glfw/glfw/blob/master/tests/vulkan.c#L1602).

**Comment by floooh** [comment]
Oh, sorry for that :) There may still be a minor sync issue, since right after starting the effect tears as if v-sync is off, and timing seems to change when I resize the window. I'll close this ticket, and see if the Lunar demo has the same issues.

**Comment by elmindreda** [comment]
It's possible their version behaves better since I stopped porting them over after 1.0.3.1.
