### ISSUE TITLE
Pressing CTRL + Pause results in a -1 keycode

### ISSUE THREAD

**Issue by stelar7** [glfw/glfw#730]
Win7, 64bit, 3.2.0 Win32 WGL VisualC DLL.

When using a key callback, pressing CTRL and Pause at the same time makes the key = -1, when the expected result would be a key of GLFW_KEY_PAUSE, with a mod of GLFW_MOD_CONTROL.

**Comment by elmindreda** [comment]
Huh.

**Comment by elmindreda** [comment]
Thank you!
