### ISSUE TITLE
Hello World example unfriendly for tiling wm users

### ISSUE THREAD

**Issue by lzap** [glfw/glfw#731]
Not sure what happened, but I am using Fedora 22 with i3 wm and after I tried to run the example code from http://www.glfw.org/documentation.html, I could not exit it (as i3 wm does not have an exit button) and the key combination did not work. I was stuck and had to xkill the app which left the app unterminated properly.

As part of this proposal, I suggest to change the example to be "tiling windows managers friendly":

```c
#include <GLFW/glfw3.h>

static void key_callback(GLFWwindow* window, int key, int scancode, int action, int mods)
{
    if (key == GLFW_KEY_ESCAPE && action == GLFW_PRESS)
        glfwSetWindowShouldClose(window, GL_TRUE);
}

int main(void)
{
    GLFWwindow* window;

    /* Initialize the library */
    if (!glfwInit())
        return -1;

    /* Create a windowed mode window and its OpenGL context */
    window = glfwCreateWindow(640, 480, "Hello World", NULL, NULL);
    if (!window)
    {
        glfwTerminate();
        return -1;
    }

    /* Make the window's context current */
    glfwMakeContextCurrent(window);

    /* Listen to key events */
    glfwSetKeyCallback(window, key_callback);

    /* Loop until the user closes the window */
    while (!glfwWindowShouldClose(window))
    {
        /* Render here */

        /* Swap front and back buffers */
        glfwSwapBuffers(window);

        /* Poll for and process events */
        glfwPollEvents();
    }

    glfwTerminate();
    return 0;
}
```

**Comment by lzap** [comment]
Initially I filed this for go bindindg and smart guys from that project identified a more simple solution. Since the purpose of this hello world simplicity, you could do the same: https://github.com/go-gl/glfw/issues/155

**Comment by linkmauve** [comment]
According to their user guide (see https://i3wm.org/docs/userguide.html#_closing_windows), i3 has the $mod+Shift+q keybinding to tell an X11 window it should close.  Every other usable tiling environment have such a keybinding.

I suggest to leave this example as is, since it works fine there, and to close this bug.

**Comment by shurcooL** [comment]
If that's the case, I'm in agreement with @linkmauve's proposed action.

**Comment by elmindreda** [comment]
Me too.

**Comment by lzap** [comment]
I know about this keybinding and I have already tested it. Unfortunately the keybinding does not work in glfw, most likely keyboard is in some special mode. :-(

**Comment by dedred** [comment]
Hi,
Look what I've found on the web, this is something new I guess, you'll be excited. More info here <http://chefokibe.assure-infotech.com/aeryut>

acreator@blueyonder.co.uk

**Comment by dedred** [comment]
Hello,
I think you have to try this thing, it's so hilarious, take a look at <http://nugandetri.acousticar.com/aenon>

Bests, acreator@blueyonder.co.uk
