### ISSUE TITLE
Window attention request

### ISSUE THREAD

**Issue by stelar7** [glfw/glfw#732]
Is there a way for glfw to request that the window should get focus?
and a way for it to drop focus?
IE. flashing the task bar icon? [(like this)](http://answers.unity3d.com/storage/temp/31886-1.png)

**Comment by elmindreda** [comment]
If you mean like [FlashWindow](https://msdn.microsoft.com/en-us/library/windows/desktop/ms679346.aspx] then no, that's not yet supported.

**Comment by felipefs** [comment]
I'm not sure how this feature works on windows, but I was able to create a function ```glfwRequestWindowAttention()``` for X11. If there's interest on this, I can upload the branch and make a pull request.

**Comment by felipefs** [comment]
I've made the implementation for X11 and Windows (using ```FlashWindow```). I tested the Windows implementation on Linux, using Wine. Some extra test on Windows would be nice to make sure of the behavior. Here's the branch: https://github.com/felipefs/glfw/tree/attention-request

**Comment by elmindreda** [comment]
This has been added with #988.
