### ISSUE TITLE
clipboard issue and return codes

### ISSUE THREAD

**Issue by artsmi** [glfw/glfw#733]
Hey guys!
When I'm using glfwGetClipboardString it has about 10% chance to fail to copy data and reset clipboard on my OS. for debugging this issue I need check output log. I see "Win32: Failed to open clipboard". Can you add  more informative return's code? GetLastError showed 0x0 that's not informative, but glfwGetClipboardString returns void.

**Comment by elmindreda** [comment]
System error strings are now appended for API errors in `glfwGetClipboardString` and many other functions on Windows with c28778e28c40a55de9c3d857ef27d8f070772fc6.

It really shouldn't fail that often, though. There is probably another application in the background that continually locks and updates the clipboard, which is an exclusive operation on Windows.

**Comment by elmindreda** [comment]
If you were calling `GetLastError` from outside of `glfwGetClipboardString` then the error code may have been overwritten by a clean-up call like `CloseClipboard`.
