### ISSUE TITLE
segfault on glfwDestroyWindow

### ISSUE THREAD

**Issue by infernalbuild** [glfw/glfw#736]
there is the gdb log

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff165f820 in ?? () from /usr/lib64/xorg/modules/dri/i965_dri.so

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.
Quit

**Comment by elmindreda** [comment]
What version of which OS are you on? What is your GLFW version string?

**Comment by infernalbuild** [comment]
Im on Linux Zenwalk
but i found the issue it was a just a mistake from me , I 'd forgot to check if an integer was equals to -1 and then i'd used this integer as an offset on a pointer, so the pointer modified some weird parameter in my programm causing the crash.
Since this i made some more check and it is perfectly stable
