### ISSUE TITLE
Fullscreen switch problem on Linux after glfwWindowHint(GLFW_RESIZABLE, GL_FALSE)

### ISSUE THREAD

**Issue by fountainment** [glfw/glfw#737]
When I add a line '**glfwWindowHint(GLFW_RESIZABLE, GL_FALSE);**' before 'window = glfwCreateWindow' in 'examples/boing.c' (line 630).

On Windows, it works well when **switch back from fullscreen to windowed**. (get 400\*400 window).
On **Linux**, the window become windowed but **remain the screen size**. (get 1366\*768 window on my laptop).

http://pastebin.ubuntu.com/15805342/
The only difference i made is the 'glfwWindowHint(GLFW_RESIZABLE, GL_FALSE);'  in line 630.

My system is ubuntu14.04 and my X server version is 1.17.1.

**Comment by elmindreda** [comment]
@linkmauve This affects Wayland as well?
