### ISSUE TITLE
glfwSetWindowSizeCallback and glfwSetFramebufferSizeCallback incorrect on monitor orientation change.

### ISSUE THREAD

**Issue by dougbinks** [glfw/glfw#740]
Avery Musbach (username on discourse DigitalEmotions) has [reported an issue with the size and framebuffersize callbacks on Windows](http://discourse.glfw.org/t/misleading-api-documentation/636).

I've verified that this issue exists as described on my Windows 8.1 system.

Specifics:

If the monitor undergoes an orientation change from landscape to portrait or visa versa in Windows the **glfwSetWindowSizeCallback** and **glfwSetFramebufferSizeCallback** functions report the incorrect width and height, with the these being transposed. This causes any viewport change using the values provided to result in incorrect rendering. This can be confirmed by calling **glfwGetWindowSize()** in the callback which will return the correct result.

Further investigation shows that the WM_SIZE message posted is the root of the error, as it appears to be incorrect after an orientation change. According to msdn the WM_DISPLAYCHANGE message should provide the correct width and heigh, but it is simpler to alter the WM_SIZE to check the client area using either glfwGetFramebufferSize, glfwGetWindowSize. I have a fix with this in which I'll provide a pull request for.

**Workaround** Use glfwGetFramebufferSize for viewport size setting. Note that this returns the same values  in Windows as glfwGetWindowSize.

**OS:** Windows 7 (unknown specifics), Windows 8.1 64bit.

**Comment by elmindreda** [comment]
`WM_SIZE` is innocent!

The dimensions reported by it are correct, but late. The problem stems from `WM_SIZE` also being the message for window restoration from iconification. GLFW detects this and first re-enters full screen mode, which entails resizing the window to the display, which then recurses into the second `WM_SIZE` and lastly reports to the callback whatever size it was given in the first event. I'll just swap the order of operations.

**Comment by dougbinks** [comment]
D'oh!

For testing I made a quick branch and fix. Can confirm that this works.

**Comment by elmindreda** [comment]
Thank you for reporting this!

**Comment by dougbinks** [comment]
No problem - just pulled latest and can confirm this is fixed, thanks!
