### ISSUE TITLE
vkGetInstanceProcAddr incorrectly returns NULL for vkCreateWin32SurfaceKHR

### ISSUE THREAD

**Issue by Overv** [glfw/glfw#744]
I'm trying to use `glfwCreateWindowSurface` to create a window surface for my Vulkan instance, but it fails with a `VK_ERROR_EXTENSION_NOT_PRESENT` error because `vkGetInstanceProcAddr(instance, "vkCreateWin32SurfaceKHR")` returns `NULL` (see [this line](https://github.com/glfw/glfw/blob/master/src/win32_window.c#L1670)).

This is strange, because if I use the following code instead of `glfwCreateWindowSurface`:

    VkWin32SurfaceCreateInfoKHR surfaceInfo = {};
    surfaceInfo.sType = VK_STRUCTURE_TYPE_WIN32_SURFACE_CREATE_INFO_KHR;
    surfaceInfo.hinstance = GetModuleHandle(nullptr);
    surfaceInfo.hwnd = glfwGetWin32Window(window);

    if (vkCreateWin32SurfaceKHR(instance, &surfaceInfo, nullptr, &windowSurface) != VK_SUCCESS) {
        std::cerr << "failed to create window surface!" << std::endl;
        exit(1);
    }

Then it works fine. Also, if I use `vkGetInstanceProcAddr` in my own program, it does not return `NULL`. It appears that GLFW internally uses a different implementation of `vkGetInstanceProcAddr` that is acquired on [this line](https://github.com/glfw/glfw/blob/master/src/vulkan.c#L54) and reports invalid results.

I'm running Windows 10 with the latest AMD beta driver and version `1.0.8.0` of the LunarG SDK.

**Comment by Overv** [comment]
I fixed the problem by linking `vulkan-1.lib` instead of `VKstatic.1.lib`.

**Comment by Delwin9999** [comment]
I'm getting this with the linux surface creation on version 3.2.1.  CentOS 6 with NVidia 367.57, GCC 4.9 and API 1.0.30.  If I insert 

        if (!vkCreateXcbSurfaceKHR)
            vkCreateXcbSurfaceKHR = (PFN_vkCreateXcbSurfaceKHR) _glfw_dlsym(_glfw.vk.handle, "vkCreateXcbSurfaceKHR");

right after the vkGetInstanceProcAddr call then it works fine as it will fall back to the dll loader when it can't find the extension using vkGetInstanceProcAddr.  This is a known problem with dynamically loading the Vulkan library and there's a lot of chatter about it on the Vulkan-Docs repository.

**Comment by elmindreda** [comment]
@Delwin9999 Thanks, will look into it. Do you have the issue number handy?

**Comment by Delwin9999** [comment]
744 if you mean the issue number that this is part of.

**Comment by Delwin9999** [comment]
https://github.com/KhronosGroup/Vulkan-Docs/issues/212

**Comment by elmindreda** [comment]
@Delwin9999 The issue @Overv was having was using the static library form of the Vulkan loader while GLFW expected the shared library form. Which are you using?

**Comment by Delwin9999** [comment]
Shared.

**Comment by elmindreda** [comment]
@Delwin9999 This is a separate problem then. Please open a new issue for it.
