### ISSUE TITLE
Two windows and glfwSetCursor

### ISSUE THREAD

**Issue by NkD** [glfw/glfw#745]
I have two windows. One is primary (window1) and second (window2) which share context with window1.
Then I try set different mouse cursor to window1 and window2.
pseudo code:
glfwSetCursor(window1.hwnd, HAND)
glfwSetCursor(window2.hwnd, HRESIZE)

If window1 has focus and mouse cursor is in window1 area, then cursor is HAND (correct).
But when I move cursor to window2 area (enter callback event icomming), then cursor is ARROW (bug). This is because window2 hasn't  focus. If click now and window2 got focus, cursor is changed to HRESIZE (ok).

Problem: Mouse cursor doesn't changed if is in window area which hasn't focus.

Windows7 x64
lwjgl3 (Nigthly - #3.0.0 build 72) + GLFW 3.2?

**Comment by elmindreda** [comment]
Oh, right, this was fixed in 3.2 with 2d2756cbadeae77d2648708f7b476e45849a8abc.
