### ISSUE TITLE
glfwSetWindowMonitor broken

### ISSUE THREAD

**Issue by Spasi** [glfw/glfw#748]
Restoring fullscreen mode to windowed mode does not respect the `glfwSetWindowMonitor` arguments.

GLFW 3.2.0 Cocoa NSGL chdir menubar retina dynamic (d97044d9acc0c76433edda5a75b3196957906ca5)
OS X 10.11.4
Intel Iris Graphics 6100
#### Details

While in fullscreen mode, calling `glfwSetWindowMonitor(window, NULL, xpos, ypos, width, height, 0);` does not result in a window at `xpos, ypos` with `width x height` dimensions, but rather covers the entire screen (like having double-clicked on the window title bar). Printing all events gives the following sequence:

```
BEFORE RESTORE to: 520,176 - 640 x 480
6.252: Window framebuffer resized to 3300 x 2002
6.253: Window resized to 1650 x 1001
6.256: Window framebuffer resized to 1650 x 1001
6.260: Window refreshed
6.270: Window framebuffer resized to 640 x 480
6.271: Window resized to 640 x 480
6.273: Window refreshed
AFTER RESTORE
6.277: Window framebuffer resized to 1680 x 1001
6.278: Window resized to 1680 x 1001
6.281: Window refreshed
6.310: Window framebuffer resized to 3360 x 2002
6.322: Window refreshed
```

A workaround seems to be:

``` c
glfwSetWindowMonitor(window, NULL, xpos, ypos, width, height, 0);
glfwPollEvents();
glfwSetWindowMonitor(window, NULL, xpos, ypos, width, height, 0);
```

I also randomly inserted a `_glfwPlatformPollEvents();` in `cocoa_window.m` after `_glfwInputWindowMonitorChange(window, monitor);` at line 1220. This also fixes the issue and produces the following output:

```
BEFORE RESTORE to: 520,176 - 640 x 480
    BEFORE INNER POLL EVENTS
11.455: Window moved to 0, 0
11.456: Window framebuffer resized to 3300 x 2100
11.459: Window refreshed
    AFTER INNER POLL EVENTS
11.510: Window framebuffer resized to 3300 x 2002
11.511: Window resized to 1650 x 1001
11.537: Window framebuffer resized to 3300 x 2002
11.547: Window refreshed
11.574: Window framebuffer resized to 1280 x 960
11.574: Window resized to 640 x 480
11.579: Window refreshed
AFTER RESTORE
```

Note also that, even though with the workarounds the window ends-up in the correct shape, window position events are missing.

**Comment by elmindreda** [comment]
I can verify that the position callback does not get called as it should be both on entering or exiting full screen mode, but I'm unable to reproduce the window placement issue (using the Boing example on 10.11.4 with 4eb7cbac47c7d40e2c1469016b54f9323aa36d8f).

**Comment by Spasi** [comment]
Did some more testing and the window placement issue only occurs when the switch to fullscreen caused an actual display mode change. On OS X, you know there's a display mode change when the switch is not instantaneous; there's maybe a delay of 1 second and the screen going black between switches.

Note that I'm not doing anything weird with the display mode, just using the native mode as reported by `glfwGetVideoMode(gflwGetPrimaryMonitor())`. I'm on a retina macbook and the issue is reproducible only on specific levels of scale. Looks like it might be the same issue as #682. Disabling `setWantsBestResolutionOpenGLSurface` does not help, but using SwitchResX to switch to the corresponding non-HiDPI resolution for the current scale level resolves the issue.
