### ISSUE TITLE
Add a GLFW_CENTER_CURSOR window hint

### ISSUE THREAD

**Issue by cafarm** [glfw/glfw#749]
Any chance of adding a GLFW_CENTER_CURSOR window hint that defaults to GL_TRUE but can be set to GL_FALSE?

Commit f3b6544 "fixed" behavior that was actually ideal for my application. I don't want to center the cursor over newly created full screen windows.

**Comment by shurcooL** [comment]
Would this window hint achieve something that can't be done simply by using existing APIs to get the monitor size, calculate its center, and position the cursor?

**Comment by cafarm** [comment]
The second one: it's about giving the ability to turn off that default behavior.
