### ISSUE TITLE
Support Oculus PC SDK 1.3

### ISSUE THREAD

**Issue by raysan5** [glfw/glfw#750]
I'm porting my C games library, [raylib](https://github.com/raysan5/raylib), to Oculus PC SDK 1.3 (and Oculus Rift CV1). On most of the platforms raylib uses GLFW3 for windows/context/input management and I also expected to use it for Oculus Rift CV1.

I setup a small sample to test Oculus Rift initialization and context creation: https://github.com/raysan5/raylib/tree/develop/examples/oculus_glfw_sample

Oculus connection and management seems to work ok but I can not link GLFW3 windows/context with Oculus windows/context because `ovrHmd_AttachToWindow()` was removed from the API. Neither I can use the Extended Desktop Mode (configuring and detecting the Oculus as a second monitor) because since Oculus SDK 0.7 it can only be accessed in Direct HMD mode.

When I compile and run my sample, Oculus is initialized correctly but, apparently, I get two window/context, the one provided by GLFW3 (that I clear to red) and a window/context provided by Oculus SDK (colored in black), that black Oculus window/context can be seen in the desktop and in the glasses.

Any help or tip on this issue is highly appreciated!

**Comment by shurcooL** [comment]
Just checking, but have you already seen/read http://www.glfw.org/docs/latest/rift.html?

**Comment by raysan5** [comment]
Thanks @shurcooL, I already checked that document, it's intended for Oculus SDK 0.4.4 and I'm using Oculus SDK 1.3 (with Oculus Rift CV1); `ovrHmd_attachToWindow()` was removed from the API.

Actually, there is another issue about updating that documentation: https://github.com/glfw/glfw/issues/513

**Comment by raysan5** [comment]
Finally managed to get it working thanks to @jherico sample: https://github.com/jherico/OculusMinimalExample

I used GLFW3 3.1.2. Here it is an screenshot:
![raylib_oculusriftcv1](https://cloud.githubusercontent.com/assets/5766837/15023424/b22a1ade-1230-11e6-99b0-dca22e233409.png)

Actually, setup was easier than listed in documentation... I'm cleaning up my C sample and I'll share it here before closing the bug.

**Comment by jherico** [comment]
@raysan5 that screenshot doesn't look quite right.  Looks like the eye offsets may be inverted.

**Comment by raysan5** [comment]
Thanks @jherico! Actually, it was just a quick test, eyes projection-modelview matrices are not being used in that draw; I'm reviewing it to use my own math library.

**Comment by raysan5** [comment]
GLFW3 + GLAD + Oculus PC SDK 1.4 code sample is already functional, you can check it [here](https://github.com/raysan5/raylib/tree/develop/examples/oculus_glfw_sample). You can close the issue.
