### ISSUE TITLE
GLFW_CURSOR_DISABLED produces large deltas

### ISSUE THREAD

**Issue by httpdigest** [glfw/glfw#759]
I am testing GLFW on an Ubuntu Desktop 16.04 LTS x64 on Oracle VirtualBox 5.0.20 with a Windows 7 x64 host.

There, when I use `glfwSetInputMode(window, GLFW_CURSOR, GLFW_CURSOR_DISABLED);` the callback registered via `glfwSetCursorPosCallback` receives very large position deltas. For example, when I move the mouse only one pixel to the right, the xpos delta sometimes is -400.0, other times -110.0 and then sometimes even -1000.0, also somtimes positive and sometimes negative.
I know that the xpos and ypos coordinates can have arbitrary large values since the mouse cursor is unrestricted. But I am talking about the delta (the changes between successive xpos and ypos values for successive calls of the callback). I am getting very large deltas here.
On Windows everything is fine. It's just weird on Ubuntu Desktop 16.04 LTS. I don't know whether it is a thing with Oracle VirtualBox.

Here is the example app I use to test this:
```C
#include <GLFW/glfw3.h>
#include <stdlib.h>
#include <stdio.h>
static void error_callback(int error, const char* description) {
    fprintf(stderr, "Error: %s\n", description);
}
static void key_callback(GLFWwindow* window, int key, int scancode, int action, int mods) {
    if (key == GLFW_KEY_ESCAPE && action == GLFW_PRESS)
        glfwSetWindowShouldClose(window, GLFW_TRUE);
}
static void cp_callback(GLFWwindow* window, double xpos, double ypos) {
  fprintf(stderr, "%f , %f\n", (float)xpos, (float)ypos);
  fflush(stderr);
}
int main(void) {
    GLFWwindow* window;
    glfwSetErrorCallback(error_callback);
    if (!glfwInit())
        exit(EXIT_FAILURE);
    window = glfwCreateWindow(640, 480, "", NULL, NULL);
    if (!window) {
        glfwTerminate();
        exit(EXIT_FAILURE);
    }
    glfwSetKeyCallback(window, key_callback);
    glfwSetCursorPosCallback(window, cp_callback);
    glfwSetInputMode(window, GLFW_CURSOR, GLFW_CURSOR_DISABLED);
    while (!glfwWindowShouldClose(window)) {
        glfwPollEvents();
    }
    glfwDestroyWindow(window);
    glfwTerminate();
    exit(EXIT_SUCCESS);
}
```

And here is the output I get from moving the mouse cursor very very slightly (should be just one pixel each) to the right:
```
639.000000 , 479.000000
958.000000 , 479.000000
1277.000000 , 479.000000
1596.000000 , 479.000000
1915.000000 , 479.000000
2234.000000 , 479.000000
2553.000000 , 479.000000
2872.000000 , 479.000000
3191.000000 , 479.000000
3510.000000 , 479.000000
```
In this run, the delta happens to be around +319.0'ish.
I do not have a HighDPI monitor or HighDPI mouse.

The issue does not happen when using GLFW_CURSOR_HIDDEN or GLFW_CURSOR_NORMAL. In those two settings, I get correct pixel values.

**Comment by elmindreda** [comment]
Have you disabled cursor integration in VirtualBox?

**Comment by httpdigest** [comment]
Hm... if, then not consciously. This is a very off the shelves installation with absolutely no customization of settings or stuff. The only thing I did was to install the Guest Additions which compiled and built successfully.

**Comment by httpdigest** [comment]
Interesting. When I disable mouse cursor integration (leaving that mouse in the status bar gray with a yellow arrow) the readings of the cursor position are correct now.

**Comment by elmindreda** [comment]
This is not a bug, it's just GLFW and VirtualBox fighting over where the cursor should be. Leave cursor integration off while you're working with disabled cursor mode and it'll be fine.

**Comment by httpdigest** [comment]
Thank you! Will do.
