### ISSUE TITLE
GLFW Static and Shared using PKG_CONFIG

### ISSUE THREAD

**Issue by shehzan10** [glfw/glfw#765]
I'm trying to integrate GLFW using PKG_CONFIG into my application that uses CMake. I have built and installed GLFW from source to /usr/local. I first did it first for static and followed by shared libs. 

Relevant output

```
-- Install configuration: "Release"
-- Installing: /usr/local/include/GLFW
-- Up-to-date: /usr/local/include/GLFW/glfw3.h
-- Up-to-date: /usr/local/include/GLFW/glfw3native.h
-- Installing: /usr/local/lib/cmake/glfw/glfw3Config.cmake
-- Installing: /usr/local/lib/cmake/glfw/glfw3ConfigVersion.cmake
-- Old export file "/usr/local/lib/cmake/glfw/glfwTargets.cmake" will be replaced.  Removing files [/usr/local/lib/cmake/glfw/glfwTargets-release.cmake].
-- Installing: /usr/local/lib/cmake/glfw/glfwTargets.cmake
-- Installing: /usr/local/lib/cmake/glfw/glfwTargets-release.cmake
-- Installing: /usr/local/lib/pkgconfig/glfw3.pc
-- Up-to-date: /usr/local/lib/libglfw3.a
```

```
-- Install configuration: "Release"
-- Installing: /usr/local/include/GLFW
-- Up-to-date: /usr/local/include/GLFW/glfw3.h
-- Up-to-date: /usr/local/include/GLFW/glfw3native.h
-- Installing: /usr/local/lib/cmake/glfw/glfw3Config.cmake
-- Installing: /usr/local/lib/cmake/glfw/glfw3ConfigVersion.cmake
-- Old export file "/usr/local/lib/cmake/glfw/glfwTargets.cmake" will be replaced.  Removing files [/usr/local/lib/cmake/glfw/glfwTargets-release.cmake].
-- Installing: /usr/local/lib/cmake/glfw/glfwTargets.cmake
-- Installing: /usr/local/lib/cmake/glfw/glfwTargets-release.cmake
-- Installing: /usr/local/lib/pkgconfig/glfw3.pc
-- Up-to-date: /usr/local/lib/libglfw.so.3.1
-- Up-to-date: /usr/local/lib/libglfw.so.3
-- Up-to-date: /usr/local/lib/libglfw.so
```

Now I added 

```
# Check if we can use PkgConfig
FIND_PACKAGE(PkgConfig)

#Determine from PKG
IF(PKG_CONFIG_FOUND AND NOT GLFW_ROOT_DIR)
    PKG_SEARCH_MODULE(GLFW QUIET glfw3)
ENDIF()

IF(GLFW_FOUND)
    MESSAGE("GLFW_INCLUDE_DIRS = ${GLFW_INCLUDE_DIRS}")
    MESSAGE("GLFW_LIBRARIES = ${GLFW_LIBRARIES}")
    MESSAGE("GLFW_STATIC_LIBRARIES = ${GLFW_STATIC_LIBRARIES}")
ENDIF(GLFW_FOUND) # GLFW Was not found by PKG_CONFIG
```

 However, this prints

```
GLFW_INCLUDE_DIRS = /usr/local/include;/usr/include/libdrm
GLFW_LIBRARIES = glfw
GLFW_STATIC_LIBRARIES = glfw;rt;m;dl;Xrandr;Xinerama;Xi;Xcursor;Xrender;GL;m;pthread;dl;drm;Xdamage;Xfixes;X11-xcb;xcb-glx;xcb-dri2;xcb-dri3;xcb-present;xcb-sync;xshmfence;Xxf86vm;Xext;X11;pthread;xcb;Xau;Xdmcp
```

Now this would work fine for the shared libraries, but I dont understand why the static libraries variable has `glfw` instead of `glfw3`.

I also tried installing shared followed by static in which case it gave the following output:
(the static lib is picked up for both the `GLFW_LIBRARIES` and `GLFW_STATIC_LIBRARIES` variable)

```
GLFW_INCLUDE_DIRS = /usr/local/include;/usr/include/libdrm
GLFW_LIBRARIES = glfw3
GLFW_STATIC_LIBRARIES = glfw3;rt;m;dl;Xrandr;Xinerama;Xi;Xcursor;Xrender;GL;m;pthread;dl;drm;Xdamage;Xfixes;X11-xcb;xcb-glx;xcb-dri2;xcb-dri3;xcb-present;xcb-sync;xshmfence;Xxf86vm;Xext;X11;pthread;xcb;Xau;Xdmcp
```

My question is why cant they both exist in the package config file (glfw.pc)?
Is it possible to pick on over the other if both are installed? I know it can be done manually in CMake using `FIND_LIBRARY` etc, but I was hoping package config could handle this.

Ideally, the package config should pick up both libraries correctly. If one of them is not present, then the variable should simply be empty. This way users like me can pick whether to link with static or with shared.

I am using v3.1.2 tag on a Debian.

EDIT:
PKG_CONFIG uses the variables `PREFIX_FOUND` and `PREFIX_STATIC_FOUND` to set if shared or static libs were found. However, in the case of GLFW, both shared and static versions only set GLFW_FOUND. So there is no was to really differentiate if static was found and base the CMake scripts off of that.

**Comment by elmindreda** [comment]
> My question is why cant they both exist in the package config file (glfw.pc)?

Because of the structure of a `.pc` file. There is a field for linker flags common to the shared and static configurations and another field specific to the static configuration. There is no field specific to the shared configuration.

If you are using CMake to build your application and want to use installed GLFW binaries then the [CMake config package](http://www.glfw.org/docs/latest/build.html#build_link_cmake_package) might be slightly more hassle-free, but it doesn't help with this issue.

**Comment by shehzan10** [comment]
The reason I asked for this feature was because it helps in building with both static and shared libraries using pkg-config. It certainly is possible for me to write my own FindGLFW.cmake and use that instead of the package config. But that defeats the purpose of CMake advocating for users to use package config.

> Because of the structure of a .pc file. There is a field for linker flags common to the shared and static configurations and another field specific to the static configuration. There is no field specific to the shared configuration.

I thought the `GLFW_LIBRARIES` flag was for shared and `GLFW_STATIC_LIBRARIES` was for static libraries and hence I made the feature request.

According to what you have said, this is not possible. I'll try to investigate a little when I get time.

**Comment by elmindreda** [comment]
This is not possible to achieve with pkg-config as it's currently designed.
