### ISSUE TITLE
initialization context problem.

### ISSUE THREAD

**Issue by giordi91** [glfw/glfw#766]
Hi, I am currently trying to get shadow mapping working, and after hitting my head all over the place I cannot make it to work, so I started to compare 1:1 my code with all the tutorials online. But there is no way to get my shadow texture to render, it comes white, while following one of the tutorials I saw the guy setting major and minor context version, which I did not do, so I wondered if that could have been a problem and decided to set the version aswell, all my shader use 430 as version so I thought to set the same, here how i initialize the window:

```c
    if (!glfwInit())
        exit(EXIT_FAILURE);
    
    //here we crate a pointer to our window
    GLFWwindow* window;
    //here we setup the callbacks
    glfwSetErrorCallback(error_callback);
	glfwWindowHint(GLFW_SAMPLES, 4);
	//glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
	//glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
	//glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE); // To make MacOS happy; should not be needed
	//glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
    //createing the window and check if it s all good
    window = glfwCreateWindow((int)settings->m_window_width, 
							  (int)settings->m_window_height, 
							  "Platfoorm 1.0", 
							  nullptr, 
							  nullptr);
    // get version info
	    
	if (!window)
    {
        glfwTerminate();
        exit(EXIT_FAILURE);
    }

    //setting up the context and swap interval
    glfwMakeContextCurrent(window);
    glewInit ();
    glfwSwapInterval((int)settings->m_vsync);
```

Now as soon as I try to set minor or major context, I start to get problem all over the place, where opengl call crash saying I am trying to write to 0x00000 etc. Basically this happens with the first function call to opengl. Also instead if I try to set opengl core profile. I get error saying that the profile works only from opengl 3.2 and up. My driver support up to opengl 4.5 and that s what I thought I was using, I have been using geometry shaders aswell which are core since 3.2 so I should at least be running a 3.2 context. I am really confused by that. Do you see anything wrong in my code? or what do you think might trigger the problem if i set the context version?
Is it there a way to query whats the version of the created context? The crashing in opengl might it be a problem with glewInit() not initializing properly if the context is too high?

Any help on the matter is much appreciated. I am running glfw 3.1.2

**Comment by giordi91** [comment]
ps, I jumped back in the git revision to pretty much at the beginning of the project when I just had a triangle moving up and down, as soon as I touch GLFW_CONTEXT_VERSION nothing gets rendered at screen any-more, I don't get errors or crash just no render whatsoever.

**Comment by intrigus** [comment]
You can and should set the error callback before you initialize glfw.

**Comment by elmindreda** [comment]
@giordi91 What is the output of `glfwinfo -m4 -n3 -pcore -f`?

**Comment by giordi91** [comment]
Hi here is the output, i recompiled the latest 3.2 glfw to run glwinfo i hope that doesnt affect the result.

`Welcome to Git (version 1.9.5-preview20141217)


Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.


$ ./glfwinfo.exe -m4 -n3 -pcore -f
GLFW header version: 3.2.0
GLFW library version: 3.2.0
GLFW library version string: "3.2.0 Win32 WGL EGL VisualC"
OpenGL context version string: "4.3.0 NVIDIA 365.19"
OpenGL context version parsed by GLFW: 4.3.0
OpenGL context flags (0x00000001): forward-compatible
OpenGL context flags parsed by GLFW: forward-compatible
OpenGL profile mask (0x00000001): core
OpenGL profile mask parsed by GLFW: core
OpenGL robustness strategy (0x00008261): none
OpenGL robustness strategy parsed by GLFW: none
OpenGL context renderer string: "GeForce GTX 960/PCIe/SSE2"
OpenGL context vendor string: "NVIDIA Corporation"
OpenGL context shading language version: "4.30 NVIDIA via Cg compiler"
OpenGL framebuffer:
 red: 8 green: 8 blue: 8 alpha: 8 depth: 24 stencil: 8
 samples: 0 sample buffers: 0
Vulkan loader: missing


The driver should support up to 4.5 no problem, same goes for the card.

**Comment by giordi91** [comment]
@intrigus thanks for the tip, I moved the error calback before the init but did not change anything , and no extra output was seen at the console, aka I think the init works fine.

**Comment by elmindreda** [comment]
Versioned context creation seems to work, then. This does not appear to be a bug in GLFW.

**Comment by giordi91** [comment]
if the context is not specified, what will glfw create? is it possible to
create afterwards from the context?



On Fri, May 27, 2016 at 2:24 PM, Camilla Berglund <notifications@github.com>
wrote:

> Versioned context creation seems to work, then. This does not appear to be
> a bug in GLFW.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/glfw/glfw/issues/766#issuecomment-222145205>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ACaKZYTXwPXhDROIopRGQi50TUNOMaiOks5qFvCMgaJpZM4ImXel>
> .
>



-- 
Marco Giordano
Software Developer at Frontier Developmet
+447462721890
London(UK)
linkedin  <http://be.linkedin.com/in/marcogiordano3d/>

**Comment by elmindreda** [comment]
Sorry, I don't understand what that means.

**Comment by giordi91** [comment]
if I create a glfw window without asking for a specific context version ,
like 4.3 ,3.2 core etc. what context glfw creates for me? basically what is
the default?

On Fri, May 27, 2016 at 2:44 PM, Camilla Berglund <notifications@github.com>
wrote:

> Sorry, I don't understand what that means.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/glfw/glfw/issues/766#issuecomment-222150038>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ACaKZTxmMpgdm6l9avT3_lsAxSmfvUXYks5qFvVQgaJpZM4ImXel>
> .
>



-- 
Marco Giordano
Software Developer at Frontier Developmet
+447462721890
London(UK)
linkedin  <http://be.linkedin.com/in/marcogiordano3d/>

**Comment by elmindreda** [comment]
See [the documentation](http://www.glfw.org/docs/3.2/window_guide.html#window_hints_ctx) for those hints:
> `GLFW_CONTEXT_VERSION_MAJOR` and `GLFW_CONTEXT_VERSION_MINOR` are not hard constraints, but creation will fail if the OpenGL version of the created context is less than the one requested. It is therefore perfectly safe to use the default of version 1.0 for legacy code and you may still get backwards-compatible contexts of version 3.0 and above when available.

> While there is no way to ask the driver for a context of the highest supported version, GLFW will attempt to provide this when you ask for a version 1.0 context, which is the default for these hints.

**Comment by elmindreda** [comment]
Also note that if you request version 3.2 or greater, the context may by default have any profile.

**Comment by giordi91** [comment]
Yes that s what I mean, I am sorry if I am not explaining myself correctly.

that s is how I am currently initalizing the window:
` GLFWwindow* window;
    //here we setup the callbacks

    window = glfwCreateWindow((int)settings->m_window_width, 
                              (int)settings->m_window_height, 
                              "Platfoorm 1.0", 
                              nullptr, 
                              nullptr);`

I am not setting any hint to glfw of the version of the context I want. In that case what kind of context will glfw try to initialize for me ? I don't think it is a 1.0 because i am using shaders and geometry shaders etc. So what I would like to know is what context version is glfw trying to initialize if not asked explicitly? If not asked explicitly will be glfw making the decision or the driver?

Either way if not explicitly set, is there a way to query with what version the context has been created? I hope it makes sense.

**Comment by giordi91** [comment]
I was finally able to debug the problem, thanks to gDebugger, what i noticed was the following, when I set GLFW_CONTEXT the current context get destroyed and recreated, as you can see here:
Here in the first image i set the context and you can see deletion and creation of the context
![context2](https://cloud.githubusercontent.com/assets/2525797/15673549/5ff114fc-272f-11e6-8590-3cd2da778553.jpg)

In the second image where those lines have been commented you don't get the problem.
![context1](https://cloud.githubusercontent.com/assets/2525797/15673550/5ff56f7a-272f-11e6-9c96-3ba4e9aea023.jpg)

I fixed that by moving the lines:
	glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
	glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);

before glfwInit().

After doing this all worked nicely no problem.

I just find this a bit misleading sinze i am setting a window hint, so i expect this to be related to the window and not to the library initialization. I don't think changing func names might be an option but maybe is it possible to have some runtime checks to prevent this? also any idea why  the context is lost? what i mean is, looks like the current context get lost somehow when i set the context after glfwInit(), and that s why the opengl calls after that fails, although i used glfwMakeContextCurrent. 
Any idea? here the full code of my initalization:

`int major, minor,rev;
	glfwGetVersion(&major,&minor,&rev);
	std::cout<<"Initializing glfw version: "<<major <<"."<<minor<<"."<<rev<<std::endl;
	
	//let s initialize glfw, if that doesn't work let's kill the 
	//program

	glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
	glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    if (!glfwInit())
        exit(EXIT_FAILURE);
    glfwSetErrorCallback(error_callback);
    
    //here we crate a pointer to our window
    GLFWwindow* window;
  
    //createing the window and check if it s all good
    window = glfwCreateWindow((int)settings->m_window_width, 
							  (int)settings->m_window_height, 
							  "Platfoorm 1.0", 
							  nullptr, 
							  nullptr);

	if (!window)
    {
        glfwTerminate();
        exit(EXIT_FAILURE);
    }

    //setting up the context and swap interval
    glfwMakeContextCurrent(window);
    auto r = glewInit () == GLEW_OK;

    glfwSwapInterval((int)settings->m_vsync);`

**Comment by elmindreda** [comment]
The context is re-created because that is the correct and only way to access modern extensions to the WGL API, such as versioned context creation. One needs to create a legacy context to gain access to the newer context creation functions.

By putting the calls to `glfwWindowHint` before `glfwInit` you cause them to be ignored and emit errors, which in turn go unreported as you only set the error callback after calling `glfwInit`. Thus you are requesting a default 1.0 context, which doesn't require versioned context creation and so doesn't trigger context re-creation.

A tool like gDebugger should be able to cope with context re-creation, as it is a very commonly used technique.

**Comment by giordi91** [comment]
Interesting thanks for clarification, oh gdebugger has not a problem with context, my application fails flat out on simple opengl commands like :

glBindBuffer(GL_ARRAY_BUFFER, m_buffer_index);
Where it returns error 1280 which should stand for invalid enum, where it works perfectly fine without setting the context version. 

You mentioned that should default to opengl 1.0 context correct? If so how come I can access shaders , frame buffer etc which should be stuff only used in newer opengl version?

PS mine are not complains but genuine questions trying to figure out why app fails if context is set to  any version

M.

**Comment by elmindreda** [comment]
> You mentioned that should default to opengl 1.0 context correct? If so how come I can access shaders , frame buffer etc which should be stuff only used in newer opengl version?

[This is all described in the documentation](http://www.glfw.org/docs/latest/window.html#window_hints_ctx), which I linked to and quoted earlier as well.

Also, if I recall, running any but the most recent version of GLEW on a core profile context will cause `GL_INVALID_ENUM`, as only recently added support for the core profile.

**Comment by giordi91** [comment]
Thank you for your patience and help, I really appreciate it, mmmm I am going to double check the latest version of glew and try with this. Thank you so much.

**Comment by giordi91** [comment]
Sorry to re-open the issue, but actually found what the problem was it is written here , under the the GLEW bug:

http://www.opengl-tutorial.org/miscellaneous/faq/

It is a glew bug which leads to problem, I started putting glGetError() everywhere , and got up all the way to glewInit(), if the context is set right after glewInit() i get error 1280, although glew does not return any error.

In the end i solved it adding:
glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_COMPAT_PROFILE);

This fixed the problem, I also read that using glewExperimental = true; might help aswell in combination with the above line of code.

Now my last question is do I have any way to make sure that GLFW create successifully a 4.3  context and did not backfault to 3.0?

Again thanks for all the help

**Comment by elmindreda** [comment]
Thank you for the detailed follow-up!

> Now my last question is do I have any way to make sure that GLFW create successifully a 4.3 context and did not backfault to 3.0?

Just request 4.3 via the `GLFW_CONTEXT_VERSION_*` hints in addition to the profile hint above. If 4.3 compatibility profile (or later) isn't supported, creation will fail.

**Comment by giordi91** [comment]
That s all I needed to know! Thanks a lot

M.
