### ISSUE TITLE
Ability to query the maximized state of a window

### ISSUE THREAD

**Issue by theagentd** [glfw/glfw#767]
There are currently functions for creating a window maximized and to maximize an existing window, but there is no way to query if a window is maximized or not. We're having issues with saving the previous window resolution when our game exits and restoring it the next time the game starts, as we currently don't know if the user maximized the window or not.

Also: http://www.glfw.org/docs/latest/window.html does not list the maximization functionality.

**Comment by elmindreda** [comment]
Use the [window attribute](http://www.glfw.org/docs/3.2/window.html#window_attribs).

GLFW 3.2 has not been released yet and so is not the latest release.

**Comment by elmindreda** [comment]
I see I forgot to add an error section for `glfwMaximizeWindow`. Thank you for making me take another look at the documentation!

**Comment by theagentd** [comment]
Ah, seems like I jumped the gun a bit early there. xd Thanks for the info!
