### ISSUE TITLE
Hang on SwapBuffer

### ISSUE THREAD

**Issue by sagaceilo** [glfw/glfw#769]
Hey !

I've just noticed infinite hangs on SwapBuffer when window is not visible. It started happening after merging to newest branch (but I don't want to blame glfw since there was also diver update).

I have Win10 + GTX760m with latest drivers. Please check if this is common issue or its something fishy with my drivers.

Repro:
Create a few windows that share the same context. Usually second window that shares context hangs on creation (there is glClear() and SwapBuffer() in the very end of window creation).

When I commented out glClear from glfw, it started hanging on regular window refresh with SwapBuffer() - this is case when window is closing (I'm hiding windows with valid context to not to recreate them every time I open new window - there is a pool of hidden windows). 
I solved problem with SwapBuffer on window update using glFlush instead last SwapBuffer before window goes invisible.

Once again - that might be driver issue so if anyone could try to reproduce this problem and confirm something, it would be great.

Thanks !

**Comment by intrigus** [comment]
Please create a [sscce](http://sscce.org/).
It makes it far easier to (succesfully) reproduce your issue.

**Comment by elmindreda** [comment]
@sagaceilo What version is your driver?

**Comment by sagaceilo** [comment]
368.22 (23.05.2016)

**Comment by elmindreda** [comment]
This sounds a lot like a driver bug. Unfortunately the GPU in my only Windows 10 machine is not supported by the latest drivers.

**Comment by sagaceilo** [comment]
Prorably diver. I've checked it yesterday and seems to be working again.
