### ISSUE TITLE
glfw.org is down

### ISSUE THREAD

**Issue by Vorgone** [glfw/glfw#771]

**Comment by ja-San** [comment]
Is there another way to download GLFW 3 in the meantime? Or do we wait until it is back up?

**Comment by Playermet** [comment]
Windows binaries can be downloaded here: https://github.com/glfw/glfw/releases

**Comment by jjscloud** [comment]
glfw.org is down

**Comment by sgioia9** [comment]
Still down

**Comment by elmindreda** [comment]
Site is back up. Thanks everyone!
