### ISSUE TITLE
Invalid cursor position 0.000000x0.000000

### ISSUE THREAD

**Issue by fractilegames** [glfw/glfw#773]
After upgrading to version 3.2, GLFW reports error "Invalid cursor position 0.000000x0.000000" and doesn't change cursor position when I try to set cursor position to 0,0:

```
m_MouseX = 0.0;
m_MouseY = 0.0;
glfwSetCursorPos(m_Window, m_MouseX, m_MouseY);
```

If I set cursor position to 1,1 instead, everything works fine.

This happens on Xubuntu 16.04, GLFW 3.2.

**Comment by elmindreda** [comment]
I see I don't know how to C. Will fix.
