### ISSUE TITLE
Contribution guide is incomplete

### ISSUE THREAD

**Issue by tombsar** [glfw/glfw#776]
The contribution guide at ".github/CONTRIBUTING.md" is currently incomplete. In particular it is missing real content for the "Contributing a bug fix" and "Contributing a feature" sections.

It would be useful to know if you welcome PRs for trivial fixes, or if they are too much hassle to review, etc!

**Comment by elmindreda** [comment]
It definitely is incomplete. Now that 3.2 is out, I'll be working on non-code things like this for a while.

To answer your specific question, I absolutely welcome trivial PRs!

**Comment by elmindreda** [comment]
The bug report section should be somewhat usable now. Starting on these now.

**Comment by elmindreda** [comment]
I still have some things to add, but what do you think is still missing?

**Comment by CaffeineViking** [comment]
Personally, I think it looks really good. Also, love the table of contents at the top, really easy to find the information you're looking to make sure everything looks good. Honestly, the only addition I can think of would be a small coding style guide, so a contributor can basically double-check the commit before pull request for compliance. But i don't know if it's really necessary though, one can usually infer from code. Great work with the documentation in general @elmindreda! Keep up the good work!

**Comment by tombsar** [comment]
LGTM! Seconding the request for a code style guide (possibly a separate document?), but otherwise pretty much complete.

Maybe mention somewhere in the "contributing" sections that glfw is written in C90 (or whatever version it uses; I couldn't find it with a quick search), so C++ code will not be accepted?

There are a couple of language things I would suggest (e.g. replacing "i.e." with "e.g." throughout), but those are style not content.

**Comment by elmindreda** [comment]
Thank you.

Coding style will have to be a separate effort.
