### ISSUE TITLE
Window maximization callback

### ISSUE THREAD

**Issue by foofel** [glfw/glfw#778]
glfw now supports to maximize a window but does not have a callback to notify when the window is maximized or has any capabilities to retrieve the maximize status (afaik). it would be nice if that functionality could be added :)

**Comment by elmindreda** [comment]
Darn, someone noticed!

Will look into this for 3.3.

**Comment by luis4glfw** [comment]
@foofel 

> or has any capabilities to retrieve the maximize status (afaik)

You can use 

`glfwGetWindowAttrib(Win, #GLFW_MAXIMIZED)`

for that.

You can add this inside the window_size_callback() and if it returns true you can invoke a window_maximize_callback()  by yourself, passing 1 to signify MAXIMIZED.

You can also track inside the window_size_callback() if the current status of the window is maximized using a static variable, and then if glfwGetWindowAttrib() return false but the static variable is true, you update the static var and invoke the window_maximize_callback() passing 0 to signify RESTORED.

At least that's what I'm currently doing while I wait for the proper implementation. :-)
