### ISSUE TITLE
GLFW_MAXIMIZED hint not working correctly

### ISSUE THREAD

**Issue by dougbinks** [glfw/glfw#780]
On Windows the GLFW_MAXIMIZED hint does not always work - whilst it works reliably when the app is launched from a console or via an IDE double clicking the exe in Explorer results in a normal sized window. However, calling glfwMaximizeWindow(window) after window creation works correctly.

This has been tested on the example boing as well as other code, issue first reported [on the glfw forum](http://discourse.glfw.org/t/glfw-maximized-hint/667/11) by user luis.

**Comment by elmindreda** [comment]
Successfully reproduced on Windows 7.

**Comment by elmindreda** [comment]
So the easiest fix I can think of is to do
```c
ShowWindow(_glfw.win32.helperWindowHandle, SW_HIDE);
```
at init to make subsequent calls ignore the `STARTUPINFO` without workarounds.
