### ISSUE TITLE
XSetInputFocus Error on Non-Reparenting Linux WM

### ISSUE THREAD

**Issue by CaffeineViking** [glfw/glfw#789]
The following minimal program below, with the specified setup, results in the later shown error message.
```C
#include <GLFW/glfw3.h>
int main() {
    glfwInit();
    GLFWwindow* handle = glfwCreateWindow(1280, 720, "bug?",
                                          NULL, NULL);
    glfwDestroyWindow(handle);
    glfwTerminate();
    return 0;
}
```
- **Library version:** `glfw3 3.2-4` (community/glfw-x11) on `gcc 6.1.1-2` (core/gcc)
- **Library version string:** `GLFW version 3.2.0 X11 GLX EGL clock_gettime /dev/js Xf86vm shared`
- **Operating system:**  `Linux 4.6.2-1-ARCH #1 SMP PREEMPT x86_64 GNU/Linux (Arch Linux)`
- **Window manager:** `dwm 6.1-3` (community/dwm) on `xorg-server 1.18.3-2` (extra/xorg-server)
```
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  42 (X_SetInputFocus)
  Serial number of failed request:  132
  Current serial number in output stream:  134
```

Seems similar to what was reported in SFML 2.3, recently: https://github.com/SFML/SFML/issues/991
And also SDL2, some time ago: https://bugzilla.libsdl.org/show_bug.cgi?id=2997
It seems to be regarding the unique behaviour of some non-reparenting WMs.

Both GLFW and SFML seemed to start reporting this same issue on my setup a couple of weeks ago after a system upgrade, I have reproduced this on my other machine which also runs a similar setup. Lastly, I would like to thank for the amazing library, besides this issue, it has been working flawlessly!

**Comment by elmindreda** [comment]
@CaffeineViking Thank you for an incredibly detailed bug report! The bugs you linked to are not only related but point to a possible second bug in GLFW.

**Comment by roboman2444** [comment]
I get this same error using DWM. Someone suggested putting a sleep(1) after glfwInit(), but that does not fix the problem.

**Comment by elmindreda** [comment]
Tentative fix available in the `xsetinputfocus-sync` branch.

**Comment by elmindreda** [comment]
The fix has been merged. Thank you!
