### ISSUE TITLE
Random segfaults on a basic use case of GLFW 3.1.2

### ISSUE THREAD

**Issue by cpcdoy** [glfw/glfw#792]
Random segfaults happening on ubuntu 16.04 using GLFW 3.1.2.
Here is a link to the issue on my repo containing all the details and the code : [issue](https://github.com/cpcdoy/Engine/issues/2)
I can't see where this could come from, as when I remove GLFW function calls, everything works fine

**Comment by elmindreda** [comment]
I don't see any GLFW symbols in that call stack. Please run it again with debug information.

**Comment by cpcdoy** [comment]
Well, the funny thing is that I did run it in debug mode...

**Comment by elmindreda** [comment]
GLFW also doesn't create any threads.

**Comment by cpcdoy** [comment]
Well, I was asking myself if GLFW did create a new thread for input handling or anything else.
Also, I tried my sample code on another computer and it worked without any segfault, so I guess I might have a problem in my current ubuntu system and it did happen coincidentally when using GLFW, which is weird.
So I guess this issue should be closed then.

**Comment by elmindreda** [comment]
I'll run valgrind on it again the next time I'm in Linux and see if I find anything, just in case.

**Comment by cpcdoy** [comment]
Ok, you should do that, of course
