### ISSUE TITLE
Glfw with regal?

### ISSUE THREAD

**Issue by FabbiX** [glfw/glfw#796]
Please forgive my nescience about low level programming if I'll say something stupid, but I'd like to focus your attenption on an android problem and ask you to tell me if in your opinion what I'm saying is possible or it's only a ridiculus idea.
Currently most android devices are able to run a complete ubuntu/archlinux distro but they have got only an ancient opengl support.
On the other hand, this devices have got a perfect opengl es support.
I searched for a solution but replacing opengl seems to be impossible.
But after searching a lot I think I've found an half solution that may works on opengl games made with java lwjgl library: thanks to java dynamicism is possible to make those game work by replacing this library with a version that calls opengl es instead of opengl.
I have contacted lwjgl creator and he told me that is already possible to do it except for GLFW calls.
In particular I found it's possible to compile opengl programs using a library called "regal" to make them using openges so in theory I think its possible to recompile also glfw with this library to make it call opengles
What do you think about?

**Comment by elmindreda** [comment]
This is beyond the current scope of GLFW.
