### ISSUE TITLE
glfwCreateCursor() freezes on Mac.

### ISSUE THREAD

**Issue by theagentd** [glfw/glfw#799]
One of our testers had problems with our game. The game completely froze/deadlocked on glfwCreateCursor() for him and wouldn't continue. He's on OS X El Capitan 10.11.1.

**Comment by elmindreda** [comment]
Are you calling it from the main thread?

**Comment by theagentd** [comment]
Yes, it all works 100% correctly on other computers and has been reproduced with a minimal test case (initializing GLFW, creating a window, creating a cursor (freezes), then setting the cursor for the window. It freezes on glfwCreateCursor(). 100% reproducable.

**Comment by shurcooL** [comment]
> has been reproduced with a minimal test case (initializing GLFW, creating a window, creating a cursor (freezes)

Have you tried `tests/cursor.c` test program? I tried it just now, which calls `glfwCreateCursor` multiple times on startup, and it did not freeze, and the custom (animated) cursor worked fine for me. Tried with GLFW [3.2](https://github.com/glfw/glfw/releases/tag/3.2), OS X 10.11.5 (15F34).

**Comment by elmindreda** [comment]
@theagentd Please post the test case here.

**Comment by theagentd** [comment]
God damn it, sorry, the error is on our end. Using GLFW with Java on Mac requires the VM command -XstartOnFirstThread, which in turn causes all usage of Swing/AWT to break. I didn't realize that the built-in Java image functionality triggers a load for AWT, which in turn freezes. Our test is therefore freezing when creating the cursor image, not on glfwCreateCursor(). It's been a wild goose chase for days here trying to figure out why the hell this was happening. Sorry, I feel so stupid for once again making a premature issue here... >____<

Now I just have to restructure our entire image handling system here, which is gonna take a huge amount of time...

**Comment by intrigus** [comment]
Shouldn't it be enough to run java in headless mode?

**Comment by elmindreda** [comment]
@theagentd Glad you found the solution and thank you for following up!
