### ISSUE TITLE
Are EGL and WGL required at once for Windows build?

### ISSUE THREAD

**Issue by TheVice** [glfw/glfw#802]
Hello.

Not sure that is bug, but I wonder for what reason at commit [ef80bea](https://github.com/glfw/glfw/commit/ef80bea#diff-327ad30f93de55c73174b11638681eb7) provided change at ```src/win32_init.c``` that added dependence for any case (no macros to disable that) for Windows build use EGL subsystem (use files with _egl in names)?

With all respect, user of library.

**Comment by elmindreda** [comment]
EGL is not required unless you explicitly set the `GLFW_CONTEXT_CREATION_API` to use it. EGL is looked for during initialization but will not fail if it cannot be found.

**Comment by TheVice** [comment]
**elmindreda** thank you for your answer.

If that would you give an advice how to support several version of GLFW: before and after that change (or 3.1.2 and 3.2)?

For deal with version before change I use something like this:
```
# glfw
if(UNIX)
  add_definitions(-DGLFW_EXPOSE_NATIVE_X11)
  add_definitions(-DGLFW_EXPOSE_NATIVE_GLX)
else()
  if(EXISTS ${CMAKE_SOURCE_DIR}/third-party/glfw)
    set(glfw_Path ${CMAKE_SOURCE_DIR}/third-party/glfw)
  elseif(DEFINED ENV{GLFW_PATH})
    string(REPLACE "\\" "/" glfw_Path $ENV{GLFW_PATH})
  elseif(DEFINED GLFW_PATH)
    string(REPLACE "\\" "/" glfw_Path ${GLFW_PATH})
  else()
    message(FATAL_ERROR "Could not find glfw library, please check it at https://github.com/glfw/glfw/releases")
  endif()

  file(GLOB_RECURSE GLFW_SRC_FILES ${glfw_Path}/include/*.h ${glfw_Path}/src/*.h ${glfw_Path}/src/*.c)

  list(FILTER GLFW_SRC_FILES EXCLUDE REGEX ${glfw_Path}/src/cocoa_*)
  list(FILTER GLFW_SRC_FILES EXCLUDE REGEX ${glfw_Path}/src/egl_*)
  list(FILTER GLFW_SRC_FILES EXCLUDE REGEX ${glfw_Path}/src/glx_*)
  list(FILTER GLFW_SRC_FILES EXCLUDE REGEX ${glfw_Path}/src/linux_*)
  list(FILTER GLFW_SRC_FILES EXCLUDE REGEX ${glfw_Path}/src/mach_*)
  list(FILTER GLFW_SRC_FILES EXCLUDE REGEX ${glfw_Path}/src/mir_*)
  list(FILTER GLFW_SRC_FILES EXCLUDE REGEX ${glfw_Path}/src/nsgl_*)
  list(FILTER GLFW_SRC_FILES EXCLUDE REGEX ${glfw_Path}/src/posix_*)
  list(FILTER GLFW_SRC_FILES EXCLUDE REGEX ${glfw_Path}/src/wl_*)
  list(FILTER GLFW_SRC_FILES EXCLUDE REGEX ${glfw_Path}/src/x11_*)
  list(FILTER GLFW_SRC_FILES EXCLUDE REGEX ${glfw_Path}/src/xkb_*)

  add_library(glfw ${GLFW_SRC_FILES})

  target_include_directories(glfw SYSTEM PRIVATE ${glfw_Path}/include)
  target_compile_definitions(glfw PRIVATE "_GLFW_USE_OPENGL")
  target_compile_definitions(glfw PRIVATE "_GLFW_WIN32")
  target_compile_definitions(glfw PRIVATE "_GLFW_WGL")
  add_definitions(-DGLFW_EXPOSE_NATIVE_WIN32)
  add_definitions(-DGLFW_EXPOSE_NATIVE_WGL)

  if(MSVC)
    set_target_properties(glfw PROPERTIES COMPILE_FLAGS "/W0")
  else()
    set_target_properties(glfw PROPERTIES COMPILE_FLAGS "-w")
  endif(MSVC)
  list(APPEND REQUIRED_SYS_INCLUDES ${glfw_Path}/include)
endif()
```
So after that change filtering with ```${glfw_Path}/src/egl_*``` should not be used.
It is also possible to use add_subdirectory, but there is GLFW_SOURCE_DIR in the glfw CMakeLists.txt, so use construction below.

Thanks again.

**Comment by elmindreda** [comment]
I'm not sure what you're trying to do above.

If you're already using CMake and want to build GLFW along with your code, then yes, [just use `add_subdirectory`](http://www.glfw.org/docs/latest/build.html#build_link_cmake_source). The GLFW CMake files will take care of any platform-specific setup and file selection.

**Comment by TheVice** [comment]
@elmindreda thanks. That all I need to know about this question.
