### ISSUE TITLE
Wayland character callback registers on key release

### ISSUE THREAD

**Issue by cenomla** [glfw/glfw#804]
The character callback event triggers on both key press and key release, this does not happen when using X11.

**Comment by CaffeineViking** [comment]
Good day @cenomla! Could you please also provide the distribution, desktop environment & window manager, in question? I'll try to reproduce the issues you mentioned, so we can debug what is wrong. Going to try reproducing this on Fedora 24 (GNOME and Mutter) since they can also run on Wayland, but it would be best to have your exact setup, since this could be exclusive to only a subset of setups.

**Comment by linkmauve** [comment]
I could reproduce using tests/events.c on Weston master (1.11.90 revision 0da12b8) on ArchLinux, and the issue comes from src/wl_init.c:297 being executed no matter which action it is.

**Comment by CaffeineViking** [comment]
Alright, I've also tested this on `Fedora 24 Workstation` with `GNOME 3.20` with `Mutter 3.20` using their experimental `gnome-shell --wayland` compositor. Just as @linkmauve, I can reproduce these issues.

**Comment by cenomla** [comment]
I'm using ArchLinux with Gnome 3.20 and a wayland session. This only seems to happen when glfw is using the wayland platform. When I compile glfw using X11 and run it using xwayland this does not happen.

**Comment by linkmauve** [comment]
Hi, sorry for the delay, I just proposed a fix which I only tested on Weston against tests/events, please check against your compositor and application.

**Comment by jadahl** [comment]
Looks fine to me. It'd read clearer if the code that does _glfwInputChar() in its own function and then do if (action == GLFW_PRESS) input_char(...);

**Comment by cenomla** [comment]
I can confirm that this fix works.

**Comment by linkmauve** [comment]
jadahl, this is a good suggestion, it makes the code more obvious in what it does, I force-pushed this.

**Comment by jadahl** [comment]
Looks good to me.
