### ISSUE TITLE
A few more standard icons

### ISSUE THREAD

**Issue by PlutoniumHeart** [glfw/glfw#811]
I am currently using a glfwCreateStandardCursor(), but realized that there are only 6 standard cursor shapes. In my particular needs I would like to use some resizing icons for the 4 corners, but they don't exists.

I looked at the source code, trying to add those and submit a pull request, but it seams this function is also OS dependent, and I am currently looking at X11 version of this functions. This makes submitting pull requests related to this a little difficult for me, because let's face it, I am not going to touch Windows in any way... :D

So I am wondering if there is any plan by the GLFW team to expand the support of standard icons.

**Comment by tombsar** [comment]
See #427 for discussion on this issue.
