### ISSUE TITLE
Failed to create window in core profile mode

### ISSUE THREAD

**Issue by leo150** [glfw/glfw#812]
System: OS X 10.11.5; Intel HD Graphics 3000 384 MB
GLFW: 3.1.2 (from brew repo)
I'm trying to run OpenGL application. As described [here](https://developer.apple.com/opengl/capabilities/index.html) core's OpenGL Version for my OS and video card is 3.3. My code: 

```
glfwInit();
glfwWindowHint( GLFW_CONTEXT_VERSION_MAJOR, 3 );
glfwWindowHint( GLFW_CONTEXT_VERSION_MINOR, 3 );
glfwWindowHint( GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE );

if( !glfwCreateWindow( 600, 400, "Window", nullptr, nullptr ) ) {
	printf( "error: Failed to create window\n" );
	exit( 1 );
}
```

I get fail after if statement. What is wrong?

**Comment by tombsar** [comment]
You should try setting an error callback; glfw will usually report what went wrong.

**Comment by MrVallentin** [comment]
Also, did you try checking if `glfwInit()` returns `GLFW_FALSE` ?

**Comment by shurcooL** [comment]
You forgot to set the forward compatible bit to true, which is also necessary.

```
glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GLFW_TRUE)
```

As others have said, error checking is also important to do.

See this entry in the FAQ:

[4.1 - How do I create an OpenGL 3.0+ context?](http://www.glfw.org/faq.html#how-do-i-create-an-opengl-30-context)

**Comment by leo150** [comment]
@shurcooL thanks, you're right
