### ISSUE TITLE
Can't take screenshots in fullscreen on windows 7 and 10

### ISSUE THREAD

**Issue by m4ttbush** [glfw/glfw#814]
Using printscreen or alt+printscreen when in fullscreen just captures the desktop on windows 10 (amd gpu) and a black screen on windows 7 (nvidia gpu). Seems to work fine in windows 8 (nvidia).

In windows 10 if fullscreen was toggled from windowed it will show the desktop with what was last visible when windowed in the top left corner of the screenshot but with the window undecorated.

Tried on the latest build from git (3.2.1) but it's been happening for some time on older versions of glfw.

Initialise code looks like this:

``` c++
GLFWmonitor *monitor = glfwGetPrimaryMonitor();
const GLFWvidmode* mode = glfwGetVideoMode(monitor);
glfwWindowHint(GLFW_RED_BITS, mode->redBits);
glfwWindowHint(GLFW_GREEN_BITS, mode->greenBits);
glfwWindowHint(GLFW_BLUE_BITS, mode->blueBits);
glfwWindowHint(GLFW_REFRESH_RATE, mode->refreshRate);
if( fullscreen )
{
    _window = glfwCreateWindow(mode->width, mode->height, "Devil Daggers", monitor, NULL);
}
else
{
    _window = glfwCreateWindow(mode->width / 2, mode->height /2 , "Devil Daggers", NULL, NULL);
}
```

And toggle code uses glfwSetWindowMonitor

``` c++
glfwSetWindowMonitor( _window, m, 0,0, vm->width, vm->height, vm->refreshRate );
...
glfwSetWindowMonitor( _window, NULL, vm->width / 4, vm->height / 4, vm->width / 2, vm->height / 2, vm->refreshRate );
```

Thanks

**Comment by elmindreda** [comment]
The print screen function in Windows does not involve GLFW. When an OpenGL window is made full screen on Windows, the OS detects this and switches to page flipping (whether we want it to or not), allowing the application to draw directly to the screen but bypassing the GDI. This means the rendered output isn't where the print screen function expects.

**Comment by m4ttbush** [comment]
Thanks Camilla, that makes sense. I thought there might be some configuration I had wrong. If page flipping reduces latency I'd prefer that over being able to use printscreen anyway.
