### ISSUE TITLE
glfwInit() sets errno to EAGAIN after successful call

### ISSUE THREAD

**Issue by wacossusca34** [glfw/glfw#824]
On Linux, `glfwInit()` can set `errno` to `EAGAIN`. While easily worked around (`errno = 0;` before calling a function that can set errno), this probably isn't intended behaviour. On my system, this sample code will show this behaviour:

    printf("errno before call: %d\n", errno);
    glfwInit();
    printf("errno after call: %d\n", errno);

Note GLFW otherwise performs as intended, and if you use `glfwSetErrorCallback()` to set an error callback in the sample code, it is not called.

Occurs with GLFW version 3.2-4, using Arch Linux (x86_64, kernel 4.6.1-2-ARCH), using `nvidia` drivers (364.16). I am using a rather obscure window manager for X (EXWM), if that could be related.

**Comment by jcowgill** [comment]
From errno(3):

 > Its value is significant only when whe return value of the call indicated an error (i.e., -1 from most system calls; -1 or NULL from most library functions); a function that succeeds is allowed to change errno.

**Comment by wacossusca34** [comment]
@jcowgill most code I've worked with (barring libc) seemed to take care to not set errno when there wasn't an error. Oh well, guess it's not a bug.

**Comment by elmindreda** [comment]
GLFW doesn't set errno during init, but it calls a lot of other code.
