### ISSUE TITLE
Fail to run with Bumblebee, EGL will not initialize

### ISSUE THREAD

**Issue by haikarainen** [glfw/glfw#825]
Check this issue https://github.com/haikarainen/kit/issues/5 (ignore the first output, running it without bumblebee works fine)

I initialize GLFW using a singleton class (Check [declaration](https://github.com/haikarainen/kit/blob/master/include/Kit/OpenGL.hpp#L12) & [definition](https://github.com/haikarainen/kit/blob/master/src/Kit/OpenGL.cpp)), and then instantiate this class as a member in [Window.hpp](https://github.com/haikarainen/kit/blob/master/include/Kit/Window.hpp#L323).

Then I create a Window using GLFW in [Window.cpp on line 44](https://github.com/haikarainen/kit/blob/master/src/Kit/Window.cpp#L44).

According to the output that  kylenoteboom posted in that issue, the GLFW initialization is what is failing. Here's a copy of the relevant output:

```
Error: src/Kit/OpenGL.cpp at 132 in void kit::glfwError(int, const char*): GLFW error 65542: EGL: Failed to initialize EGL: EGL is not or could not be initialized
terminate called after throwing an instance of 'kit::Exception'
[1]    9208 abort (core dumped)  primusrun ./kit-material-designer
```

Currently I have no idea what the source for the error is, but any help in tracking down this issue is highly appreciated. I suspect bumblebee or user setup, but I can't exclude either GLFW or Kit just yet.

**Comment by haikarainen** [comment]
Kit has been excluded, user can now run through bumblebee!

Closing.

**Comment by elmindreda** [comment]
That's an interesting project!

This issue was partly fixed by d5e00e6b0fe1e64b4bb3b2cbe41018dad14f4e1f, but will still reoccur if you mix context creation APIs in a single process.

**Comment by haikarainen** [comment]
Thank you!

I see, should simple hinting about the context creation API make sure that the issue is not  going to happen? That is how I do it now. By build defines, so no built executable can mix APIs in different windows for example.

**Comment by elmindreda** [comment]
It's fine either to leave it at the default (i.e. native) or set it to any supported value, just as long as you don't create contexts through both APIs. There is no `GLFW_ANY_CONTEXT_API`, so there's usually no need to set it at all.

In fact, unless you want GLES on AMD, there is very little reason to use EGL on desktop.

**Comment by haikarainen** [comment]
I see, thanks for clearing this up! Very appreciated!  :+1:
