### ISSUE TITLE
glfwGetPhysicalDevicePresentationSupport needs additional surface parameter to have complete check for presentation support

### ISSUE THREAD

**Issue by tim37021** [glfw/glfw#828]
According to spec,
_To determine whether a queue family of a physical device supports presentation to a **given surface**, we must call vkGetPhysicalDeviceSurfaceSupportKHR._
plus,
to create a swapchain, _surface(a parameter in VkSwapchainCreateInfo) must be a surface that is supported by the device as determined using vkGetPhysicalDeviceSurfaceSupportKHR_.

Validation layer will report error if we do not call vkGetPhysicalDeviceSurfaceSupportKHR before vkCreateSwapchain. I must manually add vkGetPhysicalDeviceSurfaceSupportKHR even I've called glfwGetPhysicalDevicePresentationSupport.
I would like to issue pull request. but I need to add additional surface parameter to the function, which will change the interface....

Please refer to this.
https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/818

**Comment by elmindreda** [comment]
`glfwGetPhysicalDevicePresentationSupport` is merely an abstraction of the corresponding platform-specific functions `vkGetPhysicalDeviceWin32PresentationSupportKHR`, `vkGetPhysicalDeviceXlibPresentationSupportKHR`, `vkGetPhysicalDeviceWaylandPresentationSupportKHR` and `vkGetPhysicalDeviceMirPresentationSupportKHR` and is meant for use before surface creation.

**Comment by tim37021** [comment]
I see!
I have some couple of simple vulkan apps that use glfw.
I wish to make them as simple as I can only to show how to correctly use glfw with vulkan (No rendering).
Will you accept the pull request?
still need some time to finish them

**Comment by elmindreda** [comment]
I will not accept it. It will change the ABI.
