### ISSUE TITLE
LWJGL glfwCreateWindow() the share parameter not working

### ISSUE THREAD

**Issue by audioXD** [glfw/glfw#831]
LWJGL glfwCreateWindow() the share parameter not working

**Comment by elmindreda** [comment]
In what way is it not working?

**Comment by audioXD** [comment]
Its not sharing the VBOs VAOs and textures

**Comment by sriharshachilakapati** [comment]
As far as I know, shared contexts cannot share VAOs and FBOs, because those are states in OpenGL. But textures should be shared.

**Comment by elmindreda** [comment]
Yes, what @sriharshachilakapati said. If textures or VBOs weren't shared then that may be a bug in LWJGL, a driver issue or an incorrect use of ´glfwCreateWindow`. To verify object sharing on only GLFW and the driver involved, run the `sharing` test that is built along with the GLFW library.

**Comment by elmindreda** [comment]
Has this been resolved?
