### ISSUE TITLE
how to make core profile context on OS X

### ISSUE THREAD

**Issue by godshow** [glfw/glfw#832]
```
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
//    glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
```

without GLFW_OPENGL_FORWARD_COMPAT , cannot create window.

**Comment by shurcooL** [comment]
You need to set GLFW_OPENGL_FORWARD_COMPAT to true.

See https://github.com/glfw/glfw/issues/812#issuecomment-234724790:

> ```C
> glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
> ```
> 
> See this entry in the FAQ:
> 
> [4.1 - How do I create an OpenGL 3.0+ context?](http://www.glfw.org/faq.html#how-do-i-create-an-opengl-30-context)
