### ISSUE TITLE
Crash on 10.12 Sierra

### ISSUE THREAD

**Issue by ingconti** [glfw/glfw#840]
I am using the call:

``` objc
io_service_t IOServicePortFromCGDisplayID(CGDirectDisplayID displayID)
```

but on mac 15 retina it crashes as serialNumberRef is null.

``` objc
serialNumberRef = CFDictionaryGetValue(info, CFSTR(kDisplaySerialNumber));
```

so in next call:

``` objc
success &= CFNumberGetValue(serialNumberRef, kCFNumberCFIndexType, &serialNumber);
```

it crashes.

I got:

```
(lldb) p vendorID
(CFIndex) $1 = 1552
(lldb) p productID
(CFIndex) $2 = 40985
```

before crashing.

displayID is:

```
(lldb) p displayID
(CGDirectDisplayID) $4 = 69731904
```

available to make all tests needed.
thanks in advance,

**Comment by elmindreda** [comment]
I cannot reproduce this but it's not surprising. Related to #192.

**Comment by elmindreda** [comment]
GLFW doesn't have the `IOServicePortFromCGDisplayID` function, which was part of the #508 and #511 PRs. The master branch (which will become 3.3) does contain a similar fix, however, so if you're using a fork for that reason you can safely use this repo now.
