### ISSUE TITLE
_glfwInitEGL crashes on Windows 10 x64, GLFW version 3.2

### ISSUE THREAD

**Issue by glClear** [glfw/glfw#841]
Within _glfwPlatformInit, GLFW does a call to _glfwInitWGL and then to _glfwInitEGL; EGL is not present on my machine, therefore it should actually immediately return because "handle" is always NULL, but somehow "handle" still gets a value and the application finally crashes when trying to call a NULL-function-pointer [line:  "_glfw.egl.display = eglGetDisplay(_GLFW_EGL_NATIVE_DISPLAY)" -> _glfw.egl.GetDisplay is NULL].

I have no idea why _glfw_dl_open succeeds here (I don't have EGL libs) but you could at least implement checks against NULL after every _glfwGetProcAddress call in _glfwInitEGL.

**Comment by tombsar** [comment]
This should have been fixed already in current master. Are you able to compile from source? Otherwise wait until the next release (hopefully within a couple of weeks).

**Comment by glClear** [comment]
I do compile from source, but I used the package provided directly on the GLFW website. Anyways, it works perfectly now, thanks for maintaining this library!
