### ISSUE TITLE
Unable to build with MSYS2

### ISSUE THREAD

**Issue by Sogomn** [glfw/glfw#843]
It seems like when building, CMake tries to find the X11 dependencies, althought I'm on Windows.
No toolchain configuration seems to work.
Using MSYS2 on Windows 7.
CMake: 3.5.2
GCC: 5.3.0
All of them added to the system path.
Also I wonder why it uses CC.

```
-- The C compiler identification is GNU 5.3.0
-- Check for working C compiler: /usr/bin/cc.exe
-- Check for working C compiler: /usr/bin/cc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Could NOT find Vulkan (missing:  VULKAN_LIBRARY VULKAN_INCLUDE_DIR)
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
-- Using X11 for window creation
CMake Error at /usr/share/cmake-3.5.2/Modules/FindX11.cmake:439 (message):
  Could not find X11
Call Stack (most recent call first):
  CMakeLists.txt:212 (find_package)


-- Configuring incomplete, errors occurred!
See also "/d/Downloads/glfw-build/CMakeFiles/CMakeOutput.log".
```

Is there a way to fix this or do I have to switch to MinGW?

**Comment by bit2shift** [comment]
How about you telling us the command line you used?
By default, you'd do this to build just GLFW:

    cd glfw
    cmake -G "Unix Makefiles" -DBUILD_SHARED_LIBS=ON -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF .
    make

**Comment by Sogomn** [comment]
I used MSYS2 Bash.
Switched to Linux now so unfortunately I can't check if the problem still occurs.

**Comment by FlandreScarlet** [comment]
This works fine:
```
cd glfw
cmake -G "MSYS Makefiles" -DBUILD_SHARED_LIBS=ON -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF .
make
```

CMake thinks it's on Linux when used in MSYS, so you have to pass it `-G "MSYS Makefiles"`

**Comment by elmindreda** [comment]
@Sogomn Did you specify the toolchain file on the command line as per the [compilation guide](http://www.glfw.org/docs/latest/compile_guide.html#compile_deps_mingw_cross)? What is the full command you used?

**Comment by Sogomn** [comment]
I'm sorry, I can't remember.

**Comment by elmindreda** [comment]
@Sogomn No worries. Did you get it to work this or some other way in the end?

**Comment by Sogomn** [comment]
Yeah, I installed Arch Linux. :joy:

**Comment by bit2shift** [comment]
For future reference, [this will build the static lib](https://github.com/bit2shift/r3dVoxel/blob/master/makefile#L37) in both Windows (MSYS2) and Unix, assuming you have all of GLFW's dependencies installed.

PS: *MSYS* is obsolete, switch to MSYS2.

**Comment by TheSecret3003** [comment]
Still unable to install using cmake. Here is the result

-- Could NOT find Vulkan (missing:  VULKAN_LIBRARY VULKAN_INCLUDE_DIR) 
-- Using X11 for window creation
CMake Error at /usr/share/cmake-3.5/Modules/FindX11.cmake:439 (message):
  Could not find X11
Call Stack (most recent call first):
  CMakeLists.txt:219 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/secret/Documents/OpenGL/glfw/CMakeFiles/CMakeOutput.log".
See also "/home/secret/Documents/OpenGL/glfw/CMakeFiles/CMakeError.log".

Is anyone had passed this problem?

**Comment by bit2shift** [comment]
@TheSecret3003 install `xorg-dev`, it says you don't have it (`Could not find X11`).
