### ISSUE TITLE
Support hidpi on Windows

### ISSUE THREAD

**Issue by sgraham** [glfw/glfw#845]
Currently, glfwGetWindowSize() and glfwGetFramebufferSize() always seem to report the same thing on Windows.

On Mac (with _GLFW_USE_RETINA), glfwGetWindowSize() \* current_dpi == glfwGetFramebufferSize().

I have made sure that my application is DPI aware (via manifest), and GetDpiForMonitor() returns values greater than 96.

It'd be nice if Windows behaved the same as Mac. (Or did I miss that there's a different way to do this on Windows?)

**Comment by elmindreda** [comment]
Window size and framebuffer size will continue to be equal on Windows (and X11) but there will be a `glfwGetWindowContentScale` in 3.3 that will work as expected on all platforms. On modern Windows it will use per-monitor effective DPI.

**Comment by AndrewBelt** [comment]
Great! I just want to clarify the differences between each of these. Is the following correct?

- `glfwGetWindowContentScale` is the scaling factor you should be scaling graphics. Note that it may return non-integers, so I'm `roundf()`ing the result for my purposes.

- `glfwGetFramebufferSize / glfwGetWindowSize` is the same as `glfwGetWindowContentScale` on MacOS, but always 1.f on Linux X11 and Windows

- Therefore, if you scale by `glfwGetWindowContentScale` as I recommend above, you should rescale all GLFW mouse positions and window sizes by `glfwGetWindowContentScale / (glfwGetFramebufferSize / glfwGetWindowSize)` so they now match your OpenGL context's scaling.

**Comment by elmindreda** [comment]
> `glfwGetWindowContentScale` is the scaling factor you should be scaling graphics. Note that it may return non-integers, so I'm `roundf()`ing the result for my purposes so that GUI elements look a bit cleaner, being pixel-perfect.

Sounds right.

> `glfwGetFramebufferSize / glfwGetWindowSize` is the same as `glfwGetWindowContentScale` on MacOS,

Currently true, but may change at some point.

> but always 1.f on Linux X11 and Windows

No, the content scale is not the ratio of pixels and screen coordinates; it just happens to line up that way on macOS. Rather the content scale is the ratio of the current effective DPI and the platform's default DPI. This Windows laptop has a correctly configured 100 DPI monitor and the default on Windows is 96 DPI, so the monitor scale is 100 / 96 = 1.041667.

> Therefore, if you scale by `glfwGetWindowContentScale` as I recommend above, you should rescale all GLFW mouse positions and window sizes by `glfwGetWindowContentScale / (glfwGetFramebufferSize / glfwGetWindowSize)` so they now match your OpenGL context's scaling.

If your UI is working in units of `pixels * content_scale` then yes, you should scale screen coordinates (cursor position, window size, etc.) by `framebuffer_size / (window_size * content_scale)` to move them into your UI coordinate space.

**Comment by AndrewBelt** [comment]
Thank you for the corrections! Glad to know I'm using them correctly.
