### ISSUE TITLE
So many unnecessary dependencies in GLFW 3

### ISSUE THREAD

**Issue by PDirSG** [glfw/glfw#846]
I need GLFW for only Windowing, Vulkan and input handling. But with GLFW 3, there is so many unnecessary dependencies. They are making Visual Pollution. 

When i pass this command on terminal:

`pkg-config --cflags --static --libs glfw3`

this gives a big list:

`-I/usr/local/include -L/usr/local/lib -lglfw3 -lrt -lm -ldl -lXrandr -lXinerama -lXxf86vm -lXext -lXcursor -lXrender -lXfixes -lX11 -lpthread -lxcb -lXau -lXdmcp`

I mean, most of them are unnecessary. Can somebody solve this problem?

**Comment by elmindreda** [comment]
Which are the unnecessary ones?

**Comment by BestThingsInLiveFree** [comment]
pthread (i do not even need threads), lm (i will not use standart C math library) and many other.

**Comment by elmindreda** [comment]
GLFW uses libm and pthreads for gamma ramp calculations and TLS. It also uses libdl, librt, libXrandr, libXinerama, libXxf86vm, libXcursor and libX11. The remaining ones are pulled in via the X11 pkg-config files due to your use of the `--static` flag.

**Comment by BestThingsInLiveFree** [comment]
In declaration of GLFW writes 'light weight', if we have to link it
statically it is not 'light weight'. I'm using C instead of C++ because of
C executables are more smaller. Is possible to link it dynamically?

**Comment by BestThingsInLiveFree** [comment]
And not 'portable' with all.

**Comment by elmindreda** [comment]
In what way is linking statically less lightweight?

**Comment by BestThingsInLiveFree** [comment]
Well, I do not want to my application size more than 200 KB *without doing
nothing*. Especially for developers working for embedded devices, size of
the program is critical. I know GLFW is not supported embedded devices *yet*
.

And SDL2 and GLFW like libraries are compatibility* layer*s, if we link
them statically, there
no meaning to use them.

As a sample: If you write a program with SDL2 and link it dynamically on
Ubuntu 14.04 using X display manager for x86_64 architecture, you can run
the program on Ubuntu 14.04 using another display manager with x86_64
architecture.

But if you link it statically, you can't.

**Comment by elmindreda** [comment]
> As a sample: If you write a program with SDL2 and link it dynamically on Ubuntu 14.04 using X display manager for x86_64 architecture, you can run the program on Ubuntu 14.04 using another display manager with x86_64 architecture.

SDL2 supports all three window systems in the same binary, so it would make no difference in this regard whether it was statically or dynamically linked. GLFW will work the same way in 3.4 or 4.0.

If you want to link GLFW dynamically then do. If you built it yourself, see the `BUILD_SHARED_LIBS` CMake option. Otherwise see the listing for your distro package.

**Comment by BestThingsInLiveFree** [comment]
Thanks.
