### ISSUE TITLE
HIDPI support on Linux. 

### ISSUE THREAD

**Issue by serch037** [glfw/glfw#847]
Running glfwGetFramebufferSize and glfwSetWindowSize return the same values. I have also tried using glViewport to manually set the framebuffer resolution but it doesn't appear to do anything.

**Comment by tombsar** [comment]
`glViewport` doesn't change the resolution of the framebuffer; it just changes the coordinate transformation between NDC and window coordinates.

**Comment by serch037** [comment]
Apparently my problem was not directly with GLFW, but with OpenFrameworks.
