### ISSUE TITLE
Command-tabbing issues with fullscreen windows

### ISSUE THREAD

**Issue by IntellectualKitty** [glfw/glfw#848]
I used the code directly from the HTML guide for creating "windowed full screen" windows to modify the Boing demo application.  Specifically, I replaced this line:
```c
   window = glfwCreateWindow( 400, 400, "Boing (classic Amiga demo)", NULL, NULL );
```
with the following code:
```c
   GLFWmonitor* monitor = glfwGetPrimaryMonitor();
   const GLFWvidmode* mode = glfwGetVideoMode(monitor);
   glfwWindowHint(GLFW_RED_BITS, mode->redBits);
   glfwWindowHint(GLFW_GREEN_BITS, mode->greenBits);
   glfwWindowHint(GLFW_BLUE_BITS, mode->blueBits);
   glfwWindowHint(GLFW_REFRESH_RATE, mode->refreshRate);
   window = glfwCreateWindow( mode->width, mode->height, "Boing (classic Amiga demo)", monitor, NULL );
```
The fullscreen window is created correctly and initially works fine, but problems ensue when command-tabbing from and then back to the Boing application.  First, when command-tabbing from Boing to another application, the fullscreen window is iconified rather than simply hidden.  Second, a number of issues occur when command-tabbing back to the Boing application: (1) the fullscreen window remains iconified and does not reappear; (2) when you click on the Boing application in the Dock, the fullscreen window is de-iconified, but then is immediately hidden (and remains hidden) leaving you with only the menu bar; (3) if you then click anywhere but the menu bar, the fullscreen window re-appears, but then is immediately iconified.

This, at least, is the general behavior.  However, if you repeatedly command-tab back to the Boing application (or try to activate it by clicking on its icon in the Dock), the fullscreen window will sometimes no longer re-appear at all.

Desirable behavior would be that the fullscreen window is simply hidden and then restored (rather than being iconified and de-iconified) when command-tabbing from and to the Boing application.  Also, it would be desirable to be able to disable command-tabbing when in fullscreen mode, particularly per a user's request.

This test was performed with the latest GLFW code (downloaded directly from GitHub on August 26, 2016) on a late 2011 MacBook Pro running OS X 10.11.6 and built with Xcode 7.3.1.

**Comment by trustin** [comment]
Having the same issue. Probably related with #503?

**Comment by elmindreda** [comment]
Full screen window restoration should work as expected now. Spaces-unaware full screen with minimization is of course horrible even when it works and is what I was really looking into improving upon when I found this fix.
