### ISSUE TITLE
How _glfwPlatformGetRequiredInstanceExtensions function works?

### ISSUE THREAD

**Issue by BestThingsInLiveFree** [glfw/glfw#849]
Hello. I want to make an implementation of this function for X11 display manager. Portability is not a matter for me. But when i search the source code of GLFW, i can't find the declaration of this function. I'm only need this function for X11. How this function works?

**Comment by tombsar** [comment]
Are you looking for this? https://github.com/glfw/glfw/blob/3d62c9ed9d1ba4c6c285248d839c17bc5c5028f7/src/x11_window.c#L2306

**Comment by BestThingsInLiveFree** [comment]
Yes, it is. Thanks
