### ISSUE TITLE
Cursor icon and transparency problem

### ISSUE THREAD

**Issue by PDirSG** [glfw/glfw#860]
Hi there. I load my icon with SOIL and set it:

```
    GLFWimage cursorImage; cursorImage.pixels =
            SOIL_load_image("data/Cursor.PNG", &cursorImage.width, &cursorImage.height, 0, SOIL_LOAD_RGBA);

    GLFWcursor *cursor = glfwCreateCursor(&cursorImage, 0, 0); SOIL_free_image_data(cursorImage.pixels);
    glfwSetCursor(window, cursor);
```

For more soft borders, i add some transparency to border pixels. But when i open the application, there was an different cursor but the alpha channel was not cared. Every pixel was in the same color. What i need to do? Is it a bug?

GLFW 3.1

**Comment by tombsar** [comment]
What OS are you using? If Linux, what desktop environment and graphics stack?
