### ISSUE TITLE
GLFW_DECORATED should use WS_MINIMIZEBOX

### ISSUE THREAD

**Issue by xanather** [glfw/glfw#861]
On Win32 when creating a GLFW window with no border (GLFW_DECORATE == GLFW_FALSE) I noticed that WS_MINIMIZEBOX is not applied to the style.

WS_MINIMIZEBOX is useful; it allows the user to minimize the borderless window by clicking on the window in the taskbar.

**Comment by elmindreda** [comment]
Thank you!
