### ISSUE TITLE
glfw using X11/extensions/XInput.h

### ISSUE THREAD

**Issue by rkanavath** [glfw/glfw#865]
Is it possible to use X11/extensions/XInput.h instead of X11/extensions/XInput2.h?

I have centos5 and it has XInput.h no XInput2.h. If there is no way to use XInput2.h . What will be the sideffects if i disable xi option with set(_GLFW_HAS_XINPUT FALSE) ?

**Comment by elmindreda** [comment]
This file has not been used by GLFW since 3.1.2. The current version is 3.2.1. Consider updating to a newer version. If you can't, disabling `_GLFW_HAS_XINPUT` will only lose you sub-pixel cursor motion.
