### ISSUE TITLE
Add a debug CMake postfix 

### ISSUE THREAD

**Issue by TrueBers** [glfw/glfw#875]
It should be nice to add a debug postfix since install target overrides previously built library:
1. Build a release target on Windows
2. Install it to `${CMAKE_INSTALL_PREFIX}/lib/glfw3.lib`
3. Build a debug one
4. Install it to the same path so it overrides a release lib with a debug one

Should be:
4. Install debug build to `${CMAKE_INSTALL_PREFIX}/lib/glfw3d.lib`

Suggestion: add a [CMAKE_DEBUG_POSTFIX variable](https://cmake.org/cmake/help/latest/variable/CMAKE_DEBUG_POSTFIX.html) or [DEBUG_POSTFIX property](https://cmake.org/cmake/help/latest/prop_tgt/DEBUG_POSTFIX.html) with the value of _"d"_

**Comment by Delwin9999** [comment]
To add to this it's searching for the vulkan library by exact name.  If you're using a vulkan library with a debug postfix or alternate name it will fail to initialize Vulkan with some fairly cryptic error messages.  Passing that flag all the way through, or better have a configuration that can override the name it's looking for, would be great.

**Comment by elmindreda** [comment]
There is no need to add this to the GLFW CMake file to have it work and I don't want a debug postfix as default.

To get a debug postfix with command-line CMake add `-DCMAKE_BUILD_TYPE=Debug -DCMAKE_DEBUG_POSTFIX=d`, or in the CMake GUI click __Add Entry__ and add `CMAKE_DEBUG_POSTFIX` as a string.
