### ISSUE TITLE
Vulkan cmake name collision

### ISSUE THREAD

**Issue by Delwin9999** [glfw/glfw#884]
I have glfw embedded in a much larger project and I compile the vulkan loader from source earlier in the build process.  Unfortunately there's a name collision between the  vulkan test in glfw and the vulkan loader when compiling both using cmake.

CMake Error at Build/glfw-src/tests/CMakeLists.txt:49 (add_executable):
  add_executable cannot create target "vulkan" because another target with
  the same name already exists.  The existing target is a shared library
  created in source directory
  "/home/user/workspace/Vulkan/project/Build/VLAVL-src/loader".  See
  documentation for policy CMP0002 for more details.

CMake Error at Build/glfw-src/tests/CMakeLists.txt:52 (target_link_libraries):
  Attempt to add link library
  "/home/user/workspace/Vulkan/project/Build/VLAVL-build/loader/libVulkan.so"
  to target "vulkan" which is not built in this directory.

The specific collision is with https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/loader/CMakeLists.txt line 85

I believe that this is mainly due to cmake's habit of putting all targets in global scope.

**Comment by elmindreda** [comment]
Do you need to build the GLFW tests as part of your build process? Otherwise you can disable them (and the examples) with [these CMake options](http://www.glfw.org/docs/3.2/compile_guide.html#compile_options_shared), as long as you set them before `add_subdirectory(path/to/glfw)`.

**Comment by Delwin9999** [comment]
That seems to have fixed the issue.  Thank you!

**Comment by elmindreda** [comment]
Great! Your build should be faster now, too.
