### ISSUE TITLE
Joystick events not delivered without event polling

### ISSUE THREAD

**Issue by spaghetti-** [glfw/glfw#887]
Currently facing this issue on OS X, glfw 3.2

Joystick: Logitech Extreme 3D

Did not test on Linux yet.

to reproduce:
- plug in a joystick
- poll for glfwJoystickPresent() and it will return correctly when the device has been in from the start
- pull out the joystick while still polling
- glfwJoystickPresent() is now wrong

**Comment by elmindreda** [comment]
Are you polling events in the meantime?

**Comment by spaghetti-** [comment]
Polling by calling `glfwGetJoystickAxes` at 10hz.

**Comment by elmindreda** [comment]
But you haven't created any windows?

**Comment by elmindreda** [comment]
I'm asking because on macOS, joystick connection events are emitted by the main event loop. If you need them without any windows, I'll look into it.

**Comment by spaghetti-** [comment]
I have not, its actually a headless application. I have called `glfwInit()` but thats about it. I can upload a testcase if it helps.

**Comment by elmindreda** [comment]
This is the flip side of #932 and I think the only sane solution is to require calls to `glfwPollEvents` for joystick event delivery even for headless applications. This will not affect performance and will make things more consistent on both sides of the API.
