### ISSUE TITLE
Joystick hat is not a set of buttons

### ISSUE THREAD

**Issue by yerejm** [glfw/glfw#889]
The handling of the joystick hat seems flawed.

Currently the 9 possible states are treated as distinct buttons, but this is problematic because the diagonal directions are detected as two buttons. For example, UP and UPLEFT cannot be distinguished simply via the API. The callback model proposed by #856 would pass through UPLEFT as two distinct button pushes for UP and LEFT. This may not be desirable.

If the caller is responsible for working out the hat state, then there isn't a simple way to distinguish between a joystick with a hat and a joystick without a hat when the button count matches. For example, a joystick with a primary and secondary trigger and a hat would show up as 6 buttons as would a joystick with a primary and secondary trigger and 4 extra buttons and no hat. I suppose the last four buttons could be tested with user input to determine this, but it seems drastic to ask the user for help when GLFW can figure it out already.

Also, the code for hat processing seems to indicate that multiple hats are possible.
Perhaps retrieved using `const int *glfwGetJoystickHats(int joystick_id, int *count)`?

So is it possible for the hat to not be treated as extra buttons but as its own thing? For example, `int glfwGetJoystickHat(int joystick_id, int hat_id)` returning the direction where direction is 0 for the neutral (centered) position and 1, 2, 3, etc for each of the possible directions (clockwise). A reason to not use the `GLFW_PRESSED`/`GLFW_RELEASED` style would be that it is impossible for the hat to be in more than one direction. In other words, the hat could be seen as being a single button, not a set of individual buttons.

A possible callback model API would take a function signature `void(*fn)(int joystick_id, int hat_id, int direction)`.

**Comment by IntellectualKitty** [comment]
I've provided code to resolve this issue (pull request #906).

**Comment by elmindreda** [comment]
This will be included in 3.3 using the public interface provided by @IntellectualKitty and @yerejm but with a slightly different implementation due to #900.

**Comment by elmindreda** [comment]
Joystick hat support has been added with 368dec7ac712fc4a4a2f77aaec68b62fb8f98749 and 798d7c6d68bb17480fcda6074b1d5a946a05ed52, slightly messier than it should be due to backward compatibility.

**Comment by IntellectualKitty** [comment]
@elmindreda thanks for adding this.  Again I apologize for the headaches it caused because I closed the original pull request.

**Comment by elmindreda** [comment]
@IntellectualKitty No worries and thank you for an elegant patch!
