### ISSUE TITLE
No way to get/set the primary and secondary selection

### ISSUE THREAD

**Issue by kovidgoyal** [glfw/glfw#894]
As per the docs here: http://www.glfw.org/docs/latest/input_guide.html#clipboard there does not seem to be any way to get/set the primary and secondary selections from the X11 clipboard. The X11 clipboard maintains two selections, unlike most other platform clipboards that maintain only one.

This can be worked around by using the xsel to manipulate the clipboard program, but this is less than ideal, for obvious reasons. It would be nice if glfw provided some API for this.

Maybe it already does, and I just cant find it?

**Comment by elmindreda** [comment]
> As per the docs there does not seem to be any way to get/set the primary and secondary selections from the X11 clipboard.

That's correct. GLFW uses the CLIPBOARD selection, as it's the one most similar to the clipboard of other platforms. If I added functions for PRIMARY and SECONDARY selections, they wouldn't map to anything useful on platforms other than X11.

**Comment by kovidgoyal** [comment]
Sure, but on X11 it is pretty important to be able to use the other selections. The ability to paste from and copy to the PRIMARY selection is widely used throughout the X11 ecosystem, usually bound to the mouse middle click to paste and select to copy. While I can appreciate it is not useful on other platforms, IMO, it is too important to leave out. Other cross platform toolkits, Qt, for example, include the ability to use it on X11, see https://doc.qt.io/qt-5/qclipboard.html#Mode-enum

**Comment by elmindreda** [comment]
I'll consider it.

**Comment by elmindreda** [comment]
Now that I know about kitty, I think I understand this issue better. Still not sure if or how to address it, but I'll keep an eye out when implementing #275.

**Comment by kovidgoyal** [comment]
Thanks :)

**Comment by knielsen** [comment]
Meanwhile, does anyone know if there is a work-around to set the primary selection?
Eg. using a different API/library, based on a GLFW-created window?

(My motivation is that I need primary selection support in mupdf-gl, which is based on GLFW).

**Comment by kovidgoyal** [comment]
Just use a program like xsel. Look in the kitty source code for an example.

**Comment by knielsen** [comment]
Ah, I see, nice idea. Thanks for the pointer!

**Comment by knielsen** [comment]
I ended up implementing a facility in GLFW for accessing the X11 primary selection:

https://github.com/knielsen/glfw/commit/045fc5780edd215ddac70d0aad715854ac4ebd5d

The patch itself is very straight-forward, it's just plumbing to get PRIMARY down to X11 instead of CLIPBOARD. The real question here probably is whether something like this is too X11 platform specific to be included, or if it is sufficiently useful on X11 (and others, like wayland?) to be included.

In any case, if there is interest in something like this, I'm happy to create a pull request.

**Comment by tombsar** [comment]
@knielsen Thanks for the implementation. IMO since this is completely X11 specific, the function belongs in `glfw3native.h`, rather than the main API.

**Comment by knielsen** [comment]
From this, it seems Wayland might also have it:

  https://wiki.gnome.org/Initiatives/Wayland/PrimarySelection

So wayland support might be added later.

It might make sense that the functions are available on all platforms. Then applications can be written to support selection on platforms where it is available. On platforms without selection, the selection will just be unavailable.

That being said, I'm happy to put it in the native API if that is preferable.
