### ISSUE TITLE
High DPI support (native Windows 10 scaling)?

### ISSUE THREAD

**Issue by acterhd** [glfw/glfw#898]
Hello. How to get DPI from Windows settings, NOT from physical DPI of physical monitor?
For example 3840x2160 needs 200% or simply by float notation: `2.0`. 

Also, need get DPI settings in current monitor (because Windows 10 also uses own DPI scales per monitor).

**Comment by stanhebben** [comment]
I had the same problem and ended up writing some windows-specific code with the native interface:

```
#ifdef _WINDOWS
#define GLFW_EXPOSE_NATIVE_WIN32
#include <GLFW/glfw3native.h>
#include <ShellScalingApi.h>
#endif

struct ScreenScale {
	double scaleX;
	double scaleY;
};

ScreenScale getScreenScale(GLFWwindow* window)
{
	ScreenScale scale { 1, 1 };
#ifdef _WINDOWS
	HWND hwnd = glfwGetWin32Window(window);
	if (hwnd == nullptr)
		return scale;

	auto monitor = MonitorFromWindow(hwnd, MONITOR_DEFAULTTONEAREST);
	unsigned int dpiX;
	unsigned int dpiY;
	GetDpiForMonitor(monitor, MDT_EFFECTIVE_DPI, &dpiX, &dpiY);
	scale.scaleX = dpiX / 96.0;
	scale.scaleY = dpiY / 96.0;
#endif
	return scale;
}
```

Must be linked with **Shcore.lib** . Note that if the window is being moved, the application should check the scale again, since windows can be moved between different monitors, each having their own scaling setting.

If someone feels like extending this function with something that works on mac, that would be great. On any other platforms, it will simply return {1, 1}.

**Comment by elmindreda** [comment]
@stanhebben I will be adding something very similar to that function in 3.3.

**Comment by fabiopolimeni** [comment]
I also did something similar for retrieving the DPI of a monitor in Windows 10. In my version of the code, I have simply added two functions to the interface:

1. `glfwSetWindowDpiCallback()`, which gets triggered when WM_DPICHANGED is handled.
2. `glfwGetWindowDpi(GLFWwindow*, unsigned*)` that returns the current DPI. It translates directly to [GetDpiForWindow](https://msdn.microsoft.com/en-us/library/windows/desktop/mt748624(v=vs.85).aspx)

I have no enough experience with Mac or Linux, hence, no proposal. The only issue I have encountered is in file [win32_platform.h](https://github.com/glfw/glfw/blob/master/src/win32_platform.h) where at line 53 `WINVER` gets defined as declared before windows.h, therefore, such functions (which exist from Windows 10 onward) don't have a valid signature and throw a warning.

**Comment by elmindreda** [comment]
> I don't know if this is wanted because you expect those defines to be injected by VC (cl), but on my system, they don't, and therefore, the source code seem to have access only to functions up to Windows XP.

Replying only to this point; that is intentional. GLFW needs to build in old environments like VS 2010 and (non-w64) MinGW and needs to run on Windows XP.

**Comment by fabiopolimeni** [comment]
Suspected that, but I missed `win32_init.c`; runtime loading will be then :)

**Comment by capitalknew** [comment]
Rise support of high DPI in GLFW.
