### ISSUE TITLE
Inconsistent glfwMaximizeWindow behaviour for undecorated windows 

### ISSUE THREAD

**Issue by dougbinks** [glfw/glfw#899]
See forum thread [glfwMaximizeWindow bug on Windows 8.1 and Windows 10 with undecorated window](http://discourse.glfw.org/t/glfwmaximizewindow-bug-on-windows-8-1-and-windows-10-with-undecorated-window/802).

On Windows an undecorated maximized window will cover the entire monitor area, and not just the working area - so hiding the OS task/menu bar. Decorated windows only maximize to the working area, as do both decorated and undecorated windows on Linux Mint. I'm not sure of the behaviour on Mac OSX.

Whilst this follows the OS functionality since it uses ShowWindow(window->win32.handle, SW_MAXIMIZE), it makes it difficult to create an undecorated window which behaves like a decorated one.

I can think of a few solutions for this:

1. Modify glfwMaximizeWindow
1. Add a hint or compile flag to control behaviour of glfwMaximizeWindow
1. Add functionality to enable developers to maximize a window to the working area, either through a Get of the monitor working area or an alternative maximize function.

If needed I can do some of the work, but I don't have all the OSs GLFW supports if the solution alters behaviour for other systems.

**Comment by Squareys** [comment]
This is still an issue for windows created with `glfwWindowHint(GLFW_MAXIMIZED, GLFW_TRUE)` and `glfwWindowHint(GLFW_DECORATED, GLFW_FALSE)`.
A possible workaround is to call `glfwMaximizeWindow()` after window creation.

**Comment by elmindreda** [comment]
@Squareys Oops, that's definitely a bug. Please open an issue for this so it doesn't get lost.
