### ISSUE TITLE
Add direct support for gamecontrollerdb

### ISSUE THREAD

**Issue by CreamyCookie** [glfw/glfw#900]
Currently using the [**gamecontrollerdb**](https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt) might not even be possible as ["as the joystick functions don't expose POVs separately from buttons (or axes, in the case of the Linux 360 controller driver)."](https://github.com/glfw/glfw/issues/278#issuecomment-256910460)

Additionally to that we need a method to get the GUID of a joystick, which gamecontrollerdb uses to differentiate between joysticks with the same name. Note that the GUID's there may be changing soon: https://github.com/gabomdq/SDL_GameControllerDB/issues/110

Preferably this should support both polling and events.

**Comment by elmindreda** [comment]
The joystick functions don't expose POVs or GUIDs but GLFW uses the same underlying APIs as SDL2, so the internals will push the native data to both the joystick and controller functions and each will translate and present it after its own fashion.

**Comment by elmindreda** [comment]
This work has begun in the `gamecontrollerdb` branch.

**Comment by elmindreda** [comment]
- [ ] Joystick state handled by shared code
- [ ] Support for joystick hats
- [ ] Support for joystick GUIDs
- [ ] THE GREAT AND HORRIFYING SDL2 ELEMENT ORDER MATCHING
- [ ] Support for hats on Linux
- [ ] SDL_GameControllerDB parsing
- [ ] Element remapping logic
- [ ] Public gamepad state struct
- [ ] Public gamepad functions

**Comment by elmindreda** [comment]
Parsing, matching, remapping and state retrieval are working. There's still a little work left to do, but most of it is done.

Below is the raw state of an Xbox 360 controller on Linux (top) and filtered through a mapping (bottom) from the current `gamecontrollerdb.txt` file.

![mapping](https://user-images.githubusercontent.com/133714/27480294-a58485f2-5817-11e7-8eb0-c62a427c46cf.png)

The current (but not necessarily final) API is as follows:
```c
#define GLFW_GAMEPAD_DPAD_UP        0
#define GLFW_GAMEPAD_DPAD_RIGHT     1
#define GLFW_GAMEPAD_DPAD_DOWN      2
#define GLFW_GAMEPAD_DPAD_LEFT      3
#define GLFW_GAMEPAD_A              4
#define GLFW_GAMEPAD_B              5
#define GLFW_GAMEPAD_X              6
#define GLFW_GAMEPAD_Y              7
#define GLFW_GAMEPAD_LEFT_THUMB     8
#define GLFW_GAMEPAD_RIGHT_THUMB    9
#define GLFW_GAMEPAD_LEFT_BUMPER    10
#define GLFW_GAMEPAD_RIGHT_BUMPER   11
#define GLFW_GAMEPAD_START          12
#define GLFW_GAMEPAD_BACK           13

#define GLFW_GAMEPAD_LEFT_X         0
#define GLFW_GAMEPAD_LEFT_Y         1
#define GLFW_GAMEPAD_RIGHT_X        2
#define GLFW_GAMEPAD_RIGHT_Y        3
#define GLFW_GAMEPAD_LEFT_TRIGGER   4
#define GLFW_GAMEPAD_RIGHT_TRIGGER  5

typedef struct GLFWgamepadstate
{
    char buttons[14];
    float axes[6];
} GLFWgamepadstate;
glfwParseGamepadMapping
int glfwParseGamepadMapping(const char* string);
int glfwJoystickIsGamepad(int jid);
int glfwGetGamepadState(int jid, GLFWgamepadstate* state);
```

`glfwParseGamepadMapping` can handle both a single mapping, multiple mappings separated by newlines and the whole unmodified `gamecontrollerdb.txt` with comments and everything.

Feedback on the public API is very welcome, the earlier the better but any time before release works. Also, should it be _gamepad_ or _controller_?

**Comment by shurcooL** [comment]
> Also, should it be gamepad or controller?

From https://en.wikipedia.org/wiki/Game_controller:

> A game controller is a device used with games or entertainment systems to provide input to a video game, typically to control an object or character in the game.

From https://en.wikipedia.org/wiki/Gamepad:

> A gamepad (also called joypad or controller), is a type of game controller held in two hands, where the fingers (especially thumbs) are used to provide input.

So, a gamepad is a subset of controllers, it's a specific type.

https://www.googlefight.com/gamepad-vs-controller.php says controller is a much more popular word.

I think it depends on what other controllers are/will be supported.

If this API is very specific to gamepads, then gamepad is probably fine. But if it's going to apply to other types of controllers, then probably going with controller is a better fit.

(This is a very stereotypical bikeshedding moment... haha.)

**Comment by shurcooL** [comment]
> Also, how does this relate to the existing "joystick" API of GLFW?

I think I see it now:

```C
int glfwJoystickIsGamepad(int jid);
```

In that case, going with gamepad is more accurate and precise, as long as this API is only for gamepads and never for other types of controllers.

**Comment by CreamyCookie** [comment]
@elmindreda Great work! The API looks pretty good. :)

minor nitpicking: I don't mind the way it's now, but maybe the constants could be prefixed with `GLFW_GAMEPAD_BUTTON_` and `GLFW_GAMEPAD_AXIS_` respectively to make it even more obvious that they belong to two different categories. 

---

This is probably really obvious, but I just want to restate why some kind of unique identifier for the controller (for example `"$controllerName:$GUID"`) is important (to me). Given that the `GUID` differs, one one could store and restore the controller configuration (e.g. `moveUp=GLFW_GAMEPAD_DPAD_UP, useItem=GLFW_GAMEPAD_A`) for each controller, even if they're both called "Xbox controller". Each player would automatically be assigned their personal config and they could start the game and continue with the same character. 

Of course, if the controllers have different names, that (personal configs) are already possible. (If both players have controllers with the exact same name and GUID, then I guess there's no way around asking them who is who.)

**Comment by elmindreda** [comment]
> I think it depends on what other controllers are/will be supported.

@shurcooL You can see the full list [here](https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt). Basically anything that maps at least semi-reasonably to an Xbox controller.

> I don't mind the way it's now, but maybe the constants could start with `GLFW_GAMEPAD_BUTTON_` and `GLFW_GAMEPAD_AXIS_` respectively to make it even more obvious that they belong to two different categories.

@CreamyCookie Yeah, I wrote it that way initially but `GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER` got pretty long. Still considering it.

> This is probably really obvious, but I just want to restate why I think some kind of unique identifier for the controller (for example `"$controllerName:$GUID"`) is important. Given that the `GUID` differs, one could store and restore the controller configuration (e.g. `moveUp=GLFW_GAMEPAD_DPAD_UP, useItem=GLFW_GAMEPAD_A`) for each controller, even if they're both called "Xbox controller". Each player would automatically be assigned their personal config, which is useful if players have different tastes for how to control their character (or vehicle).

If you're referring to a unique hardware serial number, that's not exposed via the existing APIs. The GUID mentioned above identifies the make and model. If you mean a way to identify the current connection then the GLFW joystick ID serves just as well.

**Comment by shurcooL** [comment]
> I wrote it that way initially but `GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER` got pretty long. Still considering it.

It's long, but not unreasonable when considered in context of other long names:

```
GLFW_HAT_RIGHT_DOWN
GLFW_KEY_RIGHT_CONTROL
GLFW_MOUSE_BUTTON_MIDDLE
GLFW_CONTEXT_VERSION_MAJOR
GLFW_CONTEXT_RELEASE_BEHAVIOR
GLFW_COCOA_RETINA_FRAMEBUFFER
GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER
```

**Comment by elmindreda** [comment]
Minor API addition, separate from the `BUTTON_` or no `BUTTON_` discussion:
```c
#define GLFW_GAMEPAD_CROSS          GLFW_GAMEPAD_A
#define GLFW_GAMEPAD_CIRCLE         GLFW_GAMEPAD_B
#define GLFW_GAMEPAD_SQUARE         GLFW_GAMEPAD_X
#define GLFW_GAMEPAD_TRIANGLE       GLFW_GAMEPAD_Y
```

**Comment by elmindreda** [comment]
Another API update.
```c
#define GLFW_GAMEPAD_BUTTON_A               0
#define GLFW_GAMEPAD_BUTTON_B               1
#define GLFW_GAMEPAD_BUTTON_X               2
#define GLFW_GAMEPAD_BUTTON_Y               3
#define GLFW_GAMEPAD_BUTTON_LEFT_BUMPER     4
#define GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER    5
#define GLFW_GAMEPAD_BUTTON_BACK            6
#define GLFW_GAMEPAD_BUTTON_START           7
#define GLFW_GAMEPAD_BUTTON_GUIDE           8
#define GLFW_GAMEPAD_BUTTON_LEFT_THUMB      9
#define GLFW_GAMEPAD_BUTTON_RIGHT_THUMB     10
#define GLFW_GAMEPAD_BUTTON_DPAD_UP         11
#define GLFW_GAMEPAD_BUTTON_DPAD_RIGHT      12
#define GLFW_GAMEPAD_BUTTON_DPAD_DOWN       13
#define GLFW_GAMEPAD_BUTTON_DPAD_LEFT       14
#define GLFW_GAMEPAD_BUTTON_COUNT           15

#define GLFW_GAMEPAD_BUTTON_CROSS       GLFW_GAMEPAD_BUTTON_A
#define GLFW_GAMEPAD_BUTTON_CIRCLE      GLFW_GAMEPAD_BUTTON_B
#define GLFW_GAMEPAD_BUTTON_SQUARE      GLFW_GAMEPAD_BUTTON_X
#define GLFW_GAMEPAD_BUTTON_TRIANGLE    GLFW_GAMEPAD_BUTTON_Y

#define GLFW_GAMEPAD_AXIS_LEFT_X        0
#define GLFW_GAMEPAD_AXIS_LEFT_Y        1
#define GLFW_GAMEPAD_AXIS_RIGHT_X       2
#define GLFW_GAMEPAD_AXIS_RIGHT_Y       3
#define GLFW_GAMEPAD_AXIS_LEFT_TRIGGER  4
#define GLFW_GAMEPAD_AXIS_RIGHT_TRIGGER 5
#define GLFW_GAMEPAD_AXIS_COUNT         6

typedef struct GLFWgamepadstate
{
    char buttons[GLFW_GAMEPAD_BUTTON_COUNT];
    float axes[GLFW_GAMEPAD_AXIS_COUNT];
} GLFWgamepadstate;

int glfwParseGamepadMappings(const char* string);
int glfwJoystickIsGamepad(int jid);
const char* glfwGetGamepadName(int jid);
int glfwGetGamepadState(int jid, GLFWgamepadstate* state);
```

Something as simple as `gamepad.buttons[GLFW_GAMEPAD_BUTTON_X]` is now very clear but also very repetitive.

I think I'd prefer something like `gamepad.buttons.x`, but since we don't have anonymous structs and unions (because Microsoft) we either have to drop the state array or make struct access something like `gamepad.buttons.separate.x`.

Thoughts?

**Comment by elmindreda** [comment]
The code should now be at the point where you can try it out. See the `gamecontrollerdb` branch.

**Comment by elmindreda** [comment]
Things left to do:

- [ ] Proper solution to applying XInput mappings
- [ ] Generator [script](https://github.com/glfw/scripts) for `gamecontrollerdb.txt` > `mappings.h`
- [ ] Support for SDL 2.0.5 GUIDs
- [ ] Conversion of older GUIDs to new format
- [ ] Actually readable documentation

**Comment by elmindreda** [comment]
SDL_GameControllerDB support has been merged.

**Comment by elmindreda** [comment]
@CreamyCookie Did I misunderstand your question? Do you still want a `glfwGetJoystickGUID`?

**Comment by CreamyCookie** [comment]
@elmindreda Ohh... I started writing my response but somehow got distracted by something and the tab got buried :sweat_smile: 

> Do you still want a glfwGetJoystickGUID?

Yes, being able to know the GUID (which identifies the make and model) would be great. It'd allow to automatically use the right setup per controller every time the user starts the game. (e.g. Player 1 wants to use `GLFW_GAMEPAD_BUTTON_LEFT_BUMPER` for the "inventory" action, the other one wants to use `GLFW_GAMEPAD_BUTTON_A`.)


> If you're referring to a unique hardware serial number, that's not exposed via the existing APIs. 

A unique hardware serial number that never changes for each controller would be even better for correctly assigning the right controls, even when the make and model are the same. I guess that's often the case, because players buy another one of the same model if they're happy with it for guests (or buy them in a bundle from the start).

**Comment by elmindreda** [comment]
@CreamyCookie Fair enough.

**Comment by CreamyCookie** [comment]
@elmindreda Just saw that you closed this. So, before I forget, I want to say thank you for GLFW and the gamecontrollerdb support! (and further for adding glfwGetJoystickGUID) Great work! :vulcan_salute:

**Comment by ChengCat** [comment]
Sorry for being nitpicking, but I see an inconsistency in the new gamepad API, which you might be interested.

Currently, at least in `glfw3.h`, the only API function that returns a (int-represented) bool to indicate error is `glfwInit()`. It seems to me that returning void would be more consistent for `glfwUpdateGamepadMappings` and `glfwGetGamepadState`.

**Comment by elmindreda** [comment]
@ChengCat I agree that the return value of `glfwUpdateGamepadMappings` isn't very useful. However, the return value of `glfwGetGamepadState` saves the user having to make a separate call to `glfwJoystickIsGamepad` and/or `glfwJoystickPresent`.

**Comment by ChengCat** [comment]
@elmindreda Thanks for the reply. I don't need a separate call for `glfwGetGamepadState` in my use case. But I think you are right, and I understand other users may appreciate this. :)
