### ISSUE TITLE
OpenGL 3.2+ context creation poorly documented

### ISSUE THREAD

**Issue by DavidR91** [glfw/glfw#904]
When using glfw3 on macOS Sierra, it seems both `FORWARD_COMPAT` **and** `CORE_PROFILE` have to be supplied as hints for GL >= 3.2

Confusingly though, the absence of either produces a distinct error message, [as per the code here](https://github.com/glfw/glfw/blob/8d6f265441959d0eff2d3fd97edfb99b98ce2777/src/nsgl_context.m#L140)

* Without forward compat you're told `NSGL: The targeted version of macOS only supports forward-compatible contexts for OpenGL 3.2 and above`
* Without core profile you're told `NSGL: The targeted version of macOS only supports core profile contexts for OpenGL 3.2 and above`

So you effectively *have* to specify both. 

I don't know enough about GL caps on macOS to know if the actual logic of this check is correct - but even if it is, I think this check should be condensed into a single error message (i.e. 'You must use a forward-compatible core profile') as it is pretty confusing as it stands

**Comment by shurcooL** [comment]
> When using glfw3 on macOS Sierra, it seems both `FORWARD_COMPAT` **and** `CORE_PROFILE` have to be supplied as hints for GL >= 3.2

This is both normal and documented, at least in the FAQ:

[4.1 - How do I create an OpenGL 3.0+ context?](http://www.glfw.org/faq.html#how-do-i-create-an-opengl-30-context)

See same issues #832 and #812.

There may be a documentation clarity issue here, I'll let @elmindreda triage that.

**Comment by elmindreda** [comment]
> I think this check should be condensed into a single error message (i.e. 'You must use a forward-compatible core profile') as it is pretty confusing as it stands

This is a good point. Will fix.

**Comment by elmindreda** [comment]
This behavior could do with being documented in more places as well. I thought I'd added remarks for `glfwCreateWindow` and in the context guide, but turns out I hadn't.
