### ISSUE TITLE
Fail to create window on Sierra 10.12

### ISSUE THREAD

**Issue by umberto-sonnino** [glfw/glfw#909]
I've tried running a simple example which is available on learnopengl.com and it seems like the window creation called through `glfwCreateWindow()` fails because of the first responder on Cocoa. 

I've tried downloading the most recent version of the code from the repo - which seemed to address the problem - and recompiled the library locally, but still it doesn't seem to work properly and this is the output I get from the function call mentioned above.

```
2016-11-27 19:33:40.726198 GLFW[37260:6137830] [General] ERROR: 
Setting <GLFWContentView: 0x102a26000> as the first responder for window 
<GLFWWindow: 0x10071d510>, but it is in a different window ((null))! 
This would eventually crash when the view is freed. The first responder will be set to nil.
(
	0   AppKit                              0x00007fff798a69a4 -[NSWindow _validateFirstResponder:] + 566
	1   AppKit                              0x00007fff790979eb -[NSWindow _setFirstResponder:] + 31
	2   AppKit                              0x00007fff7913f66a -[NSWindow _realMakeFirstResponder:] + 406
	3   AppKit                              0x00007fff7913f480 -[NSWindow makeFirstResponder:] + 123
	4   libglfw3.3.dylib                    0x00000001000ab8fd _glfwPlatformCreateWindow + 617
	5   libglfw3.3.dylib                    0x00000001000a7427 glfwCreateWindow + 486
	6   GLFW                                0x0000000100001003 main + 99
	7   libdyld.dylib                       0x00007fff9056b255 start + 1
	8   ???                                 0x0000000000000001 0x0 + 1
)
Failed to create GLFW window
Program ended with exit code: 255
```

**Comment by elmindreda** [comment]
@umberto-sonnino What does `glfwGetVersionString` return?

**Comment by umberto-sonnino** [comment]
@elmindreda I get this:

`3.2.1 Cocoa NSGL chdir menubar retina dynamic`

**Comment by elmindreda** [comment]
Set an [error callback](http://www.glfw.org/docs/latest/intro_guide.html#error_handling) to get a better idea of why creation fails.

**Comment by umberto-sonnino** [comment]
The problem seems to be the following:
`65543 NSGL: The targeted version of macOS only supports forward-compatible contexts for OpenGL 3.2 and above`
Thus it fails in creating the window

**Comment by shurcooL** [comment]
@umberto-sonnino Are you setting the forward-compatible context hint to true?

If not, that's the source of your problem. See https://github.com/glfw/glfw/issues/904#issuecomment-262812712, https://github.com/glfw/glfw/issues/832#issuecomment-239379009 and https://github.com/glfw/glfw/issues/812#issuecomment-234724790.

**Comment by umberto-sonnino** [comment]
@shurcooL
Yeah I had set the flag, but still it doesn't seem to work properly. I'll try to figure out if something is not set up properly with the dylib

**Comment by eberlitz** [comment]
maybe its related to the issue #883. I'm having the same problem using the version 3.2.2.

**Comment by AndersenTobias** [comment]
I get the same error message to stdout, but it creates a window and everything seems to work normally besides the message.

**Comment by elmindreda** [comment]
@eberlitz There is no version 3.2.2.

**Comment by elmindreda** [comment]
@AndersenTobias Are you getting the first-responder message or the forward-compatible context message?

**Comment by AndersenTobias** [comment]
This first-responder message:
```
[General] ERROR: Setting <GLFWContentView: 0x10200be90> as the first responder for window <GLFWWindow: 0x100538e60>, but it is in a different window ((null))! This would eventually crash when the view is freed. The first responder will be set to nil.
```

**Comment by elmindreda** [comment]
@AndersenTobias That has been fixed in master.

**Comment by elmindreda** [comment]
Is it all right to close this now?

**Comment by AndersenTobias** [comment]
@elmindreda 
Yeah sure! Thank you

**Comment by lilyyyyyy2015** [comment]
can I know where to fix it? I got the same error of 'Setting <GLFWContentView: 0x100608aa0> as the first responder for window <GLFWWindow: 0x10070c810>, but it is in a different window ((null))! '

**Comment by elmindreda** [comment]
@lilyyyyyy2015 Just clone this repository, compile and use. That issue was fixed since the latest release.
