### ISSUE TITLE
Incorrect axis values returned from glfwGetJoystickAxes

### ISSUE THREAD

**Issue by DeadlyFugu** [glfw/glfw#910]
OS and version: Windows 10 64-bit
Release or commit: Release 3.2.1 and Commit 096efdf798896cff80a0b2db08d7398b703406fe
Error messages: None
events output: None relevant

When either the left or right thumbstick on my Xbox 360 controller is located to the far bottom left (i.e. position -1, -1), glfwGetJoystickAxes returns 0 for both axes instead. All other values are unaffected (e.g. -1, -0.9). Other axes remain unaffected (left and right triggers are completely unaffected, and if the left thumbstick should read (-1, -1), then only it's axes will read (0, 0) while the right thumbstick returns the correct values and vice versa).

The issue was reproducible for me via test/joysticks.c. It does not occur in the control panel, or in any games I've tried the controller with.

**Comment by elmindreda** [comment]
I cannot reproduce this with my 360 controller on 3.2.1 or master.

**Comment by DeadlyFugu** [comment]
As I can reproduce it, is there anything I am able to do to help?
If it matters, I'm using a third-party controller, although it's worked fine in games plus my own toyings with the XInput API.

**Comment by elmindreda** [comment]
Run [this tool](https://github.com/elmindreda/controllerspew) and post the output.

**Comment by DeadlyFugu** [comment]
Here's what I got from running the tool

    Controller (Gamepad for Xbox 360) (5:1:10:1): 03010e6f-0000-0000-0000-504944564944 (e6f:301:0:1:5)
    XInput Controller 0

**Comment by elmindreda** [comment]
That looks good and means GLFW should be using the XInput path for it.

If possible, please run some GLFW application with a debugger and check whether GLFW corrupts the incoming data. XInput data translation is fairly straightforward and starts [here](https://github.com/glfw/glfw/blob/3.2.1/src/win32_joystick.c#L573).

**Comment by DeadlyFugu** [comment]
Aha! Found it!
At line [606](https://github.com/glfw/glfw/blob/3.2.1/src/win32_joystick.c#L606) (and again at 619) there's an integer overflow when the controller is in the bottom left position. sThumbLX and sThumbLY both read -32768 on my controller. In this case, the statement 'xis.Gamepad.sThumbRX * xis.Gamepad.sThumbRX + xis.Gamepad.sThumbRY * xis.Gamepad.sThumbRY' will overflow, resulting in a negative, which is then passed to sqrt, resulting in a negative, which is then set to zero as it is within the deadzone.

**Comment by DeadlyFugu** [comment]
Not directly related to the issue, but I also noticed that the dead zone condition was effectively `sqrt(magnitude) < DEADZONE_CONSTANT`. Wouldn't squaring the constant instead be an (admittedly petty) optimisation, as well as slightly easier to read (less parenthesis and no `double` casts)? Although I guess it might not look very pretty with the 80 character width limit.

Sorry if it seems like I'm complaining. I think it's a great library and all, I'm just slightly averse to the sqrt function. :P

**Comment by elmindreda** [comment]
Yeah, you're not the only one to point this out. It's done but pending in another branch.
