### ISSUE TITLE
Crash on Debian 9 running glfwCreateWindow

### ISSUE THREAD

**Issue by paul4334** [glfw/glfw#913]
Debian 9/stretch live-boot
nvidia driver package version : 367.57-2
glx does not work properly in this environment and card (NVIDIA Corporation GP106 [GeForce GTX 1060 6GB] (rev a1)

> glxinfo
Error: couldn't find RGB GLX visual or fbconfig
name of display: :0.0

#912

**Comment by elmindreda** [comment]
This is a duplicate of #912.
