### ISSUE TITLE
glfwVulkanSupported emits VK_ERROR_OUT_OF_HOST_MEMORY error on systems without ICD

### ISSUE THREAD

**Issue by StrayLightning** [glfw/glfw#916]
When a Windows system has the Vulkan runtime installed but drivers that do not support Vulkan glfwVulkanSupported invokes _glfwInputError instead of returning GLFW_FALSE.

glfwVulkanSupported invokes _glfwInitVulkan with _GLFW_FIND_LOADER, and gets as far as vkEnumerateInstanceExtensionProperties before falling foul of the lack of driver support.

This might be considered an edge-case not a worth the effort to fix, but it makes it a pain for applications to report a sensible response to the user when they don't have a complete Vulkan stack.

**Comment by elmindreda** [comment]
What GPU and Windows version is this? Have run this on many machines without Vulkan support without hitting this error.

**Comment by StrayLightning** [comment]
This is on Windows 10 Anniversary, on a laptop with an AMD E-450 (Radeon HD 6320, no Vulkan support.)  Drivers are Catalyst 15.7.1 (last release with support for this APU.)  The machine has the Vulkan RT installed, as I have it installed wherever I'm developing.  The application has bespoke OpenGL and (WIP) Vulkan renderers. The application is actually using GLFW from Rust via glfw-rs, but I don't believe that will be materially affecting the situation.  When I have a moment I shall try removing the Vulkan RT and see what happens.

**Comment by elmindreda** [comment]
Thank you. This seems worth adding a workaround for.

**Comment by StrayLightning** [comment]
I'll see if I can knock up a quick example in C.

**Comment by elmindreda** [comment]
There is no need.

**Comment by StrayLightning** [comment]
OK.

**Comment by elmindreda** [comment]
This seems to be [happening](https://community.amd.com/message/2748060) to people who should have Vulkan as well.

**Comment by StrayLightning** [comment]
I am not really seeing the relevance, but perhaps I have missed something.  From reading glfwVulkanSupported and _glfwInitVulkan in vulkan.c, it seems to me that glfwVulkanSupported should return GLFW_FALSE if _glfwInitVulkan is not able to query the instance extensions (and possibly in other scenarios, too.)  I my case the Vulkan runtime was present and it requested the information from the driver, to which the driver indicated "no."

Sure, if you have invoked _glfwInitVulkan through some other path, _glfwInputError seems like a valid response on a failure path, but if you are querying whether Vulkan is supported on the system then "no" is the correct answer unless all the requisite parts are present.

**Comment by elmindreda** [comment]
My bad, I think I meant [this](https://community.amd.com/message/2751676) issue.

**Comment by elmindreda** [comment]
The reason it's not disabling all possible errors when in `_GLFW_FIND_LOADER` mode is to help diagnose bad configurations (as opposed to sane configurations lacking a Vulkan ICD). It seems I might've drawn the line in the wrong place.

**Comment by elmindreda** [comment]
I can reproduce this on my Nvidia system by removing the ICD key from `HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\Drivers`.

**Comment by elmindreda** [comment]
This should be fixed with 8e870d4cc0325ce41cc32f2323a2d8ae5429f4e6.
