### ISSUE TITLE
vkGetInstanceProcAddr incorrectly returns NULL for vkCreateXcbSurfaceKHR

### ISSUE THREAD

**Issue by Delwin9999** [glfw/glfw#918]
I'm getting this with the linux surface creation on version 3.2.1.  CentOS 6 with NVidia 367.57, GCC 4.9 and API 1.0.30.  If I insert 
```c
        if (!vkCreateXcbSurfaceKHR)
        {
            vkCreateXcbSurfaceKHR = (PFN_vkCreateXcbSurfaceKHR)
                _glfw_dlsym(_glfw.vk.handle, "vkCreateXcbSurfaceKHR");
        }
```
right after the vkGetInstanceProcAddr call in _glfwPlatformCreateWindowSurface in x11_window.c then it works fine as it will fall back to the dll loader when it can't find the extension using vkGetInstanceProcAddr.  This is a known problem with dynamically loading the Vulkan library and there's a lot of chatter about it on the Vulkan-Docs repository at [KhronosGroup/Vulkan-Docs#212](https://github.com/KhronosGroup/Vulkan-Docs/issues/212)

Unfortunately I can't issue pull requests from where I am or I would submit the patch.

**Comment by elmindreda** [comment]
Thank you for moving it!

**Comment by elmindreda** [comment]
Are you _absolutely certain_ that the instance you pass into `glfwCreateWindowSurface` has the required extensions enabled? I was able to run this code just fine on X11 with 367.57 yesterday.

Having read the linked discussion once, I could see nothing about the loader being affected by being loaded dynamically. I'll give it another look though.

**Comment by elmindreda** [comment]
The proposed fix can be made very short as `glfwGetInstanceProcAddress` already is a call to `vkGetInstanceProcAddr` with a fallback to `dlsym`.

**Comment by Delwin9999** [comment]
I'm certain since I'm using a patched version of x11_window.c that uses the fallback and that works fine.  Actually your solution is even better since swapping out the vkGetInstanceProcAddr for glfwCreateWindowSurface is a trivial fix.

**Comment by elmindreda** [comment]
Does the Vulkan test (`tests/vulkan.c`) run on your machine without this workaround?

**Comment by Delwin9999** [comment]
That test won't build on CentOS 6 because of [aligned_alloc being undefined](https://github.com/glfw/glfw/issues/727).

**Comment by elmindreda** [comment]
That has been fixed in master.

**Comment by Delwin9999** [comment]
If I fix that manually the test does run.

**Comment by elmindreda** [comment]
Thanks! Then the issue is likely somewhere in your Vulkan setup code.

**Comment by Delwin9999** [comment]
That makes sense.  Thank you!

**Comment by elmindreda** [comment]
Thank you for all the speedy replies! Hope you find the bug!
