### ISSUE TITLE
Spontaneous system volume changes on systems with lis3lv02d accelerometer

### ISSUE THREAD

**Issue by spelufo** [glfw/glfw#924]
When I run any program using glfw the system sound volume starts changing spontaneously. I have noticed this some months ago, but never reported it because it seemed hard to find a minimal example that shows what the problem is. Now I've cloned this repo and built `examples/gears.c` with `cd examples; cc -I ../deps/ -o gears gears.c ../deps/glad.c -lglfw -lm` and run it, which produces no errors and has the same effect: the volume starts changing.

I'm running Arch Linux on an HP Pavillion dv4. Below is the output of glxinfo, and of running the gears example under valgrind.

```sh
 $ pacman -Qi glfw-x11
Name            : glfw-x11
Version         : 3.2.1-1
...

 $ uname -a
Linux arch 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux

 $ glxinfo
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ironlake Mobile 
OpenGL version string: 2.1 Mesa 13.0.2
OpenGL shading language version string: 1.20
```

**Comment by elmindreda** [comment]
I have _no idea_ how to approach this one. I have never encountered or heard of this problem before and GLFW does not touch any audio API or synthesize system input that could be reasonably interpreted as volume changes.

In what way does the volume change?

**Comment by spelufo** [comment]
Increases and decreases randomly. It starts after a few seconds of starting a program, and persists some time after killing it. It also interferes with input, preventing the system from receiving keyboard events while the volume changes are happening. Maybe Xorg is getting key events for volume changes?

I'll try to disable those keys and check if the issue persists.

**Comment by spelufo** [comment]
I disabled the volume keys from the cinnamon keybindings menu. Other applications are definitely getting volume key events. Cinnamon no longer catches the events but for example VLC does, and produces similar volume changes.

Here is some output from running `xev` while running `./gears`:

```
...
KeyPress event, serial 37, synthetic NO, window 0x2a00001,
    root 0x98, subw 0x0, time 18487259, (163,-17), root:(502,249),
    state 0x0, keycode 123 (keysym 0x1008ff13, XF86AudioRaiseVolume), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x2a00001,
    root 0x98, subw 0x0, time 18487265, (163,-17), root:(502,249),
    state 0x0, keycode 123 (keysym 0x1008ff13, XF86AudioRaiseVolume), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 37, synthetic NO, window 0x2a00001,
    root 0x98, subw 0x0, time 18487269, (163,-17), root:(502,249),
    state 0x0, keycode 123 (keysym 0x1008ff13, XF86AudioRaiseVolume), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x2a00001,
    root 0x98, subw 0x0, time 18487277, (163,-17), root:(502,249),
    state 0x0, keycode 123 (keysym 0x1008ff13, XF86AudioRaiseVolume), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 37, synthetic NO, window 0x2a00001,
    root 0x98, subw 0x0, time 18487288, (163,-17), root:(502,249),
    state 0x0, keycode 122 (keysym 0x1008ff11, XF86AudioLowerVolume), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x2a00001,
    root 0x98, subw 0x0, time 18487294, (163,-17), root:(502,249),
    state 0x0, keycode 122 (keysym 0x1008ff11, XF86AudioLowerVolume), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
....
```

**Comment by elmindreda** [comment]
I don't know what to say. GLFW doesn't send `KeyPress` or `KeyRelease` to anything. You can verify this for yourself in `x11_window.c`, the only file that calls `XSendEvent`.

**Comment by spelufo** [comment]
Yes, I see that. I don't know how this is happening. I tried the same gears example on the same laptop booting from live usb sticks. One running manjaro and the other xubuntu. The same volume changes appeared in both.

**Comment by spelufo** [comment]
I run gdb on the gears example and the events start right after the `_glfwInitJoysticksLinux` call. I have no joystick, but there is a `/dev/input/js0` device file which I think is from an [accelerometer](https://www.kernel.org/doc/Documentation/misc-devices/lis3lv02d). I'll see what else I can find.

**Comment by spelufo** [comment]
Yes, after doing `# rm /dev/input/js0` the problem goes away. I guess glfw was using it as if it were a joystick and somehow that causes the problem.

**Comment by spelufo** [comment]
This seems to be the same as [this bug report](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/566181).

**Comment by elmindreda** [comment]
Nice detective work! Thank you! I'm not sure either, but will look into it.

**Comment by elmindreda** [comment]
Can you check what name GLFW said the "joystick" had?

**Comment by spelufo** [comment]
`printf("%s\n", glfwJoystickPresent(0) ? glfwGetJoystickName(0) : "No joystick");`
=> `ST LIS3LV02DL Accelerometer`

**Comment by elmindreda** [comment]
That is certainly an easy name to auto-detect. Do you know if it created any `eventX` nodes too?

**Comment by spelufo** [comment]
```
 $ cat /sys/devices/platform/lis3lv02d/input/input10/event9/uevent 
MAJOR=13
MINOR=73
DEVNAME=input/event9
```
Does this help?

**Comment by xCuri0** [comment]
@spelufo I dont have this problem when accessing that file on my HP laptop with the same accelerometer.Maybe its a problem with the accelerometer driver on your laptop

**Comment by spelufo** [comment]
Maybe. What driver are you using?

I'm not using the accelerometer for anything, so I can disable the lis3lv02d and hp_accel modules. This issue is not really a problem for me now that I now how to prevent it.

**Comment by xCuri0** [comment]
@spelufo I'm using `lis3lv02d` and `hp_accel`. I don't weird input problems so I guess its a bug with the `lis3lv02d` or `hp_accel` driver and not GLFW. Try creating a bug report for the kernel and also try upgrading your kernel to the latest stable release.

**Comment by spelufo** [comment]
OK, closing then.
