### ISSUE TITLE
Windows platform init fails if glfwInit() called from 2 different modules of a runtime

### ISSUE THREAD

**Issue by cuisinart** [glfw/glfw#927]
I found this using libfreenect2 Protonect demo on Windows 10, built with msvc 2015.
The libfreenect2 uses glfw to perform internal depth processing in a non-displayed window.
Protonect uses libfreenect2 to get images and uses glfw to display live kinect images via an opengl window.
If libfreenect2 is compiled as a dll, glfw has a different init context from its use by libfreenect2 and protonect.exe.  
glfw inits fine first from libfreenect2, and then glfwInit fails from protonect.exe when tries to init for its purposes, the error is it can't register the window class. Perhaps windows thinks it is registering again the same process?

My temporary workaround is to build libfreenect2 as a static library so that only one instance (and set of global variables) of glfw are created and shared between libfreenect2 and protonect.exe.

This problem is applicable to any uses where multiple libaries loaded by a single program may be using and loading glfw.dll without each others knowledge.

**Comment by elmindreda** [comment]
So GLFW doesn't support multiple copies of itself in the same process (as you've noticed). It might work on some platforms, but the code isn't written with that in mind. The recommended solution is either what you did, make it all static, or to have each of your dependencies depend on a single GLFW DLL.

That leaves the problem of one dependency terminating the library before another is done. My current plan is to add an option for reference counted initialization, so each dependency can operate (mostly) oblivious to the other ones. Would that be useful to you?

**Comment by cuisinart** [comment]
How about, on Windows, not failing _glfwRegisterWindowClassWin32() at RegisterClassExW if RegisterClassExW returns ERROR_CLASS_ALREADY_EXISTS.
UnregisterClass() will fail (will not delete the class) if there are windows of that class in the system, so only the last module to call glfwTerminate() will unregister the class. Granted, there are some scenarios where this could still break, but it would help most cases.

**Comment by elmindreda** [comment]
Since there can only be one window class with a single window procedure but there will be two copies of the GLFW code and internal state, one of the copies of GLFW will be using the wrong internal state copy inside the event handling. This will _not_ end well.

**Comment by zao** [comment]
Windows has a feature of "activation contexts" which can be used to have multiple side-by-side copies of the same window class, famously used for multiple versions of the Common Controls.

In short, you use isolation-aware functions to register your class with an activation context and have that context active when invoking `CreateWindow`. A place to start may be [Creating Side-By-Side Windows Classes](https://msdn.microsoft.com/en-us/library/windows/desktop/aa375136(v=vs.85).aspx) on MSDN.

I looked into this when colliding multiple versions of the Scintilla editor control in the same process but never managed to get this kind of SxS working properly. As I didn't need a well-known name for the window class, I ended up generating a random GUID at runtime as the class name for my own private Scintilla module.

**Comment by elmindreda** [comment]
Nope. Nope nope nope. Not going down this rabbit hole. Yes, I could randomly generate window class names. I won't. After this there'll be more issues, and even if @cuisinart personally won't encounter them, the next person with a slightly different use pattern will.

This is what DLLs are for. Use a single copy of GLFW as a DLL. I can add init reference counting so you don't have to implement it yourself.

**Comment by elmindreda** [comment]
However, if someone wants to maintain this capability for this and future releases, on all supported platforms, make an audit and get in touch. If the necessary changes and resulting coding restrictions aren't too intrusive on any platform, I'll merge your patches.

**Comment by elmindreda** [comment]
@cuisinart If this is the only thing preventing your specific application from working, you can change the value of [_GLFW_WNDCLASSNAME](https://github.com/glfw/glfw/blob/3.2.1/src/win32_platform.h#L211) when compiling the GLFW static library your application uses.

**Comment by cuisinart** [comment]
Ok, thank you for your review.

**Comment by elmindreda** [comment]
Sorry I couldn't give better news. I need to focus on more widely used functionality. In the meantime, the offer to work with someone who wishes to take this on stands.

**Comment by noizebox** [comment]
> That leaves the problem of one dependency terminating the library before another is done. My current plan is to add an option for reference counted initialization, so each dependency can operate (mostly) oblivious to the other ones.

Is this something that is still in the plan, 4 years down the road? I ran in to a situation where I needed reference counted initialization and implemented a basic version of it.
