### ISSUE TITLE
Window size of iconified window

### ISSUE THREAD

**Issue by ShchAlexander** [glfw/glfw#931]
Hello, when I trying to retrieve window size of iconified (minimized) window using `glfwGetWindowSize` it returns me zero values for width and height. 
The same situation with `glfwGetFramebufferSize`.
Is it correct?
And another question: Is there any way to keep size and framebuffer size the same as they were before iconifying window?

**Comment by elmindreda** [comment]
Yes, that is correct. If you want to keep rendering to a framebuffer of a size you control when the window is iconified (or resized), use an OpenGL or OpenGL ES framebuffer object.
