### ISSUE TITLE
Joystick disconnection not emitted on event poll

### ISSUE THREAD

**Issue by gestaltdevstudio** [glfw/glfw#932]
Hello,
I don't know if it's a bug but it took me some good minutes of work :/
The event GLFW_DISCONNECTED only occurs when the glfwGetJoystickAxes or glfwGetJoystickButtons is called in main loop.

To produce this issue try to remove the call of function
`        draw_joysticks(window);`
in test file "joysticks.c" at line 204, and disconnect the joystick. 

Version tested: GLFW 3.2.1

**Comment by FlandreScarlet** [comment]
I think this is intended behaviour, at least according to [the documentation](http://www.glfw.org/docs/latest/input_guide.html#joystick)?

(emphasis mine)
> Joystick state **is updated as needed when a joystick function is called** and does not require a window to be created or glfwPollEvents or glfwWaitEvents to be called.

Maybe adding this information to the _Joystick configuration changes_ section would make this harder to miss.

**Comment by elmindreda** [comment]
@FlandreScarlet Agreed, the documentation needs to be clarified.

@gestaltdevstudio What other functions were you expecting would trigger this event? I'm looking into making this bit more consistent between platforms, so this is great timing.

**Comment by gestaltdevstudio** [comment]
@FlandreScarlet Thanks!

@elmindreda I'm sorry, the title is summarized. In the example:

> void joystick_callback(int joy, int event)
> {
>     if (event == GLFW_CONNECTED)
>     {
>         // The joystick was connected
>     }
>     else if (event == GLFW_DISCONNECTED)
>     {
>         // The joystick was disconnected
>     }
> }

The "event" that I was referring to.
Sorry if it's not an issue but as the GLFW_CONNECTED occurs, I was expecting the GLFW_DISCONNECTED without code about joystick in main loop yet, like a callback behavior. Is it possible?

**Comment by elmindreda** [comment]
@gestaltdevstudio GLFW can't call your callback function unless you first pass control to it by calling one of its functions. If not one of the joystick functions, which other ones should also check for joystick disconnection?

**Comment by gestaltdevstudio** [comment]
@elmindreda This is a good question. Maybe calling pollJoystickEvents in glfwPollEvents() instead of glfwGetJoystickAxes or glfwGetJoystickButtons. I think it will be more faithful with the callback behavior. If a joystick connected has to be used why not to check if it's present always? Even if I'm not reading it's axes and buttons?

I hope I have helped :)

**Comment by elmindreda** [comment]
I can do device connection events that way. Not sure about disconnection.

Out of curiosity, what are you using the disconnection events from joysticks you aren't polling for?

**Comment by gestaltdevstudio** [comment]
@elmindreda I am testing and adapting my own engine to use GLFW, and I do it bit by bit, until it runs on Linux / Win. So first I created the callback function and I was sure that the callback should work entirely just with glfwPollEvents(), before I test the joytick's buttons and axes.
It was more intuitive for me. And I was hoping for a more simple function to check the connectivity than one that get all axes or buttons. Besides getting the GLFW_CONNECTED without all that.

But it's just my way of thinking. Do you think it makes sense? I don't know if I was clear...
Thanks for all of your hard working!
Let me know if I can help.

PS: I thought that was an issue on linux at the beginning ahahaha

**Comment by elmindreda** [comment]
@gestaltdevstudio That makes sense, thank you.

**Comment by elmindreda** [comment]
Joystick disconnection events should now be emitted by all event processing functions on X11.

**Comment by elmindreda** [comment]
There is a separate issue where the waiting event processing functions aren't properly interrupted by joystick events. Fixing that one right now.
