### ISSUE TITLE
Dynamic loading does not use full soname

### ISSUE THREAD

**Issue by lwintermelon** [glfw/glfw#941]
ubuntu 16.10 
ubuntu 16.10 doesn't have a file named libX11-xcb.so that links to libX11-xcb.so.1 or others,so the code `_glfw.x11.x11xcb.handle = dlopen("libX11-xcb.so", RTLD_LAZY | RTLD_GLOBAL);`gets NULL.Create a link or change the code,it works...

**Comment by elmindreda** [comment]
That is indeed a bug. Thank you!
