### ISSUE TITLE
Support for UWP apps

### ISSUE THREAD

**Issue by jboich** [glfw/glfw#942]
Hi. 
Does GLFW support UWP apps (Windows 10 )?
I tried to use precompiled glfw3dll.lib and get an error when trying to launch app (though it builds without errors)

`The program 'App1.exe' has exited with code -1073741515 (0xc0000135) 'A dependent dll was not found'.`

**Comment by elmindreda** [comment]
GLFW does not currently support UWP. I believe UWP doesn't currently provide sane access to OpenGL or Vulkan.

**Comment by jboich** [comment]
ok. thanks for the quick response!

**Comment by elmindreda** [comment]
What rendering API were you planning to use on UWP?

**Comment by jboich** [comment]
We would like to use all basic API of OpenGL 3.2, 3.3 at least. We are also interested in having multiple render targets feature.

**Comment by elmindreda** [comment]
Right. As far as I know, Microsoft has not made that available on UWP.

**Comment by elmindreda** [comment]
For a similar library that does support WinRT/UWP, check out SDL2. You will need to use Microsoft rendering APIs or ANGLE, though.

**Comment by linkmauve** [comment]
If you limit yourself to GLES 2.0 or 3.0, wouldn’t it be transparent to use ANGLE’s libEGL and libGLESv2 with GLFW? (Note that I never tried this configuration, this is pure speculation.)
