### ISSUE TITLE
How should an unimplemented function behave?

### ISSUE THREAD

**Issue by hesiod** [glfw/glfw#945]
In [window.c, line 227](https://github.com/glfw/glfw/blob/master/src/window.c#L227) the platform's window focus function is called, however on Wayland [that function](https://github.com/glfw/glfw/blob/master/src/wl_window.c#L591) unconditionally ~~makes GLFW terminate with an error~~ reports an error.
Since `GLFW_FOCUSED` defaults to true, this means that a number of applications using GLFW ~~don't work with Wayland out of the box~~ will see that error, i.e. without setting `GLFW_FOCUSED` to `GLFW_FALSE`.

**Comment by elmindreda** [comment]
The Wayland implementation does emit an error when `_glfwPlatformFocusWindow` is called, but it does not terminate in any sense of the word.

**Comment by hesiod** [comment]
@elmindreda Oops, my mistake, I was exiting the application in the error callback. Anyways, the issue is relevant nonetheless relevant.

**Comment by elmindreda** [comment]
Thank you for the clarification and updates.

Seems there's at least two things to do: clarify the documentation of errors and look over how unimplemented functions are handled and what if anything they should be doing. Emitting `GLFW_PLATFORM_ERROR` isn't ideal.

**Comment by elmindreda** [comment]
GLFW now emits `GLFW_FEATURE_UNAVAILABLE` or `GLFW_FEATURE_UNIMPLEMENTED` instead of re-using other error codes.
