### ISSUE TITLE
Setting refresh rate does not work

### ISSUE THREAD

**Issue by plazmakeks** [glfw/glfw#948]
OS: Ubuntu 16.04.1 LTS
GLFW version string: 3.3.0 X11 GLX EGL clock_gettime /dev/js Xf86vm

window manager:
$ wmctrl -m

Name: Compiz
Class: N/A
PID: N/A
Window manager's "showing the desktop" mode: OFF

$ echo $DESKTOP_SESSION
gnome-flashback-compiz

$ echo $XDG_CURRENT_DESKTOP
GNOME-Flashback:Unity

Hi, I'm using GLFW for my application window. I'd like to alter the refresh. According to the documentation this should be done by glfwSetWindowMonitor when a monitor is chosen, which means the window is turned to fullscreen. Unfortunately in my case it doens't work. I'll provide you some code snippets and the corresponding application output.
```c
void Window::handleKeyEvent(int _key, int _scanCode, int _action, int _mods) {
	if(_action != GLFW_PRESS) { return; }
	switch(_key){
	case GLFW_KEY_ESCAPE:
		this->exit();
		break;
	case GLFW_KEY_F:
		this->toggleFullscreen();
		break;
	case GLFW_KEY_DOWN:
		this->increase_fps(-1);
		break;
	case GLFW_KEY_UP:
		this->increase_fps(1);
		break;
	case GLFW_KEY_S:
		this->screenshot(std::string("screenshot.png"));
		break;
	}
}

void Window::increase_fps(int _delta) {
	int fps_to = settings.fps + _delta;
	if(fps_to <= 0) {
		return;
	}
	if(fps_to >= 100) {
		return;
	}

	settings.fps = fps_to;
	updateFullscreenAndFPS();
}

void Window::updateFullscreenAndFPS() {
	//http://www.glfw.org/docs/latest/group__window.html#ga81c76c418af80a1cce7055bccb0ae0a7
	std::shared_ptr<GLFWmonitor> updatedMonitor(settings.fullscreen? monitor.get() : NULL, [](GLFWmonitor*){});
	glfwSetWindowMonitor(  window.get(),
				   updatedMonitor.get(),
						 settings.xpos,
						 settings.ypos,
						 getWidth(),
						 getHeight(),
						 settings.fps);

	printf("current monitor: %s\n", updatedMonitor.get() == NULL? "NULL" : glfwGetMonitorName(updatedMonitor.get()));
	printf("desired refresh rate: %d\n", settings.fps);
	printf("actual  refresh rate: %d\n", glfwGetVideoMode(monitor.get())->refreshRate);
}
```
This code produces the following output:
```
current monitor: NULL
desired refresh rate: 61
actual  refresh rate: 59
current monitor: NULL
desired refresh rate: 62
actual  refresh rate: 59
current monitor: DP1
desired refresh rate: 62
actual  refresh rate: 59
current monitor: DP1
desired refresh rate: 63
actual  refresh rate: 59
current monitor: DP1
desired refresh rate: 64
actual  refresh rate: 59
current monitor: DP1
desired refresh rate: 65
actual  refresh rate: 59
```

**Comment by elmindreda** [comment]
The `glfwSetWindowMonitor` function updates the [desired video mode](http://www.glfw.org/docs/latest/window_guide.html#window_full_screen) of the window and then selects the most closely matching video mode of those supported by your monitor. GLFW cannot set the monitor to a mode it does not support.

Call `glfwGetVideoModes` or run the `monitors` test to see what video modes are supported by each monitor.

**Comment by elmindreda** [comment]
Why do you want such fine control over monitor refresh rate? What problem are you trying to solve?

**Comment by plazmakeks** [comment]
It's a feature request. But thanks to you i got the point. Only thing i can do is slow the refresh rate down.
