### ISSUE TITLE
Cursor does not become hidden.

### ISSUE THREAD

**Issue by assumptionsoup** [glfw/glfw#949]
```
glfwSetInputMode(window, GLFW_CURSOR, GLFW_CURSOR_HIDDEN);
```
On windows 10 with glfw-3.2.1 I'm seeing that neither `GLFW_CURSOR_HIDDEN` nor `GLFW_CURSOR_DISABLED` hide the cursor when run before the main loop.  When set inside the main loop, they cause the cursor to flicker.

**Comment by elmindreda** [comment]
Are you running in a virtual machine?

**Comment by assumptionsoup** [comment]
No, I'm running directly on the machine.  I could be doing something wrong though, I'm just starting to learn opengl.

**Comment by assumptionsoup** [comment]
Whoops! Figured out the problem.  Looks like I'm using imgui incorrectly.  I'll sort it out in my code.  Sorry for the inconvenience!!

**Comment by elmindreda** [comment]
Thank you for the follow-up.
