### ISSUE TITLE
memcpy called with NULL for zero size

### ISSUE THREAD

**Issue by LostRedSky** [glfw/glfw#950]
I don't know if it is worth something but just in case I am creating this issue.

OS: Linux Mint 18
Commit: c3fd757b

Just added GLFW as a submodule (on commit c3fd757b, which is master right now) of a project and upon calling 'glfwInit()' my standard library (compiled from sources, thus in "debug" mode) gives me the following message:

`/home/path/to/glfw/glfw/src/x11_monitor.c:117:9: runtime error: null pointer passed as argument 2, which is declared to never be null`

The line in question is:

`memcpy(disconnected, _glfw.monitors, _glfw.monitorCount * sizeof(_GLFWmonitor*));`

Aside from this message, there are no consequences, I am still able to create a window after that.

In my case _glfw.monitors is indeed null, however _glfw.monitorCount is 0 and thus the code is requesting to copy 0 bytes of a null pointer. I don't particularly see this as a problem but my memcpy does give me this annoying message.

I bisected to find the first commit in which the message appears and it's from commit 04f559e2 "Restructure monitor enumeration".

**Comment by elmindreda** [comment]
Thank you!
