### ISSUE TITLE
Draws nothing in fullscreen on Sierra on new Macbook Pro

### ISSUE THREAD

**Issue by Discordia** [glfw/glfw#953]
I have a C++ codebase based on GLFW3 and OpenGL. I got it working on OSX 10.11 El Capitan on a Macbook Pro mid 2014. But now I got the new Macbook Pro 2016 !5" with the Intel HD Graphics 530 and the Radeon Pro 455, and I'm struggling to get to work. I'm also seeing som estrange behaviour with windows sizes and fullscreen.

I created the same example as here: http://www.glfw.org/docs/latest/quick.html
but with a bit more logging. I pushed it to here: https://github.com/Discordia/glfw-example

There is two lines for creating the window. The first one creates a window and the second one a full screen window. I alternate between them to test windowed or fullscreen mode.

Output in windowed mode is:
/<pth>/glfw-example/cmake-build-debug/glfw_example
Primary mode w: 1680, h: 1050, r: 8, g: 8, b: 8, refresh: 60
Modes w: 640, h: 480, r: 8, g: 8, b: 8, refresh: 60
Modes w: 840, h: 524, r: 8, g: 8, b: 8, refresh: 60
Modes w: 800, h: 600, r: 8, g: 8, b: 8, refresh: 60
Modes w: 1024, h: 768, r: 8, g: 8, b: 8, refresh: 60
Modes w: 1152, h: 720, r: 8, g: 8, b: 8, refresh: 60
Modes w: 1280, h: 800, r: 8, g: 8, b: 8, refresh: 60
Modes w: 1440, h: 900, r: 8, g: 8, b: 8, refresh: 60
Modes w: 1650, h: 1050, r: 8, g: 8, b: 8, refresh: 60
Modes w: 2048, h: 1280, r: 8, g: 8, b: 8, refresh: 60
Modes w: 2560, h: 1600, r: 8, g: 8, b: 8, refresh: 60
Modes w: 2880, h: 1800, r: 8, g: 8, b: 8, refresh: 60
Modes w: 3360, h: 2100, r: 8, g: 8, b: 8, refresh: 60
Framebuffer size w: 1280, h: 960
Initialized, GL Version: 2.1 ATI-1.48.21
Process finished with exit code 0

Notice that I'm asking for a 640x480 window but the frame buffer ends up being 1280x960.

Output in full screen is:
/<path>/glfw-example/cmake-build-debug/glfw_example
Primary mode w: 1680, h: 1050, r: 8, g: 8, b: 8, refresh: 60
Modes w: 640, h: 480, r: 8, g: 8, b: 8, refresh: 60
Modes w: 840, h: 524, r: 8, g: 8, b: 8, refresh: 60
Modes w: 800, h: 600, r: 8, g: 8, b: 8, refresh: 60
Modes w: 1024, h: 768, r: 8, g: 8, b: 8, refresh: 60
Modes w: 1152, h: 720, r: 8, g: 8, b: 8, refresh: 60
Modes w: 1280, h: 800, r: 8, g: 8, b: 8, refresh: 60
Modes w: 1440, h: 900, r: 8, g: 8, b: 8, refresh: 60
Modes w: 1650, h: 1050, r: 8, g: 8, b: 8, refresh: 60
Modes w: 2048, h: 1280, r: 8, g: 8, b: 8, refresh: 60
Modes w: 2560, h: 1600, r: 8, g: 8, b: 8, refresh: 60
Modes w: 2880, h: 1800, r: 8, g: 8, b: 8, refresh: 60
Modes w: 3360, h: 2100, r: 8, g: 8, b: 8, refresh: 60
Framebuffer size w: 3360, h: 2100
Initialized, GL Version: 2.1 ATI-1.48.21
Process finished with exit code 0

Notice that the monitor primary mode is 1680x1050 (which seams strange), and the frame buffer ends up being 3360x2100 (which seams more reasonable).

The problem though is that it draws fine in windowed mode. A animated triangel with different color per vertex. In fullscreen the window is black. The only thing I change between runs is the forth argument to glfwCreateWindow. Either it's nullptr for windowed mode or it's the monitor pointer for fullscreen.

If I change the fullscreen line to:
window = glfwCreateWindow(3360, 2100, "Simple example", monitor, nullptr);
Then I actually see the animated triangle but in't not centered. It is spinning in the bottom half of the screen. Also the frame buffer is then reported as:
Framebuffer size w: 2560, h: 1600

If I change it to:
window = glfwCreateWindow(2560, 1600, "Simple example", monitor, nullptr);

I see just the tip of the spinning triangle at the bottom of the screen, most of it is outside. And the frame buffer is reported as:
Framebuffer size w: 2048, h: 1280

Isn't this strange.

**Comment by Discordia** [comment]
I created the same example with SDL2 baed on this: http://headerphile.com/sdl2/opengl-part-1-sdl-opengl-awesome/

I pushed it to here: https://github.com/Discordia/sdl-example

There is a similar confusion that 640x480 gives me: 1680x1050. But it works, it shows the rotating triangle centered in fullscreen.

**Comment by elmindreda** [comment]
> Notice that I'm asking for a 640x480 window but the frame buffer ends up being 1280x960.

This is normal on that system. The video mode resolution uses [screen coordinates](http://www.glfw.org/docs/latest/intro_guide.html#coordinate_systems), i.e. the same unit as window sizes and positions, cursor positions and monitor viewport positions and on modern Macs that is typically . The framebuffer size is specified in pixels, as that is what OpenGL works with.

> If I change the fullscreen line to:
```c
window = glfwCreateWindow(3360, 2100, "Simple example", monitor, nullptr);
```
>Then I actually see the animated triangle but in't not centered. It is spinning in the bottom half of the screen. Also the frame buffer is then reported as:
```
Framebuffer size w: 2560, h: 1600
```

GLFW has a bug relating to full screen windows using hidpi scaled video modes (i.e. where screen coordinates and pixels don't map 1:1). See #682 for more details. For now, the recommended approach is to use ["windowed full screen"](http://www.glfw.org/docs/latest/window_guide.html#window_windowed_full_screen).
