### ISSUE TITLE
Vulkan libraries moved in Windows LunarG SDK 1.0.42.0

### ISSUE THREAD

**Issue by cdwfs** [glfw/glfw#956]
The LunarG Vulkan SDK for Windows seems to have moved the Vulkan libraries from $VULKAN_SDK\Bin[32] to $VULKAN_SDK\Lib[32]. This breaks the search code in glfw/CMake/modules/FindVulkan.cmake, leading to VULKAN_LIBRARY and VULKAN_STATIC_LIBRARY being undefined/NOTFOUND. Replacing "\Bin" with "\Lib" in this module seemed to fix the build on my test system, but maybe both are needed for now, to support both old and new locations.

**Comment by elmindreda** [comment]
Thank you! This should be fixed now with c54b5da4037696b748fe80d207b6b9ee229c956e.

**Comment by cdwfs** [comment]
Blindingly fast response as always. Thanks!
