### ISSUE TITLE
cocoa: failed to retrieve display name

### ISSUE THREAD

**Issue by SimonDanisch** [glfw/glfw#958]
Hi,
I'm trying to setup a testing server on OSX, but it will fail when no display is connected.
It fails here: https://github.com/glfw/glfw/blob/master/src/cocoa_monitor.m#L52
Is it possible to just move on and return NULL, like it says in the comment? (` Get the name of the specified display, or NULL` )
The same setup works for me on windows, so I guess the rest of GLFW is ready for this ;)

**Comment by elmindreda** [comment]
It does just move on and return NULL. Errors are not fatal.

**Comment by elmindreda** [comment]
However, if that is where the function normally returns NULL on a headless system (I only have laptops, so I can't verify) then I'll remove that error message.

**Comment by SimonDanisch** [comment]
Oh, silly me. We implemented the error callback to throw and I didn't realize GLFW itself can just move on!
Thanks, ignoring the error works!

**Comment by SimonDanisch** [comment]
But yeah, since everything works correctly when ignoring, it would be nice to get rid of the error!

**Comment by jayschwa** [comment]
@SimonDanisch, does this error occur when calling `GetMonitorName` or someplace else, like `Init` (which the Julia package calls automatically on import).

**Comment by SimonDanisch** [comment]
it's on import in the `__init__`!

**Comment by jayschwa** [comment]
Okay. I think I will devise a workaround for this specific error in our wrapper, rather than treating all of them to warnings.

Can you confirm for @elmindreda if this is occurring on a headless system? If so, then perhaps we can back out the workaround when the next version of GLFW is released.

**Comment by maleadt** [comment]
> Can you confirm for @elmindreda if this is occurring on a headless system? If so, then perhaps we can back out the workaround when the next version of GLFW is released.

Yes, this was on an NVIDIA system with X11 option `UseDisplayDevice` set to `none`, forcing it to be headless.

**Comment by SimonDanisch** [comment]
If that helps, here is a full list of errors we could ignore on a headless system:
```Julia
code == PLATFORM_ERROR && (
			contains(description, "Failed to get display service port iterator") ||
			contains(description, "Failed to retrieve display name") ||
			contains(description, "RandR gamma ramp support seems broken") ||
			contains(description, "RandR monitor support seems broken") ||
			contains(description, "Failed to watch for joystick connections in")
)
```
