### ISSUE TITLE
Xbox gamepad's left stick has an inverted Y axis on Windows 7 & 8

### ISSUE THREAD

**Issue by gestaltdevstudio** [glfw/glfw#959]
Hi all,

I'm testing the PS4, Xbox 360 and Xbox One gamepads with GLFW 3.2.1. On Linux it works very well. But the Windows driver is inverting the Y axis of the left stick in Xbox 360 and Xbox One gamepads. I don't know if it's a bug. In my case, I made an workaround to make then work similiar. As Xbox and Windows are microsoft products, I think it's not an issue by their side.

I'm available for other tests.
I hope I have helped!

**Comment by elmindreda** [comment]
I wouldn't call it a bug, but it's definitely a limitation of the current GLFW API. The joystick functions expose the buttons, axes (and since yesterday hats) that the underlying platform APIs provide, without any remapping to make it consistent across platforms, because it doesn't have the information to do that in a general way.

To solve this for gamepads, however, there will be some new functions added to retrieve labelled, consistent gamepad state and to import [SDL2 gamepad mappings](https://github.com/gabomdq/SDL_GameControllerDB). You can track this work in #900.

**Comment by gestaltdevstudio** [comment]
@elmindreda Thanks for the answer! 

I don't know if it's elegant, but, based on GLFW idea, I made a simple text file (one per OS),  trying to help the users with unrecognized gamepads, but preset with already recognizable gamepads in my tests. And I'll add a little executable that shows the model, which button/axis is been pressed and the value (-1 or 1 for axes). That's it for while. If it doesn't solve it, in the future maybe I'll make an executable that generates the line in txt. 

I'm beginner in the joystick's subject but, If someone is interested in the code I can share without problem.

BTW, I made the executable based on [Joystick Test File](https://github.com/glfw/glfw/blob/master/tests/joysticks.c). What do you think about making something similar in the [tests folder](https://github.com/glfw/glfw/tree/master/tests)? :P

```
....
Model:"Xbox Gamepad (userspace driver)";Jump:0;MoveX:0=1;MoveY:1=1;Pause:7;
...
```

Thanks again!

**Comment by elmindreda** [comment]
If I understand this correctly, it sounds like it would be duplicating the work of SDL_GameControllerDB.

**Comment by gestaltdevstudio** [comment]
In a different way I think, but yes in the end. In short, my idea mixes the SDL_GameControllerDB solution with a specific game control settings. With no changes in GLFW 3.2.1.

Thanks!

**Comment by elmindreda** [comment]
Somewhere between these two approaches is the [GLFW controller database](http://discourse.glfw.org/t/glfw-controller-database/768) effort that might one day let GLFW tell users device-specific names of controller elements.

**Comment by andrenardelli** [comment]
I also tried it before made mine. I got "Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 11" when I connect the Ps4 controller.

**Comment by gestaltdevstudio** [comment]
I also tried it before made mine. I got the following error:
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 11
	at com.shc.silenceengine.input.InputDevice.postControllerAxisEvent(InputDevice.java:228)
	at com.shc.silenceengine.backend.lwjgl.LwjglInputDevice.pollControllers(LwjglInputDevice.java:110)
	at com.shc.silenceengine.backend.lwjgl.LwjglRuntime.start(LwjglRuntime.java:100)
	at com.shc.silenceengine.tests.lwjgl.ControllerTestRun.main(ControllerTestRun.java:38)
