### ISSUE TITLE
Only one monitor returned on dual monitor setup

### ISSUE THREAD

**Issue by surafel911** [glfw/glfw#960]
I have two monitors on my desktop, but for some reason GLFW only registers one monitor, my secondary monitor. I can't take a picture of my setup right now (nor do I think it's needed), but here is a picture of the code and the return value.

![image](https://cloud.githubusercontent.com/assets/24972439/23585862/c0d5b564-0156-11e7-9b45-5fd2d2f5c89d.png)

Let me know if you need more info.

**Comment by elmindreda** [comment]
Please see the section [Reporting a monitor or video mode bug](https://github.com/glfw/glfw/blob/master/.github/CONTRIBUTING.md#reporting-a-monitor-or-video-mode-bug).

**Comment by elmindreda** [comment]
Please also submit any text as text, not as images.

**Comment by surafel911** [comment]
Sorry for the mistake. This is my first time using an issues forum of any kind.

Windows 10 64-bit
GLFW 3.2.1

I ran the monitor.c file, and I get this output:

Name: Acer E202HL (Digital) (primary)
Current mode: 1600 x 900 x 24 (8 8 8) 60Hz
Virtual Position: 1920 0

And the rest of the info is about different modes and the physical size.

The problem with this output is that the name of the monitor is my primary monitor, but the current mode of the monitor is actually my secondary monitor, which is an Emacs monitor with analog input (forgot the model name).

**Comment by elmindreda** [comment]
Are both monitors part of the Windows desktop?

**Comment by surafel911** [comment]
If you mean that Windows recognizes both monitors, then yes.

**Comment by elmindreda** [comment]
Thank you, that is useful.

Please post the output of [this tool](https://github.com/elmindreda/monitool).

**Comment by surafel911** [comment]
Unfortunately, I'm in college right now and away from my setup. I'll be back home during the weekend and I'll run the test.

Sorry for the inconvenience.

**Comment by surafel911** [comment]
Name: Acer E202HL (Digital) (primary)
Current mode: 1600 x 900 x 24 (8 8 8) 60 Hz
Virtual position: 1920 0
Physical size: 443 x 249 mm (91.74 dpi)
Modes:
  0: 640 x 480 x 24 (8 8 8) 60 Hz
  1: 640 x 480 x 24 (8 8 8) 72 Hz
  2: 640 x 480 x 24 (8 8 8) 75 Hz
  3: 720 x 480 x 24 (8 8 8) 56 Hz
  4: 720 x 480 x 24 (8 8 8) 60 Hz
  5: 720 x 480 x 24 (8 8 8) 72 Hz
  6: 720 x 480 x 24 (8 8 8) 75 Hz
  7: 720 x 576 x 24 (8 8 8) 56 Hz
  8: 720 x 576 x 24 (8 8 8) 60 Hz
  9: 720 x 576 x 24 (8 8 8) 72 Hz
 10: 720 x 576 x 24 (8 8 8) 75 Hz
 11: 800 x 600 x 24 (8 8 8) 56 Hz
 12: 800 x 600 x 24 (8 8 8) 60 Hz
 13: 800 x 600 x 24 (8 8 8) 72 Hz
 14: 800 x 600 x 24 (8 8 8) 75 Hz
 15: 1024 x 768 x 24 (8 8 8) 60 Hz
 16: 1024 x 768 x 24 (8 8 8) 70 Hz
 17: 1024 x 768 x 24 (8 8 8) 75 Hz
 18: 1280 x 720 x 24 (8 8 8) 60 Hz
 19: 1280 x 768 x 24 (8 8 8) 60 Hz
 20: 1152 x 864 x 24 (8 8 8) 75 Hz
 21: 1280 x 800 x 24 (8 8 8) 60 Hz
 22: 1360 x 768 x 24 (8 8 8) 60 Hz
 23: 1366 x 768 x 24 (8 8 8) 60 Hz
 24: 1440 x 900 x 24 (8 8 8) 60 Hz
 25: 1600 x 900 x 24 (8 8 8) 60 Hz (current mode)

**Comment by elmindreda** [comment]
Thanks! Just waiting for the output of [monitool](https://github.com/elmindreda/monitool) then.

**Comment by surafel911** [comment]
I posted the results already, or are you talking about something else?

**Comment by elmindreda** [comment]
Above is the output of the `monitors` program in the GLFW repository. This is a different program.

**Comment by elmindreda** [comment]
I should rename monitool to something less similar to the test program,

**Comment by surafel911** [comment]
Desktop MonitorCount: 2 VirtualScreen: 0,0,3520,1080 RemoteSession: 0
Device Name: "\\.\DISPLAY1" String: "NVIDIA GeForce GTX 750 Ti" State: ACTIVE PRIMARY_DEVICE HorzSize: 477 VertSize: 268
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 640 PelsHeight: 480 DisplayFrequency: 60
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 720 PelsHeight: 480 DisplayFrequency: 56
    Mode Orientation: DEFAULT FixedOutput: STRETCH BitsPerPel: 32 PelsWidth: 720 PelsHeight: 480 DisplayFrequency: 56
    Mode Orientation: DEFAULT FixedOutput: CENTER BitsPerPel: 32 PelsWidth: 720 PelsHeight: 480 DisplayFrequency: 56
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 720 PelsHeight: 480 DisplayFrequency: 60
    Mode Orientation: DEFAULT FixedOutput: STRETCH BitsPerPel: 32 PelsWidth: 720 PelsHeight: 480 DisplayFrequency: 60
    Mode Orientation: DEFAULT FixedOutput: CENTER BitsPerPel: 32 PelsWidth: 720 PelsHeight: 480 DisplayFrequency: 60
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 720 PelsHeight: 576 DisplayFrequency: 56
    Mode Orientation: DEFAULT FixedOutput: STRETCH BitsPerPel: 32 PelsWidth: 720 PelsHeight: 576 DisplayFrequency: 56
    Mode Orientation: DEFAULT FixedOutput: CENTER BitsPerPel: 32 PelsWidth: 720 PelsHeight: 576 DisplayFrequency: 56
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 720 PelsHeight: 576 DisplayFrequency: 60
    Mode Orientation: DEFAULT FixedOutput: STRETCH BitsPerPel: 32 PelsWidth: 720 PelsHeight: 576 DisplayFrequency: 60
    Mode Orientation: DEFAULT FixedOutput: CENTER BitsPerPel: 32 PelsWidth: 720 PelsHeight: 576 DisplayFrequency: 60
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 800 PelsHeight: 600 DisplayFrequency: 56
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 800 PelsHeight: 600 DisplayFrequency: 60
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 1024 PelsHeight: 768 DisplayFrequency: 60
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 1024 PelsHeight: 768 DisplayFrequency: 70
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 1152 PelsHeight: 864 DisplayFrequency: 75
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 1280 PelsHeight: 720 DisplayFrequency: 60
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 1280 PelsHeight: 768 DisplayFrequency: 60
    Mode Orientation: DEFAULT FixedOutput: STRETCH BitsPerPel: 32 PelsWidth: 1280 PelsHeight: 768 DisplayFrequency: 60
    Mode Orientation: DEFAULT FixedOutput: CENTER BitsPerPel: 32 PelsWidth: 1280 PelsHeight: 768 DisplayFrequency: 60
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 1280 PelsHeight: 800 DisplayFrequency: 60
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 1280 PelsHeight: 960 DisplayFrequency: 60
    Mode Orientation: DEFAULT FixedOutput: STRETCH BitsPerPel: 32 PelsWidth: 1280 PelsHeight: 960 DisplayFrequency: 60
    Mode Orientation: DEFAULT FixedOutput: CENTER BitsPerPel: 32 PelsWidth: 1280 PelsHeight: 960 DisplayFrequency: 60
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 1280 PelsHeight: 1024 DisplayFrequency: 60
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 1360 PelsHeight: 768 DisplayFrequency: 60
    Mode Orientation: DEFAULT FixedOutput: STRETCH BitsPerPel: 32 PelsWidth: 1360 PelsHeight: 768 DisplayFrequency: 60
    Mode Orientation: DEFAULT FixedOutput: CENTER BitsPerPel: 32 PelsWidth: 1360 PelsHeight: 768 DisplayFrequency: 60
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 1366 PelsHeight: 768 DisplayFrequency: 60
    Mode Orientation: DEFAULT FixedOutput: STRETCH BitsPerPel: 32 PelsWidth: 1366 PelsHeight: 768 DisplayFrequency: 60
    Mode Orientation: DEFAULT FixedOutput: CENTER BitsPerPel: 32 PelsWidth: 1366 PelsHeight: 768 DisplayFrequency: 60
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 1600 PelsHeight: 900 DisplayFrequency: 59
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 1600 PelsHeight: 900 DisplayFrequency: 60
    Mode Orientation: DEFAULT FixedOutput: STRETCH BitsPerPel: 32 PelsWidth: 1600 PelsHeight: 900 DisplayFrequency: 59
    Mode Orientation: DEFAULT FixedOutput: STRETCH BitsPerPel: 32 PelsWidth: 1600 PelsHeight: 900 DisplayFrequency: 60
    Mode Orientation: DEFAULT FixedOutput: CENTER BitsPerPel: 32 PelsWidth: 1600 PelsHeight: 900 DisplayFrequency: 59
    Mode Orientation: DEFAULT FixedOutput: CENTER BitsPerPel: 32 PelsWidth: 1600 PelsHeight: 900 DisplayFrequency: 60
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 1600 PelsHeight: 1024 DisplayFrequency: 59
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 1600 PelsHeight: 1024 DisplayFrequency: 60
    Mode Orientation: DEFAULT FixedOutput: STRETCH BitsPerPel: 32 PelsWidth: 1600 PelsHeight: 1024 DisplayFrequency: 59
    Mode Orientation: DEFAULT FixedOutput: STRETCH BitsPerPel: 32 PelsWidth: 1600 PelsHeight: 1024 DisplayFrequency: 60
    Mode Orientation: DEFAULT FixedOutput: CENTER BitsPerPel: 32 PelsWidth: 1600 PelsHeight: 1024 DisplayFrequency: 59
    Mode Orientation: DEFAULT FixedOutput: CENTER BitsPerPel: 32 PelsWidth: 1600 PelsHeight: 1024 DisplayFrequency: 60
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 1680 PelsHeight: 1050 DisplayFrequency: 59
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 1680 PelsHeight: 1050 DisplayFrequency: 60
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 2715 PelsHeight: 1527 DisplayFrequency: 60
    Mode Orientation: DEFAULT FixedOutput: STRETCH BitsPerPel: 32 PelsWidth: 2715 PelsHeight: 1527 DisplayFrequency: 60
    Mode Orientation: DEFAULT FixedOutput: CENTER BitsPerPel: 32 PelsWidth: 2715 PelsHeight: 1527 DisplayFrequency: 60
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 1920 PelsHeight: 1080 DisplayFrequency: 60
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 1440 PelsHeight: 900 DisplayFrequency: 60
Device Name: "\\.\DISPLAY2" String: "NVIDIA GeForce GTX 750 Ti" State: ACTIVE HorzSize: 443 VertSize: 249
    Device Name: "\\.\DISPLAY2\Monitor0" String: "Acer E202HL (Digital)" State: ACTIVE HorzSize: 0 VertSize: 0
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 1600 PelsHeight: 900 DisplayFrequency: 60
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 640 PelsHeight: 480 DisplayFrequency: 60
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 640 PelsHeight: 480 DisplayFrequency: 72
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 640 PelsHeight: 480 DisplayFrequency: 75
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 720 PelsHeight: 480 DisplayFrequency: 56
    Mode Orientation: DEFAULT FixedOutput: STRETCH BitsPerPel: 32 PelsWidth: 720 PelsHeight: 480 DisplayFrequency: 56
    Mode Orientation: DEFAULT FixedOutput: CENTER BitsPerPel: 32 PelsWidth: 720 PelsHeight: 480 DisplayFrequency: 56
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 720 PelsHeight: 480 DisplayFrequency: 60
    Mode Orientation: DEFAULT FixedOutput: STRETCH BitsPerPel: 32 PelsWidth: 720 PelsHeight: 480 DisplayFrequency: 60
    Mode Orientation: DEFAULT FixedOutput: CENTER BitsPerPel: 32 PelsWidth: 720 PelsHeight: 480 DisplayFrequency: 60
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 720 PelsHeight: 480 DisplayFrequency: 72
    Mode Orientation: DEFAULT FixedOutput: STRETCH BitsPerPel: 32 PelsWidth: 720 PelsHeight: 480 DisplayFrequency: 72
    Mode Orientation: DEFAULT FixedOutput: CENTER BitsPerPel: 32 PelsWidth: 720 PelsHeight: 480 DisplayFrequency: 72
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 720 PelsHeight: 480 DisplayFrequency: 75
    Mode Orientation: DEFAULT FixedOutput: STRETCH BitsPerPel: 32 PelsWidth: 720 PelsHeight: 480 DisplayFrequency: 75
    Mode Orientation: DEFAULT FixedOutput: CENTER BitsPerPel: 32 PelsWidth: 720 PelsHeight: 480 DisplayFrequency: 75
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 720 PelsHeight: 576 DisplayFrequency: 56
    Mode Orientation: DEFAULT FixedOutput: STRETCH BitsPerPel: 32 PelsWidth: 720 PelsHeight: 576 DisplayFrequency: 56
    Mode Orientation: DEFAULT FixedOutput: CENTER BitsPerPel: 32 PelsWidth: 720 PelsHeight: 576 DisplayFrequency: 56
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 720 PelsHeight: 576 DisplayFrequency: 60
    Mode Orientation: DEFAULT FixedOutput: STRETCH BitsPerPel: 32 PelsWidth: 720 PelsHeight: 576 DisplayFrequency: 60
    Mode Orientation: DEFAULT FixedOutput: CENTER BitsPerPel: 32 PelsWidth: 720 PelsHeight: 576 DisplayFrequency: 60
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 720 PelsHeight: 576 DisplayFrequency: 72
    Mode Orientation: DEFAULT FixedOutput: STRETCH BitsPerPel: 32 PelsWidth: 720 PelsHeight: 576 DisplayFrequency: 72
    Mode Orientation: DEFAULT FixedOutput: CENTER BitsPerPel: 32 PelsWidth: 720 PelsHeight: 576 DisplayFrequency: 72
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 720 PelsHeight: 576 DisplayFrequency: 75
    Mode Orientation: DEFAULT FixedOutput: STRETCH BitsPerPel: 32 PelsWidth: 720 PelsHeight: 576 DisplayFrequency: 75
    Mode Orientation: DEFAULT FixedOutput: CENTER BitsPerPel: 32 PelsWidth: 720 PelsHeight: 576 DisplayFrequency: 75
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 800 PelsHeight: 600 DisplayFrequency: 56
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 800 PelsHeight: 600 DisplayFrequency: 60
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 800 PelsHeight: 600 DisplayFrequency: 72
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 800 PelsHeight: 600 DisplayFrequency: 75
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 1024 PelsHeight: 768 DisplayFrequency: 60
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 1024 PelsHeight: 768 DisplayFrequency: 70
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 1024 PelsHeight: 768 DisplayFrequency: 75
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 1152 PelsHeight: 864 DisplayFrequency: 75
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 1280 PelsHeight: 720 DisplayFrequency: 60
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 1280 PelsHeight: 768 DisplayFrequency: 60
    Mode Orientation: DEFAULT FixedOutput: STRETCH BitsPerPel: 32 PelsWidth: 1280 PelsHeight: 768 DisplayFrequency: 60
    Mode Orientation: DEFAULT FixedOutput: CENTER BitsPerPel: 32 PelsWidth: 1280 PelsHeight: 768 DisplayFrequency: 60
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 1280 PelsHeight: 800 DisplayFrequency: 60
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 1360 PelsHeight: 768 DisplayFrequency: 60
    Mode Orientation: DEFAULT FixedOutput: STRETCH BitsPerPel: 32 PelsWidth: 1360 PelsHeight: 768 DisplayFrequency: 60
    Mode Orientation: DEFAULT FixedOutput: CENTER BitsPerPel: 32 PelsWidth: 1360 PelsHeight: 768 DisplayFrequency: 60
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 1366 PelsHeight: 768 DisplayFrequency: 60
    Mode Orientation: DEFAULT FixedOutput: STRETCH BitsPerPel: 32 PelsWidth: 1366 PelsHeight: 768 DisplayFrequency: 60
    Mode Orientation: DEFAULT FixedOutput: CENTER BitsPerPel: 32 PelsWidth: 1366 PelsHeight: 768 DisplayFrequency: 60
    Mode Orientation: DEFAULT BitsPerPel: 32 PelsWidth: 1440 PelsHeight: 900 DisplayFrequency: 60
    Mode Orientation: DEFAULT FixedOutput: STRETCH BitsPerPel: 32 PelsWidth: 1440 PelsHeight: 900 DisplayFrequency: 60
    Mode Orientation: DEFAULT FixedOutput: CENTER BitsPerPel: 32 PelsWidth: 1440 PelsHeight: 900 DisplayFrequency: 60
Device Name: "\\.\DISPLAY3" String: "NVIDIA GeForce GTX 750 Ti" State: MODESPRUNED HorzSize: 0 VertSize: 0
Device Name: "\\.\DISPLAY4" String: "NVIDIA GeForce GTX 750 Ti" State: MODESPRUNED HorzSize: 0 VertSize: 0
Monitor Device: "\\.\DISPLAY1" Rect: 0,0,1920,1080 PRIMARY
Monitor Device: "\\.\DISPLAY2" Rect: 1920,0,3520,900

**Comment by elmindreda** [comment]
Thank you! That seems to explain every part of the behavior you describe.

GLFW isn't listing your actual primary monitor because it doesn't have a display device (e.g.  `"\\.\DISPLAY1\Monitor0"`), but it doesn't switch to using adapter devices (e.g. `"\\.\DISPLAY1"`) for GLFW monitors because the other adapter device _does_ have one. Since the convention in GLFW is that the first monitor in the array is the primary one, the display device of the second adapter device implicitly becomes primary.

At this point I would like to know more about your "Emacs" monitor? What is it? Hardware or emulated? How is it connected? Is the Windows display dialog and/or device manager aware of it? If so, what is is called there?

**Comment by surafel911** [comment]
I'm not home right now. College... But I do have someone at home that can get the information later in the day.

**Comment by elmindreda** [comment]
No worries! I've been able to start working based on all the information you've already provided.

**Comment by elmindreda** [comment]
This should be fixed now with 0df9cc2fc516220eff62ddd838352f92e9c24aa3, based on the information above. If not, please report it here and we'll re-open the issue.

**Comment by surafel911** [comment]
For now, all I could do was TeamView my desktop at home. It's a hardware E-Machine monitor with a VGA connection straight into the graphics card. When I go on Device Manager and look in monitors, it just says: PnP-Monitor (Standard). So Windows is aware of it, it just may be some weird brand or something because not all of the information is showing up on Windows.

Hope this helps.

**Comment by elmindreda** [comment]
It does, thank you. It also makes me even more hopeful that this has been resolved.

**Comment by surafel911** [comment]
Glad to be of help.

So will I be able to get this fix in the next update or can I just get it straight off of the github? if the update is coming soon I don't mind waiting.

**Comment by elmindreda** [comment]
You can get it right now if you want. It's in the master branch, which shouldn't be less stable than the previous release. It'll be in the next release but I don't know yet when that'll be out.
