### ISSUE TITLE
segfault when glXGetClientString return null

### ISSUE THREAD

**Issue by warmonkey** [glfw/glfw#962]
(gdb) run
Starting program: /home/sa/grc-modules/gr-fosphor/lib/fosphor/main /home/sa/name-f2.300000e+09-s2.000000e+07-t20170223134900.cfile
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Program received signal SIGSEGV, Segmentation fault.
__strcmp_ssse3 () at ../sysdeps/x86_64/multiarch/../strcmp.S:209
209	../sysdeps/x86_64/multiarch/../strcmp.S: no such file or directory
(gdb) backtrace
#0  __strcmp_ssse3 () at ../sysdeps/x86_64/multiarch/../strcmp.S:209
#1  0x00007ffff792aca1 in chooseFBConfig () from /usr/local/lib/libglfw.so.3
#2  0x00007ffff792c331 in _glfwChooseVisualGLX ()
   from /usr/local/lib/libglfw.so.3
#3  0x00007ffff79278c2 in _glfwPlatformCreateWindow ()
   from /usr/local/lib/libglfw.so.3
#4  0x00007ffff791f061 in glfwCreateWindow () from /usr/local/lib/libglfw.so.3
#5  0x0000000000403761 in glfw_init () at main.c:344
#6  main (argc=<optimized out>, argv=<optimized out>) at main.c:421
(gdb) quit

find out that glXGetClientString(_glfw.x11.display, GLX_VENDOR) returns NULL 
(on glxcontext.c line 61)
application get segfault without error info.
**fix: add NULL pointer detect**

// HACK: This is a (hopefully temporary) workaround for Chromium
//       (VirtualBox GL) not setting the window bit on any GLXFBConfigs
vendor = glXGetClientString(_glfw.x11.display, GLX_VENDOR);
if (**vendor &&** strcmp(vendor, "Chromium") == 0)
    trustWindowBit = GLFW_FALSE;

**Comment by elmindreda** [comment]
According to the spec, glXGetClientString should not return NULL when passed a valid token. However, a workaround has already been added with 9cd378caa735214d715e1e4a456750d8e1bb72b5.
