### ISSUE TITLE
Any window events while running a GLFW application causes 100% CPU usage in Ubuntu 16

### ISSUE THREAD

**Issue by birgersp** [glfw/glfw#965]
When running a GLFW application, changing/moving/resizing any window in the desktop environment causes X Window server to use 100% CPU.

Operating system: Ubuntu 16.04
Graphics card: NVIDIA K2200, driver nvidia-375 (open source)

The code I'm building and running is from the GLFW3 getting started-page: 
http://www.glfw.org/docs/3.0/quick.html

**Comment by elmindreda** [comment]
What version of GLFW are you using?

**Comment by birgersp** [comment]
Version 3, installed from here:
https://launchpad.net/ubuntu/+source/glfw3

**Comment by elmindreda** [comment]
Try the [current version](http://www.glfw.org/docs/latest/quick.html) of the example.

**Comment by birgersp** [comment]
Tried the current version of the example, I removed the line
```
gladLoadGLLoader((GLADloadproc) glfwGetProcAddress);
```

Same problem

**Comment by elmindreda** [comment]
What is the name of the process that's using a whole CPU core? Does it happen only during resizing and moving? What is the output of `glfwinfo`?

**Comment by birgersp** [comment]
The process is named `Xorg`.

I just ran the same application on Manjaro XFCE, and the problem does not occur on this installation.

**Comment by elmindreda** [comment]
What is the output of `glfwinfo`?

**Comment by OverclockedSanic** [comment]
Can confirm, same thing happens on my system

Linux Mint Cinnamon 19.1
Kernel 4.18.0-15
Nvidia GTX 960 driver 390.77

Interestingly though, it also affects other , non-glfw applications, such as `glxgears`, which means it's probably not a glfw-specific issue.

**Comment by OverclockedSanic** [comment]
adding `glfwSwapInterval(0);` before the loop seems to have done the trick.
