### ISSUE TITLE
Can we use glfw without screen? 

### ISSUE THREAD

**Issue by peterpans01** [glfw/glfw#969]
I know this question may be quite strange for you guys. But we have an application link to glfw. We need to run it without screen. But as you know, without screen, the glfw will report the error. Is there a way to go around this requirement? 

Many thanks.

**Comment by elmindreda** [comment]
The last few releases removed that requirement. What version are you using?

**Comment by elmindreda** [comment]
GLFW 3.1.2 was the first release to remove that requirement.

**Comment by elmindreda** [comment]
This was fixed three releases ago.
