### ISSUE TITLE
Confusion error message when using glfw with no monitors

### ISSUE THREAD

**Issue by whitespacer** [glfw/glfw#972]
We use glfw to render to off-screen render target, and we do it on machine which don't have any monitors. During initialization glfw calls method glfwPollMonitorsX11, which writes error message 

> X11: RandR monitor support seems broken

I think this error message is confusing. It is perfectly okay to have zero monitors, RandR is also working okay.

**Comment by Shimmen** [comment]
This was last discussed just hours ago in #969. Is anything in that thread helpful?

**Comment by whitespacer** [comment]
It is similar problem, however not the same. I am talking about master branch of glfw. I can perfectly use glfw to work without monitors. However I can see error message in such configuration. I think that reporting 'X11: RandR monitor support seems broken' in case when user doesn't have monitors is confusing.

**Comment by elmindreda** [comment]
@whitespacer What is the output of `xrandr` on that system?

**Comment by whitespacer** [comment]
@elmindreda, output is following:
```
sudo xrandr -v
xrandr program version       1.5.0
Can't open display
```

After reading this output I am not sure that X11 is configured correctly... To make nvidia driver work without monitors I have following xorg conf (otherwise nvidia driver refuses to load):
```
Section "Screen"
  Identifier "Screen0"
  Option "AllowEmptyInitialConfiguration" "on"
EndSection
```

**Comment by elmindreda** [comment]
The criteria for disabling RandR have been narrowed with 5fe4dfb511e12b954f9fba11d989df48f5f203fd.
