### ISSUE TITLE
Default state of Caps Lock

### ISSUE THREAD

**Issue by sasmaster** [glfw/glfw#974]
Hi Guys.Is there an option to check what state the caps lock is in before it's triggered?I haven't found any method that tells that,except using Win API directly.The problem is,when I press CapsLock,it has already a state 'active/non active' ,and I need to know it to identify correctly the state after the button has been pressed.Thanks.

**Comment by elmindreda** [comment]
There isn't yet, but there will be soon. See #946.

Usually checking the lock key state isn't what one wants, though. What will you use the state for?

**Comment by elmindreda** [comment]
Please see #946 for updates on this feature.
