### ISSUE TITLE
support android opengl ES 2.0? how to build ?

### ISSUE THREAD

**Issue by liulover5** [glfw/glfw#976]
1. support android opengl ES 2.0 or 3.0?  
2. how to build for andorid?
3. use glfw with glew support android?

**Comment by felipefs** [comment]
Android support was already mentioned here https://github.com/glfw/glfw/issues/611

As far as I know, there's no android implementation in this repo, maybe in some fork. I'm not sure how a mobile port would work if not rewriting the whole library from bottom to top. Inputs are handled different, creation of windows (display) is completely different.

Even with the NDK, a minimal application in Java is still required to make interface with the system.

**Comment by liulover5** [comment]
tks for answers , android  mobile（TV ,arm board） is linux ,which diffrent is EGL window , and cut of some openGL API for arm(you donot care). EGL window using android surface interface will be OK for handle ,about input same sa linux.

 whith NDK, without any of java ,we just use NDK's gcc make etc. same as linux and osx, android devices can run console aplay  draw openGL ES UI
who want  to use for java apk ,just expose ti's c jni api will be fine.
i am still look forward ,Forgive me for my low eng level...

**Comment by elmindreda** [comment]
@liulover5 As @felipefs said, there is currently no support for Android. Perhaps check out [GLFM](https://github.com/brackeen/glfm) for a GLFW-like library that does support Android.
