### ISSUE TITLE
Potential sRGB bug on Mac

### ISSUE THREAD

**Issue by xslattery** [glfw/glfw#978]
I believe I may have found a potential bug related to using a sRGB framebuffer on Mac.
I am using the latest version of GLFW (3.2.1)
My OS is MacOS Sierra 10.12.3 - current hardware is the new 2016 touchbar MacBook Pro 13"

When using a sRGB enabled framebuffer I have an issue when in fullscreen. For an unknown reason when switching away from then back to the fullscreen window, upon arrival the window gets a red overlay that encompasses the entire viewport. This red overlay the begins to quickly flash repeatedly.

If I move my cursor to expose the toolbar at the top of the screen the red flashing goes away.

Related to this, when I create an open file dialog box, if the box overlaps with the window the area under the box will have the same issue whether is it in fullscreen or not.

I have narrowed this down to being related to sRGB because if I remove the code:
```c
glfwWindowHint( GLFW_SRGB_CAPABLE, GLFW_TRUE );
```
and
```c
glEnable(GL_FRAMEBUFFER_SRGB);
```
The issue goes away.

I am not sure if it is an issue related to my code, glfw itself, my drivers, or something else entirely.
Assistance with this would be greatly appreciated.

**_EDIT:_** Upon further testing, this issue seems to arise because of the retina display on my laptop. I created a very similar window using SDL as the library and the same issue arises. However I have now learned that if I disable retina scaling the issue goes away. I know this because I was able to test the application on a non retina iMac and there was no issue. Because only applications I have been developing have been having this issue I have to believe that there is something with GLFW that can be done to fix the issue.

Here is a link to a video of the issue:
https://youtu.be/OUOE4t9tYxU
Apologies for the quality of the video, for some reason when I try to record my screen using quicktime the flashing red overlay does not show up.

Here is the Code that results in the issue:
```c
int main () {

	GLFWwindow* window_ptr;
	int window_width, window_height;
	int gl_viewport_width, gl_viewport_height;

	if ( glfwInit() ) {
		glfwWindowHint( GLFW_CONTEXT_VERSION_MAJOR, 3 );
		glfwWindowHint( GLFW_CONTEXT_VERSION_MINOR, 3 );
		glfwWindowHint( GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE );
		glfwWindowHint( GLFW_OPENGL_FORWARD_COMPAT, GLFW_TRUE );
		glfwWindowHint( GLFW_RESIZABLE, GLFW_TRUE );
		glfwWindowHint( GLFW_SRGB_CAPABLE, GLFW_TRUE );

		window_ptr = glfwCreateWindow( DEFAULT_WINDOW_WIDTH, DEFAULT_WINDOW_HEIGHT, "GLFW Window", 0, 0 );
		
		if ( !window_ptr ) {
			glfwTerminate();
			return -1;
		} else {
			glfwMakeContextCurrent( window_ptr );
			glfwGetWindowSize( window_ptr, &window_width, &window_height );
			glfwGetFramebufferSize( window_ptr, &gl_viewport_width, &gl_viewport_height );	

			glfwSwapInterval( 1 );

			glViewport( 0, 0, gl_viewport_width, gl_viewport_height );
			glEnable( GL_DEPTH_TEST );
			glCullFace( GL_BACK );
			glEnable( GL_CULL_FACE );
			glEnable(GL_BLEND);
			glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
			
			glEnable(GL_FRAMEBUFFER_SRGB);
			
			glClearColor( 0.5f, 0.5f, 0.5f, 1.0f );	
		}
	}

	if ( window_ptr ) {
		while ( !glfwWindowShouldClose( window_ptr ) ) { 
			glfwPollEvents();
			glClear( GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT );
			glfwSwapBuffers( window_ptr );
		}
		glfwTerminate();
	}

	return 0;
}
```

**Comment by elmindreda** [comment]
I don't know what is causing the flashing, but `GLFW_SRGB_CAPABLE` does nothing on macOS as all framebuffers on macOS are sRGB capable.

**Comment by elmindreda** [comment]
If you switch to the current master from this repository then you'll be able to verify on a single machine whether Retina scaling is the issue, as there is now the `GLFW_COCOA_RETINA_FRAMEBUFFER` macOS specific window hint.

**Comment by xslattery** [comment]
I switched to the current master and disabled the retina scaling using:
```c
glfwWindowHint( GLFW_COCOA_RETINA_FRAMEBUFFER, GL_FALSE );
```
This fixes the problem. However now with retina scaling disabled everything looks pretty bad.

From This I believe that retina scaling is definitely the issue. However the issue only arrises when both retina scaling and srgb are enabled together.

_( For reference I did similar testing on the SDL library and the exact same problem exists with retina scaling and srgb. )_

**Comment by xslattery** [comment]
I was able to capture a screenshot of what the window is meant to look like compared to what it is actually like.
**_Correct_:**
<img width="438" alt="screen shot 2017-03-28 at 3 09 29 pm" src="https://cloud.githubusercontent.com/assets/8789807/24388794/d17ae824-13c8-11e7-985e-0a068784c0e0.png">
_**Problem:**_
<img width="447" alt="screen shot 2017-03-28 at 3 09 55 pm" src="https://cloud.githubusercontent.com/assets/8789807/24388793/d10d4170-13c8-11e7-9452-3f211e4b5610.png">

**Comment by elmindreda** [comment]
That's a really weird bug.  It may be worth [contacting Apple](https://developer.apple.com/bug-reporting/) about it.

**Comment by xslattery** [comment]
I would like to know if the issue is related to my machine alone. (2016 MacBook Pro 13" w/ touch-bar)
If there is anyone with the same machine that can test to see if they have the same issue it would be greatly appreciated. (I can send a .app with instructions with how to reproduce the bug.)

Otherwise I may end up backing up my machine, then factory resetting it to see if the issue is still there.

**Comment by shurcooL** [comment]
> I would like to know if the issue is related to my machine alone. (2016 MacBook Pro 13" w/ touch-bar)
> If there is anyone with the same machine that can test to see if they have the same issue it would be greatly appreciated.

Would it be helpful to know if someone with a _different_ Mac (e.g., a Late 2011 15" MacBook Pro) has the same issue? Or is it already known not to affect other models?

**Comment by xslattery** [comment]
Here is a link to a dropbox folder. Included is a .app with both written and video instruction for how to reproduce the bug:
https://www.dropbox.com/sh/fbw506v7jum97yi/AAAm5Qgu9sgxWengl1l8AEGGa?dl=0

Any help at all would be great!

Personally I have tested it on a non retina iMac as well and the issue does not appear. I believe this is because there is no scaling.

The  bug is very odd in that it only appears when switching away from then back to a fullscreen window by swiping on the trackpad. Or by swiping to expose Mission control then going back to the fullscreen window.

**Comment by shurcooL** [comment]
> Here is a link to a dropbox folder. Included is a .app with both written and video instruction for how to reproduce the bug

Is it possible to provide something I can build from source? I'd prefer to be able to do that. The video and text files are helpful.

**Comment by xslattery** [comment]
Sorry I can't provide anything else. This isn't a problem specifically associated to one project. Any glfw project that I run with retina scaling and srgb results in the issue.

**Comment by shurcooL** [comment]
I'll see if I can try it on the snippet you shared in the original issue.

> Here is the Code that results in the issue

**Comment by elmindreda** [comment]
FWIW, I tried to reproduce it on my 2013 MBP with a modified version of one of the examples but had no success.

**Comment by xslattery** [comment]
I'm guessing that it is an issue with my laptop alone. I'll wait and see if anyone in the future has a similar issue. Until then I think I'll just work around it.

**Comment by xslattery** [comment]
I just factory reset by laptop (2016 MacBook Pro) and the issue no longer seems to be there. It appears that there must of been something going wrong behind the scenes that is now fixed.

Thanks for the help!

**Comment by elmindreda** [comment]
@xslattery Glad to hear it! Is it all right to close this now?

**Comment by xslattery** [comment]
Yep.
