### ISSUE TITLE
glfwGetKeyName depends on current locale

### ISSUE THREAD

**Issue by db47h** [glfw/glfw#981]
Steps to reproduce:

- switch the keyboard to some variant of French AZERTY
- run a program that calls `glfwGetKeyName(GLFW_KEY_2, 0)`

This should return "é". On a system with locale fr_FR.UTF-8, this should be "\xC3\xA9" but it returns "\xE9", the same character but in ISO8859-15 encoding (this is a limitation of `XkbTranslateKeySym`).

I would expect `glfwGetKeyName` to return unicode keynames across all platforms, regardless of the user's locale.

This is related to #837.

An easy solution is to use the a public domain keysym dataset compiled by Markus G. Kuhn ([C code](http://www.cl.cam.ac.uk/~mgk25/ucs/keysym2ucs.c)).

**Comment by db47h** [comment]
I can send a PR if that helps, but there are a few things that need to be discussed:

- Since the function documentation does not specify any encoding, fixing this in GLFW 3.x may break  existing code that rely on the current behavior.
- Is the proposed solution acceptable (the linked code is in the public domain)?

**Comment by elmindreda** [comment]
> I would expect `glfwGetKeyName` to return unicode keynames across all platforms, regardless of the user's locale.

Agreed. This is a bug. Since your specific locale is UTF-8 you should get UTF-8 key names if you do `setlocale(LC_ALL, "");` at the beginning of your program, but that's a workaround and not a proper solution.

> Is the proposed solution acceptable (the linked code is in the public domain)?

Kuhn's data and code are already available in `src/xkb_unicode.c` and for regular printable keys this approach would work well, but it doesn't handle dead keys without additional work. I will happily merge a solution based on that data if it also handles dead keys.

> Since the function documentation does not specify any encoding, fixing this in GLFW 3.x may be considered a breaking change.

I consider it a bug that the documentation doesn't mention the encoding of the returned key name. The string should be UTF-8 as are all other public strings in GLFW, and this is what is returned on other platforms.

**Comment by db47h** [comment]
Regarding dead keys, since `glfwGetKeyName` is primarily used to provide feedback to the user about which key to press (as shown in the function example), how about returning the symbol printed on the user's physical key? Most of the times, that's the equivalent of the key sequence `<dead_key> + <space>`. For example, on a french keyboard there's `XK_dead_circumflex` for which glfwGetKeyName already prints as `^`.

Supporting utf-8 output and dead keys would be a matter of adding the needed mappings to `src/xkb_unicode.c`. Here's the list of dead keys from `/usr/include/X11/keysymdef.h`:

```C
#define XK_dead_grave                    0xfe50
#define XK_dead_acute                    0xfe51
#define XK_dead_circumflex               0xfe52
#define XK_dead_tilde                    0xfe53
#define XK_dead_perispomeni              0xfe53  /* alias for dead_tilde */
#define XK_dead_macron                   0xfe54
#define XK_dead_breve                    0xfe55
#define XK_dead_abovedot                 0xfe56
#define XK_dead_diaeresis                0xfe57
#define XK_dead_abovering                0xfe58
#define XK_dead_doubleacute              0xfe59
#define XK_dead_caron                    0xfe5a
#define XK_dead_cedilla                  0xfe5b
#define XK_dead_ogonek                   0xfe5c
#define XK_dead_iota                     0xfe5d
#define XK_dead_voiced_sound             0xfe5e
#define XK_dead_semivoiced_sound         0xfe5f
#define XK_dead_belowdot                 0xfe60
#define XK_dead_hook                     0xfe61
#define XK_dead_horn                     0xfe62
#define XK_dead_stroke                   0xfe63
#define XK_dead_abovecomma               0xfe64
#define XK_dead_psili                    0xfe64  /* alias for dead_abovecomma */
#define XK_dead_abovereversedcomma       0xfe65
#define XK_dead_dasia                    0xfe65  /* alias for dead_abovereversedcomma */
#define XK_dead_doublegrave              0xfe66
#define XK_dead_belowring                0xfe67
#define XK_dead_belowmacron              0xfe68
#define XK_dead_belowcircumflex          0xfe69
#define XK_dead_belowtilde               0xfe6a
#define XK_dead_belowbreve               0xfe6b
#define XK_dead_belowdiaeresis           0xfe6c
#define XK_dead_invertedbreve            0xfe6d
#define XK_dead_belowcomma               0xfe6e
#define XK_dead_currency                 0xfe6f

/* extra dead elements for German T3 layout */
#define XK_dead_lowline                  0xfe90
#define XK_dead_aboveverticalline        0xfe91
#define XK_dead_belowverticalline        0xfe92
#define XK_dead_longsolidusoverlay       0xfe93

/* dead vowels for universal syllable entry */
#define XK_dead_a                        0xfe80
#define XK_dead_A                        0xfe81
#define XK_dead_e                        0xfe82
#define XK_dead_E                        0xfe83
#define XK_dead_i                        0xfe84
#define XK_dead_I                        0xfe85
#define XK_dead_o                        0xfe86
#define XK_dead_O                        0xfe87
#define XK_dead_u                        0xfe88
#define XK_dead_U                        0xfe89
#define XK_dead_small_schwa              0xfe8a
#define XK_dead_capital_schwa            0xfe8b

#define XK_dead_greek                    0xfe8c
```

Obviously, We can trim down the list to those that only exist as physical keys.

**Comment by db47h** [comment]
Sorry, I missed the latest update to the doc, so yes, that's the way to go. If anyone can help in trimming down the list of dead keys or provide the needed diacritics for non-latin keyboards, I'd appreciate.

**Comment by db47h** [comment]
I'm still missing a few mappings but none of them seem to be used on any keyboard layout with no modifier keys (i.e. the GLFW key callback will never see them). Among those are some like `XK_dead_belowdot` that could be mapped to combining symbols, which need at least a leading space to display properly. I don't think keeping them is worth it.

**Comment by elmindreda** [comment]
@db47h That looks really promising! I have a holiday coming up, but I'll review and test as soon as I can.
