### ISSUE TITLE
State of Mir support after recent announcement?

### ISSUE THREAD

**Issue by shurcooL** [glfw/glfw#984]
This issue is to share a recent announcement, and to ask a question.

According to a recent blog post by Mark Shuttleworth at https://insights.ubuntu.com/2017/04/05/growing-ubuntu-for-cloud-and-iot-rather-than-phone-and-convergence/:

> I’m writing to let you know that we will end our investment in Unity8, the phone and convergence shell. We will shift our default Ubuntu desktop back to GNOME for Ubuntu 18.04 LTS.

And from https://arstechnica.com/information-technology/2017/04/ubuntu-unity-is-dead-desktop-will-switch-back-to-gnome-next-year/:

> Canonical's work on creating a new desktop display server, Mir, has also been slow.
>
> By switching to GNOME, Canonical is also giving up on Mir and moving to the Wayland display server, another contender for replacing the X window system. Given the separate development paths of Mir and Wayland, "we have no real choice but to use Wayland when Ubuntu switches to GNOME by default," Hall told Ars. "Using Mir simply isn't an option we have."

My question is, how is GLFW affected?

**Comment by elmindreda** [comment]
My initial impression is that it can't be bad for GLFW.

If Mir becomes a healthy FOSS project then we already have the solid and improving alpha-stage backend by @BrandonSchaefer. If Mir fades away then it's a five minute job to remove anything related to it from GLFW and the future Unix window system auto-detection logic becomes simpler.

**Comment by shurcooL** [comment]
Thanks for answering the question. Shall I close the issue, or do you want to keep it open to track anything?

**Comment by elmindreda** [comment]
@shurcooL I don't. If anyone wants to continue the discussion then we can re-open it.

**Comment by linkmauve** [comment]
As of #1336, Mir support has been removed, their developers instead recommend to use the Wayland protocol with Mir.
