### ISSUE TITLE
Backspace not reported to character callbacks

### ISSUE THREAD

**Issue by Cooldude234** [glfw/glfw#993]
I've implemented a text field into my application using a character callback. This way I can use the system's settings for how fast characters should repeat when held down.This is fine 'n dandy and all, however when it comes down to text function keys such as backspace and the advance line key (enter) I cannot use the character callback and I am forced to use the glfwGetKey() function which doesn't have repeat functionality.

So my question is how can I get backspace (and other related keys) to repeat at the same rate as the systems repeat key rate?

**Comment by elmindreda** [comment]
Use the [key callback](http://www.glfw.org/docs/latest/input_guide.html#input_key) for keys like Enter and Backspace.

**Comment by Cooldude234** [comment]
So is it supposed to report keys like enter, backspace and tab? Because it doesn't.
Windows 7 srv pack 1, using a us standard keyboard (Logitech g15).
Switching layout modes in windows doesn't fix the issue either. Neither Canadian multilingual or Canadian french or US layouts work.

I can poll for the press and unpressed states of the keys with the glfwGetKey() function.

**Comment by tombsar** [comment]
> So is it supposed to report keys like enter, backspace and tab? Because it doesn't.

Can I just confirm you mean the callback set with `glfwSetKeyCallback` rather than `glfwSetCharCallback`? If the keys that you mention are not being passed through to the key callback, something is *seriously* broken.

**Comment by felipefs** [comment]
@Cooldude234, are you using the callback for ```glfwSetKeyCallback``` like this? This way should work fine.
```c
static void key_callback(GLFWwindow* window, int key, int scancode, int action, int mods)
{
    if (key == GLFW_KEY_ENTER && action == GLFW_PRESS)
        printf("Enter\n");
    if (key == GLFW_KEY_TAB && action == GLFW_PRESS)
        printf("Tab\n");
    if (key == GLFW_KEY_BACKSPACE && action == GLFW_PRESS)
        printf("Backspace\n");
}
```

**Comment by Cooldude234** [comment]
> Can I just confirm you mean the callback set with glfwSetKeyCallback rather than glfwSetCharCallback? If the keys that you mention are not being passed through to the key callback, something is seriously broken.
Dang, the documentation has got me again. I miss-read glfwSetKeyCallback with glfwSetCharCallback.

Okay I updated my code to utilize that callback instead and it seems to work fine. It's always the stupidest things that sets one back.
